### ISSUE TITLE
Add bookmark that goes to My Shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1126]
On install we should add a top-level bookmark item to point to My Shots, ideally next to View Pocket list.

**Comment by ianb** [comment]
Here's one pattern for this: [from Pocket](https://github.com/mozilla/gecko-dev/blob/b8f98ffe9f26c25896f6d853d66785661f8cb57e/browser/extensions/pocket/bootstrap.js#L436)

**Comment by brampitoyo** [comment]
+1 to this idea. We can use the Pageshot icon that Bryan had designed as an icon for our bookmark mtenu item.

**Comment by ianb** [comment]
Maybe a lazier idea than what Pocket does is to use the [bookmark API](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/places_bookmarks) and a hidden pref.  On startup if the pref is false, install the bookmark(s) and set the pref true.  On uninstall (with appropriate [reason](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload#reason)) try to remove the bookmarks and pref.  That should keep the bookmarks from reappearing (e.g., if the user deletes or moves them).

**Comment by ianb** [comment]
This is handled by the Library now:

![image](https://user-images.githubusercontent.com/44390/29896552-18f512ac-8da3-11e7-95af-4502c7f9e56f.png)
