### ISSUE TITLE
Display expiration dates on /shots page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1257]
https://pageshot.dev.mozaws.net/__version__

``` js
{
  source: "https://github.com/mozilla-services/pageshot/",
  version: "July 15, 2016 00:24:59 UTC",
  commit: "adceb6f"
}
```

---

Installed the latest add-on and took a bunch of shots, but I need to click on each shot individually to see when they expire.

![my_shots](https://cloud.githubusercontent.com/assets/557895/16928145/fc1327a4-4ce5-11e6-8585-93d50a635511.png)

We may want to add a "Expires in __ days" style link on the /shots page, similar to the details page (but probably only show a static string and not the `<select>` style UI):

![must_login](https://cloud.githubusercontent.com/assets/557895/16928207/4c7724c0-4ce6-11e6-8569-3f51270e3afe.png)

**Comment by fzzzy** [comment]
That does seem to be a pretty obvious feature.

**Comment by pdehaan** [comment]
Semi-related, but I'm still uncertain on what the default expiration setting should be.
As a user I generally expect my saved data to never die, and it's the service's problem to figure out how to make that work.
For example, I'd be pretty unhappy if Dropbox (or Sync) started deleting all my files after 2 weeks unless I manually changed it for each file. Not sure if we should allow the user to set a default retention length, or just set the default to "Expires: Never" and let the user set to a lower value if they don't mind the Shots disappearing into the ether.

**Comment by ChenMorpheus** [comment]
Please find the link below for the final design, and let me know if any questions, thanks.
https://mozilla.invisionapp.com/share/QV90U2ECW#/197767855_1-1_Shot_Page

**Comment by wresuolc** [comment]
I'm tentatively marking this as a good first issue, because I think it's scoped well and straight forward, but it's probably best for someone with some coding experience on other sites.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
