### ISSUE TITLE
Check out SCRN App

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/screenshots#1311]
http://scrnapp.com/

Instead of you needing to invoke the “Share” menu or save an article manually, all SCRN app asks you to do is to take a screenshot. Somehow, the app recognises this action. It then takes the article’s link and makes it available for offline reading.

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/1ytRh5WzOQD2fEB1IxUVeNeQJ4jtdIV3VkyyUb5AyfoQ/edit)
