### ISSUE TITLE
Add questions to page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#133]
Add questions, that someone could/should/must answer, directly to page - to the entire page, or in a specific context

**Comment by ianb** [comment]
UX ethnographic research seems to be adding to the relevance of this – while some messages just get sent out, "asking a question" is really important, and I think if we make the flow as easy as possible this could be a good way to get an answer when you want.  Ultimately people will seek the medium that gets them answers.

**Comment by brampitoyo** [comment]
Some thinking: a question, by nature, is different from a comment.

OP’s comment may be drowned out’by the most recent or most popular replies, but OP’s question must always appear first, on top, with the answers from other users following it.
