### ISSUE TITLE
Add links to screenshots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1484]
This is a concept I've thought about for a while, but haven't found the time to move forward on.  But I both have some time, and given a screenshot-only release there's some motivation:

We can specifically add links to the screenshots.  I should note in my own use I've wanted this.  I don't often need to copy the text (it's all right there in the screenshot, why bother with a transcription?), but links are great for all sorts of reasons, and navigating to the original page to get the links is hard.

To implement this we'd find all links who have [rectangles](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) that intersect with the clip (eliminating links that don't have a good href).  Having found them we'd create something akin to the old-timey [imagemap](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map) (except with modern positioned boxes).

**Comment by johngruen** [comment]
I still think this is an interesting concept

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
