### ISSUE TITLE
convert dateString() to Date#toLocaleString()

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1486]
Ref: [/server/src/views/frame.js:214-227](https://github.com/mozilla-services/pageshot/blob/901321a4ce477d160eef8c983efe8abb1f90f5a9/server/src/views/frame.js#L214-L227)

I think we can replace this:

``` js
    let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    let month = months[d.getMonth()];
    let hour = d.getHours();
    if (hour === 0) {
      hour = "12am";
    } else if (hour === 12) {
      hour = "12pm";
    } else if (hour > 12) {
      hour = (hour % 12) + "pm";
    } else {
      hour = hour + "am";
    }
    let year = 1900 + d.getYear();
    return `${month} ${d.getDate()} ${year}, ${hour}`;
```

With this:

``` js
const options = { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric' };
return d.toLocaleString('en-US', options); // ie: "Dec 20, 2012, 3 AM"
```

**Comment by ianb** [comment]
I suspect we need this for localization (or to avoid localizing this too closely).  *Except*, can we use it on the server?  Note there are fixups around dates in particular so we could potentially use a lame GMT-only YYYY-... date on the server and fix it up on the client.

**Comment by johngruen** [comment]
Important for server l10n
