### ISSUE TITLE
Report CSP to /cspreport

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1498]
For [reporting CSP violation errors](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_CSP_violation_reports).  I believe Mozilla has a service we can report to.

**Comment by wresuolc** [comment]
I see `report-uri /__cspreport__;` in the CSP already.  Is this already done or is this talking about something else?

**Comment by testeaxeax** [comment]
@ianb To what Mozilla service are you referring for reporting?

@wresuolc There is no `report-uri` statement in the CSP of screenshots.firefox.com and/or it's code. Where did you see your `report-uri`?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
