### ISSUE TITLE
Investigate CloudApp

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#153]
[CloudApp](https://www.getcloudapp.com/) specifically focuses on screenshots, but has expanded into other media.

**Comment by ianb** [comment]
Here's what the onboarding looks like now:

![image](https://cloud.githubusercontent.com/assets/44390/18324559/c9af9b7c-7502-11e6-8f71-75bead693734.png)

![image](https://cloud.githubusercontent.com/assets/44390/18324563/d002d48a-7502-11e6-88bb-0d14a7491ff0.png)

![image](https://cloud.githubusercontent.com/assets/44390/18324581/de8ab450-7502-11e6-8cbc-6e7d7a246cc9.png)

![image](https://cloud.githubusercontent.com/assets/44390/18324590/e3a7173a-7502-11e6-9a4a-1ae6cb83eb92.png)

**Comment by pdehaan** [comment]
I checked out https://www.getcloudapp.com/ yesterday and it seemed pretty decent.

1. They have a nice GIF capture.
1. Their annotation tools weren't the best, but i was talking with them yesterday and they said they're updating them soon.
1. They have a nice share system with a few settings (share w/ everybody, password protect, share w/ specific people), and expire shots after X hours/days, or after Y views.
1. Plus some decent use of push notifications.
1. Desktop app and not limited to just browsers.

Definitely recommend checking them out. The free account _does_ feel a bit limited, and you get pressured to upgrade to a paid account pretty early on in the funnel.

**Comment by ianb** [comment]
What were the push notifications used for?  I.e., what activities get you notified?

Can you share more about the sharing system?  Like, what options do they give, how do they work?  Does everyone have to have an account?

**Comment by pdehaan** [comment]
Here's one of my GIF shots: https://cl.ly/1E1c1y3Q023J -- you should be able to enjoy/share it without signing up/in. I can still view it in Private Browsing Mode.

**Comment by pdehaan** [comment]
We're gettin' meta! Here's a share of the push notification that gets displayed every time you take a screenshot:

https://cl.ly/1b2H3y2T0u3r

And here's what the shot page looks for me (I'm logged in and have a 60 day paid account):

![image_2016-10-18_at_10_46_41_am_png](https://cloud.githubusercontent.com/assets/557895/19489550/86481100-9520-11e6-994c-b2ca52b75c0e.png)

**Comment by pdehaan** [comment]
![](https://d3dr1ze7164817.cloudfront.net/items/1p2N2H222t3r0c0k0F2P/Image%202016-10-18%20at%2010.50.11%20AM.png?v=da301c85)

... and Advanced Settings is:

![](https://d3dr1ze7164817.cloudfront.net/items/3y3V2u020a3a0U0t0E1L/Image%202016-10-18%20at%2010.51.09%20AM.png?v=310074b4)

And that "hour(s)" dropdown has the following options:

- hour(s)
- days(s)
- week(s)
- month(s)

I tried making a shot that'd expire after ~25 minutes, but it seems to have a minimum of 1hr (which is totally valid):

![image_2016-10-18_at_10_51_09_am_png](https://cloud.githubusercontent.com/assets/557895/19489758/53a9073a-9521-11e6-849b-b5b456c35987.png)

**Comment by ianb** [comment]
Some more notes:

## Share menu

![image](https://cloud.githubusercontent.com/assets/44390/19489521/2e577740-9531-11e6-95b6-133db0ac71f0.png)

It shares the original URL, not the image URL.  Email requires sign-in, and has a special form:

![image](https://cloud.githubusercontent.com/assets/44390/19489605/8dfe80f8-9531-11e6-8672-757546503a2d.png)

Nothing fancy on the other end though, and it gets spamtrapped:

![image](https://cloud.githubusercontent.com/assets/44390/19489643/ad085582-9531-11e6-933a-eae816f47d61.png)

Pinterest is done inline (not directing to another page).  Otherwise it's all the same simplistic sharing we do.

## Context menu

![image](https://cloud.githubusercontent.com/assets/44390/19489664/c0e5ef2e-9531-11e6-9ef3-c61212fcfe1d.png)

Each of these gets to a different view, or gets the link to a different view.  They don't all make sense.

"View original file" gets you the image by itself ([like this](https://cl.ly/1E1c1y3Q023J/Screen%20Recording%202016-10-17%20at%2003.24%20PM.gif)).  

"View secure link" is this sharing page.

"Download file" downloads the file, and if you copy the link it's a link to download the file.  So it's using `Content-Disposition`.  If someone else clicks on that link from an email, for instance, they'll get a new tab, but it will still result in a download.

"Download torrent" links to a `.torrent` file.

"Save elsewhere" triggers an export process:

![image](https://cloud.githubusercontent.com/assets/44390/19489795/479ca4ae-9532-11e6-8829-a3d4db904c65.png)

It includes some rather complicated options like FTP and WebDAV.  In these cases you configure it in the form.  Anyway, it's just a widget from [Filestack](https://www.filestack.com/).

**Comment by pdehaan** [comment]
As for sharing, there are three main options:

- Anyone with the link
- Anyone with the link and password
- Only specific people

![image_2016-10-18_at_10_51_09_am_png](https://cloud.githubusercontent.com/assets/557895/19489788/7e6cb8e0-9521-11e6-9418-eea0a41ccd15.png)

![image_2016-10-18_at_10_51_09_am_png](https://cloud.githubusercontent.com/assets/557895/19489805/8eff7a62-9521-11e6-989a-df696defa3f5.png)
**Figure 2:** The alignment looks better on Chrome. 👎 

![image_2016-10-18_at_10_51_09_am_png](https://cloud.githubusercontent.com/assets/557895/19489830/aaf7bd6a-9521-11e6-8c36-aab6a427537b.png)

**Comment by ianb** [comment]
When you share through the email (maybe other ways?) you get notification when the item you shared has been viewed.  The links contain a tracking code; this is an example email:

![image](https://cloud.githubusercontent.com/assets/44390/19492808/e1d8f698-953d-11e6-9ecc-0a48b5eed1c2.png)

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1cm1kvqf1Oj12WcBEHgUwK2uGYYRxEaJa_Jrs-igojCQ/edit)
