### ISSUE TITLE
Create Twitter account for Page Shot status

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1543]
I think this might be the easiest way to publish information about known outages/etc.  There's a possibility Mozilla might have some other status approach.  We have [@mozillapageshot](https://twitter.com/mozillapageshot) but something purely for status might be better than that.

The status should get linked to some of the error messages in `error-panel.html`

**Comment by pdehaan** [comment]
@johngruen Do you think we'd need this for release, or could we just use the `@FxTestPilot` Twitter to communicate any outages, etc.

TL;DR: can we bump from this milestone?

**Comment by johngruen** [comment]
Let's bump this out...

**Comment by johngruen** [comment]
We have a twitter acct
