### ISSUE TITLE
Fix "You can't take a shot of a Page Shot page!"

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/screenshots#1586]
When you press the shot button while on a shot or the my shots page, you get an ugly error message. 

@johngruen what should we do instead in this case?

**Comment by johngruen** [comment]
@fzzzy screenshot?

**Comment by fzzzy** [comment]
![screen shot 2016-09-22 at 3 55 50 pm](https://cloud.githubusercontent.com/assets/46048/18763904/41b6161a-80dd-11e6-8696-db2c28890d65.png)

This is a stretch goal, because we need to figure out what users actually want to do when they do this.

**Comment by johngruen** [comment]
@fzzzy disable the button?

**Comment by Liudvikas** [comment]
The same here:
![my shots - vimperator_001](https://cloud.githubusercontent.com/assets/196435/19465696/7152da7e-9506-11e6-835c-96d6d7e92946.png)
Would be nice to be able to take shots there too! :)

**Comment by ianb** [comment]
@Liudvikas : we've found in user testing that people click the Page Shot button when they are confused, and then it becomes even more confusing from there as they take a shot of the shot page.  So while there's nothing technically keeping Page Shot from working on shot pages we want to avoid this situation.

Would it be reasonable for the button to take the user back to My Shots?  I've become quite partial to that behavior on new tabs.

**Comment by ianb** [comment]
Relates to #2160

**Comment by ianb** [comment]
Should be fixed by #2368
