### ISSUE TITLE
There is not "upload to imgur" option

### ISSUE THREAD

**Issue by myBestSoftAndPref** [mozilla-services/screenshots#1614]
There is not "upload to imgur.com" option.
It's strange because API for uploading to https://imgur.com **exist** in Firefox and available through `shift + F2` hot keys in developer's console.

**Comment by ianb** [comment]
Looks like the [image upload](https://api.imgur.com/endpoints/image) API endpoint is fairly straight-forward, and maybe we can do it with a simple `<form method=POST action="https://api.imgur.com/3/image" target=_blank>...` where the social button is a submit button.  I'm not sure if we need authentication for this API.

**Comment by johngruen** [comment]
@ianb i'm tempted to move this into stretch to bubble it back up into something we should consider

**Comment by johngruen** [comment]
Also toggling to needs:UX

**Comment by johngruen** [comment]
Closing in favor of a generic integration tracking bug

**Comment by johngruen** [comment]
#3685
