### ISSUE TITLE
Investigate Screengrab

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1620]
[Screengrab](https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/) is an add-on:

> Screengrab! saves entire webpages as images. Just right-click on the page you want to grab and look in the "Screengrab" menu.
> It will capture what you can see in the window, the entire page, just a selection, a particular frame... basically it saves webpages as images - either to a file, or to the clipboard, or upload to internet.

**Comment by qguv** [comment]
I'd use pageshot all the time if it supported Screengrab-style full-page screenshots. I use whole-page screenshots daily for web development QA and bug reports.

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/1rxgoNKmPjQQZj29jYBBBX1ndJCf69AZgUhNIUgMD6zY/edit)
