### ISSUE TITLE
Add "copy image" to shot pages

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1646]
Sometimes, like with GitHub issues, I'd really rather copy the image directly.  We have the URL copy but not the image copy.

**Comment by johngruen** [comment]
Kicking this out of blue sky since we're looking at copying to clipboard from the add-on. This would make sense as a follow up.

**Comment by chenba** [comment]
This is a dup of #2582

**Comment by johngruen** [comment]
@youwenliang  we need a spec to get started on this one!

**Comment by youwenliang** [comment]
@johngruen I had the measurements here:
-> https://github.com/mozilla-services/screenshots/issues/2582#issuecomment-337473248
Should we do an A/B testing for the button (icon-only & icon+text)?

**Comment by chenba** [comment]
AFAIK copying images to the clipboard (outside of an addon) is not possible.  😕
