### ISSUE TITLE
Copy button renders incorrectly on Linux

### ISSUE THREAD

**Issue by shashikumarraja** [mozilla-services/screenshots#1684]
Take a screenshot>>Click on Save button>>Now the new page opens with the option to copy the url>>In this page the copy button is not properly displayed.
Check the screenshot for more details.
![screenshot from 2016-10-04 11-09-04](https://cloud.githubusercontent.com/assets/13863716/19063793/6b3594f8-8a23-11e6-83f2-330b9c88671a.png)
![2](https://cloud.githubusercontent.com/assets/13863716/19063854/d3694862-8a23-11e6-840c-95e1c2306565.png)

**Comment by SoftVision-CosminMuntean** [comment]
I can also reproduce this issue using the latest Page Shot add-on (v. 0.1.201610031844).  The "Copy" and "Copied" strings exceed the button area.  I have tested this on Ubuntu 14.04 with latest Firefox (49.0.1) release and latest Nightly (52.0a1) build.

**Comment by shashikumarraja** [comment]
My testing environment was exactly the same except the os version which is Ubuntu 16.04 LTS.

**Comment by pdehaan** [comment]
This seems to work on my Nightly macOS El Capitan, so I'm thinking possibly a Linux specific bug:

![invalid_video_length_ _issue__382_ _meandavejustice_min-vid_and_27_hour_timer_-_youtube](https://cloud.githubusercontent.com/assets/557895/19087241/29520fa0-8a26-11e6-8ee3-7094e4cf995b.png)

Conversely, we could maybe switch from "Copy" text to an SVG icon...

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19087379/96a820ee-8a26-11e6-9d82-177012f62238.png)

**Comment by ianb** [comment]
It would be better to avoid SVG for the purpose of future translation.

**Comment by pdehaan** [comment]
> It would be better to avoid SVG for the purpose of future translation.

Wouldn't SVG be _better_ for translation (since they would be universal and not require translation)?

For example, GitHub's Copy button when cloning a repo:

![mozilla-services_pageshot__an_experiment_in_creating_better_shareable_versions_of_content](https://cloud.githubusercontent.com/assets/557895/19087513/1e3c561a-8a27-11e6-9d2e-d46305b6bbce.png)

**Comment by ianb** [comment]
Oh sure, an icon could be easier, though I believe words are generally comprehended better than icons (per some research I can only vaguely allude to).  In this case the button is actually missized, not the text, and an icon can also be misaligned in that case.

**Comment by johngruen** [comment]
agree with @ianb, we should keep the text

**Comment by wresuolc** [comment]
This is fixed
