### ISSUE TITLE
Investigate Awesome Screenshot

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/screenshots#169]
http://awesomescreenshot.com/

Awesome Screenshot does very few things very well. It lets you screenshot the whole or a specific part of the page, annotate it with arrows/lines/circles/text, and upload it to the cloud to get a shareable link.

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/1_Omt5MY9A2NS3dtSL5Q0Gwep48mMi9Pwl_QPqcnhVBQ/edit)
