### ISSUE TITLE
Batch delete, download controls on the My Shots page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#1728]
So that I can download multiple shots or delete multiple shots from the _My Shots_ page, I would like to have controls that allow me to perform these operations on multiple shots at once.
- [ ] It should present controls users to select multiple shots on the _My Shots_ page.
- [ ] it should ask users to confirm a batch delete operation
- [ ] it should be extensible for other batch operations (sharing, copying etc)

**Comment by ianb** [comment]
We should consider undo in lieu of confirmation on delete.  A very simple implementation would just delay the actual delete for 10-20 seconds.  But of course `window.confirm()` is the simplest of all implementations.

**Comment by ChenMorpheus** [comment]
Please find the link below for the UX spec, and let me know if any questions, thanks.
https://mozilla.invisionapp.com/share/WF8V8N1NX#/197767846_1-2_Shot_Hovered

**Comment by fangshih** [comment]
Here are the icon assets, thanks! 
[icon-Assets.zip](https://github.com/mozilla-services/pageshot/files/543790/icon-Assets.zip)

**Comment by ianb** [comment]
I've left several comments on the [invision document](https://mozilla.invisionapp.com/share/WF8V8N1NX#/screens/197767870/comments)

**Comment by ChenMorpheus** [comment]
I've replied all your comments and updated the spec accordingly, please find the previous link for all updates, thanks.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
