### ISSUE TITLE
Let users chose the default post-shot behavior

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#1766]
The core focus should be limiting the number of operations between intent and outcome. There are two general use cases for which we can optimize here.
- Take Shot > Share Shot
- Take Shot > Download Shot

**Proposal**

As a Page Shot user, so that i can minimize unnecessary clicks and quickly achieve my desired outcome, I would like to set a default behavior for saving a shot URL to my clipboard, downloading shots, or both.

**Sketch**
<img width="1024" alt="work notes - 28" src="https://cloud.githubusercontent.com/assets/3323249/19468036/aa6c4aee-9514-11e6-8ce5-d4b7c60ed7e3.png">

**Comment by ianb** [comment]
For "download shot" we should consider letting users choose where to download it to.  We could default to Downloads, or Downloads/Page Shots/.  But if we have no default at all then we force users to know where the shots are going.

We should also consider how we notify users that the shot has been downloaded.  A simple way is just to use the same popup we use for Copy, but change the text depending on what exactly we do.  We can make a click action on those popups too, which for downloading could show the resulting file.

I believe we are proposing that downloading happen *in addition* to creating a shot page.  We'd need to explain that too.

**Comment by ChenMorpheus** [comment]
Please find the link below for the UX spec, and we'll update the copy after review. Besides, please only refer to the "current design" in the UX spec before we have the A/B testing. 

https://mozilla.invisionapp.com/share/ER934Y4ND#/200168327_1-1_Shot_Page_-_Settings

@fangshih Could you help provide the assets? Thanks.

**Comment by fangshih** [comment]
Attached the visual spec and assets! Thanks! :D 
[#1766 Visual Assets.zip](https://github.com/mozilla-services/pageshot/files/574721/1766.Visual.Assets.zip)

**Comment by ChenMorpheus** [comment]
Sorry that it's been a while, but the copy has been reviewed, please find the link for the latest spec, thanks.

https://mozilla.invisionapp.com/share/ER934Y4ND#/200168327_1-1_Shot_Page_-_Settings

**Comment by ianb** [comment]
I think we've solved this with the current UI, without preferences.

**Comment by ianb** [comment]
I don't think there's anything more to be done here.
