### ISSUE TITLE
Congratulate users on their first shot

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#1767]
After users take their first shot, we could add a small toast notification thanking them. Something like this

<img width="1024" alt="work notes - 29" src="https://cloud.githubusercontent.com/assets/3323249/19468373/3b429cac-9516-11e6-8653-dbb7b10cd881.png">

**Comment by johngruen** [comment]
@wresuolc @ianb i think this could be a really easy A/B test for us to measure if congratulating users increases retention. I'll work with Teon to write up a plan.

**Comment by fangshih** [comment]
Hey guys! Here are the congrats first shot, not sure what would be the right text for it. 
Let me know if it works 
![key-screens-40-crop-image--first-shot](https://user-images.githubusercontent.com/4862573/32886427-9e12c26e-cafb-11e7-88cb-5b562d982a03.png)

**Assets and spec** 
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/FFSS_Congrats_1767

So it will be like this, pop out stay for like 5 second and short dismisses fade out ... ( ballroom kinda chill in the air would be fun? ) 
![comp-1_4](https://user-images.githubusercontent.com/4862573/32886605-2a367eb6-cafc-11e7-9473-7a1385fd81a6.gif)
 
Thanks!

**Comment by youwenliang** [comment]
For reference: https://codepen.io/youwenliang/pen/qVPoQd

**Comment by johngruen** [comment]
@fangshih yeah, i really like the animation. @ianb let's do this soon for 10% of people. We can reach out to Gareth about breaking out cohort tables for control vs/experiment.

Also for the strings, lets do: 

```
Congratulations
Thanks for taking your first screenshot!
```

**Comment by wresuolc** [comment]
To be clear, this only happens when they upload it to the cloud, right?  And if they take a bunch of local shots and then upload one they still see this on their first upload?

I think the answers are yes, but just want to make sure. :)

**Comment by johngruen** [comment]
@clouserw yes

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
