### ISSUE TITLE
Allow saving only locally

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#1791]
There may be pictures you do not want to share with the whole world. Therefore I'd propose a feature, which allows one to save the files only locally and not upload them to any server. It might be done with an extra button or when e.g. clicking on the button while pressing the shift key.

It might work similar to the dev tools screen capture: Directly trigger a (fake) download of the (locally handled) image.

**Comment by johngruen** [comment]
Hey @rugk, we're intentionally building a cloud service with the Page Shot experiment. Please consider Awesome Screenshot http://www.awesomescreenshot.com/ which is a great local screenshotting tool

**Comment by SebastianZ** [comment]
> we're intentionally building a cloud service with the Page Shot experiment.

It's fine to build a cloud service around Page Shot, though the decision on whether to upload images to the cloud service should stay at the user.

At https://testpilot.firefox.com/experiments/page-shot the info that the images are stored in the cloud is below the fold on average size monitors/resolutions and when installing it there is no hint telling the user that the images are stored externally.

As a user I want to be in control of whether the page shots are saved in the cloud or **exclusively** stored locally for privacy reasons.<br>
To promote the cloud server, users should be made aware of the benefits of it.

Implementation
==========
The images would be stored in a local directory and be accessible through `about:pageshots`, for example. If the user decides to store the screenshots in the cloud, the images may either be copied over to the cloud service or only future screenshots will be stored there. If the user later decides to store the images locally again, the screenshots may either be copied to a local directory again and be removed from the cloud or they are kept in the cloud and only future screenshots are stored locally.

Sebastian
