### ISSUE TITLE
Website favicons are not displayed for saved shots on the Page Shot dev build

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#1800]
[Affected versions]:
- Firefox 48.0.1 and up
- Mozilla Page Shot 0.1.201610200859

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest PageShot add-on (v0.1.201610200859) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click the Page Shot icon from the browser toolbar, perform a selection and save it.
3. Click the "My Shots" button from the top left page.
4. Observe the website favicon for the saved shot.

[Expected result]:
- Website favicon is displayed for the saved shot.

[Actual result]:
- Website favicon is not displayed on the saved shot.

[Notes]:
- Added a screenshot with the issue: 

![no favicons](https://cloud.githubusercontent.com/assets/19226534/19565736/9a7ae98c-96f0-11e6-821c-75672130de29.png)

**Comment by wresuolc** [comment]
Duping to #2648
