### ISSUE TITLE
Design general sharing interface

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1811]
We have the share panel on shot pages, and want to add a sharing interface that comes out of one shot tile, and a sharing interface for when you select multiple shots and share them.  It would be nice if these all used the same interface.

Note that we probably won't keep all the social sharing options (Facebook, Pinterest, etc) that we have now, so the interface should adapt to changing that list.

There should be a discussion about whether we show the entire URL like we do in the current share panel:

![image](https://cloud.githubusercontent.com/assets/44390/19609656/fa578790-979d-11e6-94c9-09010fa1a67f.png)

Note the text box gets pretty good engagement.  (Though maybe because people think you MUST click that before clicking copy?)

**Comment by johngruen** [comment]
This is real now
