### ISSUE TITLE
moz-extension url throws Bad URL

### ISSUE THREAD

**Issue by kareniel** [mozilla-services/screenshots#1816]
I am currently working on a Firefox add-on. I wanted to take a screenshot, so I thought I'd give
pageshot a try. Turns out it seems like it doesn't like moz-extension URLs:

> Page Shot went haywire.
> Try again or take a shot on another page?
> Failed assertion: Bad URL: 

**Steps to reproduce:**
1. Navigate to about:addons
2. Click the gear icon and select 'Install Add-on from File'
3. Select a valid manifest.json Firefox extension file
4. Navigate to the extension's url (moz-extension://{{extensionId}}) 
   (The extension's ID is available at about:support under Extensions )
5. Click on the Pageshot browserAction icon

**System info**

Firefox 49.0.2
Mac OS X El Capitan (10.11.6)
Pageshot v0.1.201610042037

**Comment by ianb** [comment]
I'm still unclear how to go to one of these pages.  For instance the id of Test Pilot is `@testpilot-addon`, but if I go to `moz-extension://@testpilot-addon` it doesn't do anything for me.

**Comment by kareniel** [comment]
Oh, sorry!

Step 2 should be: 
- Click the gear icon and select 'Debug Add-Ons'
- Click on 'Load Temporary Add-on

I just realized that the moz-extension:// uri doesn't use the extension's id but a GUID it's given.
The id for extensions that don't have an id in their manifest shows up as that GUID.

I'm not sure where to find it that GUID. So I made an example extension you can use to reproduce this.
https://github.com/kareniel/pageshot--1816

Just use it's manifest.json as a target when choosing 'Load Temporary Add-on'.
It's going to add a button to the nav bar. If you click it it will bring you to index.html inside the extension's folder. At this point if you click on PageShot's button you'll get the error message.

**Comment by ianb** [comment]
It's probable that with a port to a WebExtension we won't be able to access these pages at all, but we'll have to confirm

**Comment by ianb** [comment]
Should be fixed by #2368 ("fixed" as in "you aren't allowed to take screenshots of these pages")
