### ISSUE TITLE
Local(Offline) Preview Of Captured Content And Optional Online Sharing

### ISSUE THREAD

**Issue by shivarajnaidu** [mozilla-services/screenshots#1818]
If i click **Save** button after selecting .... it takes users to https://pageshot.net/shots ... but 

what if some don't have internet or lost connection at the time of capturing page.. and what my opinion is .... if we can do some things in offline too... then it would be comfortable to all people... we can give online sharing links right there in off line preview page... optional online preview for those who want to see their content in online..

**Comment by johngruen** [comment]
@shivarajnaidu it would be nice to default to download on timeout, for the time being we're working on letting users chose their default actions

**Comment by shivarajnaidu** [comment]
Hmmm... that's great if users provided with options to choose default actions for local preview.. 

and Thanks For Your Kind Reply @johngruen

**Comment by klint** [comment]
Offline mode is also needed for confidentiality reasons in some cases. When used in a corporate environment, taking shots of a corporate intranet website is ok but uploading them (even for a short time) on the internet is not.

**Comment by wresuolc** [comment]
There is now a download button next to the cancel and upload buttons which will save your image locally.
