### ISSUE TITLE
favicon 404 when site no longer available

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1830]
Semi-expected edge case, but not sure if we can do something "a bit better":

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19667491/0402de7e-9a06-11e6-812c-e4bf478849c1.png)

The _twist_ is that testpilot.dev:8000 is my localhost (with entry in /etc/hosts), but the site isn't currently running, so the proxy currently 404s. Not sure if we can detect 404s for favicons and provide some default/fallback for when we can't reach the target. This should hopefully provide a slightly nicer UI than an empty area where a favicon should be, but isn't.

![my_shots](https://cloud.githubusercontent.com/assets/557895/19667463/e064c73e-9a05-11e6-9419-5671a9d1950b.png)

**Comment by johngruen** [comment]
@fzzzy says we should save the favicon in the db...
also ask activity stream

**Comment by ianb** [comment]
We aren't currently showing the favicon, so this isn't applicable.
