### ISSUE TITLE
Broken image on Page Shot when trying to take a 1224x14908 shot

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1832]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19668294/94b5574e-9a0b-11e6-9671-cde642472715.png)

I was trying to take a rediculous 1224px-by-14908px screenshot of the http://www.apple.com/ipad-pro/experience/ page, but I'm getting an error when I try and view the image at https://pageshot.net/sOxWnxA3MamfRGGK/www.apple.com

My console says:

> sendEvent web/visit/owner undefined (raven.js:80:13)

And I get a broken image icon:

![page_info_-_https___pageshot_net_soxwnxa3mamfrggk_www_apple_com_and_ipad pro_-_experience_and_slack](https://cloud.githubusercontent.com/assets/557895/19668240/2ea6b89e-9a0b-11e6-8f4a-7e43da31fcc6.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19668261/4e1ddc84-9a0b-11e6-82e8-1561fd2273cf.png)

**Comment by pdehaan** [comment]
Actually, I think that `console.log()` raven.js warning is unrelated, as I get it on this random shot as well: https://pageshot.net/7X7YCN2qVmXi49vj/cl.ly

**Comment by johngruen** [comment]
@pdehaan seems to be working, but we should investigate uploading big stuff

**Comment by pdehaan** [comment]
I was also able to reproduce this while taking the 1410x5000px https://pageshot.net/uhcx5alZFnJN5Kfc/www.imdb.com (1,758kb).

The shot DOES seem to render fine now, so I'm wondering if it's just showing as a broken image while PageShot is generating the 1.7MB image .

**Comment by thekyriarchy** [comment]
So this bug is about the timing of loading not waiting for a complete render?

**Comment by wresuolc** [comment]
I can take full screen shots of the linked apple page, and they are cropped to 5000px and work fine.  So, I think this issue can be closed.
