### ISSUE TITLE
The style of popup for copied link after Save

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-services/screenshots#1844]
Based on #1734, we came up with the new style for the popup (Find the link below). We want to covey the unity by providing a centered and simplized toast. Could anyone help check if it's feasible? Please let us know if any quesitions, thanks.

https://mozilla.invisionapp.com/share/ER934Y4ND#/197767889_1-3_Windows_Selected

![2016-10-26 6 44 36](https://cloud.githubusercontent.com/assets/18019946/19723093/4e266ffa-9bac-11e6-9229-4addfacdbfb6.png)

**Comment by ianb** [comment]
Though we could put the notification up on both the creating page (the waiting page) and the completed page to make it all a little faster – often the creating page is only up for a moment, so it would have to be in both places.

**Comment by ianb** [comment]
For now we're going to stick with the OS notification popup.

**Comment by ChenMorpheus** [comment]
@ianb @johngruen 
Since we were working on the proposal and it's still under review by copywriter, that causes a bit delay here. Sorry for the late reply. 
Under the premise of keeping the current design, we suggest having an A/B testing to compare the current design and experiment to test if we can streamline the screenshot experience more, especially if we allow users choose a default action after shot(Refer to #1766). Please find the illustration below for the differences and try the prototype on InVision.

![1-0 current design vs proposal](https://cloud.githubusercontent.com/assets/18019946/19957109/c183397e-a1ce-11e6-8935-fe9813b80281.png)

Prototypes: https://mozilla.invisionapp.com/share/ER934Y4ND#/200168327_1-1_Shot_Page_-_Settings

Based on the prototype, you can notice that the main purpose of the experiment is to directly perform the default action instead of directing users to shot page for other options in a new tab every time. We believe this can simplify the screenshot process which echoes #1627 and avoid interrupting the browsing experience on the current web content. However, we understand A/B testing causes more effort and we are not familiar with the process of experiment. So please let us know if this idea is feasible and what work or document we should prepare for you, thanks.

Before we implement the experiment, we can just stick to the current design with the OS notification popup. Based on the discussion in #1734, we understand we don't have much control on how the popup looks. But it would be great if we can replace Firefox logo with  a clear copy/download icon and remove the link icon as the image shows below. Could you help check the feasibility too? Thanks.

![popup](https://cloud.githubusercontent.com/assets/18019946/19957684/c25c2a0e-a1d3-11e6-8f8d-5396b2e8ec2c.png)

**Comment by johngruen** [comment]
@ChenMorpheus i could see another case where we don't ever do a full redirect here...that might be an easier A/B to start with. I have been sharing with page shot quite a bit and find myslef not really caring about the seeing the image before i paste the URL into wherever I am sharing them.

**Comment by johngruen** [comment]
I am closing this, it's not gonna happen
