### ISSUE TITLE
Feedback: Page shot doesn't work in website containing sidebar

### ISSUE THREAD

**Issue by mdmuaj13** [mozilla-services/screenshots#1858]
If I want to take a snap shot of a website containing sidebar, the snap shot doesn't work on sidebar. So we cannot take snap shot of sidebar.

STR:
1.First open your firefox browser.
2. Go to http://cubic-bezier.com/ 
3. Try to take a snap shot of author part(left side)

Actual Result: You can cannot take snap shot author part(left sidebar)
Expected Result: We expect our snap shot would take any contain of website.

I have reproduced with Firefox 51.0a2 on windows 7, 32bit
Build ID    20161027004020
User Agent  Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0

This is the screen shot with the bug.
![capture](https://cloud.githubusercontent.com/assets/20964899/19796610/779b581c-9d07-11e6-81e2-6f08405b5049.PNG)

**Comment by ianb** [comment]
The reason this happens is that the page has `body {margin: 1em}`.  Note it actually has things in the margin, presumably with negative positioning.  I'm not sure yet how to detect this case.  E.g., `document.body.offsetLeft` just gives 0.

**Comment by ianb** [comment]
Fixed with #3907
