### ISSUE TITLE
Animated AD Error

### ISSUE THREAD

**Issue by THPallab** [mozilla-services/screenshots#1860]
If we want to take a snap shot of an animated AD from any web page, the animated Advertises are continuously moving. But we want a frozen screen so that we can take our expected shot. It should be fixed.

**STR**
1. First open your Firefox browser.
2. Go to any website with animated AD. (http://www.prothom-alo.com/)
3. Try to take a snap shot of an animated AD.

Actual Result: We get a snap shot that we get when we click the "Save" button.
Expected Result: We want a snap shot of that screen that we have on the screen at that starting moment.

I have reproduced with Firefox 51.0a2 on Windows 7, 32 Bits
Build ID 20161027004020
User Agent Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by johngruen** [comment]
Unfortunately we do not intend to support recording animations at this time.
