### ISSUE TITLE
Need to create optimized thumbnails for shots page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1896]
https://pageshot.net/__version__ (d36a1b4):

```json
{
  "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "October 24, 2016 22:56:57 UTC",
  "commit": "d36a1b4",
  "contentOrigin": "pageshot-usercontent.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/d36a1b4",
  "unincludedCommits": "https://github.com/mozilla-services/pageshot/compare/d36a1b4...master"
}
```

---

![my_shots](https://cloud.githubusercontent.com/assets/557895/19985849/d2ef7832-a1d1-11e6-960c-69fdd59ce86d.png)

I have about 49 shots (12 full rows plus 1 extra item) and noticed that my devtools is telling me that a full page load is:

## 85 requests, 43,617.24KB, 32.31 s

So basically 42.6 MB of payload and a 32 second page load time.
It looks like some of the images it's attempting to load are 1.25-2.5MB (because I enjoy full page shots, thank you very much).

Further debugging shows that the `div.shot-image-container` thumbnails are 216x130px, yet some of the images loaded are basically just the full sized images. Or rather, we're trying to load a 1.25MB 340x14908 image and downsizing it into a 216x130px image.

![my_shots_and_slack_-_dog_chat_and_cubs_vs__indians_wrapup___11_02_16_and_test_pilot_experiment_pipeline_-_mozillawiki](https://cloud.githubusercontent.com/assets/557895/19986248/2a2bb1b4-a1d3-11e6-962a-7264f9b1f66d.png)

The rest of the requests seem to be the proxied favicons. Some favicons (looking at you Netflix) are about 16KB, which isn't great. Not sure if we should be trying to grab and cache those locally, and possibly even convert them to optimized inline data URIs.

![my_shots_and_slack_-_dog_chat_and_cubs_vs__indians_wrapup___11_02_16_and_test_pilot_experiment_pipeline_-_mozillawiki](https://cloud.githubusercontent.com/assets/557895/19986391/be2300a2-a1d3-11e6-85b1-d9d242917a5d.png)

@nchapman, @k88hudson, and @bryanbell co-maintain the [**tippy-top-sites**](https://github.com/nchapman/tippy-top-sites) project (which we use for activity-stream) that has nice quality images for 150 sites, but we'd still need fallbacks for the other 99.9999999999% of the sites out there.

**Comment by ianb** [comment]
These are the actual clip images I believe, so tippy-top-sites won't matter.  But yes, we should size them down.

**Comment by pdehaan** [comment]
Sorry, I meant tippy-top-sites was just for favicons.

---

Here's a screenshot of my 49 current shots (at 30% zoom):

![my_shots](https://cloud.githubusercontent.com/assets/557895/19986662/d410f7ce-a1d4-11e6-8970-a24831f18339.png)


I think everything else looks pretty good with all my shots I've been accumulating. I noticed that the couple nike.com pages I randomly visited don't have a favicon (and there isn't a fallback nike.com/favicon.ico). One of my m.mlb.com pages has a bogus title (because they have it that way in the opengraph tags). One of the nike.com pages doesnt even have a title, so it's just a blank area.
