### ISSUE TITLE
Add package.json dependency linting?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#1937]
We've had a couple bugs in the past (#1202, #1601) with auditing unused dependencies. Not sure if we want to use something like [**depcheck-ci**](http://npm.im/depcheck-ci) to try and monitor dependencies.

We'd need to create a .depcheckrc file and add all the modules we want to ignore:

```json
{
  "ignore": [
    "babel-*",
    "browserify",
    "depcheck-ci",
    "fx-runner",
    "geckodriver",
    "jpm",
    "node-sass",
    "nodemon",
    "raven-js",
    "uglify-js"
  ]
}
```

I think everything there mostly makes sense. Stuff like babel-* are loaded via plugins and not `require()`d directly. Same w/ browserify, fx-runner, geckodriver, jpm, etc. Only suspicious one is maybe **raven-js**. Not sure if that's used since package.json has a `raven@0.12` and `raven-js@3.8.0`. So not sure if **raven-js** is actually used, or was just an experiment.

Then just install and run the `depcheck-ci` script (ideally running this on Travis-CI on each PR).

```sh
$ npm i depcheck-ci -D

$ ./node_modules/.bin/depcheck-ci --version # 1.0.1
$ ./node_modules/.bin/depcheck-ci
info: Depcheck ok
$ echo $? # 0
```

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
