### ISSUE TITLE
Determine a way to quickly turn things on and off in production

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1976]
Right now we're using environmental variables, but my impression from @relud is that changing those variables requires a redeploy of the environment.  Is there some lighter way we can do this?  The specific example is that I think the metrics were fine (the problem was other things), but now it's unnecessarily hard to turn them on.

**Comment by relud** [comment]
One solution may be to have an admin host for pageshot. It would be restricted to ldap/okta login and modify postgres, and app servers would pick up changes without restarting.

**Comment by ianb** [comment]
We could hook config overrides right into our config system that way.  I'm thinking we'd poll Postgres for changes in each app server, as setting up publish/subscribe systems is something I'm worried we'll get wrong.  (Though PG [has a system](https://www.postgresql.org/docs/9.1/static/sql-notify.html))

Right now our expectation is that `config` variables values can never change, so we'll have to review each case.  E.g., DISABLE_METRICS can't be changed during the life of the app server process.  It seems like it would be too disruptive to restart the app server process on each config update, though... maybe not?  Assuming we put in some random delays so that all app servers don't restart at the same moment.  Restarting would be safest to avoid programming errors, but if we only add dynamic config variables one by one we could be more careful.

**Comment by relud** [comment]
yeah, it's hard and I don't have a good answer :/

**Comment by ianb** [comment]
I'm not sure if we have any variables that need this right now – kicking it back to triage pending a concrete need.

**Comment by johngruen** [comment]
Looks like we may have a concrete need now. Kicking this out of the milestone to relitigate. FWIW, i don't think this blocks 54, but i'm also inclined to give @relud  what he wants. https://bugzilla.mozilla.org/show_bug.cgi?id=1343736

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
