### ISSUE TITLE
Run database migration script separately from the rest of the deploy

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#1977]
We run database migration on application server startup.  This causes problems.  There's crazy and unnecessary concurrency, and the failure modes are not good.

How should we setup these migrations?  Because of reverse migrations, we always want to run the newest version of this migration code, even when reverting.

@relud: thoughts?

**Comment by relud** [comment]
Migrations should be run by jenkins, as part of the deploy process. Ideally it would do this by ssh'ing to a running application server to run the migration. That way jenkins will have a log of what went wrong with the migration, and migrations won't be attempted concurrently.

**Comment by ianb** [comment]
We're using [pg-patcher](https://github.com/chilts/pg-patcher), which I think other projects are using?  Maybe we can copy their pattern.

All our patches are [here](https://github.com/mozilla-services/pageshot/tree/master/server/db-patches), but our target number is just in [source code](https://github.com/mozilla-services/pageshot/blob/ce00f42d7de96d31703c6fdb8ab367b7fe33cabc/server/src/dbschema.js#L7), so I'm guessing we want to give the database version someplace easier to pick up.

**Comment by relud** [comment]
presumably I would run the docker container with some command that updates the db to 'latest' or whatever version the container desires.

**Comment by ianb** [comment]
In 2d4df88629c4cab5795579b4ac248cf98fd59a2d I also made database migration work with `$CONTROLLER_SINGLETON` – this isn't a great solution, but at least it avoids the race condition we have now.  I'll leave this open though for further improvements.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
