### ISSUE TITLE
The preview instructions and displayed Page Shot buttons wrongly change position when using mouse wheel scrolling

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#1996]
[Affected versions]:
- Firefox 50.0 and up
- Mozilla Page Shot 3.0.201611190228

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Page Shot add-on (v3.0.201611190228) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on "Page Shot" icon from the browser toolbar.
3. Observe the instruction message and displayed Page Shot buttons while scrolling the page using the mouse wheel.
 
[Expected result]:
- Te instruction message and displayed Page Shot buttons remain fixed on the page.

[Actual result]:
- The instruction message and displayed Page Shot buttons are wrongly changing their position while scrolling.

[Notes]:
- If the scrollbar, or keyboard keys are used, the issue has a different behavior. The preview instructions and the buttons jumps a few pixels.
- Here is a screen recording with the issue: https://goo.gl/APRq23.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on the latest Pages Shot version 3.3.201611301947 (installed from stage server).  I have also tested with Page Shot installed from Test Pilot.

**Comment by ianb** [comment]
I did notice the problem previously, but I can't reproduce it after c93c37f landed.  It's still adjusting the position on scroll, so it is possible for it to lag, but the lag should be less now.  I'm not sure if we can improve on what it's doing.

**Comment by SoftVision-CosminMuntean** [comment]
I can still reproduce this issue with  e10s enabled. But it seems that is not reproducible with e10s disabled, the Page Shot buttons and the preview instructions are fixed on the page while scrolling.  

I have retested this issue with the latest Page Shot version 4.0.201612162329 installed form stage server using latest Firefox (50.1.0) release and latest Nightly (53.0a1) build. Tested on Windows and Mac OS.

**Comment by ianb** [comment]
Note the reason having e10s enabled changes this is [async scrolling](https://wiki.mozilla.org/QA/Async_Scrolling_in_e10s): it enables a feature where scrolling happens just by moving the rendered image around (though probably respecting `position: fixed`), and scroll events are only emitted later to catch up.

**Comment by ianb** [comment]
I realize we could fix this by having two iframes: one iframe that handles the selection (which has to overlay the entire height of the page), and another iframe that has the instructions and buttons.  The new second iframe will be `position: fixed` and so it will naturally stick to the window.

This also lets us take out the scroll tracking entirely.

**Comment by ianb** [comment]
I opened #2162 to track the implementation fix for this.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on the latest Firefox Screenshots version. Marking as verified.
