### ISSUE TITLE
Firefox latest release (50.0) crashes when trying to save a full page on Facebook or 9gag websites (Mac OS)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2008]
[Affected versions]:
- Firefox 50.0 and up
- Mozilla Page Shot 3.0.201611190228

[Affected Platforms]:
- Mac OS 10.11

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to www.9gag.com.
2. Scroll down on the page to load more content.
3. Click on "Page Shot" icon from the browser toolbar and click the "Save full page" button.
4. Observe the browser behavior.
 
[Expected result]:
- The captured page is correctly displayed.

[Actual result]:
- The browser crashes after pressing the "Save full page" button.

[Additional Notes]:
- Here is the crash report: https://goo.gl/rfCsgB.

**Comment by wresuolc** [comment]
Just tried this a couple of times and didn't see a crash.
