### ISSUE TITLE
Set up auto-deployment for add-on

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/screenshots#2031]
Instructions here:

https://github.com/mozilla/testpilot/blob/master/docs/development/hosting.md

Summary:

We need a script `bin/build-addon.sh` which builds and signs `signed-addon.xpi` using environment variables `TESTPILOT_AMO_USER` and `TESTPILOT_AMO_SECRET`, returning non-zero exit status on any failure.

We need to switch from using the branch name `stable` to one named `production` instead.

**Comment by ianb** [comment]
We have all the autodeploying happening now.
