### ISSUE TITLE
Make the URL deleteable

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2042]
We've gotten this request on Discourse, and it came up in a conversation with someone: sometimes people don't want to show the URL on the shot page.  I think we could just do something simple to allow a person to delete the URL from the shot.

**Comment by ianb** [comment]
Because the domain is in the URL we'd have to figure out something with that too.  Not sure what a good solution would be.

**Comment by pdehaan** [comment]
Why not just remove the domain from the URL and just do completely random characters (similar to imgur/giphy): http://i.imgur.com/p5pTKzU.gif or http://giphy.com/gifs/3o6ozxMJHCtku2IXPW

There are also a few services which create random URLs using combinations of words, which makes URLs a bit easier to retype/remember.

Does leaving the source URL in the shot path add any value?

**Comment by ianb** [comment]
Since we've removed the URL collection this isn't relevant.
