### ISSUE TITLE
If the Page Shot overlay is quickly dismissed, all the website elements become unactionable

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2061]
[Affected versions]:
- Firefox 50.1.0
- Mozilla Page Shot 4.0.201612191406

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.stage.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Quickly press the "Esc" key before the Page Shot selection overlay appears. 
3. Click or select any elements from the page and observe the browser behavior.
 
[Expected result]:
- The elements from the website can be clicked or selected.

[Actual result]:
- All the website elements become unactionable.

[Notes]:
- Page Shot functionality is no longer working even if you click again the Page Shot button.
- The only actions that still work are the context menu and page scrolling. 
- Refreshing the page will fix the problem. 
- Here is a screenrecording with the issue: https://goo.gl/geCkJr.
- If you right click on the page this error can be observed in the browser console:
![frozen error](https://cloud.githubusercontent.com/assets/19226534/21353110/3c0ff74a-c6cd-11e6-8af7-cc44837e5072.png)

**Comment by ianb** [comment]
This seems to be working okay now (a lot of this startup/shutdown stuff has been updated since this was opened)
