### ISSUE TITLE
The preview instructions are wrongly displayed in the top left corner of the page until the selection overlay covers the website

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2063]
[Affected versions]:
- Firefox 50.1.0
- Mozilla Page Shot 4.0.201612191406

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.stage.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website (eg http://www.nytimes.com/).
2. Observe the top left corner of the page while clicking the "Page Shot" icon from the browser toolbar.
 
[Expected result]:
- No additional text is displayed.

[Actual result]:
- The preview instructions are displayed in the top left corner of the page.

[Notes]:
- Here is a screen recording with the issue (at 0.25x speed): https://goo.gl/e5VQQF.

**Comment by ianb** [comment]
We should check how we get the CSS file into the iframe, probably we are adding it dynamically when we could put it on at the time we construct the iframe.

**Comment by ianb** [comment]
I tried changing how the stylesheet was included in 64ffddd0a2a995c4ebf2dea661c5742816a8d364 but it didn't really help.  Maybe an inline `<style>` would help, but that seems awfully complicated.  Tabling this a little in case a better approach comes to mind.

**Comment by fzzzy** [comment]
I think inlining the style tag is the only way to go, although it will be a pain to implement.

**Comment by ianb** [comment]
This was fixed by inlining the CSS
