### ISSUE TITLE
Measure time to first shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2084]
We want to understand more about the time between the install and the first time hitting the Page Shot button, or the first time successfully creating a shot.

We believe we have this information in GA, but we aren't sure how to report on it.  We might have to export.

**Comment by ianb** [comment]
We don't seem to have a good querying mechanism here.  We should add a new event: `addon/first-saved-shot` (since we're not interested in the time to later shots).  Though @clouserw had some interest in the second shot, and we could do something like `addon/first-saved-shot/count` where `count` is an eventLabel that is 1, 2, 3 (maybe stop at 3), and the time is from the last saved shot, or install.

**Comment by ianb** [comment]
Let's do this in /metrics, using the database (the devices.created value, and shot timestamps)

**Comment by wresuolc** [comment]
Now that we're installed by default I don't think there is going to be much to do here.  Closing.
