### ISSUE TITLE
Make the overlay background of help copy to be darker

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/screenshots#2103]
Follow up the issue #1631, it seems the current screen doesn't really follow the proposed design, based on the visual spec, the overlay background should be darker and the instructional text should be bigger. 

Current
![help copy in overlay](https://cloud.githubusercontent.com/assets/4092794/21972721/6896e20e-dbf6-11e6-8a9b-731420b488e8.png)

Proposed design
![pageshot_hint_1](https://cloud.githubusercontent.com/assets/4092794/21972645/e00bd534-dbf5-11e6-9b11-c0c78fcb4286.png)

Please refer to the measurement and help to implement it.
![1631 overlay visual spec](https://cloud.githubusercontent.com/assets/4092794/21972953/2e57603a-dbf8-11e6-92f9-b252b6e6cc90.png)

However, for the face icon, it can be postponed if the icon may be considered unnecessary. Feel free to let me know if any questions.

**Comment by ianb** [comment]
This feels too dark: you have to find the beginning of your selection when the help text is on the screen, so it's important to see the underlying page.

**Comment by ianb** [comment]
@TLHuang : can you upload the face icon?  We'd like to put it in.

**Comment by TLHuang** [comment]
Sorry for the late reply. I've updated the face icon to the [asset folder](https://www.dropbox.com/sh/ojayi19kll69zam/AAAaqSkjoZ1JOCHU6sP8Lh2pa?dl=0), also updated the latest measurement, please refer to [Taking Shot Measurement](https://www.dropbox.com/sh/n9zxt0u7y65og5g/AABYBQwURWCUYk3R5542h0tHa?dl=0). For the final screens, you can find them [here](https://www.dropbox.com/sh/prnul09pg81gv1f/AAAM6P5-KwaW0LOPJmS71bjBa?dl=0).

For the concer that the overlay might too dark to see the underlying content, currently we provide DIV selection that helping user to select an area quickly and easily, so it might not be a big issue for now, however, if there is any question please let us know.

**Comment by ianb** [comment]
Given the redesigns, I believe this is all fixed.
