### ISSUE TITLE
Remove copied icon on the expand sharing panel

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/screenshots#2122]
The copied icon on the top right side of the share panel is duplicated, seems there is a function that getting a shareable link below. Also, the icon doesn't function well, the copied link somehow take you to a search page. So it needs help to remove the copied icon and adjust the layout.

**Current**
![expand share panel](https://cloud.githubusercontent.com/assets/4092794/22195742/70f3b33a-e184-11e6-8131-92666a053603.png)

**Proposed Design**
![1-5 expand share panel](https://cloud.githubusercontent.com/assets/4092794/22195853/0dfe3cf4-e185-11e6-8379-1fb356e1ad90.png)

The measure is uploaded, thanks!
![1-5 expand share panel visual spec](https://cloud.githubusercontent.com/assets/4092794/22195904/409468dc-e185-11e6-838b-cf44214b41ab.png)

**Comment by ianb** [comment]
We are going to wait on the autoopen-share-panel A/B test, which will tell us how useful/important the Share Panel is generally.

**Comment by ianb** [comment]
This icon is no longer present (we removed the image copy)
