### ISSUE TITLE
Details about saved shot are hidden when resizing browser window to simulate mobile view

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2127]
[Affected versions]:
- Nightly 53.0a1
- Mozilla Page Shot 5.0.201701250820

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Perform a shot on the page and save it.
3. Resize the browser window until mobile portrait view size.
4. Observe the saved shot details from the top left corner of the page.
 
[Expected result]:
- All details about saved shot from the top left corner on the page are visible.

[Actual result]:
- The link where the shot was saved, time-stamp and expire day details under the saved shot title are hidden.

[Notes]:
- If the saved shot title is long enough, the title is not truncated and is not entirely visible.  
- Attached a screen recording of the issue:

![page shot mobile view](https://cloud.githubusercontent.com/assets/19226534/22294500/3122c720-e31c-11e6-8612-7c3d95904b00.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
