### ISSUE TITLE
The "Copy Image Text" option from a saved shot is not working on some areas from long pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2128]
[Affected versions]:
- Firefox 50.1.0
- Mozilla Page Shot 5.0.201701250820

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://en.wikipedia.org/wiki/Sun
2. Scroll the page until the "Characteristics" subtitle.
3. Perform a selection over the paragraph and save it.
4. Right click on the saved shot and choose the "Copy Image Text" option.
5. On a text area paste the copied image text.
6. Observe the pasted text.
 
[Expected result]:
- The text is correctly pasted.

[Actual result]:
- The saved shot link is pasted instead of the copied image text.

[Notes]:
- Attached a screen recording of the issue: https://goo.gl/w6J9Zy.
- Here is a screen shot with browser console errors:
![copy text image](https://cloud.githubusercontent.com/assets/19226534/22295868/11bffbfa-e321-11e6-9035-880f77d7abf4.png)

**Comment by wresuolc** [comment]
We don't support this currently
