### ISSUE TITLE
Notify user when Full Page is cut off

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2129]
We have a 5000px limit to images, even Full Page.  People hit that and then are confused why the images are limited.  We should tell them.

**Comment by 6a68** [comment]
Actually, I think this needs product:

- Do we really need to max the height at 5k? If it's just text on a white background, the resulting image might not be that big, compared to a high-res video or gradient background. Bigger, related question: what should we do if a screenshot is too big (filesize)? Should we warn the user or just lossy-compress the image or...?
- If we want to keep this restriction, should we warn users when they hover the 'shoot full page' button? should we create a selection box 5000 pixels high, then scroll down to its bottom edge, and then show a warning along the lines of "Screenshots can't be more than 5000 pixels long, so stuff below this line will not be included"?

**Comment by johngruen** [comment]
@ianb do we have a histogram of shot sizes somewhere. that would be cool to have in general? we might be able to reason about lifting or pushing out the restriction. Otherwise, maybe just an alert box for now?

**Comment by jscher2000** [comment]
In Nightly on Windows, "Save Full Page" gives me an image silently truncated at a height of 6250 pixels, while the fullpage tool gives me all 8818 pixels. Someone using "Save Full Page" for research/documentation purposes will be sorely disappointed to discover it is not actually the full page. Could you display a warning and offer the other function instead? E.g., "Page exceeds current maximum height for Save Full Page. [Save Partial Page] [Download Instead] [Cancel]"

**Comment by thekyriarchy** [comment]
What's the reason for the limit? Could users at least change a setting to lift it? 

also #220 for changing filetype for large shots

**Comment by beingalink** [comment]
In combination with #3215 or #3479 the 5000px limit becomes a problem rather quickly.

**Comment by ianb** [comment]
Roughly the UX proposed is to just put a little text on the full page preview:

![image](https://user-images.githubusercontent.com/44390/30757388-26686c10-9f94-11e7-8537-b9ecb133da7d.png)

**Comment by johngruen** [comment]
@ianb 

Here's what this should look like:

<img width="1103" alt="screen shot 2017-09-25 at 3 26 19 pm" src="https://user-images.githubusercontent.com/3323249/30826930-44fdce44-a206-11e7-9561-29b1b43444f8.png">

The string is:
`Full page shots are limited to 5000px for now.`

Here's the styles i used to mock that element up:

```
  background: rgba(0,0,0,.8);
  bottom: 0;
  color: #fff;
  font: message-box;
  padding: 10px;
  position: absolute;
  text-align: center;
  width: 100%;
  z-index: 2;
```

Note, that message should only appear if the image is cut off.
