### ISSUE TITLE
Explore where embeds are coming from

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2133]
We should investigate HTTP headers from popular embedding services to see if we can learn about where embeds are viewed. If possible we should send an event back to tell us what services embeds are being viewed in so that we can optimize against that case

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
