### ISSUE TITLE
Implement overlaid menu UI

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/screenshots#2135]
Follows up the latest UX spec, the overlaid menu haven't implemented accordingly. 

Current
![pageshot menu](https://cloud.githubusercontent.com/assets/4092794/22318384/0326f262-e3b5-11e6-9539-2a87962ae500.png)

UX proposed design
![1-2 full page hovered](https://cloud.githubusercontent.com/assets/4092794/22318385/0ddf0884-e3b5-11e6-94e3-d61aa92763de.png)

The measurement is attached below, and [the link](https://www.dropbox.com/sh/ojayi19kll69zam/AAAaqSkjoZ1JOCHU6sP8Lh2pa?dl=0) to all the assets, let me know if any questions.
![1-2 full page hovered visual spec](https://cloud.githubusercontent.com/assets/4092794/22318410/49e1cd1c-e3b5-11e6-8092-733ef5d73c66.png)

**Comment by johngruen** [comment]
Obviated by Photon
