### ISSUE TITLE
The "Remove Page Shot data" page is wrongly titled as "Confirm account deletion"

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#2140]
[Affected versions]:
- Firefox 51 and up
- Mozilla Page Shot 5.2.201701261556

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest version of the Page Shot add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any page.
2. Click on the Page Shot button from the browser toolbar.
3. Click the "My Shots" button.
4. Click the "Remove all Data" from the bottom right part of the page.
5. Observe the tab title.

[Expected result]:
- The tab title reflects data deletion process.

[Actual result]:
- The tab title is "Confirm account deletion".

[Notes]:
- Here is a screen recording with the issue: 
![remove page shot data tab](https://cloud.githubusercontent.com/assets/18304511/22372277/6f01c17a-e4a4-11e6-9bab-00a9cef0377c.gif)

**Comment by ianb** [comment]
@johngruen says there should also be a Page Shot icon on the confirmation page

**Comment by wresuolc** [comment]
Marking as a good first bug because this is just changing a string.  Let's change it to "Remove All Data"  (with the capitals)
