### ISSUE TITLE
[Enhancement] "Page Shot" button should be inactive on certain about:* pages 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#2141]
[Notes]
- Because you can't take a shot of about:config, about:preferences, about:addons it would be better for the toolbar button to either be inactive on these pages or to have a message be displayed explaining why you can't take a shot.
- Trying to take a shot of about:support, about:debugging or about:home works.
- Trying to take a shot of about:newtab redirects you to "My Shots"

[Affected versions]:
- Firefox 51 and up
- Mozilla Page Shot 5.2.201701261556

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest version of the Page Shot add-on was previously installed on a clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to about:config.
2. Click on the Page Shot button from the browser toolbar and observe the behavior.

[Expected result]:
- The Page Shot button is inactive.

[Actual result]:
- The Page Shot button is active, but it does not enable the overlay.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/UOIjc9

**Comment by ianb** [comment]
We're now disabling the button for these pages (done in PR #2368)
