### ISSUE TITLE
[Enhancement] Shots titles should have a character limit or they should be truncated after a specific numbers of characters

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2147]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Page Shot add-on was previously installed on the profile from "https://pageshot.dev.mozaws.net/homepage/install-test-local.html".

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from the browser toolbar.
3. Perform a selection an save it.
4. Click on the saved shot title and change it with a long string.
5. Observe the new title of the shot in preview page .
6. Click the "My Shots" button from the top right of the page.
7. Observe the new title of the shot.

[Expected result]:
Step 4: - A "character limit" warning is displayed for the long string. 
or
Step 5 & 7: - The long title is displayed as truncated on both pages. 

[Actual result]:
- There is no character limitation for shot rename and there is no truncation on the pages where it is displayed.

[Notes]:
- The large shot title also affects the shots from "https://pageshot.dev.mozaws.net/shots" page. All the thumbnails from the same row will gain the same dimension as the one with the long title.
- Here are some screen shots with the issue:

![title saved page shot](https://cloud.githubusercontent.com/assets/19226534/22749278/6a61c67a-ee35-11e6-8b89-0e38f5b13317.png)

![saved shot tile](https://cloud.githubusercontent.com/assets/19226534/22749283/6d6b6786-ee35-11e6-931c-856b3b5e8b28.png)

**Comment by ianb** [comment]
Let's do a 140 character limit on display (we'll keep saving the full title).

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and the long title is correctly displayed as truncated on "My Shots"page.

But, if you click the "trash" icon, the title is not truncated in the displayed "delete" dialog.
Here is a screen recording:
![shot title](https://cloud.githubusercontent.com/assets/19226534/25128647/121773b8-2443-11e7-9d37-c74a1c20cc4b.gif)
