### ISSUE TITLE
Design: do we want to keep /domain in URLs

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2149]
A design question for launch: do we want to keep the URLs like `/lksoi39s/foo.com` or just use `/lksoi39s` ?

**Comment by pdehaan** [comment]
Ref: https://discourse.mozilla-community.org/t/why-include-the-domain-name-in-the-url/11179

**Comment by jvehent** [comment]
This came up as a potential privacy leak during the security review. I think we should remove the domain and avoid the risk entirely.

**Comment by jvehent** [comment]
In addition,we must absolutely remove query string parameters from the "Saved From" URL, as those will often contain secret data.

**Comment by wresuolc** [comment]
There are two issues we're talking about here:

1) (the original issue) Should we keep /domain.com in the URL

2) Should we link to the complete URL on the page (we do today and @jvehent's latest comment is referring to this).  URLs often contain hashes and such, as well as "private unless you know the URL" things like google docs which could leak with this.

@johngruen -- this seems to be a product decision

**Comment by dannycoates** [comment]
is this closed by #2451?

**Comment by ckprice** [comment]
This is not a security issue, but we should check with legal (wil adding to next meeting).

**Comment by ckprice** [comment]
Brian doesn't think this will be an issue as long as it's accurate. Let's keep it.
