### ISSUE TITLE
Analyze: can we keep configurable backend?

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2150]
It's unclear to me if it's possible to make the backend/server configurable with a WebExtension: we may have to hardcode the backend into `manifest.json` (as a permission).  In that case then if anyone wants to use a different backend they'll have to deploy a completely different build of the add-on.  This is a bit of a bummer, as people like to know they can change out the backend (even if it's not that easy to do, as you have to host your own Page Shot server).

I'm not confident of what we can do yet (it depends if I ultimately need to add `<all_urls>` permission to the extension), so this ticket is to track what we learn.

**Comment by johngruen** [comment]
Jared and Ian to discuss this at some point in the future.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
