### ISSUE TITLE
Design: download for Save visible and Save full page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2157]
Right now we have a noticeable inconsistency where you can download a selection, but not the other options.

**Comment by johngruen** [comment]
I think this is a stretch based on the current flows i've seen. Would be nice to resolve, but i don't think it blocks launch.

**Comment by johngruen** [comment]
This was my idea...asking design to go ahead and take a look
![select list shot button 1](https://cloud.githubusercontent.com/assets/3323249/24128888/4e2e5e60-0db5-11e7-93c1-85e0f9fd2bcc.png)
![select list shot button 2](https://cloud.githubusercontent.com/assets/3323249/24128889/4e307d94-0db5-11e7-962c-6903b6f63bce.png)

**Comment by ianb** [comment]
I'm having a hard time putting my finger on why, but in this model it feels like "Save full page" is a modifier on the selection action, as opposed to an entirely separate action.  Maybe because it looks like a select box and so it's not obvious that each item is actually an action with immediate effects.

**Comment by ChenMorpheus** [comment]
We tried several mockups and decided to go this proposal since it's more consistent to the current regional crop. In short, when users choose to have a full page shot, we offer them the preview of the final result to decide if download or crop. Please find the link below for the prototype and let us know your thoughts or the feasibility, thanks.

https://mozilla.invisionapp.com/share/BJB0YYB9W#/225402436_2-1_Shot_page_right_side_menu_-2-

![2 5 save fullpage](https://cloud.githubusercontent.com/assets/18019946/24339285/50f6a558-12dd-11e7-99bc-faad5adbc3b1.png)

**Comment by dannycoates** [comment]
Should this still be in Milestone 54?

**Comment by johngruen** [comment]
@ianb is this feasible? would be a good follow on in 56?

**Comment by ianb** [comment]
Outside of the UI implementation itself, implementing download-full/visible-page is very simple. The only blocker to this has been the UI to actually ask for it to be downloaded.

**Comment by johngruen** [comment]
@ianb i guess my question is does the proposal that @ChenMorpheus made in the screenshot above look feasible...if you click the invision link, you can see a stepwise version of the same. password = testpilot (password not intended to be cryptographically secure)

**Comment by johngruen** [comment]
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Build ID: 20170529030204

Steps to reproduce:

I'm on FF Nightly 55.0a1 (2017-05-29) (64-bit) -  It seems as of this release, Firefox Screenshots go straight to the cloud by default?

I work for a large financial organization that takes security very seriously and will not allow Firefox to be installed if this is the default behaviour.   (they made me uninstall GreenShot which is open source, but enables uploading to imgur by default).

At the very least, there should be separate build for 'Enterprise' grade installs which disconnect from the cloud completely.  



Expected results:

- Scissor icon should not show
- If it does show, disable option to upload to the cloud

**Comment by fangshih** [comment]
![2 5 save fullpage](https://user-images.githubusercontent.com/4862573/27315788-48eca13c-55ae-11e7-8864-cd677d8ff40f.png)

Here are the assets and measurement. 

Assets: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets

Measurement: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Save%20fullpage/

**Comment by niharikak101** [comment]
Thank you! @fangshih

**Comment by fangshih** [comment]
Hey @niharikak101 
I was thinking for the transition of this view, maybe we can have it with the image fade in ( short ) plus a slight bounce in. Keep it very simple and slick. Thanks! :)
