### ISSUE TITLE
Write up Intent To Implement

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2168]
We should probably write an email to firefox-dev per convention.

**Comment by ianb** [comment]
I'll write this up in a Google Doc and distribute before emailing.

**Comment by 6a68** [comment]
Gdoc is here: https://docs.google.com/document/d/1cHq_j_dfccnTTxPOfHigVwj5_EkGJg6L46i-J8le7GU/edit?ts=58dab4e6

**Comment by ckprice** [comment]
Shipped https://mail.mozilla.org/pipermail/firefox-dev/2017-March/005249.html
