### ISSUE TITLE
We need a new Favicon

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2171]
[Notes]:
- The Page Shot tab favicon is also hardly visible on Firefox High Contrast themes and other 3rd party darker themes.
- On specific themes the Page Shot favicon is hardly visible even if the tab is not focused.

[Affected versions]:
- Aurora 53.0a2

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Page Shot add-on was previously installed on the profile from "https://pageshot.dev.mozaws.net/homepage/install-test-local.html".

[Steps to reproduce]:
1. Open the Developer Edition bowser with the profile from prerequisite and navigate to any website.
2. Click the Page Shot button from the browser toolbar.
3. Perform a selection an save it.
4. Observe the Page Shot tab favicon.
 
[Expected result]:
- The Page Shot favicon is perfectly visible.

[Actual result]:
- The Page Shot favicon is hardly visible.

[Additional Notes]:
- Attached a screen shot with the issue:

![untitled](https://cloud.githubusercontent.com/assets/19226534/22979860/80626e78-f3a0-11e6-8435-6a4d7fbb0442.png)

**Comment by dannycoates** [comment]
We might be able to use the `browser_style` thing for this. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action

**Comment by pdehaan** [comment]
I think @ianb added the `browser_style` thing to addon/webextension/manifest.json in [#2377](https://github.com/mozilla-services/pageshot/pull/2377/files#diff-edd690115570044e76445f43adc8ba8bR28):

```js
"browser_style": false
```

Although the I believe `false` is the default value. So sayeth [the docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/browser_action#Syntax):

> Although this key defaults to `false`, it's recommended that you include it and set it to `true`.

**Comment by ianb** [comment]
`browser_style` won't do anything, I'm afraid, it just applies to panels.  There isn't a panel, so I added it just to make a warning shut up.  

Note though that this ticket is for the favicon, not the toolbar, so this is entirely a website issue.  Maybe we want a background on our favicon?

**Comment by 6a68** [comment]
If this bug is about the colors in the favicon, that doesn't seem like a beta blocker. Removing that label; feel free to re-add it if I'm missing something.

**Comment by SoftVision-CosminMuntean** [comment]
Since the new Firefox Compact themes will enter in Firefox 54 release, I have also checked how the Screenshots tab favicon  behaves on them. It seems that we have the same issue described above, using "Compact Dark" theme.

Here is a screenshot with Screenshots tab favicon on Compact Dark theme:
![favicon](https://cloud.githubusercontent.com/assets/19226534/25437329/a6afc12c-2a9e-11e7-82a0-b4473a0e7b8d.png)
