### ISSUE TITLE
Ensure S3 instances are deleted when shot is deleted

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2173]
Looking in `servershot.js` I don't see evidence that the images are deleted.

**Comment by jvehent** [comment]
We confirmed that images are not deleted from S3 today. This must get fixed before the launch.
Because of that, we also must not copy the data from the experiment over to the new storage bucket. Users may have deleted shots that haven't been removed from S3 and must not be carried over.

**Comment by msujaws** [comment]
Does this issue have the proper tracking items on it to make sure that it is resolved prior to launch? We shouldn't be keeping personal data on the server if the user requested it deleted.
