### ISSUE TITLE
Create log messages for 404

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2176]
Anytime you get a shot 404, we should log that in a standard/documented mozlog formatted message

**Comment by dannycoates** [comment]
I don't know about screenshots' deployment, but in fxa we had nginx log status codes, etc. What is the intended use for having 404's in the app logs?

**Comment by ianb** [comment]
It's a sign that someone might be fishing for shot URLs

**Comment by dannycoates** [comment]
> It's a sign that someone might be fishing for shot URLs

Seems like something IP rep service should do https://github.com/mozilla-services/screenshots/issues/2252
