### ISSUE TITLE
Use node-jsx

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2190]
[node-jsx](https://www.npmjs.com/package/node-jsx) would let us avoid building the jsx files.

We'd have to rename jsx files to be `.jsx`, which seems fine.

After this we'd still have to do the browserify steps for the server build, but nothing else.

**Comment by pdehaan** [comment]
**PROTIP:** If we rename files to .jsx, we'll probably also have to tweak the ESLint configs so that it searches both .js and .jsx extensions.

For example, here's the npm script we use for [**pulse**](https://github.com/mozilla/pulse/blob/7deb3c912fca6eb85c7453a0462610f6aaaf9eab/package.json#L65):

```js
"lint:js": "eslint . --ext .js --ext .jsx",
```

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
