### ISSUE TITLE
Don't let users click `Back` from shot pages after taking shots

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#2193]
After taking a shot it will open a new tab to the shot detail page, and then I can click "back" to an empty previous page like this:
![image](https://cloud.githubusercontent.com/assets/8919308/23199611/5bd6b8e2-f90a-11e6-8228-127d1209c212.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
