### ISSUE TITLE
Prevent pop-up dialog will disable "Delete" function temporarily

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#2194]
In the shot detail page if I keep clicking delete button it will show this on the second time:
![image](https://cloud.githubusercontent.com/assets/8919308/23199636/95f30ddc-f90a-11e6-96ef-8a4321f47793.png)

And if I check the checkbox, then the next time I click delete button, nothing will happen because the pop-up dialog is prevented.

**Comment by shiri04** [comment]
I would like to work on this issue !
