### ISSUE TITLE
Use jpeg for large shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#220]
Full-screen screenshots tend to get big as pngs, I think at some resolution we should start using jpg.

- [x] Allow JPEGs on the server (there are many places where we force PNG)
- [x] Generate JPEGs on the client when the PNG is too large
- [x] Do some experimentation to figure out when JPEG is right, what the quality level should be, and maybe if we should bail out of JPEG if it doesn't improve the PNG enough. (E.g., I think the typical Wikipedia page should end up in PNG, but an image-heavy page should end up as JPEG)

**Comment by thekyriarchy** [comment]
It would be nice to let the user choose the format, but perhaps default to an automatic mode that decides what formats are best for what sizes. There are some screenshot tools that can save to SVG, but that's probably overkill as much as i'd enjoy it

**Comment by ianb** [comment]
Some stats:

```
imgur.com (no infinite scrolling):
PNG: 6,230Kb
JPEG/std: 20%
JPEG/0.9: 18%
JPEG/.95: 25%
JPEG/.99: 41%
JPEG/1.0: 50%

imgur.com (up to 5000px limit):
PNG: 13,149Kb
JPEG/std: 19%
JPEG/0.9: 17%
JPEG/.95: 24%
JPEG/.99: 40%
JPEG/1.0: 48%

wikipedia/pokemon page:
PNG: 1,843Kb
JPEG/std: 213%
JPEG/0.9: 193%
JPEG/.95: 264%
JPEG/.99: 432%
JPEG/1.0: 487%

gify (note images unload when not viewed):
PNG: 2265Kb
JPEG/std: 36%
JPEG/0.9: 33%
JPEG/.95: 43%
JPEG/.99: 75%
JPEG/1.0: 87%
```

I'm going to try a 2.5Mb limit.

**Comment by teohhanhui** [comment]
Currently, when I use the "Download" button (save locally) it saves as JPEG, with no option whatsoever to save as PNG. But strangely if I use the "Save" button (upload to the server) I actually get to download in PNG?

I can understand the choice of converting to JPEG when uploading to the server, but please stick to PNG for the local file. Or at least provide the UI / settings (or at the very least, a pref) to control this.

I wouldn't wish a lossy screenshot on anyone.
