### ISSUE TITLE
Add PropTypes to React components

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2209]
Ref: https://github.com/mozilla-services/pageshot/pull/2196#issuecomment-281806842

Which overrides the following rule (from "plugin:react/recommended"):

```yaml
react/prop-types: off     # TODO: change to "error"
```

If I enable the `react/prop-types` rule and set it to an "error", I get the following (where the 6 warnings were the existing warnings, and the 239 errors are new):

```
✖ 245 problems (239 errors, 6 warnings)
```

---

For more information on React PropTypes, see https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by chenba** [comment]
This was done as part of #4077
