### ISSUE TITLE
Host static assets in CDN

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2210]
This probably isn't too hard, as `staticLink()` is already used on all these links, so we'd just make that one function CDN-configuration-aware.  @relud is going to give a suggestion on how this is configured from ops (the variable to look for, and how we use that variable to construct a URL).

**Comment by relud** [comment]
I'm really flexible on this, so my suggestion doesn't need to be set in stone.

I would have `STATIC_URL=https://pageshot.cdn.mozilla.net/static/` or `STATIC_URL=https://pageshot-cdn.net/static/` and construct the urls as `staticLink(a){return config.STATIC_URL + a}; link = staticLink('minified.js')`. The cdn would then use the server as an upstream, so `https://pageshot.cdn.mozilla.net/static/minified.js` would be backed by `https://pageshot.net/static/minified.js`.

**Comment by relud** [comment]
`pageshot.cdn.mozilla.net` has the advantage that we already have an ssl cert for it, and it's already available in all our CDNs, so if we don't use cloudfront (because of the 35KB average request goal), then it wouldn't cost any extra for ssl when hosted on akamai or edgecast.

**Comment by pdehaan** [comment]
Ref: https://www.webpagetest.org/result/170307_MR_1DRW/1/performance_optimization/

![](https://pageshot.net/images/b28cb3c3-39e9-491e-84ce-aa43ec76eba3.png)
