### ISSUE TITLE
React warning while loading shot page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2216]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23284994/5bb80a30-f9e3-11e6-92f6-3e18d612cff5.png)

I'm seeing an error when I try and load the following shot page: https://pageshot.net/PNDTvTF1Q6jgffrZ/testpilot.firefox.com

> _Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:_
> 
> &nbsp;&nbsp; (client) ="Page-Shot-2017-2-23 Firefox Test Pilot
> &nbsp;&nbsp; (server) ="Page-Shot-2017-2-24 Firefox Test Pilot

**Comment by chenba** [comment]
Reopening this because setting the NODE_ICU_DATA env var is not working when deploying to dev.

**Comment by ianb** [comment]
In other places we use a pattern like this to find the location of a library:

    $(node -e 'console.log(require.resolve("raven-js/dist/raven.js"))')

In the past I've found libraries aren't installed into entirely stable locations, and this helps.

**Comment by chenba** [comment]
In this case, full-icu is not a js module to be required; [the dir of a data file needs to supplied to node, either through env var or command line option](https://nodejs.org/api/intl.html#intl_providing_icu_data_at_runtime).

I have verified that the ICU data file is in the latest docker image and in the expected path.

**Comment by chenba** [comment]
Looks like the cause is likely a node version mismatch.  It's 8.2.0 during the build, but the docker image is running 8.10.0.  This resulted in the wrong version of the ICU data being in the docker image.
