### ISSUE TITLE
Implement Telemetry

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2218]
We should probably use [scalars](http://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/scalars.html).  This would be something like:

```js
Services.telemetry.scalarAdd('SCREENSHOTS_CLICK_BUTTON', 1);
Services.telemetry.scalarAdd('SCREENSHOTS_DOWNLOAD', 1);
Services.telemetry.scalarAdd('SCREENSHOTS_UPLOAD', 1);
Services.telemetry.scalarAdd('SCREENSHOTS_CANCEL', 1);
Services.telemetry.scalarAdd('SCREENSHOTS_ERROR', 1);
```

All of these (`SCREENSHOTS_*`) have to go in [Scalars.yaml](http://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/scalars.html#the-yaml-definition-file) in the main Firefox source.

Note: we have to do this in bootstrap.js.

**Comment by ianb** [comment]
On reflection and given #2222, I think we'll just do something simpler than the experiment and use ad hoc messaging

**Comment by wresuolc** [comment]
I think we can remove this from `beta blocker` and Page Shot in 54 milestone?

**Comment by johngruen** [comment]
I'm not sure what we gain over our current data-collections.

@ianb tempted to close this

**Comment by 6a68** [comment]
@johngruen let's do this for 58! could you take a pass at the scalar names?

**Comment by ianb** [comment]
We should ask Georg Fritzsche for review on this

**Comment by 6a68** [comment]
patch datareview+ and r+ in bug 1412411. PR incoming
