### ISSUE TITLE
Add X-Content-Type-Option: nosniff

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2219]
Per [this report](https://github.com/mozilla-services/foxsec/wiki/Latest-pageshot.net) we should add [X-Content-Type-Option](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options).  Would probably go in the same place the CSP policy goes (in `server.js`).

**Comment by g-k** [comment]
+1 

link to the recommendation: https://wiki.mozilla.org/Security/Guidelines/Web_Security#X-Content-Type-Options
