### ISSUE TITLE
[Forums] Privacy notice: Mozilla, but Google Analytics

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2231]
&mdash; via https://discourse.mozilla-community.org/t/privact-notice-mozilla-but-google-analytics/13831

> **Shnoulle:** On the Page shot privacy notice : https://pageshot.net/privacy, I see the Mozilla part, but pageshot.net have google-analytics
> ```html
> <script src="//www.google-analytics.com/analytics.js" async=""></script>
> <script src="/ga-activation.js?rev=ee7d282">
> ```
> Then the privacy notice must inform clearly mozilla can not control this external privacy part.

---

> **fzzzy:** The privacy notice on https://testpilot.firefox.com/experiments/page-shot more specifically describes that we gather usage data. We gather this usage data using google analytics. I agree that the pageshot.net site should be clearer on this topic.

**Comment by zeddmaxx** [comment]
Hello!
I would like to work on this task, if there is anything I should keep in mind before starting please let me know.
Thanks

**Comment by wresuolc** [comment]
We're using the cloud services privacy notice now (https://www.mozilla.org/en-US/privacy/firefox-cloud/) so I'm going to close this.

@zeddmaxx thanks for offering, but looks like this one is closed from other changes on the site.  Feel free to check out the other open issues! :)
