### ISSUE TITLE
Document dev group

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2248]
We have a group:

https://discourse.mozilla-community.org/c/test-pilot/page-shot-dev

Email alias:

testpilot+page-shot-dev@mozilla-community.org

This should go in README, we should review the group, and we need to email everyone currently involved in the project to get them watching the group, then we need to double check those people actually receive notifications and updates.

**Comment by ianb** [comment]
As a first bug, you don't have to email everyone to tell them about the group, since you won't know who "everyone" is ;)

**Comment by shiri04** [comment]
@ianb Can you explain in detail about this

**Comment by ianb** [comment]
For this, all I think we need is something in README.md pointing to the group, and giving instructions about how to post (maybe pointing to the Discourse signup instructions).

There's also a possibility that people who sign up can't post for a while (some Discourse policy)... but I'm not sure?  You could do a test post to confirm that the instructions work.

**Comment by 6a68** [comment]
> There's also a possibility that people who sign up can't post for a while (some Discourse policy)... but I'm not sure?

Once someone has actually created a Discourse account, they should be able to post to the mailing list without problems: https://bugzil.la/1325128

**Comment by wresuolc** [comment]
We need to update the email alias to not be page shot ^
