### ISSUE TITLE
Integrate IP reputation service

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2252]
We should feed information about 404s into our IP reputation service (404s could indicate an attempt to scrape our site for pages)

**Comment by wresuolc** [comment]
is "our IP reputation service" something that exists that ops already runs?  If so, is this an ops bug?

**Comment by ianb** [comment]
Yes, this is something that we already run.  But we need to figure out how to feed our 404 information to this service.

**Comment by 6a68** [comment]
I'm pretty sure this is it: https://github.com/mozilla/fxa-customs-server

**Comment by 6a68** [comment]
Hmm. Maybe I'm wrong and this is actually it https://github.com/mozilla-services/ip-reputation-js-client

**Comment by 6a68** [comment]
OK, this is the IP reputation service: https://github.com/mozilla-services/tigerblood

and there's an [empty repo](https://github.com/mozilla-services/ip-reputation-python-client) for a python client.

**Comment by wresuolc** [comment]
@glasserc @jvehent Is this something you can help us with?  Do you already have this set up that we could hit?  Are there docs to connect?  None of us have any experience with this.

Also, this is in our blocking-launch milestone, but I don't feel like this should block.  Do you consider this a launch requirement?  Thanks

**Comment by jvehent** [comment]
@g-k is your guy.

**Comment by wresuolc** [comment]
sorry, auto-completed the wrong g!

**Comment by g-k** [comment]
Happy to help with this! We need to test the python client library too.

I don't consider it a blocker for 54.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
