### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by PRiMENON** [mozilla-services/screenshots#2256]
This service will upload screenshot images to https://pageshot.net/.
When I searched for "site: pageshot.net" on Google, I noticed that the screen shot image was crawled and cached.
I thought that this service could not be accessed by anyone unless you set up sharing like Google Doc.
Even after the expiration date of the screen shot image, the <title> information of the saved website, the location information of the website (including the path of the local drive data) can be viewed, and some privacy Information may be saved.
You should set robots.txt at https://pageshot.net/ to avoid crawling. Also, it should be set so that it will not be exposed to the outside unless you configure the settings shared by users.

>robots.txt
>---
>User-agent: *
>Disallow: /

**Comment by ianb** [comment]
Note that while there are search results for pages on pageshot.net, each of these was posted somewhere public before it was crawled.  There's no public index of shots on pageshot.net, but if you post a link somewhere then a bot can access the page.

It's the same as with a Google Doc, where if you make it visible to anyone with the link and then post the link somewhere, anyone (including bots, I think?) can access it.

**Comment by jvehent** [comment]
I agree that we should have robots.txt in place before going live. Search engine crawling is not a feature of this service and could lead to privacy issues.

**Comment by PRiMENON** [comment]
Thanks a lot!
