### ISSUE TITLE
Change uses of XMLHttpRequest to fetch

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2261]
The [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is the more modern alternative to using XMLHttpRequest.  We still have some uses of XMLHttpRequest in `addon/webextension/` and these could be replaced.  (We have some fetch examples too that you can use for reference.)

**Comment by pgadige** [comment]
I'd like to work on this issue. Could please assign it to me. Thank you.

**Comment by ianb** [comment]
@pgadige : I can't seem to assign it to you, but I'll assign it to myself so someone else doesn't take it (but I'll leave it to you to make the patch!)

**Comment by pgadige** [comment]
@ianb thank you very much for holding it up. Could you please try to assign it to me again, now?

**Comment by ianb** [comment]
Seems like there isn't activity on this, resetting assignment

**Comment by ianb** [comment]
I started this in the branch [xmlhttprequest-to-fetch](https://github.com/mozilla-services/screenshots/tree/xmlhttprequest-to-fetch), but after doing this I'm feeling uncomfortable with the amount of logic being moved around at this late date.  I don't think this work should be done until after our first release.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
