### ISSUE TITLE
Put in instructions on PostgreSQL setup

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2263]
In the [README](https://github.com/mozilla-services/pageshot#installation-and-setup) it says to connect to Postgres, but doesn't give much help about authentication.  Different platforms and installers set things up differently, but without experience with Postgres isn't not obvious how to get things setup.  Probably the best solution is to link to some appropriate documentation.

**Comment by shiri04** [comment]
For ubuntu version there is postgresql 9.4 is not working which is mentioned in main website .

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
