### ISSUE TITLE
"Not yet implemented" pop-up appears after removing all Page Shot data

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2269]
[Affected versions]:
- Nightly 54.0a1 (Build ID: 20170303030202)	
- Page Shot 5.2.6242

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.6242) custom build is installed on a new clean profile.
- Have multiple saved shots on the created profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Go to "My Shots" page (https://pageshot.dev.mozaws.net/shots ).
3. From the footer of the page click the "Remove All Data" link.
4. Click the red "Proceed" button.
5. Observe the browser behavior.

[Expected result]:
- All the Page Shot data is deleted and you are redirected to the "Leave Page Shot complete" page.

[Actual result]:
- "Not yet implemented" pop-up is displayed even if all the Page Shot data is deleted.

[Notes:]
- Here is a screen recording with the issue:

![not yet implemented](https://cloud.githubusercontent.com/assets/19226534/23557611/405332fe-0039-11e7-925a-f667cc7f9d3d.gif)

**Comment by ianb** [comment]
We need a product decision on what it should do (#2270), and then revisit this.

**Comment by 6a68** [comment]
this might also be related to pref-flipping (#2333)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that this issue is no longer reproducible on the latest Firefox Screenshots (5.2.7676) version. The "Not yet implemented" pop-up is no longer displayed.
