### ISSUE TITLE
Build DMCA capabilities

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2288]
This is an MVP for 54 launching (all server side).

- [x] Some kind of database flag to mark content as DMCA flagged
- [x] Modify shot detail page to show a DMCA message instead of the content
- [x] If original poster loads the page, provide instructions (an email) to dispute the claim
- [x] @johngruen please provide DMCA messages to display
- [x] @ianb give ops the steps to set the database flag (and ensure they're onboard. I can help if needed)
- [x] Create DMCA page #2444
- [x] open question: @johngruen should DMCA flagged content still expire as usual? (Elvin is following up on this question. 3/16) -- answer = yes!

**Comment by ianb** [comment]
There should be an optional URL associated with the block, and if that URL is given then we should show it to the owner.  (It would point to, for example, the takedown request.)
