### ISSUE TITLE
Avoid interstitial history page in /creating

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2291]
During upload we navigate from /creating to the shot URL, but that leaves an entry in the history.

In order to fix this we might need to communicate with the page itself and use `location.replace()`.  Right now the page just sits around passively.

**Comment by ianb** [comment]
Note that generally site-helper needs some revamping first, if we expect the creating page to handle location.replace.

Also we should guard against the creating page failing, and navigate the page forcefully after a timeout.  Pages don't load up entirely and other stupid little errors that we can't entirely avoid.

**Comment by johngruen** [comment]
@ianb to dupe this once the other issue is found!

**Comment by ianb** [comment]
Not a dup, but #3219 would invalidate the need for this bug
