### ISSUE TITLE
Hook up Pontoon

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2295]
This is blocked by extracting strings from the addon (#2294).

See the [Pontoon MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website#C._Add_your_project_to_Pontoon) for details on filing the correct bugzilla bug.

**Comment by 6a68** [comment]
also refs #2205

**Comment by 6a68** [comment]
Once 2294 lands, open a bug at [this URL]() with subject "Enable Pontoon for Page Shot add-on (excluding website)" and the following body:
```
This bug covers localization of just the strings that will ship in the Page Shot system addon. We'll handle the website in a separate bug.


Answering the questions listed on the Implementing Pontoon MDN page[1]:

- Project name: Page Shot (the name is not final)

- Repository URL: https://github.com/mozilla-services/pageshot/

- List of requested locales: I believe we want all the locales, since this will be shipping in Firefox as a system addon.

- Website URL: The website isn't yet localized, and the final domain name choice is blocked on the unresolved naming choice.


[1] https://mdn.io/Implementing_Pontoon_in_a_Mozilla_website#C._Add_your_project_to_Pontoon
```

**Comment by 6a68** [comment]
Filed [bug 1347219](https://bugzilla.mozilla.org/show_bug.cgi?id=1347219). Keeping this open as a tracking bug.

**Comment by 6a68** [comment]
Got an update on this issue from @johngruen today: looking at next week for final strings. We should be good to start localization after that.

**Comment by johngruen** [comment]
I should have an initial PR tomorrow

**Comment by 6a68** [comment]
Final strings just landed in the repo. Closing out this bug. For final updates, watch the Bugzilla bug.
