### ISSUE TITLE
Host images on an isolated domain

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/screenshots#2300]
Images must not be served via the main pageshot domain to reduce the risk of an image-based XSS stealing the user's cookies.

**Comment by dannycoates** [comment]
Is there any dev work remaining for this?

**Comment by johngruen** [comment]
@ianb bumping this issue. can we close?

**Comment by ianb** [comment]
Right now this is working because @relud setup an nginx response filter that rewrites image links to the new host. That's a pretty fragile solution, so we still need to do this properly.  Probably all that means is using `config.contentOrigin` in the right place.

**Comment by johngruen** [comment]
@ianb should be add another row in the x-functional doc for this?

**Comment by ianb** [comment]
It's just normal server engineering, there's nothing exceptional about this. We've mitigated the security concern, but need to do some followup work.
