### ISSUE TITLE
Enforce PNG check when posting images

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/screenshots#2301]
Only images in PNG format must be permitted through the pageshot app when a user posts a new shot. The app must check the magic number of the image.

`PNG image files begin with an 8-byte signature which identifies the file as a PNG file and allows detection of common file transfer problems: \211 P N G \r \n \032 \n (89 50 4E 47 0D 0A 1A 0A).`

**Comment by jvehent** [comment]
Also, when uploading to S3, the content type should be forced to `image/png`.

**Comment by ianb** [comment]
Note: moving to the 54 Milestone (to show we need it for 54), but removing the beta blocker label, as those are for tickets that are required for the add-on landing in 54 beta (while this is a server requirement).

**Comment by jvehent** [comment]
That would be preferable indeed if the computing cost is within limits.
It does bring the issue of crashing the process with malformed images, and other vulnerabitilies in image libraries (yurk, imagemagick...).

**Comment by g-k** [comment]
ulfr pointed out this blog post on idat chunks too: https://www.idontplaydarts.com/2012/06/encoding-web-shells-in-png-idat-chunks/

**Comment by g-k** [comment]
The Firefox Accounts profile server uses reviewed code for handling PNG and JPEG uploads for avatars that would probably be helpful.

https://github.com/mozilla/fxa-profile-server/blob/05ae545aba1044700b1952e9916f9b817daf3e2b/lib/compute/index.js#L79

https://github.com/mozilla/fxa-profile-server/blob/b6a2816914b05c99c8c43b5be2b452d2966f3f93/lib/config.js#L90
