### ISSUE TITLE
Record if pageshot is enabled or not via Telemetry

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2304]
We're shipping a system add-on that is always enabled (according to Firefox), but we want to roll it out slowly as well as offer people the option to disable it.  To do that, we're going to add a pref that the add-on reads on startup and if the pref is off the add-on will just return early and not load any of its code.

However, we also want to report whether the add-on considers itself enabled or disabled to Telemetry.  We can do that cheaply by add-on to the DEFAULT_ENVIRONMENT_PREFS variable at https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/TelemetryEnvironment.jsm#121 .

We need to choose a pref name.  I'll throw out: `extensions.screenshots.system-disabled`

Edit: I guess we should figure out the name of the add-on and then sub that in for pageshot

Edit 2:  While we're here, let's also report `extensions.screenshots.disabled` (see #2333)

**Comment by ianb** [comment]
See also #2247

**Comment by wresuolc** [comment]
@Standard8 is this something we can include in the other landing patches?

**Comment by Standard8** [comment]
@wresuolc I've just updated the patch on [bug 1346825](https://bugzilla.mozilla.org/show_bug.cgi?id=1346825) with the prefs.

**Comment by wresuolc** [comment]
Thanks!

**Comment by Standard8** [comment]
Patch is now up for review on [bug 1346825](https://bugzilla.mozilla.org/show_bug.cgi?id=1346825)

**Comment by Standard8** [comment]
The bug has landed on inbound and seems to be sticking, so I'll close this now.
