### ISSUE TITLE
Implement shooting page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2306]
In order to implement we need the following:
- [ ] ux spec with measurements, button states, colors etc
- [ ] svg image assets

**Comment by TLHuang** [comment]
The measurement is ready, please refer to [Shooting Page Measurement](https://www.dropbox.com/sh/n9zxt0u7y65og5g/AABYBQwURWCUYk3R5542h0tHa?dl=0), and the svg assets are uploaded to [the asset folder](https://www.dropbox.com/sh/ojayi19kll69zam/AAAaqSkjoZ1JOCHU6sP8Lh2pa?dl=0), the face icon is also included. All the screens for Shooting Pages you can find them [here].

**Comment by youwenliang** [comment]
As for the interaction for the eyeballs, check out this example:
http://codepen.io/youwenliang/pen/YZQbBG
