### ISSUE TITLE
Implement onboarding

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2307]
In order to implement we will need: 
- [ ] Full spec with measurements, button states, colors, etc
- [ ] All icons provided as SVG
- [ ] Rough WIP strings for the spec (I'll cover string review separately)
- [ ] full set of state diagrams explaining various flows into and out of onboarding.

There's a stretch from acceptance that indicates we might want a secondary method of triggering onboarding if a user doesn't engage w/in 3 weeks. It would be nice to see this in the flow diagram for the spec.

**Comment by fangshih** [comment]
For the onboarding visual spec, most of the spec are ready. 
We will need to provide the illustration part later on with Sean's support. 

But here are the measurements  :
https://www.dropbox.com/sh/9u9040bwuohedf4/AABhzuzB1yX82hn1_tu04iKqa?dl=0

icon assets: 
https://www.dropbox.com/sh/skfyxqt1i0b782v/AAA-0r5-SSNVSL5EBOpxiVlla?dl=0

Onboarding screens: https://www.dropbox.com/sh/zkb6xrkkv9wusoz/AAAyLrGVDnKDB2odTPxayKEga?dl=0

Please let me know if you need anything else. Thanks :D

**Comment by ckprice** [comment]
> Onboarding screens: https://www.dropbox.com/sh/zkb6xrkkv9wusoz/AAAyLrGVDnKDB2odTPxayKEga?dl=0

Clarifying question:

- screen 1 shows the browser just after Firefox install with the Screenshots icon "starred"
- screen 2 shows the FTU modal _after_ the user has clicked on the Screenshots icon (e.g. it doesn't automatically pop up), correct?

**Comment by fangshih** [comment]
Hey @ckprice, That is correct! 
For the "starred" icon we may redesign the icon itself later on. But everything else is the same. : )

**Comment by 6a68** [comment]
what needs to happen to close this bug?

**Comment by ianb** [comment]
I think we can call it closed – we have some followup bugs and @johngruen did a UI review
