### ISSUE TITLE
Implement Shots Index Page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2308]
This is the page that shows the collection of the user's shots. 

The spec should include: 
- [ ] dimensions, colors, button states for the page including
- [ ] a version of the page with no shots taken
- [ ] search interactions
- [ ] a full set of svg icons for the page

**Comment by TLHuang** [comment]
The measurement for Shots Index Page is ready, please refer to [Shots Index Page Measurement](https://www.dropbox.com/sh/pogikv8l1fom6h3/AACNN8n1jwjCWMmmdp8hzx0Oa?dl=0), and here is the link to [all the assets](https://www.dropbox.com/sh/ojayi19kll69zam/AAAaqSkjoZ1JOCHU6sP8Lh2pa?dl=0). Here you can preview [all Shots Index screens](https://www.dropbox.com/sh/imqqjilakq2oraj/AAAM-ugP3_N3ctbEGfUWerNLa?dl=0) which are covered in the measurement. 

The transition of expanding search bar will be updated soon. Let me know if anything else is still needed. Thanks!
