### ISSUE TITLE
Implement Page Shot Landing Page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2310]
We need a public landing page for Page Shot. See [acceptance](https://github.com/mozilla-services/pageshot/edit/master/docs/acceptance.md) for full set of criteria. 

- [ ] Full spec with measurements, colors, button states, etc
- [ ] All icons provided as SVG or 1x/2x PNG
- [ ] Rough WIP strings for the spec (I'll cover string review separately)
- [ ] complete spec should include messaging if a user visits in different contexts (chome, mobile, etc.)

**Comment by johngruen** [comment]
@youwenliang is going to take this issue for us provisionally. 

@youwenliang you should make all changes in this file: https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/homepage/view.js (aside from image assets obviously. Just write the CSS and JSX that works for you and i can help you land it!

**Comment by fangshih** [comment]
Here are the image assets for the landing page 
https://www.dropbox.com/sh/2pjmo9edi0llpwf/AAB_dgZq8sp2YG_QtMo4vk8_a?dl=0

Measurement spec
https://www.dropbox.com/sh/fq1ov476sbqvuf6/AAAcFcpAWv-rpTDQODWJbss7a?dl=0

**Comment by ChenMorpheus** [comment]
Please find the link below for UX spec.
https://mozilla.invisionapp.com/share/6WB6M7LN5#/232296193_Landing_Page_NonFF

**Comment by aminalhazwani** [comment]
@johngruen I noticed that the landing page is set in San Francisco. For all Firefox web properties it's advised to use Fira Sans. See [in progress design system](https://bwinton.github.io/DesignSystem/typography.html). Moreover San Francisco is only available on Apple platforms. What about other platforms? Do you have any particular reason for suggesting system typefaces on the web? If yes, please share! This afternoon CET we are going to meet with shorlander and we can discuss about it. cc @ChenMorpheus

**Comment by johngruen** [comment]
@aminalhazwani i think they they just liked the look...I'm happy to use Fira, we can start implementing with either, and make changes when we have a final decision

**Comment by aminalhazwani** [comment]
@johngruen we talked with stephen, there are few drawbacks when using system fonts. for example we can't control the style if users play around with their platform fonts. if there would be a CSS property we would be more than happy to go with system fonts. that said we highly recommend to switch to Fira Sans for Firefox Screenshots, thanks!

**Comment by ChenMorpheus** [comment]
If the guideline defines Fira Sans as the standard font for all websites relating to Firefox, we'll update the screens and measurements.

**Comment by johngruen** [comment]
closing with the caveat that there edge case bugs to be filed here
