### ISSUE TITLE
Copy to clipboard icon

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2311]
When a user takes a shot and it's copied to clipboard we trigger a push notification...

![screen shot 2017-03-07 at 6 08 39 pm](https://cloud.githubusercontent.com/assets/3323249/23683091/2c949328-0365-11e7-9270-42315f22cc92.png)

The righthand logo comes from the Application, but we might want to use a more Photon friendly copy icon here/

**Comment by TLHuang** [comment]
Update the measurement. Let me know if anything else is still needed.

Icon Asset
https://www.dropbox.com/s/uzgqzd7x1np2lwn/notification-copied.svg?dl=0

Visual Measurement - 4.2 Copied link
https://www.dropbox.com/sh/sdxpisu3x2uflp3/AADbfr0FnbKarpsh_zmtqLKxa?dl=0

Preview
﻿https://www.dropbox.com/s/tg9cq5udyxljuj4/4.2%20Copied%20link.png?dl=0
