### ISSUE TITLE
Implement Shot Page for Owners/Non-Owners

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2312]
This issue will track both owner and non-owner views.

Full acceptance [here](https://github.com/mozilla-services/pageshot/blob/master/docs/acceptance.md)

the spec should provide: 
- [ ] dimensions, button states, colors etc. 
- [ ] all icons for both owner and non-owner views (SVG)
- [ ] Responsive/mobile friendly viersions of each view

**Comment by fangshih** [comment]
For the Non-Owners 

Visual Measurements:
https://www.dropbox.com/sh/r2v5oro1op446kh/AADIJeqeY6aEWrbYZqlexI4ha?dl=0
Button Status:
https://www.dropbox.com/s/w6fq30s7ouy6efm/1.4%20Banner%20spec.png?dl=0

Icon Assets: 
https://www.dropbox.com/sh/skfyxqt1i0b782v/AAA-0r5-SSNVSL5EBOpxiVlla?dl=0

Screens:
https://www.dropbox.com/sh/ffopsk4p0ow7hc8/AACNnNdQiMakhkYflY03KObga?dl=0

For the banner, we will continue to explore more variations.
Thanks!

**Comment by TLHuang** [comment]
For the **Owner** Shot page

Visual Measurement:
https://www.dropbox.com/sh/sdxpisu3x2uflp3/AADbfr0FnbKarpsh_zmtqLKxa?dl=0

Assets:
https://www.dropbox.com/sh/skfyxqt1i0b782v/AAA-0r5-SSNVSL5EBOpxiVlla?dl=0

Screens:
https://www.dropbox.com/sh/obtoj9s11wxrncp/AACi4AFquyhqig8-OKu0CstCa?dl=0
