### ISSUE TITLE
The browser window scroll bars are not working when the Page Shot overlay covers the page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2316]
[Regression]:
- It seems that this issue is not reproducible on Nightly 52.0a1. I have performed a regression using mozregression tools and here are the results:
- Pushlog: https://goo.gl/GQNWuV
- Looks like the following bug has the  changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1324117

[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170307030205)	
- Page Shot 5.2.13477

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.13477) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from browser toolbar.
3. Try to scroll the page using the window scroll bars.
4. Observe the browser behavior.

[Expected result]:
- The page is correctly scrolled and the Page Shot overlay is not dismissed.

[Actual result]:
- The window scroll bars are not working when the Page Shot overlay covers the page.

[Notes:]
- On Mac OS the scroll bar is working only the first time when is used. This behavior is randomly reproducible in Windows.
- If a selection is performed, the scroll bars works as expected.
- Here is a screen recording with the issue:

![page shot overlay and scroll](https://cloud.githubusercontent.com/assets/19226534/23710972/2df207ba-0427-11e7-8f76-218f807a76a3.gif)

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Hey, can you still reproduce this issue? I can't on current nightly or dev edition on mac.

I did notice that arrow keys don't scroll the underlying page, but this is because the iframe takes the focus (for accessibility); once you tab through the frame, through the UI, then you do get the focus back to the content page, and the arrow keys scroll it correctly.

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the issue is no longer reproducible using latest Firefox Screenshots version. Tested on Windows and Mac OS using latest Nightly (55.0a1) build and latest Dev Edition (54.0a2).
