### ISSUE TITLE
Test performance of Firefox with Page Shot on Talos

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2317]
There's a possibility that simply having Page Shot installed will affect the performance of Firefox.  As soon as #2313 lands we should see if this is the case using Talos.

**Comment by Standard8** [comment]
I discovered today that this is how you do it:

* Push a patch to try with Talos runs
* Either compare it against central, or another try push, via

https://treeherder.mozilla.org/perf.html#/comparechooser

I'll update the build patches, then get these pushed.

**Comment by Standard8** [comment]
Try pushes:

* Original: https://treeherder.mozilla.org/#/jobs?repo=try&revision=3a8b5d7fda75c301af5d2f579fc4bbe4b4196203
* With extension: https://treeherder.mozilla.org/#/jobs?repo=try&revision=cdab514f2f8c81c1651db2f2bd27d0549f45adfd
(I exported a3279e2c31f491eebf5b30bd1f6463b07efcb09b)

Compare link (won't work properly until try runs are complete):

https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=3a8b5d7fda75c301af5d2f579fc4bbe4b4196203&newProject=try&newRevision=cdab514f2f8c81c1651db2f2bd27d0549f45adfd&framework=1&showOnlyImportant=0

**Comment by Standard8** [comment]
From what I can tell, the Talos run doesn't show anything we need to worry about, but I've sent an email to jmaher to get extra confidence.

**Comment by 6a68** [comment]
For reference, here's the (Mozilla staff-only) link to the Talos conversation on the screenshots-staff list: https://groups.google.com/a/mozilla.com/d/topic/screenshots-staff/MBCS3GkepII/discussion

**Comment by Standard8** [comment]
Everything looks good - the Win64 tests showed OK as well. So I think we can close this now.
