### ISSUE TITLE
Document or script patch creation

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2319]
After copying files into the Firefox tree (#2318) we need to produce a patch and put the patch in Bugzilla.  This could be documented or scripted, or some combination of the two.

**Comment by Standard8** [comment]
I'd suggest scripted. I had something for Loop that could do this, so I'll see if I can pull it out.

**Comment by Standard8** [comment]
We've now got a scripted way of exporting to mozilla-central (#2407).

I don't have requirements for creating bugs, but it should be pretty easy to adapt https://github.com/mozilla/loop/blob/master/bin/create_release.py to file bugs automatically & post patches. 

The one thing that is slightly different is that the export_mc.py script created in #2407 already does the creating of a branch & commit from which to push the changes. Hence the first part of `releaseMozillaCentral` just needs to make a call to that script.

**Comment by 6a68** [comment]
Hmm. Looking at the create_release.py script, I think it would be good to create a bugzilla component for firefox release requests and security bugs.

**Comment by johngruen** [comment]
Closing for now since current process seems to be working
