### ISSUE TITLE
Implement skeleton MochiTest

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2320]
In the Firefox tree we should have a MochiTest that does functional testing of Page Shot.  Initial work would be a MochiTest in the appropriate place that confirms the Page Shot button is present.

**Comment by 6a68** [comment]
@Standard8 Note that we will be using a second pref, `extensions.screenshots.system-disabled`, to gradually roll out Screenshots as part of the 54 release. While that code will be removed pretty soon after launch, we should probably check for that pref as well in the tests.
