### ISSUE TITLE
Document or script running MochiTest outside of Firefox

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2321]
After #2320 (and improvements on that test) are done, we will want to run the functional tests outside of Firefox, as part of our regular development process.  Running a MochiTest is non-trivial, so we should document or otherwise figure out a reasonable way to do this.

We are currently using both Travis and CircleCI, but only because we haven't turned Travis off.

**Comment by 6a68** [comment]
If we are able to do this, I suspect it would be really useful to publish on github. Future system addons may want to use the same code

**Comment by Standard8** [comment]
Note: there is https://bugzilla.mozilla.org/show_bug.cgi?id=1344268 to get this working for more than just screenshots (activity stream are interested as well). So I think it might be worth following along there & pushing for that.

**Comment by ianb** [comment]
Kicking this back to triage, as we have Selenium tests that cover the same stuff, and while the environment is different (and might fail differently), the value of the MochiTest is less as a result.
