### ISSUE TITLE
"Page Shot went haywire" error is displayed multiple times if the Page Shot button is clicked on "about:*" pages (On Mac OS)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2335]
[Notes]:
- **On Windows the errors are not displayed as system notification, they only appear in the browser console.**
- **On Windows if the Page Shot button is clicked multiple times, the browser becomes unresponsive.** I have noticed that the browser remains this way until all the errors are loaded in browser console. Here is a screen recording with the issue: https://goo.gl/xITz4M.

[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170308030207)	
- Page Shot 5.2.14901

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.14901) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Go to any Firefox "about:*" page (eg: "about:home" page).
3. Click the Page Shot button from the browser toolbar.
4. Observe the browser behavior.

[Expected result]:
- A single "Page Shot went haywire" error is displayed.

[Actual result]:
- 15 "Page Shot went haywire" errors are displayed.

[Additional Notes:]
- This issue depends on the decision that will be reached in issue #2236.
- Here is a screen recording with the issue: https://goo.gl/YFNy7a

**Comment by dannycoates** [comment]
fixed in #2368
