### ISSUE TITLE
The Firefox menu is not dismissed if the "Page Shot" button is clicked from it 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2336]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170308030207)	
- Page Shot 5.2.14901

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.14901) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Right-click on the "Page Shot" button from the toolbar and select the "Move to Menu" option.
3. Click the Firefox menu from the main toolbar.
4. Click on the "Page Shot" button  and observe the browser behavior.

[Expected result]:
- The Firefox menu is dismissed and the Page Shot overlay covers the entire page.

[Actual result]:
- The Firefox menu is not dismissed and the Page Shot overlay covers the entire page.

[Notes:]
- Here is the screen shot with the issue:
![firefox menu vs page shot](https://cloud.githubusercontent.com/assets/19226534/23753409/0e104ca2-04e2-11e7-8b23-a3b8a6d0086a.gif)

**Comment by wresuolc** [comment]
I can't reproduce this in Nightly, but others in this meeting could.  This doesn't feel like a 54 blocker.

**Comment by johngruen** [comment]
Obviated by Photon
