### ISSUE TITLE
Encrypted shots

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/screenshots#2337]
An interesting privacy feature would be to encrypt a shot using [AES-GCM](https://www.w3.org/TR/WebCryptoAPI/#aes-gcm) and store the symmetric key in a URL fragment. Browsers don't send URL fragments to servers, so a user could share the URL with others and we would only store encrypted blobs on the server side.

That would require storing the key that encrypted a shot in local browser storage.

**Comment by jvehent** [comment]
Note: this isn't a blocker to the release in 54, just a wishlist item.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
