### ISSUE TITLE
Page Shot icon from the browser toolbar, is hardly visible on darker themes

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2347]
[Affected versions]:
- Aurora 54.0a2 (Build ID: 20170310004008)	
- Page Shot 5.2.1906

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.1906) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the Developer Edition browser with the profile from prerequisite.
2. Observe the "Page Shot" icon from the browser toolbar.

[Expected result]:
- The "Page Shot" icon has the same color as the others icons from the browser toolbar and is perfectly visible.

[Actual result]:
- The "Page Shot" icon is hardly visible.

[Notes:]
- Here is the screen shot with the issue:
![page shot icon](https://cloud.githubusercontent.com/assets/19226534/23795469/8c59d0bc-059e-11e7-8276-56d0d3f06aaf.png)

**Comment by ianb** [comment]
[Bug 1329242](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) is about this ability.  It's not scheduled for implementation, so the only way to handle this is if we do something fancy in bootstrap.js

**Comment by SoftVision-CosminMuntean** [comment]
Since the new Firefox Compact themes will enter in Firefox 54 release, I have checked how the Screenshots icon behaves on them. It seems that we have the same issue described above, using "Compact Dark" theme.

Here is a screenshot with Screenshots icon on Compact Dark theme:

![screesnshots icon](https://cloud.githubusercontent.com/assets/19226534/25437096/faba4018-2a9d-11e7-967a-b539b79a4a35.png)

**Comment by johngruen** [comment]
This is fixed in nightly
