### ISSUE TITLE
Investigate test failures on mozilla-central when page shot is integrated

### ISSUE THREAD

**Issue by Standard8** [mozilla-services/screenshots#2348]
From #2318:

> In the meantime, here's a simple try push (just tests etc) to check for any adverse impacts:
> 
> https://treeherder.mozilla.org/#/jobs?repo=try&revision=4b6533ee47272f4c8712a081af342cdeef12ae1e

It looks like there's some real failures there, so we'll need to get those fixed before we can land.

**Comment by 6a68** [comment]
@Standard8 Let me know if I can help with fixing the broken tests. I'm sort-of familiar with Gecko, haven't pushed to try since 2014 (and then it was FxOS), but I'd like to learn how this stuff works.

**Comment by Standard8** [comment]
I've just filed a bug on the main mochitest issues (mainly in dom/) here: https://bugzilla.mozilla.org/show_bug.cgi?id=1347482

**Comment by 6a68** [comment]
I looked through the `/browser` breakage in the linux x64 opt failures from the first Try run, and it looked like these were the failures (with some duplication):

  - TEST-UNEXPECTED-FAIL | browser/components/extensions/test/browser/browser_ext_contextMenus_chrome.js | Separator before first extension item - Got menuit
  - TEST-UNEXPECTED-FAIL | browser/modules/test/browser/browser_BrowserUITelemetry_defaults.js | No other test should have left CUI in a dirty state. - false
  - TEST-UNEXPECTED-FAIL | browser/components/sessionstore/test/browser_625016.js | observe1: 1 window in data written to disk - Got 2, expected 1

The third bug is a known intermittent (see bugs 1230992, 1348583) so I have ignored it.

Fixes for the other two are in this patch: https://gist.github.com/6a68/d5d1971cbe3bd4942d366a07707e1532

**Comment by Standard8** [comment]
@6a68 The patch looks reasonable - you probably want to do the preference check for both of the tests.

**Comment by 6a68** [comment]
Turns out that patch fixes the /browser test breakage bugs on my mac, but not on the Try server. Debugging on Try and locally on a linux laptop.

**Comment by 6a68** [comment]
See also #2563 for more discussion of browser/ tests.

Per discussion in the Intent to Implement email thread, I'm changing Screenshots initialization to wait till "sessionstore-windows-restored" before starting the WebExtension. This might break the toolbar button order. Adding a note here for posterity.

**Comment by Standard8** [comment]
Current list of failing tests

- [ ] DOM Tests - I have a WIP patch for some of these, not all.
- [ ] Jetpack - Not tier 1. Currently one test times out.
- [ ] browser/modules/test/browser/browser_BrowserUITelemetry_defaults.js
- [ ] browser/base/content/test/general/browser_tabopen_reflows.js
- [ ] browser/base/content/test/plugins/browser_CTP_drag_drop.js
- [ ] browser/base/content/test/general/browser_contextmenu_input.js (Mac only?)
- [ ] browser/extensions/screenshots/test/browser/browser_screenshots_ui_check.js (on Windows????!!!)
- [ ] browser/components/extensions/test/browser/test-oop-extensions/browser_ext_contextMenus_chrome.js (Windows?)

**Comment by Standard8** [comment]
We now also have a [tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1355569) for this.

**Comment by 6a68** [comment]
Since we've landed with Screenshots preffed off for the tests, I'm going to remove the beta blocker label

**Comment by Standard8** [comment]
I've just created a fresh try push to assess the current state of the tests, especially given the recent landings:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=5841186bab3ee78d630ce86564615646e5fdd11d

**Comment by Standard8** [comment]
I believe my earlier comment https://github.com/mozilla-services/screenshots/issues/2348#issuecomment-293263098 is now up to date with the current status of tests and with bugs filed for all the failures.

**Comment by Standard8** [comment]
The only thing that's really left to do here now is to fix the customisable widgets issues - I've split that out to #2946, so I think this one can be closed.
