### ISSUE TITLE
Rename everything to Screenshots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2378]
We're going to be renaming the product to Firefox Screenshots.  We'd like to rename *everything*.

Here's a basic proposal:

- [x] "Page Shot" is replaced with "Firefox Screenshots" or sometimes "Screenshots" (these are almost all readable text)
- [x] "shots" and "shot" does not get changed
- [x] This repo gets moved to https://github.com/mozilla-services/screenshots
- [x] In CSS classes the string "pageshots" can be **removed**: it was a form of namespacing that we don't really need.  Except for `pageshot-no-pointer-events`
- [x] I'd like to move staging to screenshots.dev.mozaws.net and screenshots.stage.mozaws.net – we should open bugs for that, but can rename now, nothing is automated to make changing the code ahead of infrastructure a problem
- [x] The production domain will change from pageshot.net to screenshots.firefox.com
- [x] In most cases `pageshot` gets renamed to `screenshots`, except when it's some more global label, then we should use `firefox-screenshots`.  E.g., the name in `package.json`
- [x] Addon ID changes to `screenshots@mozilla.org`
- [x] Icons could probably get a better name that doesn't include the product name
- [x] Dockerhub image gets renamed from mozilla/pageshot to mozilla/screenshots
- [x] I guess some of the environmental variables become `SCREENSHOTS_*`
- [x] We don't technically have to change repository URLs (github will redirect) but fixing everything makes it easier to grep
- [x] We rename the channel to `#screenshots`
- [ ] ([bug 1347304](https://bugzilla.mozilla.org/show_bug.cgi?id=1347304)) We should look into renaming the Discourse groups 
- [x] (screenshots-staff@mozilla.com) We could rename pageshot-staff
- [ ] We could look through Google docs
- [x] Outreachy application
- [x] (https://wiki.mozilla.org/Firefox/Screenshots) wiki.mozilla.org
- [x] Rename pageshot-abuse and pageshot-feedback email aliases
- [x] Rename events (METRICS.md and code) ???
- [x] Review GitHub site description
- [x] Add logs.glob.uno logging of #screenshots 
- [x] Make ops bots report to #screenshots ([Bug 1349657](https://bugzilla.mozilla.org/show_bug.cgi?id=1349657))
- [x] Make GitHub bots report to #screenshots

**Comment by pdehaan** [comment]
Are we doing any more Test Pilot releases before we ship in 54? It could be pretty confusing to rename the public discourse forums mid-release (unless we can do a redirect in the forums).

**Comment by pdehaan** [comment]
Also, not sure how other people feel about this, but when we rename IRC channel, not sure if we would maybe also want to add a #screenshots-bots channel where we move all the automated bot chatter.

**PROS:** IRC will actually be usable for conversations/history.
**CONS:** One more channel to monitor (if you care about seeing all the bot comments and traffic).

**Comment by 6a68** [comment]
FWIW, I prefer having the github bot chatter in the channel

**Comment by pdehaan** [comment]
Current status: Looks like most of the remaining instances mostly URLs, IRC channels, some docs, etc.

```sh
$ git grep pageshot | grep -v "/pageshot[/.:]"

.ebextensions/00-environment.config:    value: pageshot.dev.mozaws.net
.ebextensions/00-environment.config:    value: pageshotcontent.dev.mozaws.net
.travis.yml:      - "irc.mozilla.org#pageshot"
README.md:There is an IRC channel `#pageshot` on irc.mozilla.org (you can use [this link](https://kiwiirc.com/client/irc.mozilla.org/pageshot) for chat access via the web if you do not otherwise use IRC).  There are [IRC logs available](http://logs.glob.uno/?c=pageshot).
addon/webextension/manifest.json.template:  "homepage_url": "https://github.com/mozilla-services/pageshot",
bin/release-version:    echo "Stage deployment automatically triggered, see #pageshot IRC for status"
circle.yml:    # we want firefox nightly in order to install an unsigned pageshot addon
docker-compose.yml:  image: pageshot
docs/METRICS.md:We will be tracking some events under `goto-pageshot` that would lead people from shot pages to a place where they could load the page.  Then we track clicking the install link itself, which GA reporting should be able to connect to the original `goto-pageshot` event.  We can't detect how often that install click leads to an actual install.
docs/METRICS.md:1. [x] Toggle shot button on `addon/start-shot/toolbar-button` (previous to 54 launch the label was `toolbar-pageshot-button`)
docs/METRICS.md:29. [x] Visit Screenshots link from footer `web/goto-homepage/footer` (was eventAction `goto-pageshot` before 54 launch)
docs/METRICS.md:5. [x] Click Screenshots link in header `web/goto-homepage/navbar` (was `goto-pageshot` eventAction before 54 launch)
docs/deployment.md:After it completes the stage deployment will automatically be triggered.  See the `#pageshot` IRC channel for status updates.
docs/docker.md:    docker run --net=host -e 'RDS_USERNAME=postgres' -e 'RDS_PASSWORD=********' -e 'RDS_HOSTNAME=pageshot-dev.czvvrkdqhklf.us-east-1.rds.amazonaws.com' -e 'SITE_ORIGIN=pageshotfzzzy.dev.mozaws.net' -e 'CONTENT_ORIGIN=pageshotcontentfzzzy.dev.mozaws.net' -e 'USE_S3=true' -e 'S3_BUCKET_NAME=pageshot-images-bucket' -e 'GA_ID=********' -e 'SENTRY_DSN=********' -e 'SENTRY_PUBLIC_DSN=********' fzzzy/pageshot
docs/testing-the-api.md:  "docTitle": "Screenshots erases everything in my clipboard · Issue #1237 · mozilla-services/pageshot",
server/src/config.js:    default: "pageshot-images-bucket",
server/src/footer-view.js:              <a href="https://github.com/mozilla-services/pageshot" target="_blank">GitHub</a>
server/src/pages/homepage/view.js:            <a href="https://github.com/mozilla-services/pageshot" target="_blank" className="link-icon github" title="GitHub"></a>
server/src/pages/shot/view.js:      // FIXME: consider twitter:site @mozillapageshot
server/src/server.js:      tests: "https://travis-ci.org/mozilla-services/pageshot"
server/src/server.js:      irc: "irc://irc.mozilla.org/#pageshot",
```

**Disclaimer:** I deleted the CHANGELOG.md file since that was particularly noisy.
