### ISSUE TITLE
Expose direct link to image

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2390]
This comes up often when talking to people (came up tonight in a user interview): people want the direct link to the image, but don't know how to get it, or it's too complicated.  It would be nice to address that in the UX somewhere.

**Comment by dannycoates** [comment]
I would prefer this to automatically copying the link on save. I don't appreciate how we currently clobber my clipboard without notice or option not to. Also the notification gets old after the first time. I'd rather copy the link myself. I like how github has a text box and copy button for the clone url.

**Comment by ianb** [comment]
Note this isn't the same issue as auto-copying the shot URL.  This is to URLs like https://screenshots.firefoxusercontent.com/images/2b2b2364-056a-4d8e-b99e-ab7001fc67bb.png (that people have a hard time finding) that are an alternative to the shot URL (e.g., https://screenshots.firefox.com/JrVKenMBJaQJNC3H/www.mozilla.org)
