### ISSUE TITLE
Reconsider use of alert()

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2396]
Ref: https://github.com/mozilla-services/pageshot/search?utf8=%E2%9C%93&q=alert 🔍 

... because `alert()` feels very `<marquee><blink>old school</blink></marquee>`.

**Comment by 6a68** [comment]
:+1: we could use the notification bar for stuff users really need to see, and the browser console otherwise

**Comment by ianb** [comment]
Note the alerts are all used on the web page for request errors.  There might be one that is in a stubbed-out add-on function that needs to be made into a non-stub.

**Comment by pdehaan** [comment]
Apparently we're also using `alert()`/`confirm()` for the delete shot functionality, which gives the user an option to:

> "Prevent this page from creating additional dialogs"

---

```sh
$ git grep -i "alert[(]"

addon/webextension/sitehelper.js:    alert("Not yet implemented");
server/src/pages/metrics/controller.js:      alert("Failed: " + req.status);
server/src/pages/metrics/controller.js:      alert("Failed: " + req.status);
server/src/pages/shot/controller.js:      window.alert("Error saving expiration: " + req.status + " " + req.statusText);
server/src/pages/shot/controller.js:      window.alert("Error deleting shot: " + req.status + " " + req.statusText);
server/src/pages/shot/controller.js:      window.alert("Error saving title: " + req.status + " " + req.statusText);
server/src/pages/shotindex/controller.js:      window.alert("Error deleting shot: " + req.status + " " + req.statusText);
```

```sh
$ git grep -i "confirm[(]"

server/src/pages/shot/view.js:    if (window.confirm("Are you sure you want to delete this shot permanently?")) {
server/src/pages/shotindex/view.js:    if (window.confirm(`Delete ${shot.title}?`)) {
```

**Comment by wresuolc** [comment]
Some of those are good, but the metrics ones should be investigated

**Comment by pdehaan** [comment]
Updated earlier https://github.com/mozilla-services/screenshots/issues/2396#issuecomment-288571468 with latest search results.

**Comment by ianb** [comment]
After all this time... I think the alerts are okay.
