### ISSUE TITLE
404 on site: pageshot-icon-32.png

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2411]
Viewing pages you'll see a 404 for /static/img/pageshot-icon-32.png

**Comment by pdehaan** [comment]
Yeah, even after the renaming, we'll get a 404 if you go to http://pageshot.dev.mozaws.net/favicon.ico (which redirects to /static/img/icon-32.png &mdash; and gives a "Page Not Found")

**Comment by pdehaan** [comment]
@ianb Should we just point to [/static/img/scissors-icon.svg](https://github.com/mozilla-services/screenshots/blob/master/static/img/scissors-icon.svg)?

![](https://rawgit.com/mozilla-services/screenshots/master/static/img/scissors-icon.svg)
