### ISSUE TITLE
Add fake locale

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2417]
To test localization it would be nice if in development we could all use some fake locale, with a fake translation (e.g., a Pig Latin translation, or add accented characters).

We're not sure how to get Firefox to use a fake UI locale.

**Comment by ckprice** [comment]
@flodolo any advice on how to get this going? Is there pseudo locale support we can use for WE's?

**Comment by flodolo** [comment]
Unfortunately I don't think we have anything for this (in general). 

The only place we used to have pseudolocales built-in in the l10n infrastructure was Firefox OS. Gettext has its own pseudolocales, but nothing for webextension, properties, etc.

**Comment by ianb** [comment]
I think since we have actual localizations now, using localized builds is the best way, and let's us check other things in the process.  E.g., load up in Chinese and you can easily see non-localized strings, and also do a visual check for how Chinese looks.
