### ISSUE TITLE
add helpful prefs to profile generated by `run-addon --setup-profile`

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2418]
The `./bin/run-addon --setup-profile` command creates a persistent profile that can be used for local development.

It would be great if that profile setup step included creating a `user.js` file inside the Profile folder, which could be used to automatically set prefs.

One pref that's particularly important to change is the default value of the signature check pref; this could be done via

```js
// inside user.js
user_pref("xpinstall.signatures.required", false);
```

Disabling this pref allows the extension to run in Dev Edition, so that the `./bin/run-addon --binary /path/to/dev/edition` command can run without any twiddling needed in `about:config`. Makes things one step easier for a beginner.

We could also add some prefs to enable verbose system logging, along the same lines of the prefs added by the Devprefs addon, but I'm not sure if this is a good idea or not.

**Comment by johngruen** [comment]
since we're doing this, could we set default search to DDG and about:newtab to the blank screen?

**Comment by garbados** [comment]
Hello!

I'd like to tackle this bug, so I have some questions:
- `bin/run-addon` ultimately passes FireFox the `-CreateProfile [dir]` flag to initialize the user's profile. I can't find documentation for this flag, so I'm not sure how to modify it to facilitate the desired changes.
- To create a `user.js` I imagine one might use prompts to get the necessary information, then fill out a template (ex: `user_template.js`) with those values, generating the `user.js`. Does that seem like a reasonable approach?
