### ISSUE TITLE
Should bootstrap.js errors be sent to Sentry?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2420]
It might be useful to log bootstrap.js errors to Sentry, since the WebExtension could fail to load.

I'm not sure how to do this, because the setup code lives inside the WebExtension, and assumes `auth` has returned the Sentry info. Can we hard-code the Sentry information in the addon, or do we always need to fetch it from the server?

FWIW, I've figured out how to load raven.js inside the bootstrap file:

```js
let Raven;
function initRaven() {
  const { require } = Cu.import("resource://gre/modules/commonjs/toolkit/require.js", {})
  AddonManager.getAddonByID(ADDON_ID).then((addon) => {
    Raven = require(addon.getResourceURI().asciiSpec + 'webextension/build/raven.js');
  });
}
```

**Comment by ckprice** [comment]
Ian noted that having Raven run in the high privileged could be a security risk.

**Comment by ianb** [comment]
This is too hard and too dangerous given the potential benefits.
