### ISSUE TITLE
iframe is not destroyed when WebExtension is shutdown

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2421]
When the WebExtension is disabled, the bootstrap code needs to send a signal to tell the WebExtension, and the WebExtension should tear down any iframes it has added.

Steps to reproduce:

1. start firefox with pageshot enabled
2. open example.com
3. hit pageshot button, iframe appears over page
4. open about:config & disable the webextension by setting the `extensions.pageshot.disabled` boolean pref to `true`
5. switch back to the example.com tab: the iframe is still there, but all the JS has been unloaded, so you can't get rid of it without a page refresh

**Comment by ckprice** [comment]
Don't think we can do, but we could ask in #team-addons

**Comment by ianb** [comment]
Because we don't do much updating, this doesn't feel important. Someone would have to work pretty hard to find this bug now, and it's just a harmless unfunctional interface.
