### ISSUE TITLE
Remove unsafe-inline style-src from CSP

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#2424]
Nice to have.

Can be used to exfiltrate data or deface the site: https://mikewest.org/2013/09/xss-no-the-other-s-cssconfeu-2013

**Comment by ckprice** [comment]
Ian thinks we had a reason why this is here. Nice to have == Next

**Comment by ianb** [comment]
We have a lot of reasons we need to do inline styles.

**Comment by g-k** [comment]
> We have a lot of reasons we need to do inline styles.

@ianb can you elaborate on where or when we need them? This would still be nice to have from a security perspective.
