### ISSUE TITLE
Page Shot button no longer redirects you to the "My Shots" page if it's clicked from Activity Stream New Tab

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2429]
[Notes]:
- This issue is also reproducible for Cliqz New Tab.

[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170320030209)	
- Page Shot 5.2.7704

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.7704) custom build is installed on a new clean profile.
- Activity Stream add-on was previously installed on the created profile. 

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and open a new tab.
2. Click on the "Page Shot" button from the main toolbar.
3. Observe the browser behavior.

[Expected result]:
- You are redirected to the "My Shots" page.

[Actual result]:
- A "No window matching" error is displayed and you are not redirected to the "My Shots" page.

[Additional Notes:]
- With Page Shot Test Pilot version, after clicking the "Page Shot" button you are redirected to "My Shots" page.
- Here is a screen recording with the issue:
![activity stream new tab vs page shot](https://cloud.githubusercontent.com/assets/19226534/24106760/93742f78-0d91-11e7-9e08-feb91a84adf9.gif)

**Comment by wresuolc** [comment]
@dannycoates has a PR that might fix this

**Comment by ianb** [comment]
See the function `shouldOpenMyShots()` for where you'd change this.

**Comment by dannycoates** [comment]
ought to be fix in #2368
