### ISSUE TITLE
Use yarn for package management

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#2430]
see also: https://github.com/mozilla-services/foxsec/issues/134

A compromised package or MITMed dependency could `npm run` arbitrary scripts as part of an install: https://docs.npmjs.com/misc/scripts 

This can be fixed by using `npm install --no-script`.

However, https://yarnpkg.com/ will also validate package contents against a checksum which is preferable.

**Comment by johngruen** [comment]
@6a68 will take a look

**Comment by pdehaan** [comment]
@g-k Do you know if there have been any similar checksum additions in latest npm 5 (which is bundled with recent Node 8)? http://blog.npmjs.org/post/161081169345/v500

I know npm 5 also includes a package-lock.json file (similar to the shrinkwrap.json), but wasn't sure if that offered the same functionality as Yarn.

**Comment by 6a68** [comment]
From a [recent blog post](https://yarnpkg.com/blog/2017/05/31/determinism/) by the yarn team, it seems that the difference is somewhat academic:

> npm 5 has stronger guarantees across versions and has a stronger deterministic lockfile, but Yarn only has those guarantees when you’re on the same version in favor of a lighter lockfile that is better for review.

Are there other compelling reasons to switch?

**Comment by g-k** [comment]
Yeah, this predates npm 5. After finding [this](https://github.com/yarnpkg/yarn/issues/1169#issuecomment-297522516) I'm not sure yarn is necessarily an improvement. I'll do some testing and update this issue.

**Comment by ianb** [comment]
Presumably if we stick with npm we'd still want to generate a lockfile and check it in (which we aren't doing now).

**Comment by 6a68** [comment]
@g-k we're going with the easier `npm shrinkwrap` option for now. feel free to reopen or file a new bug if the recommendation goes back to yarn

**Comment by ianb** [comment]
We never did npm shrinkwrap, and we've had a lot of problems with npm lockfiles. I think we should reconsider yarn.
