### ISSUE TITLE
Error when trying to screenshot mozAddonManager whitelisted URLs

### ISSUE THREAD

**Issue by dannycoates** [mozilla-services/screenshots#2435]
```
Error: No window matching: {"matchesHost": ["<all_urls>"]}
```

**Comment by 6a68** [comment]
Content scripts are disabled on Mozilla sites that are `mozAddonManager` whitelisted. See https://bugzil.la/1310082 for related discussion.

So, the same thing happens on sites like addons.mozilla.org as well.

I'm not sure of the best way to handle this, so I"ll just update the title for now.

**Comment by ianb** [comment]
Probably we should disable Page Shot on these sites.

In generally we should also handle these errors with an appropriate popup.  I.e., catch this error and send `exc.popupMessage="UNSHOOTABLE_PAGE"`

**Comment by 6a68** [comment]
Hmm. We should be able to detect such pages via `'mozAddonManager' in navigator`. If it's true, then bail.

**Comment by ianb** [comment]
I don't believe we can access navigator from the background page.

**Comment by 6a68** [comment]
Good point!

I asked in #teamaddons about the nicest way to do this, and kmag suggested we just check against the whitelist. AMO and Test Pilot are the only two sites on [that whitelist](https://dxr.mozilla.org/mozilla-central/source/browser/app/permissions#18-19), so hard-coding the whitelist seems reasonable.
