### ISSUE TITLE
validate request body objects before parsing as JSON

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#2438]
refs APP-INPUTVAL

Nice to have. 

To prevent insecure property access where a post body like `{"name":{"toString":"OVERWRITE"}}` handled by code like:

```
var o = {};
try {
   o = JSON.parse(req.body)
} catch (error) {
   // silently
}
o.name + ' ok'
```

triggers an error.

It'd be good to validate the incoming objects before parsing (e.g. with [joi](https://www.npmjs.com/package/joi) and [celebrate](https://www.npmjs.com/package/celebrate).

https://github.com/mozilla-services/pageshot/blob/master/server/src/server.js#L593-L603 is great because it resets the object or throws from the catch block preventing the insecure property access, but we could fail earlier and provide more detailed error messages by validating the object in advance.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
