### ISSUE TITLE
UI - Expiration time can't be changed if URL of screenshoted page is too long

### ISSUE THREAD

**Issue by zelitomas** [mozilla-services/screenshots#2441]
If URL is too long, button for changing expiration time overflows out of the screen. - see attached screenshot

![snimek z 2017-03-20 15-42-11](https://cloud.githubusercontent.com/assets/3105674/24126325/a361352a-0dcd-11e7-8f3e-13dab7fd4127.png)

**Comment by wresuolc** [comment]
Let's truncate this somehow

**Comment by ianb** [comment]
This should be re-confirmed given #3186

**Comment by zelitomas** [comment]
Although the bug is not as easy to encounter now because of #3186, you can still see it - 

![](https://screenshots.firefoxusercontent.com/images/84cdff5c-ad0a-4a04-a7f3-f2392c4c628b.png)

(Firefox half-sized on Full HD screen and on longest possible domain name. When testing this, I also found out that if domain name (with subdomains) is too long, it won't even accept your screenshot on the server - reported as #3530)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
