### ISSUE TITLE
Implement DMCA page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2444]
Basically we need some kind of route for owner-views of DMCA'ed pages...I think we can more or less use the UI for expired pages with the the string Brian Smith provided [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1343736). 

"This shot is no longer available due to an intellectual property claim. Please email dmcanotice@mozilla.com to request further information. Please include the URL of this shot in your email: [URL]"

**Comment by 6a68** [comment]
@ckprice This seems like a page on the server. Should it have the beta blocker label?

**Comment by ckprice** [comment]
Nice catch

**Comment by dannycoates** [comment]
fixed in #2709
