### ISSUE TITLE
"Made With Firefox Screenshots" button is wrongly displayed on shared shots

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2454]
[Notes]:
- This issue is reproducible for shared shots if they are opened in different browsers (Chrome, Safari, Edge, IE) or on Firefox if the add-on is not installed.
- Is also reproducible if the shared shot is opened on mobile.

[Affected versions]:
- Page Shot 5.2.2026

[Affected Platforms]:
- All Windows
- All Mac
- All Linux
- All Mobile

[Prerequisites]:
- Have a clean new Firefox profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a shared shot (eg: https://pageshot.dev.mozaws.net/xxnlucUVNhO1uyre/9gag.com).
3. Observe the "Made With Firefox Screenshots" button from the top left corner of the page.

[Expected result]:
- The "Made with Firefox Screenshots" text fits correctly in the button area.

[Actual result]:
- "Made with Firefox Screenshots" text exceeds the button area and the icon is half visible.

[Additional Notes:]
- Here is a screen shot with the issue:
![made with button](https://cloud.githubusercontent.com/assets/19226534/24198598/2aadb9c6-0f0f-11e7-8f72-3573dbd23eac.png)

**Comment by johngruen** [comment]
Fixed by #2685
