### ISSUE TITLE
Implement ability to block a user by UUID

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/screenshots#2457]
In the case of repeat infringers, we want the ability to block a user by UUID.

This begs the question if there should be some kind of auto triggered thing happening, but MVP is that we have a UUID that is violating our terms too much (>3 times), and we can make sure that user is not able to upload more content (by flagging manually in the DB or otherwise).

Not a 54 blocker, but should have priority immediately after 54.

**Comment by ianb** [comment]
We haven't needed this in practice, so closing until/unless we find we do need it.
