### ISSUE TITLE
Resizing window "breaks" selection interface

### ISSUE THREAD

**Issue by dannycoates** [mozilla-services/screenshots#2459]
Example:
<img width="1018" alt="screen shot 2017-03-22 at 10 53 53 am" src="https://cloud.githubusercontent.com/assets/87619/24212873/f522a67a-0eed-11e7-801d-81c1591a74f7.png">

**Comment by ianb** [comment]
Funnily, the maximum width is the width when you made the shot, but otherwise resizing actually works.  That is, you can see it sizing up in response to a resize, until it gets to the original width.
