### ISSUE TITLE
URL flashes and disappears on /shots page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2464]
https://pageshot.dev.mozaws.net/__version__

```json
{
  "source": "https://github.com/mozilla-services/screenshots/",
  "description": "Firefox Screenshots application server",
  "version": "5.2.0",
  "buildDate": "March 22, 2017 20:45:49 UTC",
  "commit": "e6c45b0",
  "commitLog": "https://github.com/mozilla-services/screenshots/commits/e6c45b0",
  "unincludedCommits": "https://github.com/mozilla-services/screenshots/compare/e6c45b0...master",
  "dbSchemaVersion": 15
}
```

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/24224120/ac5bf526-0f16-11e7-94a1-3047ee0db57e.png)

![about_config](https://cloud.githubusercontent.com/assets/557895/24224057/6331396a-0f16-11e7-9aa1-c770fab8aece.png)

---

After installing the add-on from the dev site, I see a brief flash of the URL then it disappears.

![my_shots](https://cloud.githubusercontent.com/assets/557895/24224231/43e5789a-0f17-11e7-810e-72258f3db153.png)

![browser_console](https://cloud.githubusercontent.com/assets/557895/24224240/538a6fd0-0f17-11e7-85d6-d3ad14ee2413.png)

**Comment by ianb** [comment]
I can't seem to reproduce this now.  Maybe URL removal hid the error.
