### ISSUE TITLE
Create a @FirefoxScreenshots twitter account?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2465]
Ref: [/server/src/pages/shot/view.js:120](https://github.com/mozilla-services/screenshots/blob/371c52b67b9920c380c59e12d689e1c6cc899625/server/src/pages/shot/view.js#L120) and [@MozillaPageShot](https://twitter.com/mozillapageshot):

```
server/src/pages/shot/view.js:      // FIXME: consider twitter:site @mozillapageshot
```

**Comment by ckprice** [comment]
We should at least squat the account before launch.

**Comment by pdehaan** [comment]
FWIW, we squatted the mozillapageshot Twitter but never tweeted from it.

**Comment by johngruen** [comment]
Created
