### ISSUE TITLE
Limit the DB privileges of the application user

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/screenshots#2468]
Pageshot currently uses an owner account to interact with its postgres database. There are no restrictions as to what that account can do, including dropping all tables and rows from the DB. This increases the impact of a potential SQL injection unnecessarily.

A separate application user should be created with limited permissions managed in SQL files and updated as any other DB change.

**Comment by ianb** [comment]
For 54: the app server that does the migration should have full permissions, and all other application servers should only have SELECT, INSERT, UPDATE, and DELETE

I think @relud can do all of this on his side?  Right now the application server doesn't have any notion of users itself, it just connects with whatever the configuration indicates.

**Comment by relud** [comment]
I can do all of this on my side, but until we separate db migrations from the controller tasks container I will need to be notified whenever a table is added and manually add permissions for that table. After that I can make the permissions automatic.

**Comment by relud** [comment]
done, and I ran across a setting I had forgotten, so this will persist automatically.
