### ISSUE TITLE
Use crypto.timingSafeEqual for secret comparision

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#2470]
[server/src/users.js line 18 in hashMatches](https://github.com/mozilla-services/screenshots/blob/05c2a000a0e233ea8f6364c893d02bd94ada4b98/server/src/users.js#L18
) should use [crypto.timingSafeEqual](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_timingsafeequal_a_b) to prevent leaking password information via timing attacks.

**Comment by ckprice** [comment]
@g-k is this a 54 blocker? Snuck past our labeling

**Comment by g-k** [comment]
@ckprice I don't think so, but it would be better to have sooner than later.  Timing attacks are hard to carry out in practice and calls to endpoints that hit this should be rate limited.
