### ISSUE TITLE
Update privacy links

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2476]
All privacy links should link to: https://www.mozilla.org/privacy/websites/

The privacy content in the server itself should be removed.

**Comment by cecilebertin** [comment]
Hi @ianb , 

I would like to work on this bug.
Can you assign it to me?

**Comment by akankshapanda** [comment]
Hello @ianb ,

Is it too late to ask about working on this bug?

**Comment by cecilebertin** [comment]
Hi @akankshapanda,
I am almost done with it.
