### ISSUE TITLE
Remove references to Firefox Screenshots being "an experimental extension"

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2478]
In this case, I was testing an existing shot in a not logged in Chrome browser, so the mention of getting Firefox now seems reasonable, but we may want to reword "experimental".

![untitled_document](https://cloud.githubusercontent.com/assets/557895/24309740/3feae864-108a-11e7-8bc2-98cfd61a2c3f.png)

---

```sh
$ git grep experimental
```

- [server/src/pages/legal/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/legal/view.js#L16):
    > “Firefox Screenshots” is an **experimental** add-on and service exclusively available to Test Pilot users.

- [server/src/pages/legal/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/legal/view.js#L28):
    > These Terms of Service ("Terms") govern your use of Firefox Screenshots (defined below), an **experimental** service available to Test Pilot users. “Firefox Screenshots” includes all of the the following:

- [server/src/pages/legal/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/legal/view.js#L63):
    > These Terms will continue to apply until ended by either you or Mozilla. You can choose to end them at any time for any reason by deleting all of your Shots, uninstalling the Firefox Screenshots **experimental** add-on and discontinuing your use of Firefox Screenshots.

- [server/src/pages/legal/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/legal/view.js#L111):
    > Firefox Screenshots is an **experimental** service for Test Pilot users that allows them to capture, save, and share images of webpages (“Shots”). For Test Pilot users of the Firefox Screenshots add-on and Firefox Screenshots service, the data we collect is described in the Firefox Screenshots Test Pilot experiment page and in the <a href="https://testpilot.firefox.com/privacy" target="_blank">Test Pilot Privacy Notice.</a>

- [server/src/pages/shot/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/shot/view.js#L321):
    > Firefox Screenshots is an **experimental** extension for Firefox. <a href={ this.props.backend } onClick={ this.clickedInstallExtension.bind(this) }>Get it here</a>

- [server/src/pages/shot/view.js](https://github.com/mozilla-services/screenshots/blob/c00c6c3ae9d51fd02c8abe24b8526f7a210e0771/server/src/pages/shot/view.js#L328):
    > Firefox Screenshots is an **experimental** extension for Firefox. <a href="https://www.mozilla.org/firefox/new/?utm_source=screenshots.firefox.com&utm_medium=referral&utm_campaign=screenshots-acquisition" onClick={ this.clickedInstallFirefox.bind(this) }>Get Firefox now</a>

**Comment by dannycoates** [comment]
done
