### ISSUE TITLE
Plan server/add-on launch (doesn't block landing in Firefox)

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2479]
When Screenshots lands in any version of Firefox, it needs to connect to a real server.  We have some small (probably backward-compatible) changes to the server, so that the current version of the add-on can't use the current pageshot.net deployment.

**Comment by ckprice** [comment]
Current plan is pageshot.net shares a db with screenshots.f.c. We should test that the code runs with the migrations.

This needs to happen before it is turned on in Firefox, but not necessarily done before we land in Firefox.

**Comment by ianb** [comment]
Plan:

- [ ] Do #2531, tag pageshot.net
- [ ] Change migration to leave in [version 15](https://github.com/mozilla-services/screenshots/blob/master/server/db-patches/patch-14-15.sql) but not the [version 14](https://github.com/mozilla-services/screenshots/blob/master/server/db-patches/patch-13-14.sql) changes which would be incompatible with the old version
- [ ] ops is going to do some fancy redirect stuff to make images work without app changes
- [ ] update stable to master
- [ ] Address some private security bugs: #2331, [Bug 1351265](https://bugzilla.mozilla.org/show_bug.cgi?id=1351265), [Bug 1348958](https://bugzilla.mozilla.org/show_bug.cgi?id=1348958), [Bug 1349073](https://bugzilla.mozilla.org/show_bug.cgi?id=1349073) – including on pageshot.net
- [ ] Test in stage that the current add-on works
- [ ] Test if the SDK add-on works with master, or how far off it is (we don't *have* to support the SDK add-on with master, but should see if we can)
- [ ] Test in prod (screenshots.firefox.com) if the add-on works

**Comment by ianb** [comment]
I moved this checklist to #2537, closing the planning itself
