### ISSUE TITLE
Contact Easy Screenshots authors

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2484]
[Easy Screenshots](https://addons.mozilla.org/en-US/firefox/addon/easyscreenshot/) is an add-on developed by Mozilla China and shipped with that version of the browser.  We should sync up with them regarding the launch.

**Comment by dannycoates** [comment]
done https://docs.google.com/document/d/1smcaqAQjW252UhEL0w0XRnAiDt_KWuOGwqgtv6wE1uY/edit
