### ISSUE TITLE
Triage: upload retry

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2490]
In the SDK add-on we did retries on upload.  We haven't implemented that for the WebExtension.  Do we want to?  GA has some information about how often it was used when it ultimately succeeded.

Note if we implement, there are metrics specific to retry that we should reimplement.  If we decide not to implement this we should update METRICS.md to deprecate those events.

**Comment by johngruen** [comment]
Yes, we should do this, but maybe this is a feature we could patch with a balrog push in the 54 beta timeframe?
