### ISSUE TITLE
Login error popup renders poorly

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2505]
After #2504 lands, if you run the add-on and leave the server off and save a shot, you'll get a login connection error.  The popup looks like:

![image](https://cloud.githubusercontent.com/assets/44390/24418816/e8a5417c-13b2-11e7-869a-4deed09611f6.png)

This is based on `LOGIN_CONNECTION_ERROR` in senderror.js.  Obviously not a great message.  I actually don't understand quite why it renders like this.

**Comment by 6a68** [comment]
Thanks to the string changes that landed yesterday, this looks a wee bit more comprehensible (in English, but probably not in German...)

![screen shot 2017-03-29 at 8 50 37 am](https://cloud.githubusercontent.com/assets/96396/24463859/dc6cb28c-145c-11e7-94d0-5d610b6e592f.png)

But...why don't we see the 'connectionErrorDetails' string in either case? That might be another bug here

**Comment by 6a68** [comment]
Hmm, even after fixing the little bug in the notifications, the strings are clearly too long:

![screen shot 2017-03-30 at 1 00 36 pm](https://cloud.githubusercontent.com/assets/96396/24523748/fb86f6ea-1548-11e7-9e21-5367ca60a51d.png)

Adding 'needs UX' to decide whether we should just move these error messages back into an `alert()`, where they would actually fit.

**Comment by johngruen** [comment]
Everything is hard. Alerts suck, but might be the better path here. Whatever we do, let's please KEEP IT SIMPLE!

**Comment by ianb** [comment]
We can't do alerts from every context, only from the selector/content worker.  Specifically we can't do it from the background page.  There's errors that occur without any such worker.
