### ISSUE TITLE
Implement filtering on Raven

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2510]
We want to be extra sure that we don't submit the URL the user is visiting to Sentry.  For this purpose we should scan the data before submission to Sentry.

I propose we scan for:

1. The full URL
2. The full URL minus the hash
3. Origin + any path (something like `/{origin}[^\s>"]*/`)

In each case we would replace the value with some specific dummy value.  If 3 is the same as `backend` then we don't need to filter it out.

This can be implemented with [dataCallback](https://docs.sentry.io/clients/javascript/config/).  It will have to scan the entire submitted object for those strings, without attempting to understand the object.

**Comment by ianb** [comment]
I realized the code here is wrong: it's using `window.location.href` *of the background page*.  It has to use the content worker.  Probably the filtering should go in shooter.js, in the `catcher.registerHandler` call.

**Comment by dannycoates** [comment]
> Probably the filtering should go in shooter.js, in the catcher.registerHandler call.

Yeah, makes sense. I originally thought the raven callback would be better so it would catch any metadata raven itself added, but since raven only lives in the background it can't access the content url.
