### ISSUE TITLE
Should the context menu item have an icon?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2514]
One of these things is not like the others:

<img width="247" alt="screen shot 2017-03-28 at 2 06 05 pm" src="https://cloud.githubusercontent.com/assets/96396/24427437/c74b18e6-13bf-11e7-90b5-a65f96a66488.png">

Do we really need an icon next to a context menu item?

**Comment by SoftVision-CosminMuntean** [comment]
On windows the icon is positioned differently and looks better. Probably because Windows has a different context menu than Mac OS.

![screenshots context menu](https://cloud.githubusercontent.com/assets/19226534/24442457/ee455914-1466-11e7-9c94-7963efea13b8.png)

**Comment by 6a68** [comment]
Thanks for the Windows screenshot, @SoftVision-CosminMuntean, but my concern is that no other item in the context menu has an icon except Screenshots.

@TLHuang @johngruen For uniformity with other built-in Firefox features, it kinda seems like we should skip the icon in the context menu?

**Comment by ckprice** [comment]
Ian thinks this is a thing WebExt auto does. @johngruen thoughts?

**Comment by johngruen** [comment]
@6a68 looks like @ianb is right, if a WebExtension registers a `menuitem` it gets the icon bound to it. The amount of work to override seems out of proportion with the resulting uniformity.

Closing due to MEH
