### ISSUE TITLE
Firefox Screenshots pages are wrongly rendered on Internet Explorer browser

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2516]
[Affected versions]:
- Internet Explorer 11
- Page Shot 5.2.10545

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open the Internat Explorer browser.
2. Navigate to a someone else's shot (https://pageshot.dev.mozaws.net/DkwWKUqnYZqq8asG/www.amazon.com).
3. Observe the shot details page.
4. In a new tab navigate to "My Shots" page  (https://pageshot.dev.mozaws.net/shots).
5. Observe the "My Shots" page.

[Expected result]:
- The pages are correctly rendered.

[Actual result]:
3. The footer links and the shot image are wrongly positioned on the page. 
5. The footer links are wrongly positioned on the page.  

[Notes]:
- Here are two screen shots with the issue: 
![ie1](https://cloud.githubusercontent.com/assets/19226534/24455021/d22646dc-1496-11e7-95b3-b21d304480d8.png)
![ie2](https://cloud.githubusercontent.com/assets/19226534/24455023/d653c734-1496-11e7-8d8c-de877a99abf4.png)

**Comment by johngruen** [comment]
Actual action here is to look up automated UI testing

**Comment by 6a68** [comment]
Assigning myself to verify this error still occurs with new UX

**Comment by 6a68** [comment]
Yup, error still occurs in IE 11 / win 10.

Looks like `.clip-container` has 0 height.

I think this is https://github.com/philipwalton/flexbugs/issues/58; changing the flex shorthand [on `.clip-container`](https://github.com/mozilla-services/screenshots/blob/master/static/css/frame.scss#L39) to `flex: 0 auto`, as mentioned in that bug, does fix the bug on IE. I don't see any breakage introduced by tweaking the flex shorthand, but turning over to @johngruen to investigate further.

**Comment by 6a68** [comment]
Also, note that modern.ie does still exist, so everyone can enjoy these quirky M$ bugs: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by 6a68** [comment]
I"ll just open a PR with the CSS change and john can review

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and the Screenshots pages are better rendered. But, the footer links doesn't have a fixed position and the image is not displayed on the center of the page.

Here is a screenshot with the issue:
![ie](https://user-images.githubusercontent.com/19226534/28465768-a6e84fe2-6e32-11e7-9d85-df2f540cbc40.png)
