### ISSUE TITLE
If the Firefox Screenshots was never used and you access someone else's shot, you are not automatically log in

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2518]
[Affected versions]:
- Firefox 54.0a2 (Build ID:20170328004003)
- Page Shot 5.2.10545

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (5.2.10545) custom build is installed on a new clean profile.
- The Firefox Screenshots was never used on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Manually navigate to a someone else's shot (https://pageshot.dev.mozaws.net/DkwWKUqnYZqq8asG/www.amazon.com).
3. Observe the shot preview page.

[Expected result]:
- You are automatically log in and you can observe that the shot is not yours.

[Actual result]:
- The log in never happens and the shot preview page is display as you don't have the Screenshots installed.

[Additional Notes]:
- A different behavior can be observed if a selection is saved or you navigate to "My Shots" page, then restart the browser. When navigate to someone else's shot, you will get log in and the page is displayed as you don't have the Screenshots installed. Here is a screen recording with the described behavior: https://goo.gl/6B2X0N.  
- Here is a screen recording with the issue: https://goo.gl/4FTlW4.

**Comment by ckprice** [comment]
We should get all the different cases with the banners figured out before launch.

**Comment by johngruen** [comment]
#2560 might give us a solution here if we decide to go with option 3, will wait for comment from matt on that one before providing direction
