### ISSUE TITLE
If you navigate to "My Shots" page on IE or Edge browsers, you are not redirected to the Firefox Screenshots homepage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2519]
[Affected versions]:
- Page Shot 5.2.10545

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the IE or Edge browser. 
2. Manually navigate to "My Shots" page (https://pageshot.dev.mozaws.net/shots).
3. Observe the browser behavior.

[Expected result]:
- After a delay, you are automatically redirect Firefox Screenshots homepage. 

[Actual result]:
- You are not redirected to the Screenshots home page, you are stuck on the interstitial page with "Looking for your shots..." message displayed in the center of the page.

[Notes]:
- Here is a screen recording with the issue:
![ie](https://cloud.githubusercontent.com/assets/19226534/24456118/abd81efc-149a-11e7-993c-930bee8d09d2.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
