### ISSUE TITLE
If Firefox Screenshots was never used and you manually navigate to "My Shots" page, the login never happens

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2520]
[Notes:]
- The same behavior can be observed if you manually navigate to "My Shots" page on a Private Window, even if you are already logged in.
- The issue is also reproducible if you manually navigate to "My Shots" page after the Firefox Screenshots is installed.

[Affected versions]:
- Firefox 55.0.3 and above 
- Screenshots 10.12.0 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots is installed on a new clean profile.
- The Firefox Screenshots was never used on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Manually navigate to "My Shots" page (https://screenshots.firefox.com/shots).
3. Observe the browser behavior.

[Expected result]:
- The "My Shots" page and is loaded correctly.

[Actual result]:
- The "My Shots" page is loaded, but a "Server error" is displayed on the page.

[Additional Notes]:
- After each refresh an error is displayed in console. Here is a screenshot with browser console errors: https://goo.gl/uMrkZU.
- Here is a screen recording with the issue: https://goo.gl/5yvJdh.

**Comment by johngruen** [comment]
I think the user should just be navigated to the homepage

**Comment by SoftVision-CosminMuntean** [comment]
I have updated this issue due to the fact that the behavior is a little bit changed.

This issue is also reproducible the Screenshots buttons is clicked from "Library" panel. After the button is clicked the "My Shots" page is opened but a "Server error" is displayed on the page.

Here is a screen recording with the issue:
![server error](https://user-images.githubusercontent.com/19226534/29967691-8ca242dc-8f20-11e7-9f2f-31032de0bae8.gif)

**Comment by ianb** [comment]
Current behavior is that you get this page for a bit:

![image](https://user-images.githubusercontent.com/44390/30343792-5b3ae72e-97c4-11e7-9ab6-06732eedda7f.png)

Then in 2-3 seconds you get directed to the homepage. Arguably you should be directed to `/#hello` or `/#tour`. @johngruen : are there any changes here that you think we should make?

**Comment by metasieben** [comment]
Is there any way to >login< to screenshots?
Somehow I'm only able to use screenshots on one of my computers, while every other one refuses to show the >My Shots< screen. Sync/Firefox Account is activated and working afaict.

**Comment by wresuolc** [comment]
Not blocking anything, but John would like to see this redirect to `/#tour` immediately instead of after a few seconds.

@metasieben I'd suggest opening a new bug about why one of your computers refuses to show the my shots screen.

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean can you reverify

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on latest Nightly 59.0a1 build with Screenshots 25.0.0 and also on Screenshots 28.0.0 dev version. Tested on Windows 7 x64, Mac 10.12 and Ubuntu 14.0.4 x64.

Now if you manually navigate to "My Shots" page and you never used Screenshots, the "My Shots" page is loaded and the "Looking for your shots..." message is displayed. After a few seconds the page is reloaded and the "No saved shots. Go on, create some." message is displayed.
