### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2521]
@relud is setting up a separate dev instance for us, to replace pageshot.dev.mozaws.net.

To deploy to this we need to build a docker image and upload it to `mozilla/screenshots` on dockerhub.  `./bin/release-version stage` pretty much does this, and we can use that as the basis for a dev release.  I believe CircleCI would be the appropriate place to do this.  We would have to get permissions setup so it can connect to dockerhub, and so it has authentication to produce signed XPIs.

Right now we might be only building the webextension/ portion in `make signed_xpi`, which doesn't exactly match the bootstrap.js add-on we ship.  We should consider what we want to do here.

**Comment by relud** [comment]
2 notes: 1) for dev i can also deploy `mozilla/pageshot:latest`, 2) I can get you permissions to push the images and file prs to get them pushed

**Comment by relud** [comment]
https://screenshots.dev.mozaws.net is up

**Comment by ianb** [comment]
I'll be updating `./bin/release-version dev` to do the right thing.

Environmental variables we need: `AMO_USER` and `AMO_SECRET` to sign the xpi.  `~/.docker/config.json` must be setup, or some form of `docker login` must be done.

CircleCI docker instructions: https://circleci.com/docs/1.0/docker/

I'm not sure how to store the AMO credentials.  CircleCI discourages any such storage: https://circleci.com/docs/1.0/environment-variables/

The only idea I have for this is to make the add-on ID configurable at build time, and create an account that can build that, and then the risk of putting those secrets in CircleCI is less.  Or we just build an unsigned add-on, which maybe is okay (or at least not terrible).  

There's also a question about whether we ship the bootstrap add-on or the WebExtension add-on.  I believe the bootstrap add-on will stop being installable, and the WebExtension will be OK for localization purposes.

**Comment by ianb** [comment]
Let's start without any add-on signing, and update the install page to give instructions on how to turn off the signing requirement.
