### ISSUE TITLE
[l10n] Add-on buttons are too narrow for localization

### ISSUE THREAD

**Issue by flodolo** [mozilla-services/screenshots#2523]
This is how Italian currently looks like

<img width="182" alt="schermata 2017-03-30 alle 00 10 46" src="https://cloud.githubusercontent.com/assets/3644868/24478975/740ab118-14dd-11e7-9e91-ba4ab379c090.png">

**Comment by adamkalis** [comment]
Same for the greek version:

![screenshot from 2017-03-30 10-05-53](https://cloud.githubusercontent.com/assets/767939/24491866/e9c78d32-1531-11e7-804f-735b356b77d7.png)

Doubling the width (from 136px to 272px ) of the button works fine at least for the greek version:

![screenshot from 2017-03-30 10-09-23](https://cloud.githubusercontent.com/assets/767939/24491867/e9cb050c-1531-11e7-8b89-9b26f6daca27.png)

Also there is an issue with the Save button:

![screenshot from 2017-03-30 10-11-31](https://cloud.githubusercontent.com/assets/767939/24491868/e9cdd2dc-1531-11e7-9e9c-b47ecacd7e35.png)

Which again works fine with double width or without define width at all.

**Comment by cecilebertin** [comment]
Hi,
I would like to work on this bug, if that's ok.

**Comment by Standard8** [comment]
I just noticed this in testing, suspect its a beta blocker, so adding flags.
