### ISSUE TITLE
about:license change for Raven.js

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2526]
Since we're including [raven.js](https://github.com/getsentry/raven-js/) we should include that in the licensing.  It uses a [BSD 2-clause "simplified" license](https://github.com/getsentry/raven-js/blob/master/LICENSE)

I think the library will end up in `browser/extensions/screenshots/webextension/build/raven.js`

Example bug: [1349288](https://bugzilla.mozilla.org/show_bug.cgi?id=1349288)

**Comment by Standard8** [comment]
Review request now up on [bug 1352387](https://bugzilla.mozilla.org/show_bug.cgi?id=1352387)

**Comment by Standard8** [comment]
The bug has landed on inbound and seems to be sticking, so I'll close this now.
