### ISSUE TITLE
Onboarding Flow if user first clicks from any non-web or unsupported page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2532]
Now it goes to My Shots, but that doesn't make much sense.

**Comment by johngruen** [comment]
@ianb changed the name of this issue to be more expansive

### Current
If a user clicks the Screenshots icon from any prohibited page (about:x, frameset etc). We either show an error notification or redirect them to "my Shots"

### Expected
The user should be onboarded

### Proposal
Maybe we should pop a new tab on the screenshots home page and onboard users on top of that page, that seems like the easiest thing to do.

**Comment by ianb** [comment]
2e5ce26005dbcd1094acc877f6c81c97aaf7c610 sends the user to `https://screenshots.firefox.com/#hello` and starts the screenshotting process (which also invokes onboarding) when the user tries to enable Screenshots on an unshootable page
