### ISSUE TITLE
Add menu item under Tools

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2539]
For accessibility, and perhaps other discoverability, things like Screenshots would often go under the "Tools" menu.  A keyboard shortcut could also be advertised there (per #2491).

There is no WebExtension API for this, so we would have to do it in bootstrap.js.  I'm unsure how we can have an event start in bootstrap.js and go to the WebExtension, except perhaps by simulating a click on the toolbar button.

**Comment by johngruen** [comment]
WONTFÏX
