### ISSUE TITLE
Use downloads.download() API

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2540]
The [downloads](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download) WebExtension API is a better way to trigger a download than what we are doing now (in ui.js:triggerDownload).

We might have to move the function into the background page, depending on what's allowable permission-wise.

**Comment by pdehaan** [comment]
<img width="699" alt="downloads_download___-_mozilla___mdn" src="https://cloud.githubusercontent.com/assets/557895/24563969/2bf8f94c-1605-11e7-9a8a-9ef88688263b.png">
