### ISSUE TITLE
Use storage.sync to share auth

### ISSUE THREAD

**Issue by dannycoates** [mozilla-services/screenshots#2541]
An alternative to explicitly logging in to use Screenshots on multiple devices might be to share the auth info via the `storage.sync` API.

**Comment by ianb** [comment]
I don't believe we get enough information from this API to support our use cases.  For instance, if you use Screenshots on device A and device B, and have not setup sync, and then you do set it up – what happens then?  One of device A or device B's authentication will win, and the other will be thrown away, losing access to shots.

Well.. it occurs to me that we could if we could have a no-conflict storage of some sort.  For instance, if we could store `[{deviceId, secret}, ...]` and on sync setup the lists get concatenated.  Or, more likely, if we can use a key pattern, like `browser.storage.set({"registration_{uuid}": registration})` and then read back all the keys and look for all `registration_*` values.  That could work?

But note this wouldn't work well across Firefox and Chrome.

**Comment by 6a68** [comment]
Adding email account IDs (FxA?) will make the multiple device story a lot simpler.

If the account info itself is synced, then we never have to worry about sync destroying data by destroying device IDs--worst case, a user will get logged out of account A by account B, but the data will still live on the server for both accounts.

**Comment by ianb** [comment]
We have a different approach in mind using FxA.
