### ISSUE TITLE
Check event.isTrusted in selector listeners

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2542]
Because the iframes we use are injected into the parent page, the parent iframe can access contents of the iframe. This means they could do things like trigger submit early or otherwise mess with things.

I *think* if we check [event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) that we can avoid this.  It might be worth trying to put together a malicious page to test on.

There's a possibility this will harm accessibility, but I don't know.

Thoughts @g-k @jvehent ?

**Comment by g-k** [comment]
How're we using iframes? Can screenshots be embedded on 3rd party pages?

**Comment by ianb** [comment]
This is on the client side – when you start Screenshots the interface you see is an iframe embedded into the page you are screenshotting

**Comment by pauljt** [comment]
I assume that should be a relatively simple change, and is probably worth doing. Of course a malicious webpage could do something like overlay content on top of _our_ overlay, and trick the user into clicking the wrong button, but that's a higher bar.

**Comment by g-k** [comment]
ianb, got it so our iframe is like a clickjacking overlay for good.

+1 for the isTrusted check

Can we set a src for the iframe to a separate origin (about:, data:text/html, addon content page, or something) so the parent page can't interfere with it via JS?

**Comment by ianb** [comment]
We can't change the source unfortunately, because our content script doesn't have special permissions and can't itself access the iframe if the parent page can't access it.  I find this frustrating, but that's how WebExtensions work :(

For implementation, this should be a wrapper similar to `catcher.watchFunction()` (which we also happen to use on all instances of `addEventListener`).  Something like:

```js
function assertIsTrusted(handlerFunc) {
  return function (event) {
    if (! event || ! event.isTrusted) {
      let exc = new Error(`Unexpected not-trusted ${event.type}`);
      exc.isTrustedType = typeof event.isTrusted;
      catcher.unhandled(exc);
    } else {
      return handlerFunc(event);
    }
  };
}

// Usage:
document.addEventListener("click", catcher.watchFunction(assertIsTrusted((event) => {
})), false);
```

**Comment by wresuolc** [comment]
@g-k @jvehent are you considering this a blocker for landing in 54?

**Comment by g-k** [comment]
@wresuolc I don't.

**Comment by ianb** [comment]
Example of trying to fire a synthetic event on the onboarding slides:

```js
document.querySelector("iframe#firefox-screenshots-onboarding-iframe").contentDocument.querySelector("#done").dispatchEvent(new Event("click"));
```

Before a6bf7ca9954bdd4bda7fa787f4ac38458902a5b0 this would close the onboarding, and after it gives an exception.  This exception is reported but not shown proactively to the user (as it shouldn't intrude on their experience).
