### ISSUE TITLE
Stage renders strangely

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2549]
I can run screenshots.stage.mozaws.net with the SDK version of the add-on okay, but the resulting shot is strange: [example](https://screenshots.stage.mozaws.net/Mmy3ZsH7duvbBHS7/example.com) – the image doesn't show up, the icons are quirky:

![image](https://cloud.githubusercontent.com/assets/44390/24580077/a9f25006-16c7-11e7-8a76-42d99e1ad14e.png)

The [image](https://screenshotsusercontent.stage.mozaws.net/images/5730388b-d619-458e-8c22-3d6b5bd352ec.png) can be loaded directly, but doesn't show up in the webpage.

To use the SDK add-on:

```sh
$ git clone -b pageshot.net-server git@github.com:mozilla-services/screenshots.git sdk-screenshots
$ cd sdk-screenshots
$ ./bin/run-addon -s https://screenshots.stage.mozaws.net
```

You could also install the Test Pilot version of the add-on and change the preferences to point to the screenshots.stage server and then restart the browser.

**Comment by wresuolc** [comment]
@relud is there anything weird in stage that would cause this off the top of your head?  Also #2552

**Comment by relud** [comment]
The image not showing is a CSP issue. Perhaps between 5.2.0 and 6.0.0 the CSP allowance for CONTENT_ORIGIN went away. I don't know why the buttons are acting funny

**Comment by pdehaan** [comment]
@ianb Are you seeing errors in the DevTools console as well?

![example_domain](https://cloud.githubusercontent.com/assets/557895/24623235/9b375386-185c-11e7-8b5c-49bca79a2cec.png)

![example_domain](https://cloud.githubusercontent.com/assets/557895/24623246/a38dbb74-185c-11e7-94e8-4ac4b96f821b.png)

**Comment by relud** [comment]
a dev in portland also points out that the CSP header for this page looks odd because it has `undefined` in the `img-src` section: `Content-Security-Policy: default-src 'self'; img-src 'self' www.google-analytics.com undefined data:; script-src 'self' www.google-analytics.com 'nonce-cdb0a196-6d49-4a56-a015-de3a0f583bd8'; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; connect-src 'self' www.google-analytics.com sentry.prod.mozaws.net; font-src https://code.cdn.mozilla.net;`

**Comment by pdehaan** [comment]
Looks like our `${CONTENT_NAME}` is coming back as `undefined`, per [/server/src/server.js:189](https://github.com/mozilla-services/screenshots/blob/e6928e16f487dd9a7d7addaff71ab5bd5c71c557/server/src/server.js#L189). Walking backwards, it looks like `CONTENT_NAME` is defined at [/server/src/server.js:163](https://github.com/mozilla-services/screenshots/blob/e6928e16f487dd9a7d7addaff71ab5bd5c71c557/server/src/server.js#L163); `const CONTENT_NAME = config.contentOrigin;`

I think our config is coming in via [/server/src/config.js](https://github.com/mozilla-services/screenshots/blob/e6928e16f487dd9a7d7addaff71ab5bd5c71c557/server/src/config.js), but I'm not seeing `contentOrigin` anywhere, unless it's getting injected via env vars.

**Comment by relud** [comment]
the config was removed in [28a6522](https://github.com/mozilla-services/screenshots/commit/28a6522a8bbcf6f5733656ea3408c84b620f655e#diff-480d08f875b12769794c80d3c6cccb9a)

**Comment by relud** [comment]
I found the source of the issue. the code that dynamically replaces /images/ links with the correct domain had a buffer with an off-by-one error causing characters to be dropped.

**Comment by relud** [comment]
this should be fixed in stage
