### ISSUE TITLE
The "Download" window is no longer displayed if you download a selection

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2550]
[Notes]:
- The "Download" window is not displayed even if the "Always ask you where to save files" option is set in "about:preferences".
- On a saved shot preview page, the "Download" window is displayed when you click the "Download" button from the top right corner of the page.

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170402004002)
- Page Shot 6.0.4770

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.4770) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Perform a selection and click the "Download" button.
4. Observe the browser behavior.

[Expected result]:
- The "Download" window is displayed.

[Actual result]:
- The "Download" window is no longer displayed and the selection is automatically downloaded. 

[Additional Notes]:
- Here is a screen shot with browser console errors:
![download selection](https://cloud.githubusercontent.com/assets/19226534/24603022/e50f43f0-1867-11e7-9e29-5215ca493a32.png)

- Here is a screen recording with the issue:
![download selection](https://cloud.githubusercontent.com/assets/19226534/24603030/ebe32b60-1867-11e7-9be3-6ea2b80d7bdb.gif)

**Comment by dannycoates** [comment]
I did this intentionally to see if @johngruen et al like it better. I know at least one person in user research was surprised by the save dialog. 

If not @niharikak101 already has a patch for it.

**Comment by wresuolc** [comment]
We talked about this in our triage today and want to move forward with the way it is.  We might do some testing in the future around this though.  Thanks.
