### ISSUE TITLE
Test Pilot spaceship and constellation are missing from screenshots.stage.mozaws.net page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2552]
[Notes]:
- @johngruen , @ianb  Since Firefox Screenshots will land in Firefox Beta as a system add-on, the Test Pilot references should not be removed? At least the "Install Screenshots with Firefox Test Pilot" button. After clicking it, you are redirected to Page Shot details page from Test Pilot. Or this is not the final page? 

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170402004002)
- Page Shot 6.0.4770

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://screenshots.stage.mozaws.net/.
2. Observe the Firefox Screenshots page.

[Expected result]:
- The page is correctly rendered.

[Actual result]:
- Test Pilot spaceship and constellation are missing from the page.

[Additional Notes]:
- On Chrome, the Test Pilot spaceship is wrongly rendered.
- On Safari, only the Test Pilot spaceship is missing.
- The https://screenshots.dev.mozaws.net/ page is correctly displayed, but the "Page Shot" name is not updated. 
- Here is a screen shot with the issue:
![stage page](https://cloud.githubusercontent.com/assets/19226534/24609261/d7244c70-1882-11e7-9729-05cccdc18f27.png)

**Comment by wresuolc** [comment]
We're creating a different landing page so going to close this.
