### ISSUE TITLE
[l10n] Add-on is not localized anymore

### ISSUE THREAD

**Issue by flodolo** [mozilla-services/screenshots#2565]
I currently have 5.2.14034 installed: the add-on description is correctly localized in about:addons, even the context menu is localized, but the add-on itself is English only (tooltip on the button, instruction to select area, save buttons).

**Comment by johngruen** [comment]
That's weird

**Comment by flodolo** [comment]
Looking at the .xpi in my profile, I correctly see strings in _locales

**Comment by SoftVision-CosminMuntean** [comment]
Works for me. I have created today a Firefox Screenshots custom build (v 6.0.7601) from GitHub repository and the addon is  correctly localized. I have tested this with a Nightly German build and a Nightly Italian build.
However, the  strigs from "My Shots" page and the save shot details page are not localized.  The strings from those pages will be localized?

**Comment by flodolo** [comment]
Can you try with
https://pageshot.dev.mozaws.net/homepage/install-test-local.html ?

**Comment by ianb** [comment]
I just tried the version from pageshot.dev with a Spanish build and everything appeared localized.  It's odd that a context menu would be localized and not other content.  For instance the confirmation popup is localized using the same technique in the same file.  (The instructions are localized using the same technique, but in another context, and I believe the tooltip is localized automatically by the WebExtension system.)

**Comment by SoftVision-CosminMuntean** [comment]
@flodolo  just tried with Firefox Screenshots installed from the provided link and the addon is correctly localized. I have also tested on a Firefox DE release version.

**Comment by flodolo** [comment]
I even tried to restart the browser in case there was some cache involved, let me try with a new profile. Note that I'm using Nightly: 55.0a1 (2017-04-05) (64 bit)

**Comment by flodolo** [comment]
OK, same version, new profile, the add-on is correctly localized. I wonder what's going on in my existing profile, and if there are ways to debug the issue.

**Comment by flodolo** [comment]
Tried uninstalling and reinstalling, add-on is fully localized now. One thing that I noticed is that I didn't get the introduction when I installed the updated version over the existing one, Page Shot was just working.
