### ISSUE TITLE
[l10n] Localizability issues with introduction steps

### ISSUE THREAD

**Issue by flodolo** [mozilla-services/screenshots#2567]
Not sure how done this is, but better filing for nothing than forgetting.

![schermata 2017-04-05 alle 18 36 31](https://cloud.githubusercontent.com/assets/3644868/24716319/f94df064-1a2e-11e7-9911-30948517d3d0.png)
Using `text-transform: uppercase` is a bad idea in general.

![schermata 2017-04-05 alle 18 36 56](https://cloud.githubusercontent.com/assets/3644868/24716377/2418dea8-1a2f-11e7-95cd-483523c0156d.png)
Again, text-transform, and unlocalized string. Also, fixed width is really risky, see how crowded Italian is, and it's not even the wordiest language.

![schermata 2017-04-05 alle 18 37 07](https://cloud.githubusercontent.com/assets/3644868/24716422/493fed34-1a2f-11e7-953a-b19fc86e2126.png)
Hard-coded skip and done, but more important, that "DONE" solution is going to work for maybe 5 or 6 locales, you need something that stretches to fit [way longer text](https://transvision.mozfr.org/string/?entity=browser/chrome/browser/browser.dtd:editBookmark.done.label&repo=aurora).

**Comment by wresuolc** [comment]
@johngruen assigning this to you in our triage.  If that's not right, let us know.

**Comment by johngruen** [comment]
@flodolo  thanks for this review... I think my PR fixes some of this stuff, and others we can work around. @pdehaan any brilliant way to grep for string length so we can figure out locales with the longest strings?

**Comment by pdehaan** [comment]
@johngruen We could maybe do some grep for string length (or character count), but not sure how reliable it'd be (since five "i"s will be much smaller than 4 "w"s, for example).
We could maybe just render each of those strings into a DOM element and then measure it's rendered width... meh.

**Comment by ianb** [comment]
In 2dc1dd4d748ce1d910ac951b99c148c045620204 I changed SKIP to be the text SKIP and removed the text-transform, so that localizers can apply their own judgement.  That commit also replaces DONE entirely, replacing it with a checkmark icon.

@johngruen changed "Firefox Screenshots BETA" to be a fixed string that does not get translated at all.

I think there's still the possibility of explanatory or header text overflowing the containers, as almost happens in your second screenshot.

**Comment by johngruen** [comment]
Hey @flodolo mind taking a look, we've made some changes that i think address most of your issues

**Comment by flodolo** [comment]
Is there an easy way to trigger this without creating a new profile?

Remaining issue: text-transform on "Skip".

I'm still seeing the text, not a checkmark

![schermata 2017-04-08 alle 06 38 48](https://cloud.githubusercontent.com/assets/3644868/24825767/1a568732-1c26-11e7-87aa-b6fd1cec8d0c.png)

Note that the layout is still risky. Italian fits, I'm not sure all languages will

![schermata 2017-04-08 alle 06 40 39](https://cloud.githubusercontent.com/assets/3644868/24825777/5856b4ee-1c26-11e7-92eb-c696c778ddfb.png)

**Comment by SoftVision-CosminMuntean** [comment]
> Is there an easy way to trigger this without creating a new profile?

@flodolo If you remove the add-on from "about:addons" page, then if you reinstall it, should work.

**Comment by flodolo** [comment]
> @flodolo If you remove the add-on from "about:addons" page, then if you reinstall it, should work.

Thanks, it works. I was expecting this to be stored behind a pref, but it isn't.

**Comment by 6a68** [comment]
> Remaining issue: text-transform on "Skip".

It looks like the string is actually uppercased in the [properties file](https://github.com/mozilla-services/screenshots/blob/master/locales/en-US/webextension.properties#L40). Maybe we should add a note for localizers?

> For completeness, I'm on 6.0.9943 and still seeing DONE instead of a checkmark.

Seems fixed on current master to me:

<img width="680" alt="screen shot 2017-04-12 at 3 07 10 pm" src="https://cloud.githubusercontent.com/assets/96396/24981489/d17640f6-1f91-11e7-9f32-4cd612ab6709.png">

**Comment by flodolo** [comment]
> It looks like the string is actually uppercased in the properties file. Maybe we should add a note for localizers?

Sorry, I was looking at "Done" and didn't think to check SKIP. If it's uppercase  in the file, that's OK, locales can decide to keep it or use lowercase.

> Seems fixed on current master to me:

Definitely not on https://pageshot.dev.mozaws.net/homepage/install-test-local.html (also don't have images), which brings to the next question: how often is that add-on updated?

**Comment by wresuolc** [comment]
@ianb is going to update the -dev add-on.  right now it's a manual process

**Comment by ianb** [comment]
We're planning on automating the dev deployment before we go live on server localization.  I believe all other issues have been fixed – no text-transform, and we use an icon for "done".
