### ISSUE TITLE
Need Onboarding Images

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2571]
Need 4 Images: images should be
1. named onboarding-#.png
2. be 1400px by 720px
3. Be matched to the content of each of the following strings
<img width="1280" alt="screen shot 2017-04-05 at 4 34 57 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725779/0e66752c-1a1e-11e7-85a2-9152f860fb19.png">
<img width="1280" alt="screen shot 2017-04-05 at 4 35 02 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725782/0e677300-1a1e-11e7-801b-9e5ae011942c.png">
<img width="1280" alt="screen shot 2017-04-05 at 4 35 04 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725781/0e66a290-1a1e-11e7-841c-3e4b5cdd5233.png">
<img width="1280" alt="screen shot 2017-04-05 at 4 35 08 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725780/0e667996-1a1e-11e7-963b-4de05790769a.png">

### NOTE: Screenshot UI looks as follows
<img width="1280" alt="screen shot 2017-04-05 at 4 35 22 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725816/2bff3380-1a1e-11e7-889d-988510e618cb.png">
<img width="1280" alt="screen shot 2017-04-05 at 4 35 27 pm" src="https://cloud.githubusercontent.com/assets/3323249/24725817/2c01c654-1a1e-11e7-8f63-f05c94432386.png">

**Comment by wresuolc** [comment]
@johngruen who owns this?

**Comment by fangshih** [comment]
Hey guys,
Here are the images assets for onboarding 
https://www.dropbox.com/sh/ggub5jbm1zx6uog/AACoeYzqd0_l8hKCMqWOPTDRa?dl=0
Thanks! 
![1 1 welcome](https://cloud.githubusercontent.com/assets/4862573/24789547/213fa19e-1ba6-11e7-96a5-897582e87e3c.png)
![1 2 select a region](https://cloud.githubusercontent.com/assets/4862573/24789548/2142c86a-1ba6-11e7-9188-3a071c24a01a.png)
![1 3 as you like it](https://cloud.githubusercontent.com/assets/4862573/24789549/214aedba-1ba6-11e7-9f13-c4fe1c6d33cd.png)
![1 4 full page](https://cloud.githubusercontent.com/assets/4862573/24789550/214d8c6e-1ba6-11e7-83d4-955cfe3c371a.png)

**Comment by johngruen** [comment]
@fangshih these look amazing

**Comment by johngruen** [comment]
Closed by #2612
