### ISSUE TITLE
Need Toolbar Icons

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2572]
Need final assets for the toolbar icon...these need to be:
1. 19px by 19px and 38px by 38px of the default icon (png)
2. The same at 60% opacity (png)
3. Version of the icon for users who haven't been onboarded. (png)

**Comment by wresuolc** [comment]
@bryanbell -- do you happen to have an icon for this? :)

**Comment by fangshih** [comment]
Hey @wresuolc here are the toolbar icons 
https://www.dropbox.com/sh/zh67xesqz0jdd5a/AAA_HyrlSMARVr9XkCfyHD_Ja?dl=0
Total 6 images with two sizes, Thanks!
