### ISSUE TITLE
Need a CHECK icon to replace "Done" string in onboarding tour

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2574]
We're having trouble with the length of different localizations of the word "DONE" fitting into the onboarding UI. We can fix this by replacing the word "DONE" with a checkbox. To close this bug we will need:

a 20px by 20px SVG check mark in the style of the back and forwards arrows.

**Comment by fangshih** [comment]
Here are the 20px by 20px SVG check icon
https://www.dropbox.com/s/mlntwam0aqe3wal/icon-check.svg?dl=0
Thanks!

**Comment by wresuolc** [comment]
thanks @fangshih
