### ISSUE TITLE
"Save full page" string wrongly exceeds the button area (Windows and Linux)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2580]
[Notes]:
- This issue is also reproducible for all buttons on localized builds on Windows and Linux.

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170405004003)
- Page Shot 6.0.9093

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.9093) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Observe the "Save full page" button from the top right corner of the page.

[Expected result]:
- The button is correctly displayed.

[Actual result]:
- The "Save full page" string exceeds the button area.

[Additional Notes]:
- On Mac OS the buttons are correctly displayed even on localized builds (screenshot: https://goo.gl/31n3Yj).
- Here is a screen shot on Windows with a German build.
![german build](https://cloud.githubusercontent.com/assets/19226534/24746628/7f4a8680-1ac2-11e7-8102-26787830d882.png)

- Here is a screen shot with the issue on a English/United States build:
![save full page](https://cloud.githubusercontent.com/assets/19226534/24746633/83c19a00-1ac2-11e7-98c2-34b3f7db7797.png)

**Comment by wresuolc** [comment]
-> @johngruen .  We think this changed with the latest UI improvements

**Comment by johngruen** [comment]
Closed by #2612
