### ISSUE TITLE
Screenshots fails to run on Windows on the try servers (or more generally packaged builds?)

### ISSUE THREAD

**Issue by Standard8** [mozilla-services/screenshots#2581]
Screenshots fails to run on Windows on the try servers (or more generally packaged builds?), post Issue #2563.

Windows doesn't like the new resourceURI that we're passing in. I'm not sure if we had data on if it liked it before or not, but I suspect not.

<details>
04:37:07     INFO - GECKO(4044) | 1491478627191	addons.xpi-utils	WARN	addMetadata: Add-on screenshots@mozilla.org is invalid: [Exception... "Failed to open input source 'jar:file:///C:/slave/test/build/application/firefox/browser/features/screenshots@mozilla.org.xpi!/webextension/manifest.json'"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/Extension.jsm :: readJSON/< :: line 355"  data: yes] Stack trace: readJSON/<()@resource://gre/modules/Extension.jsm:355 < readJSON()@resource://gre/modules/Extension.jsm:352 < parseManifest()@resource://gre/modules/Extension.jsm:414 < loadManifest()@resource://gre/modules/Extension.jsm:464 < loadManifestFromWebManifest<()@resource://gre/modules/addons/XPIProvider.jsm:965 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < TaskImpl()@resource://gre/modules/Task.jsm:277 < asyncFunction()@resource://gre/modules/Task.jsm:252 < loadManifestFromRDF<()@resource://gre/modules/addons/XPIProvider.jsm:1240 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < TaskImpl()@resource://gre/modules/Task.jsm:277 < asyncFunction()@resource://gre/modules/Task.jsm:252 < loadFromRDF()@resource://gre/modules/addons/XPIProvider.jsm:1517 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < TaskImpl()@resource://gre/modules/Task.jsm:277 < asyncFunction()@resource://gre/modules/Task.jsm:252 < Task_spawn()@resource://gre/modules/Task.jsm:166 < TaskImpl_handleResultValue()@resource://gre/modules/Task.jsm:389 < TaskImpl_run()@resource://gre/modules/Task.jsm:327 < TaskImpl()@resource://gre/modules/Task.jsm:277 < asyncFunction()@resource://gre/modules/Task.jsm:252 < loadManifestFromZipFile<()@resource://gre/modules/addons/XPIProvider.jsm:1604 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < TaskImpl()@resource://gre/modules/Task.jsm:277 < asyncFunction()@resource://gre/modules/Task.jsm:252 < loadManifestFromFile()@resource://gre/modules/addons/XPIProvider.jsm:1613 < syncLoadManifestFromFile()@resource://gre/modules/addons/XPIProvider.jsm:1625 < addMetadata()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1596 < processFileChanges()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1984 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3800 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2833 < callProvider()@resource://gre/modules/AddonManager.jsm:268 < _startProvider()@resource://gre/modules/AddonManager.jsm:755 < startup()@resource://gre/modules/AddonManager.jsm:922 < startup()@resource://gre/modules/AddonManager.jsm:3099 < observe()@jar:file:///C:/slave/test/build/application/firefox/omni.ja!/components/addonManager.js:65
</details>

**Comment by Standard8** [comment]
Try server details here: https://treeherder.mozilla.org/#/jobs?repo=try&revision=6e9cbaa1d9249d069e085031174d8154b02294a2&selectedJob=89158734

**Comment by Standard8** [comment]
/cc @Mossop, @rhelmer - If either of you two have ideas, we'd appreciate hearing them.

History:

* @Mossop gave this review comment: https://github.com/mozilla-services/screenshots/pull/2471/files/d26f842233b87c46258267feee0fb72ef3669c86#r107795580
* So @6a68 updated bootstrap as per https://github.com/mozilla-services/screenshots/pull/2480/files#diff-4b80223300be1233ce41b6b9d0c08761
* This added a `addonResourceURI.QueryInterface(Ci.nsIFileURL)` as he thought the QI was necessary.
* This failed on try servers due to `NO_INTERFACE` (I'm not sure we actually checked Windows builds for those though). It was working locally, so I suspect this is a packaging vs non-packaged issue.
* I then dropped the QI in #2563 which gets Linux & Mac passing try server, but not Windows (see the details above - note the section expands!).

**Comment by Mossop** [comment]
The QueryInterface is definitely unnecessary. I don't really understand the failures I'm seeing on windows though, are they caused by the presence of the extra button in the UI?

**Comment by Standard8** [comment]
> I don't really understand the failures I'm seeing on windows though, are they caused by the presence of the extra button in the UI?

Some of them seem to be the extra items, e.g. context menu items. However, from the screenshots associated with the failures, it is clear the button isn't being displayed on the toolbar, and the log shows that when the browser started there are `NS_ERROR_FILE_NOT_FOUND` warnings: `"Failed to open input source 'jar:file:///C:/slave/test/build/application/firefox/browser/features/screenshots@mozilla.org.xpi!/webextension/manifest.json'"`

Interestingly though, the stack in my first comment doesn't show bootstrap.js - it seems to be on loading the legacy extension itself.

**Comment by Standard8** [comment]
Ok, I found the issue - for some reason the webextension sub-directory isn't being packaged on Windows. I suspect something in the build process isn't quite right. I'll take a look.

**Comment by Standard8** [comment]
I'm hopeful that this run will have the windows builds fixed:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=7f9e7436fb8b24bb6993ef97fc0c70190131d594

I did some work on it today which hopefully has everything listed now.

**Comment by Standard8** [comment]
I believe we've resolved this now, with a change of the export mechanism that we're using (#2606)
