### ISSUE TITLE
Redirect screenshot.firefox.com to screenshots.firefox.com

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2587]
Seems like `screenshot.firefox.com` is a reasonable misspelling that we could correct.

**Comment by wresuolc** [comment]
@relud can you do this?

**Comment by relud** [comment]
over http, yeah, I can set that up. over https: I already got an ssl cert, so i'd have to get another one v_v but I can still do it

**Comment by relud** [comment]
fixed
