### ISSUE TITLE
webext review changes: shared/shot.js

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2593]
refs #2591 

shared/shot.js: deepEqual function changes, ~~makeUuid changes~~, asJson vs toJson (all kinda scary and not clear we have to change them before uplift)

**Comment by 6a68** [comment]
feel free to just push fixes for this to the `webextension-review-changes` branch

**Comment by ianb** [comment]
@6a68: I don't know what deepEqual refers to here?  I don't see a reference to that in #2471

**Comment by chenba** [comment]
@6a68 do you remember what about deepEqual that needed fixing?
