### ISSUE TITLE
webext review changes: sitehelper.js

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2595]
refs #2591 

sitehelper.js: replace JSON.stringify with cloneInto (line 16, kinda seems optional IMO)

**Comment by 6a68** [comment]
feel free to just push fixes for this to the `webextension-review-changes` branch

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
