### ISSUE TITLE
If the Screenshots button is clicked when you are on Test Pilot page, you are wrongly redirected to the "https://pageshot.stage.mozaws.net/#hello" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2598]
[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Page Shot 6.0.10626

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.10626) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate testpilot.firefox.com.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Observe the browser behavior.

[Expected result]:
- The Screenshots overlay covers the page and you are able to save a selection.
or
- The Screenshots button is not active on Test Pilot pages.

[Actual result]:
- You are redirected to "https://pageshot.stage.mozaws.net/#hello" and the Screenshots overlay automatically covers the page.

[Notes]:
- I have noticed the same behaviour  after enabling the Screenshots add-on you are able to click the Screenshots button on "about:addons" page or on any "about:*" pages if were previously opened. If the Screenshots button is clicked you are redirected to "https://pageshot.stage.mozaws.net/#hello" page.
- Here is a screen recording with the issue:
![test pilot vs screenshots](https://cloud.githubusercontent.com/assets/19226534/24807460/ed9e5d56-1bc0-11e7-889b-1e3c27205862.gif)

**Comment by ianb** [comment]
This is specific to testpilot.firefox.com – we can't take shots of addons.mozilla.org and testpilot.firefox.com because there's a blacklist due to these sites being able to install add-ons.  When in a potential onboarding state and we can't take a shot of the page for some reason, then we open a new tab.
