### ISSUE TITLE
The "Cancel" and "Download" buttons are displayed inside of the selection, if it has reduced width

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2599]
[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Page Shot 6.0.10626

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.10626) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Perform a selection with reduced width.
4. Observe the selection buttons.

[Expected result]:
- The "Cancel", "Download" and "Save" buttons are displayed out side of the selection

[Actual result]:
- The "Cancel", "Download" are displayed inside of the selection.

[Notes]:
- Here is a screen recording with the issue:
![reduced width](https://cloud.githubusercontent.com/assets/19226534/24807495/1458d89a-1bc1-11e7-9c30-ddcfc66196aa.gif)

**Comment by johngruen** [comment]
Closed by #2612

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible, but if a selection with reduced width is performed near the left part of the window, the "Cancel", "Download" and "Save" buttons are not entirely visible. 

@johngruen, I think a similar behavior was described in issue #2259, but was related to the bottom edge of the window. Is there a chance that the fix for the bottom edge of the window can be also applied for the left edge of the window? 

Here is a screen recording:
![left part of the window 2](https://cloud.githubusercontent.com/assets/19226534/25183097/43791bfa-251f-11e7-83e1-aef3ed4e258d.gif)
