### ISSUE TITLE
The "Download" button from saved shot details page is not correctly working (stage)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2600]
[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Page Shot 6.0.10626

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.10626) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Perform a selection and save it.
4. Click the "Download" button from top right corner of the page.
5. Observe the browser behavior.

[Expected result]:
- The "Download" window is opened in order to download the shot.

[Actual result]:
- The saved shot image is opened in the same tab.

[Notes]:
- Here is a screen recording with the issue:
![download shot](https://cloud.githubusercontent.com/assets/19226534/24807555/53405e02-1bc1-11e7-9614-f21846219a22.gif)

**Comment by dannycoates** [comment]
I'm not able to reproduce this. Had this profile previously chosen to automatically open pngs with firefox?

**Comment by ianb** [comment]
I wonder if there's some way that `shot.filename` can return null, and so maybe remove the `download` attribute entirely?

**Comment by dannycoates** [comment]
> I'm not able to reproduce this

oh wait. I was pointing to pageshot.stage before, on screenshots.stage I am able to repro.

**Comment by dannycoates** [comment]
The `download` attribute is restricted to same-origin and the image is now on a separate subdomain. https://developer.mozilla.org/en/docs/Web/HTML/Element/a We *might* be able to do something with CORS but I'm not sure.

**Comment by ianb** [comment]
I guess we could do something nutty like fetch the image and translate it to a data URL and substitute that in there?

Probably the better answer is to use Content-Disposition.  Maybe like:

`{contentOrigin}/images/{imageId}?download&filename={shot.filename}&sig={signature}`

I don't think we want `/images/{imageId}?download` generating its own filename, as it would expose information that is not currently available from the image link alone.
