### ISSUE TITLE
Add left/right keyboard shortcuts to onboarding slides

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2615]
To go to next/previous.  Maybe Enter to finish when you've gotten through them all?  Or we could focus the done button at the end of the slides.

**Comment by ianb** [comment]
Notes `slides.js` has the handler code, and there's an `onKeyUp` handler in that file already.

**Comment by cecilebertin** [comment]
Hi, can I work on this?

**Comment by ianb** [comment]
Please do!  I set you as a member so you should be able to assign yourself to issues now too.

**Comment by cecilebertin** [comment]
Thank you!

**Comment by cecilebertin** [comment]
@ianb, I can't seem to assign myself yet, but I will start working this issue.

**Comment by cecilebertin** [comment]
I can't seem to be able to assign this bug to myself yet, but I will start working on it.

**Comment by ianb** [comment]
Fixed by #2784
