### ISSUE TITLE
If you click the "Privacy Notice" link from Onboarding tour, you are redirected to a 404 page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2616]
[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Screenshots 6.0.4781

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.4781) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Click the "Privacy Notice" link from Onboarding tour.
4. Observe the browser behavior.

[Expected result]:
- You are redirected to the privacy page.

[Actual result]:
- You are redirected to a 404 page.

[Notes]:
- Here is a screen recording with the issue:
![privacy notice](https://cloud.githubusercontent.com/assets/19226534/24854381/ecea86dc-1de6-11e7-911a-f95bbaa4c76d.gif)

**Comment by wresuolc** [comment]
This will be fixed with #2618
