### ISSUE TITLE
An extra "expires in 1 minutes" string is wrongly displayed if a shot is about to expire in 1 minute

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2617]
[Notes]:
- The extra string also contains a typo (should be 1 minute instead of 1 minutes).

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Screenshots 6.0.4781

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.4781) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Perform a selection on the page and save it.
4. Change the expire time to 10 minutes.
5. Wait 7 minutes or change the System Time to be 7 minutes in the future and refresh the page.
6. After 1 minute refresh the page and observe the expire time. 
7. After 1 minute refresh the page and observe the expire time.

[Expected result]:
Step 5. The "expires in 2 minutes" message is correctly displayed.
Step 6. The "expires in 1 minute" message is correctly displayed.
Step 7. The "expires very soon" message is correctly displayed.

[Actual result]:
Step 5. The "expires in 2 minutes" message is correctly displayed
Step 6. The "expires in 1 minutes" string is wrongly displayed.
Step 7. The "expires in 1 minute" message is displayed, then after 41 sec if the page is refresh the "expires very soon" message is displayed.

[Notes]:
- Here are the messages that are displayed for the last 3 minutes:
02:00 - 02:59 - "expires in 2 minutes" message is displayed.
01:00 - 01:59 - "expires in 1 minutes" message is displayed.
00:20 - 00:59 - "expires in 1 minute" message is displayed.
00:00 - 00:19 - "expires very soon" message is displayed.

- Here is a screen recording with the issue:
![minutes](https://cloud.githubusercontent.com/assets/19226534/24859774/bce73782-1dfa-11e7-829b-13b25c920566.png)

**Comment by wresuolc** [comment]
This will be changed when we add localization.  Probably to something less exact and friendlier.

**Comment by wresuolc** [comment]
Is this still a bug?  @SoftVision-CosminMuntean

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and the expires messages are changed. Here are the messages that are displayed for the last 3 minutes:

**Comment by wresuolc** [comment]
thanks for checking!
