### ISSUE TITLE
Add Pref to Disable Screenshots

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2624]
At the bottom of about:preferences#content

<img width="1084" alt="370aa912-19f1-11e7-841f-8a185ca2d10c" src="https://cloud.githubusercontent.com/assets/3323249/24874800/84ff9224-1deb-11e7-83e1-2456fdba4a75.png">

**Comment by johngruen** [comment]
Does not block 54, but nice to have.

**Comment by ckprice** [comment]
Brian just stopped by and it looks like other folks are looking to make adjustments to the preferences in the next couple of releases. He mentioned keeping legal, and maybe other UX folks (verdi) looped in.

**Comment by ckprice** [comment]
Closing as a dup of #2711
