### ISSUE TITLE
You cannot trigger the Onbording tour on "about:*" pages if the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2635]
[Notes]:
- The issue is not reproducible if you navigate to "about:*" pages using the URL address.

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170407004017)
- Screenshots 6.0.2123

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites install the latest Firefox Screenshots (6.0.2123) build.
2. Restart the browser.
3. Go to to any of "about:*" pages (eg: "about:preferences").
4. Click the Firefox Screenshots button from browser toolbar.
5. Observe the browser behavior.

[Expected result]:
- A new tab is opened and the Screenshots Onboarding tour is displayed.

[Actual result]:
- The Screenshots button is inactive.

[Additional Notes]:
- This issue is also reproducible if you have opened any of "about:*" pages and you navigate to another tab. When you return to the "about:*" page, the Onboarding tour cannot be triggered, the button is inactive.

**Comment by dannycoates** [comment]
This doesn't affect `about:newtab` or `about:blank`. I suggest this not be a blocker.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible on the latest Firefox Screenshots (v. 6.2.1984), dev and stage custom builds.
