### ISSUE TITLE
Enabling First party isolation breaks My Shots functionality

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/screenshots#2639]
On dev edition I have `privacy.firstparty.isolate` set to true. This breaks the "My Shots" functionality. When I set `privacy.firstparty.isolate` to false the "My Shots" functionality works.

**Comment by ianb** [comment]
We should re-test this given the new more resilient authentication we have in place.

**Comment by SoftVision-CosminMuntean** [comment]
I have tested this issue with the "privacy.firstparty.isolate" pref set to "true" on latest Firefox 57.0.4 release and latest Nightly 59.0a1 build. Here are the results:
1. Firefox 57.0.4
- The "If you took this shot and cannot delete it, you may need to temporarily enable third party cookies from your browser’s preferences." warning is displayed and you cannot change the expiry date, edit the title or delete the shot. Also, if you navigate to the "My Shots" page you are redirected to the Screenshots tour page.
2. Nightly 59.0a1
- The warning is displayed only for the first saved shot. Even if the warning is displayed, you can change the expiry date, edit the title or delete the shot. If you refresh the page the warning disappears.
Please let me know if I should log a bug for this.
Also, if you navigate to "My Shots" page, the page is correctly loaded.

**Comment by chenba** [comment]
I just tested this with Nightly and Developer Edition.  My Shots work with the pref in either state.
