### ISSUE TITLE
Document version numbers

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2647]
We have a version number in package.json.  We should document how it is managed.  Proposal:

- Every time we release we increment the number (in development) to a new number.  E.g., release 6.x (to the Firefox tree) and we increment to 7.0.0
- Every time we do a stage release, we increment the second number in advance of that release.  I.e., 7.1.0, and if 7.1.0 fails then 7.2.0, etc.
- Every time we release to Firefox we increment the third number *one more time*, so that version is bigger than any in-development version.  I.e., if 7.2.0 is all good, we increment to 7.3.0 for export, and then immediately change our in-development version  to 8.0.0.
- In-development builds use the third number as a date timestamp, i.e., 7.1.20170411

**Comment by 6a68** [comment]
Got burned by this, incrementing patch version numbers between 6.6.0 and 6.6.2 as part of performance tweaking for the 54 release :-(

Promoting into the 54 milestone to prevent similar mistakes in the future

**Comment by 6a68** [comment]
oh wait, maybe we can just do this third thing:

> Every time we release to Firefox we increment the third number one more time, so that version is bigger than any in-development version. I.e., if 7.2.0 is all good, we increment to 7.3.0 for export, and then immediately change our in-development version to 8.0.0.
