### ISSUE TITLE
Website favicons are not displayed on saved shots from "My Shots" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2648]
[Notes]:
- I am not sure if this is the intended behavior, but on Page Shot Test Pilot version each saved shot title had a website favicon.

[Affected versions]:
- Firefox 55.0a1 (Build ID:20170411153633)
- Screenshots 6.0.2123

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.2123) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile and navigate to any website (eg: imdb.com)
2. Click the Firefox Screenshots button from browser toolbar and save a selection on the page.
3. Click "My Shots" button from the top left corner of the page.
4. Observe the saved shot tile.

[Expected result]:
- The saved shot has a specific website favicon displayed on the bottom left corner of the tile. 

[Actual result]:
- Website favicon is not displayed on the saved shot tile.

[Additional Notes]:
- Here is a screenshot with the issue:
![favicons](https://cloud.githubusercontent.com/assets/19226534/24959352/37750348-1f9b-11e7-84e6-d5fe536388e2.png)

**Comment by SoftVision-CosminMuntean** [comment]
@dannycoates I have retested this issue on Screenshots stage server. It seems that the website favicons are not displayed and the favicon links redirects you to a 404 page.

But, I have noticed that on Page Shot stage server the the favicons are correctly displayed. Is there an issue on Screenshots stage server?

Here is a screenshot with the isssue:
![fav icons](https://cloud.githubusercontent.com/assets/19226534/25284632/4a1f5d96-26c0-11e7-9b84-23d8b5907c7d.png)

**Comment by dannycoates** [comment]
@SoftVision-CosminMuntean this fix is in the addon. It's on master but not in m-c yet

**Comment by SoftVision-CosminMuntean** [comment]
@dannycoates I have received from Jared a Nightly try build with the latest Screenshots release and it seems that the issue is still reproducible. The website favicons are not displayed and the favicon links redirects you to a 404 page.

The fix wasn't deployed to production?

**Comment by dannycoates** [comment]
@SoftVision-CosminMuntean can you give me a link to a shot missing the favicon that you took with that build?

**Comment by dannycoates** [comment]
@SoftVision-CosminMuntean I figured it out. Stage and prod use a separate content domain that doesn't serve `/proxy` which favicons use. We'll get this fixed :)

**Comment by ianb** [comment]
Note that `/proxy` also doesn't handle redirects which could cause a problem (e.g., I believe wnba.com has this problem)

**Comment by johngruen** [comment]
Also not displaying on shot details page

**Comment by ianb** [comment]
As an example, [this link](https://screenshots.firefoxusercontent.com/proxy?url=https%3A%2F%2Fsanfranciscoallhandsjune2017.sched.com%2Ffavicon.png&sig=M-KS9gKVIBWH84XJiXLhFoJ7b1E) is 404, but [this link](https://screenshots.firefox.com/proxy?url=https%3A%2F%2Fsanfranciscoallhandsjune2017.sched.com%2Ffavicon.png&sig=M-KS9gKVIBWH84XJiXLhFoJ7b1E) works.  The first link is the one actually in My Shots.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is still reproducible on dev and also on production servers. 
Or the issue will not reproduce after the fix will be deployed on production?

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is still reproducible on all servers.

**Comment by johngruen** [comment]
Removed favicons
