### ISSUE TITLE
[Enhancement] Test Pilot references should be removed from "Leave Screenshots complete" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2649]
[Notes]:
- As far I know Firefox Screenshots cannot be uninstalled from Test Pilot. Also, if users doesn't have Test Pilot installed, they may be confused.

[Affected versions]:
- Firefox 55.0a1 (Build ID:20170411153633)
- Screenshots 6.0.2123

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.0.2123) custom build is installed on a new clean profile.
- Have multiple saved shots.

[Steps to reproduce]:
1. Open the browser with the profile.
2. Click the Firefox Screenshots button from browser toolbar.
3. Click the "Remove All Data" link from the footer of the page.
4. Click the "Proceed" button and observe the "Leave Screenshots complete" page.

[Expected result]:
- There are no references to Test Pilot.

[Actual result]:
- "You can uninstall the Firefox Screenshots add-on via Test Pilot" text and "Go to Test Pilot" button are displayed.

[Notes]:
- Here is a screenshot with the issue:
![test p](https://cloud.githubusercontent.com/assets/19226534/24959502/aac45312-1f9b-11e7-856c-140a5f8694aa.png)

**Comment by ckprice** [comment]
Talked a bit about this in our legal meeting today. In addition to removing references of Test Pilot, do we want to also allow the user to uninstall directly from this page/is it possible?

**Comment by dannycoates** [comment]
The Test Pilot reference has been removed. We don't have/need any notion of "uninstalling" Screenshots.
