### ISSUE TITLE
After the browser is restarted the Screenshots button is active on "about:home" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2650]
[Affected versions]:
- Firefox 55.0a1 (Build ID:20170411153633)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Nightly build with Screenshots installed and a clean profile.
- The "extensions.screenshots.system-disabled" pref is set to false.
- Make sure that the "When Nightly starts:" option has "Show your home page" set in "about:preferences".
- Onboarding tour was already visited.

[Steps to reproduce]:
1. Open the browser and profile from prerequisites.
2. Click the Screenshots button from browser toolbar.
3. Observe the browser behavior.

[Expected result]:
- Firefox Screenshots button is inactive and cannot be clicked.

[Actual result]:
- You are redirected to "https://screenshots.firefox.com/#hello" page and the Screenshots overlay covers the page.

[Notes]:
- Here is a screen recording with the issue:
![restart home page](https://cloud.githubusercontent.com/assets/19226534/24960461/8d575e7a-1f9e-11e7-9bf1-181d49c5287f.gif)

**Comment by ianb** [comment]
af225a706eb1d3466380f70800b7faa9eaaf24a3 isn't a perfect fix.  Basically when Screenshots is started it doesn't check the URL of any existing tabs to set the activation state.  There was logic that turned any activation on an unshootable page into the onboarding flow, with the expectation that you'd only be allowed to do that when onboarding was expected.

The commit changes that so if you've gone through onboarding, then in this case you'll get an error popup about how you can't shoot the page.

**Comment by SoftVision-EmilPasca** [comment]
@ianb I have tested this issue using the latest Firefox Screenshots (v. 6.2.1984), dev and stage custom builds.
After the onboarding tour was visited, the "Screenshots" button from the browser toolbar on "about:home" page becomes inactive and cannot be clicked, which solves the issue.
However, the "Screenshots" button is not grayed out on Windows as it is on Mac OS, is this a windows issue?
Also the error popup you mentioned was not shown on either platforms.
> The commit changes that so if you've gone through onboarding, then in this case you'll get an error popup about how you can't shoot the page.

![screenshots_issue](https://cloud.githubusercontent.com/assets/20083658/25011127/fd707a76-2074-11e7-8e06-4caaae264bbf.gif)
