### ISSUE TITLE
An infinite spinner is displayed when opening a non-owner shot taken from the latest Nightly Try build if uBlock Origin is installed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#2651]
[Notes]:
- The issue is not reproducible if the first ever shot is shared ([Browser Console errors](https://drive.google.com/open?id=0B8ICzPJynbchOGdfc2lyZTNqZDQ)). However it it reproducible with all subsequent shots.
- The issue is also reproducible on Chrome with uBlock Origin installed.
- If I disable uBlock Origin and refresh the page, the image is loaded correctly.
- The issue is not reproducible if the page is shared from a custom build using the Page Shot dev server.
- The issue is not reproducible on Chrome or Firefox with AdBlock Plus installed.

[Affected versions]:
- Firefox 52 and up.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have uBlock Origin installed on a clean profile.

[Steps to reproduce]:
1. Open the browser and profile from prerequisites.
2. Open a non-owner shot taken with the Nightly try build. (eg. https://screenshots.firefox.com/8JSV1y1KERYowIT3/www.imdb.com)
3. Observe the browser behavior.

[Expected result]:
- The page is loaded and the image is displayed.

[Actual result]:
- The page is loaded, but the spinner loops infinitely and the image is not displayed.

[Additional notes]:
- Here is a screen shot of the issue:
![image](https://cloud.githubusercontent.com/assets/18304511/24966069/90005bee-1fae-11e7-9255-8ed32dac44ba.png)
- Here are the errors shown in the browser console:
![image](https://cloud.githubusercontent.com/assets/18304511/24966143/d7ae72a0-1fae-11e7-9d86-91656e4ab18d.png)

**Comment by ianb** [comment]
This was probably fixed in #2798, but #2792 double-fixes it – the first makes it so uBlock doesn't keep JavaScript from loading, and the second makes it so if the JavaScript bundle fails the image will still be displayed.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible with shots taken with Screenshots from the latest Nightly build.
