### ISSUE TITLE
Update the legal onboarding string

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2668]
Since we no longer have Screenshots specific legal docs, we, unfortunately, need to change the string at the bottom of the onboarding.  It currently reads:  

`By using Firefox Screenshots, you agree to the Screenshots Terms and Privacy Notice`

It should read:

`By using Firefox Screenshots, you agree to the Firefox Cloud Services Terms and Privacy Notice`

/cc @flodolo since this is l10n

**Comment by flodolo** [comment]
Note that you'll need to update the string ID to make sure all locales update their translation.

**Comment by flodolo** [comment]
BTW; are we aware of any other string changes for the add-on? We set a deadline for April 11, but we also landed these strings a few days ago, I guess it makes sense to extend the deadline to avoid confusion.

**Comment by wresuolc** [comment]
I think there was one other string that Legal wanted to change, but it was on the server and not in the add-on.  @ckprice do you remember what it was?  or was it just removing one?

**Comment by ckprice** [comment]
It was the string on the "Leave Screenshots" page, so server. That issue is already filed (2649).
