### ISSUE TITLE
Move onboarding images to the server

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2677]
The onboarding slide images are kind of big.  It would be nice if they were hosted outside of the add-on for space consideration.

**Comment by wresuolc** [comment]
These are 170k

**Comment by 6a68** [comment]
@Standard8 FYI, just in case there are complaints about the screenshots addon size as we're moving into m-c, this is a tracking issue to move 170kb worth of images out to the server.

**Comment by johngruen** [comment]
meh? Seems good to keep these client side. Feels good that we don't have to fetch them. Also we're never going to do this.
