### ISSUE TITLE
Onboarding image uses older icon?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2701]
Testing in today's nightly, and randomly spotted the icons are ever-so-slightly-different:

<img width="823" alt="onboarding-4_png__png_image__1400 x 720_pixels__-_scaled__58__" src="https://cloud.githubusercontent.com/assets/557895/25144535/fe2bcdd8-2422-11e7-840e-01fbec17442b.png">

**Comment by fangshih** [comment]
Just updated the icon and toolbar to the latest, Thanks! 
https://www.dropbox.com/sh/ggub5jbm1zx6uog/AACoeYzqd0_l8hKCMqWOPTDRa?dl=0
![img-onboarding-4 2x](https://cloud.githubusercontent.com/assets/4862573/25161756/975d842e-24f0-11e7-8ebd-fdafa6f1e88c.png)
