### ISSUE TITLE
Flashes of older content in the onboarding flow

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/screenshots#2703]
@johngruen reported this, to confirm.

**Comment by wresuolc** [comment]
@johngruen is going to look at this

**Comment by johngruen** [comment]
@ianb turns out the flash happens on the server side...[see video](https://www.dropbox.com/s/d0s1z9a8gxp9i19/unstyled-flash.mov?dl=0). Not a gamma blocker.

﻿
