### ISSUE TITLE
Enable ESLint rule `consistent-return`

### ISSUE THREAD

**Issue by Standard8** [mozilla-services/screenshots#2705]
In #2700 I disabled the `consistent-return` ESLint rule, as there were quite a few failures, and I didn't have enough experience with the code.

This rule should be looked at at some stage.

**Comment by ianb** [comment]
I did some cases in 757fd5d2656a5597cc9f374046f402281b8756a2 but I'm not a big fan of the rule.  Or at least it doesn't work well with promises, as a return in `.then()` often means "keep doing something" not "here is a return value".

There's a couple other cases I didn't fix that involve messaging where `return true` means do an async completion.  These will be fixed when we convert that code to use promises.

**Comment by chenba** [comment]
This was fixed in #3977.
