### ISSUE TITLE
A Screenshots error is displayed, if you drag a tab back in the first browser window

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2707]
[Affected versions]:
- Nightly 55.0a1 (Build ID:20170418030220)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref is set to false.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open two tabs.
2. From one tab navigate to any website.
3. Drag the tab outside the first window to open it in a new window.
4. Drag back the tab in the first window.
5. Observe the browser behavior.

[Expected result]:
- The tab is correctly moved and no error is displayed.

[Actual result]:
- A "Whoa! Firefox Screenshots went haywire" error is displayed.

[Notes]:
- The error is displayed even if Screenshots wasn't used.
- This issue is reproducible when the last tab from the second window is dragged in the first window. 
- Here is a screen shot with browser console error:
![drag](https://cloud.githubusercontent.com/assets/19226534/25179730/cb2846ae-2513-11e7-840a-a29ea9e42265.png)

- Here is a screen recording with the issue:
![drag](https://cloud.githubusercontent.com/assets/19226534/25179740/d337a6b4-2513-11e7-8057-3c15ca700ced.gif)

**Comment by dannycoates** [comment]
The notification is already fixed by #2702 

The `tab.get(tabId)` still fails, but I'm not sure there's anything to do to react to it. We can add a catch function to ignore it though.
