### ISSUE TITLE
The Screenshots button is not grayed out when it is inactive (Windows and Linux)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2708]
[Notes]:
- On Mac Os, the Screenshots button is grayed out when the button is inactive.

[Affected versions]:
- Nightly 55.0a1 (Build ID:20170418030220)

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref is set to false.
- The Onbarding tour was already visited.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to any of "about:*" page.
3. Observe the Screenshots button from browser toolbar.

[Expected result]:
- The Screenshots button is inactive and it is grayed out.

[Actual result]:
- The Screenshots button is inactive but the button is not grayed out.

[Additional Notes]:
- Here is a screen shot with the issue:
![inactive](https://cloud.githubusercontent.com/assets/19226534/25179840/3d870172-2514-11e7-94af-d4ede6496019.png)

**Comment by 6a68** [comment]
Hmm. The button is actually [supposed](https://github.com/mozilla-services/screenshots/blob/666aad30143dbc5349105e3ce694e552c4d86954/addon/webextension/background/main.js#L76) to be enabled on about:blank and about:newtab, as well as the activity stream newtab page. If I manually load those URLs, the button is enabled, and clicking the button goes to screenshots.firefox.com, as intended.

However, the button seems to be disabled on the nightly new tab page--maybe it has some other about: URL?

The button seems to be correctly disabled on other about: pages, like about:config, about:performance, about:addons.

I'll investigate the nightly new tab page URL, but I'd say this is definitely not a blocker.

**Comment by SoftVision-CosminMuntean** [comment]
> The button seems to be correctly disabled on other about: pages, like about:config, about:performance, about:addons.

Yes, the button is correctly disabled, but on Windows and Linux the button is not grayed out. On those pages on Mac Os the Screenshots button is grayed out. 
In the attached screenshots you can see that on Windows if you are on "about:home", the Screenshots button has a black color even if it is disabled. On Mac Os you can see that the Screenshots button is grayed and it is disabled.

**Comment by 6a68** [comment]
> on Windows and Linux the button is not grayed out

Hmm, I think this might be the bug! I wonder if it's a WebExtension bug or something with how we toggle the CSS.

We probably should also enable the button on about:home, I'll file a separate bug for that.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Sorry, I just realized this _was_ the bug, I missed the title :-P

**Comment by 6a68** [comment]
Putting back the gamma blocker tag, sorry for the bug churn

**Comment by 6a68** [comment]
It turns out that it's a known issue that WebExtension buttons aren't visually changed when disabled on Windows and Linux :-\

https://bugzilla.mozilla.org/show_bug.cgi?id=1204609

We should be able to fix this easily enough, just need to add `setIconActive` calls next to the `enable` / `disable` calls inside the `onActivated` and `onUpdated` tab listeners inside `background/main`. I can put a PR together quickly, should only be a couple of lines.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible using the latest Screenshots custom build (dev and stage servers). 
The Screenshots button is grayed when it is inactive on "about:*" pages. Tested on Windows and Linux. Marking as verified.
