### ISSUE TITLE
Add Screenshots disable checkbox to about:preferences

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2711]
Product goal: add a checkbox to about:preferences, so that users can easily disable Screenshots.

From a technical standpoint, we'd like to do this without having to modify code that lives outside our system addon.

It turns out the form autofill system addon has already solved this problem. Once the `advanced-pane-loaded` observer event fires, it's safe to inject extra XUL elements: https://dxr.mozilla.org/mozilla-central/rev/c0ea5ed7f91a6be996a4a3c5ab25e2cdf6b4377e/browser/extensions/formautofill/FormAutofillParent.jsm#96-102

/edit adding John's screenshot from #2624 

<img width="1084" alt="84ff9224-1deb-11e7-83e1-2456fdba4a75" src="https://cloud.githubusercontent.com/assets/8632184/25245156/507387fc-25b8-11e7-8aaa-25c73d040cbf.png">

**Comment by wresuolc** [comment]
Let's talk to someone in UX (rfeeley?) to sync up with any preference pane changes

**Comment by 6a68** [comment]
This is needed to move to a pure webextension (#3875).

For users to set the 'screenshots.disabled' preference without going into about:config, we need to expose some UI with a checkbox. The existing UI for webextension options pages assumes users access the options from the extension's entry on the `about:addons` page. System addons aren't shown on the `about:addons` page, unfortunately.

I'm no longer so concerned about landing code outside the system addon, but that would be nice to have.

**Comment by clouserw** [comment]
@johngruen is this still something we want in about:preferences?  Seems like the landscape has changed since this was filed.

**Comment by 6a68** [comment]
Good question. I'll pull this into today's triage

**Comment by 6a68** [comment]
Actually, this seems kinda complicated. I'm going to leave this in stretch and start with an API experiment to access the existing prefs. I'll talk this over with addons folks next week.

**Comment by 6a68** [comment]
John does _not_ want to do this. Closing
