### ISSUE TITLE
Allow self-hosting via about:config pref?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2714]
It would be cool to allow users to run their own screenshots server, rather than require them to use ours.

Since exposing the endpoint via a pref would enable hijacking of potentially sensitive images, we might want to wait on this till after the 57 release, when XUL addons will be gone.

**Comment by wresuolc** [comment]
Let's have the discussion about 3rd party providers at the same time.

Ian notes some of this is hardcoded currently

**Comment by 6a68** [comment]
related to #3427. on second thought, I'll leave this one in stretch

**Comment by johngruen** [comment]
I don't see any reason _not_ to do this.

**Comment by johngruen** [comment]
To be clear. I don't think it's a super priority given that people can download everything starting in 57, but it seems like a cool thing to do for those who want it (might also be useful for testing dev servers etc.)

**Comment by ianb** [comment]
The [contentScripts.register()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts/register) API (new in 59) makes this more feasible.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
