### ISSUE TITLE
Truncate the referrer before sending to GA

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2717]
(This came from #2579)

There is a question about whether we should truncate (to just the domain) the referrer of a shot before sending it to GA.  This referrer is only ever seen by Mozilla employees who are analyzing the data.

Truncating may offer more privacy for a user who posts a shot.  Not truncating may allow mozilla to see how people are using Page Shot and improve the product.

@johngruen @ianb -- do you see a need for having the full referrer vs just the domain?

If there is a need, we should bring this up in our legal/privacy meeting to make sure we're all on the same page.

/cc @fmarier @ckprice

**Comment by ianb** [comment]
We've discussed this with Legal and decided to use the same policy we do with source URL, and truncate to origin.  So we should go ahead with this bug.
