### ISSUE TITLE
Change "Save" button text to something more suitable

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#2724]
As Firefox Screenshots/Pageshot offers an option to save the shot locally as well as upload it to the server, I found it very confusing that the button says "Save" but actually means to upload the image. It should have an icon instead as the other buttons have, of some better label, like "Upload" or maybe "Share".

**Comment by ckprice** [comment]
User research noted that Save performed well, in addition we're looking at a more holistic strategy for this communication. Thank you for the report!
