### ISSUE TITLE
The saved shots cannot be deleted from "My Shots" page (stage)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2730]
[Affected versions]:
- Firefox 55.0a1 (Build ID:20170424030211)
- Screenshots 6.4.4794

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.4.4794) custom build is installed on a new clean profile.
- Have at least one shot saved the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab.
2. Click the Firefox Screenshots button from browser toolbar. 
3. Hover a saved shot and click the "Delete" icon.
4. Click the "OK" button from the displayed dialog.
5. Observe the browser behavior.

[Expected result]:
- The saved shot is successfully deleted and is no longer displayed on "My Shots" page.

[Actual result]:
- A "Error deleting shot: 500 Internal Server Error" is displayed and the shot is not deleted.

[Notes]:
- The shot can be successfully deleted from the saved shot preview page.
- Here is a screen recording with the issue:
![delete saved shots](https://cloud.githubusercontent.com/assets/19226534/25338026/7f540118-2906-11e7-8112-c4791fcdedd9.gif)

**Comment by dannycoates** [comment]
oops. `/shots` needs a csrf token

**Comment by SoftVision-CosminMuntean** [comment]
@dannycoates It seems that this issue is also reproducible on the Nightly try build with the latest Screenshots release, received from jared.  
A "Error deleting shot: 500 Internal Server Error" is displayed if you try to delete a shot from "My Shots" page.

So, probably this fix wasn't deployed to production too?

**Comment by ianb** [comment]
The fix should be deployed to stage (as of last night), but not to production yet

**Comment by SoftVision-CosminMuntean** [comment]
@ianb  So the current version of Screenshots from production will be uplifted in Firefox?

**Comment by ianb** [comment]
This bug is purely on the server, and we aren't at the moment coordinating server and client releases.
