### ISSUE TITLE
If the shot has a large title, "My Shots" button is wrongly displayed on the saved shot preview page (stage)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2731]
[Affected versions]:
- Firefox 55.0a1 (Build ID:20170424030211)
- Screenshots 6.4.4794

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.4.4794) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any webiste.
2. Click the Firefox Screenshots button from browser toolbar and save a selection. 
3. Hover a saved shot and click the "Delete" icon.
4. Click the saved shot title and change it to a large title.
5. Observe the "My Shots" button.

[Expected result]:
- The "My Shots" button is correctly displayed.

[Actual result]:
- "My Shots" button is not entirely visible and the "My Shots" string exceeds the button area.

[Notes]:
- Here is a screen shot with the issue:
![my shots](https://cloud.githubusercontent.com/assets/19226534/25339774/75fefb62-290c-11e7-91da-a7468065c3eb.png)

**Comment by wresuolc** [comment]
@johngruen thinks this is fixed with an existing PR
