### ISSUE TITLE
Image doesn't show up on detail page

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2732]
I just took a shot in Nightly and it opened the screenshots.f.c page like it had created a shot, but the page was just the gray color with a header and footer.

Clicking download or digging through the DOM shows the image fine, but it won't show up on the page.

Nothing obvious in the console that I see

URL is at https://screenshots.firefox.com/U8ucgiEUM34NvfJ5/mozilla.slack.com

**Comment by ckprice** [comment]
Miles deployed fix, doesn't fix old ones, but fixes new ones. Closing.
