### ISSUE TITLE
Make protocol configurable

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2734]
Right now we're picking the protocol up from `X-Forwarded-Proto`.  This generally works fine, but we've seen at least one problem in production, and in production we really the protocol to be hardcoded.

I would propose that the configuration for this would force a protocol, but we leave the detection in place when the configuration isn't set.  I think the detection is helpful for development and ad hoc deployments.

**Comment by ckprice** [comment]
Miles fixed with deployment configs. WONTFIX
