### ISSUE TITLE
search button My Shots page

### ISSUE THREAD

**Issue by cecilebertin** [mozilla-services/screenshots#2757]
Version : latest code from github, Firefox Screenshots Beta

The search button in the My Shots page is not correctly rendered. The button is currently a long white rectangle next to the input field.
I think the icon is missing.

<img width="254" alt="screen shot 2017-04-26 at 19 06 45" src="https://cloud.githubusercontent.com/assets/21285660/25465019/9e4af086-2ab4-11e7-827f-c1185a615461.png">

**Comment by johngruen** [comment]
Yep! I have a patch inbound to fix this...and add all the bears.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on latest Nightly (55.0a1 - Build ID: 20170504030320) build and also on latest Beta 54.0b4.

Here is a screen shot with the issue:
![search](https://cloud.githubusercontent.com/assets/19226534/25737421/6dc0c0c6-3180-11e7-94ef-29c8469830a0.png)

**Comment by ianb** [comment]
We haven't deployed the style fixups to stage or prod yet, so the fix hasn't been deployed (note this is a server issue)
