### ISSUE TITLE
Screenshots Add-on icon nearly invisible on darker browser window themes

### ISSUE THREAD

**Issue by cecilebertin** [mozilla-services/screenshots#2758]
The Screenshots Add-on icon/button in the toolbar is almost invisible with darker browser window themes, like Firefox Developer Edition.

<img width="187" alt="screen shot 2017-04-26 at 19 25 32" src="https://cloud.githubusercontent.com/assets/21285660/25465389/c9d8fe4e-2ab6-11e7-9738-68e10d16ae08.png">

**Comment by wresuolc** [comment]
Thanks for filing this.  This is being tracked in #2347
