### ISSUE TITLE
Wait for startup to finish before shutting down

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2768]
This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1357805#c5 .  It sounds like if we don't do this we might be ok, or we might get flaky tests, and is there anything worse than flaky tests?

**Comment by wresuolc** [comment]
@kmaglione -- we're not sure if this is critical to land before we uplift or not.  We're worried that waiting for startup before shutting down risks hanging the whole browser if something goes wrong with startup.  Any recommendations or advice?

**Comment by kmaglione** [comment]
It shouldn't matter much for anything besides flaky tests. If no tests are failing without this as is, I wouldn't worry about it.

**Comment by wresuolc** [comment]
thanks

**Comment by ianb** [comment]
We've gone back and forth a bit on this... I think we actually do this correctly now.
