### ISSUE TITLE
Audit and document events added in style refactor

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2772]
@ianb i added some events, you like?

**Comment by wresuolc** [comment]
We're assuming this is related to #2769 .  Is there something to do in this issue that we wouldn't do in the comments on the PR?  Is this a 54 thing?

**Comment by wresuolc** [comment]
:you_like:

**Comment by wresuolc** [comment]
Ian is going to comment on the PR so closing this
