### ISSUE TITLE
If the "Back" button is clicked after a search is performed using the "Enter" key, the previously page is not loaded

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2773]
[Notes]:
- The issue is only reproducible for keywords that contains more than 3 characters.

[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170427130024)
- Screenshots latest version

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref is set to false.
- Have multiple saved shots.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Click on the "Screenshots" button from browser toolbar.
3. In the search field type a keyword with at least 4 characters and quickly press Enter.
4. Click the browser "Back" button and observe the page behavior.

[Expected result]:
- The previously page is loaded and all the saved shots are redisplayed.

[Actual result]:
- Nothing happens, the results for the entered keyword are still displayed.

[Additional Notes]:
- You need to click the "Back" button twice in order to be redirected to the all saved shots.
- Here is a screen recording with the issue:
![search with enter](https://cloud.githubusercontent.com/assets/19226534/25529121/6d3992e2-2c29-11e7-8f16-55ae4c5bda64.gif)

**Comment by johngruen** [comment]
Search no longer exists
