### ISSUE TITLE
robots.txt blocks Twitter card preview

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2774]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170427130024)
- Screenshots latest version

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref is set to false.
- You are already logged on a Twitter account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the "Screenshots" button from browser toolbar and save a selection.
3. Click the "Share" button and share the saved shot on Twitter.
4. Observe the shared shot.

[Expected result]:
- The saved shot preview image and the details are correctly displayed.

[Actual result]:
- Saved shot preview image and details are no longer displayed, only the saved shot link.

[Notes]:
- Here is a screenshot with the issue:
![twitter](https://cloud.githubusercontent.com/assets/19226534/25529851/90af291e-2c2c-11e7-8733-fa4963fd40e2.png)

**Comment by ianb** [comment]
This is due to robots.txt – Twitter won't fetch the card information for a site that blocks the Twitter bot.

**Comment by ianb** [comment]
Some robots:

- [ ] Twitter: https://dev.twitter.com/cards/getting-started#crawling
- [ ] Slack: https://api.slack.com/robots
- [ ] Facebook: https://developers.facebook.com/docs/sharing/webmasters/crawler

**Comment by ianb** [comment]
I have confirmed that this will not block Twitter: `<meta name="robots" content="noindex" />`

It also appears to work with Facebook, though Facebook is complaining about `og:image` being missing, despite it clearly being in the source of the page.  This might be a problem with my localtunnel setup.

**Comment by ianb** [comment]
Opened #2806 for removing robots.txt
