### ISSUE TITLE
404 when installing XPI via /homepage/install.html

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2775]
Clicking that link still redirects you to https://testpilot.firefox.com/files/pageshot/pageshot-0.1.201609082020.xpi which implodes and returns the Test Pilot 404 page:

https://screenshots.dev.mozaws.net/homepage/install.html

**Comment by wresuolc** [comment]
Try https://screenshots.dev.mozaws.net/homepage/install-test-local.html for local builds

Let's get rid of the other install page

**Comment by ianb** [comment]
I think this install.html file was only leftover as an accidentally build artifact (i.e., deleted, but the build didn't make clean and so the built file didn't get deleted).
