### ISSUE TITLE
When you open and close few new tabs quickly, an error is shown 

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#2789]
I am not sure about the exact STR, but when I open more new tabs and quickly close them, I see an error notification stating "We’re not sure what just happened..." and some more text. I thought there is not binding to a page or tabs until I interact with the Firefox button I have in the Firefox hamburger menu.

Where should I look for better debug information? Is there some log from the extension?

Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0 ID:20170501100238 CSet: 076a7a66096f9e8d102548397254be32eb26bc3d

**Comment by MikkCZ** [comment]
I have found, how to reproduce. Just quickly press "Ctrl+T" and "Ctrl+W". The error in browser console is:

> ------Error in promise: Error: Invalid tab ID: 439
Výpis zásobníku:
Async*@moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/background/main.js:187:26
watchFunction/<@moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:52:16
  catcher.js:62:7
	watchPromise/< moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:62:7
	(Async: promise callback)
	watchPromise moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:61:12
	<anonymní> moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/background/main.js:187:5
	watchFunction/< moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:52:16
Async*@moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/background/main.js:187:26
watchFunction/<@moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:52:16
  catcher.js:63:7
Unhandled error: Object { fromMakeError: true, name: "Error", message: "Error: Invalid tab ID: 439", stack: "Async*@moz-extension://4d99c3c7-a39…" } undefined  catcher.js:15:5
	exports.unhandled moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:15:5
	watchPromise/< moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:64:7
	(Async: promise callback)
	watchPromise moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:61:12
	<anonymní> moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/background/main.js:187:5
	watchFunction/< moz-extension://4d99c3c7-a39a-4781-8882-bb24677c8b97/catcher.js:52:16
Error: Object { fromMakeError: true, name: "Error", message: "Error: Invalid tab ID: 439", stack: "Async*@moz-extension://4d99c3c7-a39…" }  senderror.js:86:7
BindInt32Parameter is deprecated and will be removed soon.  (neznámý)
Error: Invalid tab ID: 439 ext-utils.js

**Comment by 6a68** [comment]
This seems to be fixed on current master. We exported master to mozilla-central last night, so Nightly should be picking up the fix within a day or so, and the fix should be uplifted to Beta soon.

BMO tracking bug for the export: https://bugzilla.mozilla.org/show_bug.cgi?id=1361208

**Comment by 6a68** [comment]
For reference, this was fixed by 11ec0806

**Comment by MikkCZ** [comment]
You are right. I cannot reproduce it anymore now.
