### ISSUE TITLE
eslint no-console

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2804]
The [no-console](http://eslint.org/docs/rules/no-console) rule disallows console.  I for one have a problem forgetting to remove all my console.logs, this could be helpful (though I would be a bit annoyed if it complains during development... but maybe there's a workaround for that).

**Comment by pdehaan** [comment]
I think I modified /.eslintrc.yml to the following and got about 62 errors:
```yaml
no-console: error
```

Apparently there is also an `allow` config we can use to say `console.warn()`, `console.info()`, and `console.error` are OK to use, and only `console.log()` will throw errors. This reduces the ESLint error count down to around 15 errors:
```yaml
no-console: [error, {allow: [warn, info, error]}]
```
Then for the remaining `console.log()` statements, we'd have to evaluate whether we want to delete them, or explicitly ignore them using `// eslint-disable-[next-]line no-console`.

**Comment by ianb** [comment]
For the add-on we could disable all of them, and of course allow them in addon/webextension/log.js

Ultimately in the server we should be using structured logs for everything, but right now only console.log is inappropriate there (except in a couple cases where we want to output unstructured information to the console for development).  Also `bin/` shouldn't have any rules on using console.
