### ISSUE TITLE
Remove robots.txt and replace with <meta name=robots value=noindex>

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2806]
`/robots.txt` blocks all access by all robots, including friendly robots like the Twitter summarization bot (that turns a link into a nice card).  I don't believe we can fix robots.txt unless we choose a small number of services to allow, and that doesn't align well with Mozilla's values.  Plus it's annoying to maintain.

Our goal is to avoid shot pages being indexed by search engines.  We can accomplish this with:

    <meta name="robots" value="noindex" />

We should add that to shot pages.  `/shots` is not public, and I don't believe any other pages are meaningfully private.

If we want to suppress indexing of images we'd have to add `X-Robots-Tag: noindex` to those requests.  At this moment (maybe just due to oversight) we don't block indexing of images.

**Comment by ianb** [comment]
Holding off on a PR for 1c6efd64fb2c0d60a56a90ab53f693b61d7bfa3b until @fmarier @jvehent @g-k or others chance for feedback

**Comment by fmarier** [comment]
Seems reasonable to me. Google, Bing, Yandex and Yahoo! support these:

https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag
https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240
https://yandex.com/support/webmaster/controlling-robot/html.xml
https://help.yahoo.com/kb/meta-tags-robotstxt-yahoo-search-sln2213.html
