### ISSUE TITLE
URLs to og:image and twitter:image metadata should be fully qualified

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2810]
Re: <view-source:https://screenshots.stage.mozaws.net/>

```jsx
<meta property="og:image" content="/static/img/onboarding-1.png"/>
<meta name="twitter:image" content="/static/img/onboarding-1.png"/>
```

Per http://ogp.me/#metadata and https://dev.twitter.com/cards/types/summary-large-image:

- `og:url` &mdash; The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

- `twitter:image` &mdash; A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

**Comment by pdehaan** [comment]
I think these may be the only 2-3 direct links to "/static/..." versus everything else being proxied via `${this.props.staticLink("/static/...")}`:

```sh
$ git grep '="/static/'

server/src/pages/homepage/view.js:        <meta property="og:image" content="/static/img/onboarding-1.png" />
server/src/pages/homepage/view.js:        <meta name="twitter:image" content="/static/img/onboarding-1.png" />
static/homepage/install-test-local.html:      <img src="/static/img/new-scissors-icon.svg" height="256" width="256" />
```

**Comment by pdehaan** [comment]
Ah, maybe these should be using `staticLinkWithHost()` to make them fully qualified.

**Comment by ianb** [comment]
Note static/homepage/install-test-local.html isn't a React page and so we can't use staticLink there - but the page is just for debugging.

**Comment by deepakbaltech** [comment]
Hello,
Is there any way to use Canonical URL or some other site url instead of image url, and twitter card will display image from that specified Canonical site, like Facebook share do!!
