### ISSUE TITLE
Warning: It looks like you're using a minified copy of the development build of React

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2811]
DevTools sayeth:

> _"Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details."_
> &mdash; via homepage-bundle.js:9:3421

<img width="1440" alt="firefox_screenshots" src="https://cloud.githubusercontent.com/assets/557895/25728177/3c74f5e4-30e2-11e7-8e9b-cc0869d4e12a.png">

**Comment by wresuolc** [comment]
@ianb for -dev work

**Comment by potch** [comment]
Screenshots probably shouldn't ship with a massively slower react build in production.

**Comment by ianb** [comment]
Huh, still not fixed, despite a few iterations on this.

**Comment by chenba** [comment]
FWIW when I `export NODE_ENV=production && make server` locally, I'd get bundles that do not produce that warning.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
