### ISSUE TITLE
Shot images not loading on dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2812]
Found in https://screenshots.dev.mozaws.net/__version__ (5557426):

```json
{
  "source": "https://github.com/mozilla-services/screenshots/",
  "description": "Firefox Screenshots application server",
  "version": "6.6.0",
  "buildDate": "May 04, 2017 20:41:35 UTC",
  "commit": "5557426",
  "contentOrigin": "screenshotsusercontent.dev.mozaws.net",
  "commitLog": "https://github.com/mozilla-services/screenshots/commits/5557426",
  "unincludedCommits": "https://github.com/mozilla-services/screenshots/compare/5557426...master",
  "dbSchemaVersion": 16
}
```

---

### Steps to reproduce:
1. Install add-on.
1. Take some shots.
1. Go to https://screenshots.dev.mozaws.net/shots

### Actual results:
<img width="1440" alt="my_shots" src="https://cloud.githubusercontent.com/assets/557895/25729513/a05051f0-30ea-11e7-8eeb-64ae88984425.png">

If I go to the shot detail page, https://screenshots.dev.mozaws.net/4Gw8iq91OBTjV1YR/screenshots.dev.mozaws.net, it just spins and spins and never loads.

**Comment by wresuolc** [comment]
@ianb is working on hooking up dev, I think

**Comment by wresuolc** [comment]
I'm going to assume this is fixed now
