### ISSUE TITLE
The images from the empty "My Shots" page are wrongly displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2815]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170504030320)
- Beta 54.0b4
- Screenshots 6.6.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref is set to false.
- Have no saved screenshots on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Observe the image from the empty "My Shots" page.
3. Perform a search using any keyword and observe the image from "no results found" page.

[Expected result]:
- Step 2 & Step 3: The images are correctly displayed in the center of the page.

[Actual results]:
- Step 2 & Step 3: The images are wrongly positioned on the page.

[Notes]:
- Here is a screen shot with the issue:
![images](https://cloud.githubusercontent.com/assets/19226534/25737435/80ef8934-3180-11e7-8755-3f9415554412.png)

**Comment by wresuolc** [comment]
@johngruen fixed this, but it didn't make it into 6.6.0.  fixed though!
