### ISSUE TITLE
When hovering a saved shot tile form "My Shots" page, the "Delete" icon is no longer displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2816]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170504030320)
- Beta 54.0b4
- Screenshots 6.6.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build and the "extensions.screenshots.system-disabled" pref set to false.
- Have at least one saved shot on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Click on the "Screenshots" button from browser toolbar.
3. Hover a saved shot tile and observe the top right corner of it. 

[Expected result]:
- A "Delete" icon is displayed on the top right corner of the tile.

[Actual result]:
- The "Delete" icon is no longer displayed on the the top right corner of the tile.

[Notes]:
- Here is a screen recording with the issue:
![delete icon](https://cloud.githubusercontent.com/assets/19226534/25738592/a74419be-3186-11e7-8121-fb9219aa22bf.gif)

**Comment by johngruen** [comment]
Yeah, this has been fixed, but is not live
