### ISSUE TITLE
Downloaded Screenshot leaks from Private Browsing to Normal Browsing

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#2818]
[Affected versions]:
Firefox 54.0b5(Build Id:20170504103226)
Firefox Screenshots 6.6.0

[Affected platforms]:
Windows 10 64bit
Mac 10.11.6
Ubuntu 16.04 64bit

[Steps to reproduce]:
1.Open Firefox with a clean profile.
2.Enable Firefox Screenshots.
3.Open a New Private Window.
4.Access www.google.com webpage from the Private Window.
5.Click the Firefox Screenshots button.
6.Focus any area.
7.Click the download button.
8.Observe that the downloaded file is leaked in the normal browsing window

[Expected result]:
The Downloaded screenshot appears only in the Private Window.

[Actual result]:
The Downloaded screenshot is leaked to the Normal Browsing window.

[Additional Notes]
Please observe the following video for more information: https://drive.google.com/drive/folders/0B94iuIVMr-TEcGJnczdIZ19NUXM?usp=sharing

**Comment by ianb** [comment]
I can reproduce this.  It's specific to private browsing, it doesn't happen with two normal windows.  If you do something like save an image from a private browsing window it doesn't have this problem.

It occurs to me that when we download the image in the WebExtension it's from the background page, and that's not associated with any particular window.  I don't [see any options](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download) that would help.

**Comment by ianb** [comment]
[Bug 1362448](https://bugzilla.mozilla.org/show_bug.cgi?id=1362448) created for the WebExtension support.

**Comment by wresuolc** [comment]
Let's just disable ourselves completely in private browsing mode

**Comment by pierreneter** [comment]
Why do we have to disable it in incognito mode? I think we should leave it in the download of incognito mode...

**Comment by 6a68** [comment]
@pierreneter Thanks for the feedback. If you save to the cloud, private and non-private screenshots would be mixed. Ditto for downloads. We don't have time to make significant changes for Firefox 55, so this is the best we can come up with. Hopefully we can make private browsing work for a future version

**Comment by johngruen** [comment]
@6a68 i think the long term solution here is to ONLY allow download in private browsing. The difficulty is managing downloads in the correct context. I may have read the docs for werExt incorrectly, but it seems like we'd need the `"incognito": "split"` api implemented

**Comment by johngruen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1345474

**Comment by johngruen** [comment]
Filed a tracking bug for the full webExtension implementation here: https://bugzilla.mozilla.org/show_bug.cgi?id=1380809

**Comment by ianb** [comment]
With #3120 this issue is moot (we're not allowing Screenshots to be used in Private Browsing mode). We should revisit this when [Bug 1362448](https://bugzilla.mozilla.org/show_bug.cgi?id=1362448) is resolved and shipped.

**Comment by 6a68** [comment]
Reopening; bug 1362448 is fixed as of 57.
