### ISSUE TITLE
Write pref tagging system add-on to test instrumented roll-out of Screenshots in Beta

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/screenshots#2819]
@gregglind is going to write this for us.

This add-on will exist to pref on a segment of Beta users and monitor things like page views, session hours, default browser state, crashiness etc.

Pref is `extensions.screenshots.system-disabled`

Screenshots is currently pref'd off in Beta. We'd like to do a test on May 10th to ensure that this will be release ready on June 19th.

We'll use Bug 1351424 to pref this on for everyone in Beta.

Sample code:

(e.g. https://github.com/gregglind/quantum-preference-telemetry-annotation-pretender/blob/master/index.js )  (more direct:  https://gist.github.com/gregglind/18d985d79c70a5fbefc0d471894d4c6b)

**Comment by gregglind** [comment]
GOT IT!  This is on me.

**Comment by gregglind** [comment]
FWIW, pref-flip is LIVE in nightly, undergoing tests.   [mozilla/normanday/issue/734](http://github.com/mozilla/normandy/issue/734)
