### ISSUE TITLE
Download, Share, and Delete buttons are in different orders on shots vs details pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2823]
Found in https://screenshots.dev.mozaws.net/__version__ (5557426):

```json
{
  "source": "https://github.com/mozilla-services/screenshots/",
  "description": "Firefox Screenshots application server",
  "version": "6.6.0",
  "buildDate": "May 04, 2017 20:41:35 UTC",
  "commit": "5557426",
  "contentOrigin": "screenshotsusercontent.dev.mozaws.net",
  "commitLog": "https://github.com/mozilla-services/screenshots/commits/5557426",
  "unincludedCommits": "https://github.com/mozilla-services/screenshots/compare/5557426...master",
  "dbSchemaVersion": 16
}
```

---

<img width="745" alt="my_shots" src="https://cloud.githubusercontent.com/assets/557895/25761875/38df36d8-3191-11e7-968d-8ea450770e29.png">

**Figure 1:** /shots page (Download ➡️ Share ➡️ Delete)

versus:

<img width="741" alt="install_dev_firefox_screenshots" src="https://cloud.githubusercontent.com/assets/557895/25761765/d0b814da-3190-11e7-92b3-2b3987c8058d.png">

**Figure 2:** details page (Delete ➡️ Share ➡️ Download).

**Comment by wresuolc** [comment]
@johngruen is going to sync up with the design team

**Comment by johngruen** [comment]
This is how it's spec'ed
