### ISSUE TITLE
Do not change button state when tab is updated

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2824]
Turns out toggling the button icon when the tab URL is updated is contributing to performance regressions. Ripping out that code now.

We will still toggle between the onboarding and regular button states.

**Comment by dannycoates** [comment]
> Turns out toggling the button icon when the tab URL is updated is contributing to performance regressions

is it though?

**Comment by 6a68** [comment]
Yeah, I'm told that this fix plus some webextension framework changes (see the bug tree [on this bug](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1361792)) will bring our Talos regressions to a reasonable point

**Comment by dannycoates** [comment]
i mean, yeah, taking out code can only make it faster but it's pretty sad that something so trivial is a problem. 🙁
