### ISSUE TITLE
Deploy dev from a different docker hub location

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2833]
Right now we deploy from `mozilla/screenshots:latest`, but I'd like to change that to something like `mozilla/screenshots-dev:latest`, so that we can give permission to update that location to CircleCI, without giving CircleCI access to `mozilla/screenshots`

Because we want to deploy to dev from CircleCI, we need to give that system the credentials to upload images.

I'd like to create a new user that can push to a new place, where that can only affect the dev Screenshots deployment.  Maybe to `mozilla/screenshots-dev` ?

I've created a user for this purpose with the username `screenshotsautodeploy` and email `ibicking+autodeploy@mozilla.com`, but the ansible scripts also have to be updated as well as dockerhub permissions.

/cc @relud @jvehent

**Comment by jvehent** [comment]
Why doesn't circleci have access to `mozilla/screenshots` on dockerhub? Isn't that where you currently publish containers built by circleci?

**Comment by relud** [comment]
there are not currently published containers built by circleci, because building containers requires signing the addon

**Comment by jvehent** [comment]
Can the addon not be inside the container, but built, signed and hosted elsewhere? If it must be added to the container, circleci can download it from some location.

**Comment by relud** [comment]
> I'd like to change that to something like mozilla/screenshots-dev:latest, so that we can give permission to update that location to CircleCI, without giving CircleCI access to mozilla/screenshots

why don't you want to give CircleCI access to `mozilla/screenshots`? that is exactly how most of our apps build their docker containers.

**Comment by ianb** [comment]
This was just intended to make things a bit more secure, but if giving CircleCI access to these areas is okay then I'll leave it as is.
