### ISSUE TITLE
The "Share" panel remains open but hidden, even if the saved shot tile is no longer focused (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2834]
[Affected versions]:
- Firefox 54 and up
- Screenshots (6.6.5561)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.6.5561) dev build is installed on a new clean profile.
- Have at least 5 saved shots on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Click the "Screenshots" button from browser toolbar.
3. Hover the first saved shot tile and click the "Share" button.
4. Move the mouse cursor outside the saved shot tile and observed the behavior.
5. Hover again the first saved shot tile and observe the behavior.

[Expected result]:
Step 4. The "Share" panel is dismissed.
Step 5. The "Share" panel is not displayed and the "Share" button is no longer active.

[Actual results]:
Step 4. The "Share" panel is no longer displayed.
Step 5. The "Share" panel is still displayed and the "Share" button is still active. 

[Notes]:
- When you hover the area where the "Share" panel was displayed, it reappears.
- Here is a screen recording with the issue:
![share pop-up still active](https://cloud.githubusercontent.com/assets/19226534/25903086/1f258d34-35a4-11e7-95af-f037284304c1.gif)

**Comment by johngruen** [comment]
@ianb not quite sure how to resolve this one since i'd have to pass props down into the button from a mouseout event in the card. Seems like we'd have to componentize cards

**Comment by ianb** [comment]
Yes, we'd want to make each card a component, that probably includes the share panel as a subcomponent. I'm guessing we're not far from that looking at shotindex/view.js – ShareButton belongs to the card, ShareButtonPanel belongs to the ShareButton. Maybe we just make Body.renderShot into a separate component.

Do we even want the share panel to disappear in this case? It seems like we should leave it open until there is a click outside the area, similar to shot pages.  I think the current behavior is a side-effect of the :hover selector showing the buttons. I can't come up with any way to fix this in CSS alone, and annoyingly it seems like it requires breaking the boundaries of the components some.
