### ISSUE TITLE
If you quickly click the "Share" button after hovering a tile, the "Share" panel is displayed for a moment under the second row of tiles on "My Shots" page (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2835]
[Affected versions]:
- Firefox 54 and up
- Screenshots (6.6.5561) dev server

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.6.5561) dev build is installed on a new clean profile.
- Have at least 5 saved shots on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Click the "Screenshots" button from browser toolbar.
3. Hover the first saved shot tile and quickly click the "Share" button.
4. Observe the "Share" panel.

[Expected result]:
- The "Share" panel is correctly displayed.

[Actual results]:
- The "Share" panel is displayed for a moment under the second row of titles.

[Notes]:
- Here is a screen recording with the issue:
![share pop-up displayed under tiles](https://cloud.githubusercontent.com/assets/19226534/25903333/c9e247da-35a4-11e7-806f-28b3e9abb2e8.gif)

**Comment by ckprice** [comment]
More share cleanup for John.

**Comment by johngruen** [comment]
@niharikak101 to confirm and probably close

**Comment by niharikak101** [comment]
Not reproducable after #2940, closing.
