### ISSUE TITLE
"UI is not defined" error is constantly thrown when dragging through the website 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#2838]
[Affected versions]:
Firefox 54.0b6 (Build Id:20170508210007)
Firefox Screenshots 6.6.0

[Affected platforms]:
Windows 10 64 bit
MacOS 10.10.5
Ubuntu 16.04 64bit

[Steps to reproduce]:
1. Open Firefox with a clean profile.
2. Enable Firefox Screenshots.
3. Access the http://www.imdb.com/ website.
4. Click the Firefox Screenshots button.
5. Perform a selection.
6. Click the Firefox Screenshots button again.
7. Drag through the website.

[Expected result]:
No error is thrown.

[Actual result]:
“Whoa! Firefox Screenshots went haywire” with “ReferenceError: ui is not defined” is constantly thrown when dragging through the website.

[Additional notes]
Please observe the following video for more information:https://drive.google.com/open?id=0B94iuIVMr-TEVlNBOU0xWjRObFE

**Comment by ckprice** [comment]
@emilghittasv having trouble reproducing this one. Can you provide any further info?

**Comment by emilghittasv** [comment]
@ckprice That's strange, I can still reproduce this issue with Firefox beta 54.0b7 by following the mentioned steps (It keeps trowing me the mentioned error). 

You need to: 
1.Open Firefox Screenshots.
2.Drag on the page to select a region.
3.Click the Firefox Screenshots button again.
4.Keep dragging through the page.

**Comment by emilghittasv** [comment]
Here are some other steps that might be of help:

1.Launch Firefox with a clean profile.
2.Enable Firefox Screenshots.
3.Got to https://ro.pinterest.com/ webpage.
4.Open any image.
5.Click the Firefox Screenshots button.
6.Click the Firefox Screenshots button again to close Firefox Screenshots.
7.Click the next button.
8.Observe that the error occurs.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Screenshots 8.2.0 and is no longer reproducible. Marking as verified.
