### ISSUE TITLE
Give account screenshotsautodeploy access to mozilla/screenshots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2839]
Currently CircleCI is setup to deploy with my account, but I've created a new account that I'd like to use instead: `screenshotsautodeploy` /cc @relud

**Comment by ianb** [comment]
Ops / @relud is going to create a new user, give it permission, store the credentials, and update CircleCI with those credentials.  The [env variables](https://circleci.com/gh/mozilla-services/screenshots/edit#env-vars) `DOCKER_*` need updating.

**Comment by relud** [comment]
fixed
