### ISSUE TITLE
The "Screenshots" button is active in the browser toolbar on shot pages

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla-services/screenshots#2840]
[Notes]:
- This issue is reproducible on Dev and Stage builds.
- Due to this issue the user is able to take screenshots of the shot pages.

[Affected versions]:
- Firefox 54 and up
- Screenshots (6.6.9566)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (6.6.9566) dev is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a new tab.
2. Click on the "Screenshots" button in the toolbar.
3. Click and observe the "Screenshots" button.

[Expected result]:
- The "Screenshots" button is inactive.

[Actual results]:
- The "Screenshots" button is active and you can take screenshots on "My Shots" page.

[Additional Notes]:
- Here is a screen recording with the issue:
![screenshots_issue](https://cloud.githubusercontent.com/assets/20083658/25958590/ae8c00f4-3679-11e7-9e71-dd35e20d6ccd.gif)

**Comment by wresuolc** [comment]
This is part of the 6.6.2 changes.  We're having to redo the icon code for performance reasons, so this is kind of in flux.
