### ISSUE TITLE
Lazy load all the things

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2841]
To avoid negatively impacting performance at startup, move the toolbar button code from the WebExtension to the bootstrapped wrapper code.

I think this could work:

- When FF starts, just check the pref (bootstrap)
  - If enabled, load the toolbar button and a click handler (bootstrap)
  - Move "has user onboarded" check from webextension to bootstrap, so we know which icon to show in the toolbar button (bootstrap, webextension)
- On initial click, load the webextension (bootstrap)
- When webextension loads, it should ask the wrapper if the overlay should be shown in the currently-focused tab (webextension)
- On subsequent button clicks, send a message to the webextension (bootstrap)
- Instead of firing click handler on webext click, fire click handler on click message from bootstrap (webextension)

**Comment by ianb** [comment]
Note the WebExtension handles authentication when you organically return to pages.  I might propose that the WebExtension be able to ask bootstrap to eagerly load, and that it do so after your first successful upload (the same place where we set `registered` to true).

**Comment by 6a68** [comment]
>  I might propose that the WebExtension be able to ask bootstrap to eagerly load

Loading the WebExtension itself is the performance hit we're trying to avoid. So, after the first usage, we would be back to regressing startup time.

What's an example of an auth flow that would be disrupted by this change?

**Comment by 6a68** [comment]
>  also manage the onboarding flag (which changes the icon) in the WebExtension, but we could manage this in bootstrap.js

Yeah, good point. I'll add that to the task list

**Comment by ianb** [comment]
> What's an example of an auth flow that would be disrupted by this change?

Use Screenshots, create a shot at screenshots.firefox.com/id/foobar.com then restart the browser – in order to be authenticated on the page screenshots.firefox.com/id/foobar.com you'll need the WebExtension loaded.

Note this *does* regress performance for someone who has saved a shot, which is not a case that Talos will test.  It also only regresses users who have used the Screenshots service (download-only users need not be affected).  We'd be relying on the WebExtension performance work to catch up.

**Comment by ianb** [comment]
It would be nice if we could revert to current behavior with a pref, though I don't know how easy that would be to manage due to the conflict between a bootstrap-implemented toolbar button and a browserAction button.  A pref would let us more easily do performance testing so we know when we can remove this code.

**Comment by 6a68** [comment]
> It would be nice if we could revert to current behavior with a pref

That is a fantastic idea, we could call it `extensions.screenshots.lazy-load`, where we use extreme lazy-loading if that pref is `true`. I think it work fine, provided we fully restart the addon when that pref is flipped, along the lines of what you'd do on addon version upgrades.

Bootstrap changes:

We already have the bootstrap startup method calling another method, handleStartup. So, we'd just handleShutdown, then handleStartup, and expect handleStartup to do different things if the pref is enabled.

Webextension changes:
We'll probably want to conditionally load the toolbar button code. I believe we can pass arguments into the webextension object's startup() method, so the webextension can read the pref value at startup (all the pref values, actually) and decide whether to draw the button or just listen for button click events from bootstrap.

Because we'll be swapping the buttons between webextension control and manual control, the position of the button will, in general, vary. This will cause more headaches with the toolbar button tests. We already have such headaches; just something to note.

This complicates the todo list a bit, I'll rewrite in a comment here before updating the description.

**Comment by 6a68** [comment]
Does this seem right? Inside bootstrap:

- on startup(*), check prefs to determine if screenshots is enabled
  - if enabled, check pref to determine if screenshots should lazy load
    - if lazy-load is enabled, draw the toolbar button from bootstrap
      - check the onboarding pref(**) to decide which icon to show
      - the bootstrap button's click handler can lazily instantiate the webextension & send a postmessage once communication is established
      - we'll have to figure out how to get a tabId from bootstrap to webextension that will Just Work for the webextension
    - if lazy-load is disabled, start the webextension from bootstrap
      - this is basically the current code path
- bootstrap needs a lazy-load pref listener: on lazy-load pref change, call handleShutdown, then handleStartup
- on shutdown, if lazy-loaded, bootstrap will need to unload the toolbar button; otherwise, webextension will
  - I don't think there's anything particularly tricky about shutdown, just bookkeeping relative to startup (removing whatever listeners / buttons were added by whichever code path)

(*) we'll need to work with perf folks to decide whether we should wait for a specific startup nsIObserver event to fire, or just run the code as soon as our addon is executed

(**) it makes sense to keep onboarding state in a pref, since using localstorage will require loading a window just to get to the storage (or maybe there's an XPCOM service that can access web storage for a given moz-extension URL...but that seems like it could be tricky)

**Comment by ianb** [comment]
> the bootstrap button's click handler can lazily instantiate the webextension & send a postmessage once communication is established

For this I was thinking:

```js
let hasPendingClick = false;
onClick: () => {
  hasPendingClick = true;
  startWebExtension();
}
onMessage: (msg) => {
  if (msg.type == "hasPendingClick") {
    return hasPendingClick; // maybe set hasPendingClick to false?
  }
}
// In WebExtension main.js, runs on startup:
callBootstrap("hasPendingClick").then((hasPendingClick) => {
  if (hasPendingClick) {
    startOnCurrentTab();
  }
});
```

> bootstrap needs a lazy-load pref listener: on lazy-load pref change, call handleShutdown, then handleStartup

Or we only look at that pref on startup?  It's just for performance debugging.  I assume Talos tests can set a pref before startup...?

I also wonder if we have to remove browserAction from manifest.json, so it doesn't conflict with the add-on?  It would be cool if we could give the bootstrap button the id `screenshots_mozilla_org-browser-action` and the WebExtension would take it over on startup, but I don't know if that works (seems unlikely).

**Comment by 6a68** [comment]
> I also wonder if we have to remove browserAction from manifest.json, so it doesn't conflict with the add-on

Good question! We'll have to experiment with dynamically modifying the manifest file, or swapping between two different files. I wonder if we'll hit caching bugs if the pref is flipped after the webextension is initially loaded. We probably should figure this part out before we decide on taking this lazy-load approach.
