### ISSUE TITLE
Lazy load our background page code

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#2843]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1361792#c31 :

> After some further investigation, it looks like a lot of the startup responsiveness issues are caused by loading a huge amount of code into the Screenshots background page at startup. It would help a lot if the add-on lazily loaded its background page code when first needed (something like require.js might be a good idea), and avoided touching extension APIs before absolutely necessary.

It looks like this is taking 150-200ms at startup

**Comment by wresuolc** [comment]
This didn't do as much as we thought when we tried it, so let's not deal with it for now.

**Comment by ianb** [comment]
Kris feels this would be helpful, [per this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1361792#c45)

**Comment by ianb** [comment]
We'll have to bring back the [lazy-background](https://github.com/mozilla-services/screenshots/tree/lazy-background) branch.  I know at least two things that aren't done in that branch:

- [ ] Context menu activation (currently only browserAction is handled)
- [ ] Handling messages (e.g., if sitehelper tries to communicate with the background page)
