### ISSUE TITLE
Let's add UTM parameters for various places where people can copy shot URLS

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2846]
### Here's the concept

There are four places where users can get shot URLs
1. From the automatic copy to clipboard action
2. By copying from the URL bar directly
3. From the share panel on the Shot Page
4. From the share panels on the shots index page

We should add different UTM codes to each of these locations so that we can better understand how each version propagates across the web. 

Maybe Gareth could help us define appropriate params? I'd love to keep them short.

Also we'll probably need legal/privacy review here.

**Comment by garethcull** [comment]
Sure thing John. Comments below for each. Append the following to each url:

1. ?utm_source=clipboard&utm_medium=fx-screenshots&utm_campaign=share-shot

2. ?utm_source=url-bar&utm_medium=fx-browser&utm_campaign=share-shot

3. From the share panel on the Shot Page
- It might be a good idea to attribute to the sources shared (ie. twitter, fb, etc) and denote the share coming form the shot page as a utm_campaign. This way, you'll be able to see total outbound shares to twitter / fb/ etc and then the resulting inbound traffic from each of these sources + be able to attribute this all back to the shot page. I'd append the following:
- example: ?utm_source=twitter&utm_medium=social&utm_campaign=share-shot-pg

4. From the share panels on the shots index page
- same rationale as 3, but updating the utm_campaign to share-shot-index
- example: ?utm_source=twitter&utm_medium=social&utm_campaign=share-shot-index

I know they are a bit long with the campaign param but you'll be able to roll-up all inbound traffic from shares by filtering on campaigns containing share-shot.

Any questions, let me know. Thanks.

**Comment by johngruen** [comment]
no this looks great! Thanks so much @garethcull, @clouserw @ianb how does this strike you guys?

**Comment by wresuolc** [comment]
strikes well! 🏅

**Comment by wresuolc** [comment]
@johngruen wants to get input from Elvin on this before we move forward.  Mahe is going to organize a meeteing

**Comment by wresuolc** [comment]
Meeting was fine.  Let's add these parameters. Thanks!

**Comment by ianb** [comment]
After some discussion we all were a little reluctant to add utm parameters everywhere. But note we could create our own short form of these parameters and decode them in [ga-activation.js](https://github.com/mozilla-services/screenshots/issues/3429). E.g., `?s=u` could be equivalent to `?utm_campaign=urlbar`
