### ISSUE TITLE
Authentication is lost after shot page load

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2860]
Not sure what's going on here, could be a weird tooling issue, but if I run:

    ./bin/run-addon -s https://screenshots.firefox.com

and then make a shot, and the link in the corner renders as My Shots on the server, but on local rendering it becomes a link to the homepage (i.e., once the page is rendered it thinks you aren't the owner). My Shots still works.

This might be specific to local testing, and moving accounts around between services. Just feels fishy.

**Comment by johngruen** [comment]
@ianb to verify fixed and close

**Comment by ianb** [comment]
@johngruen just saw this on production
