### ISSUE TITLE
Add instructions to Screenshots Pontoon for viewing/using dev

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2862]
Localizers can view the results of their localization (both server and add-on) on our dev server.  There are instructions on https://screenshots.dev.mozaws.net/homepage/install-test-local.html about how to install an add-on that points to this server.

The page should be self-explanatory, but we need to link users to this page.

/cc @flodolo

**Comment by flodolo** [comment]
It can be added to the project info
https://pontoon.mozilla.org/projects/firefox-screenshots/info/

I'm not sure it makes a lot of sense to add it until we expose strings for the website though.

**Comment by flodolo** [comment]
Actually, I realized that we had the old website linked as resource, I've updated it with the new link, and added it to the main description.

**Comment by wresuolc** [comment]
Is there anything else to do for this issue?
