### ISSUE TITLE
Very large image doesn't load

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2863]
In user testing this shot saved, but wouldn't load: https://screenshots.firefox.com/Y1rS5yVPnyLxB7sM/www.amazon.com

Note the image exists: https://screenshots.firefoxusercontent.com/images/109dd3a8-7caf-4ab6-9c99-6faedfb6a781.png

I think it was taken as a high-DPI image.

I think our onload code here is keeping the image from showing while it loads, meaning that you don't get much of a progress.

**Comment by dannycoates** [comment]
The img tag is referencing http not https

**Comment by ianb** [comment]
Arg!  This bug again.  We had intermittent problems with this before, and the person who made this shot did successfully make another shot, so it wasn't a consistent problem.  @milescrabill made some operational fixes which fixed this, but @relud has been changing the configuration some, I wonder if it could have been undone? Maybe we should revisit #2734 again.

**Comment by relud** [comment]
we are still forcing X-Forwarded-Proto:https in nginx on prod, I double-checked.

**Comment by wresuolc** [comment]
Duping to #2734
