### ISSUE TITLE
Long text overlaps the icon in take a shot mode

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#2867]
When taking a screenshot in localized version, where the translated text has more line than the original, it overlaps the nice smile/eyes icon.

Here is the screenshot of the issue.
![screenshot of the issue](https://cloud.githubusercontent.com/assets/3941344/26285601/57f103f2-3e53-11e7-8845-aeda15d4d55b.png)

CCing @flodolo to know.

**Comment by MikkCZ** [comment]
In the meantime I have shortened our translation of the text, but this may affect more localizations.

**Comment by johngruen** [comment]
@MikkCZ thanks, this could have been implemented with more flexibility; I fixed it in my PR

<img width="1282" alt="screen shot 2017-05-23 at 1 05 00 pm" src="https://cloud.githubusercontent.com/assets/3323249/26351668/d3de678c-3fb8-11e7-941c-b6822776707f.png">

**Comment by MikkCZ** [comment]
I haven't build and tested with your fix, but the screenshot looks promising. ;)
