### ISSUE TITLE
The "Share" pop-up is wrongly opened over the "Report", "Share" and "Download" buttons on other browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2873]
[Notes]:
- On Edge browser the image is not loaded and the spinner looks stuck. 
- On IE browser, the page is wrongly rendered (this issue is already logged: #2516).

[Affected versions]:
- Chrome, Safari, Edge, IE
- Screenshots 7.0.10522

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Safari or Chrome browser.
2. Navigate to a shared shot (eg: https://screenshots.firefox.com/Z54pXfM5vI89cmN4/www.wikipedia.org).
3. Click the "Share" button and observe the position where the "Share" pop-up is displayed.

[Expected result]:
- The "Share pop-up" is displayed under the "Report", "Share" and "Download" buttons.

[Actual results]:
- The "Share" pop-up is wrongly displayed over the "Report", "Share" and "Download" buttons

[Additional Notes]:
- Here is a screen recording with the issue on Chrome browser:
![share](https://cloud.githubusercontent.com/assets/19226534/26353405/f4c70e12-3fc8-11e7-9aac-a92f8f981fc7.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.

**Comment by SoftVision-CosminMuntean** [comment]
Reopening this issue due to the fact is again reproducible on other browsers.

![share panel](https://user-images.githubusercontent.com/19226534/29026237-8c46eb9a-7b83-11e7-9e19-ba7b2c92b644.gif)

**Comment by 6a68** [comment]
Looks like the issue here is that the share panel is absolutely positioned, but its position isn't getting adjusted when the blue "get firefox" bar is added at the top of the page.
