### ISSUE TITLE
"q", "y", "p", "g" and "j" letters are wrongly displayed while editing a saved shot's title

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2876]
[Notes]:
- I have also noticed that the title text box can be scrolled if you press middle click and move the mouse up/down.

[Affected versions]:
- Firefox 53.0.3 and up
- Both stage and dev Screenshots versions

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots dev or stage build is installed on a new clean profile.
- At least one shot is saved.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to "My Shots" page.
2. Click on the saved shot.
3. Click on the saved shot title from the grey toolbar.
4. Type the following letters: p, q, y, j and g.
5. Observe the way the typed letters are displayed inside the title field.

[Expected result]:
- The typed letters are correctly displayed and fully visible.

[Actual result]:
- The typed letters are truncated.

[Additional notes]:
- Added a screen recording with the issue:
![truncated](https://cloud.githubusercontent.com/assets/26000308/26360627/3b5bff14-3fe1-11e7-92d5-16b358b318ba.gif)

**Comment by johngruen** [comment]
@ianb @6a68 just assign any front end nit bugs like this to me; i'll knock em all out next week

**Comment by SoftVision-CosminMuntean** [comment]
Unfortunately this issue is still reproducible on Windows. Also, it seems that if the title of the shot contains Chinese or Japanese characters, a scrollbar wrongly appears on the title field. 

Here is a screenshot of the issue:
![baidu](https://user-images.githubusercontent.com/19226534/37968579-40516624-31d7-11e8-80cb-ef49be91f363.png)

However, on Mac Os and Linux the issue is no longer reproducible.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
