### ISSUE TITLE
"Download", "Share" and "Delete" buttons do not loose their highlight after each respective action is completed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#2880]
[Affected versions]:
- Firefox 55 and up
- Screenshots Dev (7.0.11976)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (7.0.11976) dev is installed on a new clean profile.
- At least one shot is saved.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to the My Shots page.
2. Hover one of the saved shots and click the "Delete" button.
3. Click the "Cancel" button and hover the same saved shot.
4. Observe the "Delete" button state.

[Expected result]:
- The button is no longer highlighted.

[Actual results]:
- The button is highlighted even though the mouse is not hovering it.

[Notes]:
- On Mac, the issue is reproducible only for the "Download" button.
- For the "Share" button the panel needs to be dismissed in order to reproduce the issue.
- Clicking anywhere else on the page will change the focus and the button will no longer be highlighted.
- Here is a screen recording with the issue:
![hover states still appear while buttons are not hovered](https://cloud.githubusercontent.com/assets/18304511/26397376/c3b43712-407e-11e7-87de-372883a062d2.gif)

**Comment by johngruen** [comment]
@ianb yeah this is bound up with that other issue; i think we need to go ahead and componentize each card so we can pass state down to the buttons
