### ISSUE TITLE
Icon colors fix

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#2886]
In the shot index page, the "download", "share" and "delete" icon has three different states: normal, hover, active. According to the spec the color should be:

normal: #9b9b9b
hover: #00d1e6
active: #009ec0

Currently, I think the hover and active color are switched, and the normal color is darker than it should be.

Spec:
![image](https://cloud.githubusercontent.com/assets/8919308/26435134/8f06adda-413f-11e7-8a4d-0898b04e796f.png)

Current:
![image](https://cloud.githubusercontent.com/assets/8919308/26435144/aa849eb4-413f-11e7-9402-4bf78f28905c.png)

**Comment by johngruen** [comment]
I'll pick this up and sprite-ify all the icons to boot

**Comment by johngruen** [comment]
This is fixed
