### ISSUE TITLE
Dark Theme Add-on Icons

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2887]
@6a68 attaching files for dark theme support; would be cool to make this work.

https://www.dropbox.com/sh/yihdgjly9f48hcs/AAASDtIncKs2pIs1WvXOqb8Fa?dl=0

## See comments below for updates.

**Comment by ianb** [comment]
According to [Bug 1329242](https://bugzilla.mozilla.org/show_bug.cgi?id=1329242) this is not yet possible (since the bug is still open)

**Comment by MikkCZ** [comment]
The bug is fixed now. ;)

**Comment by jonathanKingston** [comment]
@MikkCZ the code isn't in Nightly yet.

**Comment by jonathanKingston** [comment]
@MikkCZ I lied, it appears if you don't set all the same icon sizes the default one wins even if setting bigger ones.

**Comment by johngruen** [comment]
So the current dark theme icon support in nightly only works from the Manifest...

Something like this works:
```
  "browser_action": {
    "default_icon": "icons/icon-32.svg",
    "theme_icons": [{
      "light": "icons/icon-32.svg",
      "dark": "icons/icon-32-white.svg",
      "size": 32
    }]
  }
```
Unfortunately, we use `browserAction.setIcon(...)` to change the browserAction dynamically. This API does not support theme-dependent icons.

here's the closed issue for adding theme support to the manifest:
https://bugzilla.mozilla.org/show_bug.cgi?id=1329242

here's a new bug tracking work on letting svg icons use `fill="context-fill"` from inside web extensions..

**Comment by johngruen** [comment]
Status update: looks like there's a little four line patch coming in for this. I'll request uplift when it lands and go stir the pot a bit.

**Comment by johngruen** [comment]
Well, nothing is easy.

- https://bugzilla.mozilla.org/show_bug.cgi?id=1377302 got landed, but it turns out that the ability to context paint is behind a boolean pref that's defaulted to false:
- Now there's this asking of moz-extension assets to get access, but there's some pushback in the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1379464

**Comment by johngruen** [comment]
I think we're now good here
