### ISSUE TITLE
Cannot resize screeshot crop area with touch on Microsoft Surface

### ISSUE THREAD

**Issue by vladikoff** [mozilla-services/screenshots#2888]
## STR

![](http://v14d.com/i/592847810f383.jpg)

## Actual

The controls do not interact with the finger

## Expected

Should be able to resize using fingers

Nightly 55, May 26

**Comment by johngruen** [comment]
Ugh

**Comment by johngruen** [comment]
@vladikoff is gonna help me out with this tomorrow

**Comment by vladikoff** [comment]
I looked at this a bit and seems like there isn't a "one line" fix for this, will need to add touch event support to the UI resize logic. It gets a little crazy because you can have multiple touch points. Will let you know how it goes!

**Comment by johngruen** [comment]
@vladikoff want me to assign you?

**Comment by vladikoff** [comment]
@johngruen ok!

**Comment by johngruen** [comment]
\o/

**Comment by johngruen** [comment]
@vladikoff making progress?

**Comment by vladikoff** [comment]
When I looked at this it seemed like a lot of work to rewire the cropper to use touch events. It was also hard to debug. Maybe now that is in Firefox it will be easier to hack on it. Not sure when I will get time to look at this again though :(

**Comment by rugk** [comment]
Also affects Linux, of course. See https://github.com/mozilla-services/screenshots/issues/4057.

**Comment by vladikoff** [comment]
@johngruen could you assign me from this, I won't have time to fix this up :(

**Comment by rugk** [comment]
Fixed or what?
