### ISSUE TITLE
[RTL] Inteface is reversed

### ISSUE THREAD

**Issue by yarons** [mozilla-services/screenshots#2898]
When trying to take screenshots with the tool I've noticed that the message that appears on the shade is reversed:
<img width="558" alt="screen shot 2017-05-28 at 15 56 22" src="https://cloud.githubusercontent.com/assets/406826/26529233/f5baad38-43c4-11e7-939b-d8290b538a28.png">

**Comment by johngruen** [comment]
@yarons, can you clarify what's incorrect here? The RTL copy looks correct to me

**Comment by arashm** [comment]
@johngruen The dot at the end of the sentence is on the right, that's a sign that the interface is LTR. It should be at the end of the sentence, on the left.
