### ISSUE TITLE
Dismissing the screenshot leads to an error message on Mac

### ISSUE THREAD

**Issue by yarons** [mozilla-services/screenshots#2899]
If I'm not taking the screenshot but ignoring it I see a message saying there was an error and the devlopers are not sure what happened and I'm being asked to try again or to try a different page just seconds after dismissing:
<img width="334" alt="screen shot 2017-05-28 at 16 30 49" src="https://cloud.githubusercontent.com/assets/406826/26529252/64e2e70c-43c5-11e7-8a7a-5c594337a4a9.png">

**Comment by 6a68** [comment]
@yarons Are you still seeing this bug? If so, could you provide some steps to reproduce the bug? Also, would you mind trying to update to the latest Nightly and see if this bug still occurs?

**Comment by yarons** [comment]
@6a68 it looks OK now, thanks.
