### ISSUE TITLE
Removing the icon does not remove context-menu

### ISSUE THREAD

**Issue by metasieben** [mozilla-services/screenshots#2901]
After removing the Icon from the toolbar/overflow area the context-menu should also be removed, similarly to how removing the Pocket - addon is handled.

Currently only setting >extensions.screenshots.disabled< removes the context-menu.

**Comment by johngruen** [comment]
@metasieben not sure why that would be the expected behavior...can you provide an example where moving a an add-on out of the toolbar removes the context menu option

**Comment by SoftVision-CiprianMuresan** [comment]
@johngruen, I don't know of an add-on that does this. But if you have the "Share this Page" feature in the toolbar or menu, you have an extra context menu option regarding share. If the button is removed from the toolbar and menu, the context menu option also disappears.
![sharethispage](https://cloud.githubusercontent.com/assets/18304511/26584273/e768f702-4550-11e7-9566-3ecc1e7e0be1.png)

On the other hand, doing the same with uBlock Origin still blocks ads on pages.

**Comment by wresuolc** [comment]
We have some custom handling right now for the context menu, but by 57 that will all be controlled by web extensions and we'll be using that.  We're going to close this in the mean time. Thanks
