### ISSUE TITLE
[Enhancement] "Remove All Data" link should be grayed out if there are no saved shots

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2903]
[Affected versions]:
- Firefox 53.0.3 and up
- Screenshots 8.0.4796

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (8.0.4796) custom build is installed on a new clean profile.
- Don't have any saved shots.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Firefox Screenshots button from browser toolbar.
3. Click the "Skip" button down the Onboarding tour.
4. Click on "My shots" button. 
5. Hover and click the "Remove All Data" link from the footer of the page.

[Expected result]:
- "Remove All Data" should be greyed out if no shot is saved and displayed on "My Shots" page.

[Actual result]:
- "Remove All Data" link is clickable and if clicked, it redirects the user to the "Leave Screenshots" page.

[Notes]:
- Maybe there should be a more relevant name for the "Remove All Data" option - since the user is redirected to another page where is informed that all his saved shots can be erased, "Remove All My Shots" sound a little more closer to deleting data flow.
- Please see the following screenshot:

![no shots](https://cloud.githubusercontent.com/assets/26000308/26554009/e0463986-4496-11e7-86d6-6a4e64476c99.png)

**Comment by wresuolc** [comment]
Probably a good first bug, but marking needs:product to clarify the "remove all data" string

**Comment by johngruen** [comment]
how about we hide it altogether?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
