### ISSUE TITLE
The "extensions.screenshots.system-disabled" pref is no longer available on latest Nightly builds

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2904]
[Affected versions]:
- Nightly 55.0a1 (2017-05-29, Build ID: 20170526085515)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly (55.0a1, 2017-05-29) build installed and create a new profile. 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to "about:addons" page and click the "I accept the risk!" button.
3. Search the "extensions.screenshots.system-disabled" pref.

[Expected result]:
- The pref is available and is set to false.

[Actual results]:
- The pref is no longer available.

[Notes]:
- Here is a screen shot with the issue:
![pref](https://cloud.githubusercontent.com/assets/19226534/26555909/26fd7a98-44a0-11e7-88a7-285b55efcc0a.png)

**Comment by wresuolc** [comment]
The pref is still available, they just have to create it themselves.  I don't think we've ever created it for them.  Also note extensions.screenshots.disabled works as well and won't be flipped back when we launch.

**Comment by SoftVision-CosminMuntean** [comment]
> The pref is still available, they just have to create it themselves. I don't think we've ever created it for them. 

Yes, but before Screenshots became enabled by default in Nightly the "extensions.screenshots.disabled" pref was already created and available in the "about:config" page. 
Now if you want to disable Screenshots you have to create the pref.

**Comment by wresuolc** [comment]
The prefs still work, we don't think it's important that it exists by default.  Closing this
