### ISSUE TITLE
"GitHub" and "Twitter" buttons from the footer of the onboarding page, wrongly redirects to "https://screenshots.firefox.com/" page.

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2905]
[Affected versions]:
- Nightly 55.0a1
- Screenshots (8.0.0)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Firefox Screenshots (8.0.0) build is installed on a new clean profile.
- The Onboarding tour was already visited.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to "https://screenshots.firefox.com/" page.
3. From the footer of the page click the "GitHub" or "Twitter" link button. 
4. Observe the browser behavior.

[Expected result]:
- A new tab is opened and you are successfully redirected to the specific pages.

[Actual results]:
- A new tab is opened and you are wrongly redirected to "https://screenshots.firefox.com/" page.

[Notes]:
- Here is a screen recording with the issue:
![twitter and github](https://cloud.githubusercontent.com/assets/19226534/26555960/688cc48c-44a0-11e7-96c1-90f6f98012da.gif)

**Comment by pdehaan** [comment]
Ref: [/server/src/pages/homepage/view.js:658-661](https://github.com/mozilla-services/screenshots/blob/9a97377169fd720d1ca1029f7f12c63abcc6a24e/server/src/pages/homepage/view.js#L658-L661):

```html
<div className="social-links">
  <a href="#" target="_blank" className="link-icon github" title="GitHub"></a>
  <a href="#" target="_blank" className="link-icon twitter" title="Twitter"></a>
</div>
```

**Comment by pdehaan** [comment]
@johngruen +/- @ianb Do you remember what our Twitter account is for Screenshots?
I found #2465 which mentioned `@MozillaPageShot` (w/ zero tweets) but also mentioned `@FirefoxScreenshots` which seems to give me a 404, so not sure if that was the final name either.

**Comment by pdehaan** [comment]
The answer is [@FxScreenshots](https://twitter.com/FxScreenshots). I can PR this shortly.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Nightly build and the issue is no longer reproducible, A new tab is opened and you are successfully redirected to the specific pages. Marking as verified.
