### ISSUE TITLE
Typo in landing-screenshots_image_04.svg image on homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2906]
Found in https://screenshots.stage.mozaws.net/__version__ (94357b8):

```js
{
  source: "https://github.com/mozilla-services/screenshots/",
  description: "Firefox Screenshots application server",
  version: "8.0.0",
  buildDate: "May 26, 2017 18:34:41 UTC",
  commit: "94357b8",
  contentOrigin: "screenshotsusercontent.stage.mozaws.net",
  commitLog: "https://github.com/mozilla-services/screenshots/commits/94357b8",
  unincludedCommits: "https://github.com/mozilla-services/screenshots/compare/94357b8...master",
  dbSchemaVersion: 16
}
```

---

### Steps to reproduce:
1. Visit https://screenshots.stage.mozaws.net/# or dev using Chrome or something.

### Actual results:

[/static/img/landing-screenshots_image_04.svg](https://screenshots.stage.mozaws.net/static/img/landing-screenshots_image_04.svg) says "screenshot.firefox.com" but should be pluralized:

<img width="567" alt="firefox_screenshots" src="https://cloud.githubusercontent.com/assets/557895/26561728/7d33598a-4475-11e7-8b18-4278c99c5dc4.png">

**Comment by youwenliang** [comment]
@pdehaan Fang will update this image, thanks for spotting that.

**Comment by SoftVision-PaulOiegas** [comment]
@pdehaan Am I the only one who still sees the issue on both dev and stage servers?

**Comment by pdehaan** [comment]
@SoftVision-PaulOiegas Actually, I see it too, but am having some trouble understanding why.
Looking at the [/\_\_version\_\_](https://screenshots.dev.mozaws.net/__version__) route, it looks like the build on https://screenshots.dev.mozaws.net/ is from **June 26, 2017 13:20:33 UTC**.

Not sure why the latest [29 commits](https://github.com/mozilla-services/screenshots/compare/8.1.0-235-g329b382...master) aren't rebuilding on the dev server, or if something else is busted.

/cc @ianb
