### ISSUE TITLE
Getting started link on homepage jumps to top of page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2907]
Found in https://screenshots.stage.mozaws.net/__version__ (94357b8):

```js
{
  source: "https://github.com/mozilla-services/screenshots/",
  description: "Firefox Screenshots application server",
  version: "8.0.0",
  buildDate: "May 26, 2017 18:34:41 UTC",
  commit: "94357b8",
  contentOrigin: "screenshotsusercontent.stage.mozaws.net",
  commitLog: "https://github.com/mozilla-services/screenshots/commits/94357b8",
  unincludedCommits: "https://github.com/mozilla-services/screenshots/compare/94357b8...master",
  dbSchemaVersion: 16
}
```

---

### Steps to reproduce:
1. Visit https://screenshots.stage.mozaws.net/
1. Click on the "Get Started" link in the header.

### Actual results:
The link goes to `"#"` which does nothing. Not sure if this should go to `href="#section-1"` or something a bit more appropriate.

<img width="1181" alt="firefox_screenshots" src="https://cloud.githubusercontent.com/assets/557895/26561991/8d08645c-4477-11e7-83b0-fa65a94e821c.png">

Ref: [/server/src/pages/homepage/view.js:577](https://github.com/mozilla-services/screenshots/blob/9a97377169fd720d1ca1029f7f12c63abcc6a24e/server/src/pages/homepage/view.js#L577):

```html
<a href="#">Get Started</a>
```

**Comment by ianb** [comment]
Dup of #3065
