### ISSUE TITLE
Footer links inconsistent on homepage vs 404 page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2908]
Found in https://screenshots.stage.mozaws.net/__version__ (94357b8):

```js
{
  source: "https://github.com/mozilla-services/screenshots/",
  description: "Firefox Screenshots application server",
  version: "8.0.0",
  buildDate: "May 26, 2017 18:34:41 UTC",
  commit: "94357b8",
  contentOrigin: "screenshotsusercontent.stage.mozaws.net",
  commitLog: "https://github.com/mozilla-services/screenshots/commits/94357b8",
  unincludedCommits: "https://github.com/mozilla-services/screenshots/compare/94357b8...master",
  dbSchemaVersion: 16
}
```

---

### Steps to reproduce:
1. Visit https://screenshots.stage.mozaws.net/
1. Look at the various footer links and layout.
1. Visit https://screenshots.stage.mozaws.net/forum (should currently 404; see #2909)
1. Look at the various footer links and layout.

### Actual results:

The homepage footer is:
1. **Legal** &mdash; https://www.mozilla.org/about/legal/
1. **Privacy** &mdash; [/privacy](https://screenshots.stage.mozaws.net/privacy)
1. **Terms** &mdash; [/terms](https://screenshots.stage.mozaws.net/terms)
1. **Cookies** &mdash; https://www.mozilla.org/privacy/websites/#cookies
1. **Forum** &mdash; [/forum](https://screenshots.stage.mozaws.net/forum)
1. (GitHub logo) &mdash; `href="#"` (See #2905)
1. (Twitter logo) &mdash;  `href="#"` (See #2905)

<img width="1028" alt="firefox_screenshots" src="https://cloud.githubusercontent.com/assets/557895/26562387/b3f03c72-447a-11e7-82ca-0f59408ecbef.png">

---

The 404 page footer is:
1. (Mozilla logo) &mdash; https://www.mozilla.org/
1. **Terms** &mdash; https://www.mozilla.org/about/legal/terms/services/
1. **Privacy Notice** &mdash; https://www.mozilla.org/privacy/firefox-cloud/
1. **Report IP Infringement** &mdash; https://www.mozilla.org/about/legal/report-infringement/
1. **Give Feedback** &mdash; https://discourse.mozilla-community.org/c/test-pilot/page-shot
1. **GitHub** &mdash; https://github.com/mozilla-services/screenshots

<img width="1405" alt="page_not_found" src="https://cloud.githubusercontent.com/assets/557895/26562404/d3561cd0-447a-11e7-8263-e6bd237a26eb.png">

### Expected results:
The footers should be a bit more consistent.

**Comment by youwenliang** [comment]
I also notice the Mozilla logo is not showing, probably need to fix the image url.
