### ISSUE TITLE
Homepage makes no mention of Mozilla

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#2910]
Found in https://screenshots.stage.mozaws.net/__version__ (94357b8):

```js
{
  source: "https://github.com/mozilla-services/screenshots/",
  description: "Firefox Screenshots application server",
  version: "8.0.0",
  buildDate: "May 26, 2017 18:34:41 UTC",
  commit: "94357b8",
  contentOrigin: "screenshotsusercontent.stage.mozaws.net",
  commitLog: "https://github.com/mozilla-services/screenshots/commits/94357b8",
  unincludedCommits: "https://github.com/mozilla-services/screenshots/compare/94357b8...master",
  dbSchemaVersion: 16
}
```

---

### Steps to reproduce:
1. Browse to https://screenshots.stage.mozaws.net/ (without the add-on installed -- or in Chrome or whatever).
1. Ctrl+F for "Mozilla".

### Actual results:
Zero mentions of "Mozilla". If you go to a 404 page (https://screenshots.stage.mozaws.net/forum) there is a Mozilla logo in the left side of the footer.
But there are 5 mentions of "Firefox" on the homepage.

**Comment by johngruen** [comment]
@pdehaan nice spot, this page still requires a bit of work

**Comment by pdehaan** [comment]
Ah, just noticed this in my browser console type thing:

```
GET https://screenshots.stage.mozaws.net/static/img/landing-Moz-logo.svg 404 (Not Found)
```

Naturally that fails, because I don't see a _landing-Moz-logo.svg_ in the [/static/img/](https://github.com/mozilla-services/screenshots/tree/master/static/img) directory.

**Comment by wresuolc** [comment]
This is fixed on dev: https://screenshots.dev.mozaws.net/

**Comment by 6a68** [comment]
yup, it's on dev: https://screenshots.firefox.com/q7f9wUXbQCKRuFZm/screenshots.dev.mozaws.net
