### ISSUE TITLE
There is a noticeable delayed when deleting a shot or performing a search on "My Shots" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2912]
[Notes]:
- This issue is not reproducible on stage and dev servers. I am not sure if this happens due to the fact that the production server is not up to date or there is another issue.

[Affected versions]:
- Nightly 55.0a1
- Screenshots 8.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build installed and create a new profile.
- Have Screenshots enabled and multiple shots saved on the created profile. 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to "https://screenshots.firefox.com/shots" page.
3. Hover a shot and choose to delete it.
4. Notice the time until the shot is deleted from "My Shots" page.
5. Perform a search and notice the time until the results are displayed.

[Expected result]:
Step 4. The shot is deleted almost instantly.
Step 5. The results are displayed almost instantly.

[Actual results]:
Step 4. It takes about ~5-6s until the shot is removed.
Step 5. It takes about ~5-6s until the results are shown.

[Notes]:
- Here is a screen recording with the issue:
![delay](https://cloud.githubusercontent.com/assets/19226534/26582940/acaf9328-454b-11e7-9dae-25cf7e49f26d.gif)

**Comment by wresuolc** [comment]
Putting in 55 for the performance question.  The new UI changes don't block.

**Comment by johngruen** [comment]
Maybe we `display:none` search until it works well since nobody uses it
