### ISSUE TITLE
Errors are not being reported to Sentry

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2920]
We have a [buildSettings](https://dxr.mozilla.org/mozilla-central/source/browser/extensions/screenshots/webextension/build/buildSettings.js) pointing to our [prod Sentry](https://sentry.prod.mozaws.net/operations/pageshot-prod/), but I don't see any errors there.  This is implausibly quiet.

**Comment by 6a68** [comment]
can you manually trigger an error, say, by turning off your network connection, then look for a sentry ping attempt in the devtools network tab?

**Comment by 6a68** [comment]
I'll take a look at this

**Comment by ianb** [comment]
FYI, I double-checked the buildSettings.js setting, and it is correct

**Comment by 6a68** [comment]
I exported current master into current mozilla-central, built firefox, and Sentry pings are being sent to the correct URL (`https://sentry.prod.mozaws.net/api/139/store/?` followed by an enormous query string).

The easiest way to test is to switch off wifi, take a screenshot, and try to save it to the server. 

This doesn't explain why we aren't seeing anything in the Sentry dashboard, but I did observe that old profiles have an IndexedDB error on today's Nightly, which causes Screenshots to never load, instead crashing on startup.

I'll try next using the ./bin/run-addon approach.

**Comment by 6a68** [comment]
I can also confirm that Sentry endpoints are pinged if the SCREENSHOTS_SENTRY env var is set when you invoke ./bin/run-addon. Using this incantation:

```sh
SCREENSHOTS_SENTRY="https://97d8afa496f94764ae255e739b147f4b@sentry.prod.mozaws.net/139" ./bin/run-addon --bootstrap
```

I was able to turn off wifi, try to save a hsot, then observe a POST attempt to the Sentry endpoint.

**Comment by 6a68** [comment]
I'm waiting to get Sentry access. I"ll continue debugging once I can view the dashboard.

**Comment by 6a68** [comment]
Seems like the issue may be that the addon pings are coming from a randomish moz-extension URL, and may be getting dropped by sentry.

Removing the scary firefox-55 blocker label 🎉

**Comment by ianb** [comment]
Sadly it looks like request from the background page have no referrer or origin, so there's nothing to whitelist in Sentry. I'm looking into whether we should just ship with the Sentry Private DSN
