### ISSUE TITLE
Don't capture DOM strings in add-on

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2931]
Since they may leak information in unintended ways, we should not pass the strings captured in screenshot extraction to non-owner views.

**Comment by ekr** [comment]
Per my comments in e-mail, I don't think we should be uploading them at all. The user just agreed to upload the rectangle.

**Comment by ianb** [comment]
Implementation note: to remove collection entirely we need to remove the call to `util.captureEnclosedText()` in `shooter.js`

**Comment by 6a68** [comment]
I can take this. make it configurable via buildSettings
