### ISSUE TITLE
The page enters in a refresh loop if "My shots" page is opened in a container tab or Private Window 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2939]
[Affected versions]:
- Firefox 53.0.3 and up
- Screenshots 8.2.1970

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build installed and create a new profile.
- Have multiple shots saved on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Open a new tab and click the "Screenshots" button from toolbar.
3. Click on one of the saved shots.
4. Right click on "My shots" button.
5. Click on "Open Link in New Container Tab".
6. Click on one of the Containers and observe the browser's behavior.
7. Right click on "My shots" button.
8. Click on "Open Link in New Private Window" and observe the browser's behavior.

[Expected result]:
6. "My shots" page is opened in a new container tab displaying all saved shots 
**OR**
An error message stating that saved shots can not be displayed should appear.
8. "My shots" page is opened in new Private Window displaying all saved shots 
**OR**
An error message stating that saved shots can not be displayed should appear.

[Actual result]:
6. The interstitial page is loaded in a new container tab, but the page will enter in a refresh loop and the login never happens.
8. The interstitial page is loaded in the new Private Window, but the page will enter in a refresh loop and the login never happens.

[Notes]:
- Please see the following screencast:
![context menu](https://cloud.githubusercontent.com/assets/26000308/26639250/08bb891a-462d-11e7-8e7a-240d85274943.gif)

**Comment by wresuolc** [comment]
If we can't fix this, let's at least put an error on the page saying we don't work

**Comment by 6a68** [comment]
@johngruen Any thoughts on what error message we could show here?

We can set a query string when we reload the page, and give up after reloading once or twice, but I'm not sure how we'd want to message this to the user.

**Comment by 6a68** [comment]
John's suggestion: if we can't auth after one or two tries, just redirect to homepage

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev and stage servers. Marking as verified.
