### ISSUE TITLE
Doesn't work on sites like scrollmagic.io

### ISSUE THREAD

**Issue by dehghani-mehdi** [mozilla-services/screenshots#2945]
Hey, thanks for the tool, but so far it doesn't add anything useful to prev. built-in screenshot tool.
Doesn't support sites that use scroll animations, for ex. [scrollmagic.io](http://scrollmagic.io/)

**Comment by johngruen** [comment]
@dehghani-mehdi thanks for the report! unfortunately sites that use intense parallax scrolling like scrollmagic cannot be supported since we use the canvas to render images and do no call any underlying scroll events.

**Comment by dehghani-mehdi** [comment]
@johngruen I think using that kind of effect is very common and will be more (_I'm web developer, that way I said that_), so your plugin doesn't so much if you cut support for that king of websites.
