### ISSUE TITLE
Resolve issues with Screenshots causing the customisable widgets to not be in their default setting (and fix FF mochitests with screenshots enabled.

### ISSUE THREAD

**Issue by Standard8** [mozilla-services/screenshots#2946]
Splitting this out from #2348. Currently browser_BrowserUITelemetry_defaults.js fails when Screenshots is enabled during tests.

This is indicating that the restore defaults button for the customisable UI doesn't work correctly due to Screenshots being enabled.

xref https://bugzilla.mozilla.org/show_bug.cgi?id=1358097 and https://bugzilla.mozilla.org/show_bug.cgi?id=1247045

**Comment by Standard8** [comment]
Note, when this is resolved, we should also enable screenshots in unit tests in mozilla-central ([bug 1355569](https://bugzilla.mozilla.org/show_bug.cgi?id=1355569).

**Comment by 6a68** [comment]
@Standard8 It looks like screenshots is going to be shuffled into the page action ellipsis menu by 57, so is it even worth worrying about the toolbar button tests?

**Comment by Standard8** [comment]
We could certainly wait and see. It might be that we'll still need to fix a new test. In any case, we'll need to do at least something to resolve bug 1355569 so that we get screenshots enabled for tests.

**Comment by ianb** [comment]
Since we are only in the pageAction menu now, this probably isn't an issue anymore.
