### ISSUE TITLE
Create function in bootstrap.js that launches screenshotting

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2947]
For the Page Action menu, there has to be some way besides the browserAction to launch a screenshot. I believe in the lazy-button experiment there was an example of using postMessage for this.

**Comment by 6a68** [comment]
Page actions are registered in the manifest, just like browser actions, so I'm not sure why we would launch anything from bootstrap.js?

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/page_action

**Comment by ianb** [comment]
I don't think the Photon Page Actions are going to use the WebExtension page_actions, at least in the first revision.

**Comment by 6a68** [comment]
For reference, here's the metabug for the photon page action changes: https://bugzilla.mozilla.org/show_bug.cgi?id=1352697

And here's the bug for the page action changes https://bugzilla.mozilla.org/show_bug.cgi?id=1366041

**Comment by 6a68** [comment]
OK, adding more context, from https://bugzilla.mozilla.org/show_bug.cgi?id=1366041#c5:

> Status update:
> 
> Ultimately the plan is apparently to automatically list web extensions in the page action menu, or at least those that have page actions.  Screenshots is one such extension.  But I'd like to avoid all that for Photon's initial release and instead just hardcode a screenshots menu item that calls into the extension.
> 
> That seems pretty simple in concept, but Ian and Jared say that they're still figuring out how to load the extension, and that any changes I make will probably be broken pretty quickly.  My impression is that we may have to first load the extension before calling into it when the user clicks the menu item.
> 
> So I'll wait for that to be resolved before working on this.

**Comment by 6a68** [comment]
Based on the bug, it seems like adw is planning to do this. I added some context and implementation suggestions to the bugzilla bug: https://bugzil.la/1366041#c6

Not sure there's anything for us to do here, but I'll leave the bug open just in case.

**Comment by ianb** [comment]
This work has been finished (a while ago)
