### ISSUE TITLE
9.x.0 deployment notes

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2951]
Some notes to remember for the 9.x.0 deployment:

* Set `EXPECT_PROTOCOL` to `https`
* Set `EXTRA_CONTENT_ORIGIN` to `pageshot-usercontent.net`

**Comment by 6a68** [comment]
cc @relud

**Comment by johngruen** [comment]
* We should add whatever server config is necessary to enable GA on the screenshots domain.

**Comment by ianb** [comment]
Maybe we can add some of this via the [config files](https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-Configuration) pattern?  I only half-understand it from the documentation.

**Comment by relud** [comment]
let's stick with just requesting me to add configs. it is easy, and doesn't take much time, as long as i get to it quickly. I have a question about the EXTRA_CONTENT_ORIGIN config and exactly what it does. based on the PR, it adds that domain to the CSP header, but I thought that pageshot-usercontent.net wasn't actually in use, and images were hosted on pageshot.net

**Comment by ianb** [comment]
Empirically pageshot-usercontent.net is where pageshot.net images are hosted right now.

**Comment by relud** [comment]
Set `EXPECT_PROTOCOL` to `https` this is already done for screenshots.
