### ISSUE TITLE
Create pref to disable Screenshots in Beta

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2953]
I think we want to add something to [`libpref/init/all.js`](https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js) like:

```js
#ifdef NIGHTLY_BUILD
pref("extensions.screenshots.system-disabled", false);
#else
pref("extensions.screenshots.system-disabled", true);
#endif
pref("extensions.screenshots.disabled", false);
```

**Comment by 6a68** [comment]
If we do this, I think the file to modify is [`browser/app/profile/firefox.js`](https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js).

**Comment by 6a68** [comment]
Docs: https://wiki.mozilla.org/Platform/Channel-specific_build_defines

**Comment by 6a68** [comment]
Patch opened in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1369824

**Comment by 6a68** [comment]
The patch landed in m-c before 55 branched to Beta, so I think there's nothing left to do here. Closing.
