### ISSUE TITLE
All saved screenshots are deleted after "Page Shot" add-on is installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2954]
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 8.2.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the Nightly try build with Screenshots 8.2.0 installed and create a new profile.
- Have multiple shots saved and Test Pilot installed on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Navigate to "https://testpilot.firefox.com/" and install "Page Shot".
3. Restart the browser.
4. Open a new tab and click the "Screenshots" button from browser toolbar.
5. Observe the "My Shots" page.

[Expected result]:
- All the saved screenshots are displayed.

[Actual results]:
- All the saved screenshots are deleted.

[Notes]:
- I am not sure if this issue is reproducible on Mac Os, because the Nightly try build is broken for Mac.
- Here is a screen recording with the issue: https://goo.gl/KYf6CO

**Comment by wresuolc** [comment]
This is a feature!  We'll take it off Test Pilot shortly to prevent this.
