### ISSUE TITLE
No shots can be saved in the same session after "Out of order" error is displayed on Nightly and Beta

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2957]
[Notes]:
- The error is not displayed anymore if a new screenshots session is started (ESC key or "Close button").
- On the Release version 53.0.3, this issue is not reproducible: the next error is displayed "Index or size is negative or greater than the allowed amount". After resizing the area and clicking the "Save" button, the shot is saved and page preview is opened in new tab.
- On the Pilot version, the area with height/width reduced to the maximum is saved and the page preview is displayed, even though there is no image displayed.

[Affected versions]:
- Firefox Nightly 55.0a1
- Firefox Beta 54.0b12
- Screenshots v. 8.2.1970
- Screenshots from latest Nightly.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build installed and create a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website (www.wikipedia.org).
2. Click the Screenshots button from the main browser toolbar.
3. Select an area with height/width reduced to the maximum.
4. Click on "Save" button.
5. Resize the area horizontally/vertically.
6. Click the "Save" button and observe what happens next.

[Expected result]:
- The user is redirected to the saved shot preview page.

[Actual result]:
- "Out of order. Sorry! We couldn't save your shot. Please try again later" error is displayed.

[Additional Notes]:
- Please see the following screencast:

![out of order](https://cloud.githubusercontent.com/assets/26000308/26731907/460c01ae-47be-11e7-9741-21b9aea82707.gif)

**Comment by ianb** [comment]
Very helpful bug report, this uncovered a number of issues!

**Comment by SoftVision-CarmenFat** [comment]
I have retested this issue with latest Screenshots (dev build 06.06.2017) and the issue is no longer reproducible: 
- "Your selection is too small" error is displayed after clicking the "Save" button for a zero area selection;
- After displaying the error above, the "Save" button regains its functionality if the selected area is resized.
