### ISSUE TITLE
After "Page Shot" migration, "Info is undefined" error is displayed, if a Screenshots page is focused and the browser is restated using the "restart" command in "Developer Toolbar"

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#2958]
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 8.2.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox version where Screenshots is not installed and create a new profile.
- Have the "Show you windows and tabs from last time" option set on "about:preferences" page in General section.
- Have Test Pilot and Page Shot installed on the created profile.

[Steps to reproduce]:
1. Open the Nightly try build with Screenshots 8.2.0 installed with the profile from prerequisites.
2. Wait until the "Page Shot" migration happens.
3. Open the "Developer Toolbar" (Shift + F2), type the "restart" command and press "Enter" key.
4. After the browser is opened, navigate to any website and save a selection.
5. Restart again the browser using the "restart" command.
6. After the browser is restarted observe the behavior.

[Expected result]:
- No errors are displayed.

[Actual results]:
- "TypeError: info is undefined" error is displayed. 

[Notes]:
- I haven't managed to reproduce this issue on Mac Os.
- If no error are displayed, restart again the browser using the "restart" command in the "Developer Toolbar".
- Here is a screen recording with the issue: https://goo.gl/rN4xaA.
- Here is a screenshot with browser console errors:
![info is undefined](https://cloud.githubusercontent.com/assets/19226534/26732380/1535e732-47c0-11e7-82a3-d5b29a1c9850.png)

**Comment by ianb** [comment]
The migration is a red herring here, it's just a matter of the page being loaded in session-restore, and a race condition in main.js around authentication.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on the latest Nightly (Build ID: 20170607030206) build with latest Screenshots (9.0.0) version and is no longer reproducible. Marking as verified.
