### ISSUE TITLE
Shot can not be restored when expiring after 1 month or 2 weeks

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#2960]
[Affected versions]:
- Nightly 55.0a1
- Beta 54.0b12
- Screenshots 8.2.0
- Screenshots 6.6.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Have the latest Nightly build and Screenshots v. 8.2.0 installed and create a new profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to any website.
2. Click the "Screenshots" button from browser toolbar.
3. Perform a selection and save it.
4. Click on the "expires in 14 days" button.
5. From the drop down, click on "1 Month" option.
6. Click on "Save" button.
7. Change the System Time to be 1 month in the future and refresh the page.
8. Click the "restore for 14 days" button and observe what happens next.

[Expected result]:
- The user is redirected to the saved shot preview page and the expire time is extended to 14 days.

[Actual result]:
- The page is refreshed and "If you do nothing, this shot will be permanently deleted in 3 days ago." message is displayed.

[Additional Notes]:
- "2 weeks" option is also broken and cannot be restored following the same scenario. 
- Please see the following screencast:

![expire shot](https://cloud.githubusercontent.com/assets/26000308/26734716/bb332c4c-47c7-11e7-9d2b-4f7227998d28.gif)

**Comment by ianb** [comment]
Maybe the real bug here is that we expire a shot based on the local clock, even though the server isn't expiring it. Then the form doesn't work. We should be setting an expired flag in `pages/shot/model.js` instead of doing a date check in the view.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
