### ISSUE TITLE
Error: Failed assertion: Bad favicon URL:

### ISSUE THREAD

**Issue by tynopex** [mozilla-services/screenshots#2968]
When I try to use screenshots on a file:// URI, I get |Error: Failed assertion: Bad favicon URL:| reported in the screenshot pop-up and no screenshot is saved.

Steps to Reproduce:
1) Create empty file called index.html
2) Open in FF Nightly
3) Take screenshot of view

Expected:
- Screenshot saved

Actual:
- Notification with |Error: Failed assertion: Bad favicon URL:|

**Comment by ianb** [comment]
[Associated Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/612018/)

**Comment by SoftVision-CosminMuntean** [comment]
I have also encountered this error when I tried to save a selection on the following video: "http://techslides.com/demos/sample-videos/small.mp4". 
I have also managed to reproduce this using the provided steps by tynopex.

- Here is a screenshot with browser console errors:
![bad favicon](https://user-images.githubusercontent.com/19226534/26925704-7dbbe5e4-4c53-11e7-9efc-867e05e0a8a2.png)
- Here is a screen recording with the issue:
![bad favicon](https://user-images.githubusercontent.com/19226534/26925711-84440586-4c53-11e7-925e-ce4e4a87e878.gif)

**Comment by ianb** [comment]
[Related Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/612188/). We need to fix the error message, probably the error simply shouldn't be ignored.

**Comment by ianb** [comment]
This seems possibly related to #2902 (maybe not the important issue from that, but one of the issues)
