### ISSUE TITLE
Investigate "Missing host permission for the tab"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2978]
In [this Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/612019/) there's an exception, it appears to be coming from `browser.tabs.executeScript`:

```js
  exports.unloadIfLoaded = function(tabId) {
    return browser.tabs.executeScript(tabId, { # this line
      code: "this.selectorLoader && this.selectorLoader.unloadModules()",
      runAt: "document_start"
    }).then(result => {
      return result && result[0];
    });
  };
```

I wonder if there are kinds of pages that generate this error instead of the error we catch?

**Comment by SoftVision-CosminMuntean** [comment]
The "Missing host permission for the tab" error appears in browser console  when you try to use Screenshots on Test Pilot pages or on "about: *" pages. 
Here are the steps to reproduce the error:

[Prerequisites]:
- Have the latest Nightly (2017-06-7) build with Screenshots 9.0.0 installed and create a new profile.
- Screenshots Onboarding tour was already visited on the created profile.

[Steps to reproduce]:
1. Open the Nightly with the profile from prerequisites.
2. Navigate to "about:support" page or to "https://testpilot.firefox.com/" website.
3. Click the "Screenshots" button from browser toolbar.
4. Open browser console (CTRL+SHIFT+J) and observe the errors.

[Expected results]:
- No errors are displayed in browser console errors.

[Actual results]:
- A "Missing host permission for the tab" error is displayed in browser console.

[Notes]:
- Here is screen recording with the issue: https://goo.gl/Ln8IGH
- Here is a screenshot with browser console errors:
![host permition](https://user-images.githubusercontent.com/19226534/26919020-e30e76e4-4c3c-11e7-9750-67c82b2bbaac.png)

**Comment by David263** [comment]
I'm still getting it. I have "activeTab" permission set in the Manifest file, but not "<all_urls>". I thought that activeTab was sufficient to inject a content script. Can someone please pay attention and help?
