### ISSUE TITLE
Investigate "TypeError: /.*\//.exec(...) is null"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2979]
In [this Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/611974/), a traceback:

```
resolveUrl@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/build/shot.js:130:16
set favicon@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/build/shot.js:466:13
@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/background/takeshot.js:13:5
watchFunction/<@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/catcher.js:52:16
@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/background/communication.js:25:16
watchFunction/<@moz-extension://0c856cc6-1aaa-4812-ac1e-84ab9cfa7370/catcher.js:52:16
```

The interesting bit is `shot.js:466`:

```js
      val = resolveUrl(this.url, val); # in Shot set favicon
```

Really we should be handling this better, as `this.url` isn't a good base because we've removed `fullUrl` capture.

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this error when I have tired to save a selection on a local image opened in Nightly.

Here is a screenshot with browser console errors:
![local images](https://user-images.githubusercontent.com/19226534/26921750-a3f15a2c-4c45-11e7-8d18-7e61edd30228.png)

Here is a screen recording with the issue:
![local image 2](https://user-images.githubusercontent.com/19226534/26921770-b3867fe4-4c45-11e7-9599-e7c189481a51.gif)
