### ISSUE TITLE
Flip the last two slides in onboarding

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#2986]
@ianb can you grab this one, we'll have to flip strings in all the ftl as part of this ask

**Comment by ianb** [comment]
OK, I'll plan to swap `tour{Header|Body}Three` with `tour{Header|Body}Four`; current values (to be sure we're talking about the same thing):

* tourHeaderThree = As You Like it
* tourBodyThree = Save your cropped shots to the Web for easier sharing, or download them to your computer. You also can click on the My Shots button to find all the shots you’ve taken.
* tourHeaderFour = Capture Windows or Entire Pages
* tourBodyFour = Select the buttons in the upper right to capture the visible area in the window or to capture an entire page.

@flodolo : I'm planning to just swap those keys in the properties files for all locales, does that work?

**Comment by flodolo** [comment]
It should work, yes.

Having said that, I know it would be somehow confusing for someone looking at the code, but swapping only the data-l10n-ids in slides.html would also be much safer, given the number of locales enabled.

**Comment by johngruen** [comment]
@niharikak101 #2995 flips the actual images, the work here is simply to flip the string values!
