### ISSUE TITLE
"This Element is null" error is constantly thrown if pressing the escape button while resizing the browser

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#2994]
[Affected versions]:
Firefox 55.0a1 (Build Id:20170608030205)
Firefox Screenshots 9.0.0

[Affected platforms]:
Windows 10 64 bit
Ubuntu 16.04 64bit

[Steps to reproduce]:

1.Open Firefox with a clean profile.
2.Click on the Screenshots button.
3.Dismiss the tutorial.
4.Press the escape button while resizing the browser.

[Expected result]:
Screenshots is successfully closed.

[Actual result]:
An error is thrown with a type error : "This.element is null".

[Additional notes]
Please observe the following video for more information: https://drive.google.com/open?id=0B94iuIVMr-TEREZkSjh6czVDRGM

**Comment by ianb** [comment]
I believe [this Sentry report](https://sentry.prod.mozaws.net/operations/screenshots-addon-prod/issues/612254/) is from this error.

**Comment by ianb** [comment]
I wasn't able to reproduce this, but given the Sentry report and the steps I'm pretty sure I understand and can fix the error.
