### ISSUE TITLE
Zoom in & out in Shot detail page

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#3012]
It's a nice-to-have improvement for the shot detail page. It would be nice to be able to zoom in & out of an image I captured. 

Something like this: https://codepen.io/youwenliang/pen/xqaxXE

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
