### ISSUE TITLE
After Page Shot migration, a "error:connectionClosed" error is displayed in browser console, if a Screenshots page is restored

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3013]
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 9.0.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox version where Screenshots is not installed and create a new profile.
- Have Test Pilot and Page Shot installed on the created profile.

[Steps to reproduce]:
1. Start the latest Nightly build with the profile from prerequisites.
2. Wait until the migration happens, then close the browser.
3. Reopen the browser and navigate to any website and save a selection.
4. Open the Developer Toolbar (Shift+F2).
5. Type the "restart" command and press "Enter".
6. After the browser is reopened, open the browser console (CTRL+SHIFT+J).
7. Observe the errors.

[Expected result]:
- No errors are displayed.

[Actual results]:
- "{ error: "connectionClosed", message: "'getTab' active request packet to '…" }" error is displayed.

[Notes]:
- Even if the error is displayed in browser console, the Screenshots functionality is not affected, works as expected.
- Here is a screen recording with the issue: https://goo.gl/pjhrUw
- Here is a screen shot with browser console:
![connectionclosed](https://user-images.githubusercontent.com/19226534/27035096-cb96d142-4f88-11e7-96ab-4c9e21bb88f6.png)

**Comment by ianb** [comment]
I don't think we care anymore, the migrations happened however they happened and they are done!
