### ISSUE TITLE
late string change

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3024]
We need to update the string to:
> By using Firefox Screenshots, you agree to our {Terms} and {Privacy Notice}.

/cc @ianb @6a68

**Comment by ianb** [comment]
The previous string was:

    termsAndPrivacyNoticeCloudServices =By using Firefox Screenshots, you agree to the Firefox Cloud Services {termsAndPrivacyNoticeTermsLink} and {termsAndPrivacyNoticePrivacyLink}.

@flodolo : should we make a new key (e.g., `termsAndPrivacyNoticeCloudServices2`) for this change?

**Comment by 6a68** [comment]
@ianb Yeah, we need to bump the key ID whenever the string changes. I can do this

**Comment by flodolo** [comment]
Just to confirm that yes, you need a new string ID.
