### ISSUE TITLE
Two Screenshots "enable/disable" prefs are displayed in "about:config" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3028]
[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the latest Nightly build and navigate to "about:config" page.
2. Click the "I accept the risk!" button.
3. Search the "extensions.screenshots" pref.
4. Observe the results.

[Expected result]:
- There is only one pref in order to enable/disable Screenshots.

[Actual results]:
- There are two prefs in order to enable/disable Screenshots.   

[Notes]:
- Here is a screen shot with the list:
![prefs](https://user-images.githubusercontent.com/19226534/27089897-5d92257a-5064-11e7-8a09-8d3f8851f167.png)

**Comment by johngruen** [comment]
Feature, not bug! system-disabled is for roll out and will be removed at the end
