### ISSUE TITLE
about:home is not treated like about:newtab

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3029]
When you try to take a shot on about:newtab it takes you to My Shots, but it doesn't work the same for about:home

**Comment by 6a68** [comment]
about:home is xhtml, about:newtab is html5.

Looks like we don't support xhtml. Here's another example: https://www.w3.org/2000/07/8378/schemas/xhtml1-sample.xml

**Comment by gvanwaelvelde** [comment]
I added about:home to the whitelist and made a pull request.
https://github.com/mozilla-services/screenshots/pull/3088
