### ISSUE TITLE
install.rdf should not link to pageshot.net

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3041]
Noticed tonight that [install.rdf.template](https://github.com/mozilla-services/screenshots/blob/master/addon/install.rdf.template#L17) still has the Page Shot `homepageURL`.

That URL should be updated to `https://screenshots.firefox.com`.

**Comment by pdehaan** [comment]
Also filed #3081; _"Investigate remaining 'pageshot' references"_ so we can convert the remaining lingering PageShot references.
