### ISSUE TITLE
Pageshot errors in responsive design view

### ISSUE THREAD

**Issue by schalkneethling** [mozilla-services/screenshots#3046]
I am pretty sure this used to work but, since upgrading to Fx 54 Page Shot throws the following error when trying to take a screen shot in responsive design view:

<img width="1098" alt="screen shot 2017-06-16 at 12 55 05" src="https://user-images.githubusercontent.com/10350960/27224002-4084da82-5293-11e7-9dbf-9bfc9701ad99.png">

**Comment by schalkneethling** [comment]
This is the error thrown in the browser console:

```
mozilla-pageshot:Promise rejected with error: Object { name: "Error", message: "Timeout after 7000ms in pageshot@ad…", popupMessage: undefined, help: "Page Shot may not be able to work o…", stack: "lib/framescripter.js:130", multilineStack: "lib/framescripter.js:130" }  errors.js:141
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Jun 16 2017 13:00:57 GMT+0200 (SAST)
Full Message: Error: Timeout after 7000ms in pageshot@addIds
Full Stack: exports.callScript/pendingTimeouts[id]<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/lib/framescripter.js:130:25
notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
```
Also, after this happens, even switching out of responsive design view renders Page Shot broken for the current tab.

**Comment by wresuolc** [comment]
We think this is fixed.  Can you still reproduce it?

**Comment by timdream** [comment]
> Edit: Looks like this is disabled now as a "non-standard" web page.

Yeah, I saw that and thought it's a bug worth reporting. Should we reopen this issue?
