### ISSUE TITLE
[9.0.0] Screenshot overlay doesn't work at all on ulmart.ru

### ISSUE THREAD

**Issue by SXZ1** [mozilla-services/screenshots#3047]
Hello!
Ulmart is some kind of russian Amazon, more info on wiki.
STR:
Nightly 16-06, Screenshot 9.0.0, create new profile, launch it
Open new tab, go to https://www.ulmart.ru/goods/3863051?jd=false
Wait until the web page stops loading
Click on  Screenshot button

ER: Screenshot overlay on top of the ulmart page
AR: No overlay, Screenshot completely broken

**Comment by SXZ1** [comment]
These entries in the browser console seem to be related to Screenshot addon:
![image](https://user-images.githubusercontent.com/26294581/27225878-da8c46d6-52a4-11e7-9b2a-406e11427ea6.png)

**Comment by 6a68** [comment]
@SXZ1 Thanks for the bug report! Unfortunately, none of those console
messages were created by Screenshots code.

Looking at the page, there are already 19 (!) iframes in the page. I wonder
if the page has some rules that prevent unknown iframes (like the
Screenshots overlay) from displaying properly.

**Comment by ianb** [comment]
OK, I figured this out.  On that page there's a CSS file with these rules:

```css
body > iframe {
  position: absolute !important;
  clip: rect(1px,1px,1px,1px);
}
```

Both of them render our iframe invisible.

@niharikak101 is in the middle of a PR that would be useful here, adding some rules to [this function](https://github.com/mozilla-services/screenshots/pull/3050/files#diff-88bd153ab5ec987fdce5d6c98f39f31dR79).  Specifically adding `!important` to the position and `clip: auto`.  I'm going to hand it off to her.
