### ISSUE TITLE
Initial run-server takes a long time

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3048]
Takes me around 5 minutes to get through the full babelification on first run of the server.

Would be great to reduce this time, especially for new contributors.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
