### ISSUE TITLE
Wait for add-on startup before shutdown

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3057]
Per [Bug 1373614](https://bugzilla.mozilla.org/show_bug.cgi?id=1373614#c14), our unconditional shutdown in bootstrap.js is causing problems for MochiTests.

I'm guessing we might just need to do:

```js
function stop(webExtension, reason) {
  appStartupPromise.then(() => {
    webExtension.shutdown(reason);
  });
}
```

I.e., wait on `appStartupPromise`

**Comment by whimboo** [comment]
To add the problem is for test suites using Marionette and using its quit() or restart() method.

**Comment by ianb** [comment]
There's an [attachment on the other bug](https://reviewboard.mozilla.org/r/151830/diff/1#index_header) – it has to be applied to this repo of course, but I want to be sure it actually solves the problem before doing so.

**Comment by ianb** [comment]
We have a new attachment in place that seems to fix it.  I'm waiting for it to land, then will apply it to this repo.

**Comment by wresuolc** [comment]
Ian says this is fixed
