### ISSUE TITLE
Screenshots aren't very privacy friendly

### ISSUE THREAD

**Issue by pgerber** [mozilla-services/screenshots#3061]
I took a look at the screenshot functionality now offered in Firefox Nightly and noticed a disturbingly large number of privacy issues:

* *Save visible* and *Save full page* directly send screenshots to screenshots.firefox.com, without any warning.
* When selecting an area there is a possibility to download, which is good. However, the button labelled *Save* does in no way indicate that the screenshot is uploaded. Matter of fact, in the menu entry *Save Page As…*, the word save is used to mean save locally. *Upload* or *Publish* might more accurate.
* It isn't possible to remove screenshots if *Accept third-party cookies* is set no *Never*.
* A download link is automatically added to the clipboard even in *Private Browsing* mode.

  Mozilla describes *Private Browsing* like this:

  > Firefox Private Browsing automatically erases your online info like passwords, cookies and history from your computer. So that when you close out, you leave no trace. 

  The current behavior contradicts the description, clipboard entries remain after closing out. I guess there isn't really anything you can do if a user decides to copy a link but I doubt automatically adding it to the clipboard is a good idea.
* Screenshots taken in a *Private Browsing* window are added to the list of my regular screenshots and remain there even after leaving *Private Broswing* or closing the browser. While I don't mind that the screenshots remain online (after the user has been informed that the screenshots are uploaded), the screenshots really shouldn't be associated with the non-private-browsing account. Otherwise, you'll "leave a trace" which is exactly what Mozilla says you won't.

**Comment by MikkCZ** [comment]
> It isn't possible to remove screenshots if Accept third-party cookies is set no Never.

I have noticed this now too in https://github.com/mozilla-services/screenshots/issues/3085.

> A download link is automatically added to the clipboard even in Private Browsing mode.

I think it is a nice feature, but it probably should not happen in private mode, that's right.

> Screenshots taken in a Private Browsing window are added to the list of my regular screenshots and remain there even after leaving Private Broswing or closing the browser. While I don't mind that the screenshots remain online (after the user has been informed that the screenshots are uploaded), the screenshots really shouldn't be associated with the non-private-browsing account. Otherwise, you'll "leave a trace" which is exactly what Mozilla says you won't.

This is interesting. I thought screenshots are uploaded to some "account" based on a cookie you get the first time. But in private mode cookies shouldn't be reused.

**Comment by wresuolc** [comment]
Hi, thanks for filing.  It's best to keep issues filed separately so they are easy to work with.  I'll comment inline on these though.

>   Save visible and Save full page directly send screenshots to screenshots.firefox.com, without any warning.

This is being tracked at https://github.com/mozilla-services/screenshots/issues/2157

>   When selecting an area there is a possibility to download, which is good. However, the button labelled Save does in no way indicate that the screenshot is uploaded. Matter of fact, in the menu entry Save Page As…, the word save is used to mean save locally. Upload or Publish might more accurate.

This is being tracked at https://github.com/mozilla-services/screenshots/issues/3056

>  It isn't possible to remove screenshots if Accept third-party cookies is set no Never.

This is being tracked at https://github.com/mozilla-services/screenshots/issues/3085

>   A download link is automatically added to the clipboard even in Private Browsing mode.
> 
>   Mozilla describes Private Browsing like this:
> 
>       Firefox Private Browsing automatically erases your online info like passwords, cookies and history from your computer. So that when you close out, you leave no trace.
> 
>   The current behavior contradicts the description, clipboard entries remain after closing out. I guess there isn't really anything you can do if a user decides to copy a link but I doubt automatically adding it to the clipboard is a good idea.
> 
>   Screenshots taken in a Private Browsing window are added to the list of my regular screenshots and remain there even after leaving Private Broswing or closing the browser. While I don't mind that the screenshots remain online (after the user has been informed that the screenshots are uploaded), the screenshots really shouldn't be associated with the non-private-browsing account. Otherwise, you'll "leave a trace" which is exactly what Mozilla says you won't.

Both of these are being tracked at https://github.com/mozilla-services/screenshots/issues/2818 (and we're just going to disable ourselves in Private Browsing in the short term).

Thanks for filing this, I'm going to close it now so we can track the suggestions individually.

**Comment by FlorentBecker** [comment]
"Save" meaning "upload to cloud" is a very serious privacy breach. Firefox has no way to know that the content of the page being screenshot is not of the most critical level of confidentiality to the user. Furthermore, **the more sensible this information is**, the more likely it is that the user is stressed about handling it, so **the least likely they are to notice clues that an upload is happening**. "Save" needs to be the label of the "local save" functionnality, and "upload to cloud" needs to be "Foolishly publish for the whole world to see, or at least the administrators of downloads.firefox.com and whomever may acquire or hack them in the future." Wording can be discussed, but should definitely start with "Foolishly" or "carelessly".
