### ISSUE TITLE
Drop xlink:href (and therefore xmlns:xlink) from all the SVG files

### ISSUE THREAD

**Issue by gijsk** [mozilla-services/screenshots#3063]
https://bugzilla.mozilla.org/show_bug.cgi?id=1359030 turned up:

```
addon/webextension/icons/back-highlight.svg
addon/webextension/icons/back.svg
addon/webextension/icons/cancel.svg
addon/webextension/icons/done.svg
addon/webextension/icons/download.svg
addon/webextension/icons/icon-welcome-face-without-eyes.svg
addon/webextension/icons/menu-fullpage.svg
addon/webextension/icons/menu-visible.svg
```

I think the xlink namespace declaration can be dropped from these, and we can use plain href attributes instead of xlink:href for referencing.

**Comment by ianb** [comment]
I considered doing this with svgo, but on further reflection I think we should just fix this with a text-replace.
