### ISSUE TITLE
'Get started' homepage link doesn't work

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3065]
On screenshots.firefox.com, there's a 'Get Started' link at top right. Clicking it just goes to `screenshots.firefox.com/#`, it doesn't load the onboarding flow.

**Comment by wresuolc** [comment]
@youwenliang what should this link do?

**Comment by pdehaan** [comment]
Probably a dupe of #2907 _"Getting started link on homepage jumps to top of page"_.

**Comment by youwenliang** [comment]
I think the original design is to click "Get started" and it will scroll down to "How Firefox screenshots works" section.
