### ISSUE TITLE
Investigate autoprefixer for cross-browser CSS issues

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3071]
quoth @pdehaan in #3054:

> Do we need something like autoprefixer to try and handle vendor prefixes and compat issues?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
