### ISSUE TITLE
Screenshots overlay button icons are not displayed on latest Nightly build

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3072]
[Notes]:
- I am not sure if this issue will be fixed in Nightly or on Screenshots, so I have also logged this on Bugzilla: [bug 1377128](https://bugzilla.mozilla.org/show_bug.cgi?id=1377128).

[Affected versions]:
- Nightly 56.0a1, Build ID:20170629030206

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the latest Nightly build and click the "Screenshots" icon from browser toolbar.
2. Skip the "Tour" pop-up.
3. Observe the "Save full page", "Save visible" and "My Shots" buttons
4. Perform a selection and observe the "Cancel" and "Download" buttons.

[Expected result]:
Step 3 & Step4: The button icons are correctly displayed.

[Actual results]:
Step 3 & Step4: The button icons are no longer displayed.

[Regression]:
Last good revision: 6cc6282c67c75b86289d944a31cb39f5a5639925
First bad revision: 3358bef7a047d347e576bbb83d1461b3776fc5fb
Pushlog: https://goo.gl/z1u9Kj

[Additional Notes]:
- Here is a screen shot with the issue:
![screenshots](https://user-images.githubusercontent.com/19226534/27695489-b39730ec-5cf7-11e7-9599-bf4e74365914.png)

**Comment by ianb** [comment]
I'm not seeing this myself on 56.0a1 (2017-06-29) (Mac)

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on Mac Os 10.12 and also on 10.11 with latest Nightly (56.0a1, Build ID: 20170629100331)

**Comment by SXZ1** [comment]
I can reproduce this issue with a new profile. Nightly 30-06-17, Windows 8.1 x64 with latest updates.

**Comment by johngruen** [comment]
I'm seeing it

**Comment by wresuolc** [comment]
I can reproduce this on linux also

**Comment by veer66** [comment]
I can reproduce this on 56.0a1 (2017-07-04) (64 bit) on Windows 10.

![shot1](https://user-images.githubusercontent.com/370688/27845281-0ee91c94-6158-11e7-9543-1645893fac96.png)
![shot2](https://user-images.githubusercontent.com/370688/27845282-0eee8f26-6158-11e7-8a10-39f38b887f20.png)

**Comment by giridharangm** [comment]
Exists in `56.0a1 (2017-07-04) (64-bit)`

**Comment by johngruen** [comment]
I'm seeing this fixed in `56.0a1 (2017-07-07) (64-bit)`

**Comment by johngruen** [comment]
Let's keep this open for softvision to confirm

**Comment by SoftVision-EmilPasca** [comment]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

This issue is no longer reproducible, tested on Windows 10 x64, Mac OS 10.12 and Ubunutu 14.04 x64 with the latest Nightly (56.0a1, Build ID: 20170709030204) with a new clean profile.
