### ISSUE TITLE
Publish KB article

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3077]
Paul reminded me that we still need to get https://docs.google.com/document/d/1J_ajONSlhM1PpCL1JFFun9phLhvU4EslI305DAIo1_Q/edit?ts=58f7876d published

**Comment by johngruen** [comment]
Emailed Paul to get the ball rolling again

**Comment by johngruen** [comment]
Published: https://support.mozilla.org/en-US/kb/firefox-screenshots
