### ISSUE TITLE
Error saving expiration: 401 Unauthorized when 3rd party cookies are disabled

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3085]
STR:
1. Open Firefox preferences.
2. Set custom history settings + disallow 3rd party cookies.
3. Delete all screenshots.firefox.com cookies.
4. Take a screenshot.
5. On the screenshot page try to change expiration.
6. Error saving expiration: 401 Unauthorized error is displayed.

What should happen:
Changing expiration should not rely on 3rd party cookies, as they may be disabled. Btw. it would be also nice if the expiration change is not accessible at all, if you are not authorized to do so ("expires in XX minutes" not clickable).

**Comment by 6a68** [comment]
Here's an idea for some user-visible errors when this happens:

System addon observes the `third-party-cookie-rejected` (and maybe `private-third-party-cookie-rejected`?) event(s), and if the rejected URL is the screenshots website, shows a useful error via desktop notification.

Another idea: system addon checks the value of the `network.cookie.cookieBehavior` pref. Not sure we want to leak this information to the site, though.

**Comment by MikkCZ** [comment]
Hmm, maybe it does not have to be exposed to the site, but the information can be shown by the addon itself when making the screenshot. Just a note, that the cookies are disabled and the user won't be able to change the image settings...

Or maybe a workaround to not upload the image via Ajax request, but rather open a new tab a upload the image from the content script?

**Comment by wresuolc** [comment]
Let's track this in #3581
