### ISSUE TITLE
Landing screenshot 04 contains wrong domain

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3087]
STR:
1. Visit https://screenshots.firefox.com/.
2. Scroll down to see the last landing image (https://screenshots.firefox.com/static/img/landing-screenshots_image_04.svg).
3. The image contains subdomain _screenshot.firefox..._, while it should be _screenshot**s**.firefox..._.

**Comment by pdehaan** [comment]
I think this is a dupe of #2906; _"Typo in landing-screenshots_image_04.svg image on homepage"_.

**Comment by MikkCZ** [comment]
You are right, this is duplicate.
