### ISSUE TITLE
Add A few custom metrics to add on

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3091]
I would like to know: 
* What _Channel_ of Firefox people are on
* What _Version_ of Firefox people are on
It occurs to me that the first data point may not be easy to grab from w/in a web extension

**Comment by 6a68** [comment]
We can get this data from bootstrap. Based on the discussion in https://bugzil.la/988725, looks like Firefox exposes `Services.appinfo.defaultUpdateChannel` ('nightly', 'aurora', 'esr', and 'release'), and `Services.appinfo.version`, which is currently `53.0.3` on release, a little more detailed than the `53.0` provided by `navigator.userAgent`.

Doesn't look like this is exposed yet by webextensions, so we'll have to add a message to fetch it from the bootstrap side on startup (or maybe when checking the telemetry pref)

**Comment by 6a68** [comment]
@johngruen How do you want to pass the channel to GA? Is there a specific key you'd like to add?

**Comment by johngruen** [comment]
We have the version already

**Comment by johngruen** [comment]
We can triangulate releae branch based on `App ID` and `Browser Version`
