### ISSUE TITLE
Can't take screenshots of about:newtab

### ISSUE THREAD

**Issue by marco-c** [mozilla-services/screenshots#3094]
If I click the screenshot button in a new tab page, I get redirected to https://screenshots.firefox.com/shots.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @marco-c and thanks for your report! However, this is the intended behavior, Screenshots functionality is restricted for "about:" pages. 
For example, "about:home" and "about:newtab" redirect you to your saved screenshots. While on other "about:" pages like "about:addons", you get a notification saying " We can't screenshot this page. This isn't a standard Web page, so you can't take a screenshot of it.".

**Comment by PwrSrg** [comment]
I am trying to take a screenshot of my local development (*.dev) and am running into the same error.
"We can't screenshot this page. This isn't a standard Web page, so you can't take a screenshot of it."

It seems that ANY page that does not have a traditional web extension (.com, .net, etc) is not considered a "standard Web page".
