### ISSUE TITLE
[My Shots] "We can't screenshot this page" notification is displayed while trying to take a screenshot via the context menu

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#3095]
[Affected versions]:
Firefox 55.0b7 (Build Id:20170706085221)
Firefox 56.0a1 (Build Id:20170709030204)
Firefox Screenshots version: 10.3.0

[Affected platforms]:
Windows 10 64 bit
MacOS 10.10.5
Ubuntu 16.04 64bit

[Steps to reproduce]:

1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots.
3. Take a screenshot.
4. Access the "My Shots" page.
5. Right Click and select the "Take a screenshot" option.

[Expected result]:
a. The user is able to perform a screenshot on the "My shots" page.
b. The user is not able to perform a screenshot on the "My shots" page.

[Actual result]:
The "We can't screenshot this page" notification is displayed and performing a screenshot on the "My Shots" page is not possible from the context menu.

[Additional notes]
Screenshots can be successfully performed on the "My Shots" page via the Firefox Screenshots button.
For further details please observe the following video: https://goo.gl/YLRViB

**Comment by wresuolc** [comment]
This is by design
