### ISSUE TITLE
Does Firefox screenshots need a security and privacy review?

### ISSUE THREAD

**Issue by jan-ivar** [mozilla-services/screenshots#3098]
While https://github.com/mozilla-services/screenshots/issues/3061 covers it being unclear when screenshots are publicly uploaded vs. "saved" to the local computer, I have security and privacy concerns with the uploads themselves.

I'm concerned about threat vectors similar to those of [screensharing](https://support.mozilla.org/en-US/kb/screenshare-safety). Basically, a malicious website encouraging use of the feature may use cross-origin iframes to include privacy-sensitive logged-in content in screenshots, maybe even disguised with css (making it near invisible). This might be difficult to spot in long pages. This would be content the site is normally not allowed to see, due to the same-origin policy. This does an end-run around that.

While the same is true for `Prt Scr`, since all uploads end up under https://screenshots.firefox.com a site may be able to harvest sensitive information from a pool of users quickly by guessing urls.

**Comment by jvehent** [comment]
We did have a privacy and security review, and I think @pauljt specifically looked at these attack vectors.

**Comment by pauljt** [comment]
As per Julian's comment - there has been a security review (see https://github.com/mozilla-services/screenshots/issues?q=is%3Aopen+is%3Aissue+label%3Asecreview for issues raised). That said, if there  are any additional risks please raise them (though security@mozilla.org is the preferred channel for private reporting once a product goes to release)

**Comment by pauljt** [comment]
FWIW I dont _think_  scraping is a risk -  when I looked at the earlier version of this product, the entropy of the uploaded screenshot URLs seemed pretty high, so guessing/bruteforcing seemed unlikely - but if this isnt true (and we are leaking the URIs somehow) this is something we'd want to know about.

**Comment by pauljt** [comment]
Also note that screenshots uses web server headers like x-frame-options to prevent things like click-jacking and a strict CSP. Coercing the user to screenshot data is certainly a risk, but using cross-origin framing isn't allowed. The attacker would need to coerce the user to a) take a screenshot of a sensitive document, AND then b) convince the users to disclose the URI (containing the UUID token which protects the privacy of the screenshot).

**Comment by wresuolc** [comment]
thanks for the report and replies

**Comment by jan-ivar** [comment]
Glad to hear cross-origin framing isn't allowed!
