### ISSUE TITLE
Export 10.4.0 to beta

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3099]
This will be a branch off of 10.3.0:

- [x] https://github.com/mozilla-services/screenshots/issues/3056 DONE
- [x] https://github.com/mozilla-services/screenshots/pull/3084 (in review)
- [x] #3100 (not yet done)

**Comment by ianb** [comment]
Work happening in the `v10.4.0-export` branch, with 2/3 patches cherry picked.

**Comment by ianb** [comment]
Export will depend on https://bugzilla.mozilla.org/show_bug.cgi?id=1379464 and maybe one other bug @johngruen will identify

**Comment by johngruen** [comment]
The two issues blocking this are as follows:
https://bugzilla.mozilla.org/show_bug.cgi?id=1377302
and 
https://bugzilla.mozilla.org/show_bug.cgi?id=1379464

**Comment by ianb** [comment]
Export bug: [Bug 1380120](https://bugzilla.mozilla.org/show_bug.cgi?id=1380120)

**Comment by johngruen** [comment]
@ianb https://bugzilla.mozilla.org/show_bug.cgi?id=1380119

**Comment by ianb** [comment]
Well, that didn't go so well, trying again with 10.5.0 in #3121
