### ISSUE TITLE
My Shots page: `key` prop warning on Card components

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3115]
Followup from server l10n PR (#3068):

<img width="890" alt="screen shot 2017-07-12 at 4 21 21 pm" src="https://user-images.githubusercontent.com/96396/28144055-2d0d9260-671e-11e7-86ad-c28420bef0f4.png">

**Comment by ianb** [comment]
This was fixed. FYI, lack of a key caused #3267
