### ISSUE TITLE
Make truncation RTL-friendly

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3116]
Followup from server l10n PR (#3068): Update the `displayTitle` method in `shotindex.js` to ellipsize and truncate in an RTL-friendly way, or, check if `body` has the `dir=rtl` attribute set, and reverse the direction of truncation.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
