### ISSUE TITLE
Simplify l10n.js getText method

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3117]
Followup from server l10n PR (#3068):

Currently, a set of MessageContexts is generated inside the l10n.init function, so that a getText function can be exported. However, it looks like fluent-react has since added its own way of exposing translations to non-view code: https://github.com/projectfluent/fluent.js/wiki/withLocalization. See if we can use the fluent-react way instead.

**Comment by ianb** [comment]
This seems to be working fine how it is right now.
