### ISSUE TITLE
Disable in private browsing mode

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3120]
Looks like the `incognito` manifest key should work

**Comment by 6a68** [comment]
turns out incognito manifest key does nothing

**Comment by 6a68** [comment]
lol, browser compatibility table here shows that 'incognito' is not yet supported by firefox https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito

**Comment by 6a68** [comment]
aha! `tab.incognito` tells us

**Comment by 6a68** [comment]
@johngruen Turns out the 'incognito' manifest key only works on chrome, for now.

We can eagerly or lazily detect private browsing. Since Screenshots, in the past, caused Talos regressions by running code when the user switches tabs, I think lazy detection is best. This means we'd not disable the button in private browsing mode, but instead would show an error when the user initiates a shot.

How do you want to message the private browsing limitation to users? It seems late in the 55 cycle to add a string

**Comment by johngruen** [comment]
@_6a68 I don't see how we do this w/o a string...

title=Screenshots is disabled in Private Browsing Mode
subtitle=Sorry for the inconvenience. We are working on this feature for future releases.

If we can push to dev today we should get significant coverage over the weekend.

**Comment by 6a68** [comment]
:+1:

**Comment by ianb** [comment]
Hmm... we haven't updated strings yet in 10.x.0. To get strings in we'll need to figure out how to cherry-pick them all out, or maybe just export this one string?

**Comment by 6a68** [comment]
I'll add a list of strings and dates to #3121 and we can see which ones need to land

**Comment by Caspy7** [comment]
Why do we need to disable in private mode? We're only sending back data if the user interacts with it, no?
So Screenshots is on the level with saving bookmarks. They're using instantiated.

**Comment by Caspy7** [comment]
I have read the comments in issue #2818 and believe I understand that this may not be a permanent change, but is to protect privacy until a better mitigation is implemented.

**Comment by dveditz** [comment]
Clearly it would be important to remind users they're in private mode in case they forgot, but I hope that the functionality is eventually restored. Even the server upload could be appropriate for some use cases: say I'm shopping for rings and don't want local traces, but want to share a screenshot to get advice. Random link, no history in private mode, and delete the server copy after and it's private enough.
