### ISSUE TITLE
Make 10.5.0 release

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3121]
We need to get:

- [x] #3079 commit c3ef21e062496478648239f0b024dd5b93e8ae83 – missing this is what messed up 10.4.0
- [x] Private browsing disabling (#3120) PR #3122 commit aefc639b12c2f4cc716b2eca6006b21e32602648

**Comment by 6a68** [comment]
Looks like we haven't had too many string changes in version 10:
- tweak strings, #3016 
- update terms / privacy, #3024
- private windows strings, #3120

**Comment by ianb** [comment]
Happening in [Bug 1380817](https://bugzilla.mozilla.org/show_bug.cgi?id=1380817)
