### ISSUE TITLE
[Windows] "Screenshots went haywire" error message displayed for any screenshot taken and the overlay wrongly remains displayed on root page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla-services/screenshots#3127]
**[Notes]:**
- This issue is caused by a Nightly regression that started with the build from July 11th. Here is the pushlog link: https://goo.gl/SKjisQ.
- The same Firefox regression caused issues for Notes experiment.

**[Affected versions]:**
- Nightly 56.0a1 (2017-07-11) and above

**[Affected Platforms]:**
- All Windows

**[Steps to reproduce]:**
1. Start the latest Nightly build and navigate to a web page (eg: youtube.com)
2. Click the "Screenshots" icon from browser toolbar.
3. Click the "Skip" button from bottom left of the "Tour" pop-up.
4. Make a selection and click on "Save" button or select one of the available capture options.
5. Observe the browser behavior. 
6. Close the screenshot page and observe the root page.

**[Expected result]:**
- Step 5: A new tab is opened where the screenshot take is displayed and a notification message appears that informs you that the screenshot was copied to clipboard.
- Step 6: The Screenshots overlay is no longer displayed on the root page. 

**[Actual results]:**
- Step 5: A new tab is opened where the screenshot is loaded, but 2 notification messages with "Whoa! Firefox Screenshots went haywire." message are displayed.
- Step 6: The Screenshots overlay is still displayed on the page.

**[Additional Notes]:**
- You cannot take another screenshot on the root page while the overlay is displayed. None of the options is working (selection, entire page or visible).  
- Here is a screen recording of the issue: https://goo.gl/G1PCC5
- Browser Console error:
![haywire console](https://user-images.githubusercontent.com/17258026/28215125-8be93bca-68b5-11e7-9fe6-6204173a2364.png)

**Comment by SoftVision-PaulOiegas** [comment]
@ianb Filed this issue also in Bugzilla and NI Kris Maglione on it, since it seems that his changes generated this behavior.

**Comment by wresuolc** [comment]
Looks like that bug is fixed so closing this

**Comment by SoftVision-PaulOiegas** [comment]
Forgot to update this issue. Both me and Cosmin checked it last week and it seems to be fixed. 👍
