### ISSUE TITLE
Create addon-export branch and server-prod

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3128]
Names TBD. But our release process for the server and add-on is substantially different, so we should be branching to two branches independently, to give us a stable place to look for the latest live code.

**Comment by ianb** [comment]
We now have a server-prod branch, and some docs about deploying to it.

Stable is kind of our Firefox export... but not really, at least not at the moment. When we do our next export (after 10.x.0) we should revisit it for Firefox export as well.

**Comment by wresuolc** [comment]
Let's sync up with https://docs.google.com/document/d/1CSzT45tpTRyDh3yiGCSOqcd74WDOJFTooiadKkXjFXY/edit

**Comment by ianb** [comment]
I called the export branch `firefox-export` and it is noted in the export docs.
