### ISSUE TITLE
Update screenshots Privacy Notice

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3135]
From legal:

> We have decided to retire the Firefox Cloud Services Privacy Notice and fold its current content into the Firefox Browser Privacy Notice. As a result, your team needs to redirect all "Privacy" links in Screenshots from the CS notice to the browser notice. 

Browser Notice URL is https://www.mozilla.org/privacy/firefox/

**Comment by flodolo** [comment]
I really hope it's not, it should be just a code matter :-)

**Comment by 6a68** [comment]
This is fixed in the v10.4.0-export branch, which will be merged into master when #3142 lands
