### ISSUE TITLE
The loading spinner is not animated when the image is creating (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3147]
[Affected versions]:
- Beta 55.0b9
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pre is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Navigate to any website.
3. Click on the Screenshots icon from browser toolbar.
4. Perform a selection and click the "Save" button.
5. Observe the loading spinner when the image is creating.

[Expected result]:
- The loading spinner is correctly animated.

[Actual results]:
- The loading spinner is not animated and is stuck until the image is displayed.

[Notes]:
- The issue is only reproducible on dev server.
- Also, there is no spinner on "Creating..." page.
- Here is a screen shot with the issue:
![loading spinner1](https://user-images.githubusercontent.com/19226534/28374118-7b3d8768-6cac-11e7-985e-8abbe0a9a5b2.gif)

**Comment by SoftVision-CosminMuntean** [comment]
The behavior is changed a little and the loading spinner is still not displayed on "Creating..." page.
Here is a screen recording with the current behavior:
![spinner 2](https://user-images.githubusercontent.com/19226534/29027535-c018bb96-7b89-11e7-9c70-2861cb552ebb.gif)

**Comment by johngruen** [comment]
Fixed on dev
