### ISSUE TITLE
[l10n] Dev website is not localized

### ISSUE THREAD

**Issue by flodolo** [mozilla-services/screenshots#3152]
Italian is fully localized but there's no trace of localization on
https://screenshots.dev.mozaws.net/

Isn't that supposed to be updated automatically?

CC @6a68

**Comment by johngruen** [comment]
I don't see any PRs into Screenshots, so maybe there's a connection missing somewhere?

**Comment by flodolo** [comment]
> I don't see any PRs into Screenshots, so maybe there's a connection missing somewhere?

Localization is happening directly in master since yesterday.
https://github.com/mozilla-services/screenshots/pull/3068

Italian is currently fully localized, but the website is in English.
