### ISSUE TITLE
[wantsauth metabug] Detect site visits via webRequest & eagerly auth

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3159]
Screenshots users don't have to sign in to access their shots or create shots, so there is a background authentication step that identifies a particular Firefox profile with a set of shots on the srever. Because not all Firefox users are Screenshots users, we lazily perform this auth step, waiting to connect until the user takes a shot.

This lazy, anonymous auth decision leads to a class of particularly ugly, user-facing bugs: if a Screenshots user visits their 'my shots' page, or a shot that they created, without first hitting the Screenshots button, things will go wrong: the 'my shots' page will reload over and over, and the shot page may be displayed with the non-owner view.

One way we could mitigate this might be to use the webextensions webRequest API to detect attempts to navigate to the screenshots website, and when that's detected, do the auth handshake in the background.

Note that we currently wait until the 'sessionstore-windows-restored' internal event to start Screenshots, at which point the windows and tabs have been redrawn, so the user might already be in a shots page refresh loop. This might be a good moment to see if we should still need that delay; I'll file a separate bug to investigate, and link it back to this one.

**Comment by ianb** [comment]
#3185 would mitigate this some
