### ISSUE TITLE
Can we remove the delayed bootstrap startup yet?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3160]
Now that OOP webextensions have landed, we might be able to remove the code that waits to init screenshots until the 'sessionstore-windows-restored' event fires.

Let's remove that code, push to Talos, and see if any regressions are introduced.

**Comment by johngruen** [comment]
@6a68 will look into this

**Comment by 6a68** [comment]
OK, pushed a couple builds to Try. We'll see how this goes.

Link to comparison (should be a few hours before tests are done running): https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=53f1effbf00220772d5412d04181e698a6c7ee7f&newProject=try&newRevision=1480d9d3f6d8082a6deaf89a3e2377306e151765&framework=1

Base commit was current central, all Talos tests x5: https://treeherder.mozilla.org/#/jobs?repo=try&revision=53f1effbf00220772d5412d04181e698a6c7ee7f

New commit with `sessionstore-windows-restored` delay removed, lazy background loading removed, and migration check delay set to 0 (code changes [here](https://hg.mozilla.org/try/rev/96005812a0552e6f04ea9ce94a2edace149c8784)): https://treeherder.mozilla.org/#/jobs?repo=try&revision=1480d9d3f6d8082a6deaf89a3e2377306e151765

**Comment by 6a68** [comment]
Hmm, not sure we're there yet. Next step is probably to run these results past jmaher and kmag and see which of these regressions are of major concern.

![](https://screenshots.firefoxusercontent.com/images/7c9a4131-9dc4-4c79-aeb0-0613112d8ee6.png)

**Comment by johngruen** [comment]
![giphy](https://user-images.githubusercontent.com/3323249/32331034-334a9216-bfb8-11e7-92dd-ce8b437daf60.gif)
q

**Comment by 6a68** [comment]
Update: this might be a thing we could do soon. jmaher's feedback in IRC: "I see slight issues in ts_paint, sessionrestore, and tp5o responsiveness- slightly as in probably <5%; it might be good to rebase and try again"

Running another round of tests.

**Comment by 6a68** [comment]
Latest round of tests:

https://treeherder.mozilla.org/perf.html#/comparechooser?newProject=try&newRevision=754e647e4899912132d00fed40f7d256005bf13a

**Comment by 6a68** [comment]
Since removing all delays doesn't seem like it'll work, I'm going to try disabling just one of the delays at a time and see what the effects might be.

As a reminder:
- the 'app startup' delay waits to start the addon until the 'sessionstore-windows-restored' event fires, which corresponds to all the windows being drawn on screen (MDN).
- the 'webextension lazy load' delay waits to load most of the webextension code until the user clicks the webextension UI (either the page action or the context menu item)
- the migration delay waits 2 seconds to run the migration check code. This code is obsolete, but it might have an impact on startup.

Try runs:
- remove all delays
  - https://treeherder.mozilla.org/perf.html#/comparechooser?newProject=try&newRevision=754e647e4899912132d00fed40f7d256005bf13a

- remove app startup delay, remove migration delay, keep webextension lazy load delay
  - https://treeherder.mozilla.org/#/jobs?repo=try&revision=fc923806735fad901562e84e4e6a34ac71af2370

- keep app startup delay, remove migration delay, remove webextension lazy load delay
  - https://treeherder.mozilla.org/#/jobs?repo=try&revision=cd38856995e319d6a8866e119475a2db1855b2c7

- remove app startup delay, keep migration delay, remove webextension lazy load delay
  - https://treeherder.mozilla.org/#/jobs?repo=try&revision=89664cd29fb30620278903b701c0f0cdfa8cdb04

- keep all delays
  - https://hg.mozilla.org/try/rev/a404d6818c1d95ae67eb9d9c181eeaa61859f820

These can all be compared in the [compare chooser](https://treeherder.mozilla.org/perf.html#/comparechooser), by picking the 'Try' project, then pasting in the commit SHA from the links above:

<img width="788" alt="screen shot 2017-11-15 at 2 17 39 pm" src="https://user-images.githubusercontent.com/96396/32864039-7bb17d12-ca12-11e7-9f35-c67c1b17c943.png">

**Comment by 6a68** [comment]
suggestion from aswan: "seems like you should be able to just put a bunch of your startup code inside requestIdleCallback in the background page and that should "just work""

**Comment by johngruen** [comment]
I'm punting this. not gonna happen in the 59 time frame

**Comment by aswan** [comment]
As of bug 1457224, Firefox (Nightly only for now) is now delaying startup of extension background pages until after sessionstore-windows-restored.  This is not exactly the same as what Screenshots is already doing manually with the hybrid extension, but it may be close enough.  New talos numbers would be interesting...

**Comment by 6a68** [comment]
Here's a run using artifact builds (try syntax: `-b o -p linux64,macosx64,win32,win64 -u none -t all --rebuild-talos 5`)

Current central (latest export not included): https://treeherder.mozilla.org/#/jobs?repo=try&revision=8235fa711e107f55df624a651df5927ac6400845

With the `sessionstore-windows-restored` delay removed: https://treeherder.mozilla.org/#/jobs?repo=try&revision=68e1bd431c62729876cffeae3712329a3ea26d96

Talos run comparing the two: https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=8235fa711e107f55df624a651df5927ac6400845&newProject=try&newRevision=68e1bd431c62729876cffeae3712329a3ea26d96&framework=1

**Comment by 6a68** [comment]
Talos run found _no_ significant performance differences with the startup delay removed (although some of the tests didn't report results). Looks like we can indeed remove the delayed bootstrap startup 🎉

![image](https://user-images.githubusercontent.com/96396/40853323-8560ed0a-6582-11e8-97e6-02a7fd46ed32.png)
