### ISSUE TITLE
Document how to run docker locally

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3166]
I got this far yesterday:

1. Build the xpi: `make unsigned_bootstrap_xpi`
2. Create a docker image: `docker build . -t foo`
3. Run docker locally: `docker run -ti --rm foo`

Wasn't able to get postgres to connect before I moved on

**Comment by ianb** [comment]
Probably it requires docker-compose for coordinating with Postgres.

**Comment by g-k** [comment]
This worked for me for the DB part (`Docker version 18.03.1-ce, build 9ee9f40` on osx `10.13.4 (17E202)`):

```console
docker pull postgres:9.6
docker run -p 5432:5432 --rm -v $(pwd)/server/db-patches/patch-0-1.sql:/docker-entrypoint-initdb.d/patch-0-1.sql --name screenshots-postgres postgres:9.6

# use -d/--detach for the DB or in a separate terminal:
RDS_USERNAME=postgres ./bin/run-server
```

Like Ian says above, we'd probably need docker-compose and to link the postgres port to run them both in containers.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
