### ISSUE TITLE
Screenshots overlay and controls are broken on https://screenshots.firefox.com/#hello after re-enabling

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla-services/screenshots#3173]
[Affected versions]:
- Firefox Nightly 56.0a1 (2017-07-20)
- Firefox 55.0b11 build1 (20170720101430)

[Affected platforms]:
- Windows 10 x64
- Mac OS X 10.11.6
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox with a clean profile.
2. Navigate to about:config and set the extensions.screenshots.system-disabled pref to false.
3. Click the Screenshots button.
4. Skip the Screenshots tour. 
5. Switch to about:config tab and disable Firefox Screenshots.
- inspect https://screenshots.firefox.com/#hello tab
6. Switch again to about:config tab and enable back Firefox Screenshots
- inspect https://screenshots.firefox.com/#hello tab

[Expected result]:
- Firefox Screenshots overlay and controls are not displayed anymore (step 5).
- Firefox Screenshots overlay and controls are properly displayed and functional (step 6).

[Actual result]:
- Firefox Screenshots overlay and controls are broken (steps 5 and 6).
- The tour is also broken occasionally (step 6).

**Comment by IuliaCristescu4** [comment]
This issue will be more easily reproducible when Screenshots will be enabled by default: the user will just have to leave the https://screenshots.firefox.com/#hello tab open and go to disable Screenshots (steps 1 and 2 won't be needed anymore).

**Comment by ianb** [comment]
This is a limitation of the WebExtension APIs: if an add-on is disabled (as happens when the pref is turned off), there's no way for us to tear down the screenshot context works on existing tabs. (This is something we see a lot during development as the add-on reloads.) So unfortunately we can't fix this. Reloading a tab will fix it.
