### ISSUE TITLE
Firefox Screenshots is not compatible with Windows High Contrast themes

### ISSUE THREAD

**Issue by emilghittasv** [mozilla-services/screenshots#3174]
[Affected versions]:
Firefox 55.0b11
Firefox Screenshots version: 10.5.0

Firefox 56.0a1 
Firefox Screenshots version: 10.7.0

[Affected platforms]:
Windows

[Steps to reproduce]:

1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots.
3. Enable a High Contrast Theme on Windows.

[Expected result]:
The Overlay is visible and screenshots can be easily performed.

[Actual result]:
The overlay is displayed as black (which makes the content not visible).

![high contrast theme](https://user-images.githubusercontent.com/28087895/28458008-d6f57e0c-6e10-11e7-9a47-dc3ccfdc55ce.png)

**Comment by ianb** [comment]
Maybe we can detect this and change styles: http://hanshillen.github.io/HCMDS/hcmode_detection.html

**Comment by johngruen** [comment]
I wanna look at this on windows.
