### ISSUE TITLE
Screenshots does not work on Github Blame Pages

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3175]
STR: try to take a screenshot of this. 

Screenshots crashes:
https://github.com/mozilla/send/blame/master/package.json

**Comment by ianb** [comment]
I'm not seeing a crash, though when I select a region the buttons end up off the left side of the page.

**Comment by wresuolc** [comment]
I don't see any problems.
Full screen: https://screenshots.firefox.com/XNj6MdKiK3rvEW8o/github.com
Partial: https://screenshots.firefox.com/0SwXNoa4aRzRgtQl/github.com
