### ISSUE TITLE
Controls are displayed inside the selection if it includes the bottom edge of the window

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla-services/screenshots#3179]
[Affected versions]:
- Firefox Nightly 56.0a1 (2017-07-20)
- Firefox 55.0b11 build1 (20170720101430)

[Affected platforms]:
- Windows 10 x64
- Mac OS X 10.11.6
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots (if it isn't already) - navigate to about:config and set the extensions.screenshots.system-disabled pref to false.
3.  Navigate to a random website and click the Screenshots button from the main browser toolbar.
4. Perform a selection that includes the bottom edge of the window.

[Expected result]:
The selection is successfully performed and the Cancel, Download and Save buttons are properly placed, beside the selection.

[Actual result]:
The Cancel, Download and Save buttons are displayed inside the selection (see the [screencast](https://goo.gl/7qJ2sF) ).

[Note]
The same result is triggered if an already performed selection is moved to the bottom edge of the window.

**Comment by IuliaCristescu4** [comment]
This issue seems to be caused by https://github.com/mozilla-services/screenshots/issues/2259.

**Comment by ianb** [comment]
This is how we decided to display buttons when the edge of the screen gets in the way of their normal placement.
