### ISSUE TITLE
Screenshots icon is moved in Additional Tools and Features after Restore Defaults

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla-services/screenshots#3180]
[Affected versions]:
- Firefox Nightly 56.0a1 (2017-07-20)
- Firefox 55.0b11 build1 (20170720101430)

[Affected platforms]:
- Windows 10 x64
- Mac OS X 10.11.6
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox with a clean profile.
2. Enable Firefox Screenshots (if it isn't already) - navigate to about:config and set the extensions.screenshots.system-disabled pref to false.
3. Customize the browser (e.g. apply another theme). 
4. Go to Menu [≡], select Customize and click the Restore Defaults button.
- look for the Screenshots button

[Expected result]:
The Screenshots button keeps its default position and is fully functional.

[Actual result]:
The Screenshots button is moved in Additional Tools and Features. 

[Note]: 
Disabling and re-enabling Firefox Screenshots does not fix the problem.

**Comment by johngruen** [comment]
Closing this b/c we're gonna be a pageAction!
