### ISSUE TITLE
Zoom In/Out is not working using keyboard input [Print preview page]

### ISSUE THREAD

**Issue by Tanvir-rahman** [mozilla-services/screenshots#3181]
Build ID:	20170720101431
User Agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

Steps to Reproduce:
1) Open firefox with New Profile.
2) Navigate to a website which has Reader View.
   (eg. news.yahoo.com, bbc.com).
3) Click on an article from the page.
4) Go to Reader view.
5) Select Print option from menu.
6) Zoom in and out the page (CTRL +/- option using keyboard)  
	
Actual Result:
Zoom In/Out is not working using keyboard input.

Expected:
Zoom In/Out should work using keyboard input.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @Tanvir-rahman, thanks for the report, however it seems that this issue has nothing to do with Firefox Screenshots. 

I suggest logging an issue in https://bugzilla.mozilla.org/ either in Toolkit:: Printing or Toolkit:: Reader Mode.
