### ISSUE TITLE
Chrome layout issue adds space under Firefox promo bar

### ISSUE THREAD

**Issue by digitarald** [mozilla-services/screenshots#3201]
Tested in Chrome & Canary

![image](https://user-images.githubusercontent.com/8599/28548999-32b1cc1e-708c-11e7-9a46-7fe9d01c0efb.png)

**Comment by SoftVision-CosminMuntean** [comment]
I can also reproduce this issue when a saved shot link is opened in Chrome, Opera and Safari browsers.

**Comment by wresuolc** [comment]
:razzledazzle:
