### ISSUE TITLE
Unoptimized gzip and cache settings

### ISSUE THREAD

**Issue by digitarald** [mozilla-services/screenshots#3202]
More details on https://www.webpagetest.org/result/170724_VE_23RP/1/performance_optimization/

Missing gzip: https://screenshots.firefox.com/static/img/spinner.svg?rev=8.1.0-465-gcce97ba

Caching can be extended to multiple days for most static resources, given that the `rev` is in the query (to some, why not to all?):

<img width="718" alt="image" src="https://user-images.githubusercontent.com/8599/28549058-a8e2a3fe-708c-11e7-8eb4-79f91c80c952.png">

**Comment by wresuolc** [comment]
@relud is turning on gzip a switch you can flip?

**Comment by relud** [comment]
yeah, there's an nginx setting for it. what content-types should we compress? I have to specify each of them, except for `text/html` which is automatic. looks like a good list for you would be `image/png image/svg+xml application/javascript text/css`, but I don't know all the types that screenshots serves, so I'm just guessing.

the settings look like this: https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/normandy/puppet/modules/normandy/files/http_normandy_root_location.conf#L21-L23

**Comment by relud** [comment]
this should enable it, on the types i listed above: https://github.com/mozilla-services/cloudops-deployment/pull/1166

**Comment by ianb** [comment]
We shouldn't have compression on `image/png`, they are already fully compressed. The only thing I'd add is `application/x-font-ttf`

**Comment by relud** [comment]
okay, i updated the list to `image/svg+xml application/javascript application/x-font-ttf text/css` in that PR

**Comment by relud** [comment]
okay, mozilla-services/cloudops-deployment#1166 is merged, so the next to deploys to dev/stage will pick up this change.

**Comment by ianb** [comment]
One of the last issues fixed in #3592, and #3590 and #3591 cover the rest.
