### ISSUE TITLE
Enable FxA on dev

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3220]
This requires setting `$USER_SETTINGS` to true

**Comment by wresuolc** [comment]
@relud -- can you set the above variable to 1?  only on dev

thanks!

**Comment by relud** [comment]
what can I set it to outside of dev?

**Comment by ianb** [comment]
Leave it blank (empty string) outside of dev

(I'm pretty sure `"0"` will be treated as true)
