### ISSUE TITLE
Save full page and visible part buttons are missing

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3224]
Only "My Shots button" is now visible in the screenshot mode. Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 ID:20170726100241 CSet: e8400551c2e39f24c75a009ebed496c7acd7bf47, Firefox Screenshots 10.9.0

![snimek obrazovky porizeny 2017-07-27 07-32-48](https://user-images.githubusercontent.com/3941344/28655702-e096d258-729d-11e7-9292-52c18fce9218.png)

**Comment by 6a68** [comment]
Thanks for filing this bug! The buttons were intentionally removed for the 55 release, as the full-page shot wasn't performant enough in certain cases. We'll bring the buttons back as soon as we can. Closing for now

**Comment by MikkCZ** [comment]
Hope it will be soon, besides the automatic selection from the DOM, I love the option to quickly select the whole page or its visible part.

**Comment by svnpenn** [comment]
For anyone who would prefer not to use a crippled "extension", you can disable
it:

~~~js
Services.prefs.setBoolPref('extensions.screenshots.disabled', true);
~~~

**Comment by MikkCZ** [comment]
@svnpenn At this moment the buttons are enabled in current nightly. Not sure about release, but as Screenshots is a system addon, they can enabled it in current release every day.
