### ISSUE TITLE
[Linux] ESC cancels the select mode only when an area is selected

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3225]
STR:
1) Click the Firefox Screenshots button.
2) See the text about canceling the action by pressing ESC.
3) Press ESC.
4) Nothing happens.

The ESC works, but only after you select some area to take a screenshot of. It should work also before when no area is selected yet.

Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 ID:20170726100241 CSet: e8400551c2e39f24c75a009ebed496c7acd7bf47, Firefox Screenshots 10.9.0

**Comment by 6a68** [comment]
Huh. On Mac and Win 10, I can hit Escape as soon as the overlay appears, and it's gone.

@MikkCZ What distro are you using? What window manager? I wonder if your window manager is manipulating the focus, such that hitting Escape isn't sent to Firefox.

**Comment by MikkCZ** [comment]
I am running standard Linux Mint 18.2 with Cinnamon 3.4.4, updated from Mint 18.1.

**Comment by MikkCZ** [comment]
Playing around, seems it's really some focus issue. When I click anywhere in the Firefox toolbar, like I would just want to focus the window, ESC works. Interesting the window looks focused all the time. :(

**Comment by wresuolc** [comment]
ok, closing then. Thanks
