### ISSUE TITLE
Remove comments from shipped localization

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3229]
I notice that the localization shipped to users includes localization comments

**Comment by chenba** [comment]
We should wait until #3228 is merged first?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).

**Comment by ianb** [comment]
Note that the JSON localization messages that we use in the extension have comments stripped.
