### ISSUE TITLE
Pages do not default to English

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3231]
When fetching a page with `requests` I get a page in... maybe Arabic (`ar`)? Except there's also Acholi (`ach`, alphabetically before `ar`), seemingly in the same page.  What craziness is this?!?

**Comment by 6a68** [comment]
Fixed upstream, waiting on npm publish to update the package

**Comment by 6a68** [comment]
fluent-langneg 0.0.3 is out: https://github.com/projectfluent/fluent.js/blob/master/fluent-langneg/CHANGELOG.md#fluent-langneg-003

**Comment by 6a68** [comment]
Unfortunately, fluent-langneg 0.0.3 doesn't fix the bug as I'd expected.

The default is returned if Accept-Language is empty, but in the case of '*', it now returns all the languages in alphabetical order. I guess that's probably the correct behavior, relative to the spec, but if googlebot is seeing arabic, maybe the `accepts` library is passing '*' when the header is missing.
