### ISSUE TITLE
Pref Screenshots on for all channels in Nightly

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3232]
Currently we have a pref that automatically turns us off in beta/release. We should land (in Nightly, no uplift) a patch to turn extensions.screenshots.system-disabled to false (no conditionals).

**Comment by 6a68** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1386333

**Comment by 6a68** [comment]
Got R+, set checkin-needed. This is done
