### ISSUE TITLE
Firefox Screenshot causes AsyncShutdownTimeout crashes in 56.0a1

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla-services/screenshots#3245]
when webextensions were made to run OOP in bug 1357486 a shutdown blocker was also added to make sure add-on shutdown completed before app shutdown: https://hg.mozilla.org/integration/mozilla-inbound/rev/23c63ef286cc35e1e31aa6a9afcaf00d227bf9d6

since then there are at least 500 weekly crash reports on nightly, implicating Firefox Screenshots in causing problems in this regard: https://crash-stats.mozilla.com/search/?async_shutdown_timeout=~screenshots@mozilla.org

in https://bugzilla.mozilla.org/show_bug.cgi?id=1380267#c23 kris suggested it's "likely a race in add-on's own embedded extension startup/shutdown code" that's causing this.

**Comment by wresuolc** [comment]
Kris is changing the limit for the shutdown blocker which we're hoping will address this.

**Comment by johngruen** [comment]
The upstream bug here is now closed. Closing pending further unpleasantness.
