### ISSUE TITLE
Organize server tests

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3249]
There's a couple tests in `test/server/` but they are just unorganized scripts. They should run with a test runner.

**Comment by ianb** [comment]
I think this is getting important with all the moving parts. I'm thinking of adding py.test for the runner.

**Comment by 6a68** [comment]
would be really nice to move the tests to javascript. lowers the bar for contributors

**Comment by ianb** [comment]
Async code for testing is brutal, I'm pretty skeptical of using JavaScript for these tests.
