### ISSUE TITLE
Create an option to share full URL

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#3251]
Due to security issues, we remove the full URL when sharing screenshots with other. But maybe we can provide an option for people who want to share the full URL.

![1 0 source options](https://user-images.githubusercontent.com/8919308/28808489-fc343446-76ae-11e7-8b85-78b4624af0fd.png)

If a user checked the checkbox and share full URL, the receiver will see:
![1 2 source options receiver full](https://user-images.githubusercontent.com/8919308/28808491-fd6500ca-76ae-11e7-8979-e0ff7600fec2.png)

If a user didn't check the checkbox and share only the domain name, the receiver will see:
![1 1 source options receiver hide](https://user-images.githubusercontent.com/8919308/28808493-fedf900a-76ae-11e7-8078-0a38518432ac.png)

**Comment by johngruen** [comment]
@youwenliang not sure if anyone actually clicks on that share link...maybe we could think about exposing that option a different way

**Comment by kumar303** [comment]
What is the security issue with exposing the full URL?

I wanted to remember/share a specific reply in a long thread (https://www.muffwiggler.com/forum/viewtopic.php?p=131793&sid=7d2152387b91279b82dabb4e4c6805b0) so I took a screenshot of just the reply. I was surprised that it didn't link back to the full URL.

**Comment by g-k** [comment]
Full urls can be capability urls (email verification, password reset, or access control to an image, document, or gist) or disclose personal information e.g. a user's email or the session ID in a query param.

There's further discussion in https://github.com/mozilla-services/screenshots/issues/2342 but I think we ended up adding this option to make sharing the full URL opt in.

**Comment by dserodio** [comment]
Opt-in (for every screenshot, not as a default for all screenshots) looks like the best option.

**Comment by Marek-Moehling** [comment]
Would be helpful if users could add text notes that could be searched for later, these notes could include urls.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
