### ISSUE TITLE
Create a place for cross-promotional marketing on Shot pages

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3253]
<img width="1024" alt="work notes - 107" src="https://user-images.githubusercontent.com/3323249/28817399-639daba0-76a8-11e7-9055-fc353c3801d3.png">

Right now we have a top bar linking to a Firefox download page if a user looks at a Screenshot in a non-FF browser. While this bar is nice, I'd like a place to add content that does not require us to write new code. Basically i'd like to have a place for advertising other Firefox features/products in Screenshots.

## Acceptance

- [ ] it should accept an advertising image and string
- [ ] it should appear on the shot page
- [ ] it should not break layouts on mobile views
- [ ] it should be a standard size so that we can create lots of different content to test

**Comment by fangshih** [comment]
We have few proposals here: 

**Desktop- With advertising image**
![desktop-image](https://user-images.githubusercontent.com/4862573/29964449-abcd93fc-8f3c-11e7-862e-d15d633f0422.png)

**Desktop- No image- just icon ?**
![desktop-textonly](https://user-images.githubusercontent.com/4862573/29964488-cb80a324-8f3c-11e7-93f9-759c3ad6c442.png)

**On mobile, hide verison**
![mobile-hide](https://user-images.githubusercontent.com/4862573/29964513-d8db0c1c-8f3c-11e7-9254-befab7fe5717.png)

**Mobile - Expand to show content** 
![mobile-expand](https://user-images.githubusercontent.com/4862573/29964517-da4bae12-8f3c-11e7-8d74-f666d196c766.png)

**Comment by johngruen** [comment]
@fangshih these need to be simper and should not cover the page image content. 

The core purpose of Screenshots is to share shots, and i don't want to cover up content with advertising since that's counter to the primary goal. 

Let's use the dimensions of cards in 57 new tab UI and put it next to the image rather than over top. If it makes things easier we can simply hide these ads on mobile viewports for the first round.

Remember, this is an MVP. Let's get the basic feature in and then elaborate later.

**Comment by johngruen** [comment]
@fangshih sorry to be difficult. we need to turn something around here quickly b/c there's an engineering OKR to implement this feature in Q3.

**Comment by youwenliang** [comment]
@johngruen 
![1 2 promotional panel desktop with image update](https://user-images.githubusercontent.com/8919308/30009806-b20f4616-915d-11e7-9ee4-33b8ac956b72.png)
Do you mean something like this?

Fang is out sick today so I'll try to provide the measurement for implementation today.

**Comment by fangshih** [comment]
We've updated smaller version, and also place it right next to the screenshot without cover it.  
![first copy 6](https://user-images.githubusercontent.com/4862573/30044703-85c58712-9231-11e7-8f82-2280159c2cce.png)

**Comment by 6a68** [comment]
@fangshih Hi, the spec doesn't show what to do when the window and image sizes vary. For instance, right now, large images are scaled to fill the screen. The spec doesn't show what to do if the window doesn't have enough room to show the ad and the image side by side. Should the main image flex to keep the ad in view? Should the ad be hidden if the window is too narrow?

**Comment by youwenliang** [comment]
@6a68 I was thinking something like this:

If the screen size is 1200px and above: (reserve 240px on the sides)
![desktop-promotion_1200px](https://user-images.githubusercontent.com/8919308/30795422-0aac539c-a200-11e7-992b-6e4ccc323937.png)

If the screen size is 819px and below, collapse into a button: (reserve 80px on the sides)
![desktop-promotion_819px](https://user-images.githubusercontent.com/8919308/30795423-0af5068c-a200-11e7-824c-f43277b5a817.png) (button icon is not final)

User can click the button to expand and see the normal ad:
![desktop-promotion_819px expand](https://user-images.githubusercontent.com/8919308/30795424-0af8d028-a200-11e7-91bd-3d11338cc237.png)

And not showing the add for mobile version (719px and below).
Let me know what you think!

**Comment by 6a68** [comment]
@youwenliang Yeah, that makes sense. What if we show just the text headline part of the ad when the screen's between 820 and 1200 px, and expand that on hover? I'll try that in a branch and ping you

**Comment by youwenliang** [comment]
@6a68 Sure, give it a try!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
