### ISSUE TITLE
The website link and the created time are no longer displayed on the saved shot preview page, if the expire date is changed 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3255]
[Affected versions]:
- Nightly 56.0a1
- Beta 55.0b13
- Screenshots 10.9.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Nightly or Beta browser using a new clean profile.
2. Navigate to any website and save a selection on the page.
3. Click the "expires in 14 days" button.
4. Change the expire date and click the "Save" button.
5. Observer the shot details.

[Expected result]:
- All the details are correctly redisplayed after the expired date was changed. 

[Actual results]:
- The website link and the created time is no longer displayed.

[Notes]:
- If the page is refreshed the details reapers.
- Here is a screen recording with the issue:
![details](https://user-images.githubusercontent.com/19226534/28825868-97ad506c-76d0-11e7-9ee4-2b53e58a09f0.gif)

**Comment by 6a68** [comment]
React doesn't seem to like how TimeDiffs contain different times, depending on whether they are rendered on the server (UTC) or client (local time).

**Comment by 6a68** [comment]
Here's a screenshot of a console error indicating React's displeasure:

<img width="760" alt="screen shot 2017-08-31 at 5 27 07 pm" src="https://user-images.githubusercontent.com/96396/29950618-da32db56-8e71-11e7-935e-a2541579542e.png">

**Comment by johngruen** [comment]
I put this back in triage because of a report by community member @peterbe

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on latest[ Screenshots 31.3.0 dev ](https://screenshots.dev.mozaws.net/homepage/install-test-local.html)version. Tested on latest Nightly (61.0a1) build on Windows 7 x64, Mac 10.13 and Arch Linux.
