### ISSUE TITLE
Use Fira Sans and standard Firefox website font family

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-services/screenshots#3266]
If you wanna use system fonts I would suggest to extend this list
```
html, body {
  font-family: SF UI Text, sans-serif;
}
```
into
```
html, body {
  font-family: 'Fira Sans', -apple-system, BlinkMacSystemFont, 'segoe ui', 'helvetica neue', helvetica, ubuntu, roboto, noto, arial, sans-serif;
}
```

*Note: edited to put Fira Sans at the front of the list*

**Comment by 6a68** [comment]
@johngruen Is there a Mozilla design guide we can lean on here?

Grepping for "font-family" turns up a ton of different font-family statements:

```sh
jhirsch-35282:mozilla-services-screenshots jhirsch$ ack font-family server/ static/
server/src/pages/homepage/view.js
8:    font-family: SF UI Text, sans-serif;
131:      font-family: Fira Sans,sans-serif;

static/css/inline-selection.scss
268:  font-family: sans-serif;
382:  font-family: -apple-system, BlinkMacSystemFont, sans-serif;

static/css/metrics.scss
2:  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;

static/css/onboarding.scss
18:  font-family: -apple-system, BlinkMacSystemFont, sans-serif;

static/css/partials/_base.scss
13:  font-family: -apple-system, BlinkMacSystemFont, sans-serif;

static/css/settings.scss
17:  font-family: SFUIDisplay-Regular, sans-serif;
23:  font-family: SFUIText-Bold, sans-serif;
44:    font-family: SFUIDisplay-Semibold, sans-serif;
52:    font-family: SFUIDisplay-Regular, sans-serif;

static/css/styles.scss
15:  font-family: sans-serif;
60:  font-family: sans-serif;
245:  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
309:  font-family: sans-serif;

static/homepage/css/help.css
2:  font-family: sans-serif;

static/homepage/css/style.css
8:  font-family: -apple-system, BlinkMacSystemFont, sans-serif;

static/homepage/install-test-local.html
7:        font-family: sans-serif;

static/img/landing-screenshots_image_02.svg
175:                                    <text id="SAVE" font-family="SFUIText-Semibold, SF UI Text" font-size="16" font-weight="500" fill="#FFFFFF">

static/img/landing-screenshots_image_03.svg
66:                                                <text id="My-Shot" font-family="SFUIText-Regular, SF UI Text" font-size="10" font-weight="normal" line-spacing="12">
74:                                                <text id="My-Shot" font-family="SFUIText-Regular, SF UI Text" font-size="10" font-weight="normal" line-spacing="12" fill="#3E3D40">
89:                                                <text id="My-Shot" font-family="SFUIText-Regular, SF UI Text" font-size="10" font-weight="normal" line-spacing="12" fill="#3E3D40">

static/img/landing-screenshots_image_04.svg
236:                                        <g id="SAVE" transform="translate(19.000000, 8.000000)" font-size="16" font-family="SFUIText-Medium, SF UI Text" fill="#FFFFFF" font-weight="400">
277:                                <g id="https://screenshot.f" transform="translate(12.000000, 15.000000)" font-size="19" font-family="FiraSans-Medium, Fira Sans" fill="#4A4A4A" font-weight="400">

static/img/question-mark.svg
56:       style="font-size:400.00000px;font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;text-align:start;line-height:125.00000%;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:0.037383176;stroke:#000000;stroke-width:4.1000000;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1.0000000;font-family:Arial;stroke-miterlimit:4.0000000;stroke-dasharray:none"

**Comment by 6a68** [comment]
I'm not sure what to do about the font declarations in the SVG files, but this does explain why the onboarding images are weirdly shown in a generic serif font on my mac:

<img src="https://screenshots.firefoxusercontent.com/images/08c602c7-e420-4793-b2cc-b33bcf16a7e4.png" height="150">

<img src="https://screenshots.firefoxusercontent.com/images/86eb0384-72ee-4db0-b61e-a8be907e3795.png" height="150">

<img src="https://screenshots.firefoxusercontent.com/images/9b9bb94c-808f-4ff7-9bb4-6a1f1ac572b1.png" height="150">

**Comment by ChenMorpheus** [comment]
@aminalhazwani We know Firefox Design System defines Fira Sans as the primary font family for websites design. However, could you let us know the reason behind? While we were working on these sites, we found out that Fira is a bit decorative than other system fonts, so it might not be that suitable for paragraphs. Besides, for most of the websites, they use a combination of various font-family to create a particular feeling for their product. As a result, we suggest revisiting the decision and creating more flexibility for the typography of web design.

**Comment by aminalhazwani** [comment]
hey @chenmorpheus thanks for the feedback! We opt for Fira Sans for multiple reasons. One is that currently the use of system font on the web is not very reliable [yet](https://www.w3.org/TR/css-fonts-4/#system-ui). 

Another possible issue that we outlined is the combination of static assets and web typography. Using a unique web font allows you to cohesively align both visuals and typography (Fira Sans vs San Franscisco in the screenshot below).

<img width="968" alt="screen shot 2017-08-08 at 2 00 05 pm" src="https://user-images.githubusercontent.com/1721875/29071343-7309b12e-7c43-11e7-80e4-da55432cf163.png">

On a similar topic Fira Sans enables you to combine body of copy with body of code coherently thanks to Fira Mono, no matter the platform.

Regarding your concerns on readability we can assure you that seen the vast use of Meta (which Fira shares many aspects and details with) there aren't problems with its use in bodies of text. Actually thanks to its design (like the stronger difference between and uppercase 'i' and a 'l') makes it ideal for longer paragraphs. 

So, these are some of the reasons that drove us to this recommendation. We will anyway collect your feedback and forward it to @pwalm who is currently taking care of the web side of Photon Design System.

Could you point us to web properties that use more than one font family? Many thanks!

**Comment by 6a68** [comment]
I pushed some updates before I caught the additional discussion here. @johngruen let me know if we do or don't want fira sans as the font, and I can revert to the old commit as needed
