### ISSUE TITLE
If you delete a saved shot from "My Shots" page, the next one disappears after reordering

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3267]
[Notes]:
- Probably this is a regression from [#3141](https://github.com/mozilla-services/screenshots/pull/3141). 

[Affected versions]:
- Nightly 56.0a1
- Screenshots 12.0.4794

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pre is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.
- Have multiple shots already saved on the profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Delete the one shot.
3. Observe the browser behavior.

[Expected result]:
- The shot is successfully deleted and the rest of the shots are correctly reordered.

[Actual results]:
- The shot is successfully deleted, but the next one disappears after reordering.

[Notes]:
- If the page is refreshed, the saved shot reappears.
- Here is a screen recording with the issue:
![deleted](https://user-images.githubusercontent.com/19226534/28922652-b32570b0-7863-11e7-936e-27ff511f6d83.gif)

**Comment by johngruen** [comment]
This seems bad

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev and stage servers. Marking as verified.
