### ISSUE TITLE
Header / footer links are blue on shots page

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3268]
Is this intentional? 

header on shots page:

<img src="https://screenshots.firefoxusercontent.com/images/6dd331eb-7050-4177-9d44-2f3f744e683f.png" height="100">

footer on shots page:

<img src="https://screenshots.firefoxusercontent.com/images/328ddfa2-75f3-419b-a0d6-6e1d97b88f20.png" height="80">

**Comment by wresuolc** [comment]
Let's do whatever is on the spec
