### ISSUE TITLE
DOMContentLoaded of 7+ seconds on My Shots

### ISSUE THREAD

**Issue by ckarlof** [mozilla-services/screenshots#3281]
I only have about 7-8 shots and this seems slow. The impact is that My Shots feels like an unresponsive experience and page. 

<img width="740" alt="screen shot 2017-08-04 at 2 11 43 pm" src="https://user-images.githubusercontent.com/2365255/28987187-1d8e4484-791f-11e7-8544-cd071edc99cf.png">

**Comment by ckarlof** [comment]
To be more accurate, the original request for /shots takes about 6.7s to return, so the bulk of the time seems to be on the server. 

<img width="1665" alt="screen shot 2017-08-04 at 2 25 49 pm" src="https://user-images.githubusercontent.com/2365255/28987623-db710828-7920-11e7-991b-ca2418ceb147.png">

**Comment by 6a68** [comment]
Seems fixed by #3374, closing. @ckarlof please reopen if you're still seeing load times >1sec

**Comment by ckarlof** [comment]
👍
