### ISSUE TITLE
Create thumbnail of shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3282]
We store just the full-resolution shot, which means that My Shots shows really large images as thumbnails. We should generate a thumbnail on shot generation.

This requires:

- [ ] Generating a thumbnail version of the shot
- [ ] Adding a thumbnail parameter to the shot JSON
- [ ] Making sure that thumbnail is moved to S3
- [ ] Making sure the thumbnail is managed like other S3 images (in the images table, etc)

Probably some work on clipRewrites is in order, as it's not very good at finding images in multiple locations in the shot object.

**Comment by 6a68** [comment]
What if we do this on the server instead? We could still get this done for 55. Might be a good excuse to bring in a work queue, too.

**Comment by ianb** [comment]
Oh I hate work queues, so *I* am not looking for any excuses there. But yeah...

As long as the server updates the shot, and selects shots that are missing thumbnails, then the add-on could eventually add the thumbnail and the worker will just have less to do.

**Comment by chenba** [comment]
This sounds like a dup of #1896.
