### ISSUE TITLE
Drop the code that uses `extensions.screenshots.system-disabled`

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3283]
This pref did what it was supposed to, let's whack it.  This should land in Nightly in our next version (soon is good) and we should ask for an uplift to Beta also.  This will put our Nightly and Beta audiences at 100%.

**Comment by 6a68** [comment]
Done in nightly, pending beta uplift. https://bugzilla.mozilla.org/show_bug.cgi?id=1386333

**Comment by 6a68** [comment]
Uplifted into beta! Closing
