### ISSUE TITLE
Clean out unused localization keys

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3287]
I know at least these items are probably not on the site anymore:

```
homePageLegalLink = Legal
homePagePrivacyLink = Privacy
homePageTermsLink = Terms
homePageCookiesLink = Cookies
```

**Comment by 6a68** [comment]
@Pike Do you know of any l10n linting tools that can detect unused keys?

**Comment by Pike** [comment]
Nope, don't.

For declarative use of l10n apis, you can more or less guess. In Firefox, there's a mystery called chrome registry that makes it rather funky to find out which files at runtime match source files. Once you do know the files, it's not all that hard.

The real challenge is programmatic access to l10n APIs, and in those cases we actually also deal with computed keys.

Which means that we need a full static analysis of the program to get full coverage.
Alternatively, you'd need a complete test coverage, and prove that to some relevevant extent.

The hard edge cases made us never really follow up on that. I tried with https://bugzilla.mozilla.org/show_bug.cgi?id=1203547 for mozilla-central, but never got to the state that I was seeing that become a program that can be sustained.

**Comment by 6a68** [comment]
@Pike Cool, figured I'd ask

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
