### ISSUE TITLE
Add 'bump locale coverage' note to docs/export-to-firefox.md

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3296]
We never pushed PBM error strings into 10.10, and I would like to ensure such an omission never happens again. 

Let's ensure we always pull latest strings into our deployment branch before tagging releases.

**Comment by flodolo** [comment]
Side note: it might not be a trivial update. For example, v10.10.0 and master diverged, with one string existing only in the branch, replaced by another in master (terms and conditions link)
