### ISSUE TITLE
Implement upper limit for number of shots in a single account

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/screenshots#3320]
I'm wondering if we should have an upper limit for how many shots a single user can keep in their account, to prevent screenshots from being used as a generic image storage service. This limit can be high, like 1,000 or 5,000 images, which regular users probably would never reach.

Maybe a good start would be to evaluate the average number of images across all accounts.

**Comment by ianb** [comment]
We do track this on the [metrics page](https://screenshots.firefox.com/metrics/); current values:

![image](https://screenshots.firefoxusercontent.com/images/5f339934-5274-4fda-8e30-f03fed4123b5.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
