### ISSUE TITLE
Review indexes in database

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3334]
We were missing an important index for My Shots (on data.deviceid), there might be other important things to be indexing. We should review `schema.sql` for other missing indexes.

**Comment by wresuolc** [comment]
We should review the logs of database timings

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
