### ISSUE TITLE
Investigate slow page load times on production

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#3337]
I think somebody cited a 6s page load time. That seems high, but I'm having some issues w/ debugging since Lighthouse only works on Chrome, and if I go to https://screenshots.firefox.com/shots in Chrome/Lighthouse, it just does a redirect to the marketing home page.

**Comment by pdehaan** [comment]
I imagine this would cause at least _some_ performance problems in production:

- _"Warning: It looks like you're using a minified copy of the development build of React"_ #2811

**Comment by pdehaan** [comment]
Here are my results from the [**sonar**](https://github.com/sonarwhal/sonar) CLI tool (for the marketing homepage):

```
 npm run sonar https://screenshots.firefox.com

> sonar-test@1.0.0 sonar /Users/pdehaan/dev/tmp/del/sonar-test
> sonar "https://screenshots.firefox.com"

✖ Finishing...
https://screenshots.firefox.com/
                    Error    'x-ua-compatible' header was not specified                                     highest-available-document-mode
line 1    col 16    Error    <html> element must have a lang attribute                                      axe
line 1    col 500   Error    Protocol relative URL found: //www.google-analytics.com/analytics.js           no-protocol-relative-urls
line 1    col 783   Error    Zooming and scaling must not be disabled                                       axe
line 3    col 773   Warning  Consider avoiding viewport values that prevent users from resizing documents.  html-checker
line 447  col 241   Error    Links must have discernible text                                               axe
line 447  col 953   Error    Elements must have sufficient color contrast                                   axe
line 447  col 1010  Error    Elements must have sufficient color contrast                                   axe
line 447  col 3337  Error    Elements must have sufficient color contrast                                   axe
line 447  col 3468  Error    Elements must have sufficient color contrast                                   axe
line 447  col 3597  Error    Elements must have sufficient color contrast                                   axe
line 447  col 3750  Error    Elements must have sufficient color contrast                                   axe
line 447  col 3900  Error    Elements must have sufficient color contrast                                   axe
✖ Found 12 errors and 1 warning

✖ Found a total of 12 errors and 1 warning
Exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonar-test@1.0.0 sonar: `sonar "https://screenshots.firefox.com"`
npm ERR! Exit status 1
```

Nothing _too_ interesting there... I'll try rerunning this against a shot download page and see if that gives us any better indications.

**Comment by pdehaan** [comment]
Random shot page: https://screenshots.firefox.com/JPczqrIoFuiCWyhV/screenshots.firefox.com

<img width="1127" alt="lighthouse_report_viewer" src="https://user-images.githubusercontent.com/557895/29282279-1b7097dc-80d7-11e7-9c34-1d87897deeba.png">

... and here's the full report (saved as PDF, sorry): [Lighthouse Report Viewer.pdf](https://github.com/mozilla-services/screenshots/files/1222873/Lighthouse.Report.Viewer.pdf)

**Comment by 6a68** [comment]
The leading source of latency on the production My Shots page was a database query that scanned the entire devices table before rendering the shots. That's now fixed in #3374 and pushed to prod, where page times seem to have significantly improved (for me, down to half a second from around 5-6 seconds).

Once we have My Shots serving thumbnails, not full-size images (#1896), and once the servers are upgraded to support http/2 (#3382), we should be good to move on to web perf optimization.

I'm going to leave this open until a perf optimization plan is published.

**Comment by johngruen** [comment]
@pdehaan can you rerun this test?

**Comment by 6a68** [comment]
> I'm going to leave this open until a perf optimization plan is published.

Details and plans outlined here, though not yet in published blog post format:

https://public.etherpad-mozilla.org/p/screenshots-perf-planning

I'm going to close this for now. @pdehaan, feel free to open a new bug if you see perf concerns.
