### ISSUE TITLE
Update 'pg' dependency

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/screenshots#3338]
https://github.com/mozilla-services/screenshots/blob/cac907606b825624049f1e657d9c34e57189d882/package.json#L35

**Comment by ianb** [comment]
Dup of #3234

**Comment by pdehaan** [comment]
@ianb could we update to `pg@6.4.2`? It seems to be breaking our CI builds currently.

**Comment by pdehaan** [comment]
Fixed in #3339
