### ISSUE TITLE
Screenshots is not using pageAction in Nightly

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3342]
Sometime recently, I think due to changes in Firefox, Screenshots has reverted back to using a toolbar button and is not showing the pageAction.

The Library still contains the Screenshots item.

/cc @0c0w3

**Comment by 0c0w3** [comment]
You guys haven't merged the changes from #3239 into mozilla-central yet. There's discussion about it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1366041  Could you please do that ASAP?

**Comment by ianb** [comment]
I'm getting ready to do an export, but I'd be exporting this regression. I chatted with @gijsk on #screenshots and he had a theory

**Comment by 0c0w3** [comment]
What regression?
