### ISSUE TITLE
Metadata on screenshots.f.c is in Arabic

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3350]
Probably because Arabic is the first thing in the list?

To reproduce:
1) Paste https://screenshots.firefox.com/#hello into slack

![screenshot-2017-8-15 kirby mozilla slack](https://user-images.githubusercontent.com/16946141/29329220-fe84c110-81a9-11e7-8c6b-93674734c555.png)

**Comment by ianb** [comment]
Probably the same thing as #3231 – though since we're seeing a UA that actually requests without an Accept-Language header, we should probably raise the priority on this (I only saw it in testing before)

**Comment by wresuolc** [comment]
duplicate of #3231
