### ISSUE TITLE
[v16.0] The blue circle appears on Screenshots icon only if the button is clicked and the Onboarding tour is not completed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3356]
[Affected versions]:
- Nightly 57.0a1
- Screenshots 16.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Nightly try build with Screenshots 16.0 enabled on a new clean profile.

[Steps to reproduce]:
1. Start the Nightly try build with the profile from prerequisites.
2. Navigate to any website (eg: https://www.wikipedia.org/).
3. Click the "Page Action" button from URL bar.
4. Observe the Screenshots icon.
5. Click the Screenshots icon and refresh the page.
6. Click again the "Page Action" and observe the Screenshots icon.

[Expected result]:
Step4 & Step6: The Screenshots icon has a blue circle with a black star inside.

[Actual results]:
Step4: The blue circle with a black star is not displayed on the Screenshots icon.
Step6: The Screenshots icon has a blue circle with a black star inside.

[Notes]:
- I haven't got the chance to test this on Mac Os, but probably is also reproducible.
- Here is a screen recording with the issue:
![blue circle](https://user-images.githubusercontent.com/19226534/29360808-4de5b69a-828d-11e7-9cf6-df38c49d8efc.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I did more investigation and it seems that is not reproducible on Mac Os and Windows 10. 
But, is reproducible on Windows 7 and Windows 8.

**Comment by wresuolc** [comment]
We'll remove this in https://github.com/mozilla-services/screenshots/issues/3542
