### ISSUE TITLE
Blank tab is displayed after sharing on Facebook a saved shot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3357]
[Notes]:
- We have the same issue on Test Pilot (see: [#2593](https://github.com/mozilla/testpilot/issues/2593)).

[Affected versions]:
- Firefox 57.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly  build with Screenshots.
- You are already logged on Facebook.

[Steps to reproduce]:
1. Start the Nightly try build with the profile from prerequisites.
2. Navigate to any website (eg: https://www.wikipedia.org/).
3. Save a selection on the page.
4. Click the Share button and click on the "Facebook Share" button.
5. Click on "Post to Facebook" button from the bottom right corner of the browser window.
6. Observe the behavior of the page.

[Expected result]:
- Facebook page should be closed or the user should be redirected to Facebook Home page.

[Actual results]:
- The Facebook tab remains opened but blank.

[Additional Notes]:
- Here is a screen recording with the issue:
![facebook share1](https://user-images.githubusercontent.com/19226534/29366133-d696cda8-82a1-11e7-8126-009c015dbf36.gif)

**Comment by ianb** [comment]
To fix this we need to change the `<a href...>` that opens Facebook to something that uses `window.open(...)` – then when the share is complete Facebook will call `window.close()` and everything should work.

**Comment by SoftVision-CosminMuntean** [comment]
I have tested this issue on latest Nightly (58.0a1) build using Screenshots 22.0.0 dev version and the issue is no longer reproducible. Marking as verified.
