### ISSUE TITLE
What should we do with old, pre-55 page shot users?

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3368]
Before we can shutdown old page shot infrastructure we should do something with the users who still have page shot installed.  What should we do?

**Comment by wresuolc** [comment]
Let's turn this off on thanksgiving 🦃

**Comment by wresuolc** [comment]
No more needs product.  We decided to just turn this off.

**Comment by ianb** [comment]
#3613 has the work to be done
