### ISSUE TITLE
Expose some configuration in __version__

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3377]
While some configuration is secret, many others are not. Being able to confirm configuration would be helpful. The configuration included should be a whitelist.

**Comment by 6a68** [comment]
@oremj What config would be useful and safe to expose via the __version__ endpoint?

**Comment by 6a68** [comment]
Going to WONTFIX this for now. Let's reopen if QA or ops needs specific configuration exposed via this endpoint.

**Comment by SoftVision-CosminMuntean** [comment]
From the QA point of view, I think we have enough information for now. 
Thanks!
