### ISSUE TITLE
On dev, on hover the delete/share disappear

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3378]
I haven't tested this elsewhere:

![image](https://user-images.githubusercontent.com/44390/29525814-7d8076f4-8659-11e7-8cd9-2cfa75ae1e45.png)

On hover the button turns into a grey box.

**Comment by johngruen** [comment]
Unable to repro in prod, i'll try locally later/

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on dev and stage servers on Windows and Mac OS.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is now also reproducible on production after deploy. We should fix it as soon as possible in the next release.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on dev server and is no longer reproducible. Marking as verified.
