### ISSUE TITLE
Enable http/2

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3382]
Reasons to switch to http/2:
- http/2 should improve performance vs http 1.1
- website performance optimizations differ for http 1.1 vs http/2, so it'd be better to switch now, before lots of optimization begins

**Comment by relud** [comment]
This requires switching to an ALB, which requires some work on my part. I need to do some cost analysis work on my end before I can start working on this, and get approval from my manager to spend time getting ALBs to work.

**Comment by relud** [comment]
okay, ALBs are reasonably priced, and adding support didn't take too long, i'm going to start testing them in stage:

https://github.com/mozilla-services/cloudops-deployment/pull/1070

**Comment by relud** [comment]
fixed
