### ISSUE TITLE
placement of screenshot option in context right-click menu

### ISSUE THREAD

**Issue by BMCwebdev** [mozilla-services/screenshots#3383]
Please please please move the Take Screenshot up from the last item on this list. As a developer I am 100% conditioned for "inspect element" to be in this position. I had to turn off take screenshot until the placement is changed.

**Comment by johngruen** [comment]
Web Extensions put context items at the bottom of the context menu. I'd also like to see this change, but the bug should be filed in bugzilla, I'll file it in a moment.

**Comment by BMCwebdev** [comment]
Thank you johngruen!

**Comment by johngruen** [comment]
@BMCwebdev hey, you can track the issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1393108

Going to close this since there's nothing actionable to be done in the Screenshots codebase.

Thanks for your report!
