### ISSUE TITLE
[FxA] Disconnect button is not working

### ISSUE THREAD

**Issue by niharikak101** [mozilla-services/screenshots#3386]
It should disconnect the user account from the device, but it's doing nothing.

**Comment by SoftVision-CosminMuntean** [comment]
It works for me. At least on Windows using Screenshots dev server. I will also check on Mac later today.

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the button also works for me on Mac Os. So, probably the issue is reproducible locally with the latest changes.
