### ISSUE TITLE
[Enhancement][FxA]: The "Connect" and "Disconnect" buttons should have a hover effect

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3389]
[Affected versions]:
- Nightly 57.0a1
- Screenshots 17.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pre is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a new tab.
2. Click the Screenshots icon from browser toolbar.
3. Hover and observe the "Connect" button.
4. Click the "Connect" button and sign in.
5. Hover and observe the "Disconnect" button. 

[Expected result]:
- The "Connect" and "Disconnect" buttons have a hover effect. 

[Actual results]:
- The "Connect" and "Disconnect" buttons doesn't have any hover effect.

**Comment by niharikak101** [comment]
@youwenliang has a PR open with a bunch of UI changes that include the hover effects: https://github.com/mozilla-services/screenshots/pull/3396

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this behavior and the "Sign In" and "Disconnect" buttons have a hover effect. Marking as verified.
