### ISSUE TITLE
FHR is going away, we need to switch add-on metrics to respect a user's Telemetry preferences

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3390]
Two interesting things are happening:
1. FHR is being deprecated: https://bugzilla.mozilla.org/show_bug.cgi?id=1352497 
2. The FF Data prefs are being redesigned and simplified (cf Nightly)

In order to be future-safe we need to switch the add-on to look at the user's Telemetry pref, rather than FHR.

**Comment by georgf** [comment]
What data prefs are you using now?
What behavior do you need?

[Our docs](http://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/internals/preferences.html) describe what we use now.
([Temp docs link while build is broken](http://gecko-docs.mozilla.org.s3.amazonaws.com/toolkit/components/telemetry/telemetry/internals/preferences.html))

**Comment by georgf** [comment]
FHR was killed a long time ago.
"datareporting.healthreport.uploadEnabled" is still the main data upload/collection pref, there is no need to move off it.
"toolkit.telemetry.enabled" is the pref that tells you whether "extended" (now "pre-release") data can be recorded.

I don't think you need to change anything and am currently surveying how these prefs are used.

**Comment by 6a68** [comment]
Based on @georgf's comments, looks like we are good to close this.
