### ISSUE TITLE
Paginate My Shots page

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3391]
Thought I filed this bug, but maybe not.

We currently load every shot you've ever shot in the shots page. Let's cap it at 10 with a button to click for more. Infinite scroll won't work because we put important stuff in the footer (like the link to delete all your stuff).

**Comment by youwenliang** [comment]
@wresuolc I think people won't have too many pages for their shots so a previous page and next page button should do the job. Here's my proposal:
![1 1 shot index page with pagination](https://user-images.githubusercontent.com/8919308/29954803-1bcb09e4-8f0d-11e7-92a3-c2a48938893b.png)
![1 2 pagination](https://user-images.githubusercontent.com/8919308/29954805-1dbb79b4-8f0d-11e7-9559-6cd409ec6013.png)

**Comment by youwenliang** [comment]
@chenba Here's the measurement if you needed:
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FFSS_Pagination/#artboard1

**Comment by chenba** [comment]
Should the page scroll up to the top on page nav?

**Comment by youwenliang** [comment]
@chenba yes!
