### ISSUE TITLE
Non a-shot pages aren't reporting page loading times

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3394]
![screenshot-2017-8-23 site speed page timings - analytics 360](https://user-images.githubusercontent.com/16946141/29636839-016cd558-8807-11e7-86c4-22aed13dfa9d.png)

These two pages (home page and /shots) are regular web pages.  We should be able to see page load timings.

**Comment by chenba** [comment]
Weird.  Doesn't look like those pages are rendered any differently.

**Comment by chenba** [comment]
This is no longer an issue.  The latest data is showing page timings for `/` and `/shots`.

**Comment by chenba** [comment]
@wresuolc This can be closed?
