### ISSUE TITLE
Bring back add-on user timings

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3395]
![screenshot-2017-8-23 site speed user timings - analytics 360](https://user-images.githubusercontent.com/16946141/29636928-4de4b3d8-8807-11e7-9c4b-61afc270e416.png)

Ian says these were all just Page Shot uses anyway, so they weren't great data, but they are interesting numbers to have.  Is it possible to re-implement them in Screenshots?

**Comment by chenba** [comment]
Could someone point me to some reading material or elaborate on this?  I know it's GA, but what are we capturing?

**Comment by ianb** [comment]
The google-analytics.js script is supposed to save a lot of page load information automatically: https://support.google.com/analytics/answer/1205784?hl=en

For some unknown reason it is not. To test this will require access to our account, you could ask with a ticket here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Websites&component=Web%20Analytics (do you have an @mozilla.com email?) – though with config we could also use some test account.

**Comment by wresuolc** [comment]
Lemme try to get you access...

**Comment by wresuolc** [comment]
@chenba has confirmed he can access 🐻

**Comment by chenba** [comment]
Previously timing data was gathered in the addon with https://github.com/mozilla-services/screenshots/blob/86c86635dbbc7ccab48031c5b1ab55809e62af73/addon/lib/timing.js#L16 and https://github.com/mozilla-services/screenshots/blob/86c86635dbbc7ccab48031c5b1ab55809e62af73/addon/lib/timing.js#L57, and sent with https://github.com/mozilla-services/screenshots/blob/86c86635dbbc7ccab48031c5b1ab55809e62af73/addon/lib/req.js#L86  There was a `/timing` endpoint on the server to receive this data and then send it over to GA.

The code in the addon was removed at https://github.com/mozilla-services/screenshots/commit/344a7287ad0120a94a55a8a8697fc6325018f9f6 and then the `/timing` endpoint was removed for #2428.

**Comment by chenba** [comment]
I feel like the work in #3673 obviates the need for this issue.

**Comment by chenba** [comment]
I'm closing this because it's pretty a much a dup of #3673.  We can open new issues for any additional user timing we want to measure.
