### ISSUE TITLE
[FxA]Firefox accounts continues to sync a signed out Firefox profile

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3397]
[Notes]:
- If you delete a shot from the signed out profile, it will also be removed on the signed in profile (Screen recording: https://goo.gl/aie1m3). 
- Also, the saved shots from the signed out profile are synchronized as non-owner ones.

[Affected versions]:
- Nightly 57.0a1
- Screenshots 17.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- Have a custom Screenshots dev build installed on two different Firefox profiles.
- You are logged in on both profiles with the same Firefox account.
- Have multiple saved screenshots in the account.

[Steps to reproduce]:
1. Start two instances of Firefox with the profiles from prerequisites.
2. Navigate to "Settings" page on both profiles.
3. Log out from one of the opened profiles.
4. On the other profile, navigate to any website and save a shot.
5. Return to the profile from step 3 and navigate to "My Shots" page.
6. Refresh the page and observe the saved shots.

[Expected result]:
- The saved shot from the other profile is not displayed because you are not logged in and the shots can not be synchronized.

[Actual results]:
- The saved shot from the other profile is wrongly synchronized even if you are not logged in.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/282fjp

**Comment by niharikak101** [comment]
@SoftVision-CosminMuntean could you retest this with the latest changes?

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and it seems that is no longer reproducible. 

But, I think that the fixed caused a regression. In the current behavior the shots taken while signed in are removed from the account after disconnecting (see issue #3437).
