### ISSUE TITLE
[Annotations] The "Save" button is not working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3405]
[Affected versions]:
- Nightly 57.0a1
- Screenshots 17.0.1895

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- Have a custom Screenshots dev build installed on a clean Firefox profiles.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Click the Screenshots icon from browser toolbar and save a selection on the page.
3. Click the "Edit Image" button.
4. Edit the image and click the "Save" button.
5. Observe the browser behavior.

[Expected result]:
- The edited image is successfully saved.

[Actual results]:
- Nothing happens.

[Notes]:
- Here is a screen recording with the issue:
![save edited](https://user-images.githubusercontent.com/19226534/29717464-f133a290-89b7-11e7-9ec6-476fdee87c77.gif)
- Here is a screen shot with browser console errors:
![save error](https://user-images.githubusercontent.com/19226534/29717473-f7d04054-89b7-11e7-8366-dad9dd9558a2.png)

**Comment by chenba** [comment]
Is this still a bug?  I've been able to save annotated images.

**Comment by SoftVision-CosminMuntean** [comment]
I can still reproduce this issue using Screenshots dev 23.0.0 version from here: https://screenshots.dev.mozaws.net/homepage/install-test-local.html

When I click the "Save" button I get the following error:
![save](https://user-images.githubusercontent.com/19226534/32281004-35eac1e0-bf26-11e7-86d8-f9fc6ac144b7.png)

**Comment by ianb** [comment]
This needs to be verified in dev: https://screenshots.dev.mozaws.net/homepage/install-test-local.html

**Comment by SoftVision-CosminMuntean** [comment]
The "Save" button seems to work, but the image is no longer displayed in "Edit" mode and the it's wrongly saved. I have logged this issue in #3848. 
I will verify again this issue after #3848 will be fixed, to make sure that the "Save" functionality works as expected.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Screenshots 28.0.0 dev version and is no longer reproducible. The "Save" button works and the image is displayed.
