### ISSUE TITLE
Consider adding ability to selectively censor sensitive content

### ISSUE THREAD

**Issue by emmyemi** [mozilla-services/screenshots#3410]
Many times when I take a screenshot of a web page, mildly sensitive information such as usernames, profile images, etc., will also be captured. In order to prevent this, it would be helpful to be able to censor individual HTML elements on a page before saving the shot. A bit of how I believe this could work below.

### Text:

- `background: currentColor` in CSS should work perfectly fine for most cases. [Example](http://i.imgur.com/nkywv48.png)
- If a user wants to block only a certain part of a paragraph, it may be best to surround the selected text in `span` tags with the above CSS property attached. [Example](http://i.imgur.com/qHh6HS6.png)

### Images:

- Images can be either [blurred using `filter: blur()`](http://i.imgur.com/LfH7ijI.png) or [washed out using `filter: contrast(0)`](http://i.imgur.com/Z6Opoz9.png).
- Background images can be replaced through CSS as well—my first thought is that this can be done by adding a special class and replacing the `background` property with a solid color, but perhaps there's a better way.

### Finer control:

- For cases where censoring elements or selected text doesn't suffice, a simple tool to place an absolutely positioned `div` over an area should work.

**Comment by johngruen** [comment]
@emmyemi, we're working on some annotation tools that we believe will cover this use case. They're already landed in the latest development versions!
