### ISSUE TITLE
build and run server on travis-ci

### ISSUE THREAD

**Issue by erikvold** [mozilla-services/screenshots#342]

**Comment by erikvold** [comment]
with the server part built and running we can then run tests against it on travis, and run add-on tests against it on travis..

**Comment by ianb** [comment]
We are now building the server on Travis, but leaving open for us to do actual tests of the server.

**Comment by pdehaan** [comment]
Per #2201/#2268, we added Circle-CI integration. Not sure if we still need this issue, or if this issue should be repurposed to run unit/smoke tests on Circle, and we file a new issue to remove Travis support since we don't need dueling CI services.

**Comment by ianb** [comment]
Per #2355 we're turning Travis off
