### ISSUE TITLE
Saving to disk always downloads to ~/Downloads

### ISSUE THREAD

**Issue by j605** [mozilla-services/screenshots#3420]
I have the preference "Always ask you where to save files" checked so I think it is intuitive that screenshots should also ask where it needs to be saved. If this is not possible, can you provide a way to set a different screenshot save location.

**Comment by ianb** [comment]
Note we just use the [WebExtension download API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download). It has a `saveAs` flag, which would trigger the behavior you want, but I'm not sure how we can decide how to set that flag.

Well, looking a bit, I see `browser.download.useDownloadDir` is the underlying about:config pref. We could share this pref with the add-on via bootstrap.js the same way we share the Telemetry pref.

Arguably the WebExtension should be able to choose the right action on its own. I opened [Bug 1394851](https://bugzilla.mozilla.org/show_bug.cgi?id=1394851) for this.

**Comment by 6a68** [comment]
@ianb What about using shift + click to trigger the "save as..." functionality, and regular click to save in the default spot?

**Comment by 6a68** [comment]
See also https://twitter.com/LOTNorm/status/905921790387605504

**Comment by johngruen** [comment]
See also reddit thread here: https://www.reddit.com/r/firefox/comments/731m54/screenshots_is_shipping_in_firefox_56/dnnyqfj/

> Regarding directory selection, the main reason I want to be asked where to save files is so that I can choose a different name for them.

This is a slightly different use case where the commenter want to name shots via their OS dialog on download.

**Comment by ianb** [comment]
See also ([Bug 1362448](https://bugzilla.mozilla.org/show_bug.cgi?id=1362448)): this should give us the WebExtension API support we need here.

**Comment by boomsya** [comment]
I want too change location folder for saving screens (because default folder on disk C:. I use primary SSD and i want to save screens on second HDD). Name of screen file it is no matter.
2 variants of this:
1. always ask destination folder
2. set folder in preferences

**Comment by ianb** [comment]
We should verify this in Nightly since the WebExtension bug has been closed.
