### ISSUE TITLE
Remove CustomizableUI.destroyWidget from bootstrap.js

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3424]
See also [this comment](https://reviewboard.mozilla.org/r/169252/#comment227274). We use ` CustomizableUI.destroyWidget(cuiWidgetID);` in bootstrap.js to remove the browserAction. Once we move entirely to a pageAction, we should simply remove all references to the browserAction.

**Comment by ianb** [comment]
Note this is creating the `this.widget is null` errors in the browser console.

**Comment by gijsk** [comment]
Is there a separate issue tracking the move to a pageAction?

**Comment by ianb** [comment]
After discussion we decided to simply remove the browserAction code (#3468). Closing this, as we won't bother fixing how we remove the button.
