### ISSUE TITLE
Build dev bundles in development

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3433]
With #3432 we are no longer building hybrid development/production bundles, but instead build production builds all the time. It would be better if we built production bundles in production, and development builds in development.

To do this we need to add a flag to `bin/build-scripts/bundle_dependencies` for a dev or production build. A dev build doesn't uglify, uglifyify, and has NODE_ENV=dev. Then we should use `bin/build-scripts/set_file` to actually control the bundles, and make the generated file (the one that contains the flag value) a dependency for all bundles. Then we should make sure in `bin/run-server` it is set to dev, and in `bin/release-version` it is set to production.

**Comment by 6a68** [comment]
Moving into 57 milestone, because non-debuggable JS is an obstacle for contributors

**Comment by chenba** [comment]
#3643 (PR of which has been merged) fixes part of this.
