### ISSUE TITLE
The new page action does not respect Firefox theme

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3436]
In the latest Nightly the Screenshots got move the page action menu. Unfortunately the screenshots item does not respect the style, when pinned into the addressbar. It's black, while the other actions are gray. Note the action icons are gray regardless of the Firefox theme (default or dark).

**Comment by johngruen** [comment]
There's an upstream bug for this already: https://bugzilla.mozilla.org/show_bug.cgi?id=1395284
