### ISSUE TITLE
[FxA] The shots taken while signed in are removed from the account after disconnecting

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3437]
[Notes]:
- After disconnecting, the saved shots remains in the guest account.

[Affected versions]:
- Nightly 57.0a1
- Screenshots 17.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- Have a custom Screenshots dev build installed on two different Firefox profiles.
- You are already logged on a Screenshtos FxA.

[Steps to reproduce]:
1. Open the Firefox with the profiles from prerequisites.
2. Navigate to any websites and save a selection.
3. Click the "My Shots" button from the corner of the page.
4. Click the "Settings" button and disconnect from the account.
5. Create another Firefox profile and connect to the Screenshots FxA with the previously account.
6. Navigate to "My shots" page and observed the saved shots.

[Expected result]:
- The saved shot from the first profile is synchronized and is correctly displayed on the second one.

[Actual results]:
- The saved shot from the fist profile is not displayed on the second one.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/39ZcVc

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Can you please check if this issue is still replicable? Thanks

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
