### ISSUE TITLE
Screenshots onboarding tour is launched after every Firefox restart, if Screenshots is used on "about:home" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3438]
[Notes]:
- This issue is not reproducible on latest Nightly build with Screenshots 16.1.0 due to the fact that the button is now displayed in Nightly "Page Action" which is not available on "about:home" page.
- This issue is not reproducible with Screenshots version 10.12.0 on Firefox (56.0b7) Beta and Firefox Release (55.0.3).
- If Screenshots 16.1.0 will be uplifted in Firefox Beta or release, this issue will be reproducible. 

[Affected versions]:
- Nightly 57.0a1
- Screenshots 16.1.0
- Screenshots 17.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any websites.
2. Click the Screenshots icon from browser toolbar.
3. Complete the the Screenshots onboarding tour.
4. Close the browser.
5. Start the browser and from "about:home" page click the "Screenshots" button.
6. Observe the browser behavior.

[Expected result]:
- You are redirected to the "My Shots" page.

[Actual results]:
- The Screenshots overlay is launched, even if it was already completed.

[Additional Notes]:
- The issue is not reproducible if the "When Firefox starts: Remember my windows and tabs from last time" option is set in "about:preferences" or with the "restart" command.
- Here is a screen recording with the issue:
![onboarding](https://user-images.githubusercontent.com/19226534/29879612-3b5b23e4-8dae-11e7-998d-ad37fdfa4ede.gif)

**Comment by johngruen** [comment]
This should never make it to release. Closing
