### ISSUE TITLE
Update slide image to match photon

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3443]
For 57 we need to update the asset seen in this slide so that the browser chrome looks like firefox 57

<img width="843" alt="screen shot 2017-08-31 at 9 58 17 am" src="https://user-images.githubusercontent.com/3323249/29927063-3526b5b2-8e33-11e7-88fa-bc2748133195.png">

**Comment by johngruen** [comment]
@fangshih

**Comment by fangshih** [comment]
Updated the browser chrome to firefox 57 look.
![img-onboarding-4 2x](https://user-images.githubusercontent.com/4862573/29953826-dd098368-8f05-11e7-86cb-7b2fb4f38cd9.png)

https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/Onboarding/%402x/img-onboarding-4%402x.png
