### ISSUE TITLE
Put mozilla eslint rules back in

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3450]
@Standard8 is looking at the problems we've encountered.

Commit 2d01ca1864006c0d0158edeff60a8984ec64a6b2 removed the use of the mozilla plugins; undoing that commit should put things back.

**Comment by Standard8** [comment]
I think I've tracked this down to a module dependency issue - I'm currently working on a patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1395879. Once that has landed, I'll get a new version published, which will hopefully work better.
