### ISSUE TITLE
Add support for editing or removing url data from the screenshot. 

### ISSUE THREAD

**Issue by dumptyd** [mozilla-services/screenshots#3460]
In the screenshot pages, the site on which the it was taken is shown and there's no way to change/remove that. Support for completely removing site data would be really nice as I don't always want people to know what site I took the screenshot on.

**Comment by saxicek** [comment]
I was thinking about more generic solution which would enable user to add some basic shapes to the image - lines, rectangles, text maybe. Basically what Lightshot extension provides. That would allow you to remove the URL using simple rectagle.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
