### ISSUE TITLE
[Nightly try build] The shots are not successfully saved

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3461]
[Notes]:
- This issue is only reproducible on the provided [Nightly try](https://treeherder.mozilla.org/#/jobs?repo=try&revision=ebbf0fb9993c0dd4e9dda94c4a8d4ecbc9e86cd7&selectedJob=127836481) build with Screenshots 18.0.0 installed.

[Affected versions]:
- Nightly try build 57.0a1
- Screenshots 18.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest [Nightly build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=ebbf0fb9993c0dd4e9dda94c4a8d4ecbc9e86cd7&selectedJob=127836481) with Screenshots 18.0.0 installed

[Steps to reproduce]:
1. Start the Nightly try build and navigate to any website.
2. Click the Screenshots button from Nightly "Page Action".
3. Perform a selection on the page and click the "Save" button.
4. Observe the saved shot preview page.
5. Click the "My Shots" button.
6. Observe the "My Shots" page.

[Expected result]:
Step 4. The shot is successfully saved and it's correctly displayed.
Step 6. The saved shot is displayed on the "My Shots" page.

[Actual results]:
Step 4. The shot is not displayed on the saved shot preview page.
Step 6. The saved shot is not displayed on "My Shots" page, the page is empty.

[Notes]:
- Also, the download is not working after the selection is saved.
- Here is a screen shot with browser console errors:
![saved shot](https://user-images.githubusercontent.com/19226534/30029729-14873f4e-9193-11e7-993a-e9c20f19d202.png)
- Here is a screen recording with the issue:
![nightly try build saved shots](https://user-images.githubusercontent.com/19226534/30029735-1ab2e95e-9193-11e7-9698-dd035ab58a50.gif)

**Comment by wresuolc** [comment]
@ianb could you look at this when you get back?

**Comment by ianb** [comment]
Ah, this is due to #3308 – the production server doesn't understand binary upload, so version 18 of the add-on requires version 18 of the server. We don't have any particular technique for the server to inform the client of its features right now.

We could just hold off on the add-on update until 18 goes to prod, or we could try to put something in the login process that would identify server features and account for that.

**Comment by ianb** [comment]
I think we should probably do #3481 and that would fix this bug as well.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue is no longer reproducible on the provided Nightly try build with Screenshots 19.0.0. Marking as verified.
