### ISSUE TITLE
Remove inline scripts

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3465]
It occurs to me that we probably don't need inline scripts. The JSON is kept in a non-js-script (and would stay there), but the script that reactruntime adds could be removed (and included directly in bundles I suppose).

**Comment by wresuolc** [comment]
Let's investigate if this would break support for older IE/Edge

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
