### ISSUE TITLE
Easy way to cancel screenshot without pressing ESC or initiating a selection

### ISSUE THREAD

**Issue by nkestrel** [mozilla-services/screenshots#3467]
There should be an easy way to cancel a screenshot using the mouse without having to start a selection or resort to the keyboard.

You can click the "Take a Screenshot" button to cancel but this is a bit awkward and now it is buried in the "Page actions" menu making it less visible and requiring more clicks.

A simple [x] close button on the initial selection overlay would be ideal.

**Comment by 6a68** [comment]
If we put a close button on the overlay, like at the top left corner, you wouldn't be able to start a screenshot from that part of the page.

**Comment by nkestrel** [comment]
It's no different to the existing buttons in the top right corner, which is also where a close button would be conventionally located.

Here's a quick mockup where I simply copied `#highlight-button-cancel` into `#myshots-all-buttons-container`.

![mockup](https://i.imgur.com/GUKzHyP.png)

With this you wouldn't need to have the prominent "Press ESC to cancel" since it a secondary means of cancelling and can be easily discovered.

**Comment by johngruen** [comment]
@chenmorpheus, could we get a UI treatment here. Metrics suggest a lot of people refresh the page which is suboptimal

**Comment by youwenliang** [comment]
Two proposals here:
https://mozilla.invisionapp.com/share/AMDTW758R

Option A with a cancel button in the center and option B with a cancel button on the top left corner using the same treatments as the top right action buttons.

I personally prefer option A since it's easier to reach and simple. Option B kind of stresses too much on the cancel button by making it the same hierarchy as the other action buttons.

**Comment by johngruen** [comment]
Let's do option 1. Can you add a measurement spec and then unassign yourself?

@ianb i think the event here would be `addon/cancel-selection/cancel-button`

**Comment by youwenliang** [comment]
Here's the measurement: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FFSS-3467/

**Comment by 6a68** [comment]
hmm, that measurement is a blank screen for me

**Comment by youwenliang** [comment]
@6a68 Hmm...I'm able to see the screen fine, anyway here's the screenshot of the screens:
<img width="1031" alt="screen shot 2017-10-25 at 3 12 35 pm" src="https://user-images.githubusercontent.com/8919308/31985348-5e6bc4e6-b997-11e7-9a59-c949a5bdf545.png">
<img width="1032" alt="screen shot 2017-10-25 at 3 12 49 pm" src="https://user-images.githubusercontent.com/8919308/31985349-5e964158-b997-11e7-84ef-ba2a976f1d2d.png">
<img width="1030" alt="screen shot 2017-10-25 at 3 14 53 pm" src="https://user-images.githubusercontent.com/8919308/31985347-5e3dcc26-b997-11e7-9917-2928cfce2436.png">

**Comment by 6a68** [comment]
As of 57, it will be possible to click the page action to both activate and dismiss the overlay. I'm not sure I see the need for additional UI.

**Comment by johngruen** [comment]
@6a68 i see it too...maybe you have weird add-ons?
