### ISSUE TITLE
Remove browserAction

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3468]
We've switched to a pageAction for Firefox 57 / Photon.  But we kept browserAction support so we could support older Firefox version. After discussion we realized we won't be deploying the current master to any versions of Firefox older than 57, so we can just remove the browserAction entirely.

This should remove the browserAction from manifest.json, and related code from bootstrap.js. We should probably get a review on this change from Mossop or kmag (if #3463 is done we could experiment with it for this).

**Comment by gijsk** [comment]
Seems like we should get this in before the 57 merge (on the 20th/21st, so just over a week away), or beta ends up with https://bugzilla.mozilla.org/show_bug.cgi?id=1396438 . Is "stretch" the appropriate milestone for this? @ianb ?

**Comment by ianb** [comment]
During testing I'm seeing this error in the Browser Console, during the selection process: `TypeError: window is null  WebNavigationFrames.jsm:59:1` – but these changes don't seem to affect the error one way or the other, so at least it's probably unrelated to this change.
