### ISSUE TITLE
The "Save Visible Page" and "Save Full Page" options are not working on MacBook Pro

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3472]
[Notes]:
- This issue is not reproducible on YouTube and Wikipedia pages.
- This issue is not reproducible on production.

[Affected versions]:
- Nightly 57.0a1
- Beta 56.0b9
- Screenshots 18.1.0

[Affected Platforms]:
- Mac Book Pro

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" set to "true".
- Have the Screenshots 18.1.0 stage version installed from "https://screenshots.stage.mozaws.net/homepage/install-test-local.html" page. 

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "http://www.imdb.com/".
2. Click the Screenshots button from Nightly "Page Action".
3. Click the "Save Full Page" or "Save Visible Page" button from the right part of the page.
4. Click the "Save" button and observe the browser behavior.

[Expected result]:
- The shot is successfully saved.

[Actual results]:
- The shot is not saved and a "Out of order" error is displayed.

[Additional Notes]:
- I have tested this on 2 MacBook Pro and the issue is reproducible on both. I have also tested on a iMac and the issue is not reproducible.
- However, the download functionality is working.
- Here is a screen recording with the issue: https://goo.gl/Wqg63J
- Here is a screenshots with browser console errors:
![save visible](https://user-images.githubusercontent.com/19226534/30169872-3a388fda-93f6-11e7-8490-fc422e20585b.png)
- On Screenshots dev server different errors are displayed:
![dev save full](https://user-images.githubusercontent.com/19226534/30169877-3d3ce5b4-93f6-11e7-9922-3e90e8c84f15.png)

**Comment by ianb** [comment]
This appears to be a side-effect of the upload change, and large requests. It seems like we have some reporting problems, error catching problems, and then invalid request bodies, so it'll take a little sorting out.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the Nightly try build with Screenshots 19.0.0 on a MacBook Pro and the issue is no longer reproducible. Marking as verified.
