### ISSUE TITLE
"Download", "Share" and "Delete" buttons do not loose their highlight after each respective action is canceled 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3473]
[Notes]:
- The issue is reproducible on Mac OS only for the "Download" button.

[Affected versions]:
- Nightly 57.0a1
- Screenshots 18.1.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" set to "true".
- Have the Screenshots 18.1.0 stage version installed from "https://screenshots.stage.mozaws.net/homepage/install-test-local.html" page. 

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Click the Screenshots button from Nightly "Page Action".
3. Perform a selection on the page and click the "Save" button.
4. Click the "Delete" button.
5. Click the "Cancel" button and observe the "Delete" button state.

[Expected result]:
- The button is no longer highlighted.

[Actual results]:
- The button is highlighted even though the mouse is not hovering it.

[Additional Notes]:
- This issue is reproducible on stage and dev servers.
- Here is a screen recording with the issue:
![highlight](https://user-images.githubusercontent.com/19226534/30171034-69584802-93f9-11e7-87a1-93d401518abe.gif)

**Comment by iansan5653** [comment]
When you click a button that triggers a JavaScript alert in Firefox, the button keeps its active state until the alert is dismissed, at which point the button is given a focus state instead. The solution here would be to make the :focus style different from the :active style.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
