### ISSUE TITLE
Provide "Copy to clipboard" Option.

### ISSUE THREAD

**Issue by feinstein** [mozilla-services/screenshots#3485]
It would be perfect if I could get the screenshot and have it copied to my clipboard, almost NEVER I want a link, or the screenshot saved on the cloud, or on my PC, I just want to grab the screenshot and Cntr+V, paste it, on another tab. For example, get a screenshot from Facebook and paste it in a WhatsApp conversation with someone.

Windows own Snipping Tool has the "Copy" option, I think you should provide a similar option on Firefox.

**Comment by pdehaan** [comment]
Possible duplicate of #2582 _"Add option to copy image (not just link) *to* clipboard"_.

**Comment by feinstein** [comment]
Yes, it's a duplicate, I will close this one then. Thanks.
