### ISSUE TITLE
Screenshots button missing

### ISSUE THREAD

**Issue by Extarys** [mozilla-services/screenshots#3487]
Hello!!

I have a screenshots button in my Library but clicking on it open the list of my screenshots. I cannot find how to take a screenshot. It is not in "Customize". I lost it last week and didn't mind at the time since I was busy. Now  I cannot find it. Where should it be?

**Comment by SoftVision-CosminMuntean** [comment]
Hi @Extarys,
The Screenshots button is moved in the Nightly "Page Actions". When you navigate to any websites you can see 3 dots displayed in the right part of the Address Bar. If you click the dots, a pop-up appears and you can see the Screenshots button. 
![sdads](https://user-images.githubusercontent.com/19226534/30365676-24dadfec-9871-11e7-8d56-0c66b8cd68c6.png)

The "Take a Screenshot" option is also available in context menu.
Please let me know if you found it.

**Comment by Extarys** [comment]
Wow I feel so dump I never noticed this menu before. Thanks!!
