### ISSUE TITLE
Screenshots tour is outdated for photon UI

### ISSUE THREAD

**Issue by eleemoz** [mozilla-services/screenshots#3489]
With the recent move of the screenshots action to the URL context menu, the info contained in the [Screenshots Tour](https://screenshots.firefox.com/#tour) is out of date.

This has caused confusion for some users as well. e.g., [this comment](https://www.reddit.com/r/firefox/comments/6ypmhs/firefox_screenshots_feature_has_appeared_in_my/dmpe3wr/?st=j7jdqyrn&sh=6ed2576f)

**Comment by ianb** [comment]
Thanks, d07db41 will fix this in our [19.0.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1399615) release, heading to Nightly now.
