### ISSUE TITLE
"Full page" screenshot won't go past 5000 pixels

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-services/screenshots#3490]
When trying to take a screenshot of the [HTML Standard page](https://html.spec.whatwg.org/), or any web page higher than 5000px, the "Full page" feature won't take more than 5000 pixels.

This is problematic when you need to take screenshots of things like icon catalogs (the only workaround being "Print as PDF", which is not as useful as a proper PNG screenshot.)

**Comment by jankeromnes** [comment]
Here is a (system) screenshot of how the Screenshot extension behaves on pages that are longer than 5000px:

![screenshot-full-page-bug](https://user-images.githubusercontent.com/599268/30432894-523c8cfe-9963-11e7-8f58-f66c3a4fddeb.png)

And here is the resulting "Full page" screenshot (which barely contains even the table of contents):

![screenshot-2017-9-14 html standard](https://user-images.githubusercontent.com/599268/30432843-26afb926-9963-11e7-8e0b-70e670ac2fe6.png)

**Comment by jankeromnes** [comment]
See also #2129. It would be good to at least point out the arbitrary 5000px limit (e.g. with a visual warning as suggested in the related issue), and even better to be able to disable it, e.g. "I know what I'm doing, I need a screenshot larger than 5000px, and I don't care if this makes my computer slow for a short while or takes somewhat more disk space".

**Comment by ianb** [comment]
I'm going to close this in preference of #2129 (which would let people know that the limit was being applied). I also opened #3506 to remove the limit for downloads, where the performance issues aren't as great. But we need to improve the performance for full-page shots (even with the 5000px limit) before we can lift the limit.
