### ISSUE TITLE
Screenshots tour points to the old toolbar button

### ISSUE THREAD

**Issue by Mossop** [mozilla-services/screenshots#3496]
The screenshots tour page (https://screenshots.firefox.com/#tour) says to look for the screenshots toolbar button but in nightly the button is in the page action menu now.

**Comment by ianb** [comment]
We'll be deploying the fix for this (viewable on https://screenshots.dev.mozaws.net) in a day or two. Or, for the slides, the fix is in [version 19.0.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1399615)
