### ISSUE TITLE
Wording suggestions / clarifications

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3499]
These suggestions are from Matthew Davis @ https://discourse.mozilla.org/t/upload-of-screenshot-without-asking-for-permission-or-even-warning-me/16451/7

On [this page](https://screenshots.firefox.com/#hello), under “Save and Share”, it should say something like:

> When you take a shot **and click on the Cloud Share button**, Firefox posts your screenshot to your online Screenshots library and copies the link to your clipboard. We automatically store **shared** screenshots for two weeks, but you can delete shots at any time or change the expiration date to keep them in your library for longer. If you don’t click on the share button, your image doesn’t leave your computer.

Of course, only put that if it’s true.

And the “[privacy notice](https://www.mozilla.org/en-US/privacy/firefox/)” link at the bottom of [that page](https://screenshots.firefox.com/shots) should take the user to a page which actually tells the user something useful, which is specific to Firefox screenshots. Privacy notices have one purpose, and the current one fails to fulfill that. It should tell me what happens to my data. i.e. when are my photos uploaded to the cloud? And when are they not?

Similarly, there should be a question on [the FAQ page](https://wiki.mozilla.org/Firefox/Screenshots/FAQs) which says something like:

> Q: Which images are uploaded to the cloud?
> 
> A: By default, images do not leave your machine. Images are uploaded only if you click ‘share’ to generate a URL. You can choose to sync all screenshots with the cloud by going into settings and clicking on

The “download” button should have it’s hovertext changed from “download” to “save to filesystem”. Maybe also change the download icon to a hard disk shaped save icon?

Functionally, I’d like “My Shots” to show me all the shots that I’ve saved locally, even if I didn’t upload them to the cloud.

/cc @flodolo

**Comment by flodolo** [comment]
It would be nice to explain why the issue has been closed, for people landing in this issue.

**Comment by rakoczy** [comment]
Definitely it would be, but since the last year there was no change in Firefox screenshot FAQ, so it seems that the issue (fully described here [https://discourse.mozilla.org/t/upload-of-screenshot-without-asking-for-permission-or-even-warning-me/16451](https://discourse.mozilla.org/t/upload-of-screenshot-without-asking-for-permission-or-even-warning-me/16451)) is simply ignored. Perhaps wording can't be changed as suggested because after change it would be false? :-(
