### ISSUE TITLE
Add an indicator that a shots have been saved indefinitely

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3500]
In order to highlight indefinitely saved shots, we should add some kind of indicator to to _My Shots_ on each indefinitely saved shot. This could be a little badge or something. Seems like low hanging fruit and an easy way to call out favorites.

As a follow on, we might consider moving indefinitely saved shots to the top of _My Shots_.

**Comment by johngruen** [comment]
@chenmorpheus, do you think you could provide a spec for this?

**Comment by ChenMorpheus** [comment]
@johngruen Yes, Mark has some preliminary ideas. He is working on this.

**Comment by youwenliang** [comment]
@johngruen Here are some proposals for the simple indication version (without setting expiration date on my shot page)

Option 1: Add an "Infinite" indicator on the bottom of the shots. (Should probably also add the infinite symbol next to the "indefinitely" option in the drop-down menu)
![3 3 shot index page never expires](https://user-images.githubusercontent.com/8919308/30957675-87e2f9a0-a46d-11e7-8b30-783b3d8fb352.png)

Option 2: Simply add a "Never expires" section on the top of My Shot page. The assumption here is that if a user sets a shot to "indefinitely" it's probably more important or needed to be more accessible to the user.
![3 2 never expires section](https://user-images.githubusercontent.com/8919308/30957678-8832bc74-a46d-11e7-9bf6-36dfdd63a53d.png)

Option 2 could potentially add more features to the design, such as categorizing shots or adding custom sections to sort shots.

**Comment by youwenliang** [comment]
@johngruen any updates on this issue?

**Comment by johngruen** [comment]
@youwenliang i really like option 1 actually..since it's a passive indicator, i'm not sure how we would a/b test it though?

**Comment by youwenliang** [comment]
@johngruen I think we can a/b test different icons or test different location (bottom right corner or top right/left corner)

**Comment by johngruen** [comment]
Might be confused for a permalink icon. I don't think we can A/B test since there's nothing actionable here, but we e can go ahead an implement something.

**Comment by youwenliang** [comment]
I'll discuss with Fang and see if we can have a final visual design to implement.

**Comment by chenba** [comment]
@youwenliang any update on this?

**Comment by fangshih** [comment]
After we test out all different icon proposals. We feel the first option infinity icon fits better as a small indicator. Less complicated. And once we have the icon right next to the indefinitely option as image 2 here. It will give a better connection to hint the user what is this symbol for. 
**Overview**
![3500-33-shot-index-page-never-expires-copy](https://user-images.githubusercontent.com/4862573/34767590-74f2c4c0-f633-11e7-93fd-227f85c7c782.png)

**Dropdown view** 
![3500-40-crop-image](https://user-images.githubusercontent.com/4862573/34767605-82a9b470-f633-11e7-83c9-a534dc8766bb.png)

**Assets and spec**
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/FFSS-3500-infinite

**Comment by chenba** [comment]
Since the expiration select is a good ol' `<select>`, I can't put an image in an `<option>`. (Setting a `background-image` didn't work either.)  However, I can append a UTF8 ∞.  Then for consistency I can also use that instead of the image on My Shots.  What do you think?

A more heavy handed alternative would be to replace that `<select>` list with an unordered list or a set of divs and use css and javascript to make it look and behave like a select drop down.  Then we can use the image.

**Comment by chenba** [comment]
@flodolo is using ∞ to mean forever fairly universal?

**Comment by flodolo** [comment]
> @flodolo is using ∞ to mean forever fairly universal?

I can't find data about it. If possible, I would keep it in the string, so that a locale can remove it if they want.

**Comment by chenba** [comment]
Reopening this because there are some style changes that UX wanted.
