### ISSUE TITLE
Prompt FF with no shots from shot pages

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3501]
This just occurred to me, which is dumb.

## Story
I'm am on Firefox 57 and have no idea Screenshots exists. I go to a shot that someone sent me (or i see on Twitter or whatever). FIrefox should be smart enough to recognize that I'm a non-onboarded user and suggest that i try a shot of my own.

We will have a UI tour capability very soon, so this might be as simple as doing some kind of banner that says something like: `Did you know you can take Screenshots like this in Firefox` with a button that throws the UITour action. We would only do this on users who haven't taken any shots.

Possibly this could piggy back off of #3253

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
