### ISSUE TITLE
Description "Download to your computer" is misleading

### ISSUE THREAD

**Issue by HappyPony** [mozilla-services/screenshots#3505]
Description "Download to your computer" here https://screenshots.firefox.com/ is misleading, while with click at button ![screenshot-2017-9-18 firefox screenshots 2](https://user-images.githubusercontent.com/3226308/30539925-174c04fc-9c75-11e7-88c9-143371966a0a.png)  there is no downloading of screenshot. The screenshot preexisted already on my PC and with click at button ![screenshot-2017-9-18 firefox screenshots 2](https://user-images.githubusercontent.com/3226308/30539925-174c04fc-9c75-11e7-88c9-143371966a0a.png) I save only this screenshot on local storage as file.

I suggest change the label from "Download to the PC" to "Save local"

**Comment by 6a68** [comment]
Thanks for the suggestion :+1: We talked it over and we're going to stick with the current language for now
