### ISSUE TITLE
Use toBlob instead of toDataURL

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3508]
I didn't notice there's a [toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) method on canvases. We should use that.

**Comment by ianb** [comment]
There is some unfinished work on this in #3540

**Comment by wresuolc** [comment]
Clearing milestone to re-review priority. Related to bug 1424870

**Comment by johngruen** [comment]
Todo: figure out if we need to work on this

**Comment by chenba** [comment]
From some simple testing, it appears that there isn't much of a performance penalty with converting to a blob for the preview image (vs. toBlob or using a data url for the image).  For bug 1424870, we could create a small patch doing just that.  We'll put this back on the back burner in the meantime.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
