### ISSUE TITLE
Use new icon everywhere

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3509]
The new favicon doesn't match the icon used in the addon or elsewhere in the website. Let's be consistent and use it everywhere.

Website:
- Screenshot icon in homepage + my shots headers
- Screenshot icon in the homepage tour

Addon:
- Screenshot icon in page action item & toolbar button
- Screenshot icon in the onboarding tour
- Need a separate starred version of the SVG for the first-run use case

**Comment by wresuolc** [comment]
This is a feature
