### ISSUE TITLE
Investigate bumping xhr priority?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3511]
adw mentioned that request priority can be bumped higher than usual. Maybe we could use this to accelerate uploads? Need to dig in and make sure it's possible from our webextension context

https://dxr.mozilla.org/mozilla-central/source/xpcom/threads/nsISupportsPriority.idl#44

**Comment by ianb** [comment]
This is magic stuff, I don't think we want to go there.
