### ISSUE TITLE
[RTL] Cloud icon in the Save button slightly mispositioned after the fix in #3241

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-services/screenshots#3514]
Using latest Nightly, Windows 10, DPI set to 150% if it matters.
After #3241 was fixed, this is visible after selecting a portion of a page:
![default](https://user-images.githubusercontent.com/18016656/30609807-00d7a9e0-9d85-11e7-935a-2693a14c2bcb.png)

The cloud icon is slightly mispositioned here.

**Comment by johngruen** [comment]
thanks for reporting. I can clean this up!

**Comment by johngruen** [comment]
I went to fix this and found that i could not reproduce it...

**Comment by johngruen** [comment]
@ItielMaN was this on a particular website?

**Comment by ItielMaN** [comment]
Nope, this happens on every website.

**Comment by ItielMaN** [comment]
Note that this is reproducible only when selecting a portion of the page, and not when capturing the entire page.

**Comment by johngruen** [comment]
@ItielMaN what version of firefox are you using?

**Comment by ItielMaN** [comment]
@johngruen Latest Nightly. 58.0a1 2017-10-30

**Comment by johngruen** [comment]
huh, really odd, i have a hebrew build and i am not seeing it...i'm on a mac though, i guess that could make a difference given how much font stuff is OS level....FIRING UP MY VIRTUAL MACHINES!

**Comment by johngruen** [comment]
@ItielMaN got it!

**Comment by ItielMaN** [comment]
@johngruen Any idea on when will this change be seen in Nightly?
