### ISSUE TITLE
The "Take a Screenshot" button remains dark when pinned to the address bar in dark mode

### ISSUE THREAD

**Issue by iansan5653** [mozilla-services/screenshots#3515]
**User Agent**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`
**Build ID**: `20170917031738`

**Steps to reproduce:**

Pin the "Take a Screenshot" menu option from the address bar overflow menu to the address bar itself, after setting the browser theme to "Dark". 

**Actual results:**

The button remains dark, thus poorly contrasting with the address bar and becoming difficult to see.

![screenshot](https://user-images.githubusercontent.com/2294248/30611106-673c12d4-9d4e-11e7-8709-2214a95d9434.png)

**Expected results:**

The button should have a light version, just like "Save Page to Pocket" or "Copy Link".

**Comment by iansan5653** [comment]
![Screenshot](https://user-images.githubusercontent.com/2294248/30610648-d889d91e-9d4c-11e7-8c90-51acf638c886.png)

**Comment by ianb** [comment]
Thanks for the report, we just got this fixed in today's Nightly, update Firefox and it should look correct now.
