### ISSUE TITLE
Firefox Developer Edition 57 : Take Screenshot Filename Problem Background Error: filename must not contain illegal characters

### ISSUE THREAD

**Issue by netinetwalker** [mozilla-services/screenshots#3517]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401151
![error](https://user-images.githubusercontent.com/6934484/30616621-23260c5e-9d93-11e7-80c1-ce1470db265f.png)

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20170917031738

Steps to reproduce:

Go to the following Website: https://www.heise.de/forum/heise-online/News-Kommentare/Gefaehrdeter-Datenschutz-Firefox-loescht-lokale-Datenbanken-nicht/Re-Dessen-neue-Bedienoberflaeche-Photon/posting-31065842/show/

Click on Actions for this Site -> Take Screenshot
Complete Page -> local Save Button

Windows 10 / Firefox Developer Edition 57.0b1 (64-Bit)

Actual results:

It does not create the Screenshot.
On Error Bubble is shown with: Background Error: filename must not contain illegal characters

Expected results:

It should create the Screenshot

Windows 10 / Nightly 57.0a1 (2017-09-18) (64-Bit) ist affected too

**Comment by ianb** [comment]
I believe the title of the page is `Re: "Dessen neue Bedienoberfläche "Photon"..… | Forum - heise online` – which for download purposes is turned into `Re  "Dessen neue Bedienoberfläche "Photon"  …   Forum - heise online` and... apparently the quotation marks are the problem.
