### ISSUE TITLE
Does not work on AMO

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3525]
Clicking the screenshot page action does nothing on AMO.

**Comment by wresuolc** [comment]
Did you get an error message?  We just tried this in our triage and all got error messages.

The behavior is expected, but you should see an error.

**Comment by MikkCZ** [comment]
No and Yes. After Firefox restart, I never get the error on the first try. I have to click the page action two or three times and than the error message appears. All subsequent tries to take the screenshot produce an error message immediately, but not the first one or two.

**Comment by MikkCZ** [comment]
Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 ID:20170921100141
Firefox Screenshots	19.0.0

**Comment by ianb** [comment]
We suppress all errors (regardless of reason for the error) in the first 5 seconds (I think the 5 second counter is from when the add-on starts up, which is somewhat delayed). We were afraid of annoying users with startup issues. Anyway, I think that's why the error messages acted weird.

**Comment by MikkCZ** [comment]
I see. But it seems it gets actually activated on the first "take a screenshot" click. So when AMO is my first page after start I want to take a shot, I won't see the error.

**Comment by wresuolc** [comment]
Thanks for filing this, but this is too much of an edgecase for us to prioritize at this point.  I'm going to wontfix it in favor of the other bugs.
