### ISSUE TITLE
Can't save screenshot from page with very long domain name

### ISSUE THREAD

**Issue by zelitomas** [mozilla-services/screenshots#3530]
Server throws 500 error when trying to upload screenshot from URL with a long (but valid!) domain name - for example http://thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.thisisverylongdomainname.zelitomas.cf/

**Comment by testeaxeax** [comment]
@wresuolc Currently the domain's length is restricted to 103 characters. What would be a appropriate max domain length?

**Comment by wresuolc** [comment]
If the max is 253, then accepting that seems fine.
