### ISSUE TITLE
Remove .nsprc after tough-cookie is updated

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3532]
Reverting 8f9dff685b010695a34fbf4f6d2af584d1d7e31f

We should track this security warning: https://nodesecurity.io/advisories/525

Once [tough-cookie](https://www.npmjs.com/package/tough-cookie) gets past 2.3.2 we'll probably be okay.

**Comment by 6a68** [comment]
I went ahead and rebased / force-pushed this

**Comment by ianb** [comment]
New toughcookie is out BTW, with a fix
