### ISSUE TITLE
Screenshots are blurry due to strange fractional width

### ISSUE THREAD

**Issue by lol768** [mozilla-services/screenshots#3541]
First, props for a really cool tool.

I gave it a go and took [this](https://screenshots.firefox.com/hblWqiLDMTg8dJmg/screenshots.firefox.com) screenshot. On the preview page the image is given a really odd width via an inline style `height:auto;width:350.6333312988281px;max-width:100%;`

As such, it appears blurry (you'll want to open up these images below to full size to compare):

![Original](https://lol768.com/i/VY.LZ.lz.BE.di.JA.LZ.s5)

The actual width is `350px` and if I modify the style to this, then it looks sharp as you'd expect:

![With width changed](https://lol768.com/i/aN.Sx.Nn.jt.4v.zE.qu.BT)

**Comment by ianb** [comment]
I think a Math.floor will fix this, applied [here](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/view.js#L43)
