### ISSUE TITLE
Automatically Extract entities from Shots

### ISSUE THREAD

**Issue by eeejay** [mozilla-services/screenshots#3545]
I think this would be a huge accessibility win. Check out http://tesseract.projectnaptha.com/

**Comment by 6a68** [comment]
We actually could use the DOM serialization code to pick out a subset of user-selected DOM, then pass that selection to fathom. Let fathom tell us which bits of text are visible and most useful. Then, either strip out text not selected by fathom, or upload an image + the fathom-selected text.

**Comment by ianb** [comment]
The DOM text capture code is still in the product, turned off behind the `captureText` build flag.

The actual code could use some work, especially testing to ensure that it correctly captures text, and doesn't over-capture. Over-capturing was the problem that caused us to turn it off. OCR is safer in that it doesn't have access to any information the viewer doesn't already have access to.

**Comment by johngruen** [comment]
@eeejay now that we've shipped I'm working through the product backlog...changed the name of this bug to make it a little more general.

**Comment by chenba** [comment]
Related and similar to #4689

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
