### ISSUE TITLE
Don't suppress explicit errors during startup

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3559]
We have a 5 second startup error suppression limit (in senderror). I don't think we should suppress explicit errors, which is probably errors with POPUP_MESSAGE (though this should be confirmed). Haywire messages *should* be suppressed.

This is compounded because it's 5 seconds after Screenshots startup, and Screenshots starts maybe 10 seconds after the Firefox window appears.

**Comment by wresuolc** [comment]
everyone is scared of this 😨 😰
