### ISSUE TITLE
On smaller screens the expiry related buttons are not fully visible when changing zoom level at 150% or above

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3562]
[Affected versions]:
- Nightly 58.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots build v. 19.1.0 installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Perform a shot on the website and save it.
3. Change the zoom level of the browser window at 150% or above.
4. Click the "Expires in 14 days" button.
5. Observe the "Select time", "Save" and "Cancel" buttons.

[Expected result]:
- The buttons are fully visible.

[Actual result]:
- The "Select time", "Save" and "Cancel" buttons are not entirely visible.

[Notes]:
- Depending on the size of the screen, it's possible that even the "Expires in 14 days" button is not fully displayed.
- This issue is also reproducible on bigger screens if the browser is resized.
- Here is a screen recording of this issue:
![screenshot](https://user-images.githubusercontent.com/31244235/30973518-fe42a822-a475-11e7-9b13-475c419913cb.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
