### ISSUE TITLE
The background of the buttons from the Screenshots overlay is wrongly transparent

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3565]
[Affected versions]:
- Nightly 58.0a1
- Screenshots 21.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" set to "true".
- Have the Screenshots 21.0.0 dev version installed from "https://screenshots.dev.mozaws.net/homepage/install-test-local.html" page. 

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Click the Screenshots button from Nightly "Page Action" and dismiss the tour.
3. Observe the buttons from the top right of the page.

[Expected result]:
- The buttons are correctly displayed and have a grey background (100% opacity).

[Actual results]:
- The background of the buttons is transparent.

[Notes]:
- This issue is no reproducible on stage and production servers.
- Here is a screenshot with the issue:
![screenshots buttons](https://user-images.githubusercontent.com/19226534/31009808-5d47e512-a511-11e7-9bb9-071a44cb1151.png)

**Comment by wresuolc** [comment]
This is a side effect of high-contrast mode.

**Comment by ianb** [comment]
From [this question](https://stackoverflow.com/questions/1921047/how-to-check-if-user-is-in-high-contrast-mode-via-javascript-or-css) it looks like there's a media query that applies to high contrast mode.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is also reproducible with Screenshots (22.0.0) on stage server. Since this issue is a regression of the background of the buttons, we should fix this before landing the High-Contrast patch in Beta 57.

**Comment by 6a68** [comment]
Fixed by #3583

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Nightly 58.0a1 build using [Screenshots dev](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) (22.0.0) version and the issue is no longer reproducible. Marking as verified.
