### ISSUE TITLE
Create "download only" mode

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3574]
There are a couple situations where we want to let the user use Screenshots and download their shot, but not allow them to upload the shot.

The three cases we are specifically thinking about:

1. From a Private Browsing window (note we also need #3274)
2. When third-party cookies are disabled (see #3572)
3. When "never remember history" is enabled (see #3196)

To do this bug, potentially only one of these cases might be handled, and we can do a follow-on for the other cases.

The second two are based on Firefox preferences, and we would have to read these preferences in bootstrap.js. This would be sent to the WebExtension in the same manner (or at the same time) as the Telemetry/FHR preference.

**Comment by johngruen** [comment]
@clouserw why does this need product? We've already discussed this in our standup.

**Comment by wresuolc** [comment]
@johngruen only if there is anything around when to show the label.  Eg. number 2 up there -- do we want to warn about 3rd party cookies?

Sounds like needs:ux is most appropriate now.

**Comment by youwenliang** [comment]
Two quick proposals here:
https://mozilla.invisionapp.com/share/WJDTYPTGE

Option A shows a simple message about "Download-only mode" and users can click on the info button to open the tooltip and learn more about what download-only mode is.

Option B shows the whole message in a block placing at the bottom left corner.

This is a temporary copy and it should be modified by copywriters to help users better understand the situation.

**Comment by johngruen** [comment]
@youwenliang lets go with option A with the caveat that i think that tooltip should just show up on hover, so we can ditch the [x] control

**Comment by johngruen** [comment]
@youwenliang can you provide a measurement spec for option A?

**Comment by youwenliang** [comment]
Here's the measurement: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FFSS-3574/
