### ISSUE TITLE
Hover selection highlight is opaque

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3576]
Example:

![image](https://user-images.githubusercontent.com/44390/31096374-70d1fc68-a781-11e7-8584-a1f4f79b2311.png)

The white box should just be an outlined box. I'm guessing this is a byproduct of #3546

**Comment by SoftVision-CosminMuntean** [comment]
@ianb I have logged a similar issue #3566. Is this different from that one?

**Comment by 6a68** [comment]
Fixed by #3583
