### ISSUE TITLE
Error Deleting Shot (401 Error: Not logged in)

### ISSUE THREAD

**Issue by denormalizer** [mozilla-services/screenshots#3585]
Reproduce:
* Save a shot to: https://screenshots.firefox.com
* When presented with the image and a button to delete, click delete
* A popup appears: "Error Deleting Shot"

What I expect:
* Image to be deleted

**Notes**
* When viewing network activity, I saw a 401 Error: Not logged in
* After logging into Mozilla accounts (Enable "Accept cookies from websites" in Options/Privacy & Security)
* I was able to delete as expected

**Possible Solutions**
* Remove button to delete when user is not logged in; OR
* Display error: "Not logged in" when user tries to delete

Thoughts?

---
OS: Windows 10 Pro 64
FF: 57.0b3 (64-bit)

**Comment by wresuolc** [comment]
Do you have 3rd party cookies disabled?

**Comment by denormalizer** [comment]
Yes I did. Is FF screenshots dependent on 3rd party cookies being enabled?

**Comment by wresuolc** [comment]
It is right now.  We're talking about that in #3581 .  I'll close this as a duplicate
