### ISSUE TITLE
Add telegram share

### ISSUE THREAD

**Issue by Mte90** [mozilla-services/screenshots#3587]
On the share modal are missing many services and one of them is telegram

**Comment by johngruen** [comment]
No one uses the options we have here, so i'm inclined not to spend time adding more for the time being.

**Comment by Mte90** [comment]
I received this as a complain because the share was missing the telegram support :-/

**Comment by johngruen** [comment]
Noted. We're looking at more sharing option here. Direct to clipboard shot saving may be another way to resolve this issue without adding a giant share-sheet.

**Comment by johngruen** [comment]
Closing this in favor of a generic sharing bug: #3685
