### ISSUE TITLE
Remove Share panel from mobile shot pages

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3589]
Reported in slack by @ryanfeeley for ipad. I confirmed on iphone.

Looks like mobile safari doesn't just support `execCommand(copy)`. [This SO answer](https://stackoverflow.com/questions/32851485/make-clipboard-copy-paste-work-on-iphone-devices/43001673#43001673) might be worth investigating.

**Comment by ianb** [comment]
In some previous designs we just dropped the share button on mobile, since the browser has its own share interface.

**Comment by wresuolc** [comment]
Let's hide the share button on mobile views on both My Shots and the individual shot pages

**Comment by ianb** [comment]
We should just display:none the share button on shot pages, using responsive media queries. Note we don't have to worry about My Shots currently, as no one on mobile has access to My Shots. (That will change with FxA support.)

**Comment by chenba** [comment]
I'm going to use an existing media query for what's considered mobile.  But that won't work for iPads in landscape or iPad Pros (or similarly high-res tablets).  iPad was mentioned in the first comment (https://github.com/mozilla-services/screenshots/issues/3589#issue-262485471).
