### ISSUE TITLE
Feature Request: Include gif creation functionality

### ISSUE THREAD

**Issue by turtleloveshoes** [mozilla-services/screenshots#3598]
Hi There, 
Guigs, from SUMO, I was not sure what the right place you all are collecting feedback from users, so I created a bug on behalf of a user that made a suggestion in the Social Support channels. 

There is a desire to add a functionality to create gifs with screenshots. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1404414

**Comment by wresuolc** [comment]
Thanks for letting us know.  We're tracking this feature at #3445
