### ISSUE TITLE
Warn about third-party cookies

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3600]
Since we won't get any blocked-third-party-cookies fix into 57 (or 56), maybe we should put a warning on the site (for users with that pref off).

Detection techniques are kind of obtuse (you need to send a cookie-setting request to a different domain, wait for it to return, and then send a second request that checks if the cookie stuck around), but we can run them behind the scenes. We could do it *only* for new shots and My Shots, so we don't make extra overhead from regular viewers.

**Comment by 6a68** [comment]
We can just check the `network.cookie.cookieBehavior` pref from the bootstrap side. Its values are documented in the [nsCookieService interface](https://dxr.mozilla.org/mozilla-central/source/netwerk/cookie/nsICookieService.idl#84-91).

We can also set up a pref listener to notify the user when they flip this value.

**Comment by ianb** [comment]
We can do those things... in a new add-on release! But I'm proposing a server-side fix that can apply to 56 and 57.

**Comment by wresuolc** [comment]
Disabling upload for these folks will fix this so no need for a warning.

**Comment by wresuolc** [comment]
Let's do the second ping to the server and if the shot wasn't deleted we'll let the user know.
