### ISSUE TITLE
Share/Save/Upload screenshot shares more than just the screenshot

### ISSUE THREAD

**Issue by saberworks** [mozilla-services/screenshots#3602]
I noticed while testing the new screenshots tool that when I used the "save" button to upload my screenshot to your server, quite a bit more than just the screenshot was sent to your server (and is being shared).  For example, the page title and the domain is also captured and shared.  This seems to have severe privacy and security implications because someone may be screenshotting internal or admin tools (possibly running in subdomains?) and don't want all this information shared.  Also consider if someone is on a NSFW site but screenshots a portion of the page that is SFW, the screenshot itself may be fine but the associated data would be bad to share with coworkers.  (Just a contrived example.)

In addition to not showing/sharing the info, I'm curious what else is actually sent to your server when I screenshot a page and click the "Save" button.  Is there a list somewhere of what is sent?

**Comment by saberworks** [comment]
Note that your FAQ page claims web site data will not be collected if "Do Not Track" is enabled.  Indeed "Do Not Track" is set to "Always" yet the web site data was still sent.

**Comment by ianb** [comment]
What web site data are you seeing being sent? We always load the analytics scripts, but the actual data shouldn't be sent if that flag is on. (The logic for this is in [ga-activation.js](https://github.com/mozilla-services/screenshots/blob/master/server/src/ga-activation.js))

**Comment by saberworks** [comment]
Here is an example screenshot I uploaded.  Associated with the screenshot itself is the page title (snipped by the screenshot tool I guess) as well as the domain the page is hosted on.

https://screenshots.firefox.com/oFTVibyVnGx7LPAl/news.ycombinator.com

What I'm saying is that the screenshot tool should share the screenshot only, not any other information about the page I am on.

**Comment by ianb** [comment]
If you get the image alone, it won't contain any of that other information: https://screenshots.firefoxusercontent.com/images/9e6e85be-3bce-4c6b-a3bc-1a94ae46b85a.png – that image URL isn't associated with the original shot URL, so if you give that image URL to someone they can't get back to the shot page.

Do Not Track isn't intended to apply to this kind of information. The title and domain are pieces of information that are captured for your purposes, not as a way for Mozilla to track your behavior. Do Not Track is specifically about tracking for the service provider's benefit and analysis (strictly speaking it's intended to be for third party tracking, though we overextend its meaning to mean you don't want us to do our first party tracking either).

**Comment by saberworks** [comment]
I understand where you are coming from.  However, it seems clear that the intention is not to share the raw image url because when I upload an image, it copies a URL to my clipboard and a notification tells me the "link to your shot" has been copied to my clipboard.  The URL copied to clipboard is the one that contains the extra data:

https://screenshots.firefox.com/H7X8zkMsmWqW7g4V/news.ycombinator.com

I think page title, url, domain, etc., should not be sent to mozilla servers.  I'm also curious to see what other information is sent (that may not be visible on the resulting screenshot page).

**Comment by johngruen** [comment]
So we're building out a privacy mode that only downloads or copies to clipboard. I think this bug can be duped to that since using in that mode obviates the core concerns here.

Duping to #3574

**Comment by ianb** [comment]
Note if you want to see the complete information saved you can look at https://screenshots.firefox.com/data/H7X8zkMsmWqW7g4V/news.ycombinator.com (note the `/data/`). This is only visible to the shot author, though I don't believe it has any information in it that isn't also present in the shot page.

Also closing per https://github.com/mozilla-services/screenshots/issues/3602#issuecomment-335199504

**Comment by saberworks** [comment]
@ianb every time I access a URL like that I get a "bad csrf token" error message, with no information displayed.  See https://screenshots.firefox.com/HzVoBpLWsxIOpu6s/screenshots.firefox.com

(I would like to see the actual information, maybe you could post a screenshot since the link doesn't seem to actually work?)

I think closing this ticket is a mistake.  It's not a duplicate of the other ticket.  This ticket is explicitly asking for a way to take and share a screenshot without leaking other, possibly private information.  A "download only" mode (as mentioned in the other ticket) is a completely different thing.  It's not reasonable to require users to go into a private window or disable 3rd party cookies in order to take and share a screenshot without leaking other site information.  (Although I don't think the other ticket will allow sharing at all so it doesn't really solve the problem mentioned in this ticket.)

**Comment by ianb** [comment]
You are right about that URL – it's not a feature we use for much, so somewhere during our security hardening we broke that endpoint.

You can see some of the same data at https://screenshots.firefox.com/HzVoBpLWsxIOpu6s/screenshots.firefox.com?data=json&pretty – but that's literally the data we embed into the page to support the rendering, so you'd see the same things with View Source.

We do have a metrics document that we maintain, that talks about a lot of the different data collection points: https://github.com/mozilla-services/screenshots/blob/master/docs/METRICS.md
