### ISSUE TITLE
No “Save full page” menu item button

### ISSUE THREAD

**Issue by jesus2099** [mozilla-services/screenshots#3605]
Unlike what I can see [over there](https://github.com/mozilla-services/screenshots/issues/2157#issuecomment-287950610), I have no such **Save full page** feature in my Firefox v56:

![image](https://user-images.githubusercontent.com/1401086/31376654-f6366126-ada5-11e7-8d4d-5a28e72f4e40.png)

**Comment by SoftVision-EmilPasca** [comment]
@jesus2099, thanks for reporting this.
 The "Save full page" option is not yet available in Firefox 56. However, it is available on latest [Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/).
