### ISSUE TITLE
Title input box is wrongly truncated at its front margin when editing the end of a long title

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3608]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots build v. (22.0.10476) installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a website that has a long title (eg. https://www.youtube.com/watch?v=cVSSMGDciHQ). 
3. Perform a shot on the website and save it.
4. Go to the shot page and click its title.
4. Move the text caret to the end of the title.
4. Observe the appearance of the front margin.

[Expected result]:
- The front margin of the "Title" field is fully displayed.

[Actual result]:
- The front margin of the "Title" field is truncated.

[Notes]:
- This issue also affects the position of the saved page domain.
- This issue is also reproducible with shorter titles if the browser window is resized.
- This is also reproducible on Firefox 56.0.
- Here is a screen recording of this issue:
![screenshots - long title - field 2](https://user-images.githubusercontent.com/31244235/31396206-6f71ecbe-adeb-11e7-8d29-7bfa91d69643.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
