### ISSUE TITLE
[FxA] Private shots

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3611]
Right now, anyone who discovers a shot URL can view it.

We could add a private mode option, where the URL wouldn't work unless you were on the device that created the shot.

Private mode would make FxA-based sharing interesting, too.

**Comment by wresuolc** [comment]
Related to #2337

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
