### ISSUE TITLE
Replace pageshot.net with a static page

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3613]
- Marking needs:product for what you want the page to say
- I'm assuming this is English only?
- Ian wanted to do some redirects.  Are you thinking a simple redirect and let screenshots sort out 404s and such?
- How long does this page last?

Timeline:  We'd like to have this done by halloween

**Comment by ianb** [comment]
Here's the copy I'm planning to use, probably just yanking the 404 page as the basis:

---

## Thank you for being a part of the Page Shot experiment!

Hundreds of thousands of you used Page Shot during its time as a [Test Pilot](https://testpilot.firefox.com/) experiment. Enough people that we decided to make it a part of everyone's Firefox experience!

Page Shot has been renamed [Firefox Screenshots](https://screenshots.firefox.com/) and is part of Firefox 56+. If you are using Firefox 56 you'll see the familiar button. If you are on Firefox 57+ you'll find Screenshots in the URL menu:

![image](https://user-images.githubusercontent.com/44390/32567696-aa462100-c481-11e7-90b6-4f49c20f1b4b.png)

To see more check out the [tour](https://screenshots.firefox.com/#tour) or view the [introduction](https://screenshots.firefox.com/#hello).

If you used Page Shot, your shots are still available (unless they've expired), and your Page Shot account has been migrated over the Firefox Screenshots.

**Comment by ianb** [comment]
I've made a static page that looks like this:

![image](https://screenshots.firefoxusercontent.com/images/2cd628d5-9360-4804-867a-1c3bdf5870d9.png)

@johngruen : does that look okay with you?

**Comment by johngruen** [comment]
SHIP IT!

**Comment by ianb** [comment]
I've created [Bug 1415983](https://bugzilla.mozilla.org/show_bug.cgi?id=1415983)
