### ISSUE TITLE
New tab opened when saving a shot is not of the same container type as the content page

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3615]
STR:
1. Open a container tab in Nightly.
1. Take a Screenshot.
1. Press the Save button.

Result:
New default (no container) tab opens.

Expected/Desired:
New tab of same container type as the content page from step 1 opens.

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce this issue on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64 with the latest Firefox Release(56.0), latest Firefox Beta(57.0b6-20171005195903) and also with the latest Nightly(58.0a1-20171010220102).

**Comment by wresuolc** [comment]
58 to investigate, but it might be a Firefox bug

**Comment by groovecoder** [comment]
Near as I can tell, [the `takeShot` function](https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/background/takeshot.js#L5) needs to keep track of `sender.tab.cookieStoreId` and pass it to `browser.tabs.create()`.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
