### ISSUE TITLE
Expiry time briefly displays the previous selected period when saving

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3618]
[Affected versions]:
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots build version (22.0.11929) installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website.
2. Perform a shot and save it.
3. Click on the "expires in 14 days" button.
4. Change the expiry period. 
5. Click the "Save" button and observe the new period displayed in the expiry button.

[Expected result]:
- The expiry period is correctly displayed.

[Actual result]:
- The previous expiry period is briefly displayed.

[Notes]:
- This is also reproducible on Firefox 56.0.
- Here is a screen recording of this issue:
![time expiry](https://user-images.githubusercontent.com/31244235/31442285-924dcdf8-ae9e-11e7-82c5-2680530476f8.gif)

**Comment by 6a68** [comment]
Related to #3255

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
