### ISSUE TITLE
Do A/B test on share icon

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3620]
We've gotten feedback that the share icon doesn't seem right (#3578). We'd like to do an A/B test on the share icon, using the current icon (or [something closer to Photon](http://design.firefox.com/icons/viewer/#share)), and a Google-style icon (like the one in #3578)

Note our current A/B test system should work fine for this (more info in `ab-tests.js`)

**Comment by johngruen** [comment]
@youwenliang can you provide a good, generic SVG icon? We want to conduct an A/B test to see which one works better.

**Comment by youwenliang** [comment]
Google Style share button:
https://www.dropbox.com/s/lclp6ucc8pvrvhv/share-google.svg?dl=0

**Comment by johngruen** [comment]
@youwenliang Thanks! We'll A/b test to see which is more effective

**Comment by 6a68** [comment]
@youwenliang The share icon link no longer seems to be working. Could you check the permissions and URL are correct?

**Comment by youwenliang** [comment]
Here a new link:
https://www.dropbox.com/s/y2naygmg76kiwsx/share-google.svg?dl=0

**Comment by rugk** [comment]
See also https://github.com/mozilla-services/screenshots/issues/3578#issuecomment-352225856 for a new icon suggestion:
![grafik](https://user-images.githubusercontent.com/11966684/34078395-d3f210fc-e319-11e7-8d75-8c9e4324c081.png)
