### ISSUE TITLE
Share vs Download as primary call to action on shot page

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3621]
Right now, the Download button is the primary call to action on the shot page.

What if we made the Share button the primary CTA instead?

Could be very A/B testable

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
