### ISSUE TITLE
Strict-Transport-Security response header's max-age is set to 1000 days instead of 24 hours

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3622]
Currently the value for the `strict-transport-security` response header is `max-age=86400000`, which works out to be about 1000 days.  It should be 86400 seconds (24 hours).

The value is set in `addHSTS` in `server.js`.

**Comment by ianb** [comment]
@g-k: do you have a recommendation for the value of this header?

**Comment by g-k** [comment]
@ianb We usually start low like <24 hours and increase it from there if we don't see any errors. That does seem high. I think we usually stay within one year.

Are we getting HSTS errors?

@relud or @milescrabill Is that the right value or do we have extra zeroes in the config?

**Comment by chenba** [comment]
The comment in the code states 24 hours, but I think the author thought the value need to be in milliseconds.

**Comment by ianb** [comment]
Oh yeah, seconds-vs-milliseconds is probably just what happened, I think we can just fix this then.
