### ISSUE TITLE
Remove X-Powered-By header

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3634]
Per [this report](https://github.com/mozilla-services/foxsec-results/blob/master/baseline-scan/screenshots.firefox.com/2017-10-13), we still have that header for Express. We have the code that I though was supposed to remove it (`app.disable("x-powered-by");`), but for some reason it doesn't work.

**Comment by Apply55gx** [comment]
Hmm. The link to the report seems to be outdated. @ianb

**Comment by ianb** [comment]
Duplicate of #2352
