### ISSUE TITLE
User reported issue w/Instagram

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3641]
Users on Windows 7 reports that buttons aren't rendering on instagram: 

> theres not really anything to take screenshot of, the square is there but thats it (the options etc arnt). I was able to screenshot facebook and youtube (just tried it to make sure it was just on insta in my case).

**Comment by SoftVision-CosminMuntean** [comment]
I haven't managed to reproduce this issue on Windows 7 x64. I have tested this on latest Firefox (56.0) release, Beta 57.0b8 and latest Nightly (58.0a1) build. 
Screenshots works as expected and all the buttons are correctly displayed on Instagram. I wonder if the user can reproduce this issue in Safe Mode. Probably he has an add-on that is in conflict with Screenshots.?
However, I will keep on eye on this.

**Comment by johngruen** [comment]
Seems to be reproducible on individual posts and not hte feed.

**Comment by ianb** [comment]
On individual posts the selection shows up offset up.  E.g., I click on the image and the selection is sized like the image, but offset up by 50ish pixels. Then if I save the image is saved correctly! Dragging is similarly weird.

So: something is off in the math about how we render the selection (and maybe something weird about mousedown coordinates in dragging).

**Comment by chenba** [comment]
When I click on the image to select it, the browser displays a horizontal scroll bar, and that is what pushes the selection up.  The selection frame's width is causing the scroll bar to appear.

**Comment by chenba** [comment]
When viewing an Instagram post, Firefox always show the vertical scroll bar, even if the content is not scrollable.  Because of this, the width used for the selection frame is too wide, so then the horizontal scroll bar appears as a result.

**Comment by chenba** [comment]
A way to see this issue on other sites is to either go to a longish page or resize the window so that there's a vertical scroll bar but not a horizontal scroll bar.  Start Screenshots and select an element.  Notice that the horizontal scroll is displayed.
