### ISSUE TITLE
webextension strings sometimes get perma-cached

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3661]
Not sure what the underlying issue is, but it seems like changing the webextension strings and bumping the version number isn't enough to pick up new strings. However, if I navigate to the messages.json URL, I do see the correct strings. Some cache seems to be stale. Switching between dev edition and nightly clears the cache.

kmag suggested that we need to pass the version number to the startup method; need to dig into this and ask him when I understand the code a little better.

This line might be relevant: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#2029

**Comment by johngruen** [comment]
"someone ask aswan to ask kris to explain it"

**Comment by chenba** [comment]
I've found that the strings get updated reliably on the second restart.  That is, make some changes, `bin/run-addon`, exit, `bin/run-addon` once more.  I noticed that the version string passed in the startup data does not change while the version string in the manifest changes during the restarts.  (Occasionally I saw that the version string from deviceInfo, which uses browser.runtime.getManifest(), being different than the version in manifest.json on disk...)

I don't understand how XPIProvider's startup would help here.  That's what is calling bootstrap's startup looks like?  And bootstrap's startup receives the version number in the startup data so I don't understand the part where "we need to pass the version number to the startup method".

**Comment by 6a68** [comment]
bootstrap's startup receives the version number, but we don't pass that number into the webextension's startup method. we probably need to ask in #teamaddons to understand how to correctly pass in that number

**Comment by 6a68** [comment]
probably [this](https://github.com/mozilla-services/screenshots/blob/master/addon/bootstrap.js#L182) is the line that needs to be changed - but there are just a handful of 'embedded webextensions' in existence, so the (internal) APIs we're using aren't really documented in the same way that public webextension APIs are

**Comment by chenba** [comment]
EmbeddedExtension.startup doesn't take a version number as one of its params though.  It only takes the startup reason.

**Comment by 6a68** [comment]
You're right @chenba, the version number is stale. I think this may be an artifact of using the unmaintained `jpm` tool inside `./bin/run-addon`. If I bump the version number, create the xpi via `make unsigned_bootstrap_xpi`, then manually install it via `about:addons`, the version number passed to startup is correct.

The best long-term solution is to get away from jpm by removing the bootstrapped part of the webextension (#3875). Closing this, as it seems unlikely to affect real world users.
