### ISSUE TITLE
We're not using the official Twitter logo!

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3664]
Seen on Twitter, of course:

![screenshot-2017-10-23 firefox and screenshots or screenshot - twitter search 1](https://user-images.githubusercontent.com/3323249/31910547-d726c4b8-b80b-11e7-8037-87aa66829c5f.png)

**Comment by pdehaan** [comment]
FWIW, https://about.twitter.com/en_us/company/brand-resources.html

**Comment by Logan1x** [comment]
Hey, @johngruen  I would like to work on this issue.

**Comment by johngruen** [comment]
Thanks @Logan1x!
