### ISSUE TITLE
Put some kind of anti-spam measure in front of screenshots-report@

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3666]
This list is getting a lot of spam.  Can we put a fake email in there and some kind of onclick JS that decrypts it to the real one?  I think AMO does this with success

@eleemoz -- this would prevent anyone who wasn't executing JavaScript in their browser from using the link.  Is that a problem?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
