### ISSUE TITLE
Screenshots made on websites that have hyphens in domains are displayed as though you are not the owner of them

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3667]
[Notes]:
- This issue was reported in [bug 1410639](https://bugzilla.mozilla.org/show_bug.cgi?id=1410639).

[Affected versions]:
- Firefox 56.0 and up
- Screenshots 10.12.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the latest Nightly browser and navigate to "https://la-cascade.io/" website.
2. Click the "Page Action" button from the end of the URL bar.
3. Click the "Take a Screenshot" button and save a selection on the website.
4. Observe the saved shot preview page.

[Expected result]:
- The page is correctly displayed.

[Actual results]:
- The page is wrongly displayed like you are not the owner of the shot.

[Additional Notes]:
- Here are some examples of websites:
http://www.cabinet-stomatologic.com/
https://corpurideiluminat-tlb.ro/
https://www.paris-web.fr/
- Here is a screen recording with the issue:
![screenshots on cascade website](https://user-images.githubusercontent.com/19226534/31954297-e52e827a-b8ed-11e7-9334-646d31905821.gif)

**Comment by chenba** [comment]
This is caused by the regex for `maybeShotId` at https://github.com/mozilla-services/screenshots/blob/5474894acccefa7233408639608e584ab7641c45/static/js/wantsauth.js#L28

When that isn't sent during the auth process, the ownership check is skipped.
