### ISSUE TITLE
document how we'll do A/B tests

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3670]
GA custom dimensions? GA experiments?

**Comment by ianb** [comment]
There are some docs in [metrics.md](https://github.com/mozilla-services/screenshots/blob/master/docs/METRICS.md#ab-tests)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
