### ISSUE TITLE
Instrument interaction time in shot creation flow

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3673]
As part of the RAIL perf guidelines, we want to ensure the app responds in <100ms when the user clicks on a button.

I don't think it's possible to measure time from the page action click to the overlay being drawn, but we should be able to instrument time from click to paint for the other steps. Since all the frames live inside the same window, the `Performance` API should work fine.

I'm not sure how hard it'll be to instrument click to paint, but click to next callback might be a good enough proxy.

**Comment by chenba** [comment]
Related to #3395 since this is reviving the '/timing' endpoint.
