### ISSUE TITLE
Make ab-tests create 50/50 cohorts

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3674]
We should change ab-tests.js to do cohort selection, then 50/50 control/experiment (or 33/33/33 for three tests, etc).  The cohort selection might be 99/1, 90/10, 90/10 except only en-US, etc.

I think we should change from just `("control", experiment_name)` to `("excluded", "control", experiment_name)`.

**Comment by johngruen** [comment]
putting this in 58, but this is kick-outable
