### ISSUE TITLE
[Annotations][Enhancement] We should add a "Clear" button in order to reset all the changes made on the image

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3679]
[Notes]:
- I think this will improve the user experience since the user has to cancel the "Edit" page in order to rest the changes.

[Affected versions]:
- Nightly 58.0a1
- Screenshots 22.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
2. Click the "Edit Image" button and draw something on the shot.
4. Observe the edit tools.

[Expected result]:
- The "Clear" button is available.

[Actual results]:
- There is no "Clear" button in order to reset all the changes.

**Comment by niharikak101** [comment]
Can I get assets for this please @johngruen @youwenliang.

**Comment by youwenliang** [comment]
Here's a reset button icon: https://www.dropbox.com/s/bmdbkxmkdlqw7sb/reset.svg?dl=0
