### ISSUE TITLE
[FxA] The Firefox Accounts sign in no longer works

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3681]
[Affected versions]:
- Nightly 58.0a1
- Screenshots 22.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Click the "cogwheel" from the right corner of the page.
3. Click the "Sign In" button and enter a valid account.
4. Click the "Sign in" button.
5. Observe the browser behavior.

[Expected result]:
- You are successfully logged in.

[Actual results]:
- A blank page is displayed.

[Notes]:
- Also, you can't create a new account.
- If you refresh the blank page you get the following errors: 
![errors](https://user-images.githubusercontent.com/19226534/32057030-cc13dd44-ba6e-11e7-8973-a9abb0fca9d4.png)

- Here is a screenshot with browser console errors:
![fxa brwoser console errors](https://user-images.githubusercontent.com/19226534/32057034-cfa13718-ba6e-11e7-9a70-6227eb3053a4.png)

**Comment by niharikak101** [comment]
@SoftVision-CosminMuntean This should be working now! Can you test it? Thank you.

**Comment by chenba** [comment]
Adding this to current sprint since we already merged some code. 🤸‍♂️

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on latest Firefox Screenshots (31.3.0) dev version. Tested on Windows 10 x64, 7 x64, Mac 10.13 and Ubuntu 14.0.4.
