### ISSUE TITLE
"Error saving expiration" when trying to change the expiration

### ISSUE THREAD

**Issue by RalfJung** [mozilla-services/screenshots#3690]
I get an "Error saving expiration" when I try to change the expiration. This is using Firefox 57.0b12 on Linux.

I do have third-party cookies disabled, but https://github.com/mozilla-services/screenshots/issues/3581 is supposed to be fixed.

**Comment by johngruen** [comment]
I don't think we've deployed the fix yet...we will close this for now.

**Comment by RalfJung** [comment]
> I don't think we've deployed the fix yet

Ah, I see. Any ETA?

**Comment by 6a68** [comment]
I'd expect to see the fix out in the next few weeks
