### ISSUE TITLE
There is a noticeable delay until Screenshots overlay appears, when Screenshots is used on imdb.com website

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3692]
[Notes]:
- This issue is only reproducible with Screenshots 23.0.0 version. Is not reproducible with Screenshots 19.2.0 version.
- Probably the issue is also reproducible on more websites.

[Affected versions]:
- Nightly 58.0a1
- Screenshots 23.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 23.0.0 dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "http://www.imdb.com/".
2. Right click on the page and click the "Take a Screenshot" button.
3. Notice the time until the Screenshots overlay appears.

[Expected result]:
- The Screenshots overlay appears almost instantly.

[Actual result]:
- There is a noticeable delay until Screenshots overlay appears.

**Comment by chenba** [comment]
The overlay appeared with no delay for me.  (Windows 10, Nightly 58.0a1 64-bit)

**Comment by chenba** [comment]
Ah sorry, I was using the wrong version of Screenshots.

**Comment by chenba** [comment]
I just tried this with the correct version of Screenshots on Linux and Windows and I was not able to reproduce the issue.

**Comment by chenba** [comment]
@SoftVision-CosminMuntean How slow is this for you?  On Windows, it's relatively a little slower for me, but not unacceptably so.  On Linux there wasn't much of a difference.

**Comment by SoftVision-CosminMuntean** [comment]
I can reproduce the isssue using Screenshots 23.0. dev version installed from [**here**](https://screenshots.dev.mozaws.net/homepage/install-test-local.html).  The Screenshots overlay appears after ~2 sec on imdb.com using this version.
If you test this with latest Nightly (58.0a1) build where Screenshots version is 19.2.0, you can observe that the overlay appears almost instantly.

I can reproduce this issue on Windows 7 x64, Ubuntu 16.04 x64 and also on Mac 10.12.

**Comment by chenba** [comment]
The slight delay is also noticeable on https://news.google.com.

It's not quite as slow for me on imdb than what @SoftVision-CosminMuntean is seeing, but it's easily noticeable when comparing 23.x and 19.x back to back, @SoftVision-CosminMuntean pointed out.

**Comment by chenba** [comment]
The source of the lag is an _extra_ request for the content page.  During the first `unhide()` of the preselection frame, its URL is `about:blank`, and when the high contrast mode check is performed, the background image of the div (https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/selector/ui.js#L83) is the content page URL + '#'.  Thus the request.

**Comment by chenba** [comment]
@SoftVision-CosminMuntean An easy way to verify this is simply look at the network tab in dev tool when you open the Screenshots overlay.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba I just looked at the network tab and I compared the results using Screenshots 23.0.0 on imdb.com with cnn.com:
- Network tab on imdb.com when open Screenshots overlay:
![imdb2](https://user-images.githubusercontent.com/19226534/32486137-6cab7418-c3ae-11e7-97d7-e1b3f0d2ae65.png)

- Network tab on cnn.com when open Screenshots overlay:
![cnn](https://user-images.githubusercontent.com/19226534/32486143-6feadc36-c3ae-11e7-8fdb-a1b5b457d4a4.png)

I also tried to compare the results using Screenshots (19.2.0) from latest Nightly 58.0a1 build, but it seems that there is nothing displayed in Network tab when open Screenshots overlay.
Please let me know if you need more information or more testing.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Screenshots 23.0.0 dev version and is no longer reproducible. Marking as verified.
