### ISSUE TITLE
Do A/B test on 'Download Firefox' shot page UI

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3694]
I think @johngruen was thinking of some alternate UI by @sevaan to A/B test.

Related: should we close the display ad bug (#3253), which would remove the Firefox upsell that we're now going to A/B test?

**Comment by johngruen** [comment]
Let's leave that open for now, but i'll kick it into the backlog. I'll ask @sevaan to port his proposals over to to screenshots.

**Comment by sevaan** [comment]
Proposals:

- [Notification Bars](https://mozilla.invisionapp.com/share/EGE9VJYYV)
- [Button in the Footer](https://mozilla.invisionapp.com/share/XUE9VKCDW)
- [Interstitial](https://mozilla.invisionapp.com/share/H6E9VKLUD)
- [Spec](https://mozilla.invisionapp.com/share/TCE9VKR7N)

**Comment by 6a68** [comment]
@johngruen which of the variations would you like to test?

**Comment by 6a68** [comment]
per john in IRC: notification bar variants to start, with slightly bigger font (16px?)

**Comment by johngruen** [comment]
@6a68 that github net neturality font was 14px. Let's do that :)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
