### ISSUE TITLE
Let users see the reach of their shots

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3695]
In order to produce a more viral product, we should convey the viral reach of shots to both shot owners and viewers. We could start by displaying number of views here.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
