### ISSUE TITLE
[RTL] Apply patches from #3241 and #3514 for the Save, Download & Cancel buttons when screenshotting in "Save visible" and "Save full page" modes

### ISSUE THREAD

**Issue by ItielMaN** [mozilla-services/screenshots#3710]
Issue #3241 fixed the Save, Download & Cancel buttons when screenshotting in a hands-free mode, and issue #3514 fixed the padding of the cloud icon in the Download button.
These fixes should be applied to the other 2 modes ("Save visible" and "Save full page").

**Comment by chenba** [comment]
The padding fix from #3514 is no longer applicable now that `<img>` is used for the icon instead of a background image.
