### ISSUE TITLE
The "Download-Only mode" warning is not stuck to the bottom of the page when scrolling

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3716]
[Affected versions]:
- Nightly 58.0a1
- Screenshots 23.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 23.0.0 dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.
- The "Never Remember History" option set in "about:preferences#privacy" page.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to imgur.com.
2. Right click on the page and click the "Take a Screenshot" button.
3. Perform a selection on the page.
4. Observe the "Download-Only mode" warning while scrolling the page.

[Expected result]:
- The "Download-Only mode" warning is stuck on the bottom of the page.

[Actual result]:
- The "Download-Only mode" warning is not stuck on the bottom of the page.

[Notes]:
- Here is a screen recording with the issue:
![download-only mode warning](https://user-images.githubusercontent.com/19226534/32330993-61a28498-bfea-11e7-9d23-957ed20535a8.gif)

**Comment by johngruen** [comment]
should be fixed by #3705

**Comment by 6a68** [comment]
#3705 landed; closing.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using latest Screenshots 23.0.0 dev version and is no longer reproducible. The "Download-Only mode" warning is moved to the bottom of the page if the page is scrolled. Marking as verified.
