### ISSUE TITLE
A "TypeError: result is undefined" error is displayed after saving a shot (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3722]
[Affected versions]:
- Nightly 58.0a1
- Screenshots 23.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the [Screenshots 23.0.0 dev version](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.
- One shot was already saved on the session.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to any website.
2. Perform a selection and save it.
3. Observe the browser behavior.

[Expected result]:
- The shot is successfully saved and no errors are displayed.

[Actual result]:
- The shot is saved but a "TypeError: result is undefined" error is displayed.

[Notes]:
- The issue is not reproducible on stage or production versions.
- If you are using a new session, the error is displayed only for the second saved shot (because of #3707).
- Here is a screenshot with browser console errors:
![error when saving a shot](https://user-images.githubusercontent.com/19226534/32367660-8df86dcc-c08b-11e7-8085-2eae3a4f56e5.png)

- Here is a screen recording with the issue:
![error afer saving a shot](https://user-images.githubusercontent.com/19226534/32367666-9431aa8c-c08b-11e7-9519-2e21d901d953.gif)

**Comment by chenba** [comment]
This is no longer reproducible with the latest dev version of the addon (`master` @ rev `328696f`).

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on latest Screenshots 23.0.0 version. Marking as verified.
