### ISSUE TITLE
Download button does not follow Firefox option "Always ask you where to save files"

### ISSUE THREAD

**Issue by authentictech** [mozilla-services/screenshots#3724]
In a previous incarnation during the experiment phase, when I clicked the download button I was presented with a save location dialogue in keeping with the Firefox setting "Always ask you where to save files".
Now, Screenshots will always save the image in my "Downloads" folder. I do not wish to save any files in this folder as I have a folder structure specifically created for screenshots so I need to be able to select the folder. Thanks.

**Comment by wresuolc** [comment]
duplicate of #3488 

Thanks for filing, but duping this to existing bug
