### ISSUE TITLE
Show downloaded shots in My Shots?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3725]
Looking at the usage and retention data in Data Studio, downloaders stick around more than uploaders, and we have more downloads than uploads daily.

What if we kept Screenshots downloads in a profile-specific folder, then displayed downloaded images in My Shots?

**Comment by johngruen** [comment]
@clouserw this should have needs:priority, not needs:product

**Comment by johngruen** [comment]
Also should be triaged into the Product Backlog

**Comment by johngruen** [comment]
I don't actually ever see this happening
