### ISSUE TITLE
get "firefox export + file a bug" script working

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3730]

**Comment by Standard8** [comment]
@6a68 I think I considered adding it, but it wasn't necessary at the time.

export_mc.py was an extraction of the github bits from Hello's [create_release.py](https://github.com/mozilla/loop/blob/master/bin/create_release.py) - the rest of that script is about filing bugs, which is what you want.

You'll need to add bugsy and maybe one or two other things to your virtualenv.

**Comment by 6a68** [comment]
@Standard8 Aha, that's the script I was looking for. Thanks for the link :+1:

**Comment by ianb** [comment]
Given ship2gecko (#3953) has this feature, I think we'll go that direction and track it in that bug.
