### ISSUE TITLE
Fix Selenium test

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3734]
The selenium test has been busted in Nightly for a few days. Figure out if it's us or Firefox.

**Comment by 6a68** [comment]
Looks like the 11/2 morning nightly build works, and the 11/2 evening nightly build is busted.

I'm not sure how to pass a mozregression binary to `npm run test`, so I'll get my m-c updated locally and bisect with artifact builds.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Any idea how to narrow the regression range further? I tried downloading individual builds from treeherder, but I'm having trouble getting the 11/2 am treeherder build to work, so maybe the config is different than regular nightly. Any ideas?

I think this is the right range of builds in treeherder: https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&fromchange=252a8528c5ab4affc2742e7ccfe4ef4aa5ee42f8&tochange=66f496680fae6e7d8f02bc17ff58b923

**Comment by SoftVision-CosminMuntean** [comment]
@6a68 I can try to narrow the regression, but can you give me some steps and the expected behavior in order to figure out which is the bad build and the good build? I haven't work with selenium tests until now.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks! I will give a try tomorrow since it's kinda late here.

**Comment by chenba** [comment]
This issue is caused by the patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1321516

I filed a PR to opt out of using that feature: https://github.com/mozilla-services/screenshots/pull/3737

**Comment by chenba** [comment]
This issue is caused by the patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1321516

I filed a PR to opt out of using that feature: https://github.com/mozilla-services/screenshots/pull/3737

**Comment by chenba** [comment]
This issue is caused by the patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1321516

I filed a PR to opt out of using that feature: https://github.com/mozilla-services/screenshots/pull/3737
