### ISSUE TITLE
Dynamicity + Privacy + Server error

### ISSUE THREAD

**Issue by rayman89** [mozilla-services/screenshots#3740]
I think it would be better, to make the app/addon more dynamic, if we have the option to auto copy to clipboard when you use left mouse button to select the area and give the options to cancel/save if you use right mouse button for example that way the probably make it a lot more useful IMO. Probably an other easy at hand shortcut could be done to take an screenshot of the whole page area istead of having to draw the rectangle yourself for that.

I also noticed that when you wanna check the privacy aspects of the addon/app they are not clearly specified for it. The page sends you to a general privacy policy page that is the same for browser and cloud and does not say what info you get from us using this specific addon/app and what is done with that info.

When clicking on my captures without having any capture it tried to send me to https://screenshots.firefox.com/shots5 and that page said server error.

**Comment by wresuolc** [comment]
Hi,

We're tracking a keyboard shortcut in https://github.com/mozilla-services/screenshots/issues/2491 .  In Firefox 58 you'll see a full screen option in the top right once you start taking a screenshot.  We're not going to do separate actions depending on which mouse button is clicked.

There is documentation at https://github.com/mozilla-services/screenshots/tree/master/docs including what analytics are collected.

I'm assuming the '5' in your URL is a typo in which case the /shots page looks empty without any shots, but that's as designed.

**Comment by rayman89** [comment]
It's a typo but the page is not blank i get the mentioned error.
