### ISSUE TITLE
The Image Height Limit Can Be Bypassed by Dragging the Hightlight Rectangle

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3745]
### STR

1. Go to a loooong page (some page with a lot of user comments should work...)
1. Start Screenshots
1. Start a selection rectangle by clicking on an element or dragging.
1. Now drag the bottom edge of rectangle down by dragging
1. Save the shot

### Result

Shot is saved as selected.

### Expected

Shot is cropped to the image height limit.

**Comment by ianb** [comment]
We discussed this and decided that if someone wants to put forward the considerable effort to select a very large rectangle, we should let them. Power to the people! No gods, no masters!
