### ISSUE TITLE
Edit Name behaviors

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#3751]
If I click on my shot's name to edit it, it should highlight the whole input field rather than putting the typing cursor to the front.

Another issue is that if I click the name again, it's showing the last name I edited, not the current one, as shown below: (And the page title won't change if I edit the name)
![001](https://user-images.githubusercontent.com/8919308/32718575-7b9e3c46-c898-11e7-8596-09c47f18d32c.gif)

There's also an issue around input box length, it should have a fixed width instead of growing with the input content. Right now it's causing some issues if name is too long.

![002](https://user-images.githubusercontent.com/8919308/32718586-85d74ffe-c898-11e7-8fdb-26c8112167c1.gif)
(Box width changes)

![003](https://user-images.githubusercontent.com/8919308/32718587-85fc908e-c898-11e7-9f7a-342176a06b86.gif)
(Long text box issue)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
