### ISSUE TITLE
Remove iconPath-related messages from bootstrap.js

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3756]
This is a followup to #3747 (00f04091ffa4200009dd6b9bfe38ccdc34370157).

Now that we don't dynamically set the icon for onboarding, we can remove all icon-resetting code from bootstrap.js.

See also [Bug 1412377](https://bugzilla.mozilla.org/show_bug.cgi?id=1412377) (change it all to a pageAction)

**Comment by chenba** [comment]
This also follows #3760

**Comment by chenba** [comment]
Important Note: with this patch, the Screenshots page action button would be moved to a different position.  There's some discussion in [Bug 1412377](https://bugzilla.mozilla.org/show_bug.cgi?id=1412377) about this.

**Comment by chenba** [comment]
This is currently blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1419842.  See comments here: https://github.com/mozilla-services/screenshots/pull/3795#issuecomment-346440837

**Comment by chenba** [comment]
[Bug 1419842](https://bugzilla.mozilla.org/show_bug.cgi?id=1419842) has been resolved.
