### ISSUE TITLE
Batch events and timings

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3757]
Right now we get events (and with #3727 timings) one-by-one to our /events and /timing endpoints. It would be better to batch these, since some events happen very quickly in succession. Batching can be as simple as:

```js
let pendingEvents = [];
let eventTimer = null;
function sendEvent(event) {
  // do normal stuff to prepare the event
  // set the time of the event
  pendingEvents.push(event);
  if (!eventTimer) {
    eventTimer = setTimeout(() => {
      eventTimer = null;
      flushAllEvents();
      pendingEvents = [];
    }, 1000);
  }
}
```

We should set [queueTime](https://github.com/peaksandpies/universal-analytics/blob/master/AcceptableParams.md#queue-time) to backdate the events. Note that means we should record how long it was between `sendEvent()` being called, and `flushAllEvents()` (per-event).

**Comment by 6a68** [comment]
Rather than using `setTimeout`, this seems like a good use case for [`window.requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback).
