### ISSUE TITLE
Sticky elements break full-page-screenshot function

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [mozilla-services/screenshots#3759]
using the screenshot tool trying to take a picture of the whole website causes problems on some websites with sticky elements (eg elements that follow you as you scroll)

example: https://www.youtube.com/user/GermanLetsFail/videos
https://screenshots.firefox.com/n6w9646SFUsFbOsC/www.youtube.com

Firefox 57.0 
Windows 10

**Comment by johngruen** [comment]
duping this to #3124. Stupid CSS!
