### ISSUE TITLE
The Screenshots icon is no longer displayed in "Page Actions" menu after the browser is opened (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3760]
[Notes]:
- The Screenshots icon is displayed after the add-on is used, but disappears after restarting the browser. 
- The issue is not reproducible on Screenshtos stage version. Probably is something related to #3542
- The issue is not reproducible on older versions of Nightly (eg: build from 2017-10-25). Considering this I have performed a regression using mozregression tools. Here are the results:
Last good revision: 6a3ca81dc56ab7687ca70b1b98fbe397aa3fa388
First bad revision: 9f83f552a6118f1061ee5afd87578d9b5b82b308
Pushlog: https://goo.gl/G5NJkk
From the provided pushlog it seems that the [bug 1395387](1395387) introduced this issue.

[Affected versions]:
- Nightly 59.0a1
- Dev Edition 58.0b1
- Screenshots 23.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 23.0.0 dev version installed  from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Click the 3 dots button from the end of the URL bar.
3. Observe the Screenshots icon from "Page Actions" menu.

[Expected result]:
- The Screenshots icon is correctly displayed.

[Actual result]:
- The Screenshots icon is no longer displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
![screenshots icon](https://user-images.githubusercontent.com/19226534/32790920-604701b4-c968-11e7-907e-a6fd11bf0d6e.gif)

**Comment by johngruen** [comment]
@chenba i think this is cleanup from #3747
