### ISSUE TITLE
Pictures that havent been rendered are missing

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [mozilla-services/screenshots#3761]
pictures that firefox hasnt rendered yet seem to be missing under some circumstances in the final screenshot when using the full-website-screenshot function.

i took this screenshot https://screenshots.firefox.com/x7G9zpYk8i4L4nau/www.youtube.com without scrolling. that means only 2 lines of thumbnails were visible on my screen. there are however 2 more lines in the screenshot. i guess firefox just prerenders pictures to some degree and the missing ones from the next lines were too far away to be prerendered ?
direct link: https://www.youtube.com/user/GermanLetsFail/videos

Firefox 57.0
Windows 10

**Comment by sdfasdfgawe456h4356** [comment]
#2996

**Comment by wresuolc** [comment]
This is working as designed right now.
