### ISSUE TITLE
Suggestion: include elements that will be loaded when you scroll down the website

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [mozilla-services/screenshots#3763]
many websites feature a functionality where the website will be loaded gradually as you scroll down in order to speed up loading and save bandwidth.
if i want to take a screenshot of such a website whole i have to scroll down all the way which can take ages in some cases.
my suggestion is: screenshot the WHOLE website including all the bits that would be loaded only once you scroll down. eg. make the screenshot tool scroll down all the way. this can ofc be optional. via a tick-box or smth.

example: https://screenshots.firefox.com/x7G9zpYk8i4L4nau/www.youtube.com
this youtube channel has 1000s of videos i might want to make a screenshot with all of them.
i would now have to scroll down for like 10 minutes or smth with the way the screenshot tool currently works.

**Comment by wresuolc** [comment]
Thanks for filing this.  The way Screenshots is working today is as intended.  It won't take shots of non-loaded content.
