### ISSUE TITLE
Add config parameter to remove save screenshots online button

### ISSUE THREAD

**Issue by alexhass** [mozilla-services/screenshots#3770]
Firefox Screenshots is a nice feature, but there are serious privacy issues.

I'd like to disable the **upload to cloud** button(s). So that users cannot upload the screenshots. Saving locally is ok.

I only found prefs to disable the screenshot extension system wide, but not for the insecure upload button. Can you add an about:config setting to disable the upload to cloud features, please?

**Comment by yamlfd** [comment]
Next release is a good priority

**Comment by 6a68** [comment]
This was implemented in #4006. The pref is `extensions.screenshots.upload-disabled`, and it is currently in Nightly. It'll be in release as of version 60.
