### ISSUE TITLE
Cannot Take a Shot of My Shots Page from Context Menu but 👍 with Page Action

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3778]
STR

1. Go to My Shots
1. Right click on the page and then select "Take a Screenshot"
1. Get notification about the page is not being a standard page

However, if you open Screenshots from page actions, you can take a shot of the page.

**Comment by 6a68** [comment]
@ianb Do you recall why shots were disallowed on the My Shots page to begin with? This was originally added in #1350, but there's no discussion about the reasoning. Is the idea to ensure that shots are tied to their original domain? (If so, I can file a bug to disallow taking shots via the `file` scheme.)

**Comment by wresuolc** [comment]
duplicate of #4675
