### ISSUE TITLE
Practice rolling back a production-like database

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3782]
Today we talked about rolling back 23 to 22, but it turned out some unexpected complexity was lurking in that option.

Let's spin up a copy of the production stack and practice rolling forward and backward with our friends in ops.

Bonus points if we can generate a production-scale test dataset, so that we can look for any bugs that will only hit us at scale.

**Comment by johngruen** [comment]
Lets use this as a tracking issue to define what an admin panel would need in terms of features.

@relud when could we do this?

**Comment by relud** [comment]
today, tomorrow, or the weeks before and after austin, or in austin if people have time.

**Comment by johngruen** [comment]
@6a68 @ianb i'll leave it to you guys...

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
