### ISSUE TITLE
Script errors using Firefox Screenshot utility. 

### ISSUE THREAD

**Issue by Yankeese** [mozilla-services/screenshots#3784]
Does anyone else experience this?
![ff_ss_02](https://user-images.githubusercontent.com/33699056/32852776-ff8cea10-ca06-11e7-94ef-0be92dd4c829.jpg)

**Comment by 6a68** [comment]
@Yankeese Hi, are you seeing this on just this one specific page, or on multiple pages?

What addons do you have installed? Could you try again with your addons disabled, and let us know if the problem goes away?

**Comment by wresuolc** [comment]
Also, what version of Firefox?

**Comment by Yankeese** [comment]
Firefox 57.0, the newest release.  Regarding add-ons, the problem was sporadic even with add-ons enabled, so disabling them won't tell me anything. I'm going to be out of town until the weekend. Can't test it until then. Sorry for the delay. Your replies were caught in my spam filters.
