### ISSUE TITLE
Saved shots, add no longer working

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-services/screenshots#3789]
Hi, I'm still using the older version via Firefox 55 because for various reasons I'm not ready to update yet, and suddenly it can't find any of my older shots even though they are still exist and it can't take new ones. It says "Page Shots is out of order." I knew I will have to update eventually, but is there any way I can get the overview back or I can get a working version at least temporarily? I didn't change anything on my end and didn't delete any cookies or cache or anything.

**Comment by newsjunkie247** [comment]
It redirects to https://screenshots.firefox.com/#tour even though I have several shots archived. I think it has something to do with the pageshots.net/screenshots.com change. Is there anyway to update the old add-on so it can keep working for a while?

**Comment by johngruen** [comment]
So we disabled the Page Shot service (the legacy service from Test Pilot) yesterday, unfortunately you'll need to upgrade Firefox. Your shots will be waiting for you. You can upgrade to 56 and not lose legacy add-ons but still get your shots back!
