### ISSUE TITLE
how to generate and show "save as image" links on a page ?

### ISSUE THREAD

**Issue by mathieubossaert** [mozilla-services/screenshots#3799]
Good morning,

I'm using a dashbord tool (metabase) and I would like to use Screenshots to purpose a kind of "export as image" feature for the shown charts.

I read here that a link is generated when user clicks on the "download" button.

https://github.com/mozilla-services/screenshots/tree/master/addon/webextension#communication

I would like to know if ther is a way to calculate this url for a given div, containing my chart and show it on my page to easyly save my charts as pictures.

Thanks a lot.

**Comment by wresuolc** [comment]
The URLs are deliberately not based on the screenshots taken so this can't be done
