### ISSUE TITLE
Feature request: save screenshot as SVG

### ISSUE THREAD

**Issue by hauberg** [mozilla-services/screenshots#3801]
The screenshots feature of Firefox 57 works great, but it only saves to PNG. Since most of the underlying contents of which a screenshot is taken is actually vector graphics, I guess it should be feasible (probably not easy, though) to save the screenshot as an SVG file. This would be an awesome feature (esp. for screenshots involving text).

**Comment by ianb** [comment]
We don't have any APIs available to us in Firefox for generating an SVG I'm afraid.

We do have a backlogged feature we want to add to keep the text (the functionality is in the code, but it overcaptured text and we had to remove it for release).
