### ISSUE TITLE
Suggestion: Button moved out of "page action" menu

### ISSUE THREAD

**Issue by royjor2016** [mozilla-services/screenshots#3802]
With the latest 57.0, the screenshot button is hidden under the "page action" menu. This means two clicks for each screenshot taken. What a waste of time and effort! Even more so when the interface is so slim and the icons are so small, such that it takes extra unnecessary effort to locate the button each time.

Please consider moving the button back to the toolbar, or come up with a keyboard shortcut.

Thank you very much!

**Comment by chenba** [comment]
@royjor2016 There are a couple alternatives.  You could use the right click context menu, although this still requires two clicks.  Another option is to add the Screenshots page action icon to the URL bar.  You can do that by right clicking on the Screenshots icon in the page actions.

Keyboard shortcut is tracked at #2491

**Comment by royjor2016** [comment]
@chenba Thanks a lot! This is exactly what I'm looking for, one click to the icon!

Didnt know I could right click on a cascading menu (seems counter-intuitive coz there had been hardly any right click menus on menus i guess?)

**Comment by royjor2016** [comment]
@chenba Thanks a lot! This is exactly what I'm looking for, one click to the icon!

Didnt know I could right click on a cascading menu (seems counter-intuitive coz there had been hardly any right click menus on menus i guess?)
