### ISSUE TITLE
Copy to clipboard and paste feature.

### ISSUE THREAD

**Issue by QWERTYUIOPYOZO** [mozilla-services/screenshots#3803]
Needs to go beyond having download and save to cloud. It should have a copy and paste feature to paste feature to paste directly into other programs / websites. Additionally, it should have a preference to allow automatic copying to clipboard.

**Comment by chenba** [comment]
Hi @QWERTYUIOPYOZO, copy to clipboard has been implemented for #2582.  (It's not released yet.)
