### ISSUE TITLE
Device ID in Google Analytics for Image Requests are Not Hashed

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3804]
When a request is handled, if the device id is found, `req.userAnalytics` is established on https://github.com/mozilla-services/screenshots/blob/e56650dc51b470b26754e593f0c9f83ca2c79a9e/server/src/server.js#L214

The one place where this might be used is in the `/images/:imageid` request handler:
https://github.com/mozilla-services/screenshots/blob/e56650dc51b470b26754e593f0c9f83ca2c79a9e/server/src/server.js#L855

However, if `req.userAnalytics` wasn't created, then the UA instance is simply created with `analytics = ua(config.gaId);`, which doesn't include any sort of user info.

The other instances where UA is used along with the device id, the device id is first hashed, e.g. https://github.com/mozilla-services/screenshots/blob/e56650dc51b470b26754e593f0c9f83ca2c79a9e/server/src/server.js#L429

It's inconsistent at the very least.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
