### ISSUE TITLE
Design is broken, if you navigate to the image content page for a deleted shot

### ISSUE THREAD

**Issue by GitLaboratory** [mozilla-services/screenshots#3806]
[https://screenshots.firefoxusercontent.com/images/bd319fc2-1692-405d-8e1e-3d3627d9fd42.png](url)

![5d7c01ab-ed6a-43f3-b2df-dbbaf6b3e014](https://user-images.githubusercontent.com/2738607/32990949-dbdb0b0e-cd64-11e7-8a8b-3baff0662792.png)

**Comment by wresuolc** [comment]
Our 404 page is not an image, it's HTML

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
