### ISSUE TITLE
Wrong paths

### ISSUE THREAD

**Issue by GitLaboratory** [mozilla-services/screenshots#3807]
https://screenshots.firefoxusercontent.com/shots

![cce29c13-4c3b-493e-8505-b5e906d79090](https://user-images.githubusercontent.com/2738607/32990979-8eace7e8-cd65-11e7-8a0d-7425671cb67c.png)

**Comment by SoftVision-CosminMuntean** [comment]
@GitLaboratory did you manually navigated to that link or it was automatically opened using a specific scenario?
The right path for "My Shots" page is: https://screenshots.firefox.com/shots

**Comment by wresuolc** [comment]
Re-open if there is more info here
