### ISSUE TITLE
No "Screenshots" item under Page Actions at all?

### ISSUE THREAD

**Issue by that-ben** [mozilla-services/screenshots#3808]
Firefox Quantum 57.0 rolled out 2-3 days ago on my Windows 7 64-bits computer.  I checked the tour page and in-Firefox Screenshots were advertised.  Wanted to try it out, pull the Page Action menu and... it's not there.  I'm not using a privacy tab, just normal browsing.  It does that on 100% of the websites, never even seen that Screenshots menu item at all yet.

![screenshots](https://user-images.githubusercontent.com/13210399/32991271-3aeae09c-cd06-11e7-9ac1-6964fc51eab5.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1418709

**Comment by SoftVision-CosminMuntean** [comment]
@that-ben Is there any chance that you disabled Screenshots from "about:config" on previously version of Firefox? 
Can you please check if Screenshots is disabled or enabled? Navigate to "about:config" page and search for the `extensions.screenshots.disabled` boolean pref. If the pref is set to false, Screenshots should be enabled and should be displayed in "Page Actions" menu. If it's set to true, Screenshots should be disabled.

**Comment by that-ben** [comment]
It is disabled, but I didn't do that.  The update rolled out 4 days ago and I have not gone in about:config a single time.  I cannot even remember the last time I went in about:config TBH and it certainly never was to set this to true.  Weird!
