### ISSUE TITLE
Copy image url to clipboard

### ISSUE THREAD

**Issue by wadie** [mozilla-services/screenshots#3809]
Right now it copies the link of the page in which the image is in. can we have it automatically copy the url of the actual image since that is what usually people would want to share..

**Comment by SoftVision-CosminMuntean** [comment]
@wadie Copy image to clipboard was implemented in Screenshots dev version and it will be available in the next release. See this issue: #2582

But, If I understand correctly do you want to automatically copy the image content URL after the shot was saved?

**Comment by wadie** [comment]
Correct, right now it copies this 

https://screenshots.firefox.com/zTTwHZY2V3KD40on/github.com

which takes you to a page that has the screenshot. it'd be better if it auto copied this url instead 

https://screenshots.firefoxusercontent.com/images/900414af-6edb-4873-bda9-56db65d27e8d.png

which is what people wanna share usually..

**Comment by pshem** [comment]
This is a copy of #2390 
Consider merging

**Comment by wadie** [comment]
Any update on this ? I would work on it if I knew how we would wanna implement it.

Do we want to have the option to change what we copy to the clipboard ? or have it copy the image url only ?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
