### ISSUE TITLE
take a screenshot from local file

### ISSUE THREAD

**Issue by wadie** [mozilla-services/screenshots#3810]
Right now it works to right click and choose take a screenshot on any webpage and online pdf files, but I tried opening a local pdf file using Firefox and then right clicking there's no take a screenshot option. 
I had to click on the three dots in the address bar.

**Comment by SoftVision-CosminMuntean** [comment]
@wadie I just tried this and I cannot reproduce the issue. I have opened a local pdf file in Firefox and the "Take a Screenshot" option is available in context menu and works as expected.
Here is a screen recording: https://goo.gl/NUDXZ7

Can you please give us more information? On what version of Firefox and OS did you encounter the issue? I have tested on Windows 7 and Mac Os 10.12 using latest Firefox 57.0 release and also latest Nightly (59.0a1) build and I cannot reproduce the issue.
