### ISSUE TITLE
Quote title attributes

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3815]
This is a followup to #3796 – in that patch there's stuff like:

```js
` ...
<button class="highlight-button-cancel" title="${browser.i18n.getMessage("cancelScreenshot")}"></button>
`;
```

If someone puts a " in the message then this will break.  This should either be HTML-quoted or use attribute setting (probably using the localization routines we have elsewhere, that look for special `data-*` attributes).

**Comment by 6a68** [comment]
The good news here is that localizations don't use the plain old double quotation mark character (`"`), the use the fancy unicode left and right double quotation marks (`“` and `”`). The spec specifically mentions plain U+0022 double-quotes: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
