### ISSUE TITLE
Screenshot interface is super slow

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3816]
I tried this on a nightly from Nov 13th and it was instantaneous.  Trying it on a Nightly from Nov 20th and I hit this bug.

STR:
1) Load a slow page like https://bugzilla.mozilla.org/page.cgi?id=triage_owners.html
2) Click the screenshot button.  Note how slow the interface is to appear

Looking at the Network panel in the dev tools it looks like we're doing another GET before showing the interface

**Comment by chenba** [comment]
This sounds like #3692

**Comment by wresuolc** [comment]
Ah, you're right.  Is the fix in the uplift request for 23 (or 25)?

**Comment by chenba** [comment]
It's in 25.

**Comment by wresuolc** [comment]
ok, I'll close this then.  Thanks!
