### ISSUE TITLE
Usage and Retention is down with photon interface changes

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3817]
Usage and retention is down sharply after 57.  There have been several posts on discourse, github, and mailing lists asking why Screenshots was removed from 57 (and/or where it went).

Presumably, this is due to the move from the toolbar to the page action menu.  Is there some UI or onboarding we can add to help people find screenshots?

**Comment by ianb** [comment]
True! But this is old history now. Maybe in the future we can do something about this.
