### ISSUE TITLE
 firefox screenshot tools doesnt work on sites which using framesets

### ISSUE THREAD

**Issue by Eurylae** [mozilla-services/screenshots#3828]
when u try to screen a site which using framesets [this error occurs](https://i.imgur.com/v8hbDsD.png).
Translation:
(Taking a Screenshot is not possible. This is not a normal site, thats why taking a Screenshot is not possible) 

NOTE: if u force the same site to use iframes instead of framesets the scrrenshot tool works.

**Comment by wresuolc** [comment]
This is a known issue.  Duplicates at #1748 #2489
