### ISSUE TITLE
[Annotations][Enhancement] Enable users to crop shots

### ISSUE THREAD

**Issue by niharikak101** [mozilla-services/screenshots#3831]
Crop tool!

**Comment by youwenliang** [comment]
@niharikak101 Here's a crop tool icon: https://www.dropbox.com/s/hx1jb09202u9gva/crop.svg?dl=0

Adding those tools(crop, color picker, clear) the layout should look something like this:
![annotation-tools](https://user-images.githubusercontent.com/8919308/33158430-dd3cb92e-d044-11e7-943a-9a0290f84e1f.png)

(Fang is on PTO for a week so I'll need to wait for her feedback)

**Comment by chenba** [comment]
This can be closed now. 🎉
