### ISSUE TITLE
Screenshot of Talos doesn't show full page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3833]
[Example shot](https://screenshots.firefox.com/OXuEHCy3dOAwk5Cv/treeherder.mozilla.org): the full page screenshot is correctly sized, but the bottom portion is all transparent. Very mysterious. If I scroll, then just the visible screen shows up at the top of the image. [Original page](https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&newProject=try&newRevision=62068b674a563c78052c6f0cf4a16133a81a1ace&framework=1&showOnlyImportant=1&selectedTimeRange=172800)

**Comment by chenba** [comment]
Looks like it's caused by `height: 100%` and `overflow-x: hidden` on the `<body>` of that page.  If you make the browser window very narrow, then the overflow'd part of the page on the right will also be transparent.

**Comment by wresuolc** [comment]
Let's encourage an upstream fix :)
