### ISSUE TITLE
Cannot screenshot if dialog box is visible

### ISSUE THREAD

**Issue by thunderrabbit** [mozilla-services/screenshots#3836]
On OS X Firefox 57.0, a modal dialog box blocks screenshot ability.

Arguably, it's a modal, therefore nothing can be done outside the modal.
Equally arguable, the modal was created by Firefox, which could ignore it.

![cannot_screenshot_if_modal_alert](https://user-images.githubusercontent.com/21597/33237736-3e182e5a-d2bf-11e7-909c-6f399b5ea44d.png)

**Comment by wresuolc** [comment]
Argument 1 is the one we're going with. :)  We wouldn't be able to screenshot this anyway, as we look at page content and this is over it.

**Comment by thunderrabbit** [comment]
Argument 1: fair enough.

However, I wanted to include the popup in the screenshot!  ;-)
