### ISSUE TITLE
Data review for user timings

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3839]
User timings documentation at https://github.com/mozilla-services/screenshots/blob/master/docs/METRICS.md#add-on-performance-measurements

1) What questions will you answer with this data?
We're trying to make an application performance dashboard to ensure we're conforming to the [RAIL guidelines](https://developers.google.com/web/fundamentals/performance/rail).  Anything else we can speed up from the collected data would be welcome also.

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?
Slow performance was one of the main complaints about Screenshots over the summer from our end users.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
We've used surveys and seen bugs complaining about performance.  They aren't accurate enough to pinpoint the problems.

4) Can current instrumentation answer these questions?
It's also too high level.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Client timing data</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-services/screenshots/issues/3673</td>
  </tr>
</table>

6) How long will this data be collected?
* I want this data to be collected for 6 months initially (potentially renewable).
Six months is fine -- whatever the regular retention policy is.

7) What populations will you measure?
All release channels, all countries, all locales.

8) Please provide a general description of how you will analyze this data.
We'll make a dashboard in data studio.

9) Where do you intend to share the results of your analysis?
Internally and externally on blogs.

r? @rjweiss

**Comment by rjweiss** [comment]
r+

1. Documentation is provided
2. This is instrumented with GA, and respects both data preferences and the Do Not Track header.
3. Data is temporary for now.
4. Type 2.
5. Default on, all release channels, all countries, all locales, but only for Screenshots users.
6. No new identifiers.
7. Yes.
8. Recommend a renewal in 6 months and consider conversion to permanent metrics status depending on the state of the feature.

**Comment by johngruen** [comment]
thanks!
