### ISSUE TITLE
[Annotations] The image is no longer displayed in "Edit" mode 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3848]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 26.0.0 

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 26.0.0 dev version installed [from here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to any website and save a selection.
3. Click the "Edit" button and observe the image.

[Expected result]:
- The image is correctly displayed.

[Actual result]:
- The image is no longer displayed.

[Notes]:
- Here is a screen recording with the issue:
![in edit mode image not displayed](https://user-images.githubusercontent.com/19226534/33313438-501c6556-d433-11e7-9a3c-ade354c3d8fb.gif)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible using the latest Screenshots 26.0.0 dev version installed from here: https://screenshots.dev.mozaws.net/homepage/install-test-local.html
Tested on Windows 7, Mac Os 10.12 and Arch Linux.

**Comment by chenba** [comment]
I branched off an earlier master rev where the canvas img crossOrigin attribute was set to "Anonymous"; another patch was merged into master set the attribute to "use-credentials".  #3906 will change the attribute back.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Screenshots 27.0.0 dev version and is no longer reproducible. Tested on Mac, Linux and Windows. Marking this as verified.
