### ISSUE TITLE
User Timings not visible in GA

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3854]
Today's Nightly includes Screenshots 25.0.0, which measures the time between steps in the shot creation flow (#3673). Looking in the browser toolbox's network tab, I see pings flowing to the /timing endpoint:

<img width="1143" alt="screen shot 2017-11-28 at 11 16 36 am" src="https://user-images.githubusercontent.com/96396/33339334-a0daa760-d42d-11e7-8ce3-932c28ae01c0.png">

However, I don't see any pings at all in the User Timings section in GA:

<img width="1191" alt="screen shot 2017-11-28 at 11 18 33 am" src="https://user-images.githubusercontent.com/96396/33339438-00528744-d42e-11e7-9624-9df66f587b16.png">

Is that data in GA somewhere, or do we need to look at the server logs to figure out what's up?

**Comment by wresuolc** [comment]
@chenba knows how to do this

**Comment by chenba** [comment]
Looks like data started arriving on Nov. 27th.  (See image below.)

Navigate to "Behavior" > "User Timings", and you should see "addon" as the only available timing category (second column of the table).  Clicking on "addon" will take you to the timing variables data.  This is the good stuff.

![image](https://user-images.githubusercontent.com/198055/33388118-a6f3a666-d4f4-11e7-96ca-62b508180deb.png)
