### ISSUE TITLE
Screenshots Is Redirecting 

### ISSUE THREAD

**Issue by DDMOREH** [mozilla-services/screenshots#3856]
Screenshots is redirecting to My Shots instead of loading capture region .

**Comment by SoftVision-PaulOiegas** [comment]
Hi @DDMOREH and thanks for your report. Screenshots does this when the page you are trying to capture is not a real web page. Like the "New Tab" page, or "about::addons". But this does not mean that what you are reporting couldn't be an issue. 
Can you please tall us what page you were trying to capture? If the page is legit, then we'll need to investigate on this further.

**Comment by DDMOREH** [comment]
It redirects to My Shots on any and every page . email's , websites , this page , any page I am on .
I left click screenshot and immediately get sent to My Shots .
I have been having issues with Firefox57 from day one .
Reinstalled Firefox57 for the 15th time yesterday , screenshot worked one time .
After first screenshot now screenshot only redirects straight to My Shots

**Comment by SoftVision-PaulOiegas** [comment]
This clearly does not happens on a new profile and we haven't seen any other reports saying this for existing profiles as far as I know. So it could be either something changed with your profile preferences or there is a conflict with your installed add-ons. 
Can you please navigate to "about:support" page and use the "Copy text to clipboard" button to copy the page content and paste it here in a new comment? The info from that page will help us to debug further the issue.
Thanks!

**Comment by 6a68** [comment]
@DDMOREH Hi, just to confirm, there are two menus with Screenshots-related items. Which one are you clicking?

The 'page action' menu looks like three dots, is visible on regular web pages, but not on pages built into Firefox, like the new tab page, and the menu item says "Take a Screenshot" - this is probably what you're looking for:

<img width="402" alt="screen shot 2017-11-29 at 8 54 49 am" src="https://user-images.githubusercontent.com/96396/33387924-66eaa4f4-d4e3-11e7-92d4-7ad0e1c62946.png">

I suspect you might be clicking on the Library menu, where the menu item says "Screenshots", and clicking it takes you to the My Shots page:

<img width="357" alt="screen shot 2017-11-29 at 8 54 41 am" src="https://user-images.githubusercontent.com/96396/33387836-345b600a-d4e3-11e7-8520-afe875e554d8.png">

Does this help?

**Comment by DDMOREH** [comment]
SOLVED . MY MISTAKE . 
Directions on how to use are not that clear .
THANK YOU FOR THE ASSISTANCE !
