### ISSUE TITLE
Per-page notification prefs

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#386]
There's a couple concepts around notification that have come up:
- Notify when the first visitor sees your page
- Notify when you get a comment
- Notify after some amount of time (use as a to-do)
- Notify if you see a traffic burst

Maybe other stuff.  Maybe we could have one notification pref menu, and you click on it and get a few of these options, presented mostly as checkboxes.

**Comment by brampitoyo** [comment]
What about something that appears on the user/profile/people menu, like this?

![pageshot-notification-settings](https://cloud.githubusercontent.com/assets/51007/7805882/48fbb0f2-03ce-11e5-9d8e-373fdb672117.gif)

**Comment by johngruen** [comment]
Closing this issue, will reopen with more relevant deetz
