### ISSUE TITLE
There is a noticeable delay when "Copy", "Download" or "Save" buttons are used for a Full Page screenshot

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3861]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 25.0.0 

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://imgur.com/" website.
2. Scroll the page in order to load more content.
3. Click the "Take a Screenshot" button from "Page Actions" menu.
4. Click the "Save Full page" button from the right part of the page.
5. Click the Copy, Download or Save buttons and observe the behavior.

[Expected result]:
- There is no noticeable delay after pressing the button.

[Actual result]:
- There is a noticeable delay until the process is complete.

[Notes]:
- Here is a screen recording with the issue:
![delayed buttons action - timer](https://user-images.githubusercontent.com/31244235/33381978-2f2d413a-d528-11e7-8f53-d73b6c809cf9.gif)

**Comment by wresuolc** [comment]
Flagging needs:ux because we are looking for some kind of transition/spinner thing.  Is there already a bug that shows that?

**Comment by wresuolc** [comment]
@youwenliang

**Comment by youwenliang** [comment]
The only spinner I know is the loading bar when users save a shot to the server. I'll talk with Fang to come up with another spinner for this situation.

**Comment by youwenliang** [comment]
The expected behavior for downloading large files should be:
1. Click download (and will immediately leave the screenshot overlay view)
2. Start loading in the download panel (calculating sizes)
3. Start downloading the files
4. Download complete

From the screen-recording it seems like step 1 & 2 & 3 are combined so it feels like it's freezing in the first step. Any chance we can fix that?

**Comment by chenba** [comment]
The title and original bug report mentioned Save, but in that use case, the user is immediately taken to the new tab for the shot page, so this issue isn't applicable there.

**Comment by chenba** [comment]
@youwenliang The "freezing" is from generating the image data.  It is not something we can avoid.  The code to hide the preview UI is actually called before the image generation and download/copy, but during normal execution, the browser doesn't get a chance to update the UI before it's blocked by the image generation.

We could try delaying the image generation until we know the preview UI's been hidden.  The just move the "delay" to between the hiding of the preview UI and the start of the download though.  (And it'd be slightly slower overall since we wait and check on the state of the preview UI.)

**Comment by chenba** [comment]
@johngruen @wresuolc I just gave this a spin with an animated SVG spinner.

While `canvas.toDataURL()` is happening, the browser does not animate the spinner image.  So for downloads, the users will see a still image.  Users will see a bit of animation between the end of `canvas.toDataURL()` and switching to the new tab on saves.  I suggest that we don't use animation.

There's also the threshold at which this spinner/message should be displayed.  All full-page shots?  Shots exceeding a certain area in size?  The UI "flashes" when things happen quickly.  (We could add some sort of minimum time to display the message...)

**Comment by chenba** [comment]
Here's the full page capture user timing for the last 30 days btw:

![image](https://user-images.githubusercontent.com/198055/35177658-a579aa40-fd46-11e7-9cc6-ab7d15740cfb.png)

**Comment by wresuolc** [comment]
Google says "Beyond 1000 milliseconds (1 second), users lose focus on the task they are performing." in their RAIL guidelines, and 20% of our users are hitting that, so, that seems like something we should try to fix.  

Additionally, "For actions that take longer than 50ms to complete, always provide feedback."

So, we would want an animation if it goes over 50ms.  All full page shots would be a good start if we can't figure out better dimensions.

Can we put `canvas.toDataURL()` on a different thread somehow so the animation can still run?  Can we fire toDataURL() in the background once they choose the selection area but before they hit save/download?  (just making stuff up here, I'm not sure how viable that is)

**Comment by chenba** [comment]
We should work on #3968 first.  It's a lower hanging fruit that'd help with some of the use cases.

I'll see if we can use a web worker.

**Comment by chenba** [comment]
@wresuolc animation was animating when a background script is doing the `toDataURL()`.

Using the preview image for download or copy to clipboard (#3968) was very fast when I tried it, so I pulled that into the current sprint and created a PR.

With that in place, then perhaps we'll only show the spinner and use a background `toDataURL()` when it's a truncated full-page shot.

Spinner image still TBD for this.

**Comment by chenba** [comment]
The proposed patch (PR #4023):

- Displays the animated loader only for truncated full page downloads and copy to clipboards
- Uses the CSS loader animation from `/creating`, partly because #4000 might use it for annotation saves as well

@fangshih Let me know if you want us to use a different spinner.

**Comment by chenba** [comment]
Here's a screen recording of the loader CSS animation in action for a large download:

![loader](https://user-images.githubusercontent.com/198055/35529615-2d9392f8-04f7-11e8-90c5-4f361a96bd14.gif)

**Comment by johngruen** [comment]
@chenba looks good, but there's a flash where the underlying content shows without an opacity layer btwn the loader and the preview. possible to maintain that layer throughout the flow?

**Comment by chenba** [comment]
@johngruen Sorry, I don't totally understand your comment.  The loader is on the same layer as the preview; the preview UI and the 10000px notice are hidden while the loader is displayed.  I'm having a really hard time spotting the flash in the image above. 😕

**Comment by chenba** [comment]
So, I was being economical with my bits and start the recording right before I click on the download button.  That's _after_ I've already selected the full page shot option and received the preview.  Sorry about the confusion.  #StartFromTheBeginning

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v28.0.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 60.0a1 (2018-02-12), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
