### ISSUE TITLE
Audit site colors and replace with Photon library colors

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3864]
Hello: https://www.npmjs.com/package/photon-colors

We should go through our CSS and make sure we're using photon-official colors across the repo.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
