### ISSUE TITLE
Copy image to clipboard, bitmap image instead of the URL

### ISSUE THREAD

**Issue by vizapata** [mozilla-services/screenshots#3865]
Should this app contain an option to copy the image to clipboard aditional to the download and save options?

So we can paste it in a email or a blog entry editor just with *CTRL-V*. With this option there is no need to download or save the screenshot in the cloud.

![clipboard](https://user-images.githubusercontent.com/6758467/33438934-2e26a74e-d5ba-11e7-9550-c7c2033307c1.png)

**Comment by wresuolc** [comment]
Thanks for the comment -- we've just landed this feature in Firefox Nightly.
