### ISSUE TITLE
Visual refresh screenshots share panel

### ISSUE THREAD

**Issue by fangshih** [mozilla-services/screenshots#3869]
Current share panel needs to update the visual to align with photon doorhanger UI style. I'll update the visual assets and spec.

**Comment by fangshih** [comment]
Visual refresh for the share screen panel
- Using the doorhanger style from Photon. 
- Updated the social media and email buttons 
- Highlight the copy button 
- Change the copy link function above the social media buttons, hoping it encourages people to share the link more and also it has better visual balance. 
![key-screens-40-share-panel](https://user-images.githubusercontent.com/4862573/33652478-95ee1bf2-daa4-11e7-9355-4a82f96a53ac.png)

**Visual Spec:** 
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/Share%20Panel

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
