### ISSUE TITLE
Update visual for delete screenshot confirm window

### ISSUE THREAD

**Issue by fangshih** [mozilla-services/screenshots#3870]
Delete shot confirm window are still using the old UI, I'll update the visual screens and spec soon.

**Comment by fangshih** [comment]
Here is the update visual screen for the delete panel
![key-screens-40-delete-panel-copy-2](https://user-images.githubusercontent.com/4862573/33652407-501d0778-daa4-11e7-921a-2e55b381c730.png)
**Visual Spec:**
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/Delete%20Panel
Thanks!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
