### ISSUE TITLE
Investigate why Twitter embeds look broken for some shots:

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3871]
For example:
![image](https://user-images.githubusercontent.com/3323249/33497837-44cd5ffe-d69d-11e7-89ac-933bf5bbe4d1.png)

**Comment by Softvision-CristinaBadescu** [comment]
I've managed to reproduce this issue for cut off images shared on Twitter. I've tested this using the latest Firefox Screenshots v32.1.0stage, on latest Nightly build 61.0a1 (2018-04-25), on Windows 10 x64.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
