### ISSUE TITLE
direct-view-embedded-non-owner calls are getting made at an alarming rate

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3872]
The following graph is a view of web events filtered for event actions that equal `visit` where the browser is Firefox over the first two months of Screenshots.

There's a massive spike in `direct-view-embedded-non-owner` event pings at this point, which seems bad and wrong. We should investigate this. 

![image](https://user-images.githubusercontent.com/3323249/33499996-369dad8c-d6a5-11e7-944e-a809d8c1e54c.png)

**Comment by ianb** [comment]
After discussion, we realized this was due to Activity Stream: Activity Stream uses og:image to make cards for pages on newtab, and so if a Screenshot shows up there then we'll get pinged. I'll ask around about separating out AS pings from other similar views.
