### ISSUE TITLE
Scroll in PDF file

### ISSUE THREAD

**Issue by wadie** [mozilla-services/screenshots#3876]
Normally on any webpage you can drag and scroll to take a screenshot, but this isn't working when opening a PDF file. I can drag and take a screenshot to whatever is visible, but not scroll to include other parts of the PDF in the screenshot.

**Comment by ianb** [comment]
The way our PDF rendering works (unfortunately), the webpage is only the size of the screen, and then there's a scrollable element inside the page that contains the PDF. The result is that the whole page can't scroll, only an element, and Screenshots can't figure out how to scroll just that one element.

So, unfortunately, we won't be able to fix this.

**Comment by wadie** [comment]
Thanks for the explanation.
