### ISSUE TITLE
Downloading a selection fails if "Never Remember History" option is set

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3886]
[Affected versions]:
- Firefox trybuild https://goo.gl/zWBXfk
- Screenshots 25.0.0 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have this trybuild: https://goo.gl/zWBXfk , installed on a new Firefox profile.
- Have the "Never Remember History" option set in "about:preferences#privacy" page.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to any website and perform a selection.
3. Click the "Download" button.
4. Observe the behavior.

[Expected result]:
- The selection is successfully downloaded with the correct name and format.

[Actual result]:
- The download fails and the following message is displayed in the Download doorhanger: "Failed -blob resource-".

[Notes]:
- This issue is also reproducible with Firefox Screenshots 26.0.2 from here: https://screenshots.dev.mozaws.net/homepage/install-test-local.html.
- This issue is also reproducible on latest Nightly build 59.0a1 (2017-12-05) with Screenshots 25.0.0.
- Here is a screen recording with the issue:
![download failes](https://user-images.githubusercontent.com/31244235/33615926-0f6e39d8-d9e4-11e7-974f-5eaf4c765a5e.gif)

**Comment by wresuolc** [comment]
Let's uplift this to beta

**Comment by 6a68** [comment]
This seems to be a regression (or API change) in Firefox, not in Screenshots.

I ran mozregression and got this regression window: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=e7b3e385157a43ad065f36ccf3d07327dfc170a3&tocha

**Comment by asutherland** [comment]
I have a fix for the platform regression on try, should land and get uplifted in the next few days, although it's worth noting that using "Never Remember History" in general is going to break WebExtensions until the background page docshells stop being set to be in private browsing mode.  For example, if this extension wants to use IndexedDB, that will break in never remember history mode.

**Comment by ianb** [comment]
FWIW we only use `browser.storage` for persistence, not IndexDB or localStorage or something connected to the background page specifically.

**Comment by asutherland** [comment]
The fix was made available in the 20171207220423 nightly aka 12-07 22:02 for those of us who go blind when there are that many numbers in a row.  I've requested beta uplift because the regression also made it to beta.  @Softvision-CristinaBadescu, I think devrel would appreciate a re-test of this case when possible.  Thanks!

**Comment by Softvision-CristinaBadescu** [comment]
@asutherland I've retested this issue and is no longer reproducible on latest Nightly build 59.0a1 (2017-12-10), on Windows 10x64, Mac 10.12.6 and Ubuntu 14.04 x64. However, I think the fix isn't yet uplifted in Beta, since the issue is reproducible on latest Firefox Beta 58.0b10, on the mentioned OS's. When the uplift is ready, I'll retest.

**Comment by asutherland** [comment]
@Softvision-CristinaBadescu Thank you for retesting!  Indeed, the patch only landed on the beta channel last night, so retesting will need to wait until the next beta is spun.  I'm cc'ing you on the underlying (sec) bug.

**Comment by Softvision-CristinaBadescu** [comment]
I've retested this issue on latest Firefox Beta 58.0b13 and is no longer reproducible using Firefox Screenshots 25.0.0 on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
