### ISSUE TITLE
Provision cd7 in GA for share icon A/B test

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3888]
See https://github.com/mozilla-services/screenshots/pull/3868#discussion_r154480702

**Comment by johngruen** [comment]
Okay this is created...if i read the comment correctly, this a/b test is per-user rather than per-session. I've set the `cd` to be user based. Maybe let's leave this open until we can confirm that we're pinging/recording.

**Comment by 6a68** [comment]
Cool, opened #3899 to remind ourselves to verify GA is configured correctly for this wave of A/B tests
