### ISSUE TITLE
Look at PullQuote

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#389]
Makes quote images for Twitter: http://pullquote.com/

**Comment by brampitoyo** [comment]
This is what the quote looks like as an image on Twitter:
![pullquote](https://cloud.githubusercontent.com/assets/51007/7527578/e89b70d2-f570-11e4-8a5b-bd6c097c9360.png)

The tweet contains a PullQuote link that will display the quote in bigger type: http://pullquote.com/pq/Pw6Lyp

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/1b7d5dygA7nR4XLQkwDrd_3SYKXxdRZBUhQvLzFj7OOY/edit)
