### ISSUE TITLE
A/B test textless download button on shot page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3894]
Eventually we are going to want to start rearranging buttons in the add-on. In anticipation of this, I want to see how much effect removing the text cue from a button will have.

Let's conduct a test where we hide the word `download` from the download button on shot pages for some users and measure the relative click thru rate.

Current:
![image](https://user-images.githubusercontent.com/3323249/33683592-64601820-da99-11e7-8dee-73e064ae1727.png)

Test Branch:
![image](https://user-images.githubusercontent.com/3323249/33683619-79e3f5d6-da99-11e7-8fdd-dbc23588f574.png)

I would like to measure whether taking out the text depresses clicks on this button or if it does not matter.

One gotcha to note: the diff here includes removing an `&nbsp;` hiding at the end of this line:
https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/view.js#L415

**Comment by chenba** [comment]
Note that the code for this test is going away in PR #4821 as the new UI spec does not have textless buttons.
