### ISSUE TITLE
[Annotation] There is no icon for the "Clear" button

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3897]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 26.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 26.0.0 dev version installed [from here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Observe the "Clear" button.

[Expected result]:
- There is an icon on the "Clear" button.

[Actual result]:
- There is no icon on the "Clear" button.

[Notes]:
- Here is a screen shot with the issue:
![clear](https://user-images.githubusercontent.com/19226534/33725568-35004040-db7b-11e7-8b9c-80add98269df.png)

**Comment by chenba** [comment]
There are four svgs that are no longer displayable after the patch for #3063.  Although `reset.svg` is more special: it works pre-svgo, but not displayable in Firefox post-svgo, yet works in Chrome.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Screenshots 27.0.0 dev version and now the icon is correctly displayed. Tested on Mac, Linux and Windows. Marking this as verified.
