### ISSUE TITLE
Shot page titles should include 'Firefox Screenshots'

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3898]
(Did we wontfix this bug already?)

From https://twitter.com/georgebaily/status/927520943903268864:

" hm, Firefox screenshot tool is cool and all, but setting the title as not just http://screenshots.firefox.com but also the page you screenshotted, means you get lots of false positives from browser history when typing a URL / bookmark "

**Comment by ianb** [comment]
The `<title>` tag does include `Screenshot:`. Oddly the tab title and history title doesn't include this?

There are several title-like things on the page, including og:title, twitter:title. BUT: I believe the issue here is that we set `document.title`! That's not intentional.
