### ISSUE TITLE
Verify A/B test results are using custom dimensions correctly

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3899]
Reminder bug to verify that GA is working for the A/B tests

**Comment by chenba** [comment]
How and where do we view the A/B test results?

**Comment by johngruen** [comment]
Uh, i can verify that we are not seeing anything on the metrics end. Let's discuss in our standup tomorrow

**Comment by 6a68** [comment]
I can look to see if the pings are arriving at the screenshots server proxy endpoint, and if they're getting forwarded to GA or stripped out

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
