### ISSUE TITLE
Interface flashes with long copy

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3901]
In Nightly/25.0.0, if I find a page (doesn't have to be long), select Full Page, and then hit the copy button, the interface/overlay briefly disappears, then appears, then disappears again.

**Comment by chenba** [comment]
@SoftVision-CosminMuntean Can you find a way to reproduce this consistently?  I haven't been able to with the latest Nightly on Windows and Linux.

**Comment by SoftVision-CosminMuntean** [comment]
Sure. I started to investigate this and it seems that is more visible on Mac OS. I will provide more information and a screen recording with the issue.

**Comment by chenba** [comment]
This is noticeable with copy to clipboard simply because copying is slow.  If I make download shot artificially slow (or if I'm using a very slow computer), then it's noticeable there as well.  The source of this is where `shooter.screenshotPage` `hide()` and then `unhide()` the iframe.
