### ISSUE TITLE
The saved shots wrongly overlap while "My Shots" page is loading

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3905]
[Notes]:
- Probably this issue is a regression since was not reproducible on latest Nightly (59.0a1) build with Screenshots 25.0.0 version.

[Affected versions]:
- Nightly 59.0a1
- Screenshots 26.0.0 

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 26.0.0 dev version installed [from here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  
- Have multiple shots saved on the created profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Click the "Library" button from Firefox tollbar
3. Click the "Screenshots" button.
4. Observe how the "My Shots" wile is loading.

[Expected result]:
- The "My Shots" page is correctly loaded.

[Actual result]:
- The saved shots overlap.

[Additional Notes]:
- Here is a screen recording with the issue:
![my shots page](https://user-images.githubusercontent.com/19226534/33766458-30560dee-dc26-11e7-8ad6-53b8ced39898.gif)

**Comment by chenba** [comment]
The addon version does not matter for this.

The issue is noticeable if the connection is very flow and the images are not cached (or caching is off).  The shot container previously had its height specified in CSS.  That is no longer the case.  So, as Firefox load and draw the images, they overlap down into the container below until some redraw reinstate the margins.

**Comment by wresuolc** [comment]
Lets add a fixed height to the thumbnails.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba @ianb did you guys merged some changes related to this issue? Because I haven't managed to reproduce it on latest Screenshots 27.0.0 dev version.

**Comment by chenba** [comment]
Yes: https://github.com/mozilla-services/screenshots/pull/3920

I made a typo on the PR description when referencing this issue.
