### ISSUE TITLE
[Enhancement] The "Copy" functionality should be added in Screenshots Onboarding 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3912]
[Notes]:
- Since a lots of users requested this feature, we should inform them about this functionality in the Screenshots Onboarding page and also on Onboarding tour.

[Affected versions]:
- Nightly 59.0a1
- Beta 58.0b10
- Screenshots 25.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open latest Nightly build and navigate to the "https://screenshots.firefox.com/" page.
2. Look over the Onboarding page.

[Expected result]:
- The "Copy" functionality is described in the Screenshots Onboarding page.

[Actual result]:
-  The "Copy" functionality is not described in the Screenshots Onboarding page.

**Comment by johngruen** [comment]
I am ambivalent about this: moving to product backlog.

**Comment by ianb** [comment]
I believe this basically happened
