### ISSUE TITLE
If the title of a newly created shot was edited, the shot looks broken on "My Shots" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3913]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 26.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 26.0.0 dev version installed [from here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Edit the shot title and click the "My Shots" button.
4. Observe the saved shot.

[Expected result]:
- The shot is correctly displayed on "My Shots" page.

[Actual result]:
- The shot looks broken on "My Shots" page.

[Notes]:
- This issue is not reproducible on latest Nightly 59.0a1 build using Screenshots 25.0.0 version.
- Here is a screen recording  with the issue:
![broken shot](https://user-images.githubusercontent.com/19226534/33884987-85b2af0a-df4a-11e7-8162-e5610e6006c1.gif)

**Comment by chenba** [comment]
I suspect a (failed) thumbnail re-gen was attempted on the title save.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on Screenshots (27.0.0) dev version. But, it seems that the saved shots now looks a little bit different than before the PR was merged.
See this screenshot:
![screenshot-2018-1-4 my shots](https://user-images.githubusercontent.com/19226534/34565853-17e79fa8-f165-11e7-98cc-3650127633dd.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using Screenshots 28.0.0 dev and stage version and is no longer reproducible. The shot is correctly displayed on "My Shots" page, if the title of was edited.
