### ISSUE TITLE
Do Not Save Unchanged Title

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3915]
The shot page sends a request to save the title even if the user did not modify the title.

**Comment by shreyanshdwivedi** [comment]
@chenba are you working on this? If not, I would like to work on this issue

**Comment by shreyanshdwivedi** [comment]
I am working on this. Please assign this to me

**Comment by chenba** [comment]
I don't have the power to do that.  Maybe... @clouserw ?

**Comment by ianb** [comment]
For reasons I don't entirely understand we can't assign tickets to people outside the repo's list (I opened #3963 to figure it out). Hopefully anyone else who looks at this ticket will see that @shreyanshdwivedi is planning to work on it

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
