### ISSUE TITLE
The descriptive images from Screenshots tour page are no longer displayed on dev and stage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3921]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 27.0.0 dev and stage

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://screenshots.stage.mozaws.net/#tour" page.
2. Observe the descriptive images from the page.

[Expected result]:
- The descriptive images are correctly displayed.

[Actual result]:
- The descriptive images are no longer displayed.

[Notes]:
- This issue is also reproducible on dev server.
- Here is a screenshot with the issue:
![screenshot-2017-12-21 firefox screenshots](https://user-images.githubusercontent.com/19226534/34255284-a68e16a0-e658-11e7-81c1-b1c7caf8a527.png)

**Comment by chenba** [comment]
Probably related to #3897.  Let's wait until PR #3910 is merged and re-test this.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Screenshots dev version and is no longer reproducible. It seems that was fixed after the PR #3910 was merged.
