### ISSUE TITLE
Wrong screenshot is performed for a selection smaller than 40 px width

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3922]
[Notes]:
- Also, the selection is not visible if the width is smaller than 40 px.

[Affected versions]:
- Firefox Beta 58.0b12
- Firefox Nightly 59.0a1
- Screenshots 25.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to a website.
2. Click the "Page actions" menu and select Firefox Screenshots.
3. Perform a selection with a width smaller than 40px.
4. Observe the size of the performed selection.

[Expected result]:
- The screenshot is correctly performed, with the selected size.

[Actual result]:
- A wrong screenshot is performed, with a different size.

[Additional notes]:
- Here is a screen recording of the issue:
![wrong screenshot performed](https://user-images.githubusercontent.com/31244235/34257127-3014c542-e661-11e7-91b5-ec7d80ba7228.gif)

**Comment by wresuolc** [comment]
This is odd - the eyes aren't following the mouse.

**Comment by Softvision-CristinaBadescu** [comment]
I've tested this issue and is no longer reproducible for the width limit (40px) but is reproducible for a selection smaller that 40px **height**, using latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 59.0a1 (2018-01-14), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

@ianb, @chenba, considering that this issue is reproducible for a selection smaller that 40px height, should I reopen this bug or should I file a new one and track it there?

Here is a screen recording with this behavior:
![screenshots height](https://user-images.githubusercontent.com/31244235/34936913-a89ad7b6-f9eb-11e7-9080-ed7ffc4608ef.gif)

**Comment by chenba** [comment]
It's by design that the drag selection does not start until the mouse has traveled more than 40px.  The bug here is that the pre-selection on the element where the mousedown occurred is not canceled once the user started dragging.

@Softvision-CristinaBadescu I'll file another bug for it.  Thanks.
