### ISSUE TITLE
No backups?

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3924]
Just filing this for triage later:  it sounds like we're not backing up our s3 bucket right now.  Should we be?

**Comment by wresuolc** [comment]
@oremj is going to turn on versioning and replication.  We plan on using the standard mozilla expiration times (I'm not sure what those are).

**Comment by oremj** [comment]
How long should we keep objects around after they are deleted?

**Comment by wresuolc** [comment]
Lets do 2 weeks

**Comment by oremj** [comment]
I've turned on versioning and applied the following lifecycle rule:

![image](https://user-images.githubusercontent.com/45590/35001689-25a38d10-fa9c-11e7-9147-82f6f6f5834c.png)

**Comment by oremj** [comment]
I've also applied this replication policy:

![image](https://user-images.githubusercontent.com/45590/35001828-97432e76-fa9c-11e7-9104-4403e362edfd.png)

**Comment by oremj** [comment]
New objects are being replicated now. I'm currently back filling the replica bucket with old objects.
