### ISSUE TITLE
Full page screenshot only saves partial website

### ISSUE THREAD

**Issue by KopfKrieg** [mozilla-services/screenshots#3929]
I recently had the issue, that a full page screenshot resulted only in an partial image of the website.

Tested website: http://www.ryanestrada.com/learntoreadkoreanin15minutes/

Here's the screenshot I got: ![Screenshot](https://user-images.githubusercontent.com/5047813/34469535-724500e4-ef21-11e7-9474-dd4e7c1b86ed.jpg) (as you can see, it doesn't contain the whole site)

**Comment by SoftVision-CosminMuntean** [comment]
@KopfKrieg thanks for reporting this!

Based on the current implementation Screenshots has a limit of 5000 px height on Firefox 57, but starting with Firefox 58, the new limit will be 10000px (see issue #3538).
