### ISSUE TITLE
[Annotations] The black highlighter is not transparent and the white one is not visible

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3935]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 27.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 27.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Select the "Highlighter" tool and choose the black color.
4. Draw something on the page and observe the highlighter.

[Expected result]:
- The highlighter is transparent.

[Actual result]:
- The highlighter is 100% opaque.

[Notes]:
- A similar behavior can be observed using the white highlighter, but in this case the color is not visible at all.
- Here is a screen recording with the issue:
![black and white highlighter](https://user-images.githubusercontent.com/19226534/34570283-e9734b36-f173-11e7-81bd-739707487e81.gif)

**Comment by johngruen** [comment]
Let's just make the white be a mostly opaque overlay and call this done.
