### ISSUE TITLE
 A border wrongly appears at the bottom of a saved shot's image

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3944]
[Affected versions]:
- Nightly 59.0a1
- Firefox 57.0.4
- Screenshots v28.0.0 and v19.2.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to any website.
2. Right click on the page and select "Take a Screenshot" from the context menu.
3. Perform a selection and click the "Save" button.
4. Observe the saved shot's image.

[Expected result]:
- The saved shot's image is correctly displayed.

[Actual result]:
- A border appears under the saved shot's image.

[Notes]:
- Here is a screenshot with the issue:
  
![border at the bottom of the image](https://user-images.githubusercontent.com/31244235/34619500-04166d88-f24b-11e7-9910-c8f8ccb753e6.png)
![grey border - screenshots](https://user-images.githubusercontent.com/31244235/34619524-14a993f0-f24b-11e7-9eb7-0aec4343aeaf.gif)

**Comment by johngruen** [comment]
hmm that was already there, but it looks like some margin got inserted there somehow

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v31.3.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html
), on latest Nightly build 61.0a1 (2018-03-25), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
