### ISSUE TITLE
[A/B test] On the shot page, the icon from the textless download button is not centered

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3947]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 28.0.0 dev & stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 28.0.0 stage version installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Be in the textless download button variant.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe the icon from the textless download button.

[Expected result]:
- The icon is centered in the button.

[Actual result]:
- The icon is placed slightly to the left.

[Notes]:
- Here is a screenshot with the issue:
![download icon](https://user-images.githubusercontent.com/19226534/34673247-487d9258-f48a-11e7-8d29-9fa069248edc.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue with Screenshots 28.1.0 stage version and is no longer reproducible. The icon is centered in the button. I have tested it only on Windows.
I have also tried on Mac, but I have created ~20 profiles and I haven't get the textless download button.
@chenba  Is there a way to force this variant of a/b testing?

**Comment by chenba** [comment]
@SoftVision-CosminMuntean I'm not aware of an easy way.  I suppose to you could edit the response with a proxy like [Fiddler](https://www.telerik.com/fiddler), [James](https://github.com/james-proxy/james), or [Charles](https://www.charlesproxy.com/).  But for this issue, that doesn't seem worthwhile.

Maybe @6a68 has a better suggestion up his sleeve.
