### ISSUE TITLE
Add ability to export screenshots

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3948]
We should add a button that lets users download all their shots in one bundle (zip file).  Images are easy, but how should we include the meta data?

**Comment by wresuolc** [comment]
Aiming for UX in 60-0, and implementation later

**Comment by marniepw** [comment]
@johngruen we likely need some design input: page w/shots, edge/error cases, etc. We need to get this figured out per GDPR. @clouserw to talk to Legal re: specific requirements.

**Comment by wresuolc** [comment]
Legal has confirmed that this is not a GDPR issue and not a requirement.

**Comment by ianb** [comment]
We did something kind of like this for `/export` (simplistic though)
