### ISSUE TITLE
Create a list of 5 new Selenium tests

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3949]
Per our quarterly goals, we're going to add 5 more Selenium tests (our current test is in `test/test.js`)

Each proposed test should become its own ticket.

**Comment by chenba** [comment]
Looks like we cannot use [`actions`](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_ActionSequence.html) in our Selenium tests until https://github.com/SeleniumHQ/selenium/issues/4564 is resolved (and released with selenium-webdriver 4.0).

**Comment by ianb** [comment]
Here's some suggestions:

1. Select an element using the auto-selector, save that
2. Copy a selection to the clipboard
3. Download a selection (assuming the download action works okay with Selenium)
4. Attempt to save while the server is not available
5. Use auto-select, then cancel the selection with a background click
6. Click the page action twice to start and cancel
7. Navigate to My Shots (test that the selection overlay is also cancelled)
8. Navigate to My Shots via the Library (if it's possible)
9. Test truncation (or non-truncation) of a full page

If we can do mousemove and hovers (maybe or maybe not per https://github.com/mozilla-services/screenshots/issues/3949#issuecomment-357337948), then:

1. Make a selection with mousemove
2. Test different hovering auto-selections

**Comment by johngruen** [comment]
1, 2, 3, 4, 7?

**Comment by chenba** [comment]
1: #4024

**Comment by chenba** [comment]
I'm closing this because we have more than enough suggestions.  I captured all of them into github issues just so we don't lose the ideas.  We can close the individual issue if and when we find that it's impossible to test with Selenium.
