### ISSUE TITLE
Screenshots 'forgets' that I have seen its tour

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla-services/screenshots#3954]
I'm unsure if this coincides with updates to the browser (I'm on Nightly, and update infrequently), or updates to the Screenshots add-on or both, but clicking the page action after a browser start-up often launches that tour.

I have 'Clear history when Nightly closes' enabled, but I don't clear cookies, site prefs or OWD, which AFAIK, are the only ones known to cause webext to lose their settings:
![capture](https://user-images.githubusercontent.com/8336638/34757599-52aa6138-f5f8-11e7-8086-6973ce733c69.PNG)
Additionally, this doesn't happen on every browser restart, so that should probably means that the above setting is not to be blamed.

**Comment by SoftVision-CosminMuntean** [comment]
I haven't managed to reproduce this issue on latest Nightly 59.0a1 build. I have set all the settings like yours, but the tour wasn't displayed at browser restart. I have also downloaded an older Nightly version (2018-01-02 build), set the settings like yours and after updating the browser, the tour wasn't displayed. Even if I clear all the history and cookies (using "Ctrl + Shift + Delete" shortcut) the tour is still not displayed after restarting the browser.

@FatOrangutan can you please provide a copy of the "about:support" page? Probably an add-on or a changed pref causes this.

**Comment by FatOrangutan** [comment]
I uploaded the about:support from my main profile here: http://textuploader.com/dmddl
I have also seen this on a bare-bones profile that I have. Its about:support is here: http://textuploader.com/dmdd7

**Comment by SoftVision-CosminMuntean** [comment]
@FatOrangutan thanks for your quickly response!

I have installed all the add-ons that are displayed in your provided "about:support" page, but I still cannot reproduce the issue. The tour is not displayed even if I restart the browser 10 times.

Do you have any shots saved? If yes, the shots are also affected (deleted) after you restart the browser? Or only the tour is affected?
Also, can you please retest this using a new Nightly profile to eliminate custom settings as a possible cause (https://goo.gl/npYMuk)?

**Comment by FatOrangutan** [comment]
No problem, thanks for looking into this.

>Do you have any shots saved? If yes, the shots are also affected (deleted) after you restart the browser? Or only the tour is affected?

The shots aren't deleted upon restart, just the tour is shown.

>Also, can you please retest this using a new Nightly profile to eliminate custom settings as a possible cause?

The [second about:support](http://textuploader.com/dmdd7) that I included was very close to vanilla Nightly. But I will test more on completely fresh profiles and see if I can get reproducible steps.

**Comment by johngruen** [comment]
Hey @FatOrangutan do you ever open your profile in Release FF, I've found that this happens sometimes if i go from Nightly to Release back to Nightly. I never filed a bug.

**Comment by FatOrangutan** [comment]
>do you ever open your profile in Release FF

No, I don't have release FF.

>I've found that this happens sometimes if i go from Nightly to Release back to Nightly

That's at least somewhat similar to what I'm experiencing. Thanks for letting me know. I will see if I can narrow down the issue.

**Comment by wresuolc** [comment]
@SoftVision-CosminMuntean - can you narrow this down? thanks

**Comment by SoftVision-CosminMuntean** [comment]
Unfortunately I haven't manage to reproduce this issue. I have tested this with latest Nightly 60.0a1 build using different settings regarding cookies & history, but the Screenshots Tour was displayed only the first time when I have click the "Take a Screenshot" from "Page Actions" menu.

Even if I opened older versions of Nightly with the same profile the Screenshots tour is not displayed if was already visited.
So I am not sure what caused this or how to reproduce this.

@FatOrangutan can you still reproduce this issue?

**Comment by FatOrangutan** [comment]
Yes, it has happened a bunch of times since then on my main profile (with [this about:support](http://textuploader.com/dmddl), as posted previously).

Unfortunately I haven't had much time to narrow down the issue. One thing that I did find was that at least once the tour was shown despite neither the browser nor the extension having been updated.

It would be helpful if you could answer a couple of my questions:

1. Is there a way I can access the value of `hasSeenOnboarding`, which is where I believe the relevant value is saved, while the browser is running?
2. storage.local is vulnerable to clearing select privacy data on exit - cookies, site prefs and OWD only, as far as I know. Is that correct or are there are other factors that can affect it?

You can close this issue if you'd like; I'd reopen if I find something meaningful.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks for the information! 
I think @ianb is the right person to answer your questions.

Next time when the Tour is displayed can you please check the browser console (Ctrl+Shift+J) if there are any errors?

**Comment by ianb** [comment]
I don't have a reproduction, though I've seen this myself. Looking at the code (in `main.js`), `hasSeenOnboarding` defaults to false, and then we request the value from browser storage. We log any error getting browser storage to the console, but not Sentry. So an error there could cause the onboarding to be re-shown (though I'm skeptical this is the problem). Another possibility is if fetching from storage just takes a long time. Specifically with lazy background page startup there might be a race, and if the overlay startup beats browser.storage then it should re-show the onboarding. Simply defaulting `hasSeenOnboarding` to true would fix these (though then some people who should see the onboarding won't), or we could fix the race condition.
