### ISSUE TITLE
[Annotations] "Connection error" dialog is displayed for a moment if the "Save" button is clicked multiple times

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3956]
[Notes]:
- Also, after clicking multiple times on the "Save" button the image is no longer displayed.

[Affected versions]:
- Nightly 59.0a1
- Screenshots 28.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 28.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Draw something on the page.
4. Click multiple times on the "Save" button.
5. Observe the behavior.

[Expected result]:
- The changes are successfully saved without any errors. 

[Actual result]:
- "Connection error" dialog is displayed for a moment and the image is not displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
![connection error](https://user-images.githubusercontent.com/19226534/34774934-f8d0c8f6-f619-11e7-8904-98e892c6ab0c.gif)

**Comment by chenba** [comment]
@ChenMorpheus Do we have styles for disabled primary buttons on the web site (e.g. the Download or Save button in the screen recording above)?

**Comment by fangshih** [comment]
Hey @chenba  I've put a button list together. So for the disabled primary button, that should be 40% Opacity. Let me know if you have any questions.   
![screenshot button status](https://user-images.githubusercontent.com/4862573/35312639-6dca4294-00f7-11e8-816d-c9177fc19d33.png)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on latest Firefox Screenshots 28.0.0 dev version. Tested using latest Nightly 60.0a1 build on Windows 7 x64, Mac 10.12 and Arch Linux
