### ISSUE TITLE
"My Shots" not loading

### ISSUE THREAD

**Issue by LittTee** [mozilla-services/screenshots#3960]
The My Shots page either shows that it's loading and never does, or it loads with errors when I refresh. 

The issue occurs on Firefox 57.0.4 as well as Nightly. Restarts did not fix the issue for me

<img width="1300" alt="screen shot 2018-01-10 at 1 53 58 pm" src="https://user-images.githubusercontent.com/35313617/34798203-f61dea1c-f60f-11e7-8980-318ef15366fa.png">
<img width="1042" alt="screen shot 2018-01-10 at 1 52 21 pm" src="https://user-images.githubusercontent.com/35313617/34798204-f637bd5c-f60f-11e7-8079-b2053833ac30.png">
<img width="1300" alt="screen shot 2018-01-10 at 1 52 52 pm" src="https://user-images.githubusercontent.com/35313617/34798205-f64b50ce-f60f-11e7-92d1-f81df00c2c1a.png">

**Comment by chenba** [comment]
@LittTee Thanks for filing the issue.  It is already on our radar and we are working to fix it.

**Comment by chenba** [comment]
@LittTee It's been fixed.  I'm closing this issue now.  Thanks again for reporting it.
