### ISSUE TITLE
Can't take shots of non-standard webpages

### ISSUE THREAD

**Issue by LittTee** [mozilla-services/screenshots#3961]
I'm attempting to use screenshots to capture this page (https://addons.mozilla.org/en-US/firefox/collections/mozilla/trending-add-ons/?utm_source=email&utm_medium=email&utm_campaign=desktop&utm_content=emlear_6) but got an error (below), even though the screenshot menu was available (I know that the menu doesn't even appear when on a page like about:addons and that's the signal to me that it won't work. Ideally though, for doing UX and UI audits, I'd love to be able to use the Screenshots function on all .org pages and Firefox settings pages. Possible?

Error:
<img width="1135" alt="screen shot 2018-01-10 at 2 29 45 pm" src="https://user-images.githubusercontent.com/35313617/34799127-6f26577a-f613-11e7-8520-161f348217d0.png">

**Comment by chenba** [comment]
@LittTee You should be able take shots of other .org pages; addons.mozilla.org is special (see comment below).  The settings pages aren't possible.

https://github.com/mozilla-services/screenshots/blob/99bf1715bda4626c95cd02ae7c8445d2157da0f4/addon/webextension/background/main.js#L173-L176
