### ISSUE TITLE
Cannot perform an automatically selection around the "Cancel" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3970]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 28.0.0 

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".

- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a website (eg. https://imgur.com/).
2. Click the "Page actions" menu and select "Take a Screenshot".
3. Hover the "Close" button and move the cursor around the button (above, below or its margins).
4. While the selection rectangle is displayed, perform an automatically selection.

[Expected result]:
- The rectangle selection is displayed and you can perform the selection.

[Actual result]:
- The rectangle selection isn't displayed and you cannot perform the selection.

[Notes]:
- A similar issue I've encountered when you click inside the performed selection and afterwards click another selection around (above, below or its margins.)
- Here is a screen recording of this issue:
![cannot perform an automatically selection](https://user-images.githubusercontent.com/31244235/34946989-71a264a6-fa11-11e7-9394-fa82bda14d5b.gif)

**Comment by ianb** [comment]
There's some heuristics and caching around the selection boxes, I'm guessing that's related, because it seems to matter how you approach the target area.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), using latest Nightly build 59.0a1 (2018-01-18), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. 
However, the similar behavior mentioned in the first Note is still occurring, but I'm not sure if there is a way to fix this.
