### ISSUE TITLE
Highlight annotations icon

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3973]
So that users know it exists, we should add a little highlight to the new annotations icon the first time it launches.

I'd prefer if the highlight had the following:
- it should not include text
- it should point directly to the button

Here's a terrible proposal:
![screen shot 2018-01-17 at 10 05 02 am](https://user-images.githubusercontent.com/3323249/35034418-66c40c8e-fb6e-11e7-9c43-8fcba42582fd.png)

**Comment by fangshih** [comment]
Photon happens to have highlights badge icon. Here is the mockup look like. It works pretty well with the icon here. What do you think? 

![annotate new](https://user-images.githubusercontent.com/4862573/35091480-bf0a833c-fc77-11e7-9fae-c28d98da163a.png)

**Comment by fangshih** [comment]
Hey~ I've created two kinds of assets for the badge. One PNG one SVG. Let me know if you need any other format or size. 

**Badge Assets**
[PNG](https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/Annotation/Assets/annotation-badge.png)
[SVG](https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/Annotation/Assets/annotation-badge.svg)

Here is the measurements spec
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/Annotation/Annotation-badge-notify
