### ISSUE TITLE
[Annotations] Pen draws from previous location if mousedown happens outside of shot

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3974]
If you mousedown outside of a shot, the pen will draw a line from the previous last pixel or `(0,0)` on the initial draw. Gif below shows the issue:

![pen-enter-bug](https://user-images.githubusercontent.com/3323249/35042686-ec593732-fb89-11e7-9991-25e3b8d621c3.gif)

**Comment by chenba** [comment]
According to @niharikak101's comment in #3892, this should be fixed.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is reproducible using latest Screenshots (32.1.0) dev version after #4403 landed. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

**Comment by chenba** [comment]
This was fixed in #4468

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (32.1.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux,
