### ISSUE TITLE
The selection is wrongly saved if you choose the "Copy" option using keyboard navigation

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#3981]
[Notes]:
- This issue is not reproducible for selections smaller than 400px width.
- Also, you'll encounter the "catcher is not defined" error notification from #2996 issue.
- This issue is also reproducible for manual selections.

[Affected versions]:
- Nightly 59.0a1
- Screenshots 28.0.0 dev version

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a website, eg. http://money.cnn.com/technology/.
2. Click "Page actions" button and select "Take a Screenshot".
3. Perform an automatically large selection (at least 400px).
4. Rapidly press "Tab" key twice to focus "Copy" button.
5. Press "Enter" key and observe the behavior.

[Expected result]:
- The selection is copied to clipboard and a "Shot Copied" notification appears.

[Actual result]:
- The selection is copied to clipboard but it's also saved and opened in a new tab.

[Additional notes]:
- This issue is not reproducible if you click the "Copy" button.
- This issue is not reproducible with Firefox Screenshots 25.0.0.
- Here is a screenshot with the browser console error:
![catcher is not defined browser console](https://user-images.githubusercontent.com/31244235/35097452-d723a03a-fc58-11e7-9da4-7bc6ead087d5.png)

- Here is a screen recording of this issue:
![saved instead of copied](https://user-images.githubusercontent.com/31244235/35097456-da7a5c7e-fc58-11e7-92db-d351b9f71959.gif)

**Comment by chenba** [comment]
I cannot reproduce this with latest Screenshots.

**Comment by chenba** [comment]
Sorry, I misunderstood the STR.  I can reproduce it.

**Comment by chenba** [comment]
This bug also highlights an inconsistency.  With full-page and visible shots, the enter key does not have a default action, whereas the enter key would trigger the primary button's action (Save or Download) for selection shots.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v28.0.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 60.0a1 (2018-01-28), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
