### ISSUE TITLE
[Annotations] My Shots Should be Sorted By Last Modified

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3983]
When a user saves an edited shot, then go to My Shots, the edited shot is not the first in the list of shots.  It'd be more natural if the shots are sorted by most recently modified instead of most recently captured.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
