### ISSUE TITLE
Disable uploading on ESR

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3996]
Firefox 60 is an ESR.  To avoid problems down the line, we'd like to disable the ability to save screenshots to our servers on ESR releases (note: just ESR, not plain Firefox 60).  The screenshots functionality will still be there, but the Save button will be omitted.

From our discussion:
- We should add a pref to do this and convert our current disable-save-button logic to use it
- Add ESR detection to flip the pref
- Add the pref to our documentation and/or SUMO

**Comment by 6a68** [comment]
We can detect ESR-hood via `AppConstants.MOZ_UPDATE_CHANNEL == 'esr'`. No need to set a pref.

**Comment by ianb** [comment]
It feels like the pref is generally useful (especially given the enterprise policy stuff that's being deployed)

**Comment by 6a68** [comment]
Are you thinking of a separate pref to just disable uploads, like `extensions.screenshots.upload-disabled`? If so, maybe that could be a separate bug.

I'm proposing that uploads always be disabled if a Firefox is on the ESR channel, which seems like the goal of this bug.

**Comment by 6a68** [comment]
Ah, the pref is mentioned explicitly in the description for this bug, so I'll just add it :+1:
