### ISSUE TITLE
[Annotation] Do a metrics review

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3997]
We've looked at metrics on annotation during the individual patches, but we should do a final check for the events, and check that everything is in METRICS.md

**Comment by johngruen** [comment]
YEAH!

**Comment by niharikak101** [comment]
@ianb @johngruen I think we can close this - I added events for all annotation tools as part of #4045

**Comment by ianb** [comment]
Seems mostly good to me. Though I'll note the tool events only fire if you actually change tool type, not when you click the button (so if I re-select the pen tool, no event will be fired).

Also no event is fired when you actually use a tool. I think that's more concerning, as that tells us what tools people actually use. For instance, no pen event will be fired if you edit, draw, and save; the only events in that case are the edit and save event.

Now that I've talked myself into it, I'll open an issue  #4184 for that, and as a more minor issue,  #4185 for tracking actual colors in the color picker.
