### ISSUE TITLE
Prototype Chrome add-on

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3998]
A couple thoughts:

- [x] Build Chrome add-on separately, or as a separate build option
- [x] Put some Chrome flag into buildSettings
- [x] There is some kind of dead-ish logic for using the Chrome screen capture API ([tabs.captureVisibleTab](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab)) that needs reviving – the capture takes place in the background page instead of the content worker, so the logic moves around some. This code may or may not work now. It's based on drawWindow feature detection.
- [ ] Disable/remove Full Screen on Chrome, since it lacks [drawWindow](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWindow)
- [x] Insert [browser-polyfill.js](https://github.com/mozilla/webextension-polyfill) everywhere we load things. Maybe conditional on Chrome? Otherwise it's harmless overhead on Firefox. An empty polyfill file in the Firefox build might be the easiest way to avoid overhead.
- [x] We'll need to use browserAction, ala #3967, or maybe the prototype is context-menu-only?
- [x] Check attempts to contact bootstrap.js – most of these should fail gracefully, but the defaults (e.g., no metrics) might not be right on Chrome, and probably there will be error messages in the console
- [x] Build / maintain a separate Chrome-compatible manifest.json

**Comment by 6a68** [comment]
Turning this into a tracking bug for the remaining tasks.

Most of this work is done; I've pushed the prototype to the `chrome-prototype` branch, which includes README changes to explain how to set the chrome target at build time. I'll open separate issues for the remaining tasks.

**Comment by ianb** [comment]
I don't think we're going to launch on Chrome
