### ISSUE TITLE
Rogue Copy to Clipboard Button(?)

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4008]
#### STR

1. Resize your browser window so that there's an horizontal scrollbar (imgur.com works)
2. Move the horizontal scrollbar to right
3. Start screenshots and drag to select an area
4. Move the right border of the selection box as close to the right edge of the page as possible

#### Actual Result

The copy to clipboard button is at the bottom right of the selection box while the rest of the buttons are at the top left.  (See first image below.)

Depending on how close the left border of the selection box is to the left edge of the page, the other buttons are partially obscured or not visible.  (See second image below)

![image](https://user-images.githubusercontent.com/198055/35349565-e831ded0-0100-11e8-92cf-884c6e3dfb7a.png)

![image](https://user-images.githubusercontent.com/198055/35350319-2ef9946e-0103-11e8-8da3-9320d6cf52f0.png)

#### Expected

All the buttons are visible...somewhere.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on the latest Screenshots 29.0.0 version.
