### ISSUE TITLE
Remove `history.pushState()` from /creating 

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4010]
This follows #3995 (PR #4009).  Do not merge the patch for this until the fix for #3995 is released.

**Comment by chenba** [comment]
I'm pushing this one out because the fix for #3995 is being released with Firefox 60; that's a little farther down the road still.

**Comment by chenba** [comment]
Release calendar says Firefox 60 is out on May 9th, so I'm moving this to Sprint 12.

**Comment by chenba** [comment]
Per discussion, for backward compatibility, we should add in a useragent version check so the page will continue to work with older versions of Firefox.

**Comment by 6a68** [comment]
@chenba Also, probably a good idea to file a bug or add a comment to remove that special case code once usage of versions < 60 gets below some number. We don't support ESR on the server, so hopefully the special case code can be removed in a few months

**Comment by 6a68** [comment]
In that case, I'm going to land the PR, and we'll ask QA to test against multiple versions of Firefox. cc @SoftVision-CosminMuntean

**Comment by SoftVision-CosminMuntean** [comment]
@6a68 did the patch landed? I have installed latest [Screenshots (32.1.0) dev version](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on latest Nightly (61.0a1) build and I am still redirected to the "/creating" page if I click the "Back" button from a newly saved shot.
 
Here is a screen recording:
![redirect](https://user-images.githubusercontent.com/19226534/39702354-326095d4-520d-11e8-9625-e906587b32d8.gif)

**Comment by chenba** [comment]
@SoftVision-CosminMuntean Looks like that patch is not on the dev server yet.  Weird.

**Comment by chenba** [comment]
@SoftVision-CosminMuntean There's an eslint error that's been causing test failures, thus blocking the deploy job.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba I think that also the patch for #4183 didn't land on dev server since the issue is still reproducible.
