### ISSUE TITLE
<title> is automatically submitted when uploading screenshot

### ISSUE THREAD

**Issue by kpcyrd** [mozilla-services/screenshots#4012]
I originally reported this over irc in #security and was asked to file an issue:

I noticed when taking a screenshot and uploading it to screenshots.firefox.com, the <title> of the page I screenshoted is automatically submitted and used as a title on screenshots.firefox.com. While sensitive information on the screen can be avoided using the cropping tool, it's non obvious that the <title> is going to be submitted as well (in my case, containing the info that I cropped out :)).

I understand why it's built the way it is and not sure if and how it should be fixed, I thought I just leave this here as feedback.

**Comment by wresuolc** [comment]
Ian is going to investigate if this is exposed to non-owners

**Comment by ianb** [comment]
I think this is okay, except  #4188 leaks non-user-edited titles. This should be reverified after  #4188 is fixed.

To verify:
- Take a shot of some page (e.g., this page), and save it
- Edit the title
- View the page in private mode or some other non-authenticated context
- Search for the title text (e.g., "automatically")

**Comment by SoftVision-CosminMuntean** [comment]
@ianb @chenba just to be sure, where should I search for the title text, in History or on the saved shot using the "find in this page" function (Ctrl + F)?

**Comment by chenba** [comment]
@SoftVision-CosminMuntean I took a shot of this page and updated the title: https://screenshots.dev.mozaws.net/uBMVuXdTcsd3N28u/github.com.  If you view it, you shouldn't be able to find the original title.  But when I look in the page source, there's still a spot where the original title can be found.  So this issue still need to be fixed.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba thanks for calcifying this!
I can reproduce the issue. Even if I open the save shot with other browser, the original title can be found in the page source.
I have tested this using latest Screenshots (32.1.0) dev version on latest Nightly (62.0a1) build.

**Comment by testeaxeax** [comment]
Looks like this issue got fixed. Can anybody confirm?

**Comment by chenba** [comment]
No.  The original title still exist in the shot page response.

**Comment by testeaxeax** [comment]
I can't reproduce it. Where exactly in the pages source is the title supposed to be?

**Comment by chenba** [comment]
@testeaxeax Try:

1. Take a shot of this page
1. Edit the shot's title
1. Go to the shot's page (doesn't matter as owner or not)
1. View page source
1. ctrl-f (or cmd-f) 'automatically submitted'
