### ISSUE TITLE
[Nightly] Tab crashes when performing automatically selections

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4013]
[Notes]:
- This issue is not reproducible for manual selections.
- I've filed this issue in Bugzilla, here: [1433056](https://bugzilla.mozilla.org/show_bug.cgi?id=1433056).

[Regression]:
- I've managed to find a regression window using Mozregression tool. Here are the results:
Last good revision: b529d05259c5f20af811903842655c5061ffb951
First bad revision: 60d339bdf87efaecb07bb108326d0c70a513aa4b
Pushlog: https://goo.gl/wxngyp

[Affected versions]:
- Nightly 60.0a1
- Screenshots 25.0.0, 28.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Nightly browser and navigate to a website.
2. Click the "Page actions" button and select "Take a Screenshot".
3. Perform an automatically selection.
4. Observe the behavior.

[Expected result]:
- The selection is performed.

[Actual result]:
- The tab crashes.

[Additional notes]:
- Here is a screen recording of this issue:
![tab crashes - screenshots](https://user-images.githubusercontent.com/31244235/35381421-df78430a-01c4-11e8-85cb-29842213497d.gif)

**Comment by johngruen** [comment]
Just came here to report this as well...I can repro on OSX and windows

**Comment by johngruen** [comment]
This is upstream of us but i am going to leave it open and untriaged to track.

**Comment by Softvision-CristinaBadescu** [comment]
I'm going to close this issue since it has been fixed in bug #[1433056](https://bugzilla.mozilla.org/show_bug.cgi?id=1433056) and is no longer reproducible using Firefox Screenshots v25.0.0 or Firefox Screenshots v28.0.0 dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), using latest Nightly build 60.0a1 (2018-01-26), on Windows 10x64, Mac 10.12.6 and Arch Linux 4.12.
