### ISSUE TITLE
Loading screenshots page triggers repeated Firefox error alert messages

### ISSUE THREAD

**Issue by gene1wood** [mozilla-services/screenshots#4017]
I'm not entirely sure how to describe this but here's a video of it happening. When browsing to this screenshot I took, Firefox launches a Screeshots-specific error window.

[![Firefox Screenshots bug](https://img.youtube.com/vi/5FYPLSCEsZ8/0.jpg)](https://www.youtube.com/watch?v=5FYPLSCEsZ8)

**Comment by gene1wood** [comment]
If you understand what is going on under the hood to cause this bug, please feel free to modify the title of this issue with something more descriptive as I'm unsure how to accurately describe what's going on here.

**Comment by johngruen** [comment]
@gene1wood what version of FF are you in

**Comment by gene1wood** [comment]
@johngruen 57.0.4

@6a68 Here's that console output (I can provide in a different format if desired)

![workspace 1_076](https://user-images.githubusercontent.com/1134034/35401448-5c57030a-01ae-11e8-819d-ebb6c2eeb85a.png)

**Comment by SoftVision-CosminMuntean** [comment]
@gene1wood can you reproduce this issue only for the screenshots taken on "www.paypal.com" website? Or is also reproducible for screenshots taken on other websites?

Can you please retest this issue on safe mode to eliminate add-ons as a possible cause? If it's not reproducible in safe mode, can you provide the list with all enabled add-ons? I will try to install them and see which add-on caused this.

**Comment by gene1wood** [comment]
@SoftVision-CosminMuntean 

> can you reproduce this issue only for the screenshots taken on "www.paypal.com" website? Or is also reproducible for screenshots taken on other websites?

It's reproducible for screenshots taken on other sites. Here is another one that does the same thing for me : https://screenshots.firefox.com/aEDluHd21nIcYRpf/screenshots.firefox.com

As does this one https://screenshots.firefox.com/l9b8VTHGHvqe5CXs/github.com

> Can you please retest this issue on safe mode to eliminate add-ons as a possible cause?

I tested this in another firefox profile with no add-ons and it occurred in that one too

I tested it in a brand new profile in safe mode and it does *not* occur.

Does the console output [above](https://github.com/mozilla-services/screenshots/issues/4017#issuecomment-360531247) reveal anything.

Here's the console output in safe mode if you want to compare

![selection_077](https://user-images.githubusercontent.com/1134034/35452012-f66f172c-0279-11e8-98d7-8c16ad8b07d0.png)

**Comment by SoftVision-CosminMuntean** [comment]
@gene1wood thanks for testing it!
I am not sure, but after looking at the errors I think that this issue is related to #3581. Do you have any custom configuration related to history or cookies on the profile where the issue is reproducible? 

Also, Firefox 58.0 was released last week and contains a new version of Screenshots that has some fixes related to cookies. If you don't mind, can you test if the issue is also reproducible on Firefox 58?

**Comment by gene1wood** [comment]
> Do you have any custom configuration related to history or cookies on the profile where the issue is reproducible?

The two profiles that I use regularly don't have any interesting cookie or history configuration that I know of.

> Also, Firefox 58.0 was released last week and contains a new version of Screenshots that has some fixes related to cookies. If you don't mind, can you test if the issue is also reproducible on Firefox 58

The three errors shown in the console [that I mention above](https://github.com/mozilla-services/screenshots/issues/4017#issuecomment-360847435) are gone in Firefox 58 and the problem does not occur.

**Comment by wresuolc** [comment]
If this doesn't occur anymore, I think this is fixed?  Re-open if I'm misreading.
