### ISSUE TITLE
Document bug labels

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4019]
There was an email thread about adding some new bug labels, but I don't think the new labels are documented. Maybe in the readme?

**Comment by wresuolc** [comment]
Look at how React does it

**Comment by wresuolc** [comment]
I have a draft of this over here: https://github.com/mozilla/testpilot/pull/3334

**Comment by wresuolc** [comment]
This landed at https://github.com/mozilla/testpilot/blob/master/docs/experiments/developing_an_experiment.md#labels

@6a68 - do you think we need docs in Screenshots that points to that or is being a part of the program enough?  I also see that someone added descriptions to all our labels which is probably even better than my docs anyway.  I'm going to close this, re-open if you wanted more.
