### ISSUE TITLE
Add Selenium Test for Switching the `disabled` Pref On/Off

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4033]

**Comment by chenba** [comment]
@aakashhdesai That pref hides the "Save" button in the addon.  If you start Screenshots in a regular tab (not Private Browsing), then you should not see the "Save" button when you selected an area to capture.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
