### ISSUE TITLE
canvas alert when screenshoting

### ISSUE THREAD

**Issue by nrobinaubertin** [mozilla-services/screenshots#4039]
Hi,

I'm on archlinux with firefox 58.0 (64bits). 
The privacy.resistFingerprinting config is set to true.

When I try to use the screenshot tool, the canvas alert is triggered (even on static pages not using the canvas). I may want to use the tool on webpages where I block canvas usage : is it possible to decorelate the rights of the screenshoting tool from the webpage ?
For example, I blocked canvas usage on github and I'm no longer able to use the screenshots tool (it saves blank images).

**Comment by ianb** [comment]
In [Bugzilla Bug 1412961](https://bugzilla.mozilla.org/show_bug.cgi?id=1412961) they are discussing how to keep Screenshots and other extensions working with resistFingerprinting on. Screenshots will rely on fixes to fingerprinting.

**Comment by nrobinaubertin** [comment]
Thanks for the answer !
