### ISSUE TITLE
zopflipng the images

### ISSUE THREAD

**Issue by timdream** [mozilla-services/screenshots#4059]
The png images need to be compressed from the upstream. See

https://bugzilla.mozilla.org/show_bug.cgi?id=1234008

Thanks!

**Comment by timdream** [comment]
Actually, I am not sure if I should just push the changes to m-c first and for someone to "downlift" it to here instead. Let me know what I should do.

**Comment by ianb** [comment]
@timdream You can commit them in m-c, and we'll try to get it all fixed up on our end for the next export that we do. Thanks for the heads up!
