### ISSUE TITLE
Offset issues on ING.nl

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4060]
[Bug 1433052](https://bugzilla.mozilla.org/show_bug.cgi?id=1433052) reports a selection problem on ING.nl. It appears to be on an interior banking page, which makes it hard to reproduce. Probably this is a CSS conflict. @SoftVision-CosminMuntean noted it might be #3907

**Comment by SoftVision-CosminMuntean** [comment]
The reporter cannot reproduce the issue using the latest Screenshots dev version, so I think that the issue was fixed by #3907 (see [bug 1433052](https://bugzilla.mozilla.org/show_bug.cgi?id=1433052#c10)).
