### ISSUE TITLE
Consider being more strict about request formatting

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4067]
This is a bit open ended, but let's look into what we currently call a malformed request and (maybe) better define that and expand it.  This could be just making sure some fields aren't null, or it could be making sure UAs are well formed, or anything between.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
