### ISSUE TITLE
Consider rate limiting requests

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4068]
This could be all requests, or just uploads, or just upload attempts that fail, or something else...

**Comment by wresuolc** [comment]
@oremj is this an easy thing to do from your end (like, is it already built-in to our servers?)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
