### ISSUE TITLE
Consider adding contact information to the 404 pages on the CDN

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4069]
Images are often embedded when they are used and show up with a URL similar to:

> https://screenshotscdn.firefoxusercontent.com/images/xxxxxxxx.png

If you drop the filename and look at the directories above one is a custom 404 and one is a generic 404.  When someone is looking for contact information and all they have is a URL it can be hard to find.  Let's add a note about what the service is and a link to report abuse easily on:

> https://screenshotscdn.firefoxusercontent.com/images/
> https://screenshotscdn.firefoxusercontent.com/

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
