### ISSUE TITLE
Should Screenshots be on the cloud services status page?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4071]
https://status.services.mozilla.com/

**Comment by wresuolc** [comment]
@oremj this seems like a good idea (thanks @6a68)

**Comment by sexyegor** [comment]
it should go where the most participate!!  wayne

**Comment by oremj** [comment]
We can add it for you. Right now, it's just manually updated. We are currently working on a better solution, so it might be better to wait for that.

**Comment by wresuolc** [comment]
Thanks oremj.  Let's do the manual add and then it will already be there when we flip to automatic.

**Comment by oremj** [comment]
@jasonthomas can you add this to the status page?

**Comment by jasonthomas** [comment]
What should we use for service name? I was thinking "Firefox Screenshots".

**Comment by wresuolc** [comment]
That'd be great, thanks

**Comment by jasonthomas** [comment]
Done.
