### ISSUE TITLE
The descriptive images from Screenshots tour page are not displayed Safari

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4082]
[Affected versions]:
- Safari 11.0.3

[Affected Platforms]:
- All Mac OS

[Steps to reproduce]:
1. Open the Safari browser and navigate to "https://screenshots.firefox.com" page.
2. Observe the descriptive images from the page.

[Expected result]:
- The descriptive images are correctly displayed.

[Actual result]:
- The descriptive images are no longer displayed.

[Notes]:
- The issue is not reproducible on Firefox, Chrome, Opera, Edge or Internet Explorer.
- This issue is also reproducible on dev abd stage servers.
- Here is a screen recording with the issue: https://goo.gl/v3efGx

**Comment by chenba** [comment]
Probably because of svgo (#3853)

**Comment by johngruen** [comment]
Cool that safari sucks...maybe we should just convert these to PNGs?

**Comment by chenba** [comment]
Oh, on the site.  Different issue # then (and been around for a little while now), but still a svgo thing.

**Comment by 6a68** [comment]
It looks like the issue is that Safari supports "xlink:href" (SVG 1.1), but not plain "href" (SVG 2). This bug was introduced an eternity ago, by the fix for https://github.com/mozilla-services/screenshots/issues/3063.
