### ISSUE TITLE
Changing expires removes how long ago it was uploaded

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/screenshots#4085]
Before:
<img width="333" alt="screen shot 2018-02-09 at 10 52 29 am" src="https://user-images.githubusercontent.com/26739/36036251-68627b7c-0d87-11e8-85e9-5ef3966b290d.png">

Then I click the little "Expires ..." button and immediately click "Cancel" 

After:
<img width="260" alt="screen shot 2018-02-09 at 10 52 44 am" src="https://user-images.githubusercontent.com/26739/36036282-7b68b8d0-0d87-11e8-919c-9e41953cc56f.png">

If the information about how long ago it was upload was good, why does it disappear?

**Comment by peterbe** [comment]
Uh. This is on the perma page for displaying the screenshot.

**Comment by johngruen** [comment]
I am like 99.9% sure this is a dupe

**Comment by johngruen** [comment]
Found it! I'll move the original out of its backlog and we'll re-triage it on Monday

#3255
