### ISSUE TITLE
Pasting into email comes out the other end as a img tag with a data URI

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4086]
Because we can't have nice things...

I copied something to clipboard and pasted into an email in inbox.google.com. Everything looked fine on my end during composition, but the result on the receiving end was a big fat dataURI in the email. It also looks broken in my *Sent* folder:

![image](https://user-images.githubusercontent.com/3323249/36037252-7f3be5ce-0dbc-11e8-9cb4-aaa7fd286bfa.png)
nb. This image was taken via copy to clipboard from Screenshots

**Comment by 6a68** [comment]
I think this might be [bug 1308007](https://bugzilla.mozilla.org/show_bug.cgi?id=1308007), or one of the [many bugs in its dependency tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1308007).

**Comment by ianb** [comment]
We won't be able to fix this in Screenshots; we'll have to depend on the upstream fixes for this.
