### ISSUE TITLE
"Time ago" indicator is stale

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/screenshots#4087]
I saved this screenshot a lot more than "34 min" ago. 
Still says 34 min ago. 
https://screenshots.firefox.com/S0CHjUwFNOGl5a7C/screenshots.firefox.com

When I refresh the page it says "1 hour" now but that's going to get stale too. 

(Sorry if this is a dupe. It's hard to search for)

**Comment by ianb** [comment]
We don't currently do any updates of pages after they load, so we never pick up the update. A fix for this would probably involve some `setInterval(render)`

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
