### ISSUE TITLE
Automatic add to clipboard

### ISSUE THREAD

**Issue by mathieu-aubin** [mozilla-services/screenshots#4091]
I must say i havnt really checked into the settings but i strongly suggest the automatic clipboard addition to be optional and NOT set to on by default -- this could potentially f** this up for someone

**Comment by ianb** [comment]
Note we have a concept for tool preference that would allow turning this off in #1766.

**Comment by mathieu-aubin** [comment]
Still is a very annoying situation, any progress?

**Comment by 6a68** [comment]
Pull requests welcome :-)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
