### ISSUE TITLE
[Annotations] The annotation button remains highlighted after canceling the edit mode

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4093]
[Notes]:
- This issue is no longer reproducible if you click the "Confirm" button, so I'm not sure if this is the intended behavior.
- Also, the annotation button is no longer highlighted if you refresh the page.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the any website.
2. Right click on the page and select "Take a Screenshot" from the context menu.
3. Perform a selection and click the "Save" button.
4. Click the "Edit this image" highlighted annotation button.
5. Click the "Cancel" button and observe the "Edit this image" annotation button.

[Expected result]:
- The "Edit this image" annotation button is no longer highlighted.

[Actual result]:
- The "Edit this image" annotation button remains highlighted.

[Additional notes]:
- Here is a screen recording with the issue:
![edit this image highlighted button](https://user-images.githubusercontent.com/31244235/36101755-e901ef00-1012-11e8-8cd8-db266f6c6874.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
