### ISSUE TITLE
[Annotations] Drawing can be wrongly performed using right click

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4100]
[Notes]:
- This issue is also reproducible for Crop mode.
- This issue is also reproducible for middle button click.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Right click on the image and observe the behavior.

[Expected result]:
- The context menu is opened and nothing is drawn.

[Actual result]:
- A point is drawn and the context menu is open.

[Additional notes]:
- Here is a screen recording with the issue:
![right click draws](https://user-images.githubusercontent.com/31244235/36142845-e729fe4e-10b1-11e8-9af8-5acd8efdd494.gif)

**Comment by chenba** [comment]
#4116 didn't fix this when I tested it.

**Comment by Softvision-CristinaBadescu** [comment]
Indeed, this issue is still reproducible using Firefox Screenshots v28.0.0 dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 60.0a1 (2018-02-18), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.

**Comment by chenba** [comment]
Re-opening this because it isn't quite fixed in the latest patch.  The mouse down state in `setPosition` is not checking which mouse button is pressed.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v31.3.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html
), on latest Nightly build 61.0a1 (2018-03-25), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. Drawing can no longer be performed using the right click or the middle button click.
