### ISSUE TITLE
[Annotations] The annotations buttons can wrongly be actioned before the image is loaded

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4102]
[Notes]:
- This issue is easier to encounter for large screenshots.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a large saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the large saved shot link.
2. Click the "Edit this image" button.
3. Before the image is fully loaded, draw on the page.
4. Observe the behavior.

[Expected result]:
- Nothing happens, the annotations buttons are inactionable.

[Actual result]:
- The drawing is performed.

[Additional notes]:
- Here is a screen recording with the issue:
![drawn before image is loaded](https://user-images.githubusercontent.com/19226534/36154910-912a7184-10db-11e8-9280-914652917bfc.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
