### ISSUE TITLE
[Annotations][Enhancement] The mouse cursor should be changed into a crop cursor, when you are in crop mode

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4103]
[Affected versions]:
- Nightly 60.0a1
- Screenshots 28.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit This Image" button and click the "Crop" tool.
3. Hover the image and observe the mouse cursor.

[Expected result]:
- The mouse cursor is changed into a crop cursor.

[Actual results]:
- The mouse cursor is not changed and remains in its current state.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
