### ISSUE TITLE
Data Studio page 5 shows mobile uploaders/downloaders

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4112]
This seems funny. Uploading and downloading stats are identical and...how are people uploading from iOS or android?

![](https://screenshotscdn.firefoxusercontent.com/images/83e55836-42f7-452d-a9c5-17416a675d42.png)

**Comment by johngruen** [comment]
![image](https://user-images.githubusercontent.com/3323249/36218265-13f903f4-11b4-11e8-9515-dc94dd255fbb.png)

Fixed
