### ISSUE TITLE
Disable Screenshots page action on non-http(s) pages

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4121]
(I think this bug may already exist, but I can't find it right now.)

Some about pages, like `about:telemetry` or `about:mozilla`, show the page action menu, and the Screenshots item is enabled there, but it shouldn't be.

The webcompat reporter disables itself in such cases like this: ([dxr](https://dxr.mozilla.org/mozilla-central/rev/27fd083ed7ee5782e52a5eaf0286c5ffa8b35a9e/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#52-57)):

```js
  onLocationChange(window) {
    let action = PageActions.actionForID("webcompat-reporter-button");
    let scheme = window.gBrowser.currentURI.scheme;
    let isReportable = ["http", "https"].includes(scheme);
    action.setDisabled(!isReportable, window);
  },
```

where `onLocationChange` is attached inside the `PageActions.addAction` call ([dxr](https://dxr.mozilla.org/mozilla-central/rev/27fd083ed7ee5782e52a5eaf0286c5ffa8b35a9e/browser/extensions/webcompat-reporter/content/WebCompatReporter.jsm#43)):
```js
    PageActions.addAction(new PageActions.Action({
      // ... stuff ...
      onLocationChange: (window) => this.onLocationChange(window)
    }));
```

We should do something similar. (See [BMO bug 1437445](https://bugzilla.mozilla.org/show_bug.cgi?id=1437445) for more discussion.)

**Comment by 6a68** [comment]
Hmm, if we land #3967, I guess this fix wouldn't work

**Comment by ianb** [comment]
I think with #3976 this will be fixed or at least better, so let's defer to that change.
