### ISSUE TITLE
URL and chrome option in uploads

### ISSUE THREAD

**Issue by DerSmythe** [mozilla-services/screenshots#4127]
Sometimes it's necessary to have metadata with the URL the snapshot was saved from when uploaded. At other times it would be handy to also have the browser chrome (the URL bar) in the snapshot.

Yet this could cause security issues, so it should probably be a user preference with some sane safe defaults.

Links to 
#4012 
#4021

**Comment by ianb** [comment]
Note for someone considering this: Chrome has an Extension API to implement system screenshots, but Firefox does not yet have this. (Probably Firefox will get it eventually)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
