### ISSUE TITLE
[Annotations]There is a noticeable delay until a large image is loaded in edit mode

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4128]
[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to any website.
2. Right click on the page and select "Take a Screenshot" from the context menu.
3. Perform a large selection and click the "Save" button.
4. Click the "Edit this image" annotation button and observe the behavior.

[Expected result]:
- A spinner loading appears until the image is loaded.
or
- The image is loaded without any noticeable delay.

[Actual result]:
- The image in loaded after a couple of seconds and a vertical and darker line appears on the background, before the image is loaded.

[Notes]:
- Here is a screen recording with the issue:
![ss - noticeable delay until image loaded in edit mode](https://user-images.githubusercontent.com/31244235/36376105-96d19c90-157a-11e8-9dd2-0065910946bb.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
