### ISSUE TITLE
When selecting text in the URL bar, suggest PageShot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#413]
One common sharing technique is to highlight and copy the URL from the URL bar, then share it somehow.  This is a time when we could suggest the user could use PageShot.

One technique might be to watch the clipboard for a URL, and suggest PageShot when we see that happen (and maybe Firefox is focused, and the URL represents a current tab), and then pop something up in that case.

**Comment by brampitoyo** [comment]
An interesting thing we could do is supplement the copy interface with PageShot. All the user needs to do is press Ctrl+C or right click-Copy the second time.

Video:
https://www.dropbox.com/s/my6zyi8jq7gyecl/pageshot-mini-shot-panel-video.mov

* The first time Ctrl + C is pressed from inside the location bar, the URL copies to clipboard as usual
* The second time Ctrl + C is pressed, PageShot:
  * Takes a visible snapshot of the page and upload it to PageShot server
  * Opens a mini panel containing just the link
  * Copies the link to clipboard and gives a visual indicator

We now have two kinds of copy:
* Press Ctrl + C once: copy site URL
* Press Ctrl + C twice: copy site at that moment in time (PageShot URL)

Of course, you can re-copy the link again by clicking the “Copy Link” button manually.

**Comment by ianb** [comment]
Note Hello has this functionality implemented now

**Comment by wresuolc** [comment]
This raises some questions with Photon.  Also shipping as a web extension will make this tough.
