### ISSUE TITLE
[Annotations] Start Loader Animation Immediately After User Clicks Save

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4130]
#4000 [PR #4129] added the loader animation for the upload part of the annotation save.  The loader should be displayed as soon as Save is clicked, before converting the canvas into an image.

Ideally the animation is also displayed during the canvas to image part of the save, but that may be too difficult.

**Comment by chenba** [comment]
Note that given the async nature of JS, we'd probably need to ensure that the loader is displayed before we call `canvas.toDataURL()`.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
