### ISSUE TITLE
Screenshots youtube video on homepage

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4131]
The [Screenshots post on the Firefox blog](https://blog.mozilla.org/firefox/share-exactly-see-screen-firefox-screenshots/) embeds a pretty sweet little onboarding video.

How about we put this above the fold on the screenshots.firefox.com landing page?

[![screenshots vid](https://img.youtube.com/vi/lv0Mp2ZBKSE/0.jpg)](https://youtu.be/lv0Mp2ZBKSE)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
