### ISSUE TITLE
[Annotations][Enhancement] The edit header should be sticky so the annotations tools are accessible for scrolled images

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4139]
[Notes]:
- Since we have the possibility to perform long screenshots, this enhancement will help users to avoid scrolling up to have access to annotations tools (changing colors, changing drawing tools or crop). 

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a long saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Scroll down until you reach the end of the image and observe the annotations tools.

[Expected result]:
- The annotations tools are in sight and can be accessed.

[Actual result]:
- You need to scroll the page up in order to have access to the annotations tools.

[Notes]:
- Here is a screen recording with the issue:
![enhancement - sticky header](https://user-images.githubusercontent.com/31244235/36539501-bf4292c6-17df-11e8-921f-6343dc5bfaef.gif)

**Comment by johngruen** [comment]
This is a great idea

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots 31.0.0 dev version, on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
