### ISSUE TITLE
[Annotations] The part of the image that exceeds 8100px looks broken in Edit mode on Windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4140]
[Notes]:
- Also, the drawing tools are not working properly on the affected part.
- This issue is not reproducible on Linux and Mac.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a long website (eg: imgur).
2. Scroll the page in order to load a large amount of content.
3. Save the full page and click the "Edit this image" button.
5. Scroll to the bottom of the page and observe the image.

[Expected result]:
- The image is correctly displayed.

[Actual result]:
- The bottom part of the image looks broken.

[Additional Notes]:
- Here is a screen recording with the issue:
![broken image in edit mode 2](https://user-images.githubusercontent.com/19226534/36542958-07d4be50-17eb-11e8-92b2-a0768bca8912.gif)

**Comment by chenba** [comment]
@niharikak101 if you don't have access to a Windows machine, let me know or assign this to me.

**Comment by niharikak101** [comment]
@chenba that would be pretty helpful!

**Comment by chenba** [comment]
I am unable to reproduce this bug on Windows 10.

**Comment by SoftVision-CosminMuntean** [comment]
I just tested this issue on Windows 10 x64 and Windows 7 x64 with latest Screenshots 31.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) and I have managed to reproduce the issue.

@chenba  is easier to reproduce the issue using the following STR:
1. Navigate to https://en.wikipedia.org/wiki/Sun website.
2. Save the full page.
3. Click the "Edit this image" button.
4. Scroll to the bottom of the page and observe the image.

Please let me know if you need more information.

**Comment by chenba** [comment]
Here's a video of me doing just that: https://youtu.be/p4qRAHczvPM

**Comment by SoftVision-CosminMuntean** [comment]
I did more investigation and I have re-tested this issue on 7 different machines. I have managed to reproduce the issue on 4 out of 7 machines. The only difference between them is the processor.
So, it seems that the issue is reproducible only on AMD processors, but it's not reproducible on Intel processors.

@chenba do you also have a Intel processor?

**Comment by chenba** [comment]
@SoftVision-CosminMuntean Yeah, only Intel processors here.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean AMD-specific bug sounds like a Nightly platform regression, I think. Would you mind filing a bug on Bugzilla?

**Comment by SoftVision-CosminMuntean** [comment]
It seems that Screenshots cannot be installed on older Nightly builds than 60, so I haven't managed to test this issue in order to see if this is a Firefox regression.
However, I will do more investigations after Annotations are released on production and also I will log a bug on Bugzilla related to this.

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the issue is also reproducible on Intel processors. Until now I have managed to reproduce it with the following processors:
- Intel (R) Core (TM) 2 Duo CPU E8400 3.00 GHz
- AMD FX (tm)-8320 Eight-Core Processor 3.50 Ghz

**Comment by SoftVision-CosminMuntean** [comment]
@chenba I also tested this issue with hardware acceleration off as you suggested in Cristina's issue #4150 and it is also not reproducible.
I have also noticed that the drawing action is smoother on large pages if the hardware acceleration is off.

**Comment by SoftVision-CosminMuntean** [comment]
I have logged this issue on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1450897
