### ISSUE TITLE
An extra border is wrongly displayed on the right side of the shot if the "Save visible" option is used

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4147]
[Notes]:
- Is also reproducible on Mac if the "Show scrollbars" option is set to "Always".
- If the browser is resized so that the horizontal scrollbar is displayed, the issue is only reproducible if the page is scrolled to the right maximum limit.
- The issue is only reproducible for "Save visible" option.
 
[Affected versions]:
- Nightly 58.0.2 and up
- Screenshots v25.0.0
- Screenshots v29.0.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open Firefox browser an navigate to "http://www.history.com/" website.
2. Click the "Take a Screenshot" option from "Page Actions" menu or context menu.
3. Click the "Save visible" button and save the shot
4. Observe the right part of the shot.

[Expected result]:
- The image is correctly displayed and no extra borders are displayed.

[Actual result]:
- An extra border is displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
![border](https://user-images.githubusercontent.com/19226534/36590549-adababb6-1897-11e8-9204-ceb94407007f.gif)

**Comment by johngruen** [comment]
This is an FF bug that we should kick down the road a little bit

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible using the latest Screenshtos (32.1.0) dev version on latest Nightly (62.0a1) build.
Tested on Windows 7 x64, Mac 10.12 and Arch Linux.
