### ISSUE TITLE
Blank thumbnail is wrongly displayed in "My Shots" page for cut off images that were saved through "Save full page" option, on Windows

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4150]
[Notes]:
- This issue is not reproducible on Firefox release 58.0.2, using Firefox Screenshots v25.0.0.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0dev, v29.0.0

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox browser and navigate to the "https://en.wikipedia.org/wiki/Sun" page.
2. Click the "Page Actions" menu and select the "Take a Screenshot" option.
3. Click the "Save full page" option and click the "Save" button.
4. Navigate to "My Shots" page and observe the shot's thumbnail.

[Expected result]:
- The shot's thumbnail is correctly displayed.

[Actual result]:
- Blank thumbnail is displayed for the saved shot.

[Additional notes]:
- This issue is reproducible only for selections that exceed 10.000px and that are performed using "Save full page" option.
- This issue is not reproducible if you manually perform a very long selection.
- Here is a screen recording with the issue:
![ss - blank thumbnail](https://user-images.githubusercontent.com/31244235/36678243-e791c8be-1b18-11e8-97a5-e7d77f19df65.gif)

**Comment by chenba** [comment]
I just tried it and I cannot reproduce it.  @Softvision-CristinaBadescu Can you still produce this bug?

**Comment by Softvision-CristinaBadescu** [comment]
Hey @chenba , I can still reproduce this issue on Windows 10x64 and Windows 7 x64 (both have AMD FX Eight-Core Processor 3.50 Hz), but this issue also might be related to the machine's processor, since I was not able to reproduce it on a Window 10 x64 machine that has Intel Core i5-6500 CPU @ 3.20GHz.

**Comment by chenba** [comment]
@Softvision-CristinaBadescu Hmm can you try disabling the "Use hardware acceleration when available" preference?

**Comment by Softvision-CristinaBadescu** [comment]
Thanks @chenba for this information! I cannot reproduce this issue if I disable the mentioned preference on both Windows 7 and Windows 10.

**Comment by chenba** [comment]
@Softvision-CristinaBadescu If you have the access, you could try updating the video drivers to the latest versions on those machines.

cc @SoftVision-CosminMuntean

**Comment by SoftVision-CosminMuntean** [comment]
@chenba I tried to update the video drivers on Windows 7 x64, but it seems that the software is up to date even if it's from 2013. 
However, I will also try on Windows 10 x64 and I will report the results.

**Comment by SoftVision-CosminMuntean** [comment]
I have logged this issue in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1450894
