### ISSUE TITLE
[Annotations] Toolbar icon measurement adjustment 

### ISSUE THREAD

**Issue by fangshih** [mozilla-services/screenshots#4155]
The toolbar icon seems a little off alignment.  I think is because of the pen icon a little slimmer than the rest of icon. Also, the color button is a bit large, it creates an uneven space.   
I've adjusted the pen icon, and we may need to change the color circle to a smaller size 19x19 ( not included the stroke )  it should be able to slove the problem. Thanks!
**Pen icon**
https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/Annotation/Assets/annotation-pen.svg
**Meaturment spec**: 
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Annotation/Annotation-icon-spacing/

Image: 
![screen shot 2018-02-27 at 5 13 12 pm](https://user-images.githubusercontent.com/4862573/36719994-991e7e2e-1be1-11e8-87ea-930855dfafcc.png)

**Comment by niharikak101** [comment]
@fangshih Could you also provide a blue icon for when the pen tool is active? Thank you!
