### ISSUE TITLE
[Annotations] Need to change the refresh icon to Photon version 

### ISSUE THREAD

**Issue by fangshih** [mozilla-services/screenshots#4156]
Need to update the refresh icon. The arrow should be going right instead of left. 
**Icon asset**
https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/Annotation/Assets/annotation-refresh.svg
![screen shot 2018-02-27 at 5 17 11 pm](https://user-images.githubusercontent.com/4862573/36720139-1555ce20-1be2-11e8-9464-8ed887cd56a6.png)

Thanks!

**Comment by ianb** [comment]
The button means "revert" not "refresh", so we believe it's correct. Though maybe if we have an "undo" icon that would be better, as clearly it's confusing as it is.

**Comment by ianb** [comment]
We'll close it for now, but can reopen this if someone feels it is too confusing.
