### ISSUE TITLE
The paginate arrows from "My Shots" page are wrongly displayed in active and hover states

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4157]
[Notes]:
- Based on the UX requirements for the "My Shots" page pagination from issue #3391, the arrows should be centered on a gray background.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v25.0.0, v28.0.0dev, v29.0, v31.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Windows

[Prerequisites]:
- Have at least 25 screenshots saved.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://screenshots.firefox.com/shots.
2. Scroll down and hover the right arrow.
3. Observe the arrow when it's hovered.

[Expected result]:
- The right arrow is centered on a gray background.

[Actual result]:
- The right arrow is not centered in the gray background and it is slightly lower.

[Additional notes]:
- The same behavior can be observed when the arrow button is clicked and it is in the active state.
- Here are some screenshots with the issue:
![next page](https://user-images.githubusercontent.com/31244235/36729327-7c180e40-1bcc-11e8-8136-f26a4a395dd7.png)
![previous page](https://user-images.githubusercontent.com/31244235/36729334-7ea68268-1bcc-11e8-9502-5fd741ab5530.png)

- Here is a screen recording with the issue:
![ss - pagination](https://user-images.githubusercontent.com/31244235/36729340-8227023c-1bcc-11e8-94de-dcacdd648bd5.gif)

**Comment by 123survesh** [comment]
Hi I would like to work on this issue, I will update here, once I have some progress.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
