### ISSUE TITLE
None of the page scroll hotkeys work when the Screenshots overlay it's displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4158]
[Notes]:
- The page can be scrolled using mouse click or scrollbar.
- The hot keys are working if a selection is performed.
- Here are the hotkeys for scolling the page: "Home", "End", "Page Up", "Page Down", and arrows keys. 
 
[Affected versions]:
- Firefox 58.0.2 and up
- Screenshots v25.0.0
- Screenshots v29.0.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open Firefox browser an navigate to a large website (eg: imgur.com).
2. Click the "Take a Screenshot" option from "Page Actions" menu or context menu.
3. Press the "Home"/"End"/"Page Up"/"Page Down" or arrow keys.
4. Observe the behavior.

[Expected result]:
- The page is correctly scrolled according to the used hotkey. 

[Actual result]:
- The page is not scrolled.

[Additional Notes]:
- Here is a screen recording with the issue:
![hot keys](https://user-images.githubusercontent.com/19226534/36743122-20f91d8a-1bf2-11e8-8e00-b726f5dfbc85.gif)

**Comment by ianb** [comment]
For now we've decided not to fix this. If someone finds this problematic, please reopen.
