### ISSUE TITLE
[Enhancement][Annotations] The highlighter's yellow color should also be intensified when multiple lines overlap

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4167]
[Affected versions]:
- Nightly 60.0a1
- Screenshots 31.0.0 stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 31.0.0 stage version installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on a new clean profile.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the browser and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Select the "Highlighter" tool and change the color to yellow.
4. Triple click in the same spot the image and observe the drawing.

[Expected result]:
- The yellow drawing intensifies.

[Actual result]:
- The yellow nuance remains the same.

[Notes]:
- This behavior is easier to be noticed on dark images.
- All the other's colors nuances are intensified at multiple clicks in the same spot.
- Here is a screen recording with the issue:
![ss - intensify yellow](https://user-images.githubusercontent.com/31244235/36851314-a2b2b590-1d71-11e8-8181-e00118f585fd.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
