### ISSUE TITLE
[Annotations] The edited image is wrongly saved even if you cancel the save action

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4171]
[Affected versions]:
- Nightly 60.0a1
- Screenshots v31.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v31.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a long saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and draw on the image.
3. Click the "Save" button and rapidly click the "Cancel" button.
4. Observe the image.

[Expected result]:
- The saving action was canceled and the changes are not saved.
or 
- The "Cancel" button becomes unactionable until the saving is complete.

[Actual result]:
- All the changes applied on the image are saved.

[Notes]:
- Here is a screen recording with the issue:
![ss - cancel](https://user-images.githubusercontent.com/31244235/36903649-06402924-1e37-11e8-93ad-7a3df90b190c.gif)

**Comment by chenba** [comment]
The fix for this would be to disable the cancel button while the loader animation is displayed.

**Comment by johngruen** [comment]
has PR

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots v31.2.0 stage installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
