### ISSUE TITLE
When in Firefox, Screenshots favicon should match icon style of other Firefox feature icons

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4178]
Since Screenshots is built in to Firefox, the feature icon really should match other icons in Firefox for the sake of consistency. This means no colour.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/473531/36981026-018d6fc0-205a-11e8-8bd0-611df8644cb5.png">

The icon can remain coloured for users in other browsers for the sake of branding.

**Comment by johngruen** [comment]
We can't match the theme color from a web icon, so i'm going to close this.
