### ISSUE TITLE
Add link to relaunch FTU on empty state in My Shots

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4179]
There is a missed opportunity for teaching users how to use Screenshots on the empty state screen in the My Shots library.

A user could open the feature, see the tour, and then not use it for months. Upon returning there is no way to relearn the feature.

This is the current empty state graphic:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/473531/36981292-c9ce8500-205a-11e8-92d7-5e390294248d.png">

I propose adding a third line that says "See how!" which relaunches the tour when clicked.

**Comment by ianb** [comment]
I think linking to https://screenshots.firefox.com/#tour will lead people to the intended tour

**Comment by sevaan** [comment]
![image](https://user-images.githubusercontent.com/473531/37774679-45afa492-2db7-11e8-8dcb-7cddda7f8888.png)

Changed the string slightly.

You have no saved shots. Go create some. See how!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
