### ISSUE TITLE
Share title of image as well as URL when sharing over Twitter.

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4181]
When a user shares their screenshot over Facebook, the image title as well as the URL is shared. However, when sharing a screenshot over Twitter, only the URL is shared. The title should also be added for extra context and to save the user from having to type in their own descriptor.

<img width="594" alt="screen shot 2018-03-05 at 10 08 00 am" src="https://user-images.githubusercontent.com/473531/36982133-1abe3c1a-205d-11e8-85df-b66b3d4a6835.png">

**Comment by wresuolc** [comment]
Twitter pulls the title automatically so we're going to wontfix this
