### ISSUE TITLE
If Screenshots is first used on a non-standard web page, the Screenshots "#hello" page is wrongly opened in a new tab

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4183]
[Notes]:
- This issue is not reproducible if you use the context menu option.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v31.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v31.1.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Firefox Screenshots has not been used.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to a non-standard web page such as https://addons.mozilla.org/en-US/firefox/.
2. Click the "Page actions" menu.
3. Select "Take a Screenshot" option and observe the behavior.

[Expected result]:
- "We can't screenshot this page." notification appears.

[Actual result]:
- A new tab is opened and you are redirected to the "https://screenshots.firefox.com/#hello" page.

[Additional notes]:
- Here is a screen recording with the issue:
![ss - non standard page](https://user-images.githubusercontent.com/31244235/36983091-26159e04-209a-11e8-8255-6e664caaa213.gif)

**Comment by johngruen** [comment]
We should redirect to onboarding from the context menu as well.

**Comment by testeaxeax** [comment]
My fix shows the "We can't screenshot this page." notification and then opens "https://screenshots.firefox.com/#hello" to perform onboarding. It works via the "Page actions" and the context menu.

**Comment by Softvision-CristinaBadescu** [comment]
This issue has been partially fixed: if you use the context menu option or the option from the "Page actions" menu, you are redirected to the "#hello" page, but the notification ("We can't screenshot this page.") is not displayed. Tested using the latest Firefox Screenshots v32.1.1 installed from here, on latest Nightly build 62.0a1 (2018-05-09), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

Considering this, I'm going to reopen the issue.

**Comment by testeaxeax** [comment]
@Softvision-CristinaBadescu Screenshots isn't supposed to show an error message, see [here](https://github.com/mozilla-services/screenshots/pull/4342#issuecomment-382458770).

**Comment by Softvision-CristinaBadescu** [comment]
All right. Considering the fact that the error message should not be displayed, I'm going to close the issue. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on latest Screenshots (33.0.0) dev version installed on latest Nightly (62.0a1) build and the issue is no longer reproducible.
Tested on Windows 7 x64, Arch Linux and Mac 10.13.
