### ISSUE TITLE
Inconsistent deletion messaging

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4186]
When deleting an image from the library view, I see this message:

<img width="317" alt="screen shot 2018-03-05 at 1 30 08 pm" src="https://user-images.githubusercontent.com/473531/36992571-572ba3f6-2079-11e8-90e1-f22401579273.png">

When deleting from the image view, the message is:

<img width="532" alt="screen shot 2018-03-05 at 1 30 24 pm" src="https://user-images.githubusercontent.com/473531/36992589-600b57aa-2079-11e8-98c6-eb938b7f3427.png">

Let's pick one and use it for both areas. I feel like the latter offers more clarity, so let's use that.

**Comment by johngruen** [comment]
Let's go with the second one.

**Comment by johngruen** [comment]
Hey @sevaan could we make a custom message UI for both cases?

**Comment by sevaan** [comment]
Custom Deletion UI:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/473531/37718569-5fa1c858-2cf9-11e8-9707-f1f30944cbbd.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/473531/37718556-57bde752-2cf9-11e8-8604-e74886d9a917.png">

[Measurements found here](https://sevaan.github.io/fxscreenshots/menus/#artboard0) Also in this link, measurements for updated Share panel.
