### ISSUE TITLE
Use precision select cursor in Screenshots instead of regular arrow

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4187]
I've seen a few issues about using specific cursors for various edit functions (e.g. a crop cursor when cropping) but can't seem to find an issue about what overall cursor to use, so apologies if this is a repeat.

<img width="54" alt="screen shot 2018-03-05 at 1 46 17 pm" src="https://user-images.githubusercontent.com/473531/36993345-995aeb36-207b-11e8-8008-ab557c1584c7.png">

Right now Screenshots uses a regular arrow cursor...I think we should switch this to a precision select cursor as the state of the page has changed and the cursor should reflect that the user is no longer in a normal browsing mode. It also allows users to make more precise selection boxes if drawing their own.

**Comment by punamdahiya** [comment]
@sevaan Quick clarification on the requirement here, should the crosshair cursor replaces arrow, when the user clicks edit pencil icon or it's should change only when the user enters edit screen and moves cursor over canvas with screenshot image. Thanks

**Comment by sevaan** [comment]
If a user goes hovers over over a button (e.g. Save), we use the hand cursor.
