### ISSUE TITLE
Allow full-resolution full page copy/download?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4190]
Is there any reason we don't allow full-resolution (high DPI) downloads or copies of full page shots? 

IIRC we shrink them when uploading to account for the server upload limits, but I'm not sure we need to keep that restriction when saving or copying locally.

Related to #4174

**Comment by wresuolc** [comment]
Some of this is related to the performance of the tool itself.

**Comment by ianb** [comment]
I believe we implemented this.
