### ISSUE TITLE
[Enhancement][Annotations] Drawing should not be performed on the image area that is not in view

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4192]
[Affected versions]:
- Nightly 60.0a1
- Screenshots v31.2.0 stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v31.2.0 stage installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a long saved shot link.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to the long saved shot link.
2. Click the "Edit this image" button and scroll down the page.
3. Start drawing up through the top part of the window and move the cursor out of it.
4. Scroll up and observe the image.

[Expected result]:
- Nothing is drawn on the image area that was not in view.

[Actual result]:
- The drawn was performed on the image area that was not in view.

[Notes]:
- This issue is also reproducible for the "Crop" tool.
- Here is a screen recording with the issue:
![ss - enhancement - not in view area](https://user-images.githubusercontent.com/31244235/37036821-705add70-2159-11e8-9944-97adef49d6f3.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
