### ISSUE TITLE
Format date of title/name to YYYY-MM-DD

### ISSUE THREAD

**Issue by KopfKrieg** [mozilla-services/screenshots#4197]
I'm not sure, but I think it's [this line of code responsible](https://github.com/mozilla-services/screenshots/blob/4e093dd8caaf241463b0b8a222fca2f47cd16602/shared/shot.js#L377) for it:

```
let clipFilename = `Screenshot-${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()} ${filenameTitle}`;
```

Currently, the date in a screenshot's name is not following an ISO Standard. This is confusing, e.g. screenshots saved today will have the title "Screenshot-2018-3-7 whatever.png". I'd like to have a consistent scheme, e.g. "Screenshot-2018-03-07 whatever.png" (this should be [ISO 8601](https://xkcd.com/1179/)).

The only easy way of doing this in JavaScript might be this piece of code (date formatting in JavaScript is … confusing. There's not really an easy way to do this, right?):

```
var today = new Date();
today.toISOString().substring(0, 10);
```

I can't test that (don't want to set everything up), but maybe someone could make a PR using this?

Edit: Sorry, toISOString() won't work properly because of GMT?! Any other solution?

**Comment by 6a68** [comment]
@KopfKrieg Thanks for filing this bug! You make a good point, but we may not have a chance to get to this very soon. Pull requests welcome, see the README for setup instructions :-)

Also, as to your question here:

> Edit: Sorry, toISOString() won't work properly because of GMT?! Any other solution?

you can use [`getTimezoneOffset()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset), although it annoyingly returns the offset in minutes. I think this might work:

`offsetDate = new Date(today.getTime() - today.getTimezoneOffset() * 60 * 1000).toISOString()`
