### ISSUE TITLE
[Annotations] It is unclear which tool is active on start

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4202]
This just doesn't scream to me: I am in drawing mode

<img width="238" alt="image" src="https://user-images.githubusercontent.com/44390/37117510-1150f6c0-2217-11e8-80aa-80f63bc035ad.png">

**Comment by johngruen** [comment]
...or does it

**Comment by punamdahiya** [comment]
Needs feedback on desired experience to best resolve this issue.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
