### ISSUE TITLE
The string in the title attribute in the edit button is not localised

### ISSUE THREAD

**Issue by cecilebertin** [mozilla-services/screenshots#4206]
The string for the title attribute from the edit button is not translated.
<img width="144" alt="capture d ecran 2018-03-08 a 17 29 28" src="https://user-images.githubusercontent.com/21285660/37185824-29df2a14-22f7-11e8-98ca-7a0be888bcd5.png">

**Comment by SoftVision-CosminMuntean** [comment]
It seems that also the tooltip for the "Color Picker" button and for the color buttons is not localized.

Here is a screens recording with the issue:
![color picker tooltip](https://user-images.githubusercontent.com/19226534/37283246-f2eb9b12-25ff-11e8-9881-11ed317342fb.gif)

**Comment by flodolo** [comment]
Hardcoded `Edit this image` was introduced in #4141. Color Picker in #3880
