### ISSUE TITLE
Allow fullpage screenshotting for documents with inline scrollable elements (eg PDF.js)

### ISSUE THREAD

**Issue by Totogro** [mozilla-services/screenshots#4207]
When seeing a pdf in the built-in pdf.js viewer, I used the screenshots utility in "full page mode" to get a jpg image of this pdf. But seemingly due to the fact that pdf.js cropped the pdf document to fit the screen, the webpage document shows only a cropped version of the pdf document.
Although this is technically understandable, the expected behaviour is to get the full page of the pdf document. I would even say that the pdf.js toolbar is not wanted in the screenshot, as it is used as a part of the browser.
Here also, even if technically it it is understandable, the user is most of the time not interested in the pdf.js toolbar itself. If someone is interested in having browser's parts in the screenshot, she would use the OS screenshot tool instead. Using Firefox screenshots tool is to get a screenshot of the document (html or pdf) the browser is showing, and the entirety of it is this screenshot mode is used.

(And thank you for the good work !!)

**Comment by johngruen** [comment]
@Totogro  PDF.js uses a scrollable inline element, which is a more general issue for us.
