### ISSUE TITLE
Make shot editor tools a toolbar on the shot page?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4213]
What if we put the annotation editor toolbar on the main shot page, under the shot page header? We could save users a click and advertise the existence of the editing features.

rough sketch:

![image](https://user-images.githubusercontent.com/96396/37266670-0ff1fd3c-2579-11e8-898e-c43edb3a8dca.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
