### ISSUE TITLE
Make it possible to blur sections of the screenshot before sending it to the Screenshots server

### ISSUE THREAD

**Issue by mikeconley** [mozilla-services/screenshots#4215]
I wanted to screenshot a comment I saw on Facebook, but also wanted to preserve the anonymity of the person making the comment. It would be excellent if our Screenshot tool had the ability to selectively blur[1] sections of the screenshot before sending it to our servers or the clipboard.

[1]: And sufficiently blur - it should not be possible to recover the original pixels after the fact.

**Comment by chenba** [comment]
Related to #4795

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
