### ISSUE TITLE
Firefox Screenshots "Download" button produces a filename with explicit quote character at start and end ('foo.png' with quotes included in the filename)

### ISSUE THREAD

**Issue by dholbert** [mozilla-services/screenshots#4226]
STR:
 1. Take a screenshot, or just use mine:
 https://screenshots.firefox.com/qVugyzqX6aXrQk4c/www.example.org
 2. Click the "Download" button at the top right of the page.
 3. Find the file on your system, and look at its filename.

ACTUAL RESULTS:
The file is literally named `'Screenshot-2018-3-14 Example Domain.png'` **with the single-quote characters included** (and notably, as part of the file extension -- so this is a `.png'` file!)

EXPECTED RESULTS:
No quotes in the filename. Should be named `Screenshot-2018-3-14 Example Domain.png`

I can reproduce this bug in both Firefox and Chrome, so it's not a browser bug - it's a bug with server's choice of filename.

**Comment by 6a68** [comment]
@dholbert What OS (and WM, if linux) are you using? I don't see those characters on Mac.

**Comment by chenba** [comment]
I don't see it on Nightly on Windows 10 either.

**Comment by dholbert** [comment]
I'm on Ubuntu 18.10 (prerelease), with gnome-shell. I'm guessing it affects Linux in general, though I don't know for sure.

**Comment by dholbert** [comment]
(BTW, I only see the characters in a terminal, i.e. if I run `ls ~/Downloads` - they don't show up in my graphical file manager.)

**Comment by chenba** [comment]
I don't see the problem on CentOS 7.

**Comment by dholbert** [comment]
oh, this actually might be a bug in my window manager! I can't reproduce on an Ubuntu 17.10 system.  This just happens to have been my first download after installing Ubuntu 18.04, but maybe all downloads are affected.

Sorry for the noise. I'll investigate a bit more and probably report upstream with Ubuntu and/or Gnome.

**Comment by dholbert** [comment]
(Doesn't affect all downloads -- e.g. this one downloads fine with no quotes: http://cdimage.ubuntu.com/xubuntu/xenial/daily-live/20180313/xenial-desktop-i386.iso.zsync   *shrug*  Anyway, reporting upstream. Thanks for the sanity-check, and sorry again for the distraction.)

**Comment by dholbert** [comment]
Haha, ok, it looks like this is purely a change in the UI of the "ls" command, in Ubuntu 18.04  For filenames that contain spaces, it now displays them with quotes (presumably so that you could copypaste the full filename into some other command and it'd work correctly).

I can reproduce by simply doing:
>$ touch foo\ bar
>$ ls
> 'foo bar'

This threw me a bit, but apparently it's intentional. And wholly unrelated to Firefox Screenshots. :) Sorry again for the noise.
