### ISSUE TITLE
[Annotations] Color Picker Dismissal Click Also Draws

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4228]
#### STR

1. Start editing a shot
1. Click on color picker icon to open the picker
1. Click on outside of the color picker but _on the shot_ to dismiss it

#### Expected

Color picker is closed and nothing else.

#### Actual

Color picker is closed, but a drawing action is also performed on the shot.

**Comment by johngruen** [comment]
eh, idk i tried this and i don't think it matters.
