### ISSUE TITLE
[Annotations] Pencil and Marker icon hard to differentiate

### ISSUE THREAD

**Issue by gerdneuman** [mozilla-services/screenshots#4231]
Using the new annotations tools and like them a lot but half the time I click the Pencil when I mean Marker and vice versa. They both look far too similar regarding their form:

![image](https://user-images.githubusercontent.com/12525563/37455456-68522382-283d-11e8-8101-470500ea4643.png)

The pencil does not look like a (long, small) pencil. Please do some image search here or look at other image tools and their icons.

**Comment by johngruen** [comment]
Agree! I think we can make them a bit more distinct

**Comment by johngruen** [comment]
Related: #4155

**Comment by sevaan** [comment]
The pen icon in the Sketch file does not have that horizontal line across it which it differentiates it a bit more from the highlighter:

![image](https://user-images.githubusercontent.com/473531/37783750-a2b15680-2dcc-11e8-9571-40c97014c774.png)

I suggest using that icon instead.
[asset.zip](https://github.com/mozilla-services/screenshots/files/1838404/asset.zip)

**Comment by chenba** [comment]
Closing since the icons have been updated.
