### ISSUE TITLE
[Annotations] Add undo / redo to editor (with usual keyboard shortcuts)

### ISSUE THREAD

**Issue by gerdneuman** [mozilla-services/screenshots#4232]
I find myself always typing `Ctrl+Z` to `clear` (which seems to clear everything not just the last edit as I would expect from the icon).

Right most icon in:
![image](https://user-images.githubusercontent.com/12525563/37455663-e1f065d2-283d-11e8-995e-bd2d2fe73843.png)

**Comment by wresuolc** [comment]
It would probably be confusing to have ctrl-z reset everything, but adding an undo/redo stack would be interesting.  Thanks for filing this.

**Comment by PwrSrg** [comment]
+1  Need this asap.  I screwed up after about 10min and couldn't undo it.  Had to start all over again from scratch.

**Comment by chenba** [comment]
This mostly fixed by #4370 and #4371.  But there are no keyboard shortcuts at this time.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
