### ISSUE TITLE
[Annotations] Use yellow or red as default annotations color (not black)

### ISSUE THREAD

**Issue by gerdneuman** [mozilla-services/screenshots#4233]
Black is a pretty bad default for an annotations color:

Second from right icon:
![image](https://user-images.githubusercontent.com/12525563/37455707-01772990-283e-11e8-8d6c-ec34c3cfb3b0.png)

Yellow (or red) would be much better and I personally always need to change as a first step. Also `<mark>` tag uses yellow by default in all browsers, so yellow would make perfect sense.

Anybody seen a text marker with black color in real live? (I know for pencils ok, but still if you want to annotate you usually want to use a color that is different than what you captured).

**Comment by wresuolc** [comment]
Let's use blue

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
