### ISSUE TITLE
Screenshots are blank images

### ISSUE THREAD

**Issue by sha-265** [mozilla-services/screenshots#4237]
When ever I'm trying to take a screenshot (FF 58-59.01 64 bit, Win 7), I get blank image when saving (either locally or remotely) or copying the image to clipboard. Example:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4103710/37556625-afdcc7b6-29f0-11e8-9578-6c11794bb0c6.gif)

**Comment by SoftVision-CosminMuntean** [comment]
@sha-265 thanks for reporting this!

Can you please check in "about:config" page if you have the "privacy.resistFingerprinting" Boolean pref set to "true"? 
I have managed to reproduce this issue only if I set the pref to "true". If you change it to "false" screenshots works as expected.

**Comment by m-j-r** [comment]
@SoftVision-CosminMuntean I have the exact same issue as @sha-265, and changing the pref in about:config stopped the blank screenshots... fyi also impacts _all_ screenshotting tools, including snipping tool, and onenote clipper extension

**Comment by ianb** [comment]
It doesn't seem like we'll be able to fix this in Screenshots. [Bug 1412961](https://bugzilla.mozilla.org/show_bug.cgi?id=1412961) ("privacy.resistFingerprinting breaks extensions that use extension-based canvas APIs (like Screenshots)") is about this issue in Firefox generally
