### ISSUE TITLE
Update share panel to match styling of deletion UI

### ISSUE THREAD

**Issue by sevaan** [mozilla-services/screenshots#4249]
New deletion UI can be found in #4186. The share panel will need to be updated to match this style.

Old Share UI:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/473531/37719026-74fded66-2cfa-11e8-839e-b4a128d97802.png">

New Share UI:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/473531/37719305-16b9e128-2cfb-11e8-82d5-4e86daea4943.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/473531/37719316-1eb2b670-2cfb-11e8-95ee-bc08130e99ec.png">

Changes: Apart from styling, have put the icons on the bottom, and changed the order to email first.

[Measurements can be found here.](https://sevaan.github.io/fxscreenshots/menus/#artboard1)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
