### ISSUE TITLE
Screenshots icon from the Page Actions menu is no longer displayed on the latest Nightly

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#4252]
Cloned from https://bugzilla.mozilla.org/show_bug.cgi?id=1447943

[Regression]:
- This issue is not reproducible with latest Firefox 58.0.0, Beta or yesterday's Nightly. Considering this I have performed a regression in order to find which bug introduced this. Here are the results:

Last good revision: 1aeb1fc7be3371280a5d6f93394d6df0d8db0ad2
First bad revision: 563f8e0d9d2dbf0eec8cb3f4afa0272f873e52ff
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=1aeb1fc7be3371280a5d6f93394d6df0d8db0ad2&tochange=563f8e0d9d2dbf0eec8cb3f4afa0272f873e52ff

Looks like Bug 1446250 introduce this issue. 

[Affected versions]:
- Nightly 61.0a1
- Screenshots 31.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean new Firefox profile.

[Steps to reproduce]:
1. Start the browser with the prerequisites from prerequisites.
2. Click the "..." page actions menu.
3. Observe the "Take a screenshot" option. 

[Expected result]:
- An icon is displayed in front of the string.

[Actual results]:
- No icon is displayed.

[Notes]:
- I wasn't able to reproduce this issue on a MacBook Pro retina display laptop, however I was able to reproduce it on an older iMac.
- Attached a screen shot with the issue:
![no icon for screenshots](https://user-images.githubusercontent.com/18304511/37767153-c116ed7e-2dd1-11e8-82fb-3b3b3943738b.png)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on the latest Nightly (61.a1, Build ID: 20180402111808) build. Tested on Windows 7 x64, Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
