### ISSUE TITLE
[Annotations] Clicking on Color Picker Button No Longer Dismisses The Color Picker Panel

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4262]
#### STR

1. Start an edit
1. Click on the Color Picker button to open the panel
1. Click on the Color Picker button again

#### Expected

The color picker panel is closed

#### Actual

The color picker panel closes and immediately opens back up ("flashes")

This is a regression introduced by the patch for #4124

**Comment by niharikak101** [comment]
has PR: #4267
