### ISSUE TITLE
"Clipboard copy failed" error is displayed after saving a shot on Simply Recipes pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4269]
[Notes]:
- It seems that the saved shot link fails to be copied to the clipboard.
- However, the "Copy Image" functionality is working as expected.

[Affected versions]:
- Nightly 60.0a1
- Screenshots 31.3.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to https://www.simplyrecipes.com/recipes/minestrone_soup/.
2. Save a shot on the page.
3. Observe the behavior.

[Expected result]:
- The shot is successfully saved without any errors. 

[Actual results]:
- The shot is saved, but a "Clipboard copy failed" error is displayed and the link is not copied to the clipboard.

[Additional Notes]:
- Here is a screen shot with browser console errors:
![clipboard copy failed](https://user-images.githubusercontent.com/19226534/37907823-e779a048-310e-11e8-8bda-151da0c53b26.png)

- Here is a screen recording with the issue:
![clipboard copy failed 1](https://user-images.githubusercontent.com/19226534/37908145-f37d77ce-310f-11e8-899c-a7064d44db40.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I just found another website where the issue is reproducible:
http://www.newsweek.com/man-wins-gender-discrimination-lawsuit-after-woman-gets-promotion-he-wanted-853795

**Comment by chenba** [comment]
I get the success notification but the link was not copied.  (Windows 10 and Linux)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible using the latest Screenshots 31.3.0 dev version install from here: https://screenshots.dev.mozaws.net/homepage/install-test-local.html.

Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

**Comment by chenba** [comment]
I suspect this is caused by a build failure, so the addon you tested with does not actually have the fix.  I've filed #4333 to fix the CircleCI 2 builds.  Once that's merged, we should re-verify this.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks @chenba !
I have retested this issue using latest Screenshots 13.3.3 dev version after #4333 was merged and the issue is no longer reproducible.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
