### ISSUE TITLE
Server Should Not Allow " " Titles

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4273]
The server is allowing " "  to be saved as the shot title.  Should it?

**Comment by chenba** [comment]
Client side fix is in #4204

**Comment by wresuolc** [comment]
Let's audit our title saving code to make sure we have an appropriate allowlist

**Comment by chenba** [comment]
Currently we allow `null` and any and all strings.  https://github.com/mozilla-services/screenshots/blob/ad0c68b58bbf3baa19bf68fb3f6e806d1738e5c7/shared/shot.js#L435

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
