### ISSUE TITLE
remove /metrics endpoint

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4278]
The /metrics endpoint has had [11 page views this year](https://analytics.google.com/analytics/web/#/report/content-pages/a49796218w101460360p136052688/_u.date00=20180101&_u.date01=20180326&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fmetrics~2F/). We report regularly on our metrics via twitter and blog posts, and the metrics endpoint is a lot of code. Let's get rid of it!

**Comment by wresuolc** [comment]
Let's clean up what isn't interesting
