### ISSUE TITLE
React Developer Tools not showing for screenshots.firefox.com

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4281]
Opening bug to investigate, react developer tools not showing for screenshots website.

After installing react developer tools (https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
a) Screenshots website shows message, "This page doesn’t appear to be using React. If this seems wrong, follow the troubleshooting instructions," and no highlighted icon.
b) the react tab does not show in the developer tools.

Expected
When visiting sites built with react e.g. mozilla.slack.com react developer tool should be highlighted in toolbar and accessible from developer tools (cmd + option + i)

**Comment by ianb** [comment]
I'm not convinced that it should display on the live site. But it *should* show up on `http://localhost:10080` (does it?)

**Comment by punamdahiya** [comment]
No, unfortunately not, it doesn't show for http://localhost:10080 either

**Comment by chenba** [comment]
Our CSP is blocking it.

**Comment by punamdahiya** [comment]
I see, found this https://github.com/facebook/react-devtools/issues/460 could be related

**Comment by chenba** [comment]
Ah, then it's not _our_ CSP, just any CSP.  :no_mouth:

**Comment by punamdahiya** [comment]
Yeah, validated unsetting CSP here https://github.com/mozilla-services/screenshots/blob/master/server/src/server.js#L1131 allows debugging using react developer tools

May be we should allow in development on http://localhost:10080 until we have fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by punamdahiya** [comment]
allow ~ unset CSP

**Comment by chenba** [comment]
We should add a config to stop sending the CSP header altogether (at least until the bug in Firefox is fixed).

If `NODE_ENV` is "dev" and the new config is set to true, then the server should not send a CSP header.
