### ISSUE TITLE
[FxA] "Sign In", "Disconnect" and "Close" buttons don't have tooltips

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4292]
[Affected versions]:
- Nightly 61.0a1
- Screenshots 31.3.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 31.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profiles from prerequisites.
2. Navigate to Screenshots Settings page (https://screenshots.dev.mozaws.net/settings).
3. Hover the "Sing In" button and observe the behavior.
3. Sign in with a valid account, hover the "Disconnect" button and observe the behavior.
4. Hover the "X" button from the top right corner of the page and observe the behavior.

[Expected result]:
- The buttons have a specific tooltip when are hovered.

[Actual results]:
- The buttons don't have any tooltipls.

[Additional Notes]:
- Here is a screen recording with the issue:
![fxa buttons tooltip](https://user-images.githubusercontent.com/19226534/38140549-e216c244-343c-11e8-990a-26fd27b34681.gif)

**Comment by wresuolc** [comment]
Tooltips should be the same as the visible labels

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on the latest Screenshots 31.3.3 dev version. The mentioned buttons have a specific tooltip when are hovered.
Tested on Windows 7 x64, Mac 10.13 and Arch linux.
