### ISSUE TITLE
[Annotations][Enhancement] Text, Arrows, Circle and Square

### ISSUE THREAD

**Issue by PwrSrg** [mozilla-services/screenshots#4295]
Please add the four other basic annotation elements - Text, Arrows, Circle and Square.  =) #

**Comment by clouserw** [comment]
Thanks for the comment.  Text has been shipped and is available today.  Circles are #4368, Squares are #4372, and I filed #4756 for arrows so we can keep organized with one tool per issue.  Thanks.
