### ISSUE TITLE
Chrome prototype: get browser-polyfill.js via build tools

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4304]
Two tasks here:

1. Make sure outstanding issues with the browser-polyfill are resolved in that repo's master. Currently I believe https://github.com/mozilla/webextension-polyfill/pull/97 is the one we need to land.

2. Add something to the build tools to fetch the browser-polyfill, build it, and add it to the Chrome build folder.

Refs #3998

**Comment by 6a68** [comment]
Just heard from @rpl today that he's working with @rob--w to finish up the PR. We can check on the PR in another week or two.

In the meantime, it would be good to update the polyfill to the latest version in the PR, as it might behave differently in some failure cases.

**Comment by 6a68** [comment]
The upstream PR is still not merged. Probably need to kick this to next sprint.

**Comment by 6a68** [comment]
The upstream PR has landed, but a new version hasn't been released yet. Filed https://github.com/mozilla/webextension-polyfill/issues/150 to ask for a patch release.

**Comment by ianb** [comment]
I don't think we're going to launch on Chrome
