### ISSUE TITLE
Onboarding Displayed to Users When They Update Firefox

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4305]
Asa mentioned on the Screenshots Slack channel that 

> I'm being repeatedly prompted to go through the onboarding for screenshots each day I update.

**Comment by chenba** [comment]
I have not noticed that issue on Windows or Linux.  @SoftVision-CosminMuntean is this something you can reproduce?

**Comment by 6a68** [comment]
I've noticed this periodically on dev edition and nightly. @chenba didn't you just land a bug fix that ensures we don't display onboarding before the `storage.local` call has returned? I wonder if this should be fixed as of our next export.

**Comment by 6a68** [comment]
Hmm, I wonder if he did. I'll ask in slack

**Comment by wresuolc** [comment]
When you ask, please ask if he's going back and forth between versions.  We don't see this just upgrading nightly, for example.

**Comment by johngruen** [comment]
We think we can get a fix for this into 61 @ianb will investigate tagging soon.

**Comment by chenba** [comment]
I'm closing this.  We can open a new issue if the bug resurfaces.
