### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by LChitab** [mozilla-services/screenshots#4306]
Where are the screenshots kept?
I am a student (on line course) and have to listen to a lot of webinars, do lots of research, save tons of information for my own self study.  I just LOVE SCREENSHOTS as I can take a shot of the webinar screen  and not worry about missing out any of the information being shown. 

I use Screenshots like maybe 200  times a day...easy.   I screenshot everything I read, I screenshot more than I bookmarked.   GREAT GREAT IDEA by the way.  Thank you for offering it freely.
Now my question is:  I would do a screenshots and would give it a name and save for Unlimited time and download it as well as save the shot to Evernote.  
I had about 30+ pages of screenshots that I was keeping....it was handy, available instantly when I was searching for info on the internet and comparing the data collected.  
I did a Firefox Refresh.... and now all those shots are gone.   Is there a way to bring it back?  Are they saved somewhere beside the Download to my computer or Evernote.   I would rather have a folder on Firefox itself where I can either bring them back so they are right there for me... a click away.  Is that possible?  Thank you.

**Comment by ianb** [comment]
Oh no! I'm sorry this happened.

The shots all still exist, but your browser credentials were reset when you did the Firefox Refresh.

It is possible to retrieve the screenshots one-by-one by looking in your history and finding the URLs of each screenshot. Each screenshots will load fine, even if the site doesn't recognize you as the owner.

If that doesn't seem to work drop me an email, ibicking at mozilla.com.

**Comment by ianb** [comment]
We're in contact through email, so we won't need to keep discussing through GitHub
