### ISSUE TITLE
[Annotations] The old pen icon is wrongly displayed for the "Pen" cursor

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4312]
[Affected versions]:
- Nightly 61.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with Firefox Screenshots v31.3.1dev installed.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Hover the image and observe the mouse cursor.

[Expected result]:
- The new "Pen" cursor is displayed.

[Actual result]:
- The old "Pen" cursor is displayed.

[Notes]:
- Here is a screen recording with this issue:
![ss - old pen cursor](https://user-images.githubusercontent.com/31244235/38376676-cd7f976a-3901-11e8-9d15-159b1f52f322.gif)

**Comment by niharikak101** [comment]
@johngruen this would need a new angled icon

**Comment by punamdahiya** [comment]
@sevaan fix here needs a new icon and need your help to get one. Thanks

**Comment by punamdahiya** [comment]
Current Pen tool is using https://github.com/mozilla-services/screenshots/blob/master/static/img/cursor-pen.png

**Comment by youwenliang** [comment]
@clouserw Which one is the expected icon? Is the one Sevaan commented above the right one?

**Comment by punamdahiya** [comment]
Removing @johngruen as assignee as we have the asset to update pen icon attached above https://github.com/mozilla-services/screenshots/issues/4312#issuecomment-412596217

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
