### ISSUE TITLE
firefox screenshot limit

### ISSUE THREAD

**Issue by kanink007** [mozilla-services/screenshots#4319]
hello.
the firefox screenshot tool is very useful. but unfortunately the 10.000px limit is annoying.  i never can save website because they have more than 10.000 pixels. why is there even a limit?
i mean, its my computer which neds to work, which needs to have enough RAM etc to be able to download a big screenshot. so why not lt my computer decide? 
if its possible, please remove all screenshot limits.

**Comment by johngruen** [comment]
You can download up to 32K pixels...we limit uploads of more than 10K because of file size limitations
