### ISSUE TITLE
Allow screenshots to be organized into directories

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4320]
Source: https://discourse.mozilla.org/t/huge-help-if/27471

A huge help would be to have folders available in which to put our screen shots so that we could find
our shots more easily.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
