### ISSUE TITLE
Upgrade fluent and fluent-react

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4323]
This is a follow-up to #4280.  Upgrading these modules cause runtime errors.  Code changes are most likely necessary.

**Comment by wresuolc** [comment]
Moving into stretch until the fix above is done

**Comment by chenba** [comment]
Fluent 0.8.0 has this workaround: https://github.com/projectfluent/fluent.js/wiki/React-Overlays#custom-markup-parsers

**Comment by chenba** [comment]
Fixed in #4935
