### ISSUE TITLE
Upgrade query-string

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4325]
This is a follow-up to #4280.  Upgrading `query-string` from 5.0.0 to 6.0.0 causes the uglifying build step to fail (!?).  We need to investigate why if we want to upgrade the module.

**Comment by chenba** [comment]
query-string 6.0.0 targets Node.js 6 or later, and the code was updated to use features from ES2015.  Since uglify-js only support ES5, this upgrade would cause our bundling build script to fail.  A solution is to babelify when we browserify.  However, query-string 6.0.0 does not contain new features or fixes, so there is no urgent need to upgrade.

**Comment by famoraes** [comment]
Yeah, you guys right. Gonna downgrade it. The issue I've found is https://github.com/mozilla-services/screenshots/issues/4325.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
