### ISSUE TITLE
Support encrypted uploads

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#4328]
Using both Send and Screenshots, I wanted to ask, if you have considered reusing the encryption from Send for Screenshots. For me it would be very nice to have an option to upload the screenshot client-side encrypted and have the link contain all the necessary information for the visitor to decrypt it.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).

**Comment by ianb** [comment]
We might revisit this someday if we support uploading to https://send.firefox.com

**Comment by MaxLeiter** [comment]
Came here looking for something regarding support for Firefox send. Is it worth its own issue?
