### ISSUE TITLE
Make sure it's easy for designers to run the add-on locally and point it at different envs

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4334]

**Comment by ianb** [comment]
We should review these instructions and make sure they work: https://screenshots.dev.mozaws.net/homepage/install-test-local.html

If we want to help someone start from scratch, I guess they might need [the basic instructions](http://blog.teamtreehouse.com/install-node-js-npm-mac), or we just expand the [README install instructions](https://github.com/mozilla-services/screenshots#installation-and-setup). But maybe that first link is really just what we should be pushing people to do.

**Comment by chenba** [comment]
I expanded the README a little bit.  But I think the existing "If you want to develop the add-on but not the server" part pretty much covers this.
