### ISSUE TITLE
The "Screnshots" button from the "Library" menu no longer works

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4338]
[Affected versions]:
- Nightly 61.0a1
- Screenshots 31.3.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 31.3.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Click the "Library" button from the browser toolbar.
3. Click the "Screenshots" button and observe the behaviour. 

[Expected result]:
- You are redirected to the "My Shots" page.

[Actual results]:
- Nothing happens.

[Notes]:
- The issue is not reproducible using Screenshots 31.1 production version from latest Nightly.
- Here are the errors displayed in browser console:
![screenshots button from library](https://user-images.githubusercontent.com/19226534/38734587-d5b26074-3f2e-11e8-883f-68abee374ed0.png)

- Here is a screen recording with the issue:
![screenshots button from library](https://user-images.githubusercontent.com/19226534/38734594-d8b96312-3f2e-11e8-9ad4-55c1c6a54388.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots v32.0.0dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 61.0a1 (2018-04-17) on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12. The "Screenshots" button from the "Library" menu redirects you to the "My Shots" page.
