### ISSUE TITLE
Screenshots overlay is wrongly moved in background at first click when a selection is performed on latest Nightly

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4339]
It seems that this is a Nightly regression. I have also logged this issue in Bugzilla:
**https://bugzilla.mozilla.org/show_bug.cgi?id=1453942**

[Affected versions]:
- Nightly 61.0a1
- Screenshots 31.3.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Open the Firefox browser and navigate to "https://www.wikipedia.org/".
2. Click the "Take a Screenshots" button from "Page Actions" menu.
3. Click and hold it to the page without moving the mouse.
4. Observe the Screenshots overlay.

[Expected result]:
- The Screenshtos overlay is correctly displayed.

[Actual results]:
- The Screenshtos overlay is moved in background./

[Regression]:
- It seems that this is a Nightly regression. Using mozregression tools I have found a regression window. Here are the results:
Last good revision: 6415ccbf739f36f71548540bd92c3b86ab9e1529
First bad revision: d112cf7b2b60e6244099dc3b599a2444ba0d1da3
Pushlog: https://goo.gl/n3rymW

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/X5ywLJ

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible on latest Nightly 61.0a1 (Build ID: 20180417225505), using Firefox Screenshots (both 30.1.0 and latest Dev Version 32.0.0 installed from here:https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64.
