### ISSUE TITLE
Add new block types

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4347]
Right now we have only `'dmca'` for a block type. I propose we add `usererror` (when a user can't figure out how to delete something) and `abuse` (illegal or something).

This requires a database migration (there's an enum), and we need to be sure that all blocks show up reasonably. We might have DMCA-specific language on the site.

`usererror` and `abuse` can display as though they are simply deleted, IMHO we don't need to inform users about the underlying reasons.

**Comment by ianb** [comment]
Note that we'll follow up in https://github.com/mozilla-services/screenshots-admin/issues/29 to make use of these block types.

**Comment by chenba** [comment]
Closing this now that #4417 is merged.
