### ISSUE TITLE
Use OpenID Connect to dynamically discover FxA endpoints

### ISSUE THREAD

**Issue by rfk** [mozilla-services/screenshots#4351]
Hi!  I got here via https://bugzilla.mozilla.org/show_bug.cgi?id=1455711 and was taking a quick look at the FxA OAuth integration in this repo.  It looks good 😀!  A couple of small things I noticed:

1) You request both the "profile" scope and a bunch of more specific sub-scopes here:

 https://github.com/mozilla-services/screenshots/blob/99b73775816cb39c3d422a0ae516410bbf53a220/server/src/server.js#L1081

This is redundant, the "profile" scope implies all of "profile:displayName", "profile:email", etc.

2) If you want to avoid having to configure multiple server URLs here:

  https://github.com/mozilla-services/screenshots/blob/99b73775816cb39c3d422a0ae516410bbf53a220/server/src/config.js#L74

FxA supports [OpenID Connect discovery](https://auth0.com/docs/protocols/oidc/openid-connect-discovery), and you can look up all these endpoints in a single place via https://accounts.firefox.com/.well-known/openid-configuration or equivalent well-known URLs in dev and stage.

**Comment by 6a68** [comment]
Updating title & moving out to stretch, as the remaining FxA OAuth nit isn't critical for initial release

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
