### ISSUE TITLE
copy to clipboard notification on windows sticks around way too long

### ISSUE THREAD

**Issue by asadotzler** [mozilla-services/screenshots#4358]
When I copy a screenshot to clipboard using the button in the screenshot tool, I get a notification that the screenshot was copied to the clipboard. This is nice. The notification sticks around for about 18 seconds. This is not nice. It should stick around for maybe 5 seconds or something like that.

**Comment by 6a68** [comment]
I talked with #teamaddons about this a bit. Different OSes can delay showing the notification by an unknown period of time, so the right way to implement this is: (1) set up on onShown listener, then (2) set a 2-second timeout (or whatever) inside that listener, (3) then call `notifications.clear()`. Note `clear` needs the notification ID, which is returned by `notifications.create()`.

**Comment by 6a68** [comment]
Semi-related, I filed an upstream bug to add a `hideAfter` option when creating a notification, so that extension authors don't have to work so hard to show the user ephemeral notices.

**Comment by wresuolc** [comment]
Thanks for filing this.  We're using the system APIs to handle notifications so the OS controls how long notifications are shown.  (maybe it's adjustable in the OS?)
