### ISSUE TITLE
Screenshots no longer works on PDF pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4363]
It seems that this is a Nightly regression and I have also logged the issue in Bugzilla: **https://bugzilla.mozilla.org/show_bug.cgi?id=1456485**

[Regression]:
- The issue is not reproducible on latest Firefox 59.0.2 release. Considering this I have found the regression window using the mozregression tools. Here are the results:

Last good revision: c8514e653b71479ba22a307f58f79f563ed80e9d
First bad revision: 07ab807639ee42a407a9bdb0d374206c0f17678d
Pushlog: https://goo.gl/aLWFGg

Looks like [Bug 1436482](https://bugzilla.mozilla.org/show_bug.cgi?id=1436482) introduced this issue, but I am not sure if this should be fixed on the Screenshots or Nightly side.

[Affected versions]:
- Nightly 61.0a1 (Build ID: 20180424013604)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile.
- Screenshots onboarding tour was already visited.

[Steps to reproduce]:
1. Open the latest Nightly build with the profile from prerequisites.
2. Navigate to a PDF page (eg: http://www.pdf995.com/samples/pdf.pdf).
3. Click the "Take a Screenshot" button from "Page Actions" menu.
4. Observe the behavior. 

[Expected result]:
- The Screenshots overlay is displayed and you can make a selection.

[Actual results]:
- "We can't screenshot this page" error is displayed. 

[Notes]:
- Here is a screenshots with browser console errors:
![pdf browser console errors](https://user-images.githubusercontent.com/19226534/39190998-83f8ec22-47de-11e8-9546-719135d3bb6b.png)

- Here is a screen recording with the issue:
![pdf pages](https://user-images.githubusercontent.com/19226534/39191005-8aa8eb62-47de-11e8-8e6a-a56448865a2e.gif)

**Comment by wresuolc** [comment]
This bug is closed!

**Comment by SoftVision-CosminMuntean** [comment]
I can reproduce this issue if I install Screenshots dev or stage version from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html).

@chenba, @6a68, @ianb the issue is reproducible because the add-on is not signed? Or we have another issue here?

**Comment by chenba** [comment]
It is because the `resource://pdf.js/` permission is not in the manifest.  I'll file an issue to add that along with `about:reader*`.

**Comment by 6a68** [comment]
I think this has been fixed upstream; it was mentioned in the firefox dev meeting: https://wiki.mozilla.org/Firefox/Meeting/03-Jul-2018#Add-ons_.2F_Web_Extensions
