### ISSUE TITLE
Add metadata for image previews on social websites

### ISSUE THREAD

**Issue by autonome** [mozilla-services/screenshots#4364]
Currently, screenshot links shared on social sites just have a long terrible URL, eg:

https://twitter.com/mike_conley/status/988838930069049345

It would be FAR nicer for an image preview to show, instead of just the long URL.

The metadata for doing this is not terribly complicated.

I wrote a tool for templating the metadata for the major sites that do it: https://hacks.mozilla.org/2016/09/vaulting-out-of-walled-gardens-with-fancy-links/

**Comment by wresuolc** [comment]
@autonome it looks like Mike linked to the actual image itself.  I think you're talking about adding headers to the page which wouldn't help in this case.  Are we misunderstanding?  Seems like this is something weird on twitter's end

**Comment by wresuolc** [comment]
I think we're doing everything correctly here.  @autonome please reopen if we can do more

**Comment by autonome** [comment]
👍👍👍
