### ISSUE TITLE
[annotations] Add a Circle tool

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4368]
Add an option to draw a circle

Specs: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Advanced_Annotations/

Assets: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
