### ISSUE TITLE
[annotations] Add an Undo tool

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4370]
Add an option to undo the last edits

Specs: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Advanced_Annotations/

Assets: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations

**Comment by chenba** [comment]
@johngruen (or @sevaan ?) should https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations/annotation-undo.svg be the undo icon only and not the whole toolbar?  https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations/annotation-redo.svg is just the redo icon.

**Comment by chenba** [comment]
I can apply a transform to the redo icon to get an undo icon though.  🤷‍♂️
