### ISSUE TITLE
[annotations] Add a Stroke option

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4374]
The specs below show some tools being affected by a Stroke dropdown box (eg. the width of the pencil).  We should add a stroke option and have it affect all the relevant tools (pencil, highlighter, circle, square, and any others we have implemented at the time)

Specs: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Advanced_Annotations/

Assets: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
