### ISSUE TITLE
Make context-menu-icon optional

### ISSUE THREAD

**Issue by metasieben** [mozilla-services/screenshots#4375]
In #4264 the icon was enabled on the context-menu, would it be possible to make displaying it optional?

While I understand the reasoning in #3858 for requesting the addition, on macOS the icon is displayed on the same line with the other text entries, making it look rather weird.

**Comment by 6a68** [comment]
Thanks for filing this bug! The behavior you noticed is actually upstream code in Firefox's WebExtension implementation, so I duped this to a bugzilla bug for you.

If you'd like to track further discussion, you can CC yourself on https://bugzilla.mozilla.org/show_bug.cgi?id=1457937.

Closing this in favor of the BMO bug.
