### ISSUE TITLE
Investigate renovate

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4391]
Activity Stream is looking at [renovate](https://github.com/apps/renovate) for keeping dependencies up to date. It's supposed to be less annoying than Greenkeeper. Maybe we would like to use it?

**Comment by wresuolc** [comment]
I installed renovate.  It's supposed to open a PR to configure, but I haven't seen one yet.  Giving it some time...

**Comment by wresuolc** [comment]
This is done!
