### ISSUE TITLE
Selenium failure: "Error: Timeout of 120000ms exceeded"

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4400]
Seeing this error on the [latest build](https://circleci.com/gh/mozilla-services/screenshots/6458), and I think I've seen it before:

>   1) Test Screenshots
       should take a shot:
Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by wresuolc** [comment]
@jrbenny35 do you have ideas for reliability of this test?  This seems to fail intermittently

**Comment by ianb** [comment]
For context, our test is here: https://github.com/mozilla-services/screenshots/blob/master/test/test.js

I believe the intermittent failures are typically happening in the add-on setup code.

**Comment by chenba** [comment]
Specifically it's https://github.com/mozilla-services/screenshots/blob/master/test/test.js#L270 that occasionally fail.  When it does, neither the onboarding nor the shot selection UI shows up.  It just hangs until the 120000ms timeout is reached.

**Comment by 6a68** [comment]
To explicitly set a timeout for finding a specific element, I think we just need to pass a second time argument to driver.wait, with the time in milliseconds.

**Comment by chenba** [comment]
Kind of a duplicate of  #4287

**Comment by chenba** [comment]
The test is experiencing #3105 when it fails.  `makeEl` is called to make `<img>` for the preview image when it happens.

**Comment by chenba** [comment]
#3105 is caused by a race condition.  (Something that users most likely won't encounter unless they click at automated testing speed.)  Let's close this issue?

**Comment by chenba** [comment]
I don't know if it is a clue, but when the test is stuck waiting for onboarding, the screenshot page action icon is missing (there's an empty space in its place).

**Comment by chenba** [comment]
There's no consistent error in the browser console when this happens.  And enabling trace logs slow things down enough that whatever race condition(?) that's causing the issue does not appear.

**Comment by 6a68** [comment]
I think we're fine to close this bug.

Looking at the 120 most recent builds of the master branch on CI, I see 7 failures, 4 of which are due to this bug. That's about a 3% error rate, which is really good for Selenium.
