### ISSUE TITLE
The "Share" button disappears from the "My Shots" page if the browser is horizontally resized less than half

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4404]
[Affected versions]:
- Firefox 63.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have multiple saved shots on a new Firefox profile.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and to "My Shots" page.
2. Horizontally resize the browser less than half.
3. Hover a shot and observe the bottom part of it.

[Expected result]:
- All the buttons are correctly displayed.

[Actual results]:
- The "Share" button is no longer displayed.

[Notes]:
- Here is a screen recording with the issue:
![share button not displayed1](https://user-images.githubusercontent.com/19226534/39812812-cbe5bec0-5396-11e8-8be6-7343f1427b68.gif)

**Comment by wresuolc** [comment]
what

**Comment by punamdahiya** [comment]
This is fallout of fix done as part of https://github.com/mozilla-services/screenshots/issues/3589
@ianb @chenba you must be having more context on this. To fix this bug few options to consider
a) Remove media query fix and move check in JS to show and hide share button
b) Depending on which one is our major user group change width e.g. may be consider max-width as 480px to handle only mobile

**Comment by chenba** [comment]
@punamdahiya nice detective work.  Do you mean checking the user agent by "move check in JS"?

**Comment by punamdahiya** [comment]
@chenba that's correct, assigning myself to look into the fix

**Comment by wresuolc** [comment]
We expect this to change with the major redesign coming (with more buttons).  Closing this for now.

**Comment by SoftVision-CosminMuntean** [comment]
The issue is still reproducible on "My Shots" page with the latest changes that are merged on dev (v. 34.0.0). 
Considering this I will reopen this issue. The issue is more visible on mobile devices since the page is already resized there.

Here is a screen recording of the issue:
![share button](https://user-images.githubusercontent.com/19226534/48008368-32125500-e122-11e8-97b9-51c75b5bd040.gif)

**Comment by johngruen** [comment]
we're still good with this
