### ISSUE TITLE
Selecting expiration time not possible with low width

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#4443]
This looks like a CSS problem here:

![](https://screenshotscdn.firefoxusercontent.com/images/7d04ec89-7ddd-421d-92de-63f3f7d29764.png)

(https://screenshots.firefox.com/cEjeAKjj4Iu8Qkdv/screenshots.firefox.com)

1.024px × 682px

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this. However, this is a dupe of #3562 .
