### ISSUE TITLE
[Annotations] The drawing and area near it are wrongly blurred 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4452]
**[Affected versions]:**
- Nightly 62.0a1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" boolean pref is set to "false".
- Have the Screenshots 32.1.0 dev version installed from [ https://screenshots.dev.mozaws.net/homepage/install-test-local.html](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved shot link.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click on "Edit this image" button.
3. Select the "Highlighter" tool and draw on the image.
4. Observe the highlight and area near it. 

**[Expected result]:**
The drawing is correctly displayed.

**[Actual result]:**
The drawing is blurred and also the area near it. 

**[Notes]:**
- This issue is only reproducible when the shot image is at its original size.
- The issue is no longer reproducible if you draw and release the mouse outside the image's area.
- The issue is also reproducible with the "Pen" tool, but is more visible using the "Highlighter" tool.
- Attached a screen recording of the issue:

![rec of the issue](https://user-images.githubusercontent.com/37875464/40058286-64b5c886-5859-11e8-9747-e8b099b131a9.gif)

**Comment by chenba** [comment]
Strange.  The blur effect is pretty obvious in that recording, but in my tests it is not.  See the screen recording below.
![stroke-blur](https://user-images.githubusercontent.com/198055/40063551-38ab31b2-5823-11e8-8f49-1318637fd8fa.gif)

**Comment by chenba** [comment]
I cannot reproduce it in Linux either.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba can you please try with Firefox maximized on a small selection?

**Comment by chenba** [comment]
This bug is reproducible on smaller shots only.  Window size didn't have any effect.

**Comment by chenba** [comment]
Actually the size of the image does not matter.  It's very noticeable with text on a beige-y grey-ish background.  But apparently not on white backgrounds (as shown in my recording above).

Looks like it's an effect of all the copying done in order to produce a small, area of effect, canvas for the editor.  That was a last minute change, so I didn't test enough to notice.

@6a68 @ianb @punamdahiya I'm making a change so that a drawing tool's canvas is passed to the editor along with an optional `globalCompositeOperation`, and the editor will perform the `drawImage()` once to save the drawing.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reporducible using latest Screenshtos (32.1.0) dev version. Tested with latest Nightly (62.0a1) byuld on  Windows 7 x64, Mac 10.13 and Arch Linux.
