### ISSUE TITLE
[Annotations] The crop selection can wrongly exceed the image area

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4455]
[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 32.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Click the "Crop" button.
4. Start performing a selection and move the mouse diagonally until you hover the "Confirm" button.
5. Release the mouse and click the "Confirm" button
6. Observe the image.

[Expected result]:
Step 4: The selection remains within the image borders 
Step 6: The image is correctly cropped.

[Actual results]:
Step 4: The selection exceeds the image borders.
Step 6: An extra background is displayed.  

[Notes]:
- The issue is not reproducible after a selection was performed then resized.
- Here is a screen recording with the issue:
![crop selection 1](https://user-images.githubusercontent.com/19226534/40065306-28f7953e-586a-11e8-865a-63148a58179e.gif)

**Comment by chenba** [comment]
I've filed #4458 as a follow up.

**Comment by chenba** [comment]
Fixed in #4468

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (32.1.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux,
