### ISSUE TITLE
[Annotations] The image is wrongly dragged at first resize of a selection in crop mode 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4456]
[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" Boolean pref is set to "false".
- Have the Screenshots 32.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Click the "Crop" button.
4. Perform a selection on the image.
5. Resize the image without releasing the mouse.
6. Observe the behavior.

[Expected result]:
- The selection is correctly resized.

[Actual results]:
- The image is dragged.

[Notes]:
- After releasing the mouse the image is released but the selection can still be resized.
- Here is a screen recording with the issue:
![crop selection resize](https://user-images.githubusercontent.com/19226534/40068370-20d8fe0e-5871-11e8-85f8-7cd9f7eb6557.gif)

**Comment by chenba** [comment]
What's the being dragged are teh divs for the crop selection highlight and background (which are wrapped in a parent div).  It also looks like the right hand side background div is too wide.

**Comment by chenba** [comment]
PR's created.  Adding to current sprint.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (32.1.0) dev version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
