### ISSUE TITLE
The strings implemented on the addon side are no longer localized in the supported languages on latest Nightly 62.0a1 builds

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4464]
[Notes]:
- However, all the string from the sever side are localized.

[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a German Nightly (62.0a1) build installed or extracted.

[Steps to reproduce]:
1. Open the German Nightly (62.0a1) build with a new clean profile and navigate to any page.
2. Click on the "Page Actions" button and observe the "Take a Screenshot" button.
3. Click on the "Take a Screenshot" button and observe the Onboarding strings.
4. Skip the Onboarding tour and observe the overlay buttons and instructions.

[Expected result]:
- All the buttons and the strings are displayed in German.

[Actual result]:
- The buttons and the string are displayed in English.

[Additional Notes]:
- Tested with a German, Italian and French Nightly build.
- Here is a screen recording with the issue:
![screenshots locale 1](https://user-images.githubusercontent.com/19226534/40123079-fc8c2a4a-592d-11e8-9d72-c744aeddd54c.gif)

**Comment by chenba** [comment]
I just tried this with the French edition of the latest Nightly, and everything was localized.  @SoftVision-CosminMuntean can you re-verify?

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the issue is no longer reproducible with the latest Nightly (62.0a1, Build ID: 20180521220045) build. Tested with French and German builds and Screenshots was correctly localized.

However, the issue is still reproducible on Nightly build from 2018-05-16, so probably this was a Nightly regression that was fixed in the latest builds. Considering this I will close the issue.
