### ISSUE TITLE
Investigate NSP 663 and 664

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4470]
Builds on `master` started failing on 2018-05-16 (starting with https://circleci.com/gh/mozilla-services/screenshots/6792).  The failures are from nsp; see output below.  We should investigate to see if we can ignore those advisories in .nsprc.

```
> nsp check -o summary

(+) 2 vulnerabilities found
 Name           Installed   Patched   Path                                                                                              More Info                              
 open           0.0.5       None      firefox-screenshots@32.1.0 > jpm@1.3.1 > open@0.0.5                                               https://nodesecurity.io/advisories/663 
 stringstream   0.0.5       None      firefox-screenshots@32.1.0 > jpm@1.3.1 > sign-addon@0.2.0 > request@2.75.0 > stringstream@0.0.5   https://nodesecurity.io/advisories/664
```

**Comment by 6a68** [comment]
The bugs are in jpm, which appears to only be used in the `./bin/run-addon` local development script. I think we're fine to ignore those.

**Comment by pdehaan** [comment]
Submitted upstream issue to [deprecated] [**jpm**](https://github.com/mozilla-jetpack/jpm/issues/616) and there is an open PR in [**sign-addon**](https://github.com/mozilla/sign-addon/pull/254) which may handle the **stringstream** issue (maybe).
