### ISSUE TITLE
Conditionally Skip pg-patcher Backward Patches

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4484]
This is a follow-up to #4376 & #4347 (PR #4417 is where all the relevant comments live).

With this fix we want to, when the patch level in the database is greater than or equal to `MAX_DB_LEVEL` in `dbschema.js`:

- Always skip pgpatcher if `NODE_ENV` is "production"
- Skip pgpatcher if a certain config is set to true

**Comment by chenba** [comment]
@autrilla is the `NODE_ENV` env var exported or set in `docker run` during deployment?  [The image has a default of "production"](https://github.com/mozilla-services/screenshots/blob/master/Dockerfile#L11) and I don't know if it's changed during deployment.

**Comment by autrilla** [comment]
I don't see that env var set in the vars passed through docker run or by running `docker exec $container env`, neither in stage nor in prod.
