### ISSUE TITLE
./bin/run-addon doesn't create profile on first run

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4486]
Switched laptops this week, and `./bin/run-addon` doesn't generate the profile. Instead, it prints out the help text for the `open` command. I'm on High Sierra 10.13.4. What am I missing? Nightly is set as the default browser.

I worked around this by manually opening the Profile Manager, creating a new profile named ScreenshotsTestProfile, and saving it in a new /Profile folder inside the repo.

**Comment by 6a68** [comment]
The cause of this bug is the naming shift from "FirefoxNightly.app" to "Firefox Nightly.app" on mac.

**Comment by chenba** [comment]
Closing this since #4508 is merged.
