### ISSUE TITLE
[Annotations] Add Basic Support for Pointer Events

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4494]
React v16.4.0 added support for pointer events, and that should make it fairly easy for us to add support for them in annotations.

**Comment by chenba** [comment]
We've been discussing mobile device access to shots lately.  This issue is relevant if we want to support annotations on mobile.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
