### ISSUE TITLE
DNT implementation bug on server

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4500]
Strangely, although we [check Do Not Track status](https://github.com/mozilla-services/screenshots/blob/master/server/src/ga-activation.js#L3), it doesn't seem to be working for @fmarier:

Copied over from https://bugzil.la/1453492:

> When I open https://screenshots.firefox.com/9XnelFzjABSJrZIq/medium.com with Tracking Protection turned ON (which sets the DNT header automatically), I see this in the devtools console:
>
>  The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.
>
>Our Web Properties Tracking Policy has a few links on how this should be done:
>
>https://mana.mozilla.org/wiki/display/DATAPRACTICES/Additional+Cross-Organization+Practices#AdditionalCross-OrganizationPractices-MozillaWebPropertiesTrackingPolicy

**Comment by 6a68** [comment]
Side note: Seems like the suggested snippet on the security wiki would be a good npm module

**Comment by ianb** [comment]
Note that while we don't conditionally load the `google-analytics.js` code, we *do* suppress reporting analytics when DNT is on. The logic for this is in [ga-activation.js](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/ContextType). This was best practice at the time we actually implemented this code ;)

To fix this, we should probably change `ga-activation.js` to load the `google-analytics.js` script (I believe the logic already allows for async loading of the google-analytics.js script).

**Comment by chenba** [comment]
Funnily enough, the `[Learn More]` link after the "The resource at ... was blocked ..." message goes to an article that mentions the approach Screenshots currently use to handle DNT.
