### ISSUE TITLE
Remove use of google analytics

### ISSUE THREAD

**Issue by zuglufttier** [mozilla-services/screenshots#4511]
On https://screenshots.firefox.com/ Google Analytics is used.

Google Analytics will not help to improve the product but will only feed Google with tracking information of Firefox users that want privacy. That's why a lot of people choose Firefox in the first place!

If you need to track the usage of the site, why not implement something like Piwik/Matomo and keep the data for yourself?

**Comment by ianb** [comment]
Mozilla has decided (after very extensive legal, privacy, and policy review) that it is in line with our privacy standards and goals to use Google Analytics (which we use on many Mozilla sites, not just screenshots.firefox.com). But Mozilla generally, and Screenshots specifically, use it with two caveats:

1. We do not share the data collected with Google. That is, Google is hosting the data collection and analysis service, but they are not allowed to use the collected data for their own purposes. This is something Mozilla specifically negotiated with Google to allow, though it is now available as a preference on any Google Analytics account.
2. If you have Do-Not-Track enabled, then we do not submit any information to Google. As mentioned in #4500 we do load the script even if DNT is enabled, but we don't actually submit information. We plan to make the script loading itself conditional on DNT.
