### ISSUE TITLE
This isn’t a standard Web page, so you can’t take a screenshot of it.

### ISSUE THREAD

**Issue by armenzg** [mozilla-services/screenshots#4526]
For example:
https://support.mozilla.org/en-US/kb/firefox-screenshots

We should lead the user to a page to read more as to why we did not allow them to take a screenshot.
As of now, I don't know why I was not allowed.

**Comment by ianb** [comment]
Not related to the message, but apparently support.mozilla.org is on the domain blacklist (along with addons.mozilla.org and testpilot.firefox.com).

**Comment by marniepw** [comment]
Might consider adding a message for blacklisted sites.

**Comment by 6a68** [comment]
Hmm, it looks like the magic mozillaAddons permission fixes this bug, as I can now take screenshots of [addons.mozilla.org](https://screenshots.firefox.com/FzslEyBEwMdHkhSe/addons.mozilla.org) and [testpilot.firefox.com](https://screenshots.firefox.com/xvxm5OcMYT2OBW67/testpilot.firefox.com) in nightly, as well as [the support.mozilla.org page from the description](https://screenshots.firefox.com/8Heqt4u41vmAeLAr/support.mozilla.org).

Closing.
