### ISSUE TITLE
Define the browser support matrix

### ISSUE THREAD

**Issue by stasm** [mozilla-services/screenshots#4527]
What is the intended browser support matrix for https://screenshots.firefox.com?

I'm asking because in https://github.com/projectfluent/fluent.js/issues/133 we're considering dropping the support for old versions of Chrome and Firefox as well as the support for IE11. Fluent is used the localize the Screenshots website. Dropping the support would mean that the `fluent/compat` builds would contain async functions and `function*` generators, which cause syntax errors in browsers which don't support them.

**Comment by stasm** [comment]
FYI, here's the list of browser versions we're currently considering supporting in Fluent's `compat` builds:

    Firefox >= 52,
    FirefoxAndroid >= 52,
    Chrome >= 55,
    ChromeAndroid >= 55,
    Edge >= 15,
    Safari >= 10.1,
    iOS >= 10.1

Would that work for Screenshots?

**Comment by ianb** [comment]
We do server-side rendering and localization, so if client-side localization is broken it won't keep people from viewing pages. So dropping IE11 support won't keep IE11 users from viewing screenshots.

We don't have a specific browser support matrix, but the one you propose will work fine for us.

**Comment by stasm** [comment]
Thanks, @ianb. Sorry if I'll make you repeat the same thing again, but I'd like to make sure Fluent doesn't cause trouble for you. If we drop IE11 support, the `fluent/compat` module will cause syntax errors in the entire `shot-bundle.js`. All JS will be broken because of this. However, the website is served pre-rendered and pre-localized, and the minimal functionality of viewing screenshots will continue to work even in those older browsers. Did I get that right?
