### ISSUE TITLE
Investigate third-party image editor library

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4530]
We're investing a lot of resources in rolling our own image editor from scratch.

Let's explore integrating a third-party canvas editor library. We can use this bug to log our discussion and tie back any experimental PRs

**Comment by punamdahiya** [comment]
As discussed over IRC, some of the framework to be explored

- fabricjs - https://github.com/fabricjs/fabric.js
https://github.com/fabricjs/fabric.js/wiki/Who%27s-using-Fabric
- https://github.com/pixijs/pixi.js - lightweight 2D library using WebGL


Link to canvas demos using HTML5 canvas framework
https://github.com/rusi/canvas-demos

**Comment by chenba** [comment]
Could swap in https://github.com/viliusle/miniPaint as a replacement.  It doesn't have redo.  Happy to trade that for layers though.

**Comment by punamdahiya** [comment]
@chenba I liked how miniPaint let user enter multiple text in single text edit screen, should discuss this interaction as an option  with John and Seevan

**Comment by wresuolc** [comment]
For any new libraries, we need to make sure the licenses are compatible and they go through a security review

**Comment by 6a68** [comment]
stealing this bug

**Comment by 6a68** [comment]
I actually think we can just close this. We've got a good feature set, no external dependencies, and the future focus is on FxA integration, not additional annotations / image editing features.
