### ISSUE TITLE
Blank page while taking screenshot on console.cloud.google.com

### ISSUE THREAD

**Issue by benjiprod** [mozilla-services/screenshots#4537]
Hi,

When I use Screenshots add-ons on Console Google Cloud Plateform, website changes in a blank page and impossible to take a screenshot.

Anyone has the same issue ?

I can share a screenshot if you want.

**Comment by SoftVision-CosminMuntean** [comment]
@benjiprod Thanks for reporting this!

I have managed to reproduce this issue on latest Firefox (60.0.2) release and latest Nightly 62.0a1 build. After clicking the "Take a Screenshot" button on the "console.cloud.google.com" website, the page becomes blank. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

Here is a screen recording of the issue: 
![blank page](https://user-images.githubusercontent.com/19226534/41145929-4f57f25c-6b0a-11e8-981d-038575e64c88.gif)
