### ISSUE TITLE
[Annotations] The first drawing is wrongly performed after the "Undo" button is clicked on a cropped image

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4548]
[Affected versions]:
- Nightly 62.0a1
- Screenshots 33.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
- Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Crop" tool and confirm a selection.
3. Click the "Undo" button.
4. Hover the image and observe the cursor.
5. Draw a line on the image and observe the behavior.

[Expected result]:
Step 4: The "Pen" cursor is displayed.
Step 5: The line is correctly drawn.

[Actual results]:
Step 4: The arrow cursor is wrongly displayed instead of the "Pen" cursor outside the area that was previously cropped.
Step 5: The line is not drawn to the indicated mouse position.

[Notes]:
- This issue is not reproducible if you don't confirm the crop selection.
- This issue is not reproducible if you change the drawing tool to "Highlighter".
- Here is a screen recording with the issue:
![ss - draw after crop](https://user-images.githubusercontent.com/31244235/41239409-ee68188e-6da0-11e8-8914-80d5e145bded.gif)

**Comment by chenba** [comment]
PR #4516 should fix this bug.

**Comment by chenba** [comment]
#4516 has been merged.  Please re-verify this issue.  Thanks.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using the latest Firefox Screenshots v33.0.0dev, on latest Nightly build 62.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
