### ISSUE TITLE
Cannot cancel screenshot interface

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4560]
From discourse @ https://discourse.mozilla.org/t/feedback-cannot-return-to-page-after-screen-shot/28499

> Completed an Ipop payment and was shown a receipt page. Did a screenshot of complete page. Did a download and saved the file.
> There appears to be no way to leave the page with My screenshot icon on left top and download button on right top.
> ![image](https://user-images.githubusercontent.com/16946141/41551561-0dbf604e-72e1-11e8-84c9-6649e9783212.png)
> Note the screenshot (copied from my download folder) shows a button to return to the Interislander web site. Because I cannot escape the screenshot page cannot use that button.

**Comment by johngruen** [comment]
theory is they are looking at a raw png but idk

**Comment by johngruen** [comment]
Alternate theory...user is trying to navigate back from a newly opened shot tab

**Comment by chenba** [comment]
I've followed up in Discourse, but the user hasn't replied yet.
