### ISSUE TITLE
The "Save" and "Cancel" buttons from the expiration date cannot be accessed using the "Enter" key

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4561]
[Affected versions]:
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
- Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "expires in ..." button and select a period.
3. Press the "Tab" key once.
4. Press the "Enter" key once and observe the behavior.

[Expected result]:
- The image is saved.

[Actual results]:
- Nothing happens.

[Notes]:
- Here is a screen recording with the issue:
![ss - cannot access buttons using enter key](https://user-images.githubusercontent.com/31244235/41585270-3bfb9f3c-73b2-11e8-88e9-a04c96de0c11.gif)

**Comment by 123survesh** [comment]
Hi, I would like to work on this issue. I will update here once I have something going on :)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
