### ISSUE TITLE
Backport "skip DB downgrades" changes for a 31.5.0 server release

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4562]
- [x] Cherry-pick changes for #4484 (commit https://github.com/mozilla-services/screenshots/pull/4490/commits/f0e02c2848eeae0ed76e7bf048c9263954517104) into current server release, 31.4.0
- [x] Update version number to 31.5.0
- [x] Update changelog
- [x] Create new release tag
- [x] Push to server-prod
- [x] Apply changelog changes in master

**Comment by 6a68** [comment]
@chenba Anything left to do, or can this bug be closed?

**Comment by chenba** [comment]
Can be closed.
