### ISSUE TITLE
Manually Add Values to the `shot_block_type` pg Enum on stage

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4565]
Once 31.5.0 is running on stage, we should do a dry run of what was discussed in https://github.com/mozilla-services/screenshots/pull/4417

The following need to be executed on the stage instance of Postgresql:

```
ALTER TYPE shot_block_type ADD VALUE 'abuse';
ALTER TYPE shot_block_type ADD VALUE 'usererror';
ALTER TYPE shot_block_type ADD VALUE 'watchdog';
UPDATE property SET value = '23' WHERE key = 'patch';
```

**Comment by 6a68** [comment]
@autrilla this bug is yours :-)

**Comment by autrilla** [comment]
Executed in stage

**Comment by chenba** [comment]
Note that with this, the db level reported in `__version__` will be incorrect until the next deploy with a db up migration.

@6a68 could you add autrilla to Screenshots so we can properly assign this? 😃
