### ISSUE TITLE
Signing in to sync from "Screenshots" is no longer possible after an invalid age is entered when creating an account

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4581]
Also logged in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1470902
***

**[Affected versions]:**
- Firefox Nightly

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have "Screenshots" experiment (installed from https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

**[Steps to reproduce]:**
1. Open Firefox and navigate to https://screenshots.dev.mozaws.net/shots.
2. Click the gear wheel button and click the "Sign in" button.
3. Enter a valid e-mail adress and a valid password.
4. Enter an invalid age (under 13).
5. Click the "Create account" button and close the "accounts.firefox.com" tab.
6. Navigate to https://screenshots.dev.mozaws.net/shots and repeat step 2.
7. Observe the behavior.

**[Expected result]:**
- The "Sign in" page is displayed.

**[Actual result]:**
- "Cannot create account" message is displayed.

**[Notes]:**
- The issue remains even if the browser is restarted.
- This issue is also reproducible with the "Notes" experiment.
- This issue is not reproducible if you create a new account with an invalid age using the Firefox' Sync service. 
- Attached a screen recording of the issue:

![sync sign in screenshots](https://user-images.githubusercontent.com/37875464/41859406-c3bdb3d2-78a4-11e8-874c-d04888771195.gif)

**Comment by johngruen** [comment]
This is a legal requirement covered under COPPA and we really can't do anything about it
