### ISSUE TITLE
Firefox Screenshots Dev server no longer works

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4582]
[Affected versions]:
- Firefox 60.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://screenshots.dev.mozaws.net/homepage/install-test-local.html.
2. Observe the behavior.

[Expected result]:
- The Firefox Screenshot dev installation website is displayed.

[Actual results]:
- Blank page is displayed.

[Notes]:
- Also, if you had a Firefox profile with Firefox Screenshots dev version installed, it no longer works when you try to save a selection. Here is a screenshot with the error displayed in the Browser Console:
![ss - error](https://user-images.githubusercontent.com/31244235/41963773-1651b050-7a01-11e8-9c12-347f78db0bf4.png)

- Here is a screen recording with the issue:
![ss - firefox screenshots dev installation website](https://user-images.githubusercontent.com/31244235/41963751-0c26a892-7a01-11e8-9127-58bf867bb16e.gif)

**Comment by chenba** [comment]
Dev server is back up now.  @Softvision-CristinaBadescu Thanks for notifying.

**Comment by Softvision-CristinaBadescu** [comment]
Great news :) ! This issue is no longer reproducible using the latest Nightly build 63.0a1 and Firefox Release 61.0. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
