### ISSUE TITLE
The "Expired shot" page is wrongly displayed when refreshing the page after the time has passed

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4584]
[Affected versions]:
- Dev Edition Version 62.0b3, Build ID 20180625141512
- Nightly Version 63.0a1, Build ID 20180629100106
- Screenshots 33.0.0 dev version

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" boolean pref is set to "false"
- Have the latest Firefox Screenshots v33.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved screenshot.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the saved shot's page.
3. Change the expiration date to 1 hour.
4. Change the system date to be 1 hour in the future.
5. Refresh the savd shot's page.
6. Observe the "Expired shot" page.

[Expected result]:
- The page is correctly displayed.

[Actual result]:
- The page elements are misplaced.

[Notes]:
- The issue is also reproducible if the time passes naturally and the shot page is refreshed right after it expires.
- The issue is not reproducible with Screenshots stage or production version.
- Here is a screenshot of the issue:
![ss issue refresh](https://user-images.githubusercontent.com/40393891/42099775-09d74674-7bc7-11e8-98af-78f156ca78e1.png)

- Here is a screen recording of the issue:
![expired shot](https://user-images.githubusercontent.com/40393891/42099788-11357738-7bc7-11e8-8e48-4335bc0654b4.gif)

**Comment by ianb** [comment]
This is because we're re-rendering the page locally and using the local time as a second check, and rerendering as a result. This does appear to cause a rendering bug (the header goes at the bottom of the page), but given that it's an unusual situation I think we don't need to look into it further.
