### ISSUE TITLE
Set protected status on production branch

### ISSUE THREAD

**Issue by moz-hwine** [mozilla-services/screenshots#4587]
The production branch on this repository is not protected against force pushes. This setting is recommended as part of [Mozilla's Guidelines][guidelines_url] for a Sensitive Repository.

**Anyone with admin permissions for this repository can correct the setting using [this URL][protect_url].**

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH0001 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Security Operations team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla-services/screenshots/settings/branches
[email]: <mailto:secops+github@mozilla.com?subject=SOGH0001+Question+re+mozilla-services/screenshots>

**Comment by johngruen** [comment]
More context: https://github.com/mozilla/FirefoxColor/issues/368

**Comment by 6a68** [comment]
* We will set protected status on the server-prod branch (but note, ppl on the team could still force push)
* We don't deploy directly from this repo into Firefox or to the server, only to stage
* Everyone on the team is a repo admin & has 2FA enabled
* Even if compromised, the risk is low (we review every Firefox export carefully)

**Comment by moz-hwine** [comment]
Hello! This is your neighborhood secops team still looking out for you!

The production branch on this repository is still not protected against force pushes. If the repository's production branches are not set as the GitHub default, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScbOGCBZJ0xDpwGUyPYpdRMGl2doOh4qT7iSVvwxjXRvT6YWQ/viewform?usp=sf_link).

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH001-1 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Operations Security team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla-services/screenshots/settings/branches
[email]: <mailto:secops+gh001@mozilla.com?subject=SOGH001-1+Question+re+mozilla-services/screenshots>

**Comment by moz-hwine** [comment]
Hello! This is your neighborhood secops team still looking out for you!

The production branch on this repository is still not protected against force pushes. If the repository's production branches are not set as the GitHub default, please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLScbOGCBZJ0xDpwGUyPYpdRMGl2doOh4qT7iSVvwxjXRvT6YWQ/viewform?usp=sf_link).

If you have any questions, or believe this issue was opened in error, please contact [us][email] and mention SOGH001-2 and this repository.

Thank you for your prompt attention to this issue.
--Firefox Operations Security team

[guidelines_url]: https://wiki.mozilla.org/GitHub/Repository_Security
[protect_url]: https://github.com/mozilla-services/screenshots/settings/branches
[email]: <mailto:secops+gh001@mozilla.com?subject=SOGH001-2+Question+re+mozilla-services/screenshots>

**Comment by ianb** [comment]
`server-prod` is protected. I have noted this in the linked form.
