### ISSUE TITLE
Not working with `privacy.resistFingerprinting:true`

### ISSUE THREAD

**Issue by the-noob** [mozilla-services/screenshots#4595]
If the setting `privacy.resistFingerprinting` is `true` in `about:config` the plugin stops working.
When taking a screenshot you are presented with the attached dialog and, even if you select allow, the screenshot is saved as a white rectangle.

![html5_canvas](https://user-images.githubusercontent.com/541531/42210708-39975534-7ea1-11e8-847e-58c7a12e7426.png)

Tried on Firefox 61.0b14 (64-bit) - Ubuntu and Windows 10.

**Comment by SoftVision-CosminMuntean** [comment]
@the-noob thanks for reporting this!
This issue was fixed by [bug 1453916](https://bugzilla.mozilla.org/show_bug.cgi?id=1453916) and is no longer reproducible on Firefox Beta 62.0b4 and latest Nightly 63.0a1 build.

**Comment by the-noob** [comment]
Seems I need to do a bit more searching in the future :)

**Comment by SoftVision-CosminMuntean** [comment]
No worries. Retesting this issue helped me find another one (see #4597), so thanks for this!
