### ISSUE TITLE
"Save full page" functionality no longer works on long pages with Screenshots dev version

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4596]
[Affected versions]:
- Nightly 63.0a1
- Screenshots 33.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" boolean pref is set to "false"
- Have Screenshots (33.0.0) dev version installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://imgur.com/".
2. Scroll the page in order to load a large amount of content.
3. Click the "Take a Screenshot" option from "Page Actions" menu.
4. Click the "Save full page" button from the top right part of the page.
5. Observe the behavior.

[Expected result]:
- The "Save full page" functionality works as expected.

[Actual results]:
- Screenshots overlay is dismissed and "Whoa! Firefox Screenshots went haywire" system error is displayed.

[Notes]:
- The issue is not reproducible with stage and production version.
- Here is a screenshot with browser console errors:
![browser console errors full page](https://user-images.githubusercontent.com/19226534/42211175-976854fa-7ebb-11e8-8f4a-defb68cbbad1.png)

- Here is a screen recording with the issue:
![save full page on large pages 2](https://user-images.githubusercontent.com/19226534/42211536-8485dc30-7ebc-11e8-8887-f8b465cdfa28.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1 (2018-07-09). Verified on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
