### ISSUE TITLE
[Annotations] The image becomes blank after editing it, if the "privacy.resistFingerprinting" pref is set to "true"

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4597]
[Affected versions]:
- Nightly 63.0a1
- Beta 62.0b4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile.
- Have the "privacy.resistFingerprinting" pref is set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Click the "Edit this image" button.
4. Draw a line on the image and click the "Save" button.
5. Observe the edited image.

[Expected result]:
- The image is correctly displayed.

[Actual results]:
- The image is blank.

[Notes]:
- Here is a screen recording with the issue:
![blank image](https://user-images.githubusercontent.com/19226534/42219744-a08ca814-7ed5-11e8-9bdc-b1307fbe2943.gif)

**Comment by ianb** [comment]
resistFingerprinting makes all canvas uses not work, including on the screenshots site. We have an exception in Firefox for the add-on, but I don't think that would apply to web content. Presumably all online image editors are broken with resistFingerprinting on.
