### ISSUE TITLE
The shots saved after the "ExtensionStorageIDB" pref was set to true, are not displayed in "My Shots" page if the same profile is opened with Firefox Release

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4602]
[Affected versions]:
- Nightly 63.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile.
- Have the "extensions.webextensions.ExtensionStorageIDB.enabled" Boolean pref set to "true".

[Steps to reproduce]:
1. Open the latest Nightly browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Close the Nightly browser and open the same profile with latest Firefox Release (61.0.1).
4. Navigate to any website and from "Page Actions" menu click the "Take a Screenshot" issue.
5. Observe the behavior.
6. Click the "My Shots" button and observe the "My Shots" page.

[Expected result]:
Step 5: The Screenshots Onboarding tour is not displayed. .
Step 6: The saved shot is correctly displayed.

[Actual results]:
Step 5: The Screenshots Onboarding tour is displayed. .
Step 6: The saved shot is not displayed.

[Notes]:
- The issue is also reproducible for shots saved on Firefox Release, if the same profile is opened with the latest Nightly browser that has the "extensions.webextensions.ExtensionStorageIDB.enabled" boolean pref set to "true". The shots taken on Firefox release are not displayed on latest Nightly build.
- The issue is not reproducible if you open the Firefox Beta instead of Firefox Release.
- Here is a screen recording with the issue: https://goo.gl/ojh8xg
- Here is a screen shot with browser console errors:
![scenario 3](https://user-images.githubusercontent.com/19226534/42379402-3a3e4e18-8133-11e8-99fc-88dd0852ba8a.png)

**Comment by ianb** [comment]
This seems like it won't effect most people, as IndexedDB won't be used until at least 63 (though it's not, and if someone installs/uses 62 then they won't encounter this bug. 

Though if `extensions.webextensions.ExtensionStorageIDB.enabled` *defaults* to true in Nightly, but not in beta (something which will eventually happen), then I'm guessing this bug will reappear if you go from Nightly to Beta.

This might be a known issue (intuitively this feels expected), but we could notify the Firefox/add-ons team about the issue.

**Comment by 6a68** [comment]
I opened an upstream bug (bug 1474696) about this issue, and it was wontfixed. I don't see what more we can really do here; closing.
