### ISSUE TITLE
Add Some Logs to Debug Watchdog Integration

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4606]
The Watchdog integration code and config values have been deployed to dev.  But it isn't working: requests are not showing up in AWS monitoring for dev Watchdog's `accept` endpoint.  With the same configuration on my local setup, requests do reach the endpoint.

Let's add some (minimal) output to see what's going on.  We can back this out once everything's working.

**Comment by chenba** [comment]
Closing this because I'm fairly certain what the problem is in dev.

**Comment by 6a68** [comment]
Closed by #4608
