### ISSUE TITLE
[Annotations] The added text box and the area it overlaps are wrongly blurred after using the "Undo" / "Redo" buttons

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4616]
**[Notes]:**
- Redoing will result in blurring the added text as well.
- If you click the "Undo" and "Redo" buttons multiple times, the blur intensifies.
- This issue is not reproducible on Mac Book Pro Retina Display 13 inch, OS 10.13.3.

**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.0.0 dev version installed from here, on a new clean profile.
 - Have a saved shot link that contains some text.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot
2. Click the "Edit this image" button.
3. Click the "Add text" button and type some text.
4. Move the text box over some text from the screenshot.
5. Click on "Confirm" button.
6. Click the "Undo" button and observe the shot.

**[Expected result]:**
- The added text is correctly removed.

**[Actual results]:**
- The image is blurred where the text box was previously added.

**[Additional Notes]:**
- Here is a screen recording with the issue:
![text box blur](https://user-images.githubusercontent.com/37875464/42641478-4e58ba18-85fd-11e8-9701-d12286f7d5dd.gif)

- Undoing an added text which has a black background leaves a thin contour of it. Here is a screenshot with this issue:
![contour](https://user-images.githubusercontent.com/37875464/42641585-86c249fa-85fd-11e8-9edf-05c5fd0665f0.png)

**Comment by chenba** [comment]
This is caused by decimal pixel units.

**Comment by chenba** [comment]
@punamdahiya I'll take this since you said you cannot reproduce it.  Are you testing on a "Retina" MBP?

**Comment by punamdahiya** [comment]
@chenba just saw notes. Yes I am using Mac Book Pro Retina Display 15 inch, OS 10.13.2

**Comment by chenba** [comment]
The `x` of the input div is updated as the user types, and division is involved in calculating the new value, so that's the most likely source the a decimal.

**Comment by punamdahiya** [comment]
@chenba changes in PR looks good to remove decimal while calculating div left and top position. As I am not able to replicate this issue, I have the PR r+ trusting that it fixes the blurriness and thin contour  reported in the issue.

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Debian 9.3
