### ISSUE TITLE
[Annotations] Text shifts up slightly on confirm

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4620]
Inside Texttool, slight shift is seen when text is rendered on canvas on hit of confirm. This is because y position used to fill text on canvas varies across platform due to difference in line-height.
For example for large  font-size 36p, line-height in windows - 41.5, unix - 43, mac- 36.5

**Comment by punamdahiya** [comment]
Because of the line-height differences, may be we should use line-height instead of font-size to compute initial top position https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/text-tool.js#L37

**Comment by punamdahiya** [comment]
The shift is primarily because of line-height differences for a font-size in different platforms causing y position to be computed less than desired to render text in canvas.

For windows, for large font-size adding 1.5 to y position resolves the shift, for mac for large font-size shift is 0.5 and less apparent

**Comment by 6a68** [comment]
Still shifts noticeably on windows for certain fonts. Some funky behavior on other platforms, but windows is most of our users

**Comment by punamdahiya** [comment]
Shift is noticeable if emojis are added in the inserted text

**Comment by chenba** [comment]
Here's how what it looks like on Windows 10 and Linux.  (View the gifs in their original size.)

Windows

![winows10-text-tool-shift](https://user-images.githubusercontent.com/198055/42958432-2113cf4a-8b4b-11e8-99a0-9cccb6b2bb1c.gif)

Linux

![linux-text-tool-shift](https://user-images.githubusercontent.com/198055/42958443-2802d6d4-8b4b-11e8-8a7a-8d1751b3f3d0.gif)

**Comment by punamdahiya** [comment]
On Mac 10.13.2

![ezgif com-screenshots-mac-screen-recording-4620](https://user-images.githubusercontent.com/597734/42961836-d9d1e4ba-8b44-11e8-8836-73e1bb678345.gif)

**Comment by punamdahiya** [comment]
@6a68 @johngruen including for feedback on the gifs above in respective OS to re-evaluate #4620 priority

**Comment by 6a68** [comment]
We discussed this issue and the current outstanding PR in standup today, and based on John's WFM comment, and the fact that we're down to subpixel rounding errors, decided to just close this as good-enough for now.
