### ISSUE TITLE
[Annotations] The “Color picker” tool has inconsistent behavior when entering and exiting the "Text" tool

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4623]
**[Notes]:**
- Changing the color in the “Edit image” section modifies the color in the “Add text” section, while changing the color in the “Add text” section does not modify the color in the “Edit image” section.

**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.0.0 dev version installed from here, on a new clean profile.
 - Have a saved shot link.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot link.
2. Click the “Edit this image” button.
3. Click the “Color picker” button and change the color to red.
4. Click the “Add text” button and observe the “Color picker” button.
5. Click the “Color picker” button and change the color to blue.
6. Click the “Confirm” button and observe the “Color picker” button.

**[Expected result]:**
4. The button is red.
6. The button is blue.

**[Actual results]:**
4. The button is red.
6. The button remains red.

**[Additional Notes]:**
- The issue is reproducible regardless of what colors are chosen.
- Attached a screen recording with the issue:

![color picker](https://user-images.githubusercontent.com/37875464/42687800-a51b83d0-86a2-11e8-8ad0-339591e7b469.gif)

**Comment by punamdahiya** [comment]
Needs product thought on this issue. @johngruen  should the color changes inside text-tool be carried over to main tool to be used by pen and highlighter?

**Comment by wresuolc** [comment]
The sub-tool replaces the entire UI of the parent tool here, so we think not bubbling up the color is the right thing to do in this case.
