### ISSUE TITLE
[Annotations] Long strings disappear if they are pasted into narrow screenshots

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4625]
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to a website (eg. www.wikipedia.com).
2. Take a narrow screenshot (eg. less than 500p width) and click the "Edit this image" button.
3. Click the "Add text" button.
4. Press the "Ctrl"+"V" key combination and observe the behavior.

[Expected results]:
- The pasted string is in view, contained in the screenshot.

[Actual results]:
- The pasted string disappears from the screen.

[Notes]:
- The textbox starts to move out of sight when pasting strings of 15 characters or longer.
- The textbox disappears completely when pasting strings of 45 characters or longer
- I have attached a screencast of the issue:
![ctrl_v_disappear](https://user-images.githubusercontent.com/40393891/42690891-b5715de8-86ae-11e8-8038-dd2770b84787.gif)

**Comment by punamdahiya** [comment]
Fix of #4624 , handles paste event for both context menu and Ctrl+V and sets the left position of the text.  Please test once we have the #4624 fix landed in master

**Comment by chenba** [comment]
#4624 shouldn't affect this bug since it doesn't do anything with `this.state.left`.  I'll have a PR for this.  One of us will get a merge conflict depending whose stuff get merged first. :D

**Comment by chenba** [comment]
The default positioning behavior of the contenteditable div works pretty well: it'll keep the cursor in view.  The only time where we'd want to adjust the position is when the div is narrower than the canvas, so that the div is centered.

**Comment by chenba** [comment]
Looks like #4636 also fixes this issue.  🎉

**Comment by Softvision-PatriciuPop** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version, on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04.
