### ISSUE TITLE
[Annotations] Writing in the textbox wrongly moves it to the left

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4626]
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to a website (eg. www.wikipedia.com).
2. Click the "Edit this image" button.
3. Click the "Add text" button and write a long string of text.
4. Press and hold the "Backspace" key and observe the behavior.

[Expected results]:
- The textbox remains in a fixed position.

[Actual results]:
- The textbox moves to the left as the characters are removed.

[Notes]:
- If the textbox is moved to the left edge of the image, writing in it will cause the textbox to disappear from view.
- I have attached a screencast of the issue:
![textbook to the left](https://user-images.githubusercontent.com/40393891/42691058-42e7da4e-86af-11e8-8405-45e2568f452d.gif)

**Comment by punamdahiya** [comment]
@Softvision-PatriciuPop  with #4658 fix in master, can you please check if this issue is replicable following above steps

**Comment by Softvision-PatriciuPop** [comment]
This issue is still reproducible using the latest Firefox Screenshots dev version, on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04.

**Comment by chenba** [comment]
Currently as the user delete characters, an equal amount of width is remove from both end of the input element _regardless_ of where the input is relative to the shot image.  As a user enter text, the input is shifted to the left so that the cursor can stay in view on the right side of the shot (this is a default browser behavior).  The effect of those two things is this bug.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots [dev version](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04 x64.
