### ISSUE TITLE
[Annotations] The string is shifted to the left if it was pasted using the context menu and the left arrow key is pressed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4627]
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.0.0dev installed.
- Have a saved shot link.
- Have a string copied to the clipboard.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and click the "Add text" button.
3. Right click the text field and select the "Paste" option.
4. Press the left arrow key and observe the behavior.

[Expected result]:
- The text caret is moved to the left.

[Actual result]:
- The string is shifted to the left.

[Notes]:
- This issue is also reproducible using the "End" key.
- This issue is not reproducible if you paste the text using the "Ctrl/Cmd + V" keys combination, but the text is shifted to the left after pasting it like this. 
- Here is a screen recording with this issue:

![ss - text shifts to the left](https://user-images.githubusercontent.com/31244235/42691396-8306781e-86b0-11e8-969c-110ead4a0792.gif)

**Comment by punamdahiya** [comment]
With #4624 fix, this issue should be fixed , thanks!

**Comment by Softvision-CristinaBadescu** [comment]
While verifying this issue, I've encountered the behavior described in #4642 . I'll fully verify this after the mentioned issue is fixed. Thanks!

**Comment by Softvision-CristinaBadescu** [comment]
The issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
