### ISSUE TITLE
[Annotations] Formatted text is not pasted in the “Add text” section with “CTRL” + ”V” keys

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4628]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
- Have the Screenshots 33.0.0 dev version installed from here, on a new clean profile.
- Have a saved shot link.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and copy the following string to the clipboard: String
2. Navigate to the saved shot link.
3. Click the "Add text" button.
4. Press `CTRL` + `V` keys and observe the behavior.

**[Expected result]:**
- The text is correctly pasted.

**[Actual results]:**
- The text is briefly displayed and then it disappears.

**[Notes]:**
- Formatted text can be pasted in “Add text” section by clicking “Paste” button from context menu.
- Attached a screen recording with the issue:
![paste using the keyboard](https://user-images.githubusercontent.com/37875464/42695621-a92470b0-86be-11e8-9287-f7238c22796e.gif)

**Comment by punamdahiya** [comment]
As of now TextTool doesn't support extracting text from inside DOM elements such as P, SPAN.  With the fix in #4624, pasting simple text via context menu should work.

**Comment by punamdahiya** [comment]
Closing issue as for complex formatted text that's expected behavior. Adding text via pasting simple text should work

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version installed from here, on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux.
The formatted text is no longer pasted with 'CTRL' + 'V' keys nor with "Paste" option from context menu.
