### ISSUE TITLE
[Annotations] Long text strings have increasingly smaller textbox drag previews

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4631]
[Affected versions]:
- Nightly 63.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false".
 - Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.
 
[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to a website (eg. www.wikipedia.com).
2. Take a screenshot and click the "Edit this image" button.
3. Click the "Add text" button and write a long string of text (80+ characters).
4. Click on the textbox.
5. Start dragging it and observe the preview.

[Expected results]:
- The textbox preview remains the same size.

[Actual results]:
- The textbox preview is smaller than the textbox.

[Notes]:
- On very long strings (3000+ characters) the preview disappears completely.
- This issue is reproducible regardless of text size.
- I have attached a screencast of the issue:
![small_preview](https://user-images.githubusercontent.com/40393891/42697718-906d7cd2-86c4-11e8-87d4-476507ae534d.gif)

**Comment by chenba** [comment]
We've changed how drag and drop works and this is no longer an issue.

**Comment by Softvision-PatriciuPop** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version, on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04.
