### ISSUE TITLE
[Annotations] "Confirm" button no longer works after inserting very long strings 

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4632]
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release Unbranded

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false".
 - Have the Screenshots 33.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to a website (eg. www.wikipedia.com).
2. Take a screenshot and click the "Edit this image" button.
3. Click the "Add text" button and write or paste a very long string of text (eg. 1500+ characters).
4. Click on the "Confirm" button and observe the behavior.

[Expected results]:
- The changes are correctly saved and the image editing page is displayed.

[Actual results]:
- The "Confirm" button remains highlighted and the "Add text" menu is no longer displayed.

[Notes]: 
- The issue appears only on strings longer than 1500 characters.
- I have attached a screencast of the issue:
![confirm_not_working](https://user-images.githubusercontent.com/40393891/42698694-4ff3f304-86c7-11e8-8a88-5ed6fe4a87c8.gif)

**Comment by chenba** [comment]
I think this is caused by the width of the text being wider than the canvas width limit.

**Comment by johngruen** [comment]
@Softvision-PatriciuPop can you test 256, 512 and 1024 `O` characters and tell us if any of these break?

**Comment by Softvision-PatriciuPop** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version and now we have a limit of 1000 characters for the textbox. I have verified this on latest Nightly build 63.0a1, on Windows 10 x64, Mac 10.13.5 and Ubuntu 16.04.

**Comment by punamdahiya** [comment]
The issue is resolved and verified by QA and can be closed
