### ISSUE TITLE
a11y audit

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4634]
Following the approach demo'd by Eitan on the a11y team a week or two ago, look at the warnings generated by the axe accessibility addon in the shot page, shot creation flow, my shots page, and homepage. File bugs for reasonably small chunks that could be parallelized, maybe with the [a11y] label in the title for sorting. Use the good first bug label liberally.

**Comment by chenba** [comment]
I think this can be closed now.
