### ISSUE TITLE
[Annotations] The text caret is wrongly moved at the beginning of the string after pasting it or after changing its size or color

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4642]
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release 61.0.1 Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.0.0dev installed.
- Have a saved shot link.
- Have a string (eg. "Test") copied to the clipboard.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and click the "Add text" button.
3. Right click the text field and select the "Paste" option.
4. Observe the text caret position.

[Expected result]:
- The text caret is displayed at the end of the pasted string.

[Actual result]:
- The text caret is displayed at the beginning of the pasted string.

[Notes]:
- This issue is also reproducible if you paste the text using the "Ctrl/Cmd + V" keys combination.
- This issue is also reproducible if you click outside the text box and change the text size.
- This issue is also reproducible if you type a string and change the color.
- Here is a screen recording with this issue:
![ss - text caret - moved at the beginning](https://user-images.githubusercontent.com/31244235/42751174-9490d536-88f2-11e8-84c6-c26a7822fc15.gif)

**Comment by johngruen** [comment]
We can fix this by using an input

**Comment by punamdahiya** [comment]
This issue should be fixed with merge of #4658 in master

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for fixing this! The issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
