### ISSUE TITLE
[Annotations] The shot wrongly darkens while the "Highlighter" tool and the white color are selected

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4645]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.0.0 dev version installed from here, on a new clean profile.
 - Have a saved shot link.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot link.
2. Click the “Edit this image” button.
3. Click the “Highlighter" and select the white color from the "Color Picker".
4. Observe the shot.

**[Expected result]:**
 - The shot remains the same.

**[Actual results]:**
 - The shot darkens.

**[Notes]:**
- If you highlight an image with the white color, after you release the tool, the highlight effect loses intensity.
- All of this effects are no longer observable after the shot is saved.
- This issue is not reproducible with other colors, or with the pen tool. 
- Attached a screen recording with the issue:

![rec of the issue](https://user-images.githubusercontent.com/37875464/42758924-d836c3d4-890d-11e8-8329-a12836b4807e.gif)

**Comment by chenba** [comment]
This is a new issue.  I just verified that it does not occur in current prod.  It's caused by https://github.com/punamdahiya/screenshots/commit/503e18266ed5f6e1ee2362f3c59a0a0b0f593cf7#diff-3fdb50a1a48ec71ae775e6b54c391d42R721

**Comment by chenba** [comment]
Maybe we could use a `[QA]:Regression` label.

**Comment by punamdahiya** [comment]
Debugged and issue is .white css  selector for highlighter incorrectly loads both https://github.com/mozilla-services/screenshots/blob/master/static/css/frame.scss#L491
and 
https://github.com/mozilla-services/screenshots/blob/master/static/css/frame.scss#L718

Will update text-tool color css selectors to use both class and ID to fix  the issue

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.3 and Arch Linux.
