### ISSUE TITLE
[Annotations] Text box is not brought into view when it is refocused

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4652]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.
 - Have a very long (over 2000px) shot saved.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to my shots page. 
2. Click on the long shot and click on "Edit this image" button.
3. Click the "Add text" button.
4. Scroll down until the text box is no longer visible.
5. Change the text size and observe the behavior.

**[Expected result]:**
 - The text box is correctly focused and is in view.

**[Actual results]:**
 - The area below the text box is in view, but the text box is not in view.
 
 **[Notes]:**
 - This issue is also reproducible if you change the text color or type something when the text box is focused but is out of view.
 - This issue is not reproducible if the text box is below the visible area.
 - Screen recording with the issue: [link](https://drive.google.com/open?id=1QM0kBNWjZSDRoaTUQEiwo8dbF_OMtueL)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible when the text box is above the area in view, and the text size or text color is changed. But it is reproducible when you type a string and the text box is not in view.

Also now there is an inconsistent behavior, when the text box is below the area in view and the text size/text color is changed or a string is typed, the text box is not brought in the center of the area in view, it is placed at the bottom. 

Considering this I will reopen this issue.

Attached a screen recording with the issue: [link](https://drive.google.com/open?id=1QM0kBNWjZSDRoaTUQEiwo8dbF_OMtueL)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and the issue is no longer reproducible. 
Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
