### ISSUE TITLE
[Annotations] Inconsistent behavior across OS-es when pressing "Page Up" and "Page Down" key while the text box is focused

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4654]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.
 - Have a very long (over 3000 px) shot saved.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to my shots page. 
2. Click on the long shot and click on "Edit this image" button.
3. Click the "Add text" button from the top left Screenshots toolbar.
4. Press twice the "Page Down" key and observe the behavior.

**[Expected result]:**
 - Have the same result on all OS-es.

**[Actual results]:**
 - On Windows 10 x64 - First press scrolls the screenshot, but the second one wrongly tries to focus the text annotation.
 - On Arch Linux - Same behavior as on Windows.
 - On Mac 10.13.5 - Each key press just scrolls the screenshot. 
 
 **[Notes]:**
 - This issue is also reproducible with the "Page up" key.
 - Attached a screen recording with the issue:

![rec of the issue - page down](https://user-images.githubusercontent.com/37875464/42825557-f0a94800-89ea-11e8-9f38-e399eb691262.gif)

**Comment by punamdahiya** [comment]
This issue should be fixed with merge of #4658 in master

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux.
