### ISSUE TITLE
[Annotations] [Texttool] Use text input instead of a contenteditable div

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4658]
Refactor to switch from contenteditable div to input text to help fix issues open around page up/down/ text caret placement/undo/long strings 
#4646 
#4642 
#4632
#4655 
#4654 
#4653
#4652

**Comment by punamdahiya** [comment]
this looks too promising :), assigning myself

**Comment by chenba** [comment]
👍
