### ISSUE TITLE
[Annotations] When dragging the text box part of the string is briefly selected

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4661]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.
 - Have a saved shot link.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Click the "Add text" button and type a text of at least 4 characters.
4. Move the text box to the left and then to the right.
5. Observe the behavior of the string inside the text box.

**[Expected result]:**
 - The string is unaffected.

**[Actual results]:**
 - Characters inside the text box are briefly selected while moving the text box.
 
 **[Notes]:**
 - On Mac 10.13.3 and Arch Linux this issue is only reproducible when dragging the text box up and down.
 - Depending on the speed with which the text box is dragged, the character below or above the move pointer remains selected.
 - This issue is not reproducible if you drag the text box up and down on Windows 10 x64.
 - Attached a screen recording of the issue:

![rec of the issue - text select](https://user-images.githubusercontent.com/37875464/42878620-5d8cab96-8a96-11e8-9b8c-7b24d29b3f53.gif)

**Comment by johngruen** [comment]
add -moz-user-select: none to all children of draggable while dragging

**Comment by Softvision-AndreeaCupsa** [comment]
This issue was fixed by this PR #4660 and is no longer reproducible using the latest Firefox Screenshots dev and stage version , on latest Nightly build 63.0a1. Verified on Windows 10 x64, Mac 10.13.3 and Arch Linux.
Considering this I will close this issue.
