### ISSUE TITLE
[Annotations] The "Color Picker" and "Cancel" buttons are not visibly focused when using keyboard navigation

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4663]
[Affected versions]:
- Dev Edition Version 62.0b9
- Nightly Version 63.0a1
- Screenshots 33.1.0 dev version

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" boolean pref is set to "false".
- Have the latest Firefox Screenshots v33.1.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved screenshot.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the saved shot's page and click the "Edit this image" button.
3. Cycle through the buttons using the "Tab" key and observe the behavior.

[Expected result]:
- All the Menu buttons have a pressed state when selected with the "Tab" key.

[Actual result]:
- The "Color Picker" and the "Cancel" buttons do not have pressed state.

[Notes]:
- This issue occurs on the Color Picker from the Text tool as well.
- I have attached a screen recording of the issue:
![pressed](https://user-images.githubusercontent.com/40393891/42885467-b1385d68-8aa9-11e8-911e-14c0bd05d930.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and the issue is no longer reproducible.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
