### ISSUE TITLE
Sign dev/stage built XPIs with Autograph

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4665]
To ensure the `mozillaAddons` permission is not stripped out of our dev and stage builds, we can set up Autograph signing for Circle-CI.

Autograph docs on XPI signing: https://github.com/mozilla-services/autograph/blob/master/signer/xpi/README.rst

**Comment by 6a68** [comment]
Related to #4586

**Comment by 6a68** [comment]
g-k has a solution! https://bugzilla.mozilla.org/show_bug.cgi?id=1476778

Still needs to be deployed on the autograph side.

We'll just need to have circle-CI submit the XPI to autograph via curl; see comment 1 of the linked BMO bug for the analogous approach used by Notes to sign its APK.

**Comment by 6a68** [comment]
Autograph side is deployed, and the $AUTOGRAPH_EDGE_TOKEN is configured in Circle-CI. Working on our part.

**Comment by chenba** [comment]
Just tried the addon on dev; didn't seem to work. 🙁
