### ISSUE TITLE
Add alt text to images

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4667]
Add alt text to images, both on the shot page, and the my shots page.

Really easy solution: "Screenshot image"

Nicer solution: insert text visible in the image, whether via OCR, or via DOM capture at creation time

**Comment by punamdahiya** [comment]
Let's fix this issue with UI updates on shot and my shot page in #4686, #4685

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
