### ISSUE TITLE
Critical: Shot rendering on Chrome/Safari

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4672]
<img width="1269" alt="screen shot 2018-07-19 at 1 08 58 pm" src="https://user-images.githubusercontent.com/3323249/42939159-00d30e94-8b55-11e8-998e-8b87f4662313.png">

![screen shot 2018-07-19 at 1 09 01 pm](https://user-images.githubusercontent.com/3323249/42939207-251dd77a-8b55-11e8-818a-429939c58105.png)

<img width="1122" alt="screen shot 2018-07-19 at 1 09 03 pm" src="https://user-images.githubusercontent.com/3323249/42939161-0103fdb0-8b55-11e8-9dde-1373207db8e1.png">

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas can you verify this on stage?

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be ok on Mac OS for both Safari and Chrome, here is a [link](https://screenshots.stage.mozaws.net/HOPkUOz1oVmhgFPu/twitter.com) to test it too.

Also, here are some screenshots form my iMac.

![screen shot 2018-07-19 at 18 57 02](https://user-images.githubusercontent.com/17258026/42954623-e1d7c620-8b85-11e8-82d5-b9594c1bb666.png)

![screen shot 2018-07-19 at 18 57 34](https://user-images.githubusercontent.com/17258026/42954690-ea5b5e7e-8b85-11e8-87ed-2f0fd2630aa7.png)

**Comment by 6a68** [comment]
I uploaded a screenshot to the staging server, opened the staging URL in Chrome on Win 10, and the image is not stretched. Between this and the mac confirmation above, I think we're good here.

Closing.
