### ISSUE TITLE
[Annotations] The text tool is not placed in the middle of the visible area when the browser's width is narrow

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4673]
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites in fullscreen mode.
2. Navigate to https://wikipedia.org and click the "Screenshots" icon.
3. Click the "Save visible" button and then the "Save" button.
4. Resize the browser to be at 1/3 of its width.
5. Click the "Edit this image" button. 
6. Click the "Add text" button and observe the shot.

**[Expected result]:**
 - The text box is placed in the middle of the visible area.

**[Actual results]:**
 - The text box is placed in the middle of the shot, moving the scroll location in the process.
 
 **[Notes]:**
 - If have the browser on fullscreen and you scroll down on a long shot and click the "Add text" button, the text box is placed in the middle of the visible area.
 - Attached a screen recording of the issue:

![rec of the issue - text box](https://user-images.githubusercontent.com/37875464/42939703-6720bfde-8b5f-11e8-96ed-34366cfc2467.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
