### ISSUE TITLE
[Annotations][Enhancement] Users should be able to choose where to put the text box instead of it being automatically placed

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#4674]
**[Notes]:**
- The text box is automatically placed in the middle of the shot when the "Add text" button is clicked, and it might be hard to spot for new users.
- Instead of having the user move the text in the area they want it, they should be able to place the text box where they want from the beginning.

**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.
 - Have a shot saved.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to the saved shot. 
2. Click on "Edit this image" button.
3. Click the "Add text" button and observe the behavior. 

**[Expected result]:**
 - The mouse cursor changes into the text selector and the user can choose the area where to place the text box.

**[Actual results]:**
- The text box is automatically placed in the middle of the shot.
 
 **[Addtitional notes]:**
 - Attached a screen recording with the issue:

![rec of the issue 2](https://user-images.githubusercontent.com/37875464/42940926-b88bc2e8-8b63-11e8-8d69-09b8854f2801.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
