### ISSUE TITLE
[Annotations] Undo/Redo Causes Blurriness on Some Shots

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4678]
#### STR

1. Go to mozilla.org
1. Take a selection shot of the image used for "IRL season 3: The grand bargain" (see below)
1. Go shot page
1. Open editor and add a stroke from the highlighter or pen tool
1. Click undo

This is the image mentioned in step 2:
![image](https://user-images.githubusercontent.com/198055/42982639-d2f14222-8ba7-11e8-84be-c18ffe5be8c0.png)

#### Expected

Successfully undo without any errors or negative effects

#### Actual

The rectangular area containing the stroke from step 4 is blurry.  Additional undo/redos will make the are even more blurry.

**Comment by chenba** [comment]
QA: the easiest way to test this that I know of is to do selection shots on mozilla.org.  Whatever theme it is using produces a lot of elements with decimal width and height.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots 33.2.0 dev version and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04.
