### ISSUE TITLE
[Enhancement] Disable right click mouse events in Screenshot's edit mode

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-services/screenshots#4679]
[Notes]:
- If you click the "View Image" option a gray image is displayed.
- If you click the "Save Image As..." option a black image is saved.
- The "Select All" option enables the "Copy" and "View Selection Source" options.
- The "Copy" option does not work at all and the "View Selection Source" works as expected.
- If you click the Take a screenshot" option you encounter bug #4675
- The "Inspect element" option is the only one that works as expected.
- Considering the fact that the majority of the options are not working at all and the ones that are working correctly do not really help the user, in my opinion the right click mouse events should be disabled in the Screenshots "edit this image" mode.

[Affected versions]:
- Dev Edition Version 62.0b9
- Nightly Version 63.0a1
- Screenshots 33.1.0 dev version

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.install.requireBuiltInCerts" boolean pref is set to "false".
- Have the latest Firefox Screenshots v33.1.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.
- Have a saved screenshot.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the saved shot's page and click the "Edit this image" button.
3. Right-click the screenshot and observe the behavior.

[Expected result]:
- Nothing happens.

[Actual result]:
- A context menu is opened.

[Notes]:
- Attached a screen recording of the issue:
![enh context menu](https://user-images.githubusercontent.com/40393891/42995491-b130459e-8c19-11e8-872a-71419cc11ab1.gif)

**Comment by ianb** [comment]
This kind of context menu issue is common across the web – the browser is just doing its best job, and it doesn't always work. Including on our own site ;)
