### ISSUE TITLE
[Annotations] Text width should not extend beyond 5px inside canvas

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4680]
After playing with the canvas, i think we need to adjust the max string length so that text input cannot exceed the width of the canvas - 10px (5 on each side)

Now there's an edge case where the user could type longer strings with a small font and then resize, but i think that's OK

**Comment by punamdahiya** [comment]
Updating title of the bug to reflect description of the bug that is Text input width should not be extend  beyond 5px inside canvas
