### ISSUE TITLE
[FxA] Implement Sign in From Site Homepage

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4683]
Spec is available here: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/home

Header is the important bit as is the ability to be able to sign in via FXA

**Comment by 6a68** [comment]
Tasks:
- sign in from header instead of settings page
- sign out still on the settings page?
- redirect code may need to be updated to return to the right spot

**Comment by punamdahiya** [comment]
This seems a good bug to familiarize with existing FxA implementation, assigning myself

**Comment by punamdahiya** [comment]
Are there plans to have screenshots checkbox on about:preferences page about:preferences?entrypoint=menupanel#sync 

or server hosted services doesn't need one?

**Comment by punamdahiya** [comment]
We are using dev hosted server https://github.com/mozilla-services/screenshots/blob/master/server/src/config.js#L74,  we might need one for stage. 

For production /api/fxa-oauth/login call will have support from https://accounts.firefox.com/signin?service=sync. Is that correct?

**Comment by chenba** [comment]
> redirect code may need to be updated to return to the right spot

We definitely should do this.  Users can log in from any page with the new UI, so they should return to the page from where the auth request was initiated.

**Comment by punamdahiya** [comment]
@chenba +1 , thinking of writing a component for signin that
a) toggles text 'Sign In' or 'Setting' based off user FxA authentication state
b) Has page URL as one of SignIn component attribute. For SignIn flow, URL value will be passed to middleware and will be used to redirect user back to respective  page once the user is authenticated.
https://github.com/mozilla-services/screenshots/blob/master/server/src/server.js#L1115
c) Click of Settings will take user to settings page. Signout will be done from settings page by clicking on Disconnect and can redirect user back to home page.
https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/settings/controller.js#L23
