### ISSUE TITLE
[FxA] Implement common marketing view (also in header)

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4684]
Looking at the [new spec](
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/), there's a common component used as an advertising banner across all pages. In some cases it has a little 🥕 pointing to the sign in button. 

Refer to Shot View, My Shots and Home Page specs

It should accept arbitrary text and inline elements as children.

**Comment by youwenliang** [comment]
I tried a different color for the banner here (because the blue background and white text is not that readable and reminds me of Windows blue screen...)

![image](https://user-images.githubusercontent.com/8919308/45471695-76a5f380-b764-11e8-98f0-549cd3ed60ac.png)

https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_Banner

**Comment by johngruen** [comment]
@punamdahiya I think this spec works... seems simple enough to just wrap the text?

**Comment by punamdahiya** [comment]
Looks good, assigning it to myself

**Comment by punamdahiya** [comment]
Few clarifications as per initial specs
- Advertising banner will be always visible for owners on shot page, myshots and homepage in non authenticated state, with strings as ‘Sign in or sign up to sync shots across devices, save your favorite shots forever.’ ( Final string TBD)
- Advertising banner will be always visible on for non-owners on shot page with string as ‘Screenshots made simple. Take, save, and share screenshots without leaving Firefox.   Get Firefox now.’ ( Final string TBD)

Display of banner should be configurable via variable  enableUpsellBanner

**Comment by punamdahiya** [comment]
> https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_Banner
@youwenliang Can you please provide firefox icon svg file used in banner. Thanks!

**Comment by punamdahiya** [comment]
@johngruen In initial specs Advertising banner with string as ‘Screenshots made simple. Take, save, and share screenshots without leaving Firefox. Get Firefox now.’ is only shown for non-owners and non-firefox users. This will replace existing message we show on shot page to non-firefox users.  Is that correct?

**Comment by punamdahiya** [comment]
@youwenliang PR uses https://github.com/mozilla-services/screenshots/blob/master/static/img/landing-small-firefox-logo%402x.png as logog in banner which is 114 x 118, it will be good to get exact size asset. Thanks

**Comment by youwenliang** [comment]
@punamdahiya 
I upload the svg firefox icon I used here: (24 x 24)
https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/FxA_Banner/assets/firefox_svg.svg
