### ISSUE TITLE
[FxA] Implement Common Header Component for All Site UI

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4685]
Looking at the [new spec](https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/), there's a common component used as at site header/nav. We should implement while migrating to FxA

Refer to Shot View, My Shots and Home Page specs

**Comment by punamdahiya** [comment]
Assets linked to https://github.com/mozilla-services/screenshots/issues/4760
