### ISSUE TITLE
[FxA][Meta] Implement new Shot Page UI

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4686]
We should update the Shot Page UI to make it clear to users that our service has changed.

https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/shot

**Comment by 6a68** [comment]
Tasks:
- add favorite, copy, sign in buttons
- figure out how to do l10n to abbreviate button labels to avoid breaking design (e.g. in German maybe), talk to flod
- add upsell to top of page for non-owners
- CSS changes

**Comment by punamdahiya** [comment]
Assets linked to https://github.com/mozilla-services/screenshots/issues/4760

**Comment by punamdahiya** [comment]
@johngruen quick clarification copy icon in attached spec is for copying image to clipboard?

**Comment by chenba** [comment]
Filed #4776 for the copy feature.

**Comment by chenba** [comment]
Since @punamdahiya is actively working on #4685, let's wait on this so we can make use of the layout/component from that issue.

**Comment by punamdahiya** [comment]
Filed #4844 to implement share button

**Comment by punamdahiya** [comment]
Filed #4845 to update shot page content UI

**Comment by punamdahiya** [comment]
Shot Page header is updated with fix of #4685 except below features
- Share button #4844
- Copy button #4776
- Upsell #4684 
- Expiration Info #4825
