### ISSUE TITLE
[FxA] Bring back entity extraction for FxA users

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4689]
I made a rough spec for how this could work...this will need sec review etc.

https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/shot-advanced

**Comment by chenba** [comment]
Note that the addon has zero awareness of FxA at the moment.  We'll need to add that in order to have FxA only features in the addon.

**Comment by chenba** [comment]
Hey @johngruen, questions for ya:

1. In the Product Brief this is marked as a stretch feature (feature item #6).  Should we move this issue out of the current sprint?  Give it a P2?  Or something?
1. If we keep entity extraction only on the addon side, but require FxA, that would mean a user's shots taken before authenticating with FxA will not have the shot text content after the user logged in.  (It also applies to all shots taken before the addon release with entity extraction.)  Should we add something to the UI to make that clear?  It might be confusing to have some shots with entity extraction and some without.

**Comment by youwenliang** [comment]
Put some ideas here, might need to think about how to inform users who haven't sign in about this feature.

![4689 - entity extraction](https://user-images.githubusercontent.com/8919308/46186883-8c461c00-c313-11e8-9b65-52357efb76cc.png)
![4689 - entity extraction panel](https://user-images.githubusercontent.com/8919308/46186961-df1fd380-c313-11e8-8361-c4d17c6fd257.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
