### ISSUE TITLE
[Annotations] The text caret is not displayed at the end of the pasted string if the text box was previously placed at the image's margin

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4703]
[Affected versions]:
- Nightly 63.0a1
- Release 61.0.1 Unbranded

[Affected Platforms]:
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.2.0dev installed.
- Have a saved shot link.
- Have a string copied to the clipboard.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button and move the text box to one of the image's margin.
3. Right click the text box and select the "Paste" context menu option.
4. Observe the behavior.

[Expected result]:
- The string is pasted in the text box and the text caret is displayed at its end.

[Actual result]:
- The string is pasted in the text box but the text caret is not displayed.

[Notes]:
- This issue is also reproducible if you paste a string that exceeds the image's margin.
- On Linux, this issue is also reproducible if you type a long string that exceeds the image's margin.
- This issue is not reproducible on Windows OSes.
- Here is a screen recording with this issue: https://goo.gl/GamS2B

**Comment by punamdahiya** [comment]
The issue should be resolved with fix of #4680. Please validate. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots 33.2.0 dev version and it's no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04.
