### ISSUE TITLE
[bug 1478028] replace nsp with npm audit

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#4704]
nsp is deprecated and shutting down: https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

Should allow us to close https://github.com/mozilla-services/screenshots/issues/4324 and with `npm audit fix` make updating transitive dependencies for https://github.com/mozilla-services/screenshots/pull/4617 too.

e.g. https://github.com/mozilla-services/ip-reputation-js-client/blob/78d76c26f412ffddb920a4a8250a1141c24861d7/.travis.yml#L13-L15

**Comment by 6a68** [comment]
Unfortunately, `npm audit` does not cleanly replace `nsp`, as there's no way for `npm audit` to conditionally ignore specific vulnerabilities in transitive dependencies; see https://github.com/npm/npm/issues/20565.

It looks like FxA is currently [hacking around](https://github.com/mozilla/fxa-auth-server/pull/2530) this limitation via "npm audit || true" in their CI builds.

We've discussed this a bit, and current consensus would be to warn on `npm audit` errors in the dev build, but fail on such errors in the stage build, to prevent deploying insecure code to production.

**Comment by g-k** [comment]
That's frustrating. I was hoping `npm audit fix` would work for everything screenshots pulls in. 

If we have github (and sentry if you're using it) vulnerability alerts enabled, swapping `npm audit || true` would be fine.

Also if you want automatic PRs, @hwine can enable dependabot https://dependabot.com/blog/automatically-respond-to-security-advisories for JS.  It looks like it's pulling the github NVD and from the node security working group https://github.com/nodejs/security-wg

**Comment by ianb** [comment]
I've created  #4803 as a followup about `npm audit || true`. Otherwise this was fixed in #4617 (in a5935e1ea126007c22c68fb9bf7908f62111c8ab)
