### ISSUE TITLE
Set NODE_ENV to "dev" in Docker Images for dev

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4707]
I pulled down the latest Docker image yesterday, echoed out NODE_ENV, and received "production".  It should be "dev".  `release-version` already export NODE_ENV to "dev" before calling `build-docker-image`, but it's not working?

**Comment by ianb** [comment]
I think it makes sense to keep this as production, and use "dev" for our local servers where we are actually developing the server. So we'll leave this as it is.
