### ISSUE TITLE
My Shots Should Not Show Blocked Shots

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4721]
It looks broken because the server won't serve image data of block shots.

**Comment by chenba** [comment]
Follow-up to #4717

**Comment by 6a68** [comment]
Might be good to audit the watchdog code to make sure there's some debug- level logging for cases where a shot is not blocked, and warn- level logging for cases where a shot is blocked.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
