### ISSUE TITLE
Temporisation

### ISSUE THREAD

**Issue by InfoLibre** [mozilla-services/screenshots#4722]
Could you add a temporisation (x seconds) in next version ?

**Comment by ianb** [comment]
I'm not exactly sure what you are asking for? Like a very short expiration time? Or you want to know the exact creation date?

**Comment by Petrouchka** [comment]
A delay between clicking on the screenshot icon and taking the screenshot. It's useful for taking a screenshot of menu, forms... in a web page. Like this :
![capture du 2018-08-01 07-27-49](https://user-images.githubusercontent.com/3955499/43502707-6d8f38c6-955c-11e8-97fe-887959d8efcc.png)

**Comment by Petrouchka** [comment]
It's technically impossible to do it as Greenshot do ?

**Comment by ianb** [comment]
There are other ways to take screenshots that would make it possible, but Firefox Screenshots doesn't use that approach – we get our image from the Firefox rendering system, not from the operating system.

**Comment by Petrouchka** [comment]
I understood that Firefox Screenshots woks only in the navigator. But I was asking me if it was possible to have the time to open a list in a form in a web page before capturing the page or thinks like this.
