### ISSUE TITLE
[FxA] Limit Favorite Shots to 100

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4723]
Per https://docs.google.com/document/d/1lyY9V-ff-4qFYboQawjtay-AAgZUPjiFLYYnu0LlRVc/edit#heading=h.b012ntepyb1

Follow up to #4688

**Comment by 6a68** [comment]
This service uses S3 for storage; it's really cheap to store shots indefinitely.

Putting a limit on the number of uploads seems like it'll penalize our most passionate users for no clear reason. Maybe we can send them a (virtual) cake instead at 100 or 1000 uploads 🎂🎉

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
