### ISSUE TITLE
Put in a popup promotion for the editing tools

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4724]
Would be a simple popup dialog, that would show to people once (twice?) to tell them about this new/improved feature.

We could use the same React component we use to invite people to use Firefox. Or we can use the component used for the share dialog. We can use localStorage to track who has seen the popup before.

@clouserw is going to ask about text/copy. We should get some text in soon so we can get it to translators.

**Comment by punamdahiya** [comment]
promo visual https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Cross-promotional/

**Comment by punamdahiya** [comment]
@sevaan Need UX feedback on showing edit tool new features promotion dialog as per specs in comment above

![screenshot_2018-07-31 firefox screenshots](https://user-images.githubusercontent.com/597734/43496510-99cba93e-94f2-11e8-9c0d-3971e1776012.png)

**Comment by sevaan** [comment]
LGTM. Does mousing over it show the close x?

Also, re: the text, I think the title should be plural: New Edit Tools!

And a period or exclamation point after "support".

**Comment by clouserw** [comment]
Thanks.  Michelle is pondering some new copy for us by this Friday.

**Comment by 6a68** [comment]
Hmm. It seems like we should have some kind of caret pointing at the button we want people to click. The image there is just a box floating in space.

I think an 'x' to close the doorhanger makes more sense than clicking anywhere to dismiss it.

**Comment by 6a68** [comment]
Although I guess the share card doesn't have a caret. Maybe we could highlight the button and display the CTA just underneath it? Something like this:

<img width="1247" alt="screen shot 2018-08-01 at 2 29 44 pm" src="https://user-images.githubusercontent.com/96396/43550102-68a79322-9597-11e8-9cb2-5203b510e855.png">

**Comment by punamdahiya** [comment]
LGTM! 'Give it a try' can be a link as well and takes user to edit screen

**Comment by sevaan** [comment]
That's really great, @6a68!

**Comment by 6a68** [comment]
thanks! :beers:

**Comment by clouserw** [comment]
From Michelle:

> Here's my recommendation.
> Take Note!
> Updated editing tools let you crop, highlight, and even add text to your shot.
> 
> Am suggesting that you sell the whole feature and give a bit of emphasis to what's new. 1. New users may benefit from the whole story. 2. Existing users might not know or remember what's already there. 2. It's better to be specific about what it offers than just saying something is new - this gives people even more reason to explore the feature. 

Which looks great to me.

**Comment by punamdahiya** [comment]
Screenshot with new copy from Michelle, updated PR with the changes
![screenshot-promo-new-text](https://user-images.githubusercontent.com/597734/43793418-5b5a6c2e-9a30-11e8-8d30-94db2877b083.png)

**Comment by punamdahiya** [comment]
Screen shot with option is to use text title 'Take Note!' in case it's preferred
![screenshot-text-title](https://user-images.githubusercontent.com/597734/43793489-95131a56-9a30-11e8-9635-d14af79ca234.png)

**Comment by johngruen** [comment]
I like the second version... can we ditch the circle around the X?

**Comment by punamdahiya** [comment]
Done
![screenshot-promo-final](https://user-images.githubusercontent.com/597734/43794489-4a3c4bbc-9a33-11e8-9829-070eacdcd0dd.png)

**Comment by johngruen** [comment]
SHIPIT
