### ISSUE TITLE
The Address bar, Search bar and toolbar buttons stop working if you move the "Creating..." tab to a new window

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#4730]
[Affected versions]:
- Nightly 63.0a1
- Firefox Release 61.0.1
- Screenshots 33.0.0 production
- Screenshots 33.2.2614 dev

[Affected Platforms]:
- All Windows
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to a website.
2. Save a shot and quickly drag the newly opened tab to a new window (or outside the current window) without releasing the mouse.
3. Wait for the shot to load and release the mouse.
4. Click the Address bar and observe the behavior.

[Expected result]:
- The bar is focused.

[Actual results]:
- Nothing happens.

[Notes]:
- All toolbar buttons except the Home and Downloads buttons are affected by this issue.
- The only way to regain mouse control over the Address bar or the Search bar is to restart the browser.
- Keyboard navigation is not affected by this issue. You can still focus the Address bar or Search bar this way.
- I was unable to reproduce the issue on Mac. 
- Here is a screen recording with the issue:
![address bar and search bar can no longer be focused with the mouse after moving a shot that is loading in a new window](https://user-images.githubusercontent.com/18304511/43587722-8b74c92e-9673-11e8-8ed4-1da5c5417bde.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
Dupped in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1480685.

**Comment by johngruen** [comment]
We think this is upstream. WONTFIX.
