### ISSUE TITLE
Restore subtitle link favicon

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4740]
Follow up of issue #4738 

Fix involves
- Put favicon back as base64 images https://github.com/mozilla-services/screenshots/pull/3319#issuecomment-321872946
- 
- Hide favicon if proxy endpoint is url and not functional e.g.  https://screenshots.firefoxusercontent.com/proxy?url=https%3A%2F%2Fwww.mozilla.org%2Fmedia%2Fimg%2Ffirefox%2Ffavicon.e6bb0e59df3d.ico&sig=3tqcvOHWEFcIeEj3Jo51eHJ6R08

**Comment by chenba** [comment]
WONTFIX
