### ISSUE TITLE
color option in new text tool does not work

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-services/screenshots#4741]
The color option in the new text tool does not work at all. The text is always black.

<img width="924" alt="bildschirmfoto 2018-08-04 um 23 24 22" src="https://user-images.githubusercontent.com/1100614/43680546-92128bc4-983d-11e8-80a5-e6f41fc9f83a.png">

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on latest Firefox (61.0.1) release and also latest Nightly (63.0a1) build.

[Stepst to reproduce]:
1. Open the latest Firefox release and navigate to "about:preferences" page.
2. Click the "Choose" button from the "Language and Apperance" section.
3. Add the "German [de]" language on the first position and click the "OK"button.
4. Navigate to any website and save a selection.
5. Click the "Edit this image" button.
6. Click the "Add Text" button.
7. Change the color of the text and observe the behavior.

[Expected Results]:
- The color is correctly applied.

[Actual Results]:
- The color is not applied.

[Notes]:
- Here is a screen recording of the issue:
![color picker 3](https://user-images.githubusercontent.com/19226534/43728632-5677fdca-99ae-11e8-9bfa-f3e3fba8e0c4.gif)

**Comment by punamdahiya** [comment]
color picker CSS is picking colorName from title attribute which gets localized and doesn't work for languages other than en. Will submit fix to pick colorName from a new dataset attribute inside color-picker

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (34.0.0) dev version and it's no longer reproducible. Tested on Windows 10 x64, Windows 7 x64, Mac 10.13 and Arch Linux.
