### ISSUE TITLE
Track channel and user agent in logins

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4748]
We want to distinguish pre-release users (i.e., Nightly and Beta users) from release Firefox users. Right now we're not saving enough in the device table to know the difference.

If we can get the channel information and add it to the login/register call that should be sufficient. Getting the User-Agent wouldn't be as helpful, as you have to match up dates to determine the channel based on the User-Agent. But we could consider User-Agent, as it could be done server-only.

We might want to consider copying the channel information to the shot (data) table on shot creation, so we track which channel the user was using at the moment they uploaded.

**Comment by chenba** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1386076

**Comment by chenba** [comment]
If we can access prefs with an experiment, which is currently discussed in https://github.com/mozilla-services/screenshots/issues/4800, then we can grab the channel from the prefs as well.

**Comment by ianb** [comment]
It might be easiest to just use release JSON files on the server: https://wiki.mozilla.org/Release_Management/Product_details

Specifically [this file](https://product-details.mozilla.org/1.0/firefox_history_major_releases.json) will identify when we should start treating a version as a production release, and [this file](https://product-details.mozilla.org/1.0/firefox_versions.json) gives some additional information. My only concern here is that if the file isn't updated very promptly (or ahead of a release) we might be unaware of a version update.

**Comment by clouserw** [comment]
Getting channel from the add-on could be a stretch/enhancement.  Grabbing the product details seems easiest and most likely to get done this quarter.  We need to get the channel stuff hooked up to finish the Watchdog integration which we're on the hook for this quarter.

**Comment by chenba** [comment]
`AppConstants.MOZ_UPDATE_CHANNEL` is available through an experiment API (https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/experiments/screenshots/api.js#L29).  Are not we not using that because we want to do everything server side?

**Comment by 6a68** [comment]
That API will be available as of Firefox 64, which hits release in December 2018.
