### ISSUE TITLE
Screenshots disabled on Citibank web page after login

### ISSUE THREAD

**Issue by mavink** [mozilla-services/screenshots#4751]
Error says "This isnt a standard webpage so you cant take a screenshot of it" Even fireshot is prevented from taking a screenshot of this page. Why this strange behavior?

https://www.citibank.co.in/infojsp/launch.jsp

**Comment by mavink** [comment]
Even Happy right click is disabled on this page. Tampermonkey however seems to work... Is there a list of sites on which extensions are disabled?

**Comment by johngruen** [comment]
We think there might be a `frameset` tag on this page which we do not support unfortunately. Would you be able to inspect the page to verify?

**Comment by mavink** [comment]
Yes there is a frameset tag. Do you plan to support it? Or does the new webextension model prevent you from ever being able to support it? Do you know of any workarounds?  
If this information becomes more and more public, more and more of silly website designers will start using this option to disable screenshots.

**Comment by mavink** [comment]
How does Tampermonkey manage to get through?

**Comment by johngruen** [comment]
I don't know about tampermonkey, we have no immediate plans to support frameset sites unfortunately. Sorry about that!
