### ISSUE TITLE
[annotations] Add an Arrows tool

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/screenshots#4756]
This was a user request.  It's not on the mockups, but if it is wanted, it would be similar to the other tools.  That is:

Specs: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/Advanced_Annotations/

Assets: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/annotation/Advanced_Annotations

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
