### ISSUE TITLE
[Annotations][Text Tool] The "Confirm" and "Cancel" buttons are not localized 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4757]
[Affected versions]:
- Firefox Release 61.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a German Firefox build installed or extracted.

[Steps to reproduce]:
1. Open latest Firefox browser with the profile from prerequisites and navigate to any website.
2. Perform a selection on the page and save it.
3. Click the "Edit this image" button.
4. Click the "Add Text" button and observe the "Confirm" and "Cancel" buttons.  

[Expected result]:
- The "Confirm" and "Cancel" buttons are translated in German.

[Actual result]:
- The "Confirm" and "Cancel" buttons are displayed in English.

[Notes]:
- However, the tooltip for the "Cancel" and "Confirm" buttons is correctly localized.
- Here is a screenshot with the issue:
![confirm and cancel](https://user-images.githubusercontent.com/19226534/43898319-256b84e6-9be7-11e8-9b73-b1a1649cb97c.png)

**Comment by johngruen** [comment]
Has PR

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (34.0.0) dev version and it is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
