### ISSUE TITLE
[FXA] Assets for new shot page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4760]
@punamdahiya here are all the SVGs i used for in my spec: [link](https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/NEW_FxA_Integration/images)

**Comment by johngruen** [comment]
@punamdahiya can you just close this once we confirm you have everything you need?

**Comment by punamdahiya** [comment]
Looks good. Thanks!
