### ISSUE TITLE
Need to screenshot about:support

### ISSUE THREAD

**Issue by abitrolly** [mozilla-services/screenshots#4763]
PR #2368 disabled screenshots for `about:support` and now with `pastebin.mozilla.org` getting decommissioned there is no way to easily share Firefox info for certain machines. Screenshot for this page could help a lot.

**Comment by johngruen** [comment]
We're gonna close this and file separately for screenshotting arbitrary about pages. Thanks!

**Comment by 6a68** [comment]
@abitrolly Note that the about:support page already has a 'copy text to clipboard' button, which is the better option when submitting bug reports.

**Comment by abitrolly** [comment]
@6a68 that text format is almost unreadable, and I need it something people can skim over for asking this question https://ask.fedoraproject.org/en/question/125175/how-to-check-that-firefox-uses-hardware-gpu-acceleration/

@johngruen I'd be happy to subscribe for updates if you get the issue number. ;)
