### ISSUE TITLE
[Watchdog] Add Release Channels Configuration

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4770]
Add a configuration that would allow Screenshots to submit shots based on the shots' release channels.  This issue depends on #4748.

**Comment by chenba** [comment]
@clouserw FYI in case you aren't aware of it: there's already a configuration in Screenshots server for throttling traffic to Watchdog.  It serves a similar purpose to this issue.

**Comment by clouserw** [comment]
a general throttling could still be useful as we scale up, but legal signed off on the nightly/beta channel testing first while they review legal docs
