### ISSUE TITLE
Allow FxA users to save and share full original URLs of shots

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4774]
Update add-on to save original URLSs to allow FxA users to save and share full original URLs of shots.

**Comment by 6a68** [comment]
We removed full URLs for legal/privacy reasons. Changing this will require working with those teams

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
