### ISSUE TITLE
Add server version

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4775]
We are now going to allow ESR to upload shots. Let's figure out how to ensure that ESR will always work (are system addons updated in ESR?).

There are many options to consider when decoupling server and client via a version number. We should identify the potential needs / use cases before jumping to implementation. 

Related to #4772

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
