### ISSUE TITLE
[FxA] Add "Copy" to Shot Page

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4776]
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/shot shows a "Copy" button.  This feature does not exist currently.

Is it copy URL or copy image?

**Comment by chenba** [comment]
Copy URL is currently in the share panel.  The copy icon in the UI spec is the same one that's for copying a shot to the clipboard in the addon.  @johngruen feel free to close this issue if "Copy" in this case mean copying the shot url.

**Comment by chenba** [comment]
Check share panel usage and potentially change to two copy buttons.

**Comment by chenba** [comment]
A copy shot image to clipboard feature will be limited to Firefox since it'd need the addon to invoke https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData.

Aside from not having a Chrome extension at the point, https://developer.chrome.com/apps/clipboard is also for dev channel or ChromeOS apps only.

**Comment by 6a68** [comment]
Maybe this is an opportunity to upsell Firefox to Chrome users: if the browser doesn't support copying the image, show a disabled copy button with some kind of "If you were using Firefox, you could copy this image" popup on mouseover

**Comment by johngruen** [comment]
We should change this to copy shot

**Comment by chenba** [comment]
@johngruen A few questions:

1. The successful copy notification will be identical to the one triggered by copying in the addon shot UI.  Is that ok?
1. What should error messages look like?
1. What should we do with the copy button if the user's browser does not have the addon to copy to clipboard (Chrome, older version of the addon, etc.)?

Thanks!

**Comment by johngruen** [comment]
> 

> @johngruen A few questions:
> 
>     1. The successful copy notification will be identical to the one triggered by copying in the addon shot UI.  Is that ok?
> 
Yep

>     2. What should error messages look like?
> 
Is this going to be a major problem? How about just a push that says "Something went wrong" / "Unable to copy this shot to the clipboard." With the same ui as the normal push below: 

<img width="372" alt="screen shot 2018-09-18 at 12 26 01 pm" src="https://user-images.githubusercontent.com/3323249/45681562-189b5680-bb3e-11e8-86af-e4e4bc7a9ac3.png">


>     3. What should we do with the copy button if the user's browser does not have the addon to copy to clipboard (Chrome, older version of the addon, etc.)?
> 

Hide the button
