### ISSUE TITLE
Clean Up Old States from the States Table Periodically

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4777]
A state is created whenever someone initiates an FxA auth request.  Then it's deleted when the auth is successful.  The rest of the time, we've got states lingering about.  We should delete those old records.  We can be conservative: delete states that are 1+ week old?

**Comment by punamdahiya** [comment]
Either we or ops should setup a cron job to cleanup the states

**Comment by chenba** [comment]
We can add this to `jobs.js`.

**Comment by chenba** [comment]
This requires a migration to add a `created` timestamp column.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
