### ISSUE TITLE
[FxA] Update marketing banner strings

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4789]
We should update the colors and strings in this CTA. I will reach out to Michelle for guidance here.

**Comment by 6a68** [comment]
@johngruen I'm concerned that the string here talks about signing in to 'sync' shots across devices. We don't use the sync backend, and it seems like that could confuse users. Thoughts?

**Comment by johngruen** [comment]
Suggested this change here: https://github.com/mozilla-services/screenshots/pull/4910

**Comment by johngruen** [comment]
This can be closed when #4910 lands.

**Comment by punamdahiya** [comment]
With #4910 in master, this issue can be closed
