### ISSUE TITLE
[FxA] Non-FxA shot takers should be briefly onboarded

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4790]
This is underdefined in my spec at the moment. The first time a shooter sees the new shot UI, we should indicate that shots expire by default in two weeks, and that they can sign in to shave them forever or favorite them.

**Comment by youwenliang** [comment]
Quick ideas about the brief FxA onboarding:

If users access my shot page directly:
![4790-1](https://user-images.githubusercontent.com/8919308/45290271-cba5f780-b521-11e8-8a0c-bd7be32f49cc.png)

If users take a shot and enter shot detail view:
![4790](https://user-images.githubusercontent.com/8919308/45290273-cba5f780-b521-11e8-886b-fe2cadb013e4.png)

**Comment by johngruen** [comment]
When the user sees onboarding, hide the blue bar

**Comment by johngruen** [comment]
@youwenliang can you do a treatment for how this might look on mobile as well?

**Comment by youwenliang** [comment]
I've updated the measurement to include responsive view:
Measurements: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_Onboarding

**Comment by punamdahiya** [comment]
@youwenliang can you please attach link to screenshots icon used in on-boarding promo. Thanks!

**Comment by youwenliang** [comment]
@punamdahiya Here: https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/logo.svg
