### ISSUE TITLE
[FxA] Update Favorite button on shot page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4791]
This is under-defined in the spec on both the shot page and the my shots page. We need a better overall interaction pattern to indicate favorite-ing shots.

**Comment by youwenliang** [comment]
Some quick ideas here:
![UX](https://user-images.githubusercontent.com/8919308/44775599-95bf5580-aba8-11e8-9a6b-08ef3b7863fd.png)

**Comment by johngruen** [comment]
Looks good to me!

**Comment by youwenliang** [comment]
Measurements: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA-4791/
Icons: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/FxA-4791/assets

**Comment by johngruen** [comment]
@youwenliang when you add assets can you unassign yourself and remove needs UX label

**Comment by clouserw** [comment]
If a shot has been favorited and the user signs out on the Shot View:
- The shot is shown as favorited, but greyed out/disabled

**Comment by punamdahiya** [comment]
Thanks Wil. You did it right, I should have left this comment here https://github.com/mozilla-services/screenshots/issues/4878#issuecomment-422219085

**Comment by youwenliang** [comment]
I put all the toolbar icons here: (I made small adjustments to the stroke weight for some of the icons so that they look consistent)
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/Updated_Icons

**Comment by punamdahiya** [comment]
@youwenliang @johngruen Updated specs for 4791 shows disable Favorite icon on MyShots page. I propose on my shots page we keep favorite icon hidden [as proposed here.](https://github.com/mozilla-services/screenshots/issues/4791#issuecomment-416870115) for reasons below
a)  we should encourage user to sign in to see favorite shots.
b) Favorite icon on my shots is not clickable and could be confusing for users to show it disabled and not clickable even after SignIn

**Comment by youwenliang** [comment]
> @youwenliang @johngruen Updated specs for 4791 shows disable Favorite icon on MyShots page. I propose on my shots page we keep favorite icon hidden [as proposed here](https://github.com/mozilla-services/screenshots/issues/4791#issuecomment-416870115) for reasons below
> a) we should encourage user to sign in to see favorite shots.
> b) Favorite icon on my shots is not clickable and could be confusing for users to show it enabled and not clickable even after SignIn

@punamdahiya Just a quick thought, is it possible to make the fav icon in MyShots page clickable? This way I think showing the disabled favorite icon after signed out makes more sense.
