### ISSUE TITLE
[FxA] Audit and update homepage content for FxA release

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4792]
Need to make sure it all makes sense

**Comment by youwenliang** [comment]
@johngruen Any particular features  we want to highlight for the FxA release? This would help me sketch some ideas for this issue and #4793.

**Comment by youwenliang** [comment]
Highlighting the sync feature (WIP)
![image](https://user-images.githubusercontent.com/8919308/45348550-952fb180-b5e1-11e8-89cc-1aa05a46ba89.png)

**Comment by youwenliang** [comment]
Here are the images I created:
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_tour/

Assets here:
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/FxA_tour/assets

**Comment by punamdahiya** [comment]
@johngruen if above assets from Mark and content on homepage looks good, I can pick it next. Thanks

**Comment by johngruen** [comment]
Has A PR #4950
