### ISSUE TITLE
[FxA] Audit and update add-on onboarding content for FxA release 

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4793]

**Comment by 6a68** [comment]
@johngruen Should we make this a stretch acceptance criterion for Q3, or make the acceptance criteria "code written but not exported to Firefox"? We're pretty late in the quarter and don't have a spec yet.

**Comment by youwenliang** [comment]
Here are the images I created:
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_tour/

Assets here:
https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/FxA_tour/assets
