### ISSUE TITLE
API experiment to access Screenshots prefs

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4800]
Read values of existing Screenshots prefs via an API experiment.

Rather than tackle the complexity of #4773 and #2711 in the run-up to legacy removal in Firefox 64, it might make more sense to first access existing prefs via an API experiment, then handle migration later.

Refs #3875.

**Comment by ianb** [comment]
Example of a WebExperiment that gives access to prefs: https://github.com/mozilla/shield-studies-addon-utils/tree/87dd2e7150bce77fc78e732f3eb5d804841535d3/webExtensionApis/prefs

**Comment by ExE-Boss** [comment]
See also #4533
