### ISSUE TITLE
Upgrade to Node.js 10.x

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4804]
Node.js 10 will enter into LTS in October 2018.  We should consider upgrading then.  It would also give us NPM 6.x.

**Comment by chenba** [comment]
[This line](https://github.com/mozilla-services/screenshots/pull/4948/files#diff-1d37e48f9ceff6d8030570cd36286a61R66) can be removed once the CircleCI config is updated to use Node 10.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
