### ISSUE TITLE
Integrate Stage Screenshots with Stage Watchdog

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4813]
This is a meta bug for tracking the work required to get stage Screenshots working with stage Watchdog.

- [x] Deploy Watchdog on Stage
- [x] Generate client credentials for Screenshots (https://github.com/mozilla/watchdog-proxy/issues/162)
- [x] Add Watchdog related configs for stage Screenshots and (re)Deploy stage Screenshots (https://github.com/mozilla-services/cloudops-deployment/issues/2466)

**Comment by clouserw** [comment]
@chenba credentials are in Slack or I can give them to you

**Comment by chenba** [comment]
@clouserw Do you mean the user that was created for load testing?  Or is there a Screenshots specific one that I'm not aware of?

**Comment by chenba** [comment]
Opened https://github.com/mozilla-services/cloudops-deployment/pull/2482 to configure and enable Watchdog for stage Screenshots.

@oremj Please review ☝️ and deploy stage Screenshots if that PR looks ok.
