### ISSUE TITLE
[Watchdog] Enable Watchdog Integration on Prod

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4820]
Meta issue to keep track what need to be done in order integrate with Watchdog on prod.

- [ ] A Screenshots server deploy that contains the fix for #4799 and #4926
- [ ] Fix and deploy #4770 (this depends on #4748)
- [x] Add Watchdog related configs for prod Screenshots

**Comment by chenba** [comment]
Created https://github.com/mozilla-services/cloudops-deployment/issues/2589 for oremj.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
