### ISSUE TITLE
Replace keygrip with iron

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4840]
Keygrip has some long-dormant crypto issues. Iron is a maintained alternative suggested by security folks.

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1389708

**Comment by 6a68** [comment]
Ian notes that we'll have some migration issues to sort out with this change.

Maybe we can gradually migrate from keygrip to iron, considering old signatures case-by-case

**Comment by ianb** [comment]
Closing this in preference of doing #4882
