### ISSUE TITLE
Edit image toolbar doesn't make it clear that the highlighter will default to the colour black

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla-services/screenshots#4843]
Latest Nightly, Screenshot v33.0.0.

STR:

1. Upload a screenshot.
2. Click `Edit this image` button.
3. The editing toolbar looks like this:
![yellow highlight](https://user-images.githubusercontent.com/8336638/45137658-450eb480-b1c7-11e8-86b3-f7b6ecd311a4.png)
The Pen is the default tool, the Colour Picker is set to black and the Highlighter button is a nice inviting yellow. Click the Highlighter. The Highlighter cursor has a yellow edge too.
4. Try to highlight something.

AR:
![gif](https://user-images.githubusercontent.com/8336638/45138388-d67f2600-b1c9-11e8-9fa9-2baea4d4e7ca.gif)
The "highlight" is black.
Then realised that (a) the small yellow lines, part of the Highlighter icon and the Highlighter cursor, are static; they don't reflect the colour of the actual highlight. (b) the colour picker applies to all the three tools preceding it in the toolbar.
The UI doesn't make either of these things clear.

ER:
Black, especially fully opaque, is not used for highlights. It makes no sense as the default colour of the highlighter.
Better UI to communicate what is the currently active colour. Snipping Tool changes the colour of the Pen cursor (a dot) to reflect the current colour. Paint does the same for the Brushes tool.
Better UI to communicate that the Colour Picker is global.

**Comment by chenba** [comment]
Related to #4233

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
