### ISSUE TITLE
[FxA]  Update Footer component

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4846]
Update Footer component as per new UI specs https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/my-shots

**Comment by chenba** [comment]
Note that there's a small bug with the current footer.  As a side effect of #4819 and the current auth check, the "Remove All Data" link is displayed to all Firefox users who visited more than one shot (or same shot more than once)--that is, has a user cookie--but have never created a shot.

I propose that we only show "Remove All Data" to the owner of the shot.

@johngruen ^ ?
