### ISSUE TITLE
[FxA] Display synced state in my shots page

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4847]
This comes from discussion in today's Screenshots daily meeting. Feel free to edit this description or add comments to capture additional details I might have missed.

If a user has uploaded shots from Firefox profiles A and B, and connects both A and B to the same Firefox Account, then visiting the My Shots page from either profile will show all shots from A and B.

We don't currently separate the shots from different profiles in any way in the My Shots page.

It's not clear if this will make sense to users in all cases. Cases like logging into FxA on a shared computer, uploading a shot, then logging out of FxA, show that users might reasonably expect their shots to be connected to the account itself, and not the particular device.

Some questions:

- What are the most important use cases?
- What are user expectations in those use cases?
- How do we need to change the Firefox Accounts implementation (UI and backing service code) to fit the use cases and user expectations?

**Comment by punamdahiya** [comment]
Decision here should influence content in #4870

**Comment by johngruen** [comment]
@youwenliang I think we're going to do the treatment where when a user logs out, their on-device shots remain...we should add a visual indicator to each card for shots that come from other devices indicating their origin. Note, we don't have like device device id or anything so maybe just make it visual with a tooltip that says "This shot came from another Firefox"

**Comment by youwenliang** [comment]
@johngruen is it possible to have different sections in my shot page instead of using indicators on shot cards?

Something like this:
![image](https://user-images.githubusercontent.com/8919308/45546518-17bda880-b850-11e8-94fe-503e0b7fd8b7.png)

**Comment by youwenliang** [comment]
A few ideas here:
![fxa screens my shots - sync](https://user-images.githubusercontent.com/8919308/45734292-9b8fe000-bc16-11e8-8e80-a9b70dc4047f.png)

**Comment by johngruen** [comment]
Yeah, let's go with 2!

**Comment by 6a68** [comment]
Updating the title, since this is now a bug about showing a synced-image icon on the my shots page
