### ISSUE TITLE
why Firefox Screenshots saved in jpg?

### ISSUE THREAD

**Issue by eniodefarias** [mozilla-services/screenshots#4860]
why Firefox Screenshots saved in jpg?
i need all screenshots in png format only.
how to do configure to all screenshots take in only png format?

**Comment by chenba** [comment]
@eniodefarias I've filed #4861 so I'm closing this issue.

**Comment by dtvn** [comment]
I found a way to save a FULL-only screenshot as PNG. Use the `Take a screenshot of entire page` in developer tool. It will always give us a best quality of screenshot.

**Comment by ggojedap** [comment]
> I found a way to save a FULL-only screenshot as PNG. Use the `Take a screenshot of entire page` in developer tool. It will always give us a best quality of screenshot.

yes @dtvn, your method works better, thanks!
