### ISSUE TITLE
Do Not Convert Shot to jpeg When Downloading or Copying to Clipboard

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4861]
This is in response to a user's query in #4860.  It should be okay to use PNG for downloaded/copied shots.

**Comment by chenba** [comment]
This is a duplicate of #3969.

**Comment by Darkmaster006** [comment]
Is there a way to solve this? I want to click 'Download' and have them download in PNG. Why is there not an option to control this? Thank you.
