### ISSUE TITLE
[FxA] Different text for FxA 'Sign In' button?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4870]
Could the FxA button label text, currently 'Sign In', be replaced with something about FxA or linking shots from other devices?

If you were on a website, and saw a button in the header labeled "Sign In", you'd naturally infer that you were currently logged out, and the content on the page was public. This, together with our unique auth system for Screenshots, might lead users to wonder if their shots are public, and seems likely to cause confusion.

**Comment by clouserw** [comment]
@ryanfeeley do you have preferred language for a sign in button?

**Comment by ryanfeeley** [comment]
@clouserw I lack the context to answer accurately. Can you get me up to speed on what screenshots is doing with fxa? Slack, email, vidyo, long cable car ride over the alps. Reach out!

**Comment by punamdahiya** [comment]
Link this to content issue #4789

**Comment by punamdahiya** [comment]
#4792

**Comment by johngruen** [comment]
I don't think any one or two word string is going to make this clear. I'd rather resolve this through #4790
