### ISSUE TITLE
[FxA] - Update Shot Page PromoPanel at smaller widths

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4874]
https://github.com/mozilla-services/screenshots/issues/4848#issuecomment-420498879

With new UI update shot page Promo Panel 
a) hide promo panel when we are displaying on-boarding dialog in #4790
b) For width < 1024, promo panel should be above Menu doorhanger. Star badge should be added to  menu icon  (will disappear when menu is open)

**Comment by punamdahiya** [comment]
It should be linked to smaller width bugs

**Comment by johngruen** [comment]
@punamdahiya does this need UX?

**Comment by punamdahiya** [comment]
@johngruen This issue was opened based off Menu doorhanger UX spec from Mark. We have revised treatment here  https://github.com/mozilla-services/screenshots/issues/4848#issuecomment-420948872 which shows promo panel at smaller width and should work.
