### ISSUE TITLE
[FxA] On Mobile click on image in shot page should trigger download

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4876]
Default action on click of image on shot page is open image in browser. With download button going away from header for non-owners, on mobile click on image should trigger download image.

**Comment by johngruen** [comment]
@punamdahiya please let me know when you verify that this is possible. otherwise, we can come up with a different solution

**Comment by punamdahiya** [comment]
@johngruen this is doable , we need to check for isMobile and for mobile update href to use download URL instead of clip.image.url 

https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/view.js#L49
https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/model.js#L11

**Comment by johngruen** [comment]
great, glad to hear it. We could probably just use the download URL everywhere? Seems kind of better to me? @ianb...thoughts?
