### ISSUE TITLE
[FxA] Use React Context to capture FxA auth state

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4877]
With all the auth related info being passed as props in multiple places, we should look into using  React's Context to pass auth state to SignInbutton and marketing header.

See https://github.com/mozilla-services/screenshots/pull/4821#issuecomment-420443624

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
