### ISSUE TITLE
[FxA] Indicate FxA sign in is needed to favorite shots

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4878]
From FxA acceptance criteria:

 It should indicate that favoriting shots requires sign in [note: this is currently demonstrated in the the spec by wiggling the sign-in button if the disabled favorite button is clicked]

**Comment by johngruen** [comment]
@punamdahiya please let @youwenliang and I know if you need more UX here.

**Comment by johngruen** [comment]
@youwenliang why don't we recycle the card we use to highlight the new annotations feature with something like "Sign in to save your favorite shots forever"

We could show it under the sign in button

**Comment by youwenliang** [comment]
I'm just wondering how users can trigger to show the promo panel, maybe when a user clicks the disabled favorite icon we can show the panel under the sign in button.

https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_fav_promo

![image](https://user-images.githubusercontent.com/8919308/45528138-96dfbc00-b811-11e8-8862-a94944255f81.png)

**Comment by clouserw** [comment]
It looks possible to re-use the card there.

What happens if the Edit promo is shown (which uses the same card)

Also, the shot detail view layout you have above is a totally different UI than what we're building (eg. no button labels, buttons are below the header) -- is that intentional?

**Comment by punamdahiya** [comment]
we need to think through  favorite icon shown when user is not authenticated e.g. What happens if a user SignIn -> Click on favorite icon and  mark a shot favorite -> Sign out. In this case, should we show disabled favorite icon or hide it?

**Comment by youwenliang** [comment]
What I have in mind is like this:
If a user is not SignIn, they can see the disabled favorite icon, if they click the icon, the Fav Shot promo will display as shown in my comment above. If the Edit promo is already there, then the Edit promo should be dismissed and show the Fav Shot promo instead.

If a user SignIn -> click on fav icon -> sign out, the favorite icon should be "favorited" but disabled (40% opacity), just like what Will mentioned here: https://github.com/mozilla-services/screenshots/issues/4791#issuecomment-422467928

**Comment by youwenliang** [comment]
> A couple notes and a question for @johngruen and @youwenliang (cc @punamdahiya)
> 
> The placement of the favorite shot promo is currently a mixture of the editor promo and the mock-up from [#4878 (comment)](https://github.com/mozilla-services/screenshots/issues/4878#issuecomment-421220241). The editor promo is placed directly below the button. The favorite shot promo will be displayed below the sign in button but not tucked into a corner. It looks liek this:
> ![image](https://user-images.githubusercontent.com/198055/45832471-92128080-bcc7-11e8-850c-00aebef143bc.png)
> 
> Let me know if you want change the placement of either promo cards.

> 
> Should we still show the promo if the shot is already a favorite but the owner's been signed out?
> 

I think the Fav promo should only get triggered by someone who hasn't signed in before and clicks the disabled favorite icon.

> > I think the Fav Shot promo should also popup automatically if the users have seen the disabled fav icon several times already but haven't clicked it yet
> 
> If we are going to do this, I think we should create a new bug for it so we can work out the details there.

Sure, I'll work on this.

**Comment by youwenliang** [comment]
By the way I updated the promo panel design based on the discussion on Slack
-> https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_fav_promo/

**Comment by chenba** [comment]
I noticed that #4684 (PR #4910) is promoting favorite shots.  I don't think we need this if we have the banner already.

![image](https://user-images.githubusercontent.com/198055/45898711-6b744880-bda0-11e8-83d7-9004a8f25272.png)

**Comment by chenba** [comment]
John said we can close this without merging.
