### ISSUE TITLE
[FxA] Allow shots to be favorited from My Shots page

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4879]
Add a favorite button to the shot view in the My Shots page for logged-in users.

See #4791 for spec.

Note that the spec does not visually indicate that signing in will add the ability to favorite shots.

**Comment by johngruen** [comment]
@6a68 i think you have the wrong bug referenced here...

**Comment by johngruen** [comment]
@6a68: 

@youwenliang and i discussed this. we think it's cool not to indicate favorite-ing behavior on my shots for not-signed-in users
