### ISSUE TITLE
Instrument My Shots button in Library

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4885]
It makes sense to drive users to use the Library menu.

However, I can't tell from the Data Studio graphs how much the 'My Shots' button is actually used.

**Comment by johngruen** [comment]
@6a68 I made a graph on page 12 of the add-on dashboard...it looks like 4.3% of ppl who interact with that panel go to My Shots. This nets out to about 7-8k per day, so it's non-trivial. 

![image](https://user-images.githubusercontent.com/3323249/45680494-564ab000-bb3b-11e8-9552-763730cd06f3.png)

Also, I looked at all the different ways we have instrumented to get to My Shots and it appears this is the most popular way that we have instrumented:

![image](https://user-images.githubusercontent.com/3323249/45680990-ad04b980-bb3c-11e8-85cc-166767955246.png)

So i don't think we shoud get rid of it, but i do think we should istrument the library button so we can see if people use it

how about: 
```
ec: add-on
ea: goto-myshots
el: library
```

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
