### ISSUE TITLE
[FxA] Delete Button on a Shot's Card on My Shots is Missing Its Styles

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4889]
Not exactly FxA but it's caused by the patch from #4685 

![image](https://user-images.githubusercontent.com/198055/45520167-aca3a180-b77d-11e8-9414-ff0f669f817d.png)

**Comment by punamdahiya** [comment]
Thanks for catching it. It is fallout of #4685. I believe fix should have this component return small icon (as before) or icon with text  button based off property set on this component.
