### ISSUE TITLE
Make 'Color Picker' available for localization.

### ISSUE THREAD

**Issue by Joergen** [mozilla-services/screenshots#4891]
The tooltip **Color Picker** is not localized in any locales. It's not available for localization on Pontoon.  
Example from the Danish Firefox Screenshots: [http://www.joergenr.dk/Mozilla/color_picker.png](url)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
