### ISSUE TITLE
The "All Shots" and "Download" buttons are truncated on German localization

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4892]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have the preferred language set to German [de-de] in "about:preferences#general".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe the "All Shots" and "Download" buttons.

[Expected result]:
- The buttons are entirely visible.

[Actual results]:
- The buttons are truncated.

[Notes]:
- Also, it seems that the "All Shots" and "Settings" button are too close to the edge of the page in German localization.
- Here is a screenshot of the issue:
![download and all shots buttons](https://user-images.githubusercontent.com/19226534/45550726-69f0d080-b834-11e8-94b4-715d8ec85c34.png)

**Comment by chenba** [comment]
@6a68 raised this exact concern when the new UI was proposed.  @punamdahiya do you remember if there's a decision on how to handle this?

**Comment by punamdahiya** [comment]
Text style changes to ellipsis on overflow, no formal UX decision on that, including @youwenliang  @johngruen  for their take on it.

**Comment by clouserw** [comment]
@flodolo if we put a comment above these strings to choose the shortest words possible, does that sound like a viable strategy for this? Is the German localizer on github so we could ping them and ask?

**Comment by flodolo** [comment]
I think we should really fix the layout, not asking for shorter translations.

But yes, @koehlermichael is available on GitHub.

**Comment by johngruen** [comment]
@youwenliang's UI proposes using tooltips instead of text labels for the buttons. That would certainly save space and obviate the string length problem

**Comment by punamdahiya** [comment]
@johngruen For width > 719px we are sticking with buttons with text and needs to be fixed. Should we ask for shorter translation?

**Comment by youwenliang** [comment]
I think we should have shorter translation, at least for "All Shots".

**Comment by johngruen** [comment]
Agree with @flodolo, shorter translation likely means bad translation. Let's keep working on the design as is, but let's move these labels into tooltips

**Comment by punamdahiya** [comment]
@youwenliang Hiding labels leaves extra space around buttons, it will be great if we can get spec of how header (width > 719) looks without labels. Thanks!

**Comment by youwenliang** [comment]
Here's the measurement:
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_Header

**Comment by punamdahiya** [comment]
Thanks @youwenliang for updated spec. @johngruen for non-owner view, are we keeping report and download button in header, my understanding these are going away.

https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FxA_Header/

**Comment by johngruen** [comment]
@punamdahiya you can ignore these buttons. they are deprecated

**Comment by punamdahiya** [comment]
#4848 should fix this issue

**Comment by johngruen** [comment]
Closed by #4848
