### ISSUE TITLE
Does it matter if the Screenshots item moves in the page action menu?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4911]
Removing bootstrap moves the Screenshot item in the page action menu (but note, the context menu is not affected). Does this matter?

before:
<img width="377" alt="screen shot 2018-09-17 at 3 09 30 pm" src="https://user-images.githubusercontent.com/96396/45653181-edf0c580-ba8b-11e8-96cb-40b0e96c68c9.png">

after:
<img width="371" alt="screen shot 2018-09-17 at 3 09 58 pm" src="https://user-images.githubusercontent.com/96396/45653183-f0ebb600-ba8b-11e8-9db1-97cdff58471f.png">

**Comment by chenba** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1483088 is related.

iirc far more people use the context menu than the page action button.

Most importantly, keyboard shortcut is coming!  😁

**Comment by 6a68** [comment]
Yeah, I was reminded by aswan that https://bugzil.la/1483591 tracks this very issue upstream, and indeed, the description of that BMO bug was penned by jgruen himself. Closing.
