### ISSUE TITLE
React dev tool add-on not working with latest screenshot extension in nightly

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4915]
With env variable DO_NOT_SEND_CSP set to  true and NODE_ENV as "dev" , we can debug screenshot local dev website using React Dev Tool (#4281)

It's stuck now on Waiting for roots to load.. message with console error as TypeError: name is null; can't access its "replace" property

React devtool works on Firefox release, with react tab able to debug non-owner shot page

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
