### ISSUE TITLE
[Watchdog] Update (or Remove) Channel Specific Submissions

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4920]
With #4770 we can submit shots to Watchdog only if they are not captured with Firefox in the release channel.  It is accomplished by checking the version in the useragent string and a few hard coded (planned future) release dates.

Once Firefox 64 is released, Screenshots will be able to save the update channel in the shot data.  At that point, the Watchdog submission code should switch to use that.  (Unless by then we no longer care about channels and going to submit all shot.  In which case, remove all relevant code. 🍻)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
