### ISSUE TITLE
[watchdog] Disable any actions from watchdog

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/screenshots#4926]
For our initial test, I'd like to make watchdog logging only, meaning, don't flag an image as positive even if watchdog says it is.  That way we can review what it's flagging and fine tune without affecting users.

For this issue, just no-op the response from Watchdog.  That will give us time to figure out the legal flows.

/cc @chenba

**Comment by chenba** [comment]
I'm pulling this into the current sprint since Watchdog is a Q3 OKR.

**Comment by chenba** [comment]
@clouserw what needs to be in the message in order for it to be useful?  The "watchdog id" is available for matching against the positive emails.  The entire PhotoDNA response is in the callback, and anything on the Screenshots side is possible of course.

**Comment by clouserw** [comment]
I think the current emails are fine.  Feel free to throw in anything else you think might be useful, but until we go through some flows, I won't know for sure.
