### ISSUE TITLE
[watchdog] Target all pre-release uploads for intial test

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/screenshots#4927]
We want to run all images from pre-release browsers through watchdog.  That means Nightly, Beta, and Dev Edition.  We've talked about just Nightly, but I wanted to clarify.  If there is a couple day overlap it's not a big deal -- just go off of the dates that the trains move.

/cc @chenba

**Comment by chenba** [comment]
This is what #4770 (PR #4841) is doing.  It compares the version from the UA string against the (scheduled) release dates up to Firefox 65.  If `now` and version is before the release date then the shot is sent to Watchdog.

Closing as a duplicate.
