### ISSUE TITLE
[Watchdog] Add Tests

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4931]
[Watchdog](https://github.com/mozilla/watchdog-proxy/) is written to be serverless, and currently there's no way to deploy it locally.  That makes local integration testing difficult.  Perhaps we could add some unit tests.

Tests to consider:

- when a shot is saved, is a request sent to Watchdog?
- is the submission request to Watchdog correct?
- are positive callbacks handled correctly?
- are negative callbacks handled correctly?
- are error callbacks handled correctly?

Some refactoring might be necessary.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
