### ISSUE TITLE
[Watchdog] Remove Logs Only Mode

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4936]
This is a followup to #4926, where we introduced a config to enable a logs only mode.

Note that there are other configs for enabling and throttling Watchdog.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
