### ISSUE TITLE
[FxA] Do Not Wrap Long Lines for Button Label Text

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4937]
Depending on the locale the text label for the buttons in the header could warp into multiple lines, pushing the button image up.  The favorite shot button in German is a good example.  Until we move a text-less button design, we should stop wrapping the text.

**Comment by clouserw** [comment]
Wontfix in favor of https://github.com/mozilla-services/screenshots/pull/4940#issuecomment-423704058
