### ISSUE TITLE
[Discussion] Shots page layout / organizational tools

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4939]
Looking at the metrics page, there are about 8 million users with active uploads.

About 90% of those users have 4 or fewer shots.

If most users have 1-4 shots, how do we give them more value? The layout of the my shots page seems to assume users will have many shots, but that's not the case. Should we show much larger tiles on that page?

<img src="https://user-images.githubusercontent.com/96396/45897444-feef4e80-bd8b-11e8-81ac-8e27fc719775.png" width=300>

-----

This is the typical (~75% of users) case. How do we add value here?

<img width="500" alt="screen shot 2018-09-21 at 10 56 29 am" src="https://user-images.githubusercontent.com/96396/45897822-05ca9100-bd8d-11e8-8340-1df08c78ae8d.png">

**Comment by johngruen** [comment]
I don't think this is high priority right now. I don't think there's a world where a UI will look attractive with one list item. Fortunately, I think there's also very little utility to this UI.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
