### ISSUE TITLE
Mobile devices cannot access my shots

### ISSUE THREAD

**Issue by mantou132** [mozilla-services/screenshots#4949]
I access [my shots](https://screenshots.firefox.com/shots) on my mobile device to get links to share.

But did not display the picture list, and made a jump.

**Comment by mantou132** [comment]
I ended up using the "send tab to device"

**Comment by clouserw** [comment]
We have a new mobile design with FxA support coming soon which should help address our mobile issues.  Look for a new design in the next couple of months.

If this doesn't address your concern, please file a new bug with lots of details.  Thanks
