### ISSUE TITLE
[FxA] Upsell Banner Not Displayed on Editor Page

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4952]
Not sure if it's intentional or we missed a spot...

#### STR
1. Upload new shot or go to a shot while not signed in with FxA
1. Click on Draw to start the editor

#### Expected
Upsell banner display a message promoting FxA.

#### Actual
No upsell banner.

**Comment by clouserw** [comment]
"I think it's ok"  --jgruen
