### ISSUE TITLE
Use arrow keys to move between images

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/screenshots#4968]
[From Discourse:](https://discourse.mozilla.org/t/feature-req-use-arrow-keys-to-move-between-images/32142)

Would be great to be able to use the left/right arrow keys to move between images.

**Comment by Michael-Overall** [comment]
Would this be when the "Screenshot" tab comes up after taking a screenshot with the extension?

![image](https://user-images.githubusercontent.com/28114489/49105751-78556280-f24f-11e8-9177-7c6b594cebe5.png)

Either way, I can see if I can implement something for this feature if you like.

**Comment by punamdahiya** [comment]
> Would this be when the "Screenshot" tab comes up after taking a screenshot with the extension?

@Michael-Overall yes, scope of this issue is to allow user to navigate between multiple shots thumbnail images using arrow keys on my shots page (screenshots.firefox.com/shots)

> 
> 
> Either way, I can see if I can implement something for this feature if you like.

perfect, Thank you!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
