### ISSUE TITLE
"Firefox Screenshots" string is too close to the left margin of the "My Shots" page and Screenshots homepage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4978]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Prerequisites]:

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "My Shots" page.
3. Observe the "Firefox Screenshots" string displayed in the top left corner of the page.

[Expected result]:
- The string is correctly displayed.

[Actual results]:
- The string is too close to the left margin of the page.

[Notes]:
- Here is a screenshot of the issue:
![firefox screenshots](https://user-images.githubusercontent.com/19226534/46343914-08a86a00-c648-11e8-9da3-26e71c182f74.png)

**Comment by punamdahiya** [comment]
Should be fixed by https://github.com/mozilla-services/screenshots/pull/5011

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
