### ISSUE TITLE
The "Report shot", "Share" and "Download" buttons are no longer displayed on non-owner page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4979]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Prerequisites]:

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and copy the link of the save shot.
3. Paste the link in other browser or on a new Firefox profile.
4. Observe the left corner of the page.

[Expected result]:
- The "Report shot", "Share" and "Download" buttons are displayed.

[Actual results]:
- There is no "Report shot", "Share" or "Download" button.

[Notes]:
- I am not sure if the "Share" button should be implemented but it's displayed in the mock-ups provided in [#4848](https://github.com/mozilla-services/screenshots/issues/4848#issuecomment-423398474).
- Here is a screenshot of the issue:
![no buttons](https://user-images.githubusercontent.com/19226534/46344048-89fffc80-c648-11e8-986e-b30b9d95e476.png)

**Comment by chenba** [comment]
It's caused by [this block of code](https://github.com/mozilla-services/screenshots/pull/4940/files#diff-c089cb65f9a6ab0a43538517ddbcc5b6L366) being moved into a isOwner guarded `if`.

**Comment by johngruen** [comment]
Note the flagging stuff has been moved into the footer. Gonna figure out what else we ant to display here, if anything

**Comment by johngruen** [comment]
Fixing this might just be adding the promo panel

**Comment by chenba** [comment]
What should be the promo in this case?  The browser is Firefox, but we don't know if they are Screenshots users, so we can't promote Firefox or FxA...?

**Comment by punamdahiya** [comment]
That's correct, there is no promo banner for non-owners on Firefox. On non-Firefox browser , it's showing promo banner with text "⁨Screenshots made simple. Take, save, and share screenshots without leaving Firefox.⁩ Get Firefox now"

**Comment by ianb** [comment]
We'll put back just one button, as described in #5043

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and  Arch Linux. 4.12.
