### ISSUE TITLE
DRY Up the Delete and Favorite Functions in Shot and My Shots

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4985]
Users can delete and favorite shots from the shot or My Shots page, and the controller for the respective page has a function for each operation.  The delete shot functions are nearly identical in code, and the favorite shot/update expiration functions are similar as well.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
