### ISSUE TITLE
[FxA] Several UI related issues

### ISSUE THREAD

**Issue by youwenliang** [mozilla-services/screenshots#4995]
I'm using this link to test the current UI (https://screenshots.dev.mozaws.net/homepage/install-test-local.html) and here are some of the UI issues I saw:

My Shot page:
1. The logotype in the header should have a padding-left: 30px, as mentioned in #4978, and the settings icon on the far right should not have a margin-right: 30px.

2. The logotype turns too small after width <= 719px, should still have at least 260px width (currently 180px)

3. Footer should change to flex-direction: column after width <= 959px instead of width <= 719px to avoid this to happen: 

- <img width="712" alt="image" src="https://user-images.githubusercontent.com/8919308/46457793-2b708500-c7e6-11e8-8e41-067a80b41254.png">

4. And when footer changes to column layout there should be a margin 16px between the list and mozilla logo, here:

- <img width="183" alt="image" src="https://user-images.githubusercontent.com/8919308/46457883-7e4a3c80-c7e6-11e8-9396-ae96001f87bf.png">

---

Shot Detail page:
1. The delete panel in smaller width is misaligned, and I would suggest changing the button color like this:
- misaligned: <img width="347" alt="image" src="https://user-images.githubusercontent.com/8919308/46458470-725f7a00-c7e8-11e8-9acb-de8873a1c05a.png">
- color changes: <img width="366" alt="image" src="https://user-images.githubusercontent.com/8919308/46458589-e26e0000-c7e8-11e8-964f-6b1062d25581.png">

2. For the action buttons, there should not be border-radius in hover state:
- <img width="307" alt="image" src="https://user-images.githubusercontent.com/8919308/46458697-2fea6d00-c7e9-11e8-9fd3-3c684e5d885a.png">
- <img width="140" alt="image" src="https://user-images.githubusercontent.com/8919308/46459006-37f6dc80-c7ea-11e8-9dff-87adb694daa0.png">

3. Also for the action buttons, there should be a "pressed state" with rgba(12, 12, 13, 0.3) as the background.

4. The shot title part gets cut weirdly, with the max-width: 250px when width < 1260px and max-width: 130px when width < 719px. Is there a way to make sure the action buttons won't wrap while the shot title part adjusts its width according to the remaining available space? (Instead of setting max-width in different breakpoints)

5. Icons should be updated: https://github.com/mozilla/testpilot-assets/tree/master/Firefox_Screenshots/00_Assets/Updated_Icons

Let me know if there is anything to clarify! I can also work on some of these issues once I'm able to run this locally.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified these fixes on latest Screenshots (34.0.0) dev version and it seems that the "Delete" pop-up is still misaligned at smaller width. 
I have created a new issue for this in #5040
