### ISSUE TITLE
The time when the shot was taken is no longer displayed for a saved shot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5012]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe the strings displayed under the title of the shot.

[Expected result]:
- The time when the shot was taken is displayed under the title.

[Actual results]:
- The time when the shot was taken is no longer displayed.

[Notes]:
- Here is a screenshot of the issue:
![expires](https://user-images.githubusercontent.com/19226534/46615930-1bc4a980-cb22-11e8-8e92-934483c4a324.png)

**Comment by punamdahiya** [comment]
Should be fixed with #4944 revert

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on latest Screenshots 34.0.0 dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
