### ISSUE TITLE
You are wrongly redirected to the Screenshots page if you don't have any shots saved and you navigate to "My Shots" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5023]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile created and no shots were saved.
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the new profile from prerequisites.
2. Click the "Take a Screenshots" button from "Page Actions" menu.
3. Click the "My Shots" button from the top right corner.
4. Observe the behavior.

[Expected result]:
- You are redirected to "My Shots" page and the "No saved shots. Go on, create some." message is displayed on the page.

[Actual results]:
- You are redirected to "My Shots" page, the "Loading" message is displayed then you are redirected to the Screenshots Homepage.

[Notes]:
- Here is a screen recording of the issue:
![no shots saved](https://user-images.githubusercontent.com/19226534/46727023-57798380-cc88-11e8-9bcf-4492897b2c4d.gif)

**Comment by punamdahiya** [comment]
This is expected behavior
