### ISSUE TITLE
The "Sign In" promo from the header of the Screenshots pages is not displayed if you have an adblocker installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5027]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have the uBlock Origin or Adblock Plus installed on the created profile.
- You are not logged in into FxA.

[Steps to reproduce]:
1. Open the Firefox browser with the new profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe the header of the page.

[Expected result]:
- The "Sign In" promo is displayed.

[Actual results]:
- The "Sign In" promo is not displayed.

[Notes]:
- I have managed to reproduce this issue with uBlock Origin, Adblock Plus, AdBlocker Ultimate.
- Here is a screen recording of the issue:
![promo adblock](https://user-images.githubusercontent.com/19226534/46801696-1060c080-cd64-11e8-909b-6143470c7897.gif)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the issue is also reproducible for the Firefox promo bar displayed in the non-Firefox browser at the header of the page.
For example, if you have an adblocker on chrome and you open a shot the Firefox promo bar is not displayed,
Here is a screenshot on Chrome with uBlock installed:
![chrome with adblock](https://user-images.githubusercontent.com/19226534/46811932-64779f00-cd7c-11e8-9809-c3361e7caf26.png)

Here is a screenshot on Chrome without any adblocker installed:
![chrome without adblock](https://user-images.githubusercontent.com/19226534/46811938-67728f80-cd7c-11e8-8324-f21bd83b5bf1.png)

**Comment by johngruen** [comment]
Let's change the class name?

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and  Arch Linux. 4.12.
