### ISSUE TITLE
The "Edit Title" field and the strings below are slightly moving their position when clicking the title of the shot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5028]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the new profile from prerequisites and navigate to any website.
2. Save a selection on the page.
3. Observe the "Edit Title" filed, the domain link and the expire info when clicking the title of the shot.

[Expected result]:
- The "Edit Title" field, the domain link and the expire info do not move their position.

[Actual results]:
- The "Edit Title" field, the domain link and the expire info are slightly moving their position upwards.

[Notes]:
- Here is a screen recording of the issue:
![doamin and link](https://user-images.githubusercontent.com/19226534/46810147-b6b6c100-cd78-11e8-879a-b28f4b77a56a.gif)

**Comment by johngruen** [comment]
@youwenliang do you care about/want to work on this?

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7x64, Mac 10.13 and Arch Linux.
