### ISSUE TITLE
[FxA] Browser login automated tests

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5031]
Here's the tests I would propose we include as part of #4966:

- [ ] Use clientlib to login and create some shots
- [ ] Associate the clientlib deviceId with an accountId (something to be added to pglib.py, probably)
- [ ] Use pglib.py to login browser-only (meaning accountId, but no deviceId)
- [ ] Confirm that we can change expiration and delete shots made previously
- [ ] Confirm that we *cannot* change expiration or delete shots made with a different deviceId/accountId
- [ ] (Optional?) Test that we can update a shot (e.g., new title, or upload a new version)
- [ ] Confirm we get the appropriate shots via My Shots (we can use `?format=json` to avoid rendering/parsing My Shots)
- [ ] Test some of the UI elements we expect to show up when authenticated (I don't think this has to be entirely thorough)

Stuff we wouldn't be testing:

- All the details of the UI that show up or don't in different states
- The login process itself, including OAuth
- The cookie setting that happens afterwards (we'd be making our own cookies in pglib)
- Anything related to wantsauth

**Comment by punamdahiya** [comment]
@ianb can you please elaborate on requirement 'Confirm we get the appropriate shots via My Shots (we can use ?format=json to avoid rendering/parsing My Shots)' in the initial comment.

Trying /shots?format=json didn't change response text

**Comment by punamdahiya** [comment]
> @ianb can you please elaborate on requirement 'Confirm we get the appropriate shots via My Shots (we can use ?format=json to avoid rendering/parsing My Shots)' in the initial comment.
> 
> Trying /shots?format=json didn't change response text

Figured its /shots?withdata=true&data=json that returns json

**Comment by punamdahiya** [comment]
Fixed with https://github.com/mozilla-services/screenshots/pull/4966 in master
