### ISSUE TITLE
Screenshots "Page not found" page is wrongly displayed on Safari and Chrome

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5034]
[Affected versions]:
- Chrome 69.0.3497.100
- Safari

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Chrome and navigate to a shot page that was previously deleted (eg: this shot).
2. Observe the "Page not found" page.

[Expected result]:
- The page is correctly displayed as in Firefox.

[Actual results]:
- The "Firefox Screenshots" title is displayed in the left center of the page and the specific image is very small and displayed at the bottom of the page.

[Notes]:
- The issue is not reproducible on Edge.
- Here is a screen shot of the issue:
![image](https://user-images.githubusercontent.com/19226534/46872327-73be2180-ce3c-11e8-9c42-80041b05139e.png)

**Comment by ianb** [comment]
See also #5002

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and the issue is no longer reproducible. Tested on Chrome, Safari, Opera and Edge.
