### ISSUE TITLE
The "Shot expired" and "Leave Screenshots" pages should also have a white background

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5035]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to any website and save a selection.
3. Click the "Remove All Data" link from the footer of the page.
4. Observe the background of the "Leave Screenshots" page.
2. Observe the "Page not found" page.

[Expected result]:
- The background of the page is white.

[Actual results]:
- The background of the page is dark gray.

[Notes]:
- Here is a screenshot of a "Shot expired" page:
![image](https://user-images.githubusercontent.com/19226534/46872517-ffd04900-ce3c-11e8-87dd-77c5110f6c1e.png)

- Here is a screenshot of a "Leave Screenshots" page:
![image](https://user-images.githubusercontent.com/19226534/46872496-f0e99680-ce3c-11e8-9466-6fd7ec502c6b.png)

**Comment by punamdahiya** [comment]
Fixed with https://github.com/mozilla-services/screenshots/pull/5065

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and the "Shot expired" and "Leave Screenshots" pages have a white background on latest Screenshtos dev version.
