### ISSUE TITLE
The "Delete" panel is misaligned when the browser window is resized at smaller width

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5040]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to any website and save a selection.
3. Resize the browser window until the tools are displayed in the top center of the page.
4. Click the "Delete" button.
5. Observe the "Delete" pop-up.

[Expected result]:
- The "Delete" pop-up is correctly aligned.

[Actual results]:
- The "Delete" panel is misaligned.

[Notes]:
- The issue is also reproducible for the "Delete" pop-up displayed on "My Shots" page.
- Here is a screen recording of the issue:
![delete popup](https://user-images.githubusercontent.com/19226534/46947925-018c4d80-d085-11e8-99b3-e74243ebb633.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
