### ISSUE TITLE
A tiny scrollbar is wrongly displayed beside the expire string on Chrome and Opera browsers on Windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5041]
[Affected versions]:
- Chrome 69.0.3497.100
- Opera 56.0.3051.43

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a link of a saved shot.

[Steps to reproduce]:
1. Open a link of a saved shot on Chrome.
2. Observe the expire status area.

[Expected result]:
- The expire status is correctly displayed and there is no scrollbar.

[Actual results]:
- A tiny scrollbar is displayed beside the expire string.

[Notes]:
- Here is a screen recording of the issue:
![scrollbar](https://user-images.githubusercontent.com/19226534/46948602-4e712380-d087-11e8-9169-41b8fb263aac.gif)

**Comment by 123survesh** [comment]
Hi, I would like to fix this issue. I will get back with some updates :smile:

**Comment by 123survesh** [comment]
@SoftVision-CosminMuntean I couldn't recreate the bug in both chrome and opera. I checked why and it seems only the person who created the screen shot can view the expiring time left, I was failing the isOwner check. Do you know how to view the screenshots as their owner from other browsers?


Also I tried by passing that test, and I couldn't recreate that error in chrome V 69.0.3497.100  and Opera V 56.0.3051.43, in Windows 8.1

![image](https://user-images.githubusercontent.com/8644987/47211242-a2934500-d3b2-11e8-89fa-90a8d3211a62.png)
![image](https://user-images.githubusercontent.com/8644987/47211342-da01f180-d3b2-11e8-85e4-c3d277d22397.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
