### ISSUE TITLE
parallax image problem

### ISSUE THREAD

**Issue by alisiddique** [mozilla-services/screenshots#5044]
Hi There,
Sometime can't capture parallax image website.
http://bridge201.qodeinteractive.com/
https://screenshots.firefox.com/vwXNVCdLzw0WEqDZ/bridge201.qodeinteractive.com

Thanks,
Ali

**Comment by marniepw** [comment]
This is a duplicate of #2945. Parallax backgrounds don't always work due to the way we implement Screenshots.
