### ISSUE TITLE
There is a "FxA" slide on the production Onboarding tour even if the "FxA" feature is not available yet on production

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5045]
[Affected versions]:
- Nightly 64.0a1
- Screenshots 35.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open a new Firefox profile and navigate to any website.
2. Click the "Take a Screenshot" option from the "Page Actions" menu.
3. Observe each slide from the Onboarding tour.

[Expected result]:
- There is no slide that promotes the "FxA" feature.

[Actual results]:
- The last slide promotes the "FxA" feature even if is not available yet.

[Notes]:
- The issue is only reproducible on latest Nightly (64.0a1) build with Screenshots 35.0.0 version.
- Here is a screen recording of the issue:
![onboarding](https://user-images.githubusercontent.com/19226534/47075929-4095dc80-d206-11e8-82ff-c75b6a0f8b35.gif)

**Comment by 6a68** [comment]
@johngruen says, this'll be deployed before it hits release, meh, ship it
