### ISSUE TITLE
[FxA] Messaging on settings page 

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#5052]
Opening issue to discuss messaging on settings page to educate user what disconnect / sign out does

![settings-logout](https://user-images.githubusercontent.com/597734/47177684-f415d400-d2cd-11e8-96e9-512c1bac984c.png)

**Comment by ianb** [comment]
Maybe we could get a bear picture, of the bear doing something login-related? Also some text describing the value of logging in.

**Comment by punamdahiya** [comment]
@youwenliang planning release soon and hoping to get this in, can you please share a UI that we can use for initial launch. Thanks!

**Comment by weivicky** [comment]
Just some ideas...hopefully it helps in some way!

1. Including text on the settings page about how valuable syncing is
- my question with including text about how valuable syncing the account is/how bad signing out is: should that be what the on-boarding or the initial sign in page are for? Could that be the reason why they signed in? If that's the reason why they signed in, maybe we can do not need to include too much (one sentence with a button to expand if needed)?

2. Including a warning when signing out
- creating friction and warning them before signing, warning them that they might be losing data

**Comment by youwenliang** [comment]
Based on @ianb's comment, here's what I came up with:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/8919308/48248241-71e28080-e431-11e8-9251-eb33b1985268.png">

We do have a disconnect warning message right now but didn't talk about the disadvantage of disconnecting. Currently the message is: "Are you sure you want to disconnect this device from your Firefox account?" Maybe we could change the message here?
