### ISSUE TITLE
"Sign in" text in upsell banner should be a link

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5054]
Seems like a missed opportunity to not linkify the "Sign in or sign up" text here:

<img width="585" alt="screen shot 2018-10-19 at 11 53 13 am" src="https://user-images.githubusercontent.com/96396/47238027-9e0c6380-d395-11e8-8ecd-964aca0cc858.png">

**Comment by yehudab** [comment]
Thinking about it again, I guess a better URL would be: `/api/fxa-oauth/login/<current-url>`.

**Comment by punamdahiya** [comment]
> /api/fxa-oauth/login

That's correct, its invokes [route handler here](https://github.com/mozilla-services/screenshots/blob/master/server/src/server.js#L1090)
