### ISSUE TITLE
Firefox Screenshots 10.12.0 screenshots@mozilla.org.xpi

### ISSUE THREAD

**Issue by grahamperrin** [mozilla-services/screenshots#5062]
Hi

If I add (here) the `.xpi` that I copied from within Firefox 56.0.2, could it be added to the assets? 

https://github.com/mozilla-services/screenshots/releases/tag/10.12.0

Context: https://www.reddit.com/r/waterfox/comments/9ln1eq/-/e78ekbq/ under _Pocket, Firefox Screenshots etc hanging around?_

TIA

**Comment by punamdahiya** [comment]
Sorry but we can't support old version of screenshots. We have made lot of changes since 57 release and if we post link to xpi you mentioned people will think its supported but we can't fix bug in older version. Thanks

**Comment by grahamperrin** [comment]
Thanks, understood. I found the signed `.xpi` on a Mozilla server (now captured in the Wayback Machine) but I'll not link from it here.
