### ISSUE TITLE
Expiration info should always be visible

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5068]
Seems like this data should be visible at all widths, but it's hidden at 2 out of the 4:

![image](https://user-images.githubusercontent.com/96396/47446012-19439000-d76f-11e8-8a24-f38b51985f72.png)

![image](https://user-images.githubusercontent.com/96396/47446018-1d6fad80-d76f-11e8-8630-8b5251c351cd.png)

![image](https://user-images.githubusercontent.com/96396/47446020-21033480-d76f-11e8-831b-ea94922cdc0e.png)

![image](https://user-images.githubusercontent.com/96396/47446023-2496bb80-d76f-11e8-8b7f-96949e4537a8.png)

**Comment by yehudab** [comment]
I can take this. 

Just to clarify, are you talking about both the time taken part (“14 minutes ago” in the above example) and expiration time (“expires in 14 days”), or just the expiration time?

It also looks a bit different when logged-in vs. not logged-in.

**Comment by punamdahiya** [comment]
> I can take this.
> 
> Just to clarify, are you talking about both the time taken part (“14 minutes ago” in the above example) and expiration time (“expires in 14 days”), or just the expiration time?
> 
That's correct, we should display both. May be for smaller width, if it doesn't fit, we can just show expiration time and hide span.time-diff (created info) @6a68 wdyt?

> It also looks a bit different when logged-in vs. not logged-in.

**Comment by mathieu-aubin** [comment]
How about a ' _best before_ ' type date format.

##### This is a ** flash ** idea so bare with me, i havnt given it any more thoughts simply figured there is potential in integrating a solution that has been working for decades and is already well engrained in the modern culture. It doesn't provide any actual ways of implementing/applying the method to the current scope. Post markdown format, hoping to help making a point _

#### 1. Its a proven thing

 - The food industry depends on it to keep it's customer's satisfaction as high as possible by making sure the goods are edible and safe.

#### 2. Already widespread

- Everybody on the planet that has access to enough technology to handle Firefox should be familiar with the concept.

#### 3. Its fast

- A quick glance at a BB date is enough to inform

#### 4. Its somewhat forgiving

- The format can differ a little bit from one company to the next and it perform just as well

#### 5. It's scalable

- It can be expressed many different ways
  - Saturday, August 2, 2011
  - Sat. Aug. 2, 2011
  - Aug. 2 2011
  - 08/02/11 (or with dots...)
  - ...

    Shorter form caveat: valid output with certain dates (including this one). It seems time format isn't a global standard so it has a misleading potential

They are in no particular order other than what came to mind at the time. Thanks
