### ISSUE TITLE
"Delete" button is wrongly enlarged on "Shots" page on non-Firefox browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5072]
[Notes]:
- The issue is not reproducible on Safari.

[Affected versions]:
- Chrome 70.0.3538.77
- Opera 56.0.3051.43
- Microsoft Edge 42.17134.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Screenshots FxA account with at least one saved shot.

[Steps to reproduce]:
1. Open another browser than Firefox (eg: Chrome) and navigate to "https://screenshots.dev.mozaws.net" page.
2. Click the "Sign In" button from the top right part of the page.
3. Click the "My Shots" button from the top right of the page.
4. Hover a saved shot and observe the "Delete" button.

[Expected result]:
- The "Delete" button is correctly displayed on the shot tile.

[Actual results]:
- The "Delete" button is enlarged and exceeds the shot's area.

[Additional Notes]:
- On Microsoft Edge the "Download" and "Share"
- Here is a screen recording of the issue:
![delete button](https://user-images.githubusercontent.com/19226534/47563866-cf53d900-d92b-11e8-8c34-503e0ff6aa4d.gif)

**Comment by punamdahiya** [comment]
Issue should be fixed with #5002 

https://github.com/mozilla-services/screenshots/pull/5071

**Comment by punamdahiya** [comment]
Fixed with https://github.com/mozilla-services/screenshots/pull/5071 in master

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Chrome, Opera, Edge and Safari.
