### ISSUE TITLE
[FxA] The "Copy Image to clipboard" button is not displayed on the shot page in non-Firefox browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5073]
[Affected versions]:
- Safari 12.0
- Chrome 70.0.3538.77
- Opera 56.0.3051.43
- Microsoft Edge 42.17134.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Screenshots FxA account with at least one saved shot.
- You are already logged in Screenshots FxA account in another browser than Firefox (eg: Chrome).

[Steps to reproduce]:
1. Open the browser from prerequisites and navigate to "https://screenshots.dev.mozaws.net/shots".
2. Click on one of the shots.
3. Observe the options displayed in the top right part of the page.

[Expected result]:
- The "Copy Image" button is displayed between "Edit this image" and "Download" button.

[Actual results]:
- The "Copy Image" button is not displayed.

[Notes]:
- I have noticed that "Copy Image to clipboard" button is displayed only while the page is loading.
- Here is a screen recording of the issue:
![copy image button](https://user-images.githubusercontent.com/19226534/47565784-45f3d500-d932-11e8-86a8-7edd5b3d85cd.gif)

**Comment by punamdahiya** [comment]
Copy button on shot page to be visible needs screenshots extension and thats why hidden on non-Firefox browser. https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/controller.js#L291

**Comment by punamdahiya** [comment]
Discussed this issue in triage today and inclined to mark it as won't fix for now. Thanks
