### ISSUE TITLE
[FxA] The "Sign In" promo is wrongly displayed on a non-owner shot if it's opened on the Firefox profile where you are already logged

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5074]
[Affected versions]:
- Nightly 65.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Screenshots FxA account with at least one saved shot.
- Have a profile where you are already logged in Screenshots FxA account.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a saved shot created on a different profile (eg: this [link](https://screenshots.dev.mozaws.net/KoETlKnQJ34ZC7Dk/www.wikipedia.org)).
3. Observe the shot page.

[Expected result]:
- The "Sign In" promo is not displayed.

[Actual results]:
- The "Sign In" promo is displayed even if you are already logged in.

[ Notes]:
- Here is a screen recording of the issue:
![sign in promo on non owner](https://user-images.githubusercontent.com/19226534/47566721-3629c000-d935-11e8-89d5-f4d21a3c88a9.gif)

**Comment by punamdahiya** [comment]
Attached PR with the fix

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue with latest Screenshots (34.0.0) dev version and the issue is no longer reproducible on a received shot.
But, I have noticed that the "Sign In" promo is still displayed if you navigate to a non-owner shot that has been deleted or has expired.

[Prerequisities]:
- The latest Screenshots dev version is installed on a Firefox profile.
- You are already logged with a valid FxA account.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to an expired shot or deleted shot that was made on another profile (eg: [this one](https://screenshots.dev.mozaws.net/Y4MygQ50aCBhmw1I/www.wikipedia.org)).
3. Observe the page.

[Expected result]:
- The "Sign In" promo is not displayed.

[Actual results]:
- The "Sign In" promo is displayed even if you are already logged in.

Here is a screen recording of the issue:
![sign in probo](https://user-images.githubusercontent.com/19226534/47710990-cec58600-dc3c-11e8-9db5-5ae589c31ea4.gif)

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Thanks for catching this, we should pass accountId cookie info (hasFxa) in not found pages https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/not-found/view.js#L32, will submit the PR

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12.
