### ISSUE TITLE
"Favorite", "Copy Image" and "Downlod" buttons wrongly remain in the pressed state after are clicked

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5075]
[Affected versions]:
- Nightly 65.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have the latest Screenshots 34.0.0 dev version isntalled from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html).
- You are already logged in Screenshots FxA account.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a saved shot.
2. Click the "Copy Image to clipboard" button.
3. Hover away and observe the "Copy Image to clipboard" button.

[Expected result]:
- The "Copy Image to clipboard" button loses the pressed state.

[Actual results]:
- The "Copy Image to clipboard" button remains in the pressed state.

[Notes]:
- The issue is also reproducible on non-Firefox browsers.
- The issue is not reproducible on Mac 10.13 with latest Nightly build and Safari 12.0. However, it is reproducible with Chrome browser.
- Here is a screen recording of the issue:
![pressed state](https://user-images.githubusercontent.com/19226534/47568050-bc93d100-d938-11e8-82b8-81a9d86c58da.gif)

**Comment by ianb** [comment]
Maybe the `:focus` and `:active` styles are the same here?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
