### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5089]
We want to use Ctrl+Shift+S (or Command+Opt+S on Mac). This previously opened the devtools debugger, but that has been disabled (per [this comment](https://github.com/mozilla-services/screenshots/issues/2491#issuecomment-420007290)).

We'll need to open a Bugzilla ticket to remove this from devtools. We'll have to experiment with whether we can override it in our add-on before they remove it.

See also previous discussion in #2491

**Comment by 6a68** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1502924 to track the devtools work

**Comment by 6a68** [comment]
> We'll have to experiment with whether we can override it in our add-on before they remove it.

According to [mdn](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations), we're out of luck:

> If a key combination is already used by the browser (for example, "Ctrl+P"), or by an existing add-on, then you can't override it. You will be allowed to define it, but your event handler will not be called when the user enters it.

If any other addon tries to use our key combination, they're going to be in for a surprise. Might be good to figure out if/where the Firefox key combinations are documented (MDN? Mozilla wiki?) and make sure we're included in the big list.

**Comment by Rob--W** [comment]
FYI, users can change shortcuts of their add-ons, via the "Manage Extensions Shortcuts" menu on the gears button at `about:addons`.

System add-ons such as Screenshots were not shown, but this is going to change in Firefox 69, by https://bugzilla.mozilla.org/show_bug.cgi?id=1553416
