### ISSUE TITLE
Consider removing "renovate" app in place of Dependabot

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla-services/screenshots#5091]
Dependabot can handle JavaScript and Docker dependencies, and adds support for python dependency management

**Comment by kimberlythegeek** [comment]
I can disable the docker + javascript checks

**Comment by 6a68** [comment]
@kimberlythegeek cool, and I think we'll want to figure out the right frequency for the python checks, too. is that configurable?

**Comment by 6a68** [comment]
the python deps are just test dependencies, so I feel like once a month would be plenty (but again, this is the sort of thing we should talk about in the morning meeting, not just turn on for the repo)

**Comment by kimberlythegeek** [comment]
Monthly sounds good. I have weekly updates on some repos, and it seems like overkill.

**Comment by punamdahiya** [comment]
As discussed in standup, plan is to stick with renovate for now as it can handle python dependencies.
