### ISSUE TITLE
[Annotations] The added text is not visible on the shot if is added from Chrome, Opera or Edge

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5106]
[Affected versions]:
- Chrome 70.0.3538.77
- Opera 56.0.3051.43
- Microsoft Edge 42.17134.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.

[Steps to reproduce]:
1. Open the Chrome browser and navigate to "https://screenshots.dev.mozaws.net" page.
2. Click the "Sign In" button and log in with the account from prerequisites.
3. Click the "My Shots" button and click one of the displayed shots.
4. Click the "Edit this image" button.
5. Click the "Add Text" button.
6. Enter a text and click the "Confirm" button.
7. Observe the shot. 

[Expected result]:
- The added text is correctly displayed.

[Actual results]:
- The added text is not visible, only the background of the text box. 

[Notes]:
- The issue is reproducible with any color.
- Here is a screen recording of the issue:
![add text](https://user-images.githubusercontent.com/19226534/47718946-641f4500-dc52-11e8-9467-24150a1e2c0c.gif)

**Comment by punamdahiya** [comment]
Tracked in #5002, Fix of issue in PR https://github.com/mozilla-services/screenshots/pull/5071

**Comment by punamdahiya** [comment]
Fixed with https://github.com/mozilla-services/screenshots/pull/5071 in master

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and the issue is no longer reproducible. Tested on Chrome, Opera, Edge and Safari.
