### ISSUE TITLE
The Screeshots tools are covered by the image if the browser window is resized, on non-Firefox browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5107]
[Affected versions]:
- Safari 12.0
- Chrome 70.0.3538.77
- Opera 56.0.3051.43
- Microsoft Edge 42.17134.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.

[Steps to reproduce]:
1. Open the Chrome browser and navigate to "https://screenshots.dev.mozaws.net" page.
2. Click the "Sign In" button and log in with the account from prerequisites.
3. Click the "My Shots" button and click one of the displayed shots.
4. Resize the browser window (smaller than 50%) and observe the Screenshots tools.

[Expected result]:
- The Screenshots tools are visible.

[Actual results]:
- The Screenshots tools are covered by the image.

[Notes]:
- The issue is also reproducible on mobile devices.
- Here is a screen recording of the issue:
![screnshots tools](https://user-images.githubusercontent.com/19226534/47727415-09dbaf80-dc65-11e8-884d-6533dd2932de.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is still reproducible. Tested on Chrome, Safari and Edge.

**Comment by punamdahiya** [comment]
It's very strange, not seeing css fix updated on https://screenshots.dev.mozaws.net

**Comment by punamdahiya** [comment]
With tests passing, fix should reflect on dev server. Closing issue as fixed. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Chrome, Safari, Opera, and Edge.
