### ISSUE TITLE
[Mobile][Annotations] The "Crop" functionality is not working on mobile devices

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5113]
[Affected versions]:
- Firefox 63.0.

[Affected Platforms]:
- Android 8.0.0 (Samsung Galaxy S8)

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.
- You are already logged in on Screenshots with the valid account.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Tap on one of the shots displayed.
3. Tap the "Edit this image" button.
4. Tap the "Crop" button and observe the behavior.

[Expected result]:
- The crop overlay is displayed over the image and you can perform a selection

[Actual results]:
- The crop overlay is not displayed and you cannot perform a selection in order to crop the image.

[Notes]:
- Here is a screen recording of the issue:
![mobile crop](https://user-images.githubusercontent.com/19226534/47797834-c732d980-dd2f-11e8-9e96-d2165f5d4dcf.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
