### ISSUE TITLE
[Mobile][Annotations] The "Pen" and the "Highlighter" tools are not working on mobile devices

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5114]
[Affected versions]:
- Firefox 63.0.

[Affected Platforms]:
- Android 8.0.0 (Samsung Galaxy S8)

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.
- You are already logged in on Screenshots with the valid account.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Tap on one of the shots displayed.
3. Tap the "Edit this image" button.
4. Tap the "Pen" tool.
5. Tap and hold on the image in order to draw.

[Expected result]:
- The "Pen" tool works as expected.

[Actual results]:
- The page is scrolled and the "Pen" tool is not working.

[Notes]:
- The same behavior can be observed for the "Highlighter" tool.
- Here is a screen recording of the issue:
![pen and highlighter](https://user-images.githubusercontent.com/19226534/47797923-fc3f2c00-dd2f-11e8-88f7-5a96a2f0d694.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
