### ISSUE TITLE
[Mobile][Annotations] The added text cannot be moved

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5115]
[Affected versions]:
- Firefox 63.0.

[Affected Platforms]:
- Android 8.0.0 (Samsung Galaxy S8)

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.
- You are already logged in on Screenshots with the valid account.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Tap on one of the shots displayed.
3. Tap the "Edit this image" button.
4. Tap the "Add text" tool.
5. Hold and tap on the top border of the text box and try to move it.

[Expected result]:
- The text box can be moved.

[Actual results]:
- The text box cannot be moved.

[Notes]:
- The same behavior can be observed for the "Highlighter" tool.
- Here is a screen recording of the issue: https://drive.google.com/open?id=1jmU_kz6AyBL31No1rhf94ni_GsinxkBh

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
