### ISSUE TITLE
[Mobile][Annotations] The "Clear" button is not visible on mobile devices

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5116]
[Notes]:
- If the image is large, the page can be zoomed out and then the entire annotation tools are visible. However, if you tap the "Save" or the "Cancel" button, the shot page will be zoomed out also.
- If the image is small, the page cannot be zoomed out and the "Clear" button is not visible.

[Affected versions]:
- Firefox 63.0.

[Affected Platforms]:
- Android 8.0.0 (Samsung Galaxy S8)

[Prerequisites]:
- Have a valid FxA account with at least one saved shot.
- You are already logged in on Screenshots with the valid account.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Tap on one of the shots displayed.
3. Tap the "Edit this image" button.
4. Observe the annotation tools.

[Expected result]:
- All the tools are correctly displayed and visible.

[Actual results]:
- The "Clear" button is not displayed.

[Additional Notes]:
- Here is a screen recording of the issue with a large image: https://goo.gl/cQxEF5

- Here is a screen recording of the issue with a small image:
![image with small hight](https://user-images.githubusercontent.com/19226534/47798924-e2064d80-dd31-11e8-9f76-e0c29ff09c55.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
