### ISSUE TITLE
[Meta] [Mobile] Enable edit screenshots tool on mobile

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#5118]
Meta bug to track issues / dependencies that needs to be fixed to enable edit tool on mobile

**Comment by punamdahiya** [comment]
Dependent issues:
"Clear" button is not visible on mobile devices - https://github.com/mozilla-services/screenshots/issues/5116 
The added text cannot be moved - https://github.com/mozilla-services/screenshots/issues/5115
The "Pen" and the "Highlighter" tools are not working on mobile devices - https://github.com/mozilla-services/screenshots/issues/5114
The "Crop" functionality is not working on mobile devices - https://github.com/mozilla-services/screenshots/issues/5113

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
