### ISSUE TITLE
[Annotations] The added text cannot be moved on Microsoft Edge

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5121]
[Affected versions]:
- Microsoft Edge v40.15063.674.0
- Microsoft Edge v42.17134.1.0

[Affected Platforms]:
- Windows 10

[Prerequisites]:
- Have a valid FxA account with at least one saved shot.
- You are already logged in Screenshots.

[Steps to reproduce]:
1. Open the Edge browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Click one of the shots.
3. Click the "Edit this" image button.
4. Click the "Add text" tool.
5. Click and hold the top border of the text box and try to move it.
6. Observe the behavior.

[Expected result]:
- The text box can be moved.

[Actual results]:
- The text box cannot be moved.

[Notes]:
- Here is a screen recording of the issue:
![edge moving text](https://user-images.githubusercontent.com/19226534/47852444-73ce9300-dde4-11e8-89d2-ddafa67694a2.gif)

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Can you please validate if rest of the edit tools (crop, pen and highlight) are functional in edge. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
@punamdahiya I have tested today the Annotations feature on Edge and it seems that the Crop, Pen, and Highlighter tools are not working at all. I have logged the issue at #5149.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
