### ISSUE TITLE
add make zip to accessibility test

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5132]
Right now, the accessibility test assumes that build/screenshots.zip exists, but doesn't actually call the `make zip` step that creates that file. (I discovered this after doing `make distclean`, followed by `npm run test:accessibility`.)

I'm not sure what the nicest way to do this would be...probably change the npm script to call `make zip && `, followed by the existing python incantation.

**Comment by MisraAnandita** [comment]
Hi I would like to work on this issue
It would be really helpful if you could suggest some pointers to begin with since I am very new to open source contribution.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
