### ISSUE TITLE
Code (function name?) exposed after expiry date change

### ISSUE THREAD

**Issue by mathieu-aubin** [mozilla-services/screenshots#5144]
Hey.

After updating expiration date on a screenshot, i noticed the date being displayed with what looked like a function name being included in the output. I took a screenshot that should hopefully be descriptive enough. Have not tried to replicate but nothing special in replication steps worth mentionning... following the flow, no gravy.

![Github's mozilla-services issue #5144](https://i.imgur.com/EXbhkJO.png)

`timeDiffFutureHours`

**Comment by mathieu-aubin** [comment]
Tried replicating, and shot this for visual

![5144](https://user-images.githubusercontent.com/15820228/47981350-80c7dc80-e099-11e8-97e0-d407478fb93f.gif)

**Comment by johngruen** [comment]
We've ripped all of this code out in the next releae. I am gonna go ahead and close this since that solves the problem!
