### ISSUE TITLE
[Mobile][My Shots] The "Download", "Delete" and "Favorite" buttons are displayed on the shot's tile only if the bottom part of it is tapped

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5145]
[Notes]:
- The buttons are also displayed while you are redirected to the Shot page after tapping on the shot. [Here ](https://drive.google.com/open?id=1367AeNCjAiv-TvUCS37TJJGJOfgunRnl)is screen recording with the behavior.
- You can wrongly download or delete the shot since the buttons are not visible and you tap on the position of the buttons.

[Affected Platforms]:
- Android 8.0.0 (Samsung Galaxy S8)

[Prerequisites]:
- Have a valid FxA account with a least one saved shot.
- You are already logged in on Screenshots with the valid account.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Observe the shots tile.

[Expected result]:
- Should be more clear for users how to use the "Download", "Delete" and "Favorite" buttons on mobile.

[Actual results]:
- The "Download", "Delete" and "Favorite" buttons are visible only if the top part of the shot tile is tapped. 

[Additional Notes]:
- Here is a screen recording of the issue:
![mboile shots tile 2](https://user-images.githubusercontent.com/19226534/48005405-0d1ae380-e11c-11e8-91b4-5f35711e53d5.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
