### ISSUE TITLE
The Copy string is not localized in supported languages and on certain cases the string is not displayed at all

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla-services/screenshots#5146]
[Affected versions]:
Nightly 65.0a1
Screenshots 34.0.0 dev

[Affected Platforms]:
Windows 10

[Prerequisites]:
- Have the latest Screenshots 34.0.0 dev version installed from here.
- Have several selections saved in the profile.
- Have the browser set to Spanish (Spain)

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to any website and click the "Take a Screenshot" from "Page Actions" menu.
3. Save a selection.
4. On the selection page, click on "All shots" button.
5. In "All shots" page, hover a shot, then click on "Share" button
6. See how "Copy" text is displayed on the button.

[Expected result]:
- The Copy string is localized in supported languages and  is displayed inside the button.

[Actual results]:
- The Copy string is not localized in supported languages and on certain cases the string is not displayed at all.

[Additional Notes]:
![screenshots - chrome - copy button text](https://user-images.githubusercontent.com/44404741/48012324-87d60580-e100-11e8-8b9d-6b3be9aca513.PNG)
![copy button spanish - english text](https://user-images.githubusercontent.com/44404741/48012338-8dcbe680-e100-11e8-900c-d6f0472a1eff.PNG)

**Comment by punamdahiya** [comment]
It seems [shotPageCopy string](https://github.com/mozilla-services/screenshots/blame/master/server/src/share-buttons.js#L158) is missing from server.ftl

**Comment by LucianaQueirolo** [comment]
I have verified this issue using the latest Screenshots (34.0.0) dev version and is no longer reproducible. Tested on Windows 10 x64, Mac 10.13.4
