### ISSUE TITLE
[Edge][Annotations] The "Crop", "Pen" and "Highlighter" tools are not working on Microsoft Edge browser

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5149]
[Affected versions]:
- Microsoft Edge v40.15063.674.0 
- Microsoft Edge v42.17134.1.0

[Affected Platforms]:
- Windows 10

[Prerequisites]:
- Have a valid FxA account with at least one saved shot.
- You are already logged in Screenshots.

[Steps to reproduce]:
1. Open the Edge browser and navigate to "https://screenshots.dev.mozaws.net/shots" page.
2. Click one of the shots and click the "Edit this image" button.
3. Click on the "Crop" tool and observe the behavior.
4. Select the "Pen" tool and observe the behavior.
5. Select the "Highlighter" tool and observe the behavior.

[Expected result]:
Step 3: You can successfully crop the image.
Step 4: You can successfully draw on the image using the "Pen" tool.
Step 5: You can successfully draw on the image using the "Highlighter" tool. 

[Actual results]:
Step 3: The crop overlay is not displayed so you cannot crop the image.
Step 4: The "Pen" tool is selected but the mouse cursor is not changed and you cannot draw on the image.
Step 5: The "Highlighter" tool is selected but the mouse cursor is not changed and you cannot draw on the image.

[Notes]:
- Here is a screen recording of the issue:
![screenshots_edge](https://user-images.githubusercontent.com/19226534/48071791-c2fd3500-e1e3-11e8-9a74-7de0f4817d9c.gif)

**Comment by johngruen** [comment]
Let's investigate this, we can disable temporarily if the fix is deemed to be too costly. However if we want to be a real services company we should fix this.

**Comment by punamdahiya** [comment]
Debugging the issue, mousedown event handler is not invoked in Microsoft edge for drawing, text and crop tool when the containing div has Canvas object. 
Moving mouse down event handler to document level helps for drawing tool but breaks dragging in crop.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
