### ISSUE TITLE
[Annotations] On Chrome/Safari, the caret is not displayed after deleting the string

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla-services/screenshots#5151]
[Affected versions]:
Chrome Version 70.0.3538.77
Screenshots 34.0.0 dev

[Affected Platforms]:
Windows 10

[Prerequisites]:
- Have this site opened in Chrome: https://screenshots.dev.mozaws.net/shots
- Have a narrow screenshot saved (eg. width less than 500p).

[Steps to reproduce]:
1. Open the Chrome browser.
2. Navigate to the url displayed on prerequisites. 
3. Once the site is rendered, select the narrow screenshots saved.
4. Click the "Edit this image" button.
5. Click the "Add text" button
6. Type a string in the text box
7. Press the "Backspace" key and delete entirely the string.

[Expected result]:
On Chrome, the caret is displayed after deleting the string

[Actual results]:
On Chrome, the caret is not displayed after deleting the string

[Additional Notes]:
![chrome caret - not displayed](https://user-images.githubusercontent.com/44404741/48085597-7f9dc900-e1d9-11e8-8f4f-83de1ab59bf8.PNG)
<img width="1841" alt="screen shot 2018-11-14 at 12 51 59" src="https://user-images.githubusercontent.com/44404741/48494896-8c3fa400-e80d-11e8-9897-34da69857125.png">

**Comment by LucianaQueirolo** [comment]
This issue also occurs on Safari on Mac OS 10.13.6

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
