### ISSUE TITLE
[Annotations] On Safari, Text box is not brought into view when it is refocused

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla-services/screenshots#5176]
[Affected versions]:
Safari 11.1.2
Screenshots 34.0.0 dev

[Affected Platforms]:
MacOS high Sierra 10.13.6

[Prerequisites]:
-  Have a very long saved screenshot.
-  The user is logged into F&A account.

[Steps to reproduce]:
1. Navigate to screenshots website and click the "All shots" button.
2. Click on the long screenshot.
3. Click on "Edit" button.
4. Click on "Add text" button.
5. Scroll down the image.
6. Click the text size button.
7. Select a different text size and observe the behavior.

[Expected result]:
On Safari, Text box is brought into view when it is refocused

[Actual results]:
On Safari, Text box is not brought into view when it is refocused

[Additional Notes]:
![screen shot 2018-11-14 at 13 41 53](https://user-images.githubusercontent.com/44404741/48498860-e6dcfe00-e815-11e8-8fbf-1a754ae96a01.png)

**Comment by punamdahiya** [comment]
@LucianaQueirolo Trying on Safari, looks like on changing text size , Textbox is refocused but shows on the top of the view instead of center. Is that  right?

**Comment by LucianaQueirolo** [comment]
Hi! yes, that's right @punamdahiya

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
