### ISSUE TITLE
[Annotations] On non firefox browsers, the strings below are slightly moving their position when clicking the title of the shot

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla-services/screenshots#5177]
[Affected versions]:
Safari 11.1.2
Screenshots 34.0.0 dev

[Affected Platforms]:
MacOS high Sierra 10.13.6

[Prerequisites]:
-  Have a saved screenshot.

[Steps to reproduce]:
1. Open the Safari browser and navigate to screenshots site.
2. Click on "All shots" button.
3. Click on a screenshot.
4. Click and edit the screenshot title.

[Expected result]:
The domain link and the expire info do not move their position.

[Actual results]:
Tthe domain link and the expire info are slightly moving their position upwards.

Here is a screen recording of the issue:
![safari edit title](https://user-images.githubusercontent.com/44404741/48500119-d417f880-e818-11e8-95a8-281385cf4b93.gif)

**Comment by punamdahiya** [comment]
@youwenliang Another minor UI issue to look at it. Thanks!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
