### ISSUE TITLE
[Annotations] On Safari, the "x" button seems to move its position when on hover in setting page

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla-services/screenshots#5178]
[Affected versions]:
Safari 11.1.2
Screenshots 34.0.0 dev

[Affected Platforms]:
MacOS high Sierra 10.13.6

[Prerequisites]:
Have a saved screenshot.

[Steps to reproduce]:
1. Open the Safari browser and navigate to screenshots site.
2. Log in with an account.
3. Click on the settings button.
4. Hover over the "X" button.

[Expected result]:
The domain link and the expire info do not move their position.

[Actual results]:
Tthe domain link and the expire info are slightly moving their position upwards.

Here is a screen recording of the issue:
![safari setting x button](https://user-images.githubusercontent.com/44404741/48501695-8b623e80-e81c-11e8-8102-a1e069a31fb7.gif)

**Comment by punamdahiya** [comment]
@LucianaQueirolo looks like STR of this issue are copied by mistake from #5177

**Comment by punamdahiya** [comment]
@youwenliang would you like to take a shot at it? Thanks!

**Comment by LucianaQueirolo** [comment]
Sure! @punamdahiya  :)

**Comment by youwenliang** [comment]
@punamdahiya sorry for the late reply, I was not able to find the fix for this issue...

Also, I notice that the disconnect button's default/hover/active color are wrong. It should follow the color here: https://design.firefox.com/photon/components/buttons.html#default-4

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
