### ISSUE TITLE
Include guards around use of IN in servershot.js

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5183]
We use a pattern like this in several places:

```sql
        WHERE data.deviceid IN (${idNums.join(", ")})
```

If `idNums` is the empty list, then this results in a SQL syntax error. It's kind of harmless, it shouldn't ever happen (but it is), and we should throw an error early instead of getting a SQL error.

**Comment by punamdahiya** [comment]
Fix of #5184 should resolve this issue by ensuring we check for zero deviceids length before executing the query in all places in servershot.js
