### ISSUE TITLE
[FxA] Settings page UI when accessed directly using /settings

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#5185]
Scope of this bug is to discuss /settings page when accessed directly from url in firefox and non-firefox browsers
a) **on non-Firefox browsers**, 
i) if not signed into Firefox Account, [page with message "You must have Screenshots installed"](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/settings/server.js#L10)
<img width="908" alt="non-firefox-not-signedin" src="https://user-images.githubusercontent.com/597734/48589226-8de19880-e8ef-11e8-97d8-659f0c514483.png">

ii) if signed into Firefox Account,
<img width="1242" alt="non-firefox-signedin" src="https://user-images.githubusercontent.com/597734/48589257-a3ef5900-e8ef-11e8-81d3-3cded6416485.png">
 

b) **On Firefox browser**

i) If not signed in Firefox Account
<img width="1266" alt="firefox-not-signed-in" src="https://user-images.githubusercontent.com/597734/48589275-b073b180-e8ef-11e8-94e5-9294b0de4a63.png">

ii) if signed into Firefox Account
<img width="1264" alt="firefox-signedin" src="https://user-images.githubusercontent.com/597734/48589282-b8cbec80-e8ef-11e8-97e3-bad9728ba486.png">

**Comment by punamdahiya** [comment]
@johngruen we should review Firefox browsers not signed in settings pageUI, with options as 
a) remove it as we have sign-in available from header
b) Update strings and messaging to remove sync

**Comment by punamdahiya** [comment]
Submitting fix that shows settings page only when user is authenticated with Firefox account.  If user has not previously authenticated, accessing /settings redirects to homepage

**Comment by johngruen** [comment]
Let's redirect to the homepage

**Comment by SoftVision-CosminMuntean** [comment]
I have verified these scenarios using the latest Screenshtos dev version but I have observed the following behaviors:

1. On non-Firefox browsers, if you are not signed into Firefox Account, if you navigate directly to the https://screenshots.dev.mozaws.net/settings, the "You must have Screenshots installed" message is still displayed.
But, from what I understand, now that the PR #5207 landed, you should be redirected to the homepage.

2. On Firefox browsers if you are not signed and you don't have any shots uploaded when you navigate directly to the "Settings" page, the "You must have Screenshots installed" message is displayed.
However, If you have a shot uploaded and you access directly the "Settings" page you are correctly redirected to the "Settings" page.

@punamdahiya are these behaviors intended and I misunderstood the issue?

**Comment by punamdahiya** [comment]
> I have verified these scenarios using the latest Screenshtos dev version but I have observed the following behaviors:
> 
>     1. On non-Firefox browsers, if you are not signed into Firefox Account, if you navigate directly to the https://screenshots.dev.mozaws.net/settings, the "You must have Screenshots installed" message is still displayed.
>        But, from what I understand, now that the PR #5207 landed, you should be redirected to the homepage.
That's correct, accessing /settings page directly from url when not signed in should redirect user to homepage
> 
>     2. On Firefox browsers if you are not signed and you don't have any shots uploaded when you navigate directly to the "Settings" page, the "You must have Screenshots installed" message is displayed.
>        However, If you have a shot uploaded and you access directly the "Settings" page you are correctly redirected to the "Settings" page.
> 
With the fix in this PR, for both Firefox and non-Firefox browsers, accessing /settings url when not signed in should redirect to home page 
> 
> @punamdahiya are these behaviors intended and I misunderstood the issue?

@SoftVision-CosminMuntean fix of this issue should be reflected in >=36.2.0 version on dev which got deployed today and should work now. Thanks!
