### ISSUE TITLE
[FxA] Screenshots homepage shows legacy content for non-Firefox browsers

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#5187]
For non-Firefox browsers we are showing legacy content meant for[ firefox version earlier than 57](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/homepage/view.js#L100)

<img width="1279" alt="get-started-non-firefox" src="https://user-images.githubusercontent.com/597734/48646127-b5426f00-e99c-11e8-8c61-f1413e040a0d.png">

**Comment by johngruen** [comment]
Let's just back out all of the before/after 57 logic on that page
