### ISSUE TITLE
Switch to tag-based deployment

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5205]
Following on #5188, we should get rid of the server-prod branch, and just release from tags.

We'll need to update our circle-ci config to deploy from tags, not branches. See the comments in #5188 for configs from other projects that we can borrow.

**Comment by johngruen** [comment]
@g-k thoughts?

**Comment by g-k** [comment]
@johngruen :+1: Tags signed by a trusted screenshots dev (e.g. `git tag -s 2.0.0`) and deployed from a protected branch are preferable security-wise and CloudOps is familiar with this flow.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
