### ISSUE TITLE
[FxA] The uploaded shots are not synced on non-Firefox browsers if no shots were uploaded on Firefox before logging with a new FxA account

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5210]
[Notes]:
- The shots are correctly synced and displayed on non-Firefox browser after you disconnect and log in again from the Firefox browser.

[Prerequisites]
- The latest Screenshots dev version is installed.
- Screenshots was never used and no screenshots were uploaded.

[Steps to reproduce]:
1. Navigate to https://screenshots.dev.mozaws.net and click the "Sign In" button.
2. Create a new FxA account and activate it.
3. Navigate to https://screenshots.dev.mozaws.net and log in with the newly created FxA account.
4. Navigate to any website and upload a shot.
5. Open a non-Firefox browser and navigate to https://screenshots.dev.mozaws.net page.
6. Click the "Sign In" button an log in with the newly created account.
7. Navigate to "My Shots" page on the opened non-Firefox browser and observe the behavior.

[Expected Results]:
- The shot taken on the Firefox browser is synced and displayed on the "My Shots" page opened in non-Firefox browser.

[Actual Results]:
- The "No saved shots. Go on, create some." message is displayed even if you already saved a shot on Firefox browser.

[Additional Notes]:
- The issue is not reproducible if you already have shots saved and then you create a new FxA account.
- Here is a screen recording with the issue: https://drive.google.com/open?id=1vtuZuIS1XBv5PSjrCIzCRRJQ5z_KPW2G

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the issue is also reproducible on Firefox browsers. If you have two different Firefox profiles and you didn't upload any shot then you log in with a newly FxA account on one of the profiles, then the uploaded shots are not synced on the other profile even if you are logged with the same account.

Also, you can upload shots on both Firefox profiles, but the shots are not synced on the account. Only after you disconnect and log in again.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Screenshots (36.1.0) dev server but is still reproducible following the STR from the first comment. 
@punamdahiya is this issue partially fixed and there is another patch that should be merged in order to fix it?

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean fix of this issue should be reflected in 36.3.0 version

**Comment by punamdahiya** [comment]
With 36.3.0 deployed, this fix should be reflected both in dev and stage. Closing issue as fixed for QA to verify. Thanks!
