### ISSUE TITLE
Persistent download Firefox banner on non-Firefox browsers

### ISSUE THREAD

**Issue by weivicky** [mozilla-services/screenshots#5211]
Posted the issue from my conversation with @johngruen 

I think we already have an existing banner that can be used for download? Maybe we can reuse that.

Also, we can make it dismissible if it's too intrusive and save the user's option like on Slack's.

**Comment by johngruen** [comment]
i think we already have this :)

**Comment by johngruen** [comment]
<img width="1378" alt="screen shot 2018-11-29 at 10 23 30 am" src="https://user-images.githubusercontent.com/3323249/49236853-a7401580-f3c2-11e8-8812-cc98acda78b9.png">

**Comment by johngruen** [comment]
![screen shot 2018-11-29 at 10 36 23 am](https://user-images.githubusercontent.com/3323249/49236955-d3f42d00-f3c2-11e8-918f-13560511625d.png)

**Comment by weivicky** [comment]
Do we have it for all the account related pages :O like would users see it after they login on non-Firefox browser? This is the screenshot I saw from punamdahiya, which doesn't show one.

![image](https://user-images.githubusercontent.com/10877399/49237647-ae6c2100-f3cc-11e8-81eb-3b18d2ee1aa0.png)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
