### ISSUE TITLE
[Edge][Safari] The title of the shot is not changed when pressing the "Enter" key 

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla-services/screenshots#5215]
**[Affected Versions]:**
- Safari 11.0.3
- Microsoft Edge 42.17134.1.0

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- Have a FxA with a saved shot.
- Have a link to the saved shot.

**[Steps to reproduce]:**
1. Open the Microsoft Edge browser and navigate to https://screenshots.dev.mozaws.net.
2. Log in to the FxA and navigate to the saved shot.
3. Click on the title of the saved shot.
4. Change the string from the shot name and press the "Enter" key.
5. Change the string again and press the "Enter" key.
6. Observe the name of the shot.

**[Expected result]:**
- The last string added is displayed.

**[Actual result]:**
- The previous string is displayed.

**[Notes]:**
- This issue is intermittent, in certain cases, the issue is reproducible only after the second changed string or only after a couple of changes.
- This issue is also reproducible on Safari, but it is much harder to reproduce. 
- This issue is reproducible with the stage and dev version of "Screenshots".
- Attached a screen recording of the issue: 

![rec of the issue - this](https://user-images.githubusercontent.com/37875464/48905680-e1f9f900-ee6a-11e8-9963-69b3b1a37bca.gif)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
