### ISSUE TITLE
[Annotations] The entered text slightly moves its position in the text box after the "Confirm" button is clicked

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/screenshots#5217]
[Affected versions]:
- Nightly 65.0a1
- Screenshots 36.1.0 dev and stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots 36.1.0 dev version isntalled from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html).

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a saved shot.
2. Click the "Edit this image" button.
3. Click the "Add text" button.
4. Enter a string in the text box and observe its position.
5. While clicking the "Confirm" button observe the text position in the text box.

[Expected result]:
- The text is correctly displayed and its position was not moved.

[Actual results]:
- The entered text slightly move its position.

[Notes]:
- This issue is also reproducible on non-Firefox browsers.
- Here is a screen recording of the issue:

![text changes](https://user-images.githubusercontent.com/26000308/48952581-5ad08200-ef4b-11e8-917c-8533587eb3d3.gif)

**Comment by punamdahiya** [comment]
A slight shift in text is known issue in production as discussed in https://github.com/mozilla-services/screenshots/issues/4620

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
