### ISSUE TITLE
[FxA] The account's avatar is not displayed on "Settings" page, on stage server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5223]
[Affected versions]:
- Nightly 65.0a1
- Screenshots 36.3.0 stage

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots 36.3.0 stage version installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html).
- Have at least one shot uploaded.
- You are not logged in.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to https://screenshots.stage.mozaws.net/settings.
3. Log in with a valid FxA account.
4. Observe the "Firefox Account" section from the "Settings" page. 

[Expected result]:
- The account's avatar is displayed under the "Firefox Account".

[Actual results]:
- The account's avatar is not displayed.

[Notes]:
- The issue is not reproducible on Screenshots dev version.
- On non-Firefox browser, the border's avatar is displayed but the avatar looks broken.
- Here is a screen recording of the issue:
![fxa avatar](https://user-images.githubusercontent.com/19226534/49081507-c66a6600-f24f-11e8-9a83-05d5898b8c65.gif)

**Comment by punamdahiya** [comment]
On stage default profile picture returned by FxA oauth API is

https://firefoxusercontent.com/00000000000000000000000000000000

On dev server it's
https://stable.dev.lcip.org/profile/a/00000000000000000000000000000000

**Comment by punamdahiya** [comment]
https://firefoxusercontent.com/00000000000000000000000000000000 when used as src for img tag here https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/settings/view.js#L55, fails to load image in dev, stage and prod server. It works on localhost and seems to be a permission issue
