### ISSUE TITLE
Not working on https://www.dropbox.com/

### ISSUE THREAD

**Issue by def00111** [mozilla-services/screenshots#5234]
It will not work on this page:
https://www.dropbox.com/help/security/enable-two-step-verification

**Comment by ianb** [comment]
This appears to be the same issue as #4924 – the page is specifically changing the iframe we use, which blocks Screenshots from working. We aren't able to fix this until [Bug 1340930](https://bugzilla.mozilla.org/show_bug.cgi?id=1340930) happens (and it's unclear when if ever that bug will be fixed).
