### ISSUE TITLE
Explicitly opt-in Screenshots for private browsing mode 

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5244]
Mozilla will be defaulting webextensions to disabled in private browsing mode in 66. See the list posting for more details and history: https://mail.mozilla.org/pipermail/firefox-dev/2018-December/006917.html

We already did some work to detect PBM and disable uploads in that case. We just need to twiddle some manifest keys to keep Screenshots working in PBM.

**Comment by ianb** [comment]
I think we'll have to followup with @mixedpuppy, as it doesn't look like any add-ons will be automatically enabled in private browsing. But I'm not entirely clear on it.
