### ISSUE TITLE
American flag in shot title is corrupted

### ISSUE THREAD

**Issue by kootoopas** [mozilla-services/screenshots#5246]
**Environment**
Ubuntu 18.04, Latest Firefox Nightly

![image](https://user-images.githubusercontent.com/601001/50306150-6dcc6880-049d-11e9-8d48-5cbf4aa97bf7.png)
Link to html: https://screenshots.firefox.com/ZMWQmOw9oONGNmpn/twitter.com

As I type this I realize that it's probably an emoji with font-weight display issue.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
