### ISSUE TITLE
Improve export

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5249]
Right now our only export process is Save As on My Shots. And My Shots is paged, so people with lots of shots (of which there are a few) will have a tedious time of it.

We'll have to think about this a bit. Creating a zip file would be nicest, but is kind of annoying to handle on the server (a file takes a while to create, and then we'd have to store it until the user downloads it, and other complicated things). Maybe Save As is enough, if we increase the number of shots on a page. Or we could create something *like* My Shots, but with instructions inline, and good filenames on all the shot images, and then still use Save As to handle the downloading.

The extension download API isn't all that great, so I don't think extension support will help us much.

Note we don't need UX to start, as we first have to determine what's usable and reasonable to implement from an engineering perspective.

**Comment by 6a68** [comment]
Yeah, I definitely think increasing the My Shots shots-per-page from 10 to 100, then directing users to Save As... for mass exports, seems like the lowest-effort approach :+1:
