### ISSUE TITLE
Add API endpoint for extension to query on usage

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5251]
We want the extension to be able to check if the user needs special notification about the server going away.

We should make an endpoint at `/api/check-usage` which will return a JSON object with:

```json
{
  "hasIndefiniteShots": true/false,
  "hasExpiringShots": true/false
}
```

Obviously this endpoint will require authorization.

**Comment by 6a68** [comment]
Similar to my comment in #5260, adding an endpoint seems unnecessary. If they have authed before, we'll have a locally-stored device ID. We can just show those users a message with updates about screenshots, whether that's opening a tab to the Screenshots website on upgrade, or showing them a modal next time they try to take a screenshot.
