### ISSUE TITLE
Query user status from server

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5260]
We want to know if a user needs notification about the server status. We should query the status (using #5251) and decide if the user:

1. Is using the server, and has shots with indefinite expiration
2. Is using the server, but all shots would normally expire
3. Has not used the server, or all shots are expired

**Comment by 6a68** [comment]
Do we really need to check the state with the server? Seems like the addon could just show one catch-all message in a modal when the user starts taking a shot, and set some local storage state when the user clicks the "OK, I understand" button
