### ISSUE TITLE
Turn down GA metrics

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5264]
Note that once the server is gone we'll have to completely remove these metrics.

@johngruen wants to consider keeping some of these metrics, instead of simply turning metrics off entirely. This is assigned to him to determine exactly what metrics we want to keep (or, e.g., turn down to 1% of users).

**Comment by 6a68** [comment]
Would keeping metrics require moving them to telemetry, and doing a privacy / data review?

**Comment by ianb** [comment]
We're going to go down to 10% of users sending information to GA
