### ISSUE TITLE
Add incognito key to manifest?

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#5279]
Webextensions will soon (firefox 66) be disabled by default in private browsing windows, instead of enabled by default. To keep Screenshots working in private windows, we'll need to add the [`incognito` key](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) to the manifest. (I think it needs to be set to `spanning` to work in both modes?) More details [here](https://mail.mozilla.org/pipermail/firefox-dev/2018-December/006917.html).

Not sure if this applies to system addons / privileged addons in the same way as third-party webextensions, but we should talk to mixedpuppy and land any necessary changes before the next export.

**Comment by ianb** [comment]
Fixed in  #5294
