### ISSUE TITLE
If you have at least one shot uploaded, the "My Shots" button and the "Screenshots" button from the Library menu are not displayed for 10 seconds after each Firefox restart

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5322]
[Affected versions]:
- Firefox 66.0a1
- Screenshots 36.0.0 dev version

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Screenshots dev version installed on a Firefox profile.
- Have at least one shot already uploaded.

[Steps to reproduce]:
1. Open Firefox browser from prerequisites and navigate to any website.
2. Wait more than 10 seconds and restart the browser.
3. Click the "Take a Screenshot" button from "Page Actions" menu and observe the overlay.
4. Click the "Library" button from browser toolbar and observe displayed menu.

[Expected result]:
Step 3: The "My Shots" button is displayed in the top right corner of the Screenshots overlay.
Step 4: The "Screenshots" button is displayed on the menu.

[Actual result]:
Step 3: The "My Shots" button is not displayed in the top right corner of the Screenshots overlay.
Step 4: The "Screenshots" button is not displayed on the menu.

[Notes]: 
- The buttons are displayed only after 10 seconds have passed after each restart.
- Here is a screen recording with the issue:
![my shots and screenshots butttons](https://user-images.githubusercontent.com/19226534/51335661-4dd39900-1a8b-11e9-8ba8-976d5e5294b5.gif)

**Comment by ianb** [comment]
We're going to leave this as-is, though some other issues (like #5332) might improve the time a bit on second startup. We're waiting a few seconds at startup to check the server, so we don't pile onto other Firefox startup activities, and we want to leave it that way.
