### ISSUE TITLE
The "hosting-shutdown" page is not triggered if you don't have any shots uploaded but you are logged in with a FxA account that contains at least one shot that never expires

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5323]
[Affected versions]:
- Firefox 66.0a1
- Screenshots 36.0.0 dev version

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have an older Screenshots dev version installed on a Firefox profile.
- Have no shots uploaded.
- You are logged with a FxA account that contains shots that never expire.

[Steps to reproduce]:
1. Open Firefox browser from prerequisites and navigate to https://screenshots.dev.mozaws.net/homepage/install-test-local.html.
2. Install the latest Screenshots dev version.
3. Wait 10 minutes and observe the behavior.

[Expected result]:
- The "hosting-shutdown" page is opened in a new tab.

[Actual result]:
- The "hosting-shutdown" page is not triggered.

[Notes]: 
- Also, the "My Shots" button and the "Screenshots" button from the Library menu are no longer available.
- I haven't managed to make a screen recording since I have to wait 10 minutes in order to verify if the page is triggered.

**Comment by ianb** [comment]
We've decided not to fix this issue, users would have to have a bunch of specific steps in order to get into this situation (including not using the browser profile where indefinite shots were originally made).
