### ISSUE TITLE
No way to change expiry in the UI

### ISSUE THREAD

**Issue by SRGOM** [mozilla-services/screenshots#5345]
I have some really old shots too so I assume the 'unlimited' expiry still stands, how do I change my new shots to expire 'never'?

**Comment by ianb** [comment]
We've made changes to "favoriting" sets a shot not to expire, but that requires logging in with your Firefox Account. But unfortunately Mozilla has also decided [to retire the server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/) so all shots will be going away sometime this summer :(
