### ISSUE TITLE
The "hosting-shutdown" page is not localized in the supported languages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5360]
[Notes]:
- I have observed in the Github repository that the strings are localized on several locales, but it seems that some tests failed in circle CI and probably that is why are not yet localized.

[Affected versions]:
- Firefox 67.0a1
- Screenshots 38.0.0 stage version

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a German Nightly (67.0a1) build installed or extracted.
- Have an older Screenshots stage version installed.
- Have at least one shot uploaded.
- You are logged with a FxA account that contains shots that never expire.

[Steps to reproduce]:
1. Open Firefox browser from prerequisites and navigate to https://screenshots.stage.mozaws.net/homepage/install-test-local.html.
2. Install the latest Screenshots stage version and restart the browser.
3. Wait ~ 10 seconds and observe the "hosting-shutdown" page.

[Expected result]:
- The "hosting-shutdown" page is displayed in German.

[Actual result]:
- The "hosting-shutdown" page is displayed in English

[Additional Notes]: 
- Here is a screenshot with the issue:
![scr german](https://user-images.githubusercontent.com/19226534/53251761-111c4280-36c6-11e9-9b15-2bcce613b06b.png)

**Comment by ianb** [comment]
Thanks for noticing this. I merged a PR with a string *just* before creating 38.0.0 and localizers didn't have a chance to work on it. I've created 38.1.0 that basically just includes locale updates, and it fixes this issue.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Screenshots (38.1.0) version on the latest Nightly 67.0a1 build, and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.14 and Arch Linux.
