### ISSUE TITLE
The "hosting-shutdown" page is not trigger after installing the latest Screenshots version and then you login with a FxA account that contains indefinitely shots

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5361]
[Affected versions]:
- Nightly 67.0a1
- Screenshots 38.0.0 stage version

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have an older Screenshots stage version installed on a Nightly profile.
- Have at least one shot uploaded.

[Steps to reproduce]:
1. Open Nightly browser from prerequisites and navigate to https://screenshots.stage.mozaws.net/homepage/install-test-local.html.
2. Install the latest Screenshots stage version.
3. Navigate to https://screenshots.stage.mozaws.net/ and login with the FxA account from prerequisites.
4. Restart the browser and wait ~15 seconds.

[Expected result]:
- The "hosting-shutdown" page is opened in a new tab.

[Actual result]:
- The "hosting-shutdown" page is not triggered.

[Notes]: 
- Here is a screen recording with the issue:

![trigger](https://user-images.githubusercontent.com/19226534/53256735-39f60500-36d1-11e9-9409-f23af79ed7eb.gif)

**Comment by ianb** [comment]
We've decided not to fix this issue (and the related #5323), users would have to have a bunch of specific steps in order to get into this situation (including not using the browser profile where indefinite shots were originally made).
