### ISSUE TITLE
Heart/Unexpiry is missing

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-services/screenshots#5369]
Now suddenly the Heart/Unexpire option is missing. I know it was working yesterday in an older version of Firefox and then when I found out about the planned closure, I wanted to see if there if were was any info in the newest Nightly, so I logged in there,  and since then it's missing nor is it there with a new account. Can you at least restore that option until the download/it's closer to export time?

**Comment by Darkilen** [comment]
I can confirm, Heart/Unexpiry button is missing since 7 days.
