### ISSUE TITLE
Login/Account isssues

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-services/screenshots#5370]
Also, I thought I was supposed to be able to access my shots through my Firefox account, but I don't seem to be able to at all. When I try to log in to my account that has several unexpired shots in it on other, newer Firefox versions,  I never get them, even though they are associated with my account in an older Firefox version on another profile. On that version, the same one I created them on, I am never getting any notification that there is a shutdown happening and would have had no idea if I hadn't stumbled on it by accident.

**Comment by ianb** [comment]
I'm sorry this was unclear. A notification will go up on all pages soon, so far we've only sent proactive notifications to Firefox Nightly users in some circumstances, but as the Firefox release goes into beta/release this should be something everyone will see.

**Comment by newsjunkie247** [comment]
It should also be visible to people using older/alternative Firefox versions, not just if you happen to be using the the newest version. Unfortunately I think you're going to get more upset users once this becomes more widely known.
