### ISSUE TITLE
Screenshot of Bugzilla page does not capture whole page

### ISSUE THREAD

**Issue by emceeaich** [mozilla-services/screenshots#5394]
STR

1. Go to a report page in Bugzilla that is longer than window height such as https://bugzilla.mozilla.org/page.cgi?id=triage_owners.html&product=&owner=jmathies%40mozilla.com%2C+
2. Select screenshot from awesomebar menu
3. Select full page

Expected result: 

Full page screen shot

Actual result: 

![Screenshot truncated at bottom of viewport](https://user-images.githubusercontent.com/10146300/65808860-40a79780-e14c-11e9-940c-b14ead9bde7a.png)

**Comment by jscher2000** [comment]
This is caused by style rules fixing the height of the page to the height of the viewport. The rules are somewhat idiosyncratic, so it would be difficult to code a universal override.

**Comment by emceeaich** [comment]
I'll file a bug in our bugzilla.mozilla.org component on Bugzilla.

**Comment by emceeaich** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1586640
