### ISSUE TITLE
Pounce mode

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#54]
When the first visitor arrives at a page marked for pounce, the author gets an immediate notification.  One heuristic for pounce is that when you have a shot page open, and the first person other than you arrives, you get a notification.

Put up a blocking/modal query when the person arrives.  The question would move aside once confirmed.  Now the person definitely knows why they are being asked to look at this.

The question would become part of the copied version of the page.

**Comment by ianb** [comment]
Perhaps share links should be different in the case of a pounced link – it's something that would be nice to know when you click on the link, that you'll be watched.  Doesn't work with adding pounce mode to an existing link (which might be the most common flow).

**Comment by johngruen** [comment]
Closing this issue, will reopen with more relevant deetz
