### ISSUE TITLE
"404 Not Found" error is received when navigate to "shots" or "export" pages on stage server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5421]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Nightly 72.0a1 try build

[Prerequisites]:
- Have a [Nightly try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=45f5dcfda2dac6f95fae67e0a9d43b49715035ba) that uses the stage static server.
- Have the Network Monitor console opened (Ctrl+Shift+E).

[Steps to reproduce]:
1. Open the Nightly try build and navigate to "https://screenshots.stage.mozaws.net/shots" page.
2. Refresh the page.
3. Observe the Network Monitor console.

[Expected result]:
- No 404 status code is displayed

[Actual result]:
- A 404 status code is displayed for the "shots" file of the "screenshots.stage.mozaws.net" domain.

[Notes]:
- The issue is also reproducible when navigating to the "https://screenshots.stage.mozaws.net/export" page.
- Attached a screen recording with the issue:
![404](https://user-images.githubusercontent.com/19226534/69733907-c8068c80-1136-11ea-8226-4dae008a1fd1.gif)

**Comment by ianb** [comment]
This is expected, we're going to just turn off all of it at this point (since there's been deprecation warnings for a long time).
