### ISSUE TITLE
Design oembed

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#585]
We need to think about what the rich widget will be like when we support oembed (per #176)

An example is Twitter, which looks like:

![screen shot 2015-07-16 at 6 42 54 pm](https://cloud.githubusercontent.com/assets/44390/8736881/7ecc504e-2bea-11e5-9e94-1bf68a82af96.png)

**Comment by brampitoyo** [comment]
![pageshot-oembed](https://cloud.githubusercontent.com/assets/51007/8795013/29f25248-2fdd-11e5-8a0e-54a15b388570.png)

**Comment by ianb** [comment]
Header has the og:site_name or else the domain name.  We'll try the middle bottom example from above

**Comment by fzzzy** [comment]
Let's go with the 5th design in the image

**Comment by ianb** [comment]
Test with http://iframely.com/debug (having made your server public, e.g., with http://localtunnel.me/)

**Comment by ianb** [comment]
I now [question whether anyone uses oembed](https://en.wikipedia.org/wiki/OEmbed#oEmbed_Clients)
