### ISSUE TITLE
Consider Cloud app’s annotation feature

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/screenshots#651]
![unnamed](https://cloud.githubusercontent.com/assets/51007/9051781/a282d328-3ab3-11e5-8af2-197306a3d0a8.gif)

**Comment by ianb** [comment]
Just looking at this animation is a little painful for me ;)

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/13oKcu3Xji8vvyNVsnzRO9DB3F6QPNtbm02X4LgTibtQ/edit)
