### ISSUE TITLE
Check out TinyGrab

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#686]
[TinyGrab](http://tinygrab.com/) "social screenshot sharing: Take a screenshot and share it with your clients or friends in less time than it took you to read this sentence!"

**Comment by brampitoyo** [comment]
Mac workflow:
* <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>4</kbd>
* System puts screenshot as a file on desktop

TinyGrab workflow:
* <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>4</kbd>
* System puts uploads screenshot to cloud

It seems that what TinyGrab does is ‘hijack’ the existing keyboard shortcut and put an uploader app at the end.

Cloud App does exactly the same thing as TinyGrab, but with a different shortcut: <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>7</kbd>

**Comment by ianb** [comment]
Filed in [gdocs](https://docs.google.com/document/d/1zbxaXlrcRTCgoXfNbGZDClGj_tesV5Ivz-P1HGDkD6M/edit)
