### ISSUE TITLE
Check how referrer information is sent

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#740]
We should make sure that the URL can't leak in the referer header.

**Comment by ianb** [comment]
IE doesn't support the [referrer meta tag](http://caniuse.com/#feat=referrer-policy).  Maybe we need a redirector.

**Comment by fzzzy** [comment]
A redirector isn't enough. Browsers still send the original referrer.

**Comment by fzzzy** [comment]
Using javascript to do the redirect does work.

**Comment by jvehent** [comment]
Reopening this, as the mitigation ended up creating an open redirect, which is undesirable in firefox.com domains.

I'm failing to understand the value of hiding the referer to the original domain. The URL was generated by that domain anyway, so what are we protecting against by hiding the screenshot url from the original domain?

**Comment by ianb** [comment]
This ticket is a bit old, but for the record we are now using `rel=noreferrer` on this link and no redirector.
