### ISSUE TITLE
FxA web login

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#763]
We need to do a login through the web, not just through the addon.  This is because we want to make people login before installing the addon (though also for other future reasons).

**Comment by ianb** [comment]
I don't think this is necessary at this moment – IdeaTown can do a rough first pass at restricting people, and some follow-up bugs #902 and #903 do the necessary limiting in the add-on and service.

**Comment by johngruen** [comment]
Closing in favor of #3469
