### ISSUE TITLE
"Archive" shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#80]
Sometimes you want to get rid of a shot, but maybe not delete it.  Instead we should just allow "archive".  Its meaning would depend on the context.  On a tag page, the page would retain the tag but it would be marked "archive" in some fashion, so it wasn't shown by default.  On other views it would be a kind of global "archive" flag that would keep it out of all-page queries and the like.

**Comment by johngruen** [comment]
I don't think this is a thing anymore
