### ISSUE TITLE
Localize PageShot with l20n

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#865]
[l20n](http://l20n.org/) is the library Mozilla will be using for its (modern) localization.

**Comment by ianb** [comment]
[Here are some notes](https://bugzilla.mozilla.org/show_bug.cgi?id=1296039#c3) about the preferred localization process.

**Comment by MikkCZ** [comment]
Hi @ianb .

I have just found the news about Page Shot going to be release in Firefox 54. Is localization planned to be enabled in time, so we can make it before the release? I think it would be great to have the strings in the add-on localized.

**Comment by johngruen** [comment]
We are now localized
