### ISSUE TITLE
Export to local files

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#88]
One export mechanism should just create a set of HTML files locally on the computer.  Additionally it might create a bookmark pointing to the head file.

Allowing just some items to be moved locally could be interesting for storage purposes.  A survey of users found many stopped using cloud services when their quota reached its limit.  We could keep metadata in the cloud, but allow for some of the bigger data to be referenced locally.

**Comment by ianb** [comment]
In theory one could even remotely retrieve these locally-stored shots, if the browser was active and online.

**Comment by ianb** [comment]
We might want to look at [MAF/Mozilla Archive Format](http://maf.mozdev.org/)

**Comment by ianb** [comment]
Also [WARC](https://en.wikipedia.org/wiki/Web_ARChive)

**Comment by johngruen** [comment]
@ianb can we close this? IDK what it is

**Comment by ianb** [comment]
The idea was to let you take your uploaded shots (or at the time, entire page archives) and save them locally. We should probably consider exporting from the service sometime, but we can do that in another ticket.
