### ISSUE TITLE
Use npm shrinkwrap

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#910]
npm shrinkwrap helps pin not just the top-level requirements, but all indirect requirements, so everything gets installed correctly.  The [npm-shrinkwrap](https://github.com/uber/npm-shrinkwrap) wrapper might improve on `npm shrinkwrap` as well.

**Comment by ianb** [comment]
[npm-lockdown](https://github.com/mozilla/npm-lockdown) is probably the better thing to use.

**Comment by pdehaan** [comment]
> _npm-lockdown is probably the better thing to use._

I wouldn't recommend lockdown.
I don't think we support it anymore and generally just use vanilla `$ npm shrinkwrap` in our other [FxA-based] projects.

But it should be pretty simple to add a basic package.json script for "shrink" which does something like:

```js
"scripts": {
  "shrink": "rm -rf node_modules npm-shrinkwrap.json && npm install && npm prune && npm shrinkwrap --dev" 
}
```

... Or you could use `npm install --production` and `npm shrinkwrap` above &mdash; or just use the overkill [**npmshrink**](https://github.com/pdehaan/npmshrink) module if that seems like too many steps. Then to purge and regen your dependencies+shrinkwrap, you just need to run `$ npm run shrink` and watch the magic. 🎉

**Comment by ianb** [comment]
We might want to consider yarn per #2430

**Comment by chamini2** [comment]
What about package-lock.json?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).

**Comment by ianb** [comment]
(Note the webextension's dependencies are minimal, so this really only applied to the server.)
