### ISSUE TITLE
Consider Redux

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#947]
Looking at [Redux](https://github.com/rackt/redux) I like the approach, and doesn't feel so far off from what we're doing currenly – single state object, and we modify the state directly but it would be easy to turn that into actions.  Redux is small but may be "complex"; still, seems interesting.

**Comment by fzzzy** [comment]
I like it.

**Comment by fzzzy** [comment]
I spent a few hours investigating this. I like it a lot, but there's a lot to do if we decide to switch to it. We should probably do it later.

**Comment by ianb** [comment]
My feelings towards Redux have become cold and disinterested.
