### ISSUE TITLE
On mobile layout, don’t disable zoom in

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/screenshots#979]
This is because sometimes we get images that are too small to be legible, and we’d like user to be able to zoom into it (instead of relying on them to tap the image to open it in a new tab).

One idea to check out is the PhotoSwipe JS, which provides some of the functionalities that we need without allowing the _entire_ page to zoom in. Just the image.

http://photoswipe.com/

**Comment by ianb** [comment]
It appears we don't allow zoom in: `<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />`

(In `server/src/pages/shot/view.js`)

**Comment by johngruen** [comment]
Fixed
